In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/Taitanic_train.csv")

In [5]:
data['Embarked'].mode()

0    S
Name: Embarked, dtype: object

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mms=MinMaxScaler()
mms_X_train=mms.fit_transform(X_train)
mms_X_test=mms.transform(X_test)
mms_X_train=pd.DataFrame(mms_X_train, columns=X_train.columns, index=X_train.index)
mms_X_test=pd.DataFrame(mms_X_test, columns=X_test.columns, index=X_test.index)

In [ ]:
model=Sequential()
model.add(Input(shape=(mms_X_train.shape[1],)))
model.add

모델의 파라미터 세팅 model.compile()
* loss: 오차 계산 지표
* optimizer: learning_rate
* metrics: 평가지표 accuracy

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
inputs=Input(shape=(mms_X_train.shape[1],))

x=Dense(64, activation='relu')(inputs)
x=Dense(32, activation='relu')(x)
x=Dense(16, activation='relu')(x)

outputs=Dense(1, activation='sigmoid')(x)

model=Model(inputs=inpuuts, outputs=outputs)
model.summary()

In [ ]:
rs=RobustScaler()
train_temp=rs.fit_transform(X_train)
valid_temp=rs.transform(X_valid)
test_temp=rs.transform(X_test)
rs_X_train=pd.DataFrame(train_temp, columns=X_train.columns, index=X_train.index)

In [ ]:
n_class=y_train.shape[1
model=Sequential()
model.add(Input(shape=(rs_X_train.shape[1],)))
model.add(Dense(64, activation='relu')
model.add(Dense()

In [ ]:
import os

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
early_stop=EarlyStopping(patience=100)
os.makedirs("./model", exist_ok=True)
filepath="./model/witewine_loss_{val_loss:.4f}_epoch_{epoch:04d}__.keras"
model_save=ModelCheckpoint(filepath=filepath, save_best_only=True)
history=model.fit(rs_X_train, y_train, epochs=1000, batch_size=32,
                  validation_data=(rs_X_valid, y_valid), callbacks=[early_stop, model_save])



plt.figure(figsize=(8,5))
plt.plot

In [ ]:
model.add(Dense(3, activation='softmax'))

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data=pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/Taitanic_train.csv")
data.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [6]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
data=data[['Survived', 'Pclass','Sex','Age','SibSp','Parch','Embarked']]

In [8]:
data.head()

   Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

In [9]:
data['family']=data['SibSp']+data['Parch']
data

     Survived  Pclass     Sex   Age  SibSp  Parch Embarked  family
0           0       3    male  22.0      1      0        S       1
1           1       1  female  38.0      1      0        C       1
2           1       3  female  26.0      0      0        S       0
3           1       1  female  35.0      1      0        S       1
4           0       3    male  35.0      0      0        S       0
..        ...     ...     ...   ...    ...    ...      ...     ...
886         0       2    male  27.0      0      0        S       0
887         1       1  female  19.0      0      0        S       0
888         0       3  female   NaN      1      2        S       3
889         1       1    male  26.0      0      0        C       0
890         0       3    male  32.0      0      0        Q       0

[891 rows x 8 columns]

In [10]:
data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [11]:
data['Age']=data['Age'].fillna(data['Age'].mean())

In [12]:
data

     Survived  Pclass     Sex        Age  SibSp  Parch Embarked  family
0           0       3    male  22.000000      1      0        S       1
1           1       1  female  38.000000      1      0        C       1
2           1       3  female  26.000000      0      0        S       0
3           1       1  female  35.000000      1      0        S       1
4           0       3    male  35.000000      0      0        S       0
..        ...     ...     ...        ...    ...    ...      ...     ...
886         0       2    male  27.000000      0      0        S       0
887         1       1  female  19.000000      0      0        S       0
888         0       3  female  29.699118      1      2        S       3
889         1       1    male  26.000000      0      0        C       0
890         0       3    male  32.000000      0      0        Q       0

[891 rows x 8 columns]

In [13]:
data['Embarked']=data['Embarked'].fillna(data['Embarked'].mode()[0])

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Embarked  891 non-null    object
 7   family    891 non-null    int64
dtypes: float64(1), int64(5), object(2)
memory usage: 55.8+ KB

In [15]:
data=data.drop(['SibSp','Parch'], axis=1)
data

     Survived  Pclass     Sex        Age Embarked  family
0           0       3    male  22.000000        S       1
1           1       1  female  38.000000        C       1
2           1       3  female  26.000000        S       0
3           1       1  female  35.000000        S       1
4           0       3    male  35.000000        S       0
..        ...     ...     ...        ...      ...     ...
886         0       2    male  27.000000        S       0
887         1       1  female  19.000000        S       0
888         0       3  female  29.699118        S       3
889         1       1    male  26.000000        C       0
890         0       3    male  32.000000        Q       0

[891 rows x 6 columns]

In [16]:
data=pd.get_dummies(data, drop_first=True)
data

     Survived  Pclass        Age  family  Sex_male  Embarked_Q  Embarked_S
0           0       3  22.000000       1      True       False        True
1           1       1  38.000000       1     False       False       False
2           1       3  26.000000       0     False       False        True
3           1       1  35.000000       1     False       False        True
4           0       3  35.000000       0      True       False        True
..        ...     ...        ...     ...       ...         ...         ...
886         0       2  27.000000       0      True       False        True
887         1       1  19.000000       0     False       False        True
888         0       3  29.699118       3     False       False        True
889         1       1  26.000000       0      True       False       False
890         0       3  32.000000       0      True        True       False

[891 rows x 7 columns]

In [17]:
X=data.drop('Survived', axis=1)
y=data['Survived']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# 딥러닝시에도 데이터 스케일을 맞춰 주는 것이 좋음

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [22]:
mms=MinMaxScaler()
mms_X_train=mms.fit_transform(X_train)
mms_X_test=mms.transform(X_test)
mms_X_train=pd.DataFrame(mms_X_train, columns=X_train.columns, index=X_train.index)
mms_X_test=pd.DataFrame(mms_X_test)

# Tensorflow Sequential Api를 사용한 순차적 모델 생성 및 분석

In [23]:
import tensorflow as tf
from tensorflow.keras import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

2025-05-29 06:39:38.567287: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-29 06:39:38.853649: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1748468378.969263     497 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748468379.003583     497 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748468379.248342     497 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748468379.248391     497 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748468379.248393     497 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748468379.248394     497 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-29 06:39:39.269883: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [24]:
model=Sequential()
model.add(Input(shape=(mms_X_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

I0000 00:00:1748468384.938085     497 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1347 MB memory:  -> device: 0, name: NVIDIA GeForce MX450, pci bus id: 0000:01:00.0, compute capability: 7.5

In [26]:
mms_X_train.shape

(623, 6)

# 모델 파라미터 세팅

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

In [ ]:
len(mms_X_train)

# 모델 훈련 modl.fit(X_train, y_train)

In [ ]:
history=model.fit(mms_X_train, y_train, epochs=100, batch_size=16, validation_data=(mms_X_test, y_test))

# 딥러닝 모델 성능 평가

In [ ]:
score=model.evaluate(mms_X_test, y_test)
print('test loss', score[0])
print