In [1]:
import pandas as pd
from sqlalchemy import create_engine

# ── 0. MySQL 접속 ────────────────────
# 실제 접속 정보로 아래 값을 수정하세요.
DB_USER = "dev"
DB_PASS = "pwd"
DB_HOST = "localhost"
DB_PORT = "3307"
DB_NAME = "orders"

engine = create_engine(f"mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

# ── 제외할 customerId 목록 ──────────────────────────────
excluded_ids = [
    '01H8K9XWK972V31SN3HDRGY022','01H7S6309C3ZWPVVMAWDYQDQE9',
    '01H7JEGZX7C0NCPN8ZZ3AJXASE','01H7YB33EPCWHTX1WWA9ANJCPG',
    '01H7VSQW5TB8Q4HR1Z4S5CTJKQ','01H4001EP0F1859987V7D4YJFG',
    '01H8DZZ71SYRKB4868B0WHV68E','01H98VZ8Y98MJ489TEJW7QCDS4',
    '01H7S0P3HK62VATNYDHADQPHKJ','01H9A1GTJVCTA13SA9YPEB9ETA',
    '01H7QY348FZQRVP21JAN8X4Z7R','01H7S9MDFE2FW13DPP93DV0WWP',
    '01H7SVW6ECGZ5JXPSV0YS6P7KG','01H7J0A52BKC867SHMNBZ85XTC',
    '01H847J2DGX5KEKMX386TKYGY1','01H7HNC3GKV65TAG2H3SGW7A0H',
    '01H98W8WA1X2E09TZ50DHHRJSA','01H59HRM9W7WZC0Y0Y5YK4ZJS8',
    '01H7HTY1JNFB3H0MP72X5R4QJW','01H7QXJZ7MQ63FTGJTJ5WB5TFR',
    '01H98VE7QSYH0W7AFH9Z9RY6KZ','01H3ZY9J55GM6S18YQGR3DCGQT',
    '01H8Y02HDQZTAH5AVKP51RN05G','01H847HNN73J8V4DN1V1Z7QJTT',
    '01GZZ0C5HVG9049C8AT5Y96HFS','01H9MSJKX4CCDBG2JK327BSP84',
    '01H9MAY8ZDX7KMFBS7EJYJR5AF','01HFDTAW1QRVR8P1HDKH4CNM47',
    '01HF8FYGWYH8Y27TMDPDAK2MH1','01HDJHZ6WM6QQAG627YQ549S8Z',
    '01HF3DR2VBV3D2M0SB6M32WXHQ'
]
excluded_ids_str = ', '.join(f"'{cid}'" for cid in excluded_ids)

# ── 1. 방문 단위 데이터 (세션별 최초 주문) ────────
query_visits = f"""
    SELECT
        customerId,
        sessionId,
        MIN(storeId)   AS storeId,
        MIN(createdAt) AS createdAt
    FROM orders
    WHERE customerId NOT IN ({excluded_ids_str})
    GROUP BY customerId, sessionId
"""
visits = pd.read_sql(query_visits, engine, parse_dates=["createdAt"])

# ── 2. 고객 × 매장 단위 방문 분석 ─────────────
def avg_interval(series):
    if len(series) < 2:
        return None
    s = series.sort_values()
    return (s.diff().dt.total_seconds() / 86_400).mean()

agg = (
    visits.groupby(["customerId", "storeId"])
          .agg(visit_count=('createdAt', 'size'),
               first_visit=('createdAt', 'min'),
               last_visit=('createdAt', 'max'),
               avg_revisit_days=('createdAt', avg_interval))
          .reset_index()
)

# ── 3. 주요 매장 선정 (방문 수 최다) ─────────────
top_idx = agg.groupby("customerId")["visit_count"].idxmax()
main_store = (
    agg.loc[top_idx]
       .rename(columns={"storeId": "main_storeId",
                        "visit_count": "main_store_visits",
                        "avg_revisit_days": "main_store_avg_revisit_days"})
)

# ── 4. 고객 요약 테이블 ────────────────────
summary = (
    visits.groupby("customerId")
          .size()
          .reset_index(name="total_visits")
          .merge(main_store, on="customerId")
          .sort_values("total_visits", ascending=False)
          .reset_index(drop=True)
)

# ── 5. 결과 확인 ────────────────────────
display(summary.head(50))

,customerId,total_visits,main_storeId,main_store_visits,first_visit,last_visit,main_store_avg_revisit_days
0,01GYNFXQNDD0ATWHDFXCBHD5XG,626,3,456,2023-08-10 11:03:30.813545,2023-09-20 10:55:08.505207,0.090097
1,01JMYTEJKA4YKPEYRZMHQ5CDXH,104,10011,79,2025-03-01 03:18:25.597374,2025-03-24 08:41:44.640538,0.297750
2,01HJSQYASPCWZ1P0ZM9JE85AV0,77,16,22,2024-01-03 02:59:56.078862,2024-05-02 02:30:37.493148,5.713316
3,01J4GEK224ASG6SP8Y6292G6GF,73,10029,53,2024-08-05 09:15:52.906374,2024-10-11 00:43:43.407217,1.281622
4,01JASB86MWHHQ6JBR7X7RNVTM5,64,10066,14,2025-05-02 06:51:41.505473,2025-05-02 08:53:25.162228,0.006503
5,01HMD870VA0J7MH5BZDYB6MDHX,63,10,26,2024-01-24 03:06:38.802240,2024-05-02 02:46:01.185533,3.959427
6,01JAQ39RK68Q5Z14Z3KF6HNMPR,63,10006,27,2024-10-21 08:44:24.685268,2025-02-04 00:45:44.537988,4.064138
7,01HMWHSV1Q4JV0M35CDAQM9WAN,60,16,21,2024-01-24 01:34:50.683867,2024-04-19 03:18:03.917205,4.303584
8,01HJT1EESSP7KAK3PZ1DZT85YS,58,3,58,2023-12-29 05:40:31.260502,2025-02-15 06:05:38.463367,7.263464
9,01HYCV37GAEZAMJJS6HT3N961X,52,3,28,2024-05-21 05:48:25.514666,2024-05-22 12:23:30.971184,0.047199
10,01HK94YZDDWY6SA42M5SV9EZT8,51,16,20,2024-01-04 02:32:08.744234,2024-04-23 02:07:23.431782,5.788569
11,01JR4YRCW1XC0QE1FFDPAQ2PS3,48,10028,48,2025-04-06 07:06:36.835488,2025-05-09 11:36:21.979392,0.706113
12,01HMWP1YJVQ56A4H4Z11XHNRGS,47,10,19,2024-01-24 02:51:47.933021,2024-03-28 02:42:45.385677,3.555207
13,01HQ9PT1B3E7MX4DA5HPBFKC2X,44,10006,15,2024-03-27 01:02:01.384850,2024-11-06 09:37:35.087619,16.025573
14,01HNH8MKQV48TQ4WH18N9REM09,42,16,22,2024-02-01 02:40:47.982804,2024-04-12 02:33:46.760006,3.380720
15,01HJ543YMHXJ29JN6RPRERREWV,42,16,14,2024-01-08 02:43:57.632276,2024-04-08 01:25:17.618744,6.995798
16,01HRNQKH37GKT8P3YK9356VXSX,40,10,27,2024-03-11 03:05:53.848692,2024-04-26 03:02:09.220848,1.769131
17,01HKBFW0G850Z36GT72P1Z508P,39,10,12,2024-01-05 00:21:40.074039,2024-04-26 02:48:19.946693,10.191077
18,01JN85C33A4HSRR9YCSQ2DZ49J,39,10036,38,2025-03-01 06:13:25.093954,2025-03-22 12:22:13.199764,0.574490
19,01HRR9GE711J3JYA9PJ8593ZYC,39,16,14,2024-03-12 02:57:59.649917,2024-04-12 02:08:27.339277,2.381969
20,01JS44S2CCQ82RAY5TYBXGX7ZJ,37,10054,20,2025-04-18 09:48:34.750903,2025-04-18 09:51:41.276974,0.000114
21,01H8NBTC7ECMG8GNQX6F7NS657,37,3,37,2023-08-25 03:29:00.012902,2024-06-19 03:40:06.590331,8.305770
22,01HWYJ7K2C3WJ9CX480YT9SSRV,37,10000,14,2024-06-03 12:06:30.222773,2024-07-12 08:18:29.103010,2.987820
23,01HM84HDJD0Z362Y28P60DGV02,36,10,16,2024-01-16 03:20:02.706573,2024-04-29 02:57:54.699506,6.932309
24,01JS43G4Y4VFSEKJ6SKJD0F3XA,36,10054,17,2025-04-18 09:28:23.701143,2025-04-19 05:10:15.115733,0.051296
25,01JS1HYERDWH23BYGBFRV3EN3T,35,10054,16,2025-04-17 09:40:24.636499,2025-04-24 13:27:41.012520,0.477189
26,01HE36HEG1MRRQFWTNRHT6T4QM,35,11,35,2023-10-31 15:44:52.388570,2023-10-31 15:59:07.752201,0.000291
27,01JKSYCRKQSN8SNNH7CEXW18PR,34,10034,19,2025-02-11 07:25:12.082429,2025-02-11 07:54:43.011932,0.001139
28,01JBBPBETRRCWRHP59Q4NECX2S,34,10007,10,2025-01-09 07:56:53.930247,2025-03-29 02:58:36.052450,8.754761
29,01JS44H313658610SX05F9KKVZ,33,10020,21,2025-04-18 09:43:42.275717,2025-04-18 09:51:09.087165,0.000259
30,01JB629DN8XK7ZX4CSJE0YEZR3,33,10007,11,2024-10-31 08:56:39.920748,2025-03-26 23:15:18.673080,14.659628
31,01JSP53SAEK8QWF1AV1PRHNHBM,32,10054,28,2025-04-25 10:08:18.679191,2025-04-25 10:18:03.004568,0.000250
32,01HG2DPB0C10EERR92W0X4TJ9D,31,9,31,2023-11-25 05:02:01.862582,2024-07-17 04:28:21.372315,7.832554
33,01JS8GYDZQTSF4WHY50KG0A8SF,31,10045,19,2025-04-20 02:38:05.217683,2025-04-20 03:25:48.743277,0.001841
34,01HN5R313JTSG395KH7HYD1JTS,30,10000,12,2024-02-16 10:34:53.065707,2024-03-19 11:02:18.738857,2.910822
35,01H9CY93FVA1J4SA755K6JNAQ8,29,3,12,2023-09-03 07:11:58.286431,2025-01-13 06:18:14.241681,45.269335
36,01J98BNWM5W38SXS3WA9DD56HQ,29,10023,29,2024-10-03 04:54:50.415275,2024-12-26 05:54:41.373359,3.001484
37,01JDY1P290EWY43SKVT23RHREZ,28,10006,9,2024-11-30 08:05:49.704295,2025-03-01 04:29:03.305959,11.356183
38,01HPQZMMFPDWB43J9910F4T71D,28,3,28,2024-02-16 03:34:03.402768,2024-06-07 03:28:10.214935,4.147997
39,01J87GTZW3FZVEHTHEHWF62HBA,27,10028,27,2024-09-20 10:49:37.782954,2025-05-02 10:51:08.824606,8.615425
40,01JB60Y53Z8X2WGE4F24D91ECX,27,10006,13,2024-10-27 03:40:52.342475,2025-03-24 09:32:33.747050,12.353686
41,01HJ2HJ5ZCCENT5G5KYJWMMXFJ,27,16,17,2023-12-20 02:40:04.098496,2024-04-02 02:32:46.556784,6.499683
42,01JB60C3TZMHZ09DJPRV8R45D6,26,10007,12,2024-10-27 03:30:58.823982,2025-01-07 04:51:16.702649,6.550524
43,01H9W8SZ19CAVG54Z4XGR2DWTR,26,5,11,2023-09-23 07:10:22.234626,2025-01-07 05:37:48.978677,47.193573
44,01JDPA7N5349FHRTRJXH1HBM74,26,5,15,2025-03-07 08:22:47.630926,2025-04-15 04:35:03.879813,2.774418
45,01JM3CMP99QS8G8848QWVQ80RG,26,10020,8,2025-02-14 23:28:19.852419,2025-05-02 09:17:30.509255,10.915593
46,01HJSR7BRJDJEXSYFVPFGQAVV0,26,16,23,2023-12-29 02:59:47.415943,2024-04-30 11:34:44.221163,5.607164
47,01HJMKYP0NV486G142EJ05XVP6,26,16,15,2023-12-27 03:21:40.028596,2024-04-23 03:00:35.786905,8.427526
48,01JSRP9FHTFJW2RWYJAH5P65W6,25,10020,25,2025-04-26 09:18:51.412618,2025-04-26 09:25:27.990656,0.000191
49,01JBH01NFQSMFX0YZWXQMNZM15,25,10007,10,2024-10-31 09:55:35.232392,2025-03-03 05:45:04.086038,13.647336

In [2]:
pd.set_option('display.max_rows', None)

In [3]:
summary[
    summary['main_storeId'] == 10028
].head(100)

,customerId,total_visits,main_storeId,main_store_visits,first_visit,last_visit,main_store_avg_revisit_days
11,01JR4YRCW1XC0QE1FFDPAQ2PS3,48,10028,48,2025-04-06 07:06:36.835488,2025-05-09 11:36:21.979392,0.706113
39,01J87GTZW3FZVEHTHEHWF62HBA,27,10028,27,2024-09-20 10:49:37.782954,2025-05-02 10:51:08.824606,8.615425
64,01JKSDCD52SAQ2BFTRDXFPX24F,22,10028,22,2025-02-11 02:28:32.182984,2025-04-24 08:41:30.175039,3.440905
70,01J48NVC08SYZ28MP51PVMC9YX,21,10028,21,2024-08-02 04:33:58.338397,2024-09-30 03:22:05.825727,2.947504
75,01J8EJ7D84PJB5CYZ15XDVFCSC,21,10028,20,2024-09-23 04:28:38.965876,2025-05-12 08:54:55.794928,12.167627
82,01J7CSDEPJ6ZAXJW1KPXKVBTCM,20,10028,20,2024-09-10 01:40:19.831744,2024-09-23 02:36:26.577614,0.686261
83,01J5274R9DXM751GGA8D3JMX8G,20,10028,20,2024-08-12 02:37:12.420777,2024-12-17 10:00:12.272725,6.700402
104,01JJR5VNGYXF49M5TSRQWDBATE,18,10028,16,2024-08-14 02:01:42.912445,2025-01-21 01:47:01.589289,10.665987
123,01JMNNE6KSFFEJEJ20S5Z4G4KG,16,10028,16,2025-02-22 01:48:03.664333,2025-05-10 09:28:45.197610,5.154662
127,01JAC1K3KWPVSHSHV951YJB2W3,16,10028,16,2024-10-17 01:30:31.572569,2024-12-20 04:24:36.417868,4.274726
133,01JG31V4AJY2189MR89YREGF30,15,10028,8,2024-11-13 03:02:18.703744,2025-04-29 05:02:07.316830,23.869029
172,01J90E7D8WDBARJT3JDTHC8QD2,13,10028,13,2024-09-30 03:04:59.506162,2025-03-05 15:27:19.966594,13.042960
177,01J8HHNZG9FZBXGYSMTEND3127,13,10028,13,2024-09-24 08:17:04.565837,2024-11-21 10:38:21.119422,4.841509
195,01JCHNVG8S022S46CYRY4QH29R,12,10028,12,2024-11-13 02:31:59.351429,2024-12-10 04:54:19.247288,2.463531
201,01JFS3964BXRX35DS6YTE7KKH8,12,10028,12,2024-12-23 06:28:51.483916,2025-04-29 01:49:48.373052,11.527838
222,01JAY33R5XQ9A6ZXNY9WF2P81X,12,10028,8,2024-10-24 01:44:11.002804,2025-03-21 13:05:13.195023,21.210420
244,01JQWT6TZZC8ZMTZC3P51SBH76,11,10028,11,2025-04-03 03:12:43.708424,2025-04-28 06:16:58.564123,2.512795
251,01JCA9HPFT3084JMW9310MR28E,11,10028,11,2024-11-10 05:43:01.940077,2025-01-15 01:03:49.889483,6.580611
256,01JNMT2YBEHYJ8NQ377VVSWC2D,11,10028,11,2025-03-06 04:05:44.979583,2025-05-11 02:42:48.008951,6.594240
280,01JM40WGE0BVR8NZET7KXK1ND5,10,10028,10,2025-02-15 05:21:46.971536,2025-03-21 05:52:21.362074,3.780137
302,01JM1TXGNGZD6RAPM0VKJCXA18,10,10028,10,2025-02-14 08:58:59.656950,2025-03-26 16:47:06.337062,4.480564
308,01JC7F3B3FPHJJXACZZPSWSN8P,10,10028,9,2024-12-20 11:12:47.901790,2025-04-18 10:52:23.871601,14.873229
311,01JT8C87NQEB9F789EQ9QFJ5KK,10,10028,10,2025-05-02 11:31:18.953216,2025-05-13 07:19:47.540218,1.202815
321,01JAC1PWY4TSDJ8FASZ555PBHX,10,10028,10,2024-10-17 01:33:08.959401,2024-12-17 08:39:46.792454,6.810697
331,01JTCN2201KS7TE5G7071QTKZD,10,10028,10,2025-05-04 03:22:08.021453,2025-05-12 11:22:22.060568,0.925944
333,01JNJJ1PHRWBFMFNWKG4QVP5J4,10,10028,10,2025-03-05 07:06:46.746549,2025-05-05 03:51:55.669218,6.762743
339,01J93EW61P02APN5H1E9JCSHEB,10,10028,8,2024-10-27 05:00:37.284026,2024-12-06 05:48:16.458777,5.719013
349,01J7B2YNQ97V67TNQ2BHH7XCY5,10,10028,10,2024-09-09 09:48:32.387697,2025-01-13 04:32:41.352504,13.975629
352,01JF1K3JEPJ2JX5460Y6EB1G8F,9,10028,9,2024-12-14 03:24:00.429226,2024-12-15 19:59:49.496987,0.211443
354,01JQ5KV4FEASZ5JRQWYVBWA5MP,9,10028,9,2025-03-25 02:58:37.729106,2025-05-05 09:16:06.836355,5.157768
360,01J8MB5XAQ6YZTP7DV9AKSZ186,9,10028,9,2024-09-25 10:17:47.359588,2025-03-19 04:45:59.472711,21.846198
367,01JTD221NBT3Y2J0YAVNBWRBVZ,9,10028,9,2025-05-04 07:09:37.859205,2025-05-10 21:54:47.878701,0.826837
380,01J7B2FN1YSYR34BJZ3PC6EN08,9,10028,9,2024-09-09 09:40:20.183077,2024-11-12 05:51:43.026684,7.980155
381,01JR4VP7CFAD1GB16P1YMB8Y1H,9,10028,9,2025-04-06 06:12:39.673291,2025-05-11 04:35:54.447982,4.366601
383,01JDY1NEBC7W51JGG2ED420516,9,10028,9,2024-11-30 08:05:25.978255,2025-04-26 09:34:17.905122,18.382714
394,01JAPC5KWJ4H50A9CPW78A0D1E,9,10028,9,2024-09-01 07:36:34.328514,2025-02-28 04:32:39.461709,22.484035
395,01J7QAG6MDZHF9ZZXFATF9NQQ1,9,10028,9,2024-09-14 03:51:05.844863,2025-05-09 02:29:08.936947,29.617886
396,01JEMZTSHVATNH6J3MBHS14MH0,9,10028,9,2024-12-09 05:56:01.587958,2025-04-21 07:42:03.709373,16.634204
468,01J8Y2EH3DW8K2YP0K0B4KSTSR,8,10028,8,2024-09-29 05:00:59.408436,2024-10-14 10:43:37.162458,2.176848
475,01JPSEBNCJRDK7H4FDGE6KYNBF,8,10028,8,2025-03-20 09:32:41.785753,2025-04-20 23:55:47.896002,4.514197
478,01JS1KB7WW5G4ZJPVX1HQXX85D,8,10028,8,2025-04-17 10:05:09.948419,2025-04-27 16:32:36.729976,1.467009
481,01J7ASSQ9FWBHBWXWEEZV8FCGN,8,10028,8,2024-09-09 07:08:13.770389,2024-09-22 11:02:11.682580,1.880354
482,01JHYCSH6HX49XTDJNWNGFF05Y,8,10028,4,2025-01-19 04:23:02.140615,2025-01-25 09:44:01.809803,2.074304
514,01J7NHNB7RX9YWCY7FS40Q33EM,8,10028,8,2024-09-13 11:17:59.706835,2025-01-16 16:17:31.585960,17.886858
517,01JCCD0880GK6GXF8RQ3P9QS85,8,10028,8,2024-11-11 01:22:04.362841,2025-05-12 03:05:00.482372,26.010212
524,01JNQ5F5ZST3H7BG40415YDH0Q,8,10028,8,2025-03-07 02:02:13.588061,2025-03-08 11:51:36.844180,0.201328
541,01J8Y3JSY64N1G6WPSHXKT1HQB,8,10028,8,2024-09-29 05:20:48.103182,2025-01-26 06:26:53.388382,17.006556
551,01JS0PJPASC8NBYZYD904YVEWG,7,10028,7,2025-04-17 01:42:25.405176,2025-05-12 15:14:40.927250,4.260678
554,01JDE92VVEQGYNS06AD6XNK28T,7,10028,7,2024-11-24 05:07:06.566469,2025-04-30 03:07:35.175500,26.152833
556,01JM6KD1TRYAC9SZJGJC3TANVS,7,10028,7,2025-02-16 05:23:23.521683,2025-02-22 02:09:30.409217,0.977560
564,01JED3C9B9YBM8J7NYN3DZR5TM,7,10028,7,2024-10-10 06:52:59.528889,2024-12-09 05:50:02.360252,9.992714
574,01J95TJAFWZBBTXZWHF4A92EQE,7,10028,6,2024-10-17 08:42:28.154557,2024-10-20 15:00:15.083904,0.652470
578,01JCD29E4WX0JQWX9M7JVMWSAH,7,10028,6,2024-11-11 07:33:33.425667,2025-03-03 20:24:18.910857,22.507050
583,01JT0FC41MK2BWG47EQ8TAPACX,7,10028,7,2025-04-29 09:51:53.721668,2025-05-07 02:01:25.497186,1.278881
595,01JETF4GWSFVVMTWD2FNNHS61D,7,10028,7,2024-10-29 03:36:57.182000,2025-03-27 09:08:00.742343,24.871650
602,01JFPZB4BQZ3FME6YJF1VR1XY1,7,10028,7,2024-09-22 10:55:13.834519,2025-04-12 10:17:58.587182,33.662355
608,01JS48S2A34K697W9CBEEMHFSE,7,10028,7,2025-04-18 10:57:58.167264,2025-05-13 10:16:16.855518,4.161842
610,01JCF1B4SWXJ9G1JQPR2HQXC8H,7,10028,7,2024-11-12 01:55:50.752111,2024-11-16 10:41:46.085388,0.727537
619,01J9XD0NJGPS0N8VYPJ9C9B45C,7,10028,7,2024-10-11 09:01:36.351791,2024-12-18 09:08:32.634483,11.334136
627,01J849CHSVFK6J8KYSM8BX1AFQ,7,10028,7,2024-09-19 04:41:40.849376,2024-11-14 04:44:20.686732,9.333642
629,01JBEMFGB6ZPH4CW8SX4X2HJ4P,7,10028,5,2025-03-30 08:11:21.474849,2025-04-13 12:44:09.771236,3.547362
636,01JD6G63F0XXD2060M07VGB6X0,7,10028,7,2024-11-21 04:37:46.117609,2024-11-22 13:42:16.338550,0.229688
656,01JB5ZJMKSC905W2XYYESVK428,7,10028,7,2024-10-27 03:15:47.220266,2024-10-30 23:37:48.453894,0.641438
660,01JTFD7TV5W1N1A1PN9EBZS6V0,7,10028,7,2025-05-05 05:03:30.701227,2025-05-13 10:23:35.502572,1.370380
673,01J8HM493GTZQCX6VKS7A6YA2C,7,10028,7,2024-09-24 08:59:50.296970,2024-10-15 06:35:53.796992,3.483340
674,01JNWBXJAGC7RBKK0EZM09C4DB,7,10028,7,2025-03-09 02:32:04.199793,2025-03-20 08:49:32.478373,1.877022
696,01JQ177PGRFRPMSX8HBAHS0JB0,7,10028,7,2025-03-23 10:02:07.285633,2025-03-27 14:18:28.526079,0.696337
708,01JN89CR4WQXH58H7A0K0F5KP9,7,10028,5,2025-04-07 03:49:07.920195,2025-04-10 06:36:21.429240,0.779032
711,01JA53KMCVN4BG1D6BBHNC7064,7,10028,7,2024-10-14 08:51:07.387880,2024-11-09 22:49:10.768561,4.430331
716,01JE8GHCFVT06EQ25FTJCQ4JRT,7,10028,7,2024-12-04 09:38:06.492003,2024-12-06 18:39:05.922988,0.395948
751,01JQ5GX8N049PKA5MQMZAJ98TC,6,10028,6,2025-03-25 02:08:08.903659,2025-04-22 05:22:31.761568,5.626997
753,01JECWTR3GPC8G07QQCWPB9R8R,6,10028,6,2024-12-05 09:34:15.880751,2025-02-21 09:11:52.525349,15.596890
765,01J7B21PWHFZX1040G27WFY81P,6,10028,6,2024-09-09 09:32:43.376975,2024-11-17 09:04:42.556215,13.796109
772,01JPBZ3K1578RF0N1WMTV4DFGC,6,10028,6,2025-03-15 03:56:00.976173,2025-03-18 12:47:40.094430,0.673841
775,01JP9A6F8GTA0BD5HKNXPS89V4,6,10028,6,2025-03-14 03:12:06.450921,2025-04-02 05:45:03.826354,3.821244
777,01JP7MQDB6D1QF5YP5VD5T4HZK,6,10028,6,2025-03-13 11:37:38.431248,2025-04-08 12:37:27.838914,5.208309
778,01JP77513N58YT0APNXS6V9CAS,6,10028,6,2025-03-13 07:40:14.195534,2025-05-03 01:36:32.551195,10.149487
779,01JP6WVP793QJ3EGV24Q15ZN29,6,10028,6,2025-03-13 04:40:32.776919,2025-04-30 03:18:57.765434,9.588669
780,01JP4W4A08QZ734NXKYJE4JH94,6,10028,6,2025-03-12 09:37:14.672733,2025-05-10 15:24:18.282347,11.848203
781,01JP27K19XRB1NJR5Y6H9JD4F3,6,10028,4,2025-03-11 09:12:04.029301,2025-05-13 10:27:30.264973,21.017462
784,01JFS1Q2GHMQJRSERKFDATR285,6,10028,6,2024-12-23 05:59:20.798234,2025-01-01 05:39:18.982003,1.797218
785,01JP1JX0VERA1RJJE4YYZ5YBPM,6,10028,6,2025-03-11 03:10:06.165174,2025-04-29 03:35:10.962349,9.803483
788,01JNX79VYARPA4KT24GK21016E,6,10028,6,2025-03-08 09:40:18.845092,2025-03-22 05:39:26.749931,2.766546
789,01JNWDXVGTD42HVW2GSYG4WNV8,6,10028,6,2025-03-09 03:07:10.807751,2025-05-13 23:11:05.011571,13.167209
805,01JN61JFC1YGAYW5ZGJ8EB3W29,6,10028,6,2025-02-28 10:27:57.475758,2025-03-12 08:00:22.250741,2.379502
807,01JF9H2R4ZW6YA9G1988BGXMQ4,6,10028,6,2024-12-17 05:22:18.335244,2024-12-22 18:39:48.583417,1.110764
816,01J11DMXXVRV9P6R1QR5ABQQXB,6,10028,5,2024-10-25 02:30:03.623242,2025-03-16 07:17:24.363146,35.549886
823,01JEW7N57YPKCQF69JBRASXZJD,6,10028,6,2024-10-17 01:33:50.243360,2024-12-20 04:24:43.850449,12.823735
835,01J6P2CJYT4808VRVTBVCSS9VZ,6,10028,6,2024-09-01 05:54:55.411828,2025-04-13 03:16:10.223501,44.777951
837,01JAQ9HMDBTCKJ9Z95HZ5RHTH7,6,10028,6,2024-10-21 10:21:29.612738,2024-12-14 06:59:20.669379,10.771924
849,01J7JQ5ND43HZ2B6DJQAF4AJ58,6,10028,6,2024-09-12 08:56:33.987678,2024-12-14 12:20:54.780512,18.628381
868,01JE56P02T426Y6MDWA2YYWWF9,6,10028,6,2024-12-03 02:47:41.535990,2025-04-25 05:01:37.559245,28.618602
874,01J7MKYXCNXPBME28292ZAHZ3G,6,10028,6,2024-09-13 02:38:31.226274,2024-11-11 13:14:46.295358,11.888368
876,01J7MME4NRJ6JVS5FPNHEYK1SE,6,10028,6,2024-09-13 02:47:14.899906,2024-09-21 01:33:29.127464,1.589755
884,01JQNDCYB5X551F42KVTKZ5JDX,6,10028,6,2025-03-31 06:14:39.234170,2025-04-14 15:11:33.074943,2.874569
892,01J9JB09KTCZ1GDK1ZKR78YX8F,6,10028,6,2024-10-07 01:54:49.813070,2025-04-30 05:06:06.628941,41.026567
897,01JJB864J5SM60DAKS3K4JK06J,6,10028,6,2025-01-19 03:10:51.861106,2025-01-24 04:12:04.448940,1.008501
899,01HFG84R58348JYTYZ7318TBCH,6,10028,5,2025-03-04 10:14:26.667421,2025-04-08 08:35:33.159041,8.732831
915,01J7NDA8R08KMZRTAQ7GAEQ77D,6,10028,6,2024-09-13 10:01:48.756808,2024-09-23 05:16:56.313646,1.960434
922,01J9BAT8KV6G9S5PBSYYH994SH,6,10028,6,2024-10-04 08:37:20.172058,2024-12-04 03:11:53.403417,12.154799

In [4]:
# customers 테이블에서 필요한 컬럼만 불러오기
query_customers = """
    SELECT id AS customerId, fullName, phoneNumber, gender, dateOfBirth, subscribedToSicpamaKakaoChannel, isMarketingAgreed
    FROM customers
"""
customers = pd.read_sql(query_customers, engine)

# summary와 customerId 기준으로 join
customers = customers.merge(summary, on="customerId", how="right")

customers[
    (customers['main_storeId'] == 10028)
].head(100)

,customerId,fullName,phoneNumber,gender,dateOfBirth,subscribedToSicpamaKakaoChannel,isMarketingAgreed,total_visits,main_storeId,main_store_visits,first_visit,last_visit,main_store_avg_revisit_days
11,01JR4YRCW1XC0QE1FFDPAQ2PS3,G***t,None,None,None,0,NaT,48,10028,48,2025-04-06 07:06:36.835488,2025-05-09 11:36:21.979392,0.706113
39,01J87GTZW3FZVEHTHEHWF62HBA,하*우,************2624,male,1999-06-11,0,NaT,27,10028,27,2024-09-20 10:49:37.782954,2025-05-02 10:51:08.824606,8.615425
64,01JKSDCD52SAQ2BFTRDXFPX24F,G***t,None,None,None,0,NaT,22,10028,22,2025-02-11 02:28:32.182984,2025-04-24 08:41:30.175039,3.440905
70,01J48NVC08SYZ28MP51PVMC9YX,G***t,None,None,None,0,NaT,21,10028,21,2024-08-02 04:33:58.338397,2024-09-30 03:22:05.825727,2.947504
75,01J8EJ7D84PJB5CYZ15XDVFCSC,신*준,************6547,male,2001-08-30,0,NaT,21,10028,20,2024-09-23 04:28:38.965876,2025-05-12 08:54:55.794928,12.167627
82,01J7CSDEPJ6ZAXJW1KPXKVBTCM,G***t,**********6340,None,None,0,2024-09-10 01:43:51,20,10028,20,2024-09-10 01:40:19.831744,2024-09-23 02:36:26.577614,0.686261
83,01J5274R9DXM751GGA8D3JMX8G,G***t,**********3522,None,None,0,NaT,20,10028,20,2024-08-12 02:37:12.420777,2024-12-17 10:00:12.272725,6.700402
104,01JJR5VNGYXF49M5TSRQWDBATE,전*구,************7294,male,1985-04-25,1,NaT,18,10028,16,2024-08-14 02:01:42.912445,2025-01-21 01:47:01.589289,10.665987
123,01JMNNE6KSFFEJEJ20S5Z4G4KG,G***t,None,None,None,0,NaT,16,10028,16,2025-02-22 01:48:03.664333,2025-05-10 09:28:45.197610,5.154662
127,01JAC1K3KWPVSHSHV951YJB2W3,이*희,************4302,female,2005-05-06,1,NaT,16,10028,16,2024-10-17 01:30:31.572569,2024-12-20 04:24:36.417868,4.274726
133,01JG31V4AJY2189MR89YREGF30,조*형,************9295,male,1985-02-22,0,NaT,15,10028,8,2024-11-13 03:02:18.703744,2025-04-29 05:02:07.316830,23.869029
172,01J90E7D8WDBARJT3JDTHC8QD2,조*원,************7193,female,2004-10-11,0,NaT,13,10028,13,2024-09-30 03:04:59.506162,2025-03-05 15:27:19.966594,13.042960
177,01J8HHNZG9FZBXGYSMTEND3127,G***t,None,None,None,0,NaT,13,10028,13,2024-09-24 08:17:04.565837,2024-11-21 10:38:21.119422,4.841509
195,01JCHNVG8S022S46CYRY4QH29R,편*원,************2159,female,2004-10-15,0,NaT,12,10028,12,2024-11-13 02:31:59.351429,2024-12-10 04:54:19.247288,2.463531
201,01JFS3964BXRX35DS6YTE7KKH8,안*진,************4365,male,1997-10-10,1,NaT,12,10028,12,2024-12-23 06:28:51.483916,2025-04-29 01:49:48.373052,11.527838
222,01JAY33R5XQ9A6ZXNY9WF2P81X,이*빈,************3373,female,2005-12-22,0,2024-11-06 03:36:11,12,10028,8,2024-10-24 01:44:11.002804,2025-03-21 13:05:13.195023,21.210420
244,01JQWT6TZZC8ZMTZC3P51SBH76,윤*준,************8524,male,2001-11-04,1,NaT,11,10028,11,2025-04-03 03:12:43.708424,2025-04-28 06:16:58.564123,2.512795
251,01JCA9HPFT3084JMW9310MR28E,G***t,None,None,None,0,NaT,11,10028,11,2024-11-10 05:43:01.940077,2025-01-15 01:03:49.889483,6.580611
256,01JNMT2YBEHYJ8NQ377VVSWC2D,G***t,None,None,None,0,NaT,11,10028,11,2025-03-06 04:05:44.979583,2025-05-11 02:42:48.008951,6.594240
280,01JM40WGE0BVR8NZET7KXK1ND5,G***t,None,None,None,0,NaT,10,10028,10,2025-02-15 05:21:46.971536,2025-03-21 05:52:21.362074,3.780137
302,01JM1TXGNGZD6RAPM0VKJCXA18,G***t,None,None,None,0,NaT,10,10028,10,2025-02-14 08:58:59.656950,2025-03-26 16:47:06.337062,4.480564
308,01JC7F3B3FPHJJXACZZPSWSN8P,김*형,************5765,male,2005-04-17,1,NaT,10,10028,9,2024-12-20 11:12:47.901790,2025-04-18 10:52:23.871601,14.873229
311,01JT8C87NQEB9F789EQ9QFJ5KK,노*균,************1686,male,1991-03-22,1,NaT,10,10028,10,2025-05-02 11:31:18.953216,2025-05-13 07:19:47.540218,1.202815
321,01JAC1PWY4TSDJ8FASZ555PBHX,G***t,None,None,None,0,NaT,10,10028,10,2024-10-17 01:33:08.959401,2024-12-17 08:39:46.792454,6.810697
331,01JTCN2201KS7TE5G7071QTKZD,조*근,************8462,male,1979-11-13,1,NaT,10,10028,10,2025-05-04 03:22:08.021453,2025-05-12 11:22:22.060568,0.925944
333,01JNJJ1PHRWBFMFNWKG4QVP5J4,G***t,None,None,None,0,NaT,10,10028,10,2025-03-05 07:06:46.746549,2025-05-05 03:51:55.669218,6.762743
339,01J93EW61P02APN5H1E9JCSHEB,정*희,None,None,None,0,NaT,10,10028,8,2024-10-27 05:00:37.284026,2024-12-06 05:48:16.458777,5.719013
349,01J7B2YNQ97V67TNQ2BHH7XCY5,G***t,None,None,None,0,NaT,10,10028,10,2024-09-09 09:48:32.387697,2025-01-13 04:32:41.352504,13.975629
352,01JF1K3JEPJ2JX5460Y6EB1G8F,G***t,None,None,None,0,NaT,9,10028,9,2024-12-14 03:24:00.429226,2024-12-15 19:59:49.496987,0.211443
354,01JQ5KV4FEASZ5JRQWYVBWA5MP,신*우,************2830,male,2004-03-17,0,NaT,9,10028,9,2025-03-25 02:58:37.729106,2025-05-05 09:16:06.836355,5.157768
360,01J8MB5XAQ6YZTP7DV9AKSZ186,이*웅,************4644,male,2002-10-28,1,NaT,9,10028,9,2024-09-25 10:17:47.359588,2025-03-19 04:45:59.472711,21.846198
367,01JTD221NBT3Y2J0YAVNBWRBVZ,G***t,None,None,None,0,NaT,9,10028,9,2025-05-04 07:09:37.859205,2025-05-10 21:54:47.878701,0.826837
380,01J7B2FN1YSYR34BJZ3PC6EN08,G***t,None,None,None,0,NaT,9,10028,9,2024-09-09 09:40:20.183077,2024-11-12 05:51:43.026684,7.980155
381,01JR4VP7CFAD1GB16P1YMB8Y1H,심*종,************3338,male,1982-08-21,0,NaT,9,10028,9,2025-04-06 06:12:39.673291,2025-05-11 04:35:54.447982,4.366601
383,01JDY1NEBC7W51JGG2ED420516,최*석,************4507,male,1998-12-13,1,NaT,9,10028,9,2024-11-30 08:05:25.978255,2025-04-26 09:34:17.905122,18.382714
394,01JAPC5KWJ4H50A9CPW78A0D1E,성*훈,**********7260,male,1999-06-04,1,NaT,9,10028,9,2024-09-01 07:36:34.328514,2025-02-28 04:32:39.461709,22.484035
395,01J7QAG6MDZHF9ZZXFATF9NQQ1,안*범,************9532,male,1979-02-06,1,NaT,9,10028,9,2024-09-14 03:51:05.844863,2025-05-09 02:29:08.936947,29.617886
396,01JEMZTSHVATNH6J3MBHS14MH0,양*혁,************1813,male,1999-12-05,1,NaT,9,10028,9,2024-12-09 05:56:01.587958,2025-04-21 07:42:03.709373,16.634204
468,01J8Y2EH3DW8K2YP0K0B4KSTSR,G***t,None,None,None,0,NaT,8,10028,8,2024-09-29 05:00:59.408436,2024-10-14 10:43:37.162458,2.176848
475,01JPSEBNCJRDK7H4FDGE6KYNBF,G***t,None,None,None,0,NaT,8,10028,8,2025-03-20 09:32:41.785753,2025-04-20 23:55:47.896002,4.514197
478,01JS1KB7WW5G4ZJPVX1HQXX85D,G***t,None,None,None,0,NaT,8,10028,8,2025-04-17 10:05:09.948419,2025-04-27 16:32:36.729976,1.467009
481,01J7ASSQ9FWBHBWXWEEZV8FCGN,이*윤,************1871,male,1995-03-01,1,2024-09-09 07:10:34,8,10028,8,2024-09-09 07:08:13.770389,2024-09-22 11:02:11.682580,1.880354
482,01JHYCSH6HX49XTDJNWNGFF05Y,G***t,**********5999,None,None,0,NaT,8,10028,4,2025-01-19 04:23:02.140615,2025-01-25 09:44:01.809803,2.074304
514,01J7NHNB7RX9YWCY7FS40Q33EM,G***t,None,None,None,0,NaT,8,10028,8,2024-09-13 11:17:59.706835,2025-01-16 16:17:31.585960,17.886858
517,01JCCD0880GK6GXF8RQ3P9QS85,김*진,************0423,female,2005-04-23,1,NaT,8,10028,8,2024-11-11 01:22:04.362841,2025-05-12 03:05:00.482372,26.010212
524,01JNQ5F5ZST3H7BG40415YDH0Q,김*주,************5376,female,2003-02-18,0,NaT,8,10028,8,2025-03-07 02:02:13.588061,2025-03-08 11:51:36.844180,0.201328
541,01J8Y3JSY64N1G6WPSHXKT1HQB,G***t,None,None,None,0,NaT,8,10028,8,2024-09-29 05:20:48.103182,2025-01-26 06:26:53.388382,17.006556
551,01JS0PJPASC8NBYZYD904YVEWG,G***t,None,None,None,0,NaT,7,10028,7,2025-04-17 01:42:25.405176,2025-05-12 15:14:40.927250,4.260678
554,01JDE92VVEQGYNS06AD6XNK28T,배*영,************3364,female,2005-08-20,1,NaT,7,10028,7,2024-11-24 05:07:06.566469,2025-04-30 03:07:35.175500,26.152833
556,01JM6KD1TRYAC9SZJGJC3TANVS,장*람,************5990,female,1985-07-12,1,NaT,7,10028,7,2025-02-16 05:23:23.521683,2025-02-22 02:09:30.409217,0.977560
564,01JED3C9B9YBM8J7NYN3DZR5TM,정*현,************9494,male,2005-11-24,1,NaT,7,10028,7,2024-10-10 06:52:59.528889,2024-12-09 05:50:02.360252,9.992714
574,01J95TJAFWZBBTXZWHF4A92EQE,G***t,None,None,None,0,NaT,7,10028,6,2024-10-17 08:42:28.154557,2024-10-20 15:00:15.083904,0.652470
578,01JCD29E4WX0JQWX9M7JVMWSAH,신*석,************6295,male,1999-02-14,1,NaT,7,10028,6,2024-11-11 07:33:33.425667,2025-03-03 20:24:18.910857,22.507050
583,01JT0FC41MK2BWG47EQ8TAPACX,전*형,************3973,male,2003-02-23,1,NaT,7,10028,7,2025-04-29 09:51:53.721668,2025-05-07 02:01:25.497186,1.278881
595,01JETF4GWSFVVMTWD2FNNHS61D,진*진,************6417,female,2001-04-17,0,NaT,7,10028,7,2024-10-29 03:36:57.182000,2025-03-27 09:08:00.742343,24.871650
602,01JFPZB4BQZ3FME6YJF1VR1XY1,최*정,************2396,female,2004-08-01,1,NaT,7,10028,7,2024-09-22 10:55:13.834519,2025-04-12 10:17:58.587182,33.662355
608,01JS48S2A34K697W9CBEEMHFSE,이*규,************0716,male,1977-12-03,1,NaT,7,10028,7,2025-04-18 10:57:58.167264,2025-05-13 10:16:16.855518,4.161842
610,01JCF1B4SWXJ9G1JQPR2HQXC8H,G***t,None,None,None,0,NaT,7,10028,7,2024-11-12 01:55:50.752111,2024-11-16 10:41:46.085388,0.727537
619,01J9XD0NJGPS0N8VYPJ9C9B45C,홍*훈,************4268,male,2005-06-24,1,NaT,7,10028,7,2024-10-11 09:01:36.351791,2024-12-18 09:08:32.634483,11.334136
627,01J849CHSVFK6J8KYSM8BX1AFQ,정*기,************6424,male,2004-10-25,0,NaT,7,10028,7,2024-09-19 04:41:40.849376,2024-11-14 04:44:20.686732,9.333642
629,01JBEMFGB6ZPH4CW8SX4X2HJ4P,맘**아,None,male,2002-10-28,0,NaT,7,10028,5,2025-03-30 08:11:21.474849,2025-04-13 12:44:09.771236,3.547362
636,01JD6G63F0XXD2060M07VGB6X0,G***t,None,None,None,0,NaT,7,10028,7,2024-11-21 04:37:46.117609,2024-11-22 13:42:16.338550,0.229688
656,01JB5ZJMKSC905W2XYYESVK428,강*숙,************5690,female,1985-06-15,1,NaT,7,10028,7,2024-10-27 03:15:47.220266,2024-10-30 23:37:48.453894,0.641438
660,01JTFD7TV5W1N1A1PN9EBZS6V0,G***t,None,None,None,0,NaT,7,10028,7,2025-05-05 05:03:30.701227,2025-05-13 10:23:35.502572,1.370380
673,01J8HM493GTZQCX6VKS7A6YA2C,G***t,None,None,None,0,NaT,7,10028,7,2024-09-24 08:59:50.296970,2024-10-15 06:35:53.796992,3.483340
674,01JNWBXJAGC7RBKK0EZM09C4DB,G***t,None,None,None,0,NaT,7,10028,7,2025-03-09 02:32:04.199793,2025-03-20 08:49:32.478373,1.877022
696,01JQ177PGRFRPMSX8HBAHS0JB0,G***t,None,None,None,0,NaT,7,10028,7,2025-03-23 10:02:07.285633,2025-03-27 14:18:28.526079,0.696337
708,01JN89CR4WQXH58H7A0K0F5KP9,G***t,None,None,None,0,NaT,7,10028,5,2025-04-07 03:49:07.920195,2025-04-10 06:36:21.429240,0.779032
711,01JA53KMCVN4BG1D6BBHNC7064,김*원,************0908,female,2000-09-08,1,NaT,7,10028,7,2024-10-14 08:51:07.387880,2024-11-09 22:49:10.768561,4.430331
716,01JE8GHCFVT06EQ25FTJCQ4JRT,G***t,None,None,None,0,NaT,7,10028,7,2024-12-04 09:38:06.492003,2024-12-06 18:39:05.922988,0.395948
751,01JQ5GX8N049PKA5MQMZAJ98TC,G***t,None,None,None,0,NaT,6,10028,6,2025-03-25 02:08:08.903659,2025-04-22 05:22:31.761568,5.626997
753,01JECWTR3GPC8G07QQCWPB9R8R,김*정,************3099,female,1984-03-02,0,NaT,6,10028,6,2024-12-05 09:34:15.880751,2025-02-21 09:11:52.525349,15.596890
765,01J7B21PWHFZX1040G27WFY81P,G***t,None,None,None,0,NaT,6,10028,6,2024-09-09 09:32:43.376975,2024-11-17 09:04:42.556215,13.796109
772,01JPBZ3K1578RF0N1WMTV4DFGC,G***t,None,None,None,0,NaT,6,10028,6,2025-03-15 03:56:00.976173,2025-03-18 12:47:40.094430,0.673841
775,01JP9A6F8GTA0BD5HKNXPS89V4,G***t,None,None,None,0,NaT,6,10028,6,2025-03-14 03:12:06.450921,2025-04-02 05:45:03.826354,3.821244
777,01JP7MQDB6D1QF5YP5VD5T4HZK,G***t,None,None,None,0,NaT,6,10028,6,2025-03-13 11:37:38.431248,2025-04-08 12:37:27.838914,5.208309
778,01JP77513N58YT0APNXS6V9CAS,이*지,************6518,female,2004-04-16,1,NaT,6,10028,6,2025-03-13 07:40:14.195534,2025-05-03 01:36:32.551195,10.149487
779,01JP6WVP793QJ3EGV24Q15ZN29,G***t,None,None,None,0,NaT,6,10028,6,2025-03-13 04:40:32.776919,2025-04-30 03:18:57.765434,9.588669
780,01JP4W4A08QZ734NXKYJE4JH94,최*영,************8387,male,2005-04-01,1,NaT,6,10028,6,2025-03-12 09:37:14.672733,2025-05-10 15:24:18.282347,11.848203
781,01JP27K19XRB1NJR5Y6H9JD4F3,손*범,************7451,male,2006-02-06,1,NaT,6,10028,4,2025-03-11 09:12:04.029301,2025-05-13 10:27:30.264973,21.017462
784,01JFS1Q2GHMQJRSERKFDATR285,이*림,************2734,female,2004-01-08,1,NaT,6,10028,6,2024-12-23 05:59:20.798234,2025-01-01 05:39:18.982003,1.797218
785,01JP1JX0VERA1RJJE4YYZ5YBPM,권*은,************8889,female,2006-10-17,1,NaT,6,10028,6,2025-03-11 03:10:06.165174,2025-04-29 03:35:10.962349,9.803483
788,01JNX79VYARPA4KT24GK21016E,류*성,************0611,male,2006-11-27,1,NaT,6,10028,6,2025-03-08 09:40:18.845092,2025-03-22 05:39:26.749931,2.766546
789,01JNWDXVGTD42HVW2GSYG4WNV8,G***t,None,None,None,0,NaT,6,10028,6,2025-03-09 03:07:10.807751,2025-05-13 23:11:05.011571,13.167209
805,01JN61JFC1YGAYW5ZGJ8EB3W29,G***t,None,None,None,0,NaT,6,10028,6,2025-02-28 10:27:57.475758,2025-03-12 08:00:22.250741,2.379502
807,01JF9H2R4ZW6YA9G1988BGXMQ4,이*현,************5061,male,2001-01-24,1,NaT,6,10028,6,2024-12-17 05:22:18.335244,2024-12-22 18:39:48.583417,1.110764
816,01J11DMXXVRV9P6R1QR5ABQQXB,이*주,************1663,female,2005-12-09,0,NaT,6,10028,5,2024-10-25 02:30:03.623242,2025-03-16 07:17:24.363146,35.549886
823,01JEW7N57YPKCQF69JBRASXZJD,유*정,************5251,female,2005-09-16,0,NaT,6,10028,6,2024-10-17 01:33:50.243360,2024-12-20 04:24:43.850449,12.823735
835,01J6P2CJYT4808VRVTBVCSS9VZ,김*빈,************7279,male,1993-12-23,1,NaT,6,10028,6,2024-09-01 05:54:55.411828,2025-04-13 03:16:10.223501,44.777951
837,01JAQ9HMDBTCKJ9Z95HZ5RHTH7,김*슬,************4524,female,2005-04-24,1,2024-10-21 10:25:13,6,10028,6,2024-10-21 10:21:29.612738,2024-12-14 06:59:20.669379,10.771924
849,01J7JQ5ND43HZ2B6DJQAF4AJ58,G***t,**********5077,None,None,0,2024-09-12 08:57:36,6,10028,6,2024-09-12 08:56:33.987678,2024-12-14 12:20:54.780512,18.628381
868,01JE56P02T426Y6MDWA2YYWWF9,배*나,************1942,female,2004-10-15,0,NaT,6,10028,6,2024-12-03 02:47:41.535990,2025-04-25 05:01:37.559245,28.618602
874,01J7MKYXCNXPBME28292ZAHZ3G,최*렬,************5037,male,1999-06-16,0,NaT,6,10028,6,2024-09-13 02:38:31.226274,2024-11-11 13:14:46.295358,11.888368
876,01J7MME4NRJ6JVS5FPNHEYK1SE,G***t,None,None,None,0,NaT,6,10028,6,2024-09-13 02:47:14.899906,2024-09-21 01:33:29.127464,1.589755
884,01JQNDCYB5X551F42KVTKZ5JDX,G***t,None,None,None,0,NaT,6,10028,6,2025-03-31 06:14:39.234170,2025-04-14 15:11:33.074943,2.874569
892,01J9JB09KTCZ1GDK1ZKR78YX8F,임*준,************5283,male,2002-03-20,0,NaT,6,10028,6,2024-10-07 01:54:49.813070,2025-04-30 05:06:06.628941,41.026567
897,01JJB864J5SM60DAKS3K4JK06J,김*지,************9892,female,2004-08-12,0,NaT,6,10028,6,2025-01-19 03:10:51.861106,2025-01-24 04:12:04.448940,1.008501
899,01HFG84R58348JYTYZ7318TBCH,김*윤,************6727,male,2005-12-01,1,NaT,6,10028,5,2025-03-04 10:14:26.667421,2025-04-08 08:35:33.159041,8.732831
915,01J7NDA8R08KMZRTAQ7GAEQ77D,김*우,************6784,male,1998-01-22,1,2024-09-13 10:06:27,6,10028,6,2024-09-13 10:01:48.756808,2024-09-23 05:16:56.313646,1.960434
922,01J9BAT8KV6G9S5PBSYYH994SH,G***t,None,None,None,0,NaT,6,10028,6,2024-10-04 08:37:20.172058,2024-12-04 03:11:53.403417,12.154799

In [14]:
customers[
    customers['customerId'] == '01JR4YRCW1XC0QE1FFDPAQ2PS3'
]

,customerId,fullName,phoneNumber,gender,dateOfBirth,subscribedToSicpamaKakaoChannel,isMarketingAgreed,total_visits,main_storeId,main_store_visits,first_visit,last_visit,main_store_avg_revisit_days
11,01JR4YRCW1XC0QE1FFDPAQ2PS3,G***t,None,None,None,0,NaT,48,10028,48,2025-04-06 07:06:36.835488,2025-05-09 11:36:21.979392,0.706113

In [6]:
c1 = customers[
    (customers['main_storeId'] == 10028) &
    ~customers['isMarketingAgreed'].isnull()
]
c1

,customerId,fullName,phoneNumber,gender,dateOfBirth,subscribedToSicpamaKakaoChannel,isMarketingAgreed,total_visits,main_storeId,main_store_visits,first_visit,last_visit,main_store_avg_revisit_days
82,01J7CSDEPJ6ZAXJW1KPXKVBTCM,G***t,**********6340,None,None,0,2024-09-10 01:43:51,20,10028,20,2024-09-10 01:40:19.831744,2024-09-23 02:36:26.577614,0.686261
222,01JAY33R5XQ9A6ZXNY9WF2P81X,이*빈,************3373,female,2005-12-22,0,2024-11-06 03:36:11,12,10028,8,2024-10-24 01:44:11.002804,2025-03-21 13:05:13.195023,21.210420
481,01J7ASSQ9FWBHBWXWEEZV8FCGN,이*윤,************1871,male,1995-03-01,1,2024-09-09 07:10:34,8,10028,8,2024-09-09 07:08:13.770389,2024-09-22 11:02:11.682580,1.880354
837,01JAQ9HMDBTCKJ9Z95HZ5RHTH7,김*슬,************4524,female,2005-04-24,1,2024-10-21 10:25:13,6,10028,6,2024-10-21 10:21:29.612738,2024-12-14 06:59:20.669379,10.771924
849,01J7JQ5ND43HZ2B6DJQAF4AJ58,G***t,**********5077,None,None,0,2024-09-12 08:57:36,6,10028,6,2024-09-12 08:56:33.987678,2024-12-14 12:20:54.780512,18.628381
915,01J7NDA8R08KMZRTAQ7GAEQ77D,김*우,************6784,male,1998-01-22,1,2024-09-13 10:06:27,6,10028,6,2024-09-13 10:01:48.756808,2024-09-23 05:16:56.313646,1.960434
964,01J9K3VPW2ENWAJ1B410GCDBGF,박*원,************4919,female,2002-05-30,1,2024-10-07 09:10:48,6,10028,6,2024-10-07 09:09:19.781079,2024-11-04 07:28:59.667266,5.586065
1144,01J4ZZSVJ6HDH8F4FJTJ7PHP85,G***t,**********6709,None,None,0,2024-09-09 03:12:57,5,10028,5,2024-08-11 05:50:26.417109,2024-09-09 03:11:24.497607,7.222390
1378,01JA9QXTN06K5H0GZ7NGPMYNXE,김*준,************3990,male,2004-06-29,1,2024-10-16 04:07:49,5,10028,5,2024-10-16 04:03:26.682643,2024-10-20 04:30:38.713605,1.004722
1453,01J9V12JYSJCD32XP655TEWSZX,윤*수,************6883,male,1999-02-09,1,2024-10-10 10:56:14,5,10028,5,2024-10-10 10:54:37.777245,2024-11-04 11:00:19.177961,6.250988
1566,01J87JT4JBG92W58RFHZ2JBJ2H,김*미,************5489,female,1920-05-11,1,2024-09-20 11:26:23,4,10028,3,2024-09-20 11:24:12.215318,2024-11-17 10:59:57.259286,28.991580
1870,01J9NTXRYR7D595ZB324XF48TT,김*빈,************3852,female,2005-09-08,1,2024-10-08 10:32:59,4,10028,4,2024-10-08 10:31:29.466670,2025-02-28 05:11:49.416615,47.592670
2103,01JAYH736AYB7G9FVMZ0NFSYY3,최*정,************0528,female,2004-05-28,0,2024-10-28 10:30:20,4,10028,4,2024-10-24 05:49:58.610538,2025-03-20 04:25:29.816825,48.980444
2148,01JA23C6CCD8B4MBAD31BZ8FWR,조*이,************5065,female,2001-05-09,1,2024-10-13 04:50:36,4,10028,4,2024-10-13 04:49:39.720021,2025-05-10 06:53:36.378956,69.695357
2242,01JAFBKNA4RY7AN9C9FY4JE79Q,송*준,************7723,male,2000-12-22,1,2024-10-18 08:25:56,4,10028,4,2024-10-18 08:24:01.541162,2025-04-14 07:00:11.913797,59.313929
2489,01JBXVY1Z3S4Y6XX8MF1SS4V0S,조*우,************3770,male,2001-02-23,1,2024-11-05 09:56:33,4,10028,4,2024-11-05 09:53:52.757384,2025-01-21 09:59:19.892629,25.667929
2518,01J821JMP6D21K0PRNAW0K5Z05,지**니,**********8681,None,1982-04-01,0,2024-09-18 07:50:03,3,10028,3,2024-09-18 07:46:18.115610,2024-11-08 03:50:07.257276,25.417993
2875,01J9K4RPFP0GJQMP2NJYPQZV50,G***t,**********3762,None,None,0,2024-11-18 03:00:59,3,10028,3,2024-10-07 09:25:32.836359,2024-11-18 02:58:03.304305,20.865454
3042,01JAHGYND3Z51A9B1XW272J4CJ,이*영,************3080,male,2000-08-05,1,2024-10-19 04:37:13,3,10028,3,2024-10-19 04:35:03.596155,2024-11-26 08:56:43.020727,19.090853
3081,01J6ZWVY598Q0231A15CDM5P01,G***t,**********8997,None,None,0,2024-09-05 01:32:38,3,10028,3,2024-09-05 01:30:32.518773,2024-09-13 16:12:31.925344,4.306247
3174,01J70G6GRWT6Q91RW1XC6G71NQ,G***t,**********4949,None,None,0,2024-09-05 07:10:22,3,10028,3,2024-09-05 07:08:22.223375,2024-09-10 20:29:48.920726,2.778279
3188,01J9NRW899DSXXG2YD0XFMZZWM,G***t,**********5938,None,None,0,2024-10-08 09:57:57,3,10028,3,2024-10-08 09:55:29.741202,2024-10-21 04:40:10.055376,6.390511
3238,01J9QHH0YQBXATBGWJED1B2N6D,G***t,**********7924,None,None,0,2024-11-01 06:12:20,3,10028,3,2024-10-09 02:25:30.636086,2024-11-01 06:20:50.337135,11.581711
3450,01J9T2NB44EG7R1G30E4KD4D68,안*빈,************6003,female,2005-09-30,1,2024-10-10 02:04:24,3,10028,3,2024-10-10 02:02:58.220503,2024-10-11 12:10:09.618116,0.710830
3513,01J77T42E9C139ZTFWADD9K1P5,김*영,************4868,female,1979-11-26,0,2024-09-08 03:21:32,3,10028,3,2024-09-08 03:16:04.883681,2024-11-10 20:55:56.574047,31.868007
3659,01J9WVK4B27ZPE8WPVZHDPRF21,G***t,**********5386,None,None,0,2024-11-21 04:37:34,3,10028,3,2024-10-11 03:57:37.572551,2024-11-21 04:36:24.123723,20.513464
3688,01J8ERZ4WMR2W578Y8SZDJKJ4Y,G***t,**********5581,None,None,0,2024-09-23 06:28:31,3,10028,3,2024-09-23 06:26:41.736103,2024-09-23 23:28:35.034511,0.354822
3769,01JC562YGKFP7QSPCP1DWVVVNN,김*구,************0107,male,1978-02-26,1,2024-11-08 06:10:26,3,10028,3,2024-11-08 06:06:03.750690,2024-11-12 04:20:45.223897,1.963434
3883,01J0JM2DFHVBKZSKHJY53BW8TQ,정*윤,************1807,female,2001-08-25,1,2024-09-09 02:56:24,3,10028,2,2024-09-09 02:53:15.790824,2024-09-09 08:08:29.914430,0.218913
3901,01HBQFZMCNA4CBAXPWPEXVNHFT,김*서,************2370,female,2001-01-19,1,2024-11-14 02:06:27,3,10028,2,2024-11-14 02:03:31.099968,2024-11-14 23:09:15.472914,0.878986
3997,01J8KKGMYJHPYX4DTRJR7BNZ3W,G***t,**********2340,None,None,0,2024-09-25 03:29:18,3,10028,3,2024-09-25 03:27:35.918991,2024-10-02 03:07:52.411129,3.493151
4121,01JC7HJAHSMRZ548MTGPKM6S3Q,G***t,**********3524,None,None,0,2024-11-09 04:08:38,3,10028,3,2024-11-09 04:05:27.780590,2025-01-15 09:09:23.060000,33.605528
4140,01J4P0FPK6RY6X460058QXAQ7N,G***t,**********5177,None,None,0,2024-09-23 09:47:22,3,10028,3,2024-08-07 08:49:57.919232,2024-09-23 09:46:16.210976,23.519550
4152,01J4P57HC7F5QFB15BESCPK2TA,홍*지,************5855,female,1999-10-25,1,2024-09-15 04:16:01,3,10028,3,2024-08-07 10:12:04.849767,2024-12-07 03:09:36.937667,60.853311
4199,01JDE94SDGZGA6ZEMNTCBT6D0E,박*영,************9117,female,2005-07-04,1,2024-11-24 05:12:02,3,10028,3,2024-11-24 05:08:19.737928,2025-01-06 08:22:34.695546,21.567448
4245,01JAWAMW96GMQ26RXZ46SG0SXW,G***t,**********2067,None,None,0,2024-10-23 09:21:41,3,10028,3,2024-10-23 09:17:10.850666,2024-11-10 23:26:11.501216,9.294795
4672,01J672R2JVDM6H86DPEQQJ366W,권*수,************8480,male,2002-04-26,1,2024-08-26 10:15:50,3,10028,3,2024-08-26 10:11:39.634428,2024-11-11 06:03:38.892264,38.413885
4675,01JD65RAZBK03KEQ1G6MB19M4T,이*훈,************7141,male,2004-07-15,1,2024-11-21 01:40:49,3,10028,3,2024-11-21 01:35:09.041361,2024-11-30 03:13:20.951569,4.534097
4683,01J68SJGMN3EQ8TRMD47VVGW48,이*정,************4061,female,1994-06-07,1,2024-08-27 02:12:16,3,10028,3,2024-08-27 02:10:04.130677,2024-09-13 04:11:07.713701,8.542035
4696,01JA7PJK9R85VJFEX6ABM96W4W,박*건,************9377,male,2002-07-04,0,2024-10-15 09:03:27,3,10028,3,2024-10-15 09:01:03.184674,2024-11-25 07:32:52.149311,20.469381
4741,01J6C4GSH2TEFQ16SRMEW09TBP,G***t,**********1855,None,None,0,2024-08-28 09:23:27,3,10028,3,2024-08-28 09:19:27.324417,2024-09-01 05:35:29.194147,1.922233
4757,01J7WMTVYB76NDYM5D2XJPD9RF,김*성,************3982,male,2001-06-30,1,2024-09-16 05:32:49,3,10028,3,2024-09-16 05:27:04.159368,2024-09-25 15:43:39.569964,4.714094
4764,01JA9GC5JKCYZ9Q9EN4F39D623,배*정,************6350,female,2003-12-27,1,2024-10-16 01:52:36,3,10028,3,2024-10-16 01:50:04.997940,2024-12-02 07:23:56.957142,23.615926
4785,01JA9MJ7QTQ661QEX8N1DDH5BV,G***t,**********8891,None,None,0,2024-10-16 03:09:33,3,10028,3,2024-10-16 03:04:55.828759,2024-11-13 18:10:48.651108,14.314542
4790,01J6EWVAPX8E59ERSK1M6QNZB4,G***t,**********8204,None,None,0,2024-08-29 11:05:23,3,10028,3,2024-08-29 11:03:07.270442,2024-09-03 12:00:24.416858,2.519891
5470,01J9K89692FKPXSF473X4MDVHE,G***t,**********8900,None,None,0,2024-10-07 10:29:48,2,10028,2,2024-10-07 10:26:59.010291,2024-10-07 15:28:35.385783,0.209449
5540,01J6Y3MCXN49Z08HK2MXF9QXEB,G***t,**********3861,None,None,0,2024-09-04 08:52:40,2,10028,2,2024-09-04 08:50:16.686686,2024-09-04 11:45:51.420602,0.121930
5819,01J9RD7NRX5C01HYSMWPJZZ42G,G***t,**********6926,None,None,0,2024-10-09 10:36:53,2,10028,2,2024-10-09 10:29:44.401758,2024-10-13 05:10:25.849443,3.778257
5876,01J9T5GDZEZN2NTW9G1GC96G5A,박*영,************3559,female,2005-12-19,1,2024-10-10 02:56:11,2,10028,2,2024-10-10 02:53:23.593841,2024-10-10 23:09:26.694142,0.844480
6053,01J7AGS3DXTWSH5J83YH6ZJWZQ,h*****i,**********0890,female,2001-02-27,0,2024-09-09 04:33:04,2,10028,2,2024-09-09 04:30:21.757075,2024-09-09 04:45:39.319106,0.010620
6068,01J7APQW8SJGKBQGT54HWMSFN0,G***t,**********4223,None,None,0,2024-09-09 06:19:36,2,10028,2,2024-09-09 06:15:06.810645,2024-09-10 01:49:38.481236,0.815644
6132,01J7CVBW9JJ3FD8KBJ2F20QQSY,진*수,************4356,male,2001-03-31,1,2024-09-26 07:35:49,2,10028,2,2024-09-10 02:14:40.854863,2024-09-26 07:34:10.609142,16.221872
6134,01J7CVS3KGSSEX2N3BPM6VA0FQ,G***t,**********6090,None,None,0,2024-09-10 02:23:36,2,10028,2,2024-09-10 02:21:38.842315,2024-09-10 13:00:36.364601,0.443721
6151,01J7CXY9472VSABY6HZ8H88SY0,G***t,**********5981,None,None,0,2024-09-10 03:02:24,2,10028,2,2024-09-10 02:59:25.491982,2024-09-10 14:03:09.851571,0.460930
6173,01JC5HGN2WG379KND7ZJ0SEQHQ,이*연,************7501,female,2005-01-09,0,2024-11-08 09:29:33,2,10028,2,2024-11-08 09:25:07.065578,2024-11-08 11:02:40.630485,0.067750
6387,01J7GCSWE2W71AZGBMTZB9AJTE,G***t,**********9222,None,None,0,2024-10-07 03:06:06,2,10028,2,2024-09-11 11:16:53.355639,2024-10-07 03:02:39.560552,25.656785
6395,01JD223QSYQTTXEY1AF0PDVPFM,G***t,**********9833,None,None,0,2024-11-19 11:16:55,2,10028,2,2024-11-19 11:14:50.852183,2024-11-19 15:46:56.112705,0.188950
6492,01J7MRZG685D26H8ZJ8AFK054Y,황*란,************4855,female,2004-01-01,0,2024-10-09 09:57:12,2,10028,2,2024-09-13 04:06:20.680741,2024-10-09 09:55:51.160432,26.242714
6624,01J7QVPA905HHJCFXABKCPND2K,G***t,**********4628,None,None,0,2024-09-14 08:56:19,2,10028,2,2024-09-14 08:51:46.113549,2024-09-14 09:30:23.649965,0.026823
6660,01JA4TRYRFE9A49SF2SJ9PP2FZ,변*진,************6659,male,2002-05-29,1,2024-10-14 06:18:51,2,10028,2,2024-10-14 06:17:28.438227,2024-10-14 20:25:11.803938,0.588696
6724,01JD4E89JZ03AC6FS3K489KYT5,강*석,************7383,male,2002-06-27,1,2024-11-20 09:27:30,2,10028,2,2024-11-20 09:24:52.071228,2025-01-11 09:16:40.401400,51.994309
6826,01J7WE5PXENDXJBMNZD8BW8WSY,G***t,**********2595,None,None,0,2024-09-16 03:34:39,2,10028,2,2024-09-16 03:31:42.684045,2024-09-16 08:15:37.658796,0.197164
6955,01JAA5M5SAV6N2KK6KCJH493GX,김*영,************4138,female,2001-02-19,1,2024-10-16 08:05:25,2,10028,2,2024-10-16 08:03:12.921667,2024-10-24 03:56:13.941705,7.828484
7014,01JBGDY99PACR9AA8VCWM9WY48,이*원,************5517,female,2006-07-30,1,2024-10-31 04:42:52,2,10028,2,2024-10-31 04:40:45.407865,2024-10-31 05:36:01.590172,0.038382
7175,01JCCR356MHERES0VASPB0VPMX,김*경,************4679,male,2000-02-07,1,2024-11-11 04:36:45,2,10028,2,2024-11-11 04:35:28.074807,2024-11-11 18:23:24.865992,0.574963
7193,01JACT8B3KHADWCH6HVG4HTEPM,김*호,************7740,male,2003-07-06,1,2024-10-17 08:44:16,2,10028,2,2024-10-17 08:41:47.740375,2024-10-19 23:23:14.688610,2.612117
7384,01J86VFF2XEXFXSGQX0VAM2ZAV,G***t,**********1853,None,None,0,2024-09-20 04:38:27,2,10028,2,2024-09-20 04:36:38.171347,2024-09-23 02:31:39.889559,2.913214
7720,01JAM7XR2ZXG18QE51FS9NEF2A,G***t,**********2753,None,None,0,2024-10-20 05:58:06,2,10028,2,2024-10-20 05:55:40.296326,2024-10-20 07:49:05.941602,0.078769
7866,01JCHTJ1T674V695NH542JAHB6,G***t,**********8903,None,None,0,2024-11-13 03:59:08,2,10028,2,2024-11-13 03:55:00.346903,2024-11-13 05:09:34.079785,0.051779
8042,01JDC5964EM5JFTRC0X6R2M0KX,G***t,**********5629,None,None,0,2024-11-23 09:26:04,2,10028,2,2024-11-23 09:22:39.437538,2024-11-23 17:21:39.115242,0.332635
8481,01J9AWY0Q4XD12YYB1P0RJC53G,윤*영,************3027,female,2003-03-27,1,2024-10-04 04:36:50,2,10028,2,2024-10-04 04:35:15.565160,2024-10-04 04:42:29.395200,0.005021
8594,01JBXSS2PYT3NRQMD67JAPZ9GJ,박*애,************6940,female,2004-09-19,1,2024-11-05 09:19:40,2,10028,2,2024-11-05 09:15:54.103864,2024-11-05 09:54:29.315292,0.026796
8851,01J6KE1NB9A6R8CQ590B9H8PNR,조*선,************3887,female,1977-11-08,1,2024-08-31 05:24:28,2,10028,2,2024-08-31 05:19:45.269045,2024-08-31 11:04:40.951937,0.239533
8895,01J6KKS4M9VN82RG7XX3WQ9VBH,정*혜,**********6952,female,2007-10-09,0,2024-08-31 07:06:19,2,10028,2,2024-08-31 07:00:19.505613,2024-08-31 10:56:17.644751,0.163867
8913,01JB5TTTS7R50Z7QM4106DZGAV,박*용,************6885,male,1985-09-09,0,2024-10-27 01:55:16,2,10028,2,2024-10-27 01:52:58.144849,2025-03-07 04:41:44.330965,131.117201
8949,01JBZSERJ2RG0J59WD51XSN5X6,이*윤,************8281,male,1998-06-30,1,2024-11-06 03:52:15,2,10028,2,2024-11-06 03:49:08.700856,2024-11-11 11:15:44.204492,5.310133
9051,01JCQS0KBQWB39ZZ7ZSJWZYZVF,G***t,**********2365,None,None,0,2024-11-15 11:25:55,2,10028,2,2024-11-15 11:23:26.504372,2024-11-16 09:43:39.288651,0.930704
9680,01JDHARBYWX9DC2HKMZ8KMVDXP,신*건,************1815,male,2000-04-03,1,2024-11-25 09:37:10,2,10028,2,2024-11-25 09:34:16.396539,2024-11-25 10:26:08.111965,0.036015
9712,01J90GD48QBNRP2REG095DTM72,G***t,**********1936,None,None,0,2024-09-30 03:52:28,2,10028,2,2024-09-30 03:43:22.427016,2024-09-30 04:58:53.270543,0.052440
9804,01JB1KFH8YT5VRQ1J4GWCVSJZE,G***t,**********1535,None,None,0,2024-10-25 10:29:43,2,10028,2,2024-10-25 10:27:45.137117,2024-10-28 11:05:37.579781,3.026301
9997,01J9AQFPM25TFH2NM6CR0ZE73Y,주*빈,************7511,female,2003-12-24,1,2024-10-04 03:01:33,2,10028,2,2024-10-04 02:59:41.485208,2025-03-20 09:07:15.455327,167.255254
11055,01J9AQX4M93849DZ052AMR1RK3,이*광,************0669,male,2001-08-18,1,2024-10-04 03:09:28,2,10028,2,2024-10-04 03:06:34.580639,2024-10-11 03:05:44.114211,6.999416
12466,01J61WKHQENHNETE4NYERM2AE4,김*태,**********6674,male,1992-02-20,0,2024-08-24 09:53:18,2,10028,2,2024-08-24 09:48:16.715310,2024-08-24 15:48:03.474459,0.249847
12532,01J966YJ6YWB0CVV55TFEM89HA,김*섭,**********7564,None,None,0,2024-10-02 08:56:57,2,10028,2,2024-10-02 08:53:19.358860,2024-11-18 09:30:39.865760,47.025932
12874,01JDE94A2PH0HG7JWGQHQB5HQX,신*명,************7659,male,2005-03-23,1,2024-11-24 05:11:53,2,10028,2,2024-11-24 05:07:27.541970,2024-11-24 15:10:26.681999,0.418740
13124,01JDE567X0RBEVN44XR1J3N3S3,김*태,************4434,male,1983-02-26,1,2024-11-24 04:03:44,2,10028,2,2024-11-24 03:58:31.698217,2024-11-25 03:54:34.125242,0.997250
13584,01J8MAXMCZHS2F1CDVNVJM99F6,장*준,************8541,male,2002-01-24,1,2024-09-25 10:28:19,2,10028,2,2024-09-25 10:16:24.839816,2024-10-24 09:47:35.916814,28.979989
21031,01J5SZ0R7FQN5EC2M2V2EP4T6S,오*민,************4031,female,2001-05-30,1,2024-08-21 07:57:38,1,10028,1,2024-08-21 07:55:53.402585,2024-08-21 07:55:53.402585,NaN
21090,01J5WQ0C8KQMK62FA2ST4T5R4F,트**티,**********7776,male,1994-01-09,0,2024-08-22 09:39:13,1,10028,1,2024-08-22 09:34:17.877076,2024-08-22 09:34:17.877076,NaN
21567,01J6PBH3T5TCBYVYNWCRPP24F3,박*성,************1170,male,1977-02-25,1,2024-09-01 08:36:34,1,10028,1,2024-09-01 08:32:59.682657,2024-09-01 08:32:59.682657,NaN
21569,01J6PDQTEYHHJTP7JQEZCWP2Q4,G***t,**********7928,None,None,0,2024-09-01 09:14:31,1,10028,1,2024-09-01 09:12:59.151737,2024-09-01 09:12:59.151737,NaN
21691,01J6VEB3S4W7SEDXCNCPHSZCH3,G***t,**********6479,None,None,0,2024-09-03 08:01:27,1,10028,1,2024-09-03 07:59:43.480323,2024-09-03 07:59:43.480323,NaN
21696,01J6VJX4YQEGBSNQZA5T0P4E47,G***t,**********7452,None,None,0,2024-09-03 09:21:21,1,10028,1,2024-09-03 09:19:28.769455,2024-09-03 09:19:28.769455,NaN
21699,01J6VM008768139GQK8Z1DYTZE,G***t,**********8816,None,None,0,2024-09-03 09:43:40,1,10028,1,2024-09-03 09:38:30.841824,2024-09-03 09:38:30.841824,NaN
21712,01J6XB942DD9HPKV16W1W7RK1A,G***t,**********0647,None,None,0,2024-09-04 01:46:58,1,10028,1,2024-09-04 01:44:41.334561,2024-09-04 01:44:41.334561,NaN
21728,01J6XHT4TC5BGXDMHR2DSVS0DP,이*민,************6104,female,1998-01-16,1,2024-09-04 03:41:30,1,10028,1,2024-09-04 03:38:29.350452,2024-09-04 03:38:29.350452,NaN
21735,01J6XTMSYRKRPV1W9AEGZJAMBA,G***t,**********1289,None,None,0,2024-09-04 06:15:45,1,10028,1,2024-09-04 06:13:12.838691,2024-09-04 06:13:12.838691,NaN
21736,01J6XTMYK41NMRP0FN3H0XKQQT,G***t,**********6539,None,None,0,2024-09-04 06:15:29,1,10028,1,2024-09-04 06:13:17.609008,2024-09-04 06:13:17.609008,NaN
21777,01J706R8QFF2MEX41FCQ13885N,김*건,************2808,male,2002-04-28,1,2024-09-05 04:26:43,1,10028,1,2024-09-05 04:23:00.686383,2024-09-05 04:23:00.686383,NaN
21944,01J75KP91YBZQS7FFK1JFFQD3J,G***t,**********1544,None,None,0,2024-09-07 06:49:17,1,10028,1,2024-09-07 06:45:36.482345,2024-09-07 06:45:36.482345,NaN
21963,01J75X1JA95S45ZP4QZG738X8S,허민,************2684,male,2002-06-10,0,2024-09-07 09:31:19,1,10028,1,2024-09-07 09:28:42.651381,2024-09-07 09:28:42.651381,NaN
22018,01J784Y59DAVK50MVKJDFSM620,G***t,**********8970,None,None,0,2024-09-08 06:27:55,1,10028,1,2024-09-08 06:25:29.429025,2024-09-08 06:25:29.429025,NaN
22064,01J78M4Q9CETX1XZSE8RFMRDC8,G***t,**********1784,None,None,0,2024-09-08 10:54:36,1,10028,1,2024-09-08 10:51:13.110288,2024-09-08 10:51:13.110288,NaN
22067,01J78PEGBYD299F8HBXNKTTFEA,G***t,**********6760,None,None,0,2024-09-08 11:33:01,1,10028,1,2024-09-08 11:31:30.849532,2024-09-08 11:31:30.849532,NaN
22077,01J7AAHFXFHQJ1F3PG0NHKE390,서*수,************3477,female,2005-01-12,1,2024-09-09 02:45:06,1,10028,1,2024-09-09 02:41:24.741497,2024-09-09 02:41:24.741497,NaN
22086,01J7AC8SVVXMQWTSZV7CDZTAZ5,G***t,**********4569,None,None,0,2024-09-09 03:17:12,1,10028,1,2024-09-09 03:12:07.076569,2024-09-09 03:12:07.076569,NaN
22113,01J7AZT8MCG8F20544JAW6HT6Y,G***t,**********1657,None,None,0,2024-09-09 08:57:13,1,10028,1,2024-09-09 08:53:42.207609,2024-09-09 08:53:42.207609,NaN
22152,01J7CYHTN25HRTY8PBM43ETJN1,G***t,**********3056,None,None,0,2024-09-10 03:12:51,1,10028,1,2024-09-10 03:10:06.022457,2024-09-10 03:10:06.022457,NaN
22182,01J7DB726XX6MRVM840H2QWGH1,오*민,************2142,male,1981-09-03,1,2024-09-10 06:52:57,1,10028,1,2024-09-10 06:51:09.604833,2024-09-10 06:51:09.604833,NaN
22272,01J7GADQAH0DYB35F7YE83A22W,L**********G,************7632,male,2002-08-23,1,2024-09-11 10:39:18,1,10028,1,2024-09-11 10:35:05.830994,2024-09-11 10:35:05.830994,NaN
22306,01J7J7ZBVNS9V1GMSANRACB7R7,김*은,************3655,female,2004-02-16,0,2024-09-12 04:32:47,1,10028,1,2024-09-12 04:30:38.296005,2024-09-12 04:30:38.296005,NaN
22312,01J7JFA6YMN8JV64W3QGB9BAAA,G***t,**********8077,None,None,0,2024-09-12 06:43:40,1,10028,1,2024-09-12 06:39:14.461587,2024-09-12 06:39:14.461587,NaN
22355,01J7MQ20HY587DRKPHD92RX309,김*근,************6119,female,2005-09-13,1,2024-09-13 03:35:44,1,10028,1,2024-09-13 03:33:27.275557,2024-09-13 03:33:27.275557,NaN
22373,01J7N0QJ5TGEQRHTRMJ0JZ4YRN,이*은,************7039,female,2004-12-15,1,2024-09-13 06:24:15,1,10028,1,2024-09-13 06:21:41.321476,2024-09-13 06:21:41.321476,NaN
22390,01J7NACRVCG0HX8EK64ECD7SAB,G***t,**********3466,None,None,0,2024-09-13 09:13:03,1,10028,1,2024-09-13 09:10:58.725067,2024-09-13 09:10:58.725067,NaN
22408,01J7NJFKG79SMDWKFP04NEH0GT,이*주,************1822,female,2000-08-22,1,2024-09-13 11:33:54,1,10028,1,2024-09-13 11:31:59.725144,2024-09-13 11:31:59.725144,NaN
22419,01J7QA8Q5FYK01EGHWVF75NXVQ,G***t,**********1438,None,None,0,2024-09-14 03:48:44,1,10028,1,2024-09-14 03:47:14.822295,2024-09-14 03:47:14.822295,NaN
22443,01J7QKGBYWMFE9T6M12P23BB26,G***t,**********7118,None,None,0,2024-09-14 06:31:45,1,10028,1,2024-09-14 06:28:42.624033,2024-09-14 06:28:42.624033,NaN
22476,01J7R1WQVWJMA214PPD10YD27T,G***t,**********1337,None,None,0,2024-09-14 10:42:21,1,10028,1,2024-09-14 10:40:08.098355,2024-09-14 10:40:08.098355,NaN
22504,01J7SWABBBFHPNVM6AFCXXVAVA,G***t,*********8027,None,None,0,2024-09-15 03:45:50,1,10028,1,2024-09-15 03:41:11.444623,2024-09-15 03:41:11.444623,NaN
22538,01J7TFMXHSTRRPE4JN04B2GV28,G***t,**********8090,None,None,0,2024-09-15 09:22:09,1,10028,1,2024-09-15 09:19:00.705467,2024-09-15 09:19:00.705467,NaN
22548,01J7TK1SM7J0QXWRPPDNEZPTN2,김*환,************6466,male,1977-11-23,0,2024-09-15 10:20:21,1,10028,1,2024-09-15 10:18:10.957449,2024-09-15 10:18:10.957449,NaN
22817,01J825R7VX59XNMCXF238J7M3R,정*주,************0627,female,2003-06-27,0,2024-09-23 03:27:06,1,10028,1,2024-09-23 03:23:58.564935,2024-09-23 03:23:58.564935,NaN

In [10]:
customers[
    ~customers['isMarketingAgreed'].isnull()
].info()

<class 'pandas.core.frame.DataFrame'>
Index: 870 entries, 35 to 66386
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   customerId                       870 non-null    object
 1   fullName                         870 non-null    object
 2   phoneNumber                      870 non-null    object
 3   gender                           534 non-null    object
 4   dateOfBirth                      535 non-null    object
 5   subscribedToSicpamaKakaoChannel  870 non-null    int64
 6   isMarketingAgreed                870 non-null    datetime64[ns]
 7   total_visits                     870 non-null    int64
 8   main_storeId                     870 non-null    int64
 9   main_store_visits                870 non-null    int64
 10  first_visit                      870 non-null    datetime64[ns]
 11  last_visit                       870 non-null    datetime64[ns]
 12  main_store_avg_revisit_days      367 non-null    float64
dtypes: datetime64[ns](3), float64(1), int64(4), object(5)
memory usage: 95.2+ KB

In [13]:
customers[
    ~customers['isMarketingAgreed'].isnull() &
    customers['gender'].isnull()
]

,customerId,fullName,phoneNumber,gender,dateOfBirth,subscribedToSicpamaKakaoChannel,isMarketingAgreed,total_visits,main_storeId,main_store_visits,first_visit,last_visit,main_store_avg_revisit_days
82,01J7CSDEPJ6ZAXJW1KPXKVBTCM,G***t,**********6340,None,None,0,2024-09-10 01:43:51,20,10028,20,2024-09-10 01:40:19.831744,2024-09-23 02:36:26.577614,0.686261
175,01JG10GRAC7PQX50PR85FYM93H,G***t,**********7150,None,None,0,2024-12-26 08:18:11,13,3,12,2024-12-26 08:14:51.258634,2025-01-04 02:46:28.147817,0.797450
315,01J7DJGX9PXSGASRGTF112XPBC,G***t,**********3312,None,None,0,2024-09-22 08:09:04,10,10023,10,2024-09-10 08:59:07.474598,2024-10-21 09:44:08.015721,4.559028
505,01J6KJEMNWVFRTMWBMYJB5KEYZ,홍*진,**********0499,None,None,0,2024-08-31 06:39:54,8,10026,6,2024-08-31 06:37:17.565604,2024-09-02 08:40:01.597653,0.417046
849,01J7JQ5ND43HZ2B6DJQAF4AJ58,G***t,**********5077,None,None,0,2024-09-12 08:57:36,6,10028,6,2024-09-12 08:56:33.987678,2024-12-14 12:20:54.780512,18.628381
1144,01J4ZZSVJ6HDH8F4FJTJ7PHP85,G***t,**********6709,None,None,0,2024-09-09 03:12:57,5,10028,5,2024-08-11 05:50:26.417109,2024-09-09 03:11:24.497607,7.222390
1330,01JAHJN0Q2AAB4CXX2HKPYYZFW,G***t,*********5135,None,None,0,2024-10-19 05:14:13,5,10023,5,2024-10-19 05:05:25.261009,2024-10-19 09:39:01.049861,0.047499
1521,01JTJJKWXD5EVFFARPAMGJF4YX,G***t,**********0116,None,None,0,2025-05-06 10:38:49,4,3,4,2025-05-06 10:35:12.201443,2025-05-12 12:50:10.722004,2.031244
1590,01JFY7KMYN4D9R8QNX2PSCN2QF,G***t,**********1503,None,None,0,2024-12-25 06:22:29,4,3,4,2024-12-25 06:21:02.860017,2024-12-26 12:35:33.090615,0.420024
1698,01JSKDV23WE7B3B2YMN6DQT88G,G***t,**********0111,None,None,0,2025-05-07 04:36:06,4,5,4,2025-04-24 08:15:16.626777,2025-05-10 08:52:11.607949,5.341879
1742,01JFKN7QY4KAZV0DK89TYP0P8T,G***t,**********4068,None,None,0,2024-12-22 10:05:47,4,3,4,2024-12-21 03:47:34.047236,2024-12-22 12:13:05.748560,0.450354
2014,01HZ9N2YYEWDDGQJHWSJR9QDD0,G***t,**********9916,None,None,0,2024-09-22 04:42:17,4,3,4,2024-06-01 10:21:23.838286,2024-09-22 13:26:29.618931,37.709513
2100,01JQN46ZPVRPFKMQHGEVA3S1C8,G***t,**********8478,None,None,0,2025-03-31 03:36:08,4,3,4,2025-03-31 03:34:06.876400,2025-04-12 10:15:25.788350,4.092897
2153,01HX8TYCAB468WD4AFAYBQ6R7Z,G***t,**********1841,None,None,0,2025-01-12 04:11:50,4,3,4,2024-05-07 06:13:07.056055,2025-01-13 02:21:02.551991,83.612946
2319,01JQDFA4E6Z82WMAGAF4KX86VW,G***t,**********0611,None,None,0,2025-04-10 04:30:02,4,3,4,2025-03-28 04:14:08.864437,2025-05-03 10:17:27.218428,12.084099
2474,01JHCNMZYQD539KH5DJGEAWETE,G***t,**********4145,None,None,0,2025-01-12 07:22:48,4,3,4,2025-01-12 07:11:30.825086,2025-01-29 13:55:40.079793,5.760221
2518,01J821JMP6D21K0PRNAW0K5Z05,지**니,**********8681,None,1982-04-01,0,2024-09-18 07:50:03,3,10028,3,2024-09-18 07:46:18.115610,2024-11-08 03:50:07.257276,25.417993
2875,01J9K4RPFP0GJQMP2NJYPQZV50,G***t,**********3762,None,None,0,2024-11-18 03:00:59,3,10028,3,2024-10-07 09:25:32.836359,2024-11-18 02:58:03.304305,20.865454
3014,01JM8XV3FM9W0GMJ12QSA5SPB5,G***t,,None,None,0,2025-02-28 03:02:06,3,3,3,2025-02-17 03:04:47.443335,2025-02-28 02:58:55.855063,5.497965
3053,01JMPJCPA9CAV83HQGS2GW85T5,G***t,**********3301,None,None,0,2025-04-11 11:12:46,3,3,3,2025-02-22 10:14:02.851737,2025-04-11 11:11:06.416802,24.019812
3081,01J6ZWVY598Q0231A15CDM5P01,G***t,**********8997,None,None,0,2024-09-05 01:32:38,3,10028,3,2024-09-05 01:30:32.518773,2024-09-13 16:12:31.925344,4.306247
3174,01J70G6GRWT6Q91RW1XC6G71NQ,G***t,**********4949,None,None,0,2024-09-05 07:10:22,3,10028,3,2024-09-05 07:08:22.223375,2024-09-10 20:29:48.920726,2.778279
3188,01J9NRW899DSXXG2YD0XFMZZWM,G***t,**********5938,None,None,0,2024-10-08 09:57:57,3,10028,3,2024-10-08 09:55:29.741202,2024-10-21 04:40:10.055376,6.390511
3238,01J9QHH0YQBXATBGWJED1B2N6D,G***t,**********7924,None,None,0,2024-11-01 06:12:20,3,10028,3,2024-10-09 02:25:30.636086,2024-11-01 06:20:50.337135,11.581711
3291,01JNTGWV6SMEA1EZKS6WJ30818,G***t,**********2858,None,None,0,2025-03-08 09:26:37,3,3,3,2025-03-08 09:20:34.545680,2025-03-08 13:15:46.078631,0.081664
3659,01J9WVK4B27ZPE8WPVZHDPRF21,G***t,**********5386,None,None,0,2024-11-21 04:37:34,3,10028,3,2024-10-11 03:57:37.572551,2024-11-21 04:36:24.123723,20.513464
3688,01J8ERZ4WMR2W578Y8SZDJKJ4Y,G***t,**********5581,None,None,0,2024-09-23 06:28:31,3,10028,3,2024-09-23 06:26:41.736103,2024-09-23 23:28:35.034511,0.354822
3703,01HSJSRTC8B1NV6ZRGXHDB20JH,G***t,**********5731,None,None,0,2024-11-16 10:10:32,3,3,3,2024-03-22 10:02:13.283977,2024-12-16 08:01:16.191331,134.458003
3997,01J8KKGMYJHPYX4DTRJR7BNZ3W,G***t,**********2340,None,None,0,2024-09-25 03:29:18,3,10028,3,2024-09-25 03:27:35.918991,2024-10-02 03:07:52.411129,3.493151
4110,01J9ZX9QEAA12TB3HP5RRPM7WN,G***t,**********0773,None,None,0,2024-10-12 08:26:18,3,3,3,2024-10-12 08:25:09.856338,2024-10-13 08:23:14.045282,0.499330
4121,01JC7HJAHSMRZ548MTGPKM6S3Q,G***t,**********3524,None,None,0,2024-11-09 04:08:38,3,10028,3,2024-11-09 04:05:27.780590,2025-01-15 09:09:23.060000,33.605528
4140,01J4P0FPK6RY6X460058QXAQ7N,G***t,**********5177,None,None,0,2024-09-23 09:47:22,3,10028,3,2024-08-07 08:49:57.919232,2024-09-23 09:46:16.210976,23.519550
4242,01JCQ0X3H4MWC0SCFA3W7CP8GA,G***t,**********65 9,None,None,0,2024-11-15 04:27:52,3,3,3,2024-11-15 04:22:06.174645,2024-11-17 06:13:13.564980,1.038584
4245,01JAWAMW96GMQ26RXZ46SG0SXW,G***t,**********2067,None,None,0,2024-10-23 09:21:41,3,10028,3,2024-10-23 09:17:10.850666,2024-11-10 23:26:11.501216,9.294795
4492,01JBX72M6DTKJ82J0RCWB4DV92,G***t,**********1750,None,None,0,2024-11-05 03:51:05,3,3,3,2024-11-05 03:49:43.273139,2025-01-15 04:01:14.740095,35.504002
4734,01J9AX4DPS595SADHW5P4T9Q8V,G***t,**********9511,None,None,0,2024-10-04 04:42:14,3,10023,3,2024-10-04 04:38:12.990369,2024-10-11 07:07:29.223345,3.551830
4741,01J6C4GSH2TEFQ16SRMEW09TBP,G***t,**********1855,None,None,0,2024-08-28 09:23:27,3,10028,3,2024-08-28 09:19:27.324417,2024-09-01 05:35:29.194147,1.922233
4762,01J7WQ5KXF7NC5RWB95ZD8W4QE,G***t,**********5607,None,None,0,2024-10-04 07:54:01,3,10024,3,2024-09-16 06:08:56.790612,2024-10-04 08:24:04.583179,9.046920
4785,01JA9MJ7QTQ661QEX8N1DDH5BV,G***t,**********8891,None,None,0,2024-10-16 03:09:33,3,10028,3,2024-10-16 03:04:55.828759,2024-11-13 18:10:48.651108,14.314542
4790,01J6EWVAPX8E59ERSK1M6QNZB4,G***t,**********8204,None,None,0,2024-08-29 11:05:23,3,10028,3,2024-08-29 11:03:07.270442,2024-09-03 12:00:24.416858,2.519891
4838,01J6KM7XERQ0FFZNFTV3GHJNAN,G***t,*********8485,None,None,0,2024-12-26 08:03:30,3,3,3,2024-08-31 07:08:54.676390,2024-12-27 16:56:37.194704,59.204065
5037,01HQYJYDQE1T5BJC95DM6R8743,G***t,**********0953,None,None,0,2024-11-23 05:29:33,3,3,3,2024-03-02 03:22:26.560364,2024-11-23 05:26:31.469653,133.043084
5040,01JGXEBCNXDR36NR8QRTHVRZSY,G***t,,None,None,0,2025-01-31 03:22:04,3,3,3,2025-01-06 09:15:19.678193,2025-01-31 03:17:43.355149,12.375831
5207,01HM8PG2PFQ6NV8ZKDBXPVJY0G,,************5848,None,0000-00-00,0,2024-11-26 12:08:23,2,3,2,2024-01-16 08:33:37.545112,2024-11-26 12:05:19.529350,315.147014
5470,01J9K89692FKPXSF473X4MDVHE,G***t,**********8900,None,None,0,2024-10-07 10:29:48,2,10028,2,2024-10-07 10:26:59.010291,2024-10-07 15:28:35.385783,0.209449
5540,01J6Y3MCXN49Z08HK2MXF9QXEB,G***t,**********3861,None,None,0,2024-09-04 08:52:40,2,10028,2,2024-09-04 08:50:16.686686,2024-09-04 11:45:51.420602,0.121930
5819,01J9RD7NRX5C01HYSMWPJZZ42G,G***t,**********6926,None,None,0,2024-10-09 10:36:53,2,10028,2,2024-10-09 10:29:44.401758,2024-10-13 05:10:25.849443,3.778257
5836,01J75BX20BA0ZA896N9KA39AY6,G***t,**********2886,None,None,0,2024-09-07 04:32:37,2,3,2,2024-09-07 04:29:30.184197,2024-09-09 05:10:51.058731,2.028714
6057,01J9X2F7TWQBVA4S8T548VDGE9,G***t,**********9794,None,None,0,2024-10-11 06:00:22,2,10023,2,2024-10-11 05:57:50.093698,2024-10-14 04:56:13.906636,2.957220
6068,01J7APQW8SJGKBQGT54HWMSFN0,G***t,**********4223,None,None,0,2024-09-09 06:19:36,2,10028,2,2024-09-09 06:15:06.810645,2024-09-10 01:49:38.481236,0.815644
6106,01JEFWJDPP2P4EJA4TRWY8BYRK,G***t,**********2126,None,None,0,2025-01-10 03:10:40,2,3,1,2025-01-10 03:04:53.891295,2025-01-10 03:04:53.891295,NaN
6134,01J7CVS3KGSSEX2N3BPM6VA0FQ,G***t,**********6090,None,None,0,2024-09-10 02:23:36,2,10028,2,2024-09-10 02:21:38.842315,2024-09-10 13:00:36.364601,0.443721
6151,01J7CXY9472VSABY6HZ8H88SY0,G***t,**********5981,None,None,0,2024-09-10 03:02:24,2,10028,2,2024-09-10 02:59:25.491982,2024-09-10 14:03:09.851571,0.460930
6387,01J7GCSWE2W71AZGBMTZB9AJTE,G***t,**********9222,None,None,0,2024-10-07 03:06:06,2,10028,2,2024-09-11 11:16:53.355639,2024-10-07 03:02:39.560552,25.656785
6395,01JD223QSYQTTXEY1AF0PDVPFM,G***t,**********9833,None,None,0,2024-11-19 11:16:55,2,10028,2,2024-11-19 11:14:50.852183,2024-11-19 15:46:56.112705,0.188950
6580,01JD3VVP793ZPN7E387MV5YW7C,G***t,**********6226,None,None,0,2024-11-20 04:06:16,2,3,1,2025-01-05 08:48:28.666278,2025-01-05 08:48:28.666278,NaN
6624,01J7QVPA905HHJCFXABKCPND2K,G***t,**********4628,None,None,0,2024-09-14 08:56:19,2,10028,2,2024-09-14 08:51:46.113549,2024-09-14 09:30:23.649965,0.026823
6678,01J7SW3EXQDAJNTK3EPVWT4P8X,G***t,**********0736,None,None,0,2024-09-15 03:43:29,2,3,2,2024-09-15 03:37:25.727974,2024-09-15 04:57:15.461371,0.055437
6826,01J7WE5PXENDXJBMNZD8BW8WSY,G***t,**********2595,None,None,0,2024-09-16 03:34:39,2,10028,2,2024-09-16 03:31:42.684045,2024-09-16 08:15:37.658796,0.197164
6984,01J7Z34ETESY2ETS9Q13WGK4N5,G***t,*********8338,None,None,0,2024-09-17 04:26:32,2,3,2,2024-09-17 04:16:30.574522,2024-09-17 11:53:30.221619,0.317357
7072,01J7ZRMZ1CPQSBZHVP8VSR268J,G***t,**********5545,None,None,0,2024-09-17 10:34:56,2,3,2,2024-09-17 10:32:31.635329,2024-09-18 03:40:33.039448,0.713905
7077,01J7ZT42WVPVKAJT2CNK55B24N,G***t,,None,None,0,2024-09-17 11:05:41,2,3,2,2024-09-17 10:58:15.605705,2024-09-17 11:00:21.059344,0.001452
7081,01J7ZT43BHRQF829TRTVVYPSE9,G***t,**********2209,None,None,0,2024-09-17 11:05:55,2,3,2,2024-09-17 10:58:16.082265,2024-09-17 10:59:42.191264,0.000997
7312,01J37X6TGEPJHG62KPM3KGQY1B,G***t,**********0336,None,None,0,2025-01-25 05:36:25,2,3,2,2024-07-20 11:07:37.428311,2025-01-25 05:32:57.104643,188.767589
7384,01J86VFF2XEXFXSGQX0VAM2ZAV,G***t,**********1853,None,None,0,2024-09-20 04:38:27,2,10028,2,2024-09-20 04:36:38.171347,2024-09-23 02:31:39.889559,2.913214
7708,01JAM5XV3ZWJHWCM8S62WXFGBZ,G***t,**********4145,None,None,0,2024-10-20 05:23:51,2,3,2,2024-10-20 05:20:46.315314,2024-10-20 12:02:35.909713,0.279046
7720,01JAM7XR2ZXG18QE51FS9NEF2A,G***t,**********2753,None,None,0,2024-10-20 05:58:06,2,10028,2,2024-10-20 05:55:40.296326,2024-10-20 07:49:05.941602,0.078769
7803,01JDBM4PM8J88V53RHP75PNKRT,G***t,**********5596,None,None,0,2024-11-23 04:28:43,2,3,2,2024-11-23 04:23:06.669662,2024-11-23 04:25:59.992650,0.002006
7866,01JCHTJ1T674V695NH542JAHB6,G***t,**********8903,None,None,0,2024-11-13 03:59:08,2,10028,2,2024-11-13 03:55:00.346903,2024-11-13 05:09:34.079785,0.051779
8042,01JDC5964EM5JFTRC0X6R2M0KX,G***t,**********5629,None,None,0,2024-11-23 09:26:04,2,10028,2,2024-11-23 09:22:39.437538,2024-11-23 17:21:39.115242,0.332635
8241,01JHCB4D4W15BZ157MXVD2AVFW,G***t,**********7934,None,None,0,2025-01-12 04:10:06,2,3,2,2025-01-12 04:07:41.549785,2025-01-12 07:52:09.836635,0.155883
8249,01JHCN015M91X972MXDPRYK6FC,王*婷,**********0356,None,None,0,2025-01-12 07:03:46,2,10023,2,2025-01-12 06:59:30.900548,2025-01-12 07:05:31.454099,0.004173
8283,01JHJ9BCT6P7RHH1T01ETN734J,G***t,**********3838,None,None,0,2025-01-14 11:39:58,2,10023,2,2025-01-14 11:31:59.995917,2025-01-15 12:30:32.683170,1.040656
8291,01JHMT0EPPTJQYZN1AHD8S1X2G,G***t,*********0500,None,None,0,2025-01-15 11:05:06,2,3,2,2025-01-15 11:01:36.172139,2025-01-15 13:36:41.740477,0.107703
8350,01J95DZ7HGGJFR7NHSQMBHK5SN,G***t,**********4669,None,None,0,2024-10-02 01:38:42,2,10024,1,2024-11-04 07:00:46.129908,2024-11-04 07:00:46.129908,NaN
8510,01J9DDVPJHKYY13Z78VWYKER81,G***t,**********5565,None,None,0,2024-10-05 04:10:09,2,15,2,2024-10-05 04:09:01.807374,2024-10-08 12:53:56.774115,3.364525
8614,01JBXSHCTXAMS9Z7T2A7DBCRJR,G***t,**********1914,None,None,0,2024-11-05 09:14:21,2,5,1,2024-12-19 11:04:47.697013,2024-12-19 11:04:47.697013,NaN
9046,01J6KTRQ73HTKNWJY6VQD7SS2C,G***t,**********5800,None,None,0,2024-08-31 09:05:48,2,15,2,2024-08-31 09:02:56.792502,2024-08-31 09:36:49.860845,0.023531
9051,01JCQS0KBQWB39ZZ7ZSJWZYZVF,G***t,**********2365,None,None,0,2024-11-15 11:25:55,2,10028,2,2024-11-15 11:23:26.504372,2024-11-16 09:43:39.288651,0.930704
9076,01JKAFASGZRAC4X8EW97EZH623,G***t,**********9969,None,None,0,2025-02-05 07:19:14,2,3,2,2025-02-05 07:13:59.885959,2025-02-05 07:37:52.460672,0.016581
9103,01JCT7M2Z4JC88XZ0TVF44KVBQ,G***t,**********5167,None,None,0,2024-11-16 10:29:23,2,10023,2,2024-11-16 10:17:13.991059,2024-11-16 13:01:39.757490,0.114187
9145,01J9E48CRSGK8Y68FC1M9WM6BH,G***t,**********9255,None,None,0,2024-10-26 05:10:05,2,10023,2,2024-10-05 10:40:26.429827,2024-10-26 05:06:54.076442,20.768376
9394,01JKQSKWBSVMKJ25WAKBVFPNQ9,G***t,**********6224,None,None,0,2025-02-10 11:27:56,2,3,2,2025-02-10 11:23:51.067574,2025-02-10 13:30:03.659401,0.087646
9501,01JKZ87R6ZSER898MN0H9J7A0A,G***t,**********9989,None,None,0,2025-03-20 10:22:23,2,10000,1,2025-02-13 08:54:03.301786,2025-02-13 08:54:03.301786,NaN
9712,01J90GD48QBNRP2REG095DTM72,G***t,**********1936,None,None,0,2024-09-30 03:52:28,2,10028,2,2024-09-30 03:43:22.427016,2024-09-30 04:58:53.270543,0.052440
9804,01JB1KFH8YT5VRQ1J4GWCVSJZE,G***t,**********1535,None,None,0,2024-10-25 10:29:43,2,10028,2,2024-10-25 10:27:45.137117,2024-10-28 11:05:37.579781,3.026301
9852,01JF20G4P7GF8NBFT99AMZ6G2C,G***t,**********8752,None,None,0,2024-12-14 07:21:37,2,3,2,2024-12-14 07:18:03.761051,2024-12-14 13:32:26.156552,0.259981
9880,01JMCB3HFWY3YH0JDPR1GSRNRX,G***t,**********1532,None,None,0,2025-02-18 10:58:04,2,10023,2,2025-02-18 10:54:18.663447,2025-02-18 16:06:33.076504,0.216833
9891,01JMEEKSW00HRYYE0A8C1KSJNY,G***t,**********6551,None,None,0,2025-02-19 06:36:51,2,3,2,2025-02-19 06:34:06.102183,2025-02-20 07:10:53.831249,1.025552
10616,01JNTB6KKG6T996W5KSJ6FJDJP,G***t,**********3908,None,None,0,2025-03-08 07:43:21,2,3,2,2025-03-08 07:41:02.998627,2025-03-09 07:01:13.648632,0.972345
10707,01J8Y7E1J2BCP3NH1QEGZKNW0H,G***t,**********6705,None,None,0,2024-09-29 06:32:17,2,3,2,2024-09-29 06:28:06.374020,2024-09-29 15:22:21.148649,0.371004
11030,01JPPQNMAWNV1X7QJS9DT42TE0,G***t,**********8455,None,None,0,2025-03-19 08:25:38,2,5,2,2025-03-19 08:17:42.282054,2025-03-19 09:07:32.130487,0.034605
11035,01JFVJKZ2P24HTNZRBTQC7HD9H,G***t,**********4058,None,None,0,2024-12-24 05:42:57,2,3,2,2024-12-24 05:35:44.254405,2024-12-24 07:54:45.885637,0.096547
11081,01JPSDVNGSZDW621DX7K9J4MFT,G***t,**********1969,None,None,0,2025-03-20 09:24:53,2,3,2,2025-03-20 09:23:57.615984,2025-03-20 15:16:51.070432,0.245063
11285,01JFYEP2WDTV5JV86YZVFP94V5,G***t,**********0224,None,None,0,2024-12-25 08:28:50,2,3,2,2024-12-25 08:24:42.684561,2024-12-26 17:47:16.943797,1.390674
11319,01JQAQ3J32M24NWNS94ENGFNPE,G***t,**********2945,None,None,0,2025-03-27 02:40:17,2,5,1,2025-03-27 02:32:38.799879,2025-03-27 02:32:38.799879,NaN
11667,01JQKA1VKR76WXRZR3MQWZCZ4C,G***t,*********7404,None,None,0,2025-03-30 10:44:17,2,3,2,2025-03-30 10:37:41.406496,2025-03-30 13:17:11.686138,0.110767
11744,01JQRCXMW4CXM1XDDVTXKVF50Y,G***t,**********1090,None,None,0,2025-04-01 10:04:47,2,3,2,2025-04-01 10:04:01.311060,2025-04-04 15:55:18.105759,3.243944
11946,01JR9RK6M0Z7A0NTNWY4HWH649,G***t,**********9905,None,None,0,2025-04-08 03:57:31,2,3,2,2025-04-08 03:55:07.285549,2025-04-08 09:42:29.262380,0.241227
12107,01JRQ1EN6P2HRZQ2GDT8S3N04T,G***t,**********8055,None,None,0,2025-04-13 07:42:30,2,3,2,2025-04-13 07:40:03.209037,2025-04-13 14:15:45.103533,0.274790
12532,01J966YJ6YWB0CVV55TFEM89HA,김*섭,**********7564,None,None,0,2024-10-02 08:56:57,2,10028,2,2024-10-02 08:53:19.358860,2024-11-18 09:30:39.865760,47.025932
12747,01JSC2K04R4223VJN1PK2TNPN2,G***t,**********5120,None,None,0,2025-04-21 11:45:19,2,3,2,2025-04-21 11:43:57.125436,2025-04-22 04:24:23.791634,0.694753
12762,01JSG8VY74M0JJE7EEWCXHPDW4,G***t,**********4218,None,None,0,2025-04-23 02:52:36,2,3,2,2025-04-23 02:50:39.221952,2025-04-24 01:21:53.998885,0.938365
12946,01JSR5CM17N84H6JBTSNDZ1JG9,G***t,**********4786,None,None,0,2025-04-26 04:26:00,2,3,2,2025-04-26 04:23:47.030585,2025-04-28 15:24:12.487845,2.458628
13007,01J8PMSJHNQTWB9R1M9MCKSACM,G***t,**********9204,None,None,0,2024-09-26 07:50:11,2,10023,2,2024-09-26 07:47:40.252741,2024-09-27 03:26:15.515697,0.818464
13232,01JT51PVM35WHH50Q4XQ8D0P9V,G***t,**********2127,None,None,0,2025-05-01 04:34:13,2,3,2,2025-05-01 04:29:35.782317,2025-05-13 09:50:11.198769,12.222632
13313,01JT9YM7HE59EB3H28VK61GZSF,G***t,**********6850,None,None,0,2025-05-03 02:13:21,2,3,2,2025-05-03 02:11:56.102103,2025-05-03 04:23:38.011657,0.091457
13412,01JTFBXVFCP7V7610WNVHWCZQ1,G***t,**********6476,None,None,0,2025-05-05 04:42:16,2,3,2,2025-05-05 04:40:35.080409,2025-05-05 15:33:04.326184,0.453116
13417,01JTFET5YY8ZJT9SW33PK4P3JJ,G***t,**********9989,None,None,0,2025-05-08 11:06:05,2,3,1,2025-05-08 11:02:55.883697,2025-05-08 11:02:55.883697,NaN
13469,01JTMXE5Q96D8PVYS86ZR7MXQR,G***t,**********0224,None,None,0,2025-05-07 08:28:26,2,3,2,2025-05-07 08:22:47.829693,2025-05-07 15:42:10.033348,0.305118
13531,01J8MC1HAAC1V55YXMPQ0PWNSQ,G***t,**********4503,None,None,0,2024-09-25 10:43:08,2,10023,2,2024-09-25 10:36:15.091229,2024-09-25 10:37:07.323417,0.000605
13558,01JTYQ2WSVGCP1ACVAJBRJSFXZ,G***t,**********8068,None,None,0,2025-05-11 03:57:02,2,3,2,2025-05-11 03:44:11.086383,2025-05-11 04:59:06.135041,0.052026
13611,01JTZMR0E3T7GXWCVJZY4G2653,G***t,**********7216,None,None,0,2025-05-11 12:27:50,2,3,2,2025-05-11 12:22:31.641332,2025-05-11 12:26:27.153604,0.002726
21204,01J63PJENR9KRZGM1ZBWY0AD9T,G***t,**********7292,None,None,0,2024-08-25 02:44:23,1,15,1,2024-08-25 02:41:46.209425,2024-08-25 02:41:46.209425,NaN
21238,01J64MQ1HBASF66AJHVAPRMW36,G***t,**********7634,None,None,0,2024-08-25 11:30:10,1,3,1,2024-08-25 11:28:33.867526,2024-08-25 11:28:33.867526,NaN
21241,01J64PVW1MSXS4BSG7WW35CJZZ,G***t,**********2506,None,None,0,2024-08-25 12:24:17,1,5,1,2024-08-25 12:06:09.243577,2024-08-25 12:06:09.243577,NaN
21347,01J6BEGHJJEM02TS6QXX52Y9J1,G***t,**********0295,None,None,0,2024-08-28 02:56:47,1,10005,1,2024-08-28 02:54:50.498382,2024-08-28 02:54:50.498382,NaN
21348,01J6BGXS3Y71FH8KHGSGZCC8NS,G***t,**********5792,None,None,0,2024-08-28 03:39:51,1,3,1,2024-08-28 03:37:01.344363,2024-08-28 03:37:01.344363,NaN
21385,01J6E0YK5ZRCAM59X77RYZV6WQ,G***t,**********3240,None,None,0,2024-08-29 02:57:23,1,15,1,2024-08-29 02:55:34.124713,2024-08-29 02:55:34.124713,NaN
21399,01J6E4TK5YK0THD3W8HYDKZEQT,G***t,**********1935,None,None,0,2024-08-29 04:18:15,1,3,1,2024-08-29 04:03:17.350638,2024-08-29 04:03:17.350638,NaN
21428,01J6EWDQY8KZH3QS6BZ4X0VJ3D,G***t,**********3875,None,None,0,2024-08-29 10:59:49,1,15,1,2024-08-29 10:55:42.101320,2024-08-29 10:55:42.101320,NaN
21569,01J6PDQTEYHHJTP7JQEZCWP2Q4,G***t,**********7928,None,None,0,2024-09-01 09:14:31,1,10028,1,2024-09-01 09:12:59.151737,2024-09-01 09:12:59.151737,NaN
21616,01J6RNQ4XFXRWD8GPPD7MEFQ5Q,G***t,**********9-55,None,None,0,2024-09-02 06:14:43,1,3,1,2024-09-02 06:10:54.546188,2024-09-02 06:10:54.546188,NaN
21637,01J6S6PV95CRGA6HPSXYEY1DNC,G***t,**********6702,None,None,0,2024-09-02 11:13:18,1,3,1,2024-09-02 11:07:50.459574,2024-09-02 11:07:50.459574,NaN
21691,01J6VEB3S4W7SEDXCNCPHSZCH3,G***t,**********6479,None,None,0,2024-09-03 08:01:27,1,10028,1,2024-09-03 07:59:43.480323,2024-09-03 07:59:43.480323,NaN
21696,01J6VJX4YQEGBSNQZA5T0P4E47,G***t,**********7452,None,None,0,2024-09-03 09:21:21,1,10028,1,2024-09-03 09:19:28.769455,2024-09-03 09:19:28.769455,NaN
21699,01J6VM008768139GQK8Z1DYTZE,G***t,**********8816,None,None,0,2024-09-03 09:43:40,1,10028,1,2024-09-03 09:38:30.841824,2024-09-03 09:38:30.841824,NaN

In [12]:
customers[
    ~customers['isMarketingAgreed'].isnull()
].groupby('main_storeId').count()

,customerId,fullName,phoneNumber,gender,dateOfBirth,subscribedToSicpamaKakaoChannel,isMarketingAgreed,total_visits,main_store_visits,first_visit,last_visit,main_store_avg_revisit_days
main_storeId,,,,,,,,,,,,
3,466,466,466,281,281,466,466,466,466,466,466,190
5,33,33,33,28,28,33,33,33,33,33,33,20
15,19,19,19,12,12,19,19,19,19,19,19,10
10000,2,2,2,1,1,2,2,2,2,2,2,0
10005,2,2,2,1,1,2,2,2,2,2,2,0
10023,122,122,122,90,90,122,122,122,122,122,122,55
10024,4,4,4,1,1,4,4,4,4,4,4,1
10026,6,6,6,3,3,6,6,6,6,6,6,4
10028,212,212,212,114,115,212,212,212,212,212,212,87
10030,4,4,4,3,3,4,4,4,4,4,4,0

In [8]:
c1.to_csv('10028.csv', index=False)