In [1]:
import pandas as pd

In [2]:
test = pd.read_csv('../data/test_group_v2.csv')
control = pd.read_csv('../data/control_group_v2.csv')

In [18]:
test.isna().sum()

customerId                  0
fullName                    1
phoneNumber                 0
dateOfBirth               128
isMarketingAgreed           0
storeId                     0
visit_count                 0
first_visit                 0
last_visit                  0
avg_revisit_days          213
pagerank                    0
degree                      0
betweenness                 0
closeness                   0
eigen                       0
community                 150
paidAmount                  0
days_since_first            0
days_since_last             0
revisited                   0
avg_revisit_days_imp        0
days_since_last_Q           0
visit_count_Q               0
avg_revisit_days_imp_Q      0
paidAmount_Q                0
pagerank_Q                  0
degree_Q                    0
closeness_Q                 0
betweenness_Q               0
eigen_Q                     0
recency_Q                   0
revisit_gap_Q               0
R_score                     0
F_score                     0
M_score                     0
N_score                     0
stratum                     0
total_score                 0
segment                     0
dtype: int64

In [19]:
control.isna().sum()

customerId                  0
fullName                    0
phoneNumber                 0
dateOfBirth               159
isMarketingAgreed           0
storeId                     0
visit_count                 0
first_visit                 0
last_visit                  0
avg_revisit_days          216
pagerank                    0
degree                      0
betweenness                 0
closeness                   0
eigen                       0
community                 143
paidAmount                  0
days_since_first            0
days_since_last             0
revisited                   0
avg_revisit_days_imp        0
days_since_last_Q           0
visit_count_Q               0
avg_revisit_days_imp_Q      0
paidAmount_Q                0
pagerank_Q                  0
degree_Q                    0
closeness_Q                 0
betweenness_Q               0
eigen_Q                     0
recency_Q                   0
revisit_gap_Q               0
R_score                     0
F_score                     0
M_score                     0
N_score                     0
stratum                     0
total_score                 0
segment                     0
dtype: int64

In [3]:
test.head()

,customerId,fullName,phoneNumber,dateOfBirth,isMarketingAgreed,storeId,visit_count,first_visit,last_visit,avg_revisit_days,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
0,01JCPX1R8TH8B5NSBBSKGVYNWE,배*우,************6097,1998-02-15,2024-11-15 03:15:42,3,1,2024-11-15 03:13:59.414151,2024-11-15 03:13:59.414151,NaN,...,1,1,2,1,1.5,1,1.0,1211,4.5,Dormant
1,01JMEGFN2FXFVJHJK8NFKQR267,박*성,************2198,2008-04-13,2025-02-19 07:07:49,3,2,2025-02-19 07:06:12.673435,2025-02-19 12:41:36.668337,0.232917,...,2,3,4,3,4.0,4,2.2,3442,13.2,VIP
2,01JCYQ8BN664JAR1R0ATKSH89Q,김*희,************2967,1999-04-28,2024-11-18 04:10:59,3,1,2024-11-18 04:07:38.242597,2024-11-18 04:07:38.242597,NaN,...,3,1,2,1,1.5,3,2.4,1232,7.9,At_Risk
3,01JJBZVDS867W3ANC9T1ESFAVM,D*********************E,************3762,1993-07-23,2025-01-24 11:17:32,3,1,2025-01-24 11:05:48.206615,2025-01-24 11:05:48.206615,NaN,...,2,3,2,3,2.0,3,2.4,3232,10.4,Growth
4,01JTZMR0E3T7GXWCVJZY4G2653,G***t,**********7216,NaN,2025-05-11 12:27:50,3,2,2025-05-11 12:22:31.641332,2025-05-11 12:26:27.153604,0.002726,...,4,4,4,4,4.0,1,3.8,4414,12.8,VIP

In [4]:
control.head()

,customerId,fullName,phoneNumber,dateOfBirth,isMarketingAgreed,storeId,visit_count,first_visit,last_visit,avg_revisit_days,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
0,01H9A0BE3PH0JVEEY4KDZT0Y5J,홍*걸,************9833,1988-05-12,2024-12-21 04:20:23,3,11,2023-09-02 03:52:45.381588,2025-03-15 03:44:27.335581,55.999424,...,3,3,3,3,3.5,4,2.4,3442,12.9,VIP
1,01JN2FCWFADYNYHF5SF99A3WCV,구*욱,************2338,1997-06-21,2025-02-27 01:13:38,3,1,2025-02-27 01:12:22.116300,2025-02-27 01:12:22.116300,NaN,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
2,01JP6GV9ZQ7GE471D99FEMJT00,G***t,**********1806,NaN,2025-03-13 01:13:21,3,1,2025-03-13 01:10:37.321087,2025-03-13 01:10:37.321087,NaN,...,4,3,1,3,1.5,3,3.4,3233,10.9,Loyal
3,01J7TAHP6DY6W2NZX8G1CBMFZX,장*영,************4475,2005-02-03,2024-09-15 07:53:37,3,1,2024-09-15 07:49:10.308058,2024-09-15 07:49:10.308058,NaN,...,3,1,3,1,2.0,1,2.6,1213,6.6,Dormant
4,01JFMDWPEB78E4T52NVZ1BBQB0,이*경,************6731,2001-11-21,2024-12-21 11:02:41,3,3,2024-12-21 10:58:12.414957,2025-05-10 05:14:09.275520,69.880537,...,4,4,3,4,3.5,4,3.6,4444,15.1,VIP

# 각 segment 비율 확인

In [5]:
test.groupby(['storeId','segment']).count()

                 customerId  fullName  phoneNumber  dateOfBirth  \
storeId segment
3       At_Risk          43        42           43           28
        Dormant          52        52           52           28
        Growth           44        44           44           28
        Loyal            46        46           46           29
        VIP              46        46           46           34
5       At_Risk           4         4            4            4
        Dormant           5         5            5            3
        Growth            2         2            2            2
        Loyal             4         4            4            2
        VIP               4         4            4            4
10028   At_Risk          23        23           23           10
        Dormant          23        23           23           15
        Growth           22        22           22           16
        Loyal            24        24           24           16
        VIP              21        21           21           16

                 isMarketingAgreed  visit_count  first_visit  last_visit  \
storeId segment
3       At_Risk                 43           43           43          43
        Dormant                 52           52           52          52
        Growth                  44           44           44          44
        Loyal                   46           46           46          46
        VIP                     46           46           46          46
5       At_Risk                  4            4            4           4
        Dormant                  5            5            5           5
        Growth                   2            2            2           2
        Loyal                    4            4            4           4
        VIP                      4            4            4           4
10028   At_Risk                 23           23           23          23
        Dormant                 23           23           23          23
        Growth                  22           22           22          22
        Loyal                   24           24           24          24
        VIP                     21           21           21          21

                 avg_revisit_days  pagerank  ...  betweenness_Q  eigen_Q  \
storeId segment                              ...
3       At_Risk                10        43  ...             43       43
        Dormant                 6        52  ...             52       52
        Growth                 12        44  ...             44       44
        Loyal                  24        46  ...             46       46
        VIP                    44        46  ...             46       46
5       At_Risk                 1         4  ...              4        4
        Dormant                 0         5  ...              5        5
        Growth                  1         2  ...              2        2
        Loyal                   3         4  ...              4        4
        VIP                     4         4  ...              4        4
10028   At_Risk                 6        23  ...             23       23
        Dormant                 0        23  ...             23       23
        Growth                  5        22  ...             22       22
        Loyal                  13        24  ...             24       24
        VIP                    21        21  ...             21       21

                 recency_Q  revisit_gap_Q  R_score  F_score  M_score  N_score  \
storeId segment
3       At_Risk         43             43       43       43       43       43
        Dormant         52             52       52       52       52       52
        Growth          44             44       44       44       44       44
        Loyal           46             46       46       46       46       46
        VIP             46             46       46       46       46       46
5       At_Risk          4              4        4        4        4        4
        Dormant          5              5        5        5        5        5
        Growth           2              2        2        2        2        2
        Loyal            4              4        4        4        4        4
        VIP              4              4        4        4        4        4
10028   At_Risk         23             23       23       23       23       23
        Dormant         23             23       23       23       23       23
        Growth          22             22       22       22       22       22
        Loyal           24             24       24       24       24       24
        VIP             21             21       21       21       21       21

                 stratum  total_score
storeId segment
3       At_Risk       43           43
        Dormant       52           52
        Growth        44           44
        Loyal         46           46
        VIP           46           46
5       At_Risk        4            4
        Dormant        5            5
        Growth         2            2
        Loyal          4            4
        VIP            4            4
10028   At_Risk       23           23
        Dormant       23           23
        Growth        22           22
        Loyal         24           24
        VIP           21           21

[15 rows x 37 columns]

In [6]:
control.groupby(['storeId','segment']).count()

                 customerId  fullName  phoneNumber  dateOfBirth  \
storeId segment
3       At_Risk          43        43           43           26
        Dormant          51        51           51           24
        Growth           44        44           44           25
        Loyal            46        46           46           23
        VIP              47        47           47           35
5       At_Risk           4         4            4            4
        Dormant           4         4            4            4
        Growth            3         3            3            2
        Loyal             3         3            3            3
        VIP               4         4            4            4
10028   At_Risk          24        24           24           10
        Dormant          23        23           23            5
        Growth           21        21           21            9
        Loyal            24        24           24           13
        VIP              21        21           21           16

                 isMarketingAgreed  visit_count  first_visit  last_visit  \
storeId segment
3       At_Risk                 43           43           43          43
        Dormant                 51           51           51          51
        Growth                  44           44           44          44
        Loyal                   46           46           46          46
        VIP                     47           47           47          47
5       At_Risk                  4            4            4           4
        Dormant                  4            4            4           4
        Growth                   3            3            3           3
        Loyal                    3            3            3           3
        VIP                      4            4            4           4
10028   At_Risk                 24           24           24          24
        Dormant                 23           23           23          23
        Growth                  21           21           21          21
        Loyal                   24           24           24          24
        VIP                     21           21           21          21

                 avg_revisit_days  pagerank  ...  betweenness_Q  eigen_Q  \
storeId segment                              ...
3       At_Risk                 7        43  ...             43       43
        Dormant                 4        51  ...             51       51
        Growth                 14        44  ...             44       44
        Loyal                  23        46  ...             46       46
        VIP                    42        47  ...             47       47
5       At_Risk                 3         4  ...              4        4
        Dormant                 0         4  ...              4        4
        Growth                  1         3  ...              3        3
        Loyal                   3         3  ...              3        3
        VIP                     4         4  ...              4        4
10028   At_Risk                 6        24  ...             24       24
        Dormant                 1        23  ...             23       23
        Growth                  5        21  ...             21       21
        Loyal                  12        24  ...             24       24
        VIP                    21        21  ...             21       21

                 recency_Q  revisit_gap_Q  R_score  F_score  M_score  N_score  \
storeId segment
3       At_Risk         43             43       43       43       43       43
        Dormant         51             51       51       51       51       51
        Growth          44             44       44       44       44       44
        Loyal           46             46       46       46       46       46
        VIP             47             47       47       47       47       47
5       At_Risk          4              4        4        4        4        4
        Dormant          4              4        4        4        4        4
        Growth           3              3        3        3        3        3
        Loyal            3              3        3        3        3        3
        VIP              4              4        4        4        4        4
10028   At_Risk         24             24       24       24       24       24
        Dormant         23             23       23       23       23       23
        Growth          21             21       21       21       21       21
        Loyal           24             24       24       24       24       24
        VIP             21             21       21       21       21       21

                 stratum  total_score
storeId segment
3       At_Risk       43           43
        Dormant       51           51
        Growth        44           44
        Loyal         46           46
        VIP           47           47
5       At_Risk        4            4
        Dormant        4            4
        Growth         3            3
        Loyal          3            3
        VIP            4            4
10028   At_Risk       24           24
        Dormant       23           23
        Growth        21           21
        Loyal         24           24
        VIP           21           21

[15 rows x 37 columns]

# 자세하게 보기

## ① test 그룹

In [9]:
test_brief = test.drop(['dateOfBirth', 'isMarketingAgreed','first_visit','last_visit'], axis=1)

In [10]:
test_brief.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 363 entries, 0 to 362
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customerId              363 non-null    object
 1   fullName                362 non-null    object
 2   phoneNumber             363 non-null    object
 3   storeId                 363 non-null    int64
 4   visit_count             363 non-null    int64
 5   avg_revisit_days        150 non-null    float64
 6   pagerank                363 non-null    float64
 7   degree                  363 non-null    float64
 8   betweenness             363 non-null    float64
 9   closeness               363 non-null    float64
 10  eigen                   363 non-null    float64
 11  community               213 non-null    float64
 12  paidAmount              363 non-null    float64
 13  days_since_first        363 non-null    int64
 14  days_since_last         363 non-null    int64
 15  revisited               363 non-null    int64
 16  avg_revisit_days_imp    363 non-null    float64
 17  days_since_last_Q       363 non-null    int64
 18  visit_count_Q           363 non-null    int64
 19  avg_revisit_days_imp_Q  363 non-null    int64
 20  paidAmount_Q            363 non-null    int64
 21  pagerank_Q              363 non-null    int64
 22  degree_Q                363 non-null    int64
 23  closeness_Q             363 non-null    int64
 24  betweenness_Q           363 non-null    int64
 25  eigen_Q                 363 non-null    int64
 26  recency_Q               363 non-null    int64
 27  revisit_gap_Q           363 non-null    int64
 28  R_score                 363 non-null    int64
 29  F_score                 363 non-null    float64
 30  M_score                 363 non-null    int64
 31  N_score                 363 non-null    float64
 32  stratum                 363 non-null    int64
 33  total_score             363 non-null    float64
 34  segment                 363 non-null    object
dtypes: float64(12), int64(19), object(4)
memory usage: 99.4+ KB

In [17]:
for id in test_brief['storeId'].unique():
    for seg in test_brief['segment'].unique():
        print('='*10, f'id : {id}, seg : {seg}','='*10)
        display(test_brief[(test_brief['storeId']==id) & (test_brief['segment']==seg)])

========== id : 3, seg : Dormant ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
0,01JCPX1R8TH8B5NSBBSKGVYNWE,배*우,************6097,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.0,1211,4.5,Dormant
7,01JGGPDZQHJF64BM835XF0DG2Z,임*성,************8892,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
19,01J9K59YMKERT6DCH9J7SZ08EZ,G***t,**********4877,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,3,1,2.0,1,2.4,1212,6.4,Dormant
21,01JDXXY28JT6HSD1YB8EVMC1M8,G***t,**********3851,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,3,1.2,1231,6.7,Dormant
38,01JN2V38V1MSH4X64DZDFBGS29,조*준,************2642,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,1,2.2,3212,7.7,Dormant
39,01JF1GCDW5AXRS74MZQK1V9AS5,김*수,************8793,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
46,01JBR4R13TDXTGDBRAX6N52YMP,박*민,**********8489,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,2,2.4,1222,6.9,Dormant
51,01J69CB70YZTER92AYS0ZX824Z,오*숙,************0622,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,3,1,2.0,1,2.4,1212,6.4,Dormant
54,01J9ZFTXN82S16VNJWJGGDR7QT,G***t,**********7061,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
68,01J74ZQRNHNFNBZ8T8TFQGKPZX,노*구,************6140,3,2,0.002110,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,2,1.0,1421,7.5,Dormant
69,01JDEEYFAXAFJ1NXZGFJ17TTDH,김*령,************7490,3,1,NaN,0.795489,5.0,0.0,0.619048,...,3,1,2,1,1.5,1,2.8,1213,6.3,Dormant
74,01J8YMH459CWVCDGXACVQQX7GW,G***t,**********2090,3,1,NaN,1.129733,8.0,0.0,0.722222,...,4,1,3,1,2.0,1,3.2,1213,7.2,Dormant
76,01J78NH5WD3HJKJ57WNGP1D6F1,K**O,**********0397,3,2,0.630979,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,1,1.0,1411,6.5,Dormant
77,01JNZ5BJKJMXG333AT452JTS9V,G***t,**********5951,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,1,2.2,3212,7.7,Dormant
81,01JE0T509JG7ATSMYNR4NK2X29,G***t,**********5474,3,1,NaN,0.961240,4.0,0.0,1.000000,...,3,2,2,2,1.5,1,3.2,2213,7.7,Dormant
83,01JEZCFWMACS2SYP4PNXYBRQWZ,윤*경,************1294,3,2,1.879147,0.000000,0.0,0.0,0.000000,...,1,2,4,2,3.5,1,1.2,2411,7.7,Dormant
86,01JB99TAWVVMM2FW25YE1BFY3X,G***t,**********7465,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
93,01JFPMZ9BENGF5JCC8E21GN9TP,박*훈,************7191,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
96,01J9AMTDY80MYTXSRK7RJJSYY9,G***t,**********3170,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,3,1,2.0,2,2.4,1222,7.4,Dormant
100,01JFPMSFJDWWXV2RGYYJRMCT33,G***t,**********0006,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
110,01JFCFH1H1HMZPHDVX2S2BKX2S,G***t,**********8876,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,2,1.2,2221,6.7,Dormant
119,01JFYP9XGH00WP8A6KGYPET6QS,G***t,**********9693,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
124,01J78CFBH44PCX9TAERRY86TED,정*빈,**********6305,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
125,01JEX7BX9EHTA39ZS4Z2YX2RFG,G***t,**********3022,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
126,01J6S6PV95CRGA6HPSXYEY1DNC,G***t,**********6702,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
129,01JPHPYJCNC2P5YMS5FA2RWSY3,G***t,**********2118,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,1,2.2,3212,7.7,Dormant
131,01J786NVPPNWBEW03RFKYKWM3P,김*분,************4707,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
136,01JAYZ1CRSN0V25V446ZAMQ5HV,G***t,**********4104,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
137,01JBX3M8TNST904GNGTQBQ9WRQ,G***t,**********8072,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.0,1211,4.5,Dormant
138,01JHCH8ZHB92CS0Z5F54YQFKKK,전*희,************0578,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
145,01J6E4TK5YK0THD3W8HYDKZEQT,G***t,**********1935,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
146,01JCAZSTRQYFG6MHKBTTG15F9R,G***t,**********2613,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,3,1.0,1231,6.5,Dormant
152,01JHVW1R5E7FEP14M8QC6Y9VPA,정*도,************2089,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
154,01JDBN5MB6AKYS7B1R1Z4WT66T,G***t,**********3454,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,2,1.2,1221,5.7,Dormant
156,01JHWBNFRWBH1DHQMY16290FTC,정*석,************9795,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,1,1.2,2211,6.2,Dormant
162,01J6KJEMNWVFRTMWBMYJB5KEYZ,홍*진,**********0499,3,1,NaN,0.750151,2.0,0.0,1.000000,...,2,1,3,1,2.0,1,2.2,1212,6.2,Dormant
164,01J7SRDGJ7DJ0EZBK7GHG14XQM,이*영,************2706,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
169,01J8YBV7GCH6BMV3M65R3K54BD,노*별,************9570,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
172,01JACH6VH82047KSR9MH5TD6GG,이*혜,************6296,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
175,01JHW7Q08Y48H2JYS9QV0W2HE4,G***t,**********9321,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
177,01J7J3XNJ7CXTYS9ETVYGDBBNC,G***t,**********8351,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
182,01JDPQ8Z51HA02M2H7CB85BSKS,오*재,************4044,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,2,1.2,1221,5.7,Dormant
184,01J8VAVW9KZ67HCXSQXDPJJ5CP,구**********H,*********4909,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
193,01JCAX9NAC4PW2D0F8C13PF77M,김*성,************7615,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,4,1.0,1241,7.5,Dormant
194,01JGAW5E3YNVPXWR5F4RX44VTZ,G***t,**********6240,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
195,01JAQ6RV66PYW4D4ANFHJYMQWE,김*미,************3728,3,2,2.827488,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,1,1.0,1411,6.5,Dormant
197,01HDRDSP2CF4PRPB7EB209FXRV,김*정,************9906,3,2,398.029255,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.0,2,1.0,1321,7.0,Dormant
201,01J7ZRNR9M2P7E3JKA32VW6YNB,윤*철,************8821,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
208,01JFHZHK74XB6KXHS7Z0Q1WN31,박*현,************0130,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,1,1.2,2211,5.7,Dormant
212,01JH05APAZEX9ET1X9K1RTWX3T,전*아,************6996,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,1,1.2,2211,6.2,Dormant
215,01JDY53T2N9VGS286QZWCWH8V5,권*섭,************3304,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,2,1.2,1221,5.7,Dormant
218,01JBB1EZGK52E85443S0RR0PSW,박*현,************9014,3,2,1.468882,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,2,1.0,1421,7.5,Dormant

========== id : 3, seg : VIP ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
1,01JMEGFN2FXFVJHJK8NFKQR267,박*성,************2198,3,2,0.232917,0.000000,0.0,0.000000,0.000000,...,2,3,4,3,4.0,4,2.2,3442,13.2,VIP
4,01JTZMR0E3T7GXWCVJZY4G2653,G***t,**********7216,3,2,0.002726,1.402891,2.0,2.000000,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,VIP
5,01JR9RK6M0Z7A0NTNWY4HWH649,G***t,**********9905,3,2,0.241227,0.961240,1.0,0.000000,1.000000,...,4,4,4,4,4.0,1,3.6,4414,12.6,VIP
8,01JSKVXANDXYD1F7B440WENRH6,오*상,************3775,3,2,2.216546,0.961240,1.0,0.000000,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,VIP
9,01JKQSKWBSVMKJ25WAKBVFPNQ9,G***t,**********6224,3,2,0.087646,0.961240,1.0,0.000000,1.000000,...,3,3,4,3,3.5,3,3.2,3433,12.7,VIP
12,01JHPQV3SAJ7EV0XK3B2ZWXBP3,서*우,************8388,3,6,59.592798,1.818332,17.0,382.000000,0.554348,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP
15,01JDEF0FVY0VFKXJXE5Y22AD3G,T*********a,************6505,3,5,15.294699,1.478989,9.0,60.000000,0.722222,...,4,3,3,3,3.5,4,3.8,3444,14.3,VIP
23,01HJDGRGXK5F2AY0DE0EC6Y8Q8,이*진,************5007,3,8,55.728301,2.868489,11.0,142.000000,0.823529,...,4,2,3,2,3.5,4,3.8,2444,13.3,VIP
32,01JGAWWXS52ZF6XW8D4CC4TJEZ,전*주,************2715,3,4,33.089790,1.622970,7.0,16.000000,1.000000,...,4,4,3,4,3.5,4,4.0,4444,15.5,VIP
33,01JT9YM7HE59EB3H28VK61GZSF,G***t,**********6850,3,2,0.091457,0.000000,0.0,0.000000,0.000000,...,2,4,4,4,4.0,2,2.4,4422,12.4,VIP
34,01JNTGWV6SMEA1EZKS6WJ30818,G***t,**********2858,3,3,0.081664,0.000000,0.0,0.000000,0.000000,...,2,3,4,3,4.0,4,2.2,3442,13.2,VIP
35,01JD6YBE6SPFNGF70FMBJT86EY,이*호,************8682,3,13,6.172741,1.408808,3.0,4.000000,1.000000,...,4,3,4,3,4.0,4,3.6,3444,14.6,VIP
56,01JT51PVM35WHH50Q4XQ8D0P9V,G***t,**********2127,3,2,12.222632,1.408808,3.0,4.000000,1.000000,...,4,4,4,4,4.0,2,4.0,4424,14.0,VIP
58,01JBVFYPTJYW7S6Z6ZJJZ27X6A,남*서,************0803,3,5,22.147408,0.961240,2.0,0.000000,1.000000,...,3,3,3,3,3.5,4,2.6,3443,13.1,VIP
62,01J14NZ3JCF5AFWGTM5WJZXPVX,천*현,************7760,3,4,77.275884,1.402891,2.0,2.000000,1.000000,...,4,3,3,3,3.5,4,3.6,3444,14.1,VIP
64,01JK33AE6871DPX3GKG0J06X55,황*범,************0574,3,1,NaN,1.068343,6.0,0.000000,0.750000,...,4,3,2,3,2.0,4,3.6,3244,12.6,VIP
70,01JFY7KMYN4D9R8QNX2PSCN2QF,G***t,**********1503,3,4,0.420024,1.622796,3.0,16.000000,0.714286,...,4,2,4,2,4.0,4,3.8,2444,13.8,VIP
73,01JFPEXWQV2BWNP31CT87ZQAQQ,이*식,************3425,3,3,0.029546,1.088985,8.0,0.000000,0.583333,...,4,2,4,2,4.0,4,3.4,2443,13.4,VIP
79,01J66W8A4C1XH3Y3CR99YJYRX9,김*은,************1263,3,4,72.665269,0.961240,2.0,0.000000,1.000000,...,3,4,3,4,3.5,4,2.6,4443,14.1,VIP
88,01J9WVNBC6K9WYJMSQF89E26G1,송*원,************2934,3,7,3.999688,1.531882,18.0,4.666667,1.000000,...,4,1,4,1,4.0,4,3.8,1444,12.8,VIP
89,01JRC60NEFPXS4CMCBRQ4VEE5B,서*한,************9506,3,1,NaN,0.961240,2.0,0.000000,1.000000,...,4,4,1,4,2.0,4,3.6,4244,13.6,VIP
92,01JKSM3A1TNNRB4DRH2F39JB48,이*현,************2400,3,2,0.047356,0.961240,2.0,0.000000,1.000000,...,3,3,4,3,3.5,3,3.2,3433,12.7,VIP
97,01JJ42JKMNXDJX2BZ72N1W245G,오*연,************7549,3,3,10.398627,1.127803,5.0,0.000000,0.750000,...,4,3,4,3,4.0,2,3.4,3423,12.4,VIP
102,01JS6TXE7VTDQTQP99CV7EDPJ1,김*진,************3474,3,2,0.110216,0.000000,0.0,0.000000,0.000000,...,2,4,4,4,4.0,2,2.4,4422,12.4,VIP
103,01JS8VF9SJTP97M1397P6M3XP4,이*은,************3819,3,2,0.001227,1.364909,4.0,6.000000,1.000000,...,4,4,4,4,4.0,3,4.0,4434,15.0,VIP
114,01JQKA1VKR76WXRZR3MQWZCZ4C,G***t,*********7404,3,2,0.110767,0.961240,7.0,0.000000,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,VIP
115,01HK24MHTERBCZZY8GEC0X37AQ,박*린,************5973,3,2,365.771524,1.393989,3.0,6.000000,0.800000,...,4,2,3,2,3.0,4,3.6,2344,12.6,VIP
139,01JQ19M6XHTVNTJ0DNVWMC4A0W,최*서,************9454,3,2,0.254274,0.961240,1.0,0.000000,1.000000,...,4,3,4,3,4.0,3,3.4,3433,13.4,VIP
140,01J4VAA701N7GZ8H8DNA7P0NRG,김*구,************0332,3,7,42.333037,1.324368,5.0,8.000000,1.000000,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP
141,01JH5CTBM5WTGXGV061QP1KYMX,김*호,************9610,3,4,0.544284,1.193532,3.0,50.000000,0.538462,...,3,2,4,2,4.0,3,3.6,2434,12.6,VIP
142,01JQDFA4E6Z82WMAGAF4KX86VW,G***t,**********0611,3,4,12.084099,2.095004,23.0,300.000000,1.000000,...,4,4,4,4,4.0,4,4.0,4444,16.0,VIP
149,01JQ1EGWT8S047FRTJQXC8H2C2,김*엽,************5584,3,2,0.095645,1.324368,5.0,8.000000,1.000000,...,4,3,4,3,4.0,3,4.0,3434,14.0,VIP
159,01JM6AYG339E224ZGQPXHKN7FE,조*은,************6753,3,2,6.965751,0.000000,0.0,0.000000,0.000000,...,2,3,4,3,4.0,4,2.2,3442,13.2,VIP
173,01JHY2GKAQC47TPZ1VS7VY9YNG,김*호,************3307,3,3,0.044429,1.458632,8.0,24.000000,1.000000,...,4,2,4,2,4.0,4,4.0,2444,14.0,VIP
174,01JPM5XPKZE4GGDH4H7P4VPK4P,신*빈,************5153,3,3,14.542933,0.000000,0.0,0.000000,0.000000,...,2,4,3,4,3.5,4,2.2,4442,13.7,VIP
190,01JNTB6KKG6T996W5KSJ6FJDJP,G***t,**********3908,3,2,0.972345,1.246566,2.0,4.000000,0.750000,...,4,3,4,3,4.0,2,3.6,3424,12.6,VIP
191,01JSK1S1J305SYF301DRWN7AV0,김*형,************7060,3,2,0.238155,0.961240,3.0,0.000000,1.000000,...,4,4,4,4,4.0,3,4.0,4434,15.0,VIP
210,01JME47H6E1KW13YC9ZTBTW3XA,황*진,************6605,3,2,81.279622,0.961240,5.0,0.000000,1.000000,...,3,4,3,4,3.5,3,3.4,4433,13.9,VIP
213,01JGTB7353H5EAR4JMK20F75MR,김*정,************1620,3,2,0.259294,0.961240,2.0,0.000000,1.000000,...,3,2,4,2,3.5,4,3.0,2443,12.5,VIP
221,01HMR4D5XRNW013CBR2AR76WNV,임*은,************7719,3,3,178.000688,1.452297,6.0,26.000000,0.583333,...,4,2,3,2,3.5,4,3.8,2444,13.3,VIP
222,01JQRC8CE1ZC4PKS9X9EP3AT6Z,김*민,************8472,3,2,0.098416,0.961240,1.0,0.000000,1.000000,...,4,4,4,4,4.0,1,3.6,4414,12.6,VIP
223,01JKTD6PJRWVET2PMX10ZX5TYC,이*휘,************8848,3,2,1.728781,0.000000,0.0,0.000000,0.000000,...,2,3,4,3,4.0,4,2.2,3442,13.2,VIP
225,01HJSY1QBJPK12Z705XVWTYD5T,임*란,************7085,3,6,84.700712,1.960005,5.0,16.000000,1.000000,...,4,3,3,3,3.5,4,3.8,3444,14.3,VIP
227,01HJMPASC1RHZFJGXJ39BEB2H5,장*근,************1241,3,2,409.033426,1.402891,2.0,2.000000,1.000000,...,4,3,3,3,3.0,4,3.6,3344,13.6,VIP
229,01JMPJCPA9CAV83HQGS2GW85T5,G***t,**********3301,3,3,24.019812,0.961240,5.0,0.000000,1.000000,...,3,4,3,4,3.5,4,3.4,4443,14.9,VIP
230,01J0CZN5947FRDP93MN1528JWC,고*언,************4336,3,22,14.290151,2.624389,13.0,184.000000,0.842105,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP

========== id : 3, seg : At_Risk ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
2,01JCYQ8BN664JAR1R0ATKSH89Q,김*희,************2967,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.4,1232,7.9,At_Risk
20,01JFPRC1D2XCQRS9633855X012,L*********T,************2129,3,2,364.853054,0.000000,0.0,0.0,0.000000,...,1,2,3,2,3.0,2,1.2,2321,8.2,At_Risk
22,01JK2VMK5SNQQEXC02MQQSC8J0,G***t,**********9271,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,2,3,2.0,2,2.2,3222,9.2,At_Risk
25,01JJXFM570YY6YV6JRSTN4B6TB,김*진,************8963,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,2,3,2.0,1,2.2,3212,8.2,At_Risk
26,01JHWJ7PSY8YB9Z5EXZP70ZW44,J****************M,************9550,3,2,0.555202,0.632704,3.0,0.0,0.464286,...,2,2,4,2,3.5,1,2.4,2412,8.9,At_Risk
28,01JNTK0EDW3BYNZX0QVF8CRVVQ,G***t,*********2381,3,1,NaN,1.036144,5.0,0.0,0.700000,...,4,3,1,3,1.5,1,3.6,3214,9.1,At_Risk
36,01JQ92CKF8SF3CY96GRJ20S203,신*민,************3113,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,1,2.2,4212,8.7,At_Risk
41,01JCW3X8GQW35AGEAH5XBXRMTV,G***t,**********7737,3,1,NaN,0.961240,3.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.6,1233,8.1,At_Risk
45,01J6XJEJPWCHCKKGA754NSW9VP,이*지,************9350,3,2,71.000183,0.548155,2.0,0.0,0.555556,...,2,1,3,1,3.0,3,2.2,1332,9.2,At_Risk
49,01HPGWPH2654CG8VY4CMXDD3PP,이*민,************5548,3,2,318.755079,0.000000,0.0,0.0,0.000000,...,1,2,3,2,3.0,3,1.0,2331,9.0,At_Risk
50,01JJTMDRZWX4BTY9JVM52DJXJM,G***t,**********6601,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,3,2,3,2.0,1,3.2,3213,9.2,At_Risk
53,01JM6D3PXTYN18AT82A8X9ZWWV,임*정,************9553,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
55,01JHCABMKWWN9854R7F6YP20CX,G***t,**********1147,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,4,1.2,2241,9.2,At_Risk
59,01JQTVZG429D1YQR1N4JB11Q7E,박*준,************4856,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,1,2.2,4212,8.7,At_Risk
66,01JC9WCVZJ0TDJTNPYGY4C0E7Q,박*경,************8413,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,4,2.6,1243,9.1,At_Risk
85,01JHD18THPPHF8C758VFDDTGHF,곽*연,************4285,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,3,1.2,2231,8.2,At_Risk
87,01J8Y7E1J2BCP3NH1QEGZKNW0H,G***t,**********6705,3,2,0.371004,0.961240,1.0,0.0,1.000000,...,3,1,4,1,3.5,1,2.4,1412,7.9,At_Risk
90,01JCW3R2XPM8F098554RX5S0KG,G***t,**********3210,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.6,1233,8.1,At_Risk
91,01JGN4CQNXXTG2ADBQ7RWS84BM,전*현,************1565,3,1,NaN,0.691063,2.0,0.0,0.338028,...,2,2,2,2,2.0,3,2.2,2232,9.2,At_Risk
101,01JF4KSG1JS94DMZ32P8M0DFG7,최*규,************1982,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,4,1.2,2241,8.7,At_Risk
106,01JJNNXAJ71X403FKFKVX9H6SW,G***t,**********9888,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,2,3,2.0,2,2.0,3222,9.0,At_Risk
107,01J915Z4J493J7KWR293TCW75Z,신*영,************2248,3,2,0.900392,0.961240,4.0,0.0,1.000000,...,3,1,4,1,3.5,1,2.8,1413,8.3,At_Risk
117,01JHZ1P1HEYNFRXGJB7H31YED5,김*휘,************0686,3,1,NaN,0.961240,4.0,0.0,1.000000,...,3,2,2,2,2.0,2,3.2,2223,9.2,At_Risk
128,01JNDK9H15F0KD12B735MZMFQG,G***t,**********4185,3,1,NaN,0.589992,2.0,0.0,0.316456,...,2,3,1,3,1.5,1,2.4,3212,7.9,At_Risk
130,01JQ14MJGSMMSBFR172K4HBPEP,G***t,**********4865,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
143,01JP7F3323F8P2FP2VDPT5J6W0,최*수,************8781,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
155,01JH004GBB6H7D3S54SY6RDQ6N,임*란,************2282,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,3,1.2,2231,8.2,At_Risk
161,01JBR911TN982SKAPSFBXPWP14,전*진,************7122,3,1,NaN,0.961240,4.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.8,1233,8.3,At_Risk
165,01JBVBAC49GBF8GANXXPJ8JTR6,장*숙,************4470,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.6,1233,8.1,At_Risk
166,01HGYPPCFRAB1M6ZXRENR62CJM,고*희,************8251,3,2,326.957508,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.0,4,1.0,1341,9.0,At_Risk
168,01JFVJKZ2P24HTNZRBTQC7HD9H,G***t,**********4058,3,2,0.096547,0.000000,0.0,0.0,0.000000,...,1,2,4,2,3.5,2,1.2,2421,8.7,At_Risk
170,01JCA2WYKDCDKN2DHNEPF5S1CF,정*규,************8816,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.4,1232,7.9,At_Risk
178,01JPGV91Z5XF43FYT9DE2TFC3D,G***t,**********9906,3,1,NaN,1.020023,6.0,0.0,0.875000,...,4,3,1,3,1.5,1,3.6,3214,9.1,At_Risk
179,01J9ZMMVP4ZVX1NJEKRPJ467JT,B*******************O,************6271,3,2,28.945233,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.0,3,1.0,1331,8.0,At_Risk
183,01JNAPARVVW2SCP54FWPY3F88B,G***t,**********0443,3,1,NaN,0.980824,8.0,0.0,0.722222,...,4,3,1,3,1.5,1,3.6,3214,9.1,At_Risk
192,01JK2H1E65NRTXECDW9TCJWF6N,권*지,************4607,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,3,2,3,2.0,1,3.2,3213,9.2,At_Risk
196,01JQB656M3CJ51RC7VJSZ3H5RJ,G***t,**********2527,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,1,2.2,4212,8.7,At_Risk
198,01JQZYYAC8RPVGQBHMTD9NXTDK,L*******G,************1214,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,1,2.2,4212,8.7,At_Risk
203,01JJ100G1YRG82T89CGZZPZ1Z5,배*우,************2199,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,2,2,2,2.0,2,2.0,2222,8.0,At_Risk
205,01J7DSX4Y1EA4YWZTSS6BGZGD0,성*영,************6962,3,1,NaN,0.961240,4.0,0.0,1.000000,...,3,1,3,1,2.0,2,2.8,1223,7.8,At_Risk
207,01JFSB1MPTS0N8HPSYPYCZVA7W,김*현,************7348,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,2,3.0,2223,8.5,At_Risk
209,01JPKMMTTTK43TG6G1WYJP7BFZ,G***t,**********6388,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
217,01HM8PG2PFQ6NV8ZKDBXPVJY0G,NaN,************5848,3,2,315.147014,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.0,4,1.0,1341,9.0,At_Risk

========== id : 3, seg : Growth ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
3,01JJBZVDS867W3ANC9T1ESFAVM,D*********************E,************3762,3,1,NaN,0.546252,1.0,0.0,0.600000,...,2,3,2,3,2.0,3,2.4,3232,10.4,Growth
6,01JEJHWNBK2X31KBHP87E0Z1DW,이*택,************2242,3,1,NaN,0.935614,2.0,0.0,0.666667,...,3,2,2,2,1.5,4,2.8,2243,10.3,Growth
10,01JQDPJHRXJV9554D3EXDJQ97T,이*현,************4285,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,2,2.2,4222,9.7,Growth
11,01JG6HQC090KB4G163X0JB2Y3R,G***t,**********7090,3,1,NaN,0.533020,1.0,0.0,0.538462,...,2,2,2,2,1.5,4,2.4,2242,9.9,Growth
16,01JHJ65RYZHAJP283HCSFTF814,박*진,************5565,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,3,3.0,2233,10.0,Growth
18,01JE2QVAM0VN7X4VM0H1JVZK8W,G***t,**********2275,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,3,2.8,2233,9.3,Growth
24,01JNTVK5WRCZAPCFP5YFMFBYAP,김*우,************6591,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,3,1,3,1.5,3,3.2,3233,10.7,Growth
27,01JJBZY7H8XFB3D2WPTCY4C1GG,H****************A,************6052,3,2,0.049080,0.000000,0.0,0.0,0.000000,...,2,3,4,3,3.5,2,2.0,3422,10.5,Growth
29,01JSTPW3YP2VN3PTB0AEB2XGEY,박*민,************1262,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
30,01HSJSRTC8B1NV6ZRGXHDB20JH,G***t,**********5731,3,3,134.458003,0.317955,1.0,0.0,0.533333,...,2,2,3,2,3.5,2,1.8,2422,9.3,Growth
31,01HSJ9Q7X72YRFQ0CB658FCX4A,정*림,************2705,3,4,55.448723,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.5,4,1.0,1441,9.5,Growth
43,01JGQTB3KFA440ZYPQE0F7WZSD,박*정,************4292,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,3,3.0,2233,10.0,Growth
47,01JT4XYMQSQM1XN068MRHTRVSX,최*진,************7791,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
48,01JQE0QE3VHNR31CBCBW4JWEWT,서정,*************0276,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,1.5,1,3.6,4214,10.1,Growth
60,01J8C56WB5GH98JDMCPN19X265,김*순,************3785,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,3,1,2.0,4,2.6,1243,9.6,Growth
61,01JS8KE8FMPCSVMJG3S0WTB7N3,손*혁,************9511,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,2,2.4,4222,10.4,Growth
67,01JT52QF23QPAZ2063S0SYZ6CB,박*지,************8620,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,2,2.4,4222,10.4,Growth
78,01JN8JVP14D90T63F2YNAEV210,정*원,************6127,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,3,1,3,1.5,3,3.2,3233,10.7,Growth
84,01JMR4C7HCGMGKVJMYHMF33WT4,G***t,**********0397,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,4,2.2,3242,10.7,Growth
98,01JS6SGCZM7R21TT2S0SFWAJZH,정*경,************8677,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
99,01JRPKJSCFTBA094JYC12C1712,G***t,**********2146,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
104,01JH2R0HH07DMS42KAVPPJP77H,G***t,**********5133,3,1,NaN,0.740415,1.0,0.0,0.666667,...,2,2,2,2,2.0,3,2.4,2232,9.4,Growth
108,01JE048TTH2ZHA4YR9MT9SXESG,김*민,************9561,3,1,NaN,1.000605,3.0,0.0,0.625000,...,4,2,2,2,1.5,3,3.2,2233,9.7,Growth
113,01JTFET5YY8ZJT9SW33PK4P3JJ,G***t,**********9989,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
118,01J7T1TBKD5K907KYRCF03F8CX,김*홍,************5877,3,1,NaN,0.842701,4.0,0.0,0.400000,...,3,1,3,1,2.0,4,2.4,1242,9.4,Growth
127,01JMYA0VDT9FY0X7T50TPJVVG9,최*미,************9494,3,1,NaN,0.850039,3.0,0.0,0.185355,...,2,3,1,3,1.5,3,2.8,3233,10.3,Growth
133,01JKYS6E3AERAF2KKFHS0NETNC,김*경,************0306,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,3,2.2,3232,9.7,Growth
135,01JNG44GSGBYMKCC682Y4GZ5SR,G***t,**********9628,3,1,NaN,0.988412,6.0,0.0,0.446809,...,4,3,1,3,1.5,2,3.4,3223,9.9,Growth
144,01J75BX20BA0ZA896N9KA39AY6,G***t,**********2886,3,2,2.028714,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,4,1.0,1441,9.5,Growth
150,01J37X6TGEPJHG62KPM3KGQY1B,G***t,**********0336,3,2,188.767589,0.000000,0.0,0.0,0.000000,...,1,3,3,3,3.0,3,1.0,3331,10.0,Growth
157,01JKAFASGZRAC4X8EW97EZH623,G***t,**********9969,3,2,0.016581,0.000000,0.0,0.0,0.000000,...,2,3,4,3,3.5,2,2.2,3422,10.7,Growth
167,01JF1NSKKFJNKS4P5YEX90N2KY,강*경,************9194,3,2,0.274517,0.961240,1.0,0.0,1.000000,...,3,2,4,2,3.5,1,2.8,2413,9.3,Growth
171,01JHCB4D4W15BZ157MXVD2AVFW,G***t,**********7934,3,2,0.155883,1.189650,6.0,160.0,0.363636,...,4,2,4,2,3.5,1,3.6,2414,10.1,Growth
180,01JTTFSDZ81GN27S0FRA00ZZ14,G***t,**********2216,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,2,2.4,4222,10.4,Growth
181,01JNAJR4SBFSM6M660ZA5RQBBT,조*정,************3658,3,2,2.797087,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,1,2.2,3412,10.2,Growth
186,01JSKRQPXAYT6JDVECXT6PP9ZB,김*민,************5463,3,1,NaN,0.249098,1.0,0.0,0.411765,...,2,4,1,4,2.0,1,2.6,4213,9.6,Growth
187,01JT51Q3YCX226SWBE5RQM9BNZ,G***t,**********5230,3,1,NaN,0.944951,2.0,0.0,0.750000,...,3,4,1,4,2.0,1,3.2,4213,10.2,Growth
188,01JDBM4PM8J88V53RHP75PNKRT,G***t,**********5596,3,2,0.002006,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,4,1.2,1441,9.7,Growth
189,01JEG18ZYZ0ZS0ZETNRCNBVWFG,단*은,************1534,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,4,2.8,2243,10.3,Growth
202,01JNAHJ4Q26YDP7KK03TCTRT1G,G***t,**********8026,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,4,2.2,3242,10.7,Growth
204,01JQ6BWVZP9X0NC6ADPT4N37GM,황*호,************0721,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,1.5,1,3.6,4214,10.1,Growth
206,01J3CE2151B1YS1N0XAQEMYZKX,류*효,**********2486,3,6,31.010428,0.000000,0.0,0.0,0.000000,...,1,2,3,2,3.5,4,1.0,2441,10.5,Growth
214,01JPH4R31GV9ES9ZAPDQ1VXPGP,권*현,************8320,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,3,1,3,1.5,3,3.2,3233,10.7,Growth
216,01HWYXQ4GM1XK6TW0RXTZZABXT,이*빈,************0983,3,4,43.295433,0.961240,2.0,0.0,1.000000,...,3,1,3,1,3.5,3,2.6,1433,10.1,Growth

========== id : 3, seg : Loyal ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
13,01JFRV27HHHCBNK580G6XKCXG6,윤*령,************5330,3,2,0.000689,0.961240,1.0,0.0,1.000000,...,3,2,4,2,3.5,3,3.0,2433,11.5,Loyal
14,01JDHF7TZ46GWQAYGGZYJA79VJ,정*래,************2649,3,3,24.503569,0.961240,1.0,0.0,1.000000,...,3,2,3,2,3.5,4,2.6,2443,12.1,Loyal
17,01JBX72M6DTKJ82J0RCWB4DV92,G***t,**********1750,3,3,35.504002,0.961240,1.0,0.0,1.000000,...,3,2,3,2,3.5,3,2.4,2432,10.9,Loyal
37,01JE37CYMDR2KMY7028Y2S5VV3,김*섭,**********3905,3,2,0.108071,0.961240,1.0,0.0,1.000000,...,3,2,4,2,3.5,3,2.8,2433,11.3,Loyal
40,01JT87D4RXR8JT6SBBE9KATJYW,G***t,**********4865,3,1,NaN,0.961240,4.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
42,01JSC2K04R4223VJN1PK2TNPN2,G***t,**********5120,3,2,0.694753,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,1,2.4,4412,11.4,Loyal
44,01JQTXPF0CP3R1N04KZHS20WF7,김*정,************2133,3,3,7.984442,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,2,2.2,4422,12.2,Loyal
52,01JD43TJFT3T2RJR71QC4G8E1R,황*성,************8996,3,3,11.550376,0.000000,0.0,0.0,0.000000,...,1,2,4,2,4.0,4,1.0,2441,11.0,Loyal
57,01JRMG1698KH3AKPKDKZP1VD84,김*희,************0234,3,3,0.596540,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,1,2.4,4412,11.4,Loyal
63,01JKJEKAQ8D823HGYEHD0XVRC3,김*한,************0368,3,2,0.117965,0.000000,0.0,0.0,0.000000,...,2,3,4,3,3.5,3,2.2,3432,11.7,Loyal
65,01JHFECZ76BCRCF1D2KAFDHK42,G***t,**********1899,3,1,NaN,1.085179,8.0,0.0,0.263844,...,4,2,2,2,2.0,4,3.2,2243,11.2,Loyal
71,01JQ1ADTK87C41MRWTW15BJM3J,장*원,************5299,3,1,NaN,0.961240,2.0,0.0,1.000000,...,4,3,1,3,1.5,3,3.4,3233,10.9,Loyal
72,01JRYYFQBYFX5AJJ3ZJ65X7WR0,G***t,**********6112,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
75,01JQJF0R6RX2CXED08D1WPKSGF,엄*현,************6530,3,1,NaN,0.961240,6.0,0.0,1.000000,...,4,4,1,4,1.5,2,3.8,4224,11.3,Loyal
80,01JF4GQGWEVJ96N316EK9N2M1P,이*지,************5958,3,6,4.644169,0.000000,0.0,0.0,0.000000,...,1,2,4,2,4.0,4,1.2,2441,11.2,Loyal
82,01JRQ1EN6P2HRZQ2GDT8S3N04T,G***t,**********8055,3,2,0.274790,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,1,2.4,4412,11.4,Loyal
94,01JF1QP9R72JMRRSSJRJAXPTBQ,최*원,************4593,3,2,47.075174,0.961240,4.0,0.0,1.000000,...,3,3,3,3,3.0,3,3.2,3333,12.2,Loyal
95,01JNAES5YFD4DYS478QC38221K,전*지,************3389,3,2,2.866185,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,3,2.2,3432,12.2,Loyal
105,01J9ZX9QEAA12TB3HP5RRPM7WN,G***t,**********0773,3,3,0.499330,1.292189,6.0,10.0,1.000000,...,4,1,4,1,4.0,3,3.8,1434,11.8,Loyal
109,01HZ9N2YYEWDDGQJHWSJR9QDD0,G***t,**********9916,3,4,37.709513,0.961240,2.0,0.0,1.000000,...,3,1,3,1,3.5,4,2.6,1443,11.1,Loyal
111,01JHZ8Q9FKSA3B2W3AR8CCYTA3,G***t,**********6912,3,1,NaN,1.023220,6.0,0.0,0.800000,...,4,2,2,2,2.0,4,3.4,2243,11.4,Loyal
112,01JTD5Z6E3PTKVQ10NRQ4AP1FB,G***t,**********7682,3,1,NaN,0.972857,10.0,0.0,0.592593,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal
116,01JV15B83475G1QAYZT6BSR06S,박*욱,************8613,3,1,NaN,0.961240,2.0,0.0,1.000000,...,4,4,1,4,2.0,1,3.8,4214,10.8,Loyal
120,01JFSM0ZJXH03WGPVTTHH2FHPK,김*영,************0375,3,3,0.301260,1.028985,3.0,26.0,0.400000,...,2,2,4,2,4.0,2,3.2,2423,11.2,Loyal
121,01JRHJKGBHV3C95DHX62PQHSK9,박*현,************2722,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
122,01JJR1ZZ8KGVZNS5C50P9EYQY2,최*학,************8884,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,3,2,3,2.0,3,3.2,3233,11.2,Loyal
123,01JCSGPCKY48Q42K6MEEEH4XZ1,이*호,************1424,3,2,0.334942,1.242117,4.0,184.0,0.337500,...,4,1,4,1,3.5,3,3.6,1434,11.1,Loyal
132,01JT87DBYRJHT54YBR6696EWGM,G***t,**********6364,3,1,NaN,0.961240,4.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
134,01HPDNYF6TG1ADMGQPVB9G8Y5D,이*헌,************7524,3,4,78.077933,1.402891,2.0,2.0,1.000000,...,4,1,3,1,3.5,4,3.6,1444,12.1,Loyal
147,01JN8M9ZTF7ME8EJQAC231SAH1,G***t,**********0605,3,1,NaN,1.015113,6.0,0.0,0.538462,...,4,3,1,3,1.5,3,3.6,3234,11.1,Loyal
148,01JR4E34Z9WDMHNVCB5K8GVGSM,하*은,************7115,3,2,2.328998,0.910341,4.0,138.0,0.440678,...,2,4,4,4,4.0,1,3.0,4413,12.0,Loyal
151,01JT87FXCNKX3TJ1KRDGP9JX6M,G***t,**********3656,3,1,NaN,0.961240,4.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
153,01JV15AA4Z4VZ70P1RDMP6N80Z,G***t,**********6699,3,1,NaN,0.961240,2.0,0.0,1.000000,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal
158,01JCA4XZMMGSHDRYTY22ZKGFDQ,차*범,**********5068,3,2,56.104480,0.961240,1.0,0.0,1.000000,...,3,2,3,2,3.0,4,2.4,2342,11.4,Loyal
160,01JR4SFPQG3DCYNTXEANWM67ET,김*민,************6520,3,2,0.706837,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,1,2.2,4412,11.2,Loyal
163,01JTMEQQ4K1E6A9S5ACHCY553D,G***t,**********5495,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal
176,01J447RP2DXDEFKWH2NRQG7VTF,김*림,************3874,3,3,80.883237,0.961240,2.0,0.0,1.000000,...,3,2,3,2,3.5,4,2.6,2443,12.1,Loyal
185,01JEWMN3XYF8A27BXC7HG4EJAZ,마고,**********5435,3,8,6.438237,0.000000,0.0,0.0,0.000000,...,1,2,4,2,4.0,4,1.2,2441,11.2,Loyal
199,01JQ3WKB22B7D25CEBVXFHS8TH,이*신,************2368,3,2,0.519159,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,3,2.2,3432,12.2,Loyal
200,01JSK1YR98HD5BWJBMX73WQNVS,이*지,************2061,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal
211,01JMVY6CFSRWGE9FCDB7B0GQ7D,G***t,**********5153,3,1,NaN,0.961240,3.0,0.0,1.000000,...,3,3,1,3,1.5,3,3.4,3233,10.9,Loyal
219,01JTN5A251AQSV4PM76EJGEC4Y,G***t,**********7243,3,1,NaN,0.961240,7.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
220,01JN89SB90KSVBF9WDKAW8BQYE,최*희,************0803,3,1,NaN,0.961240,9.0,0.0,1.000000,...,3,3,1,3,1.5,4,3.4,3243,11.9,Loyal
224,01JT53ADPT7XGANHQRD9HCJBE4,백*수,************6472,3,1,NaN,0.961240,6.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
226,01JR5BJVBB10KAKSBDW71QM890,김*영,************4583,3,1,NaN,0.669141,2.0,0.0,0.379310,...,2,4,1,4,1.5,3,2.4,4232,10.9,Loyal
228,01JV3V5021JTV9TFPSFSFM9YXX,박*영,************7083,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal

========== id : 5, seg : Dormant ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
233,01JAYRDYZM78ZMN75XVCV9M45E,김*민,************1767,5,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,1,2,1.0,2,1.2,2121,6.2,Dormant
234,01J7QGD1CS3YS50DWCX1PGJBMJ,이*윤,************1176,5,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,2,1.0,1221,5.5,Dormant
235,01JGTC4CRSST66KG8YP4YXBSJA,심*우,************3657,5,1,NaN,0.000000,0.0,0.0,0.000000,...,1,3,1,3,1.5,1,1.4,3211,6.9,Dormant
242,01J64PVW1MSXS4BSG7WW35CJZZ,G***t,**********2506,5,1,NaN,0.445658,1.0,0.0,0.428571,...,2,1,2,1,1.5,4,1.8,1242,8.3,Dormant
243,01JBXSHCTXAMS9Z7T2A7DBCRJR,G***t,**********1914,5,1,NaN,0.000000,0.0,0.0,0.000000,...,1,3,1,3,1.0,1,1.2,3111,6.2,Dormant

========== id : 5, seg : VIP ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
232,01JAY33R5XQ9A6ZXNY9WF2P81X,이*빈,************3373,5,4,4.419770,1.364909,4.0,6.0,1.000000,...,4,2,4,2,4.0,3,4.0,2434,13.0,VIP
238,01JAM9FA29W01Z50CSR3R17RX2,정*정,************2677,5,5,11.308003,1.402891,2.0,2.0,1.000000,...,4,2,3,2,3.5,4,3.6,2444,13.1,VIP
245,01J6VWNE93K2KSM2Y8FMDPPTCM,김*준,************0661,5,7,8.331215,1.173648,4.0,48.0,0.352113,...,4,2,3,2,3.5,4,3.6,2444,13.1,VIP
248,01JMC5G3MK9Y2CEG76CRC9PW8A,김*나,************4770,5,3,8.955304,0.961240,1.0,0.0,1.000000,...,3,3,3,3,3.0,4,3.2,3343,13.2,VIP

========== id : 5, seg : At_Risk ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
236,01JEB9NT047YBTQ093F3S2A33F,전*정,************7180,5,2,1.617315,0.933899,4.0,0.0,0.7,...,2,2,4,2,3.5,1,2.6,2413,9.1,At_Risk
239,01JAPG2A2X967KNQQ75NQRYJXX,김*채,************4693,5,1,NaN,0.000000,0.0,0.0,0.0,...,1,4,2,4,1.5,2,1.2,4221,8.7,At_Risk
240,01J7AK8095EN3ZYDRJKWRR9G4T,김*영,************7198,5,1,NaN,0.961240,3.0,0.0,1.0,...,3,4,2,4,1.5,1,2.6,4213,9.1,At_Risk
249,01JEZAG864D3EAA783RC4X5EV0,김*은,************9860,5,1,NaN,0.961240,1.0,0.0,1.0,...,3,2,1,2,1.5,2,3.0,2223,8.5,At_Risk

========== id : 5, seg : Growth ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
241,01HARR323KHW4NDARB2VGHBQYD,오*윤,*********4493,5,4,8.329685,1.277794,4.0,8.0,0.833333,...,4,1,3,1,3.0,3,3.8,1334,10.8,Growth
244,01JEWGB5VDYX0J38NN68YXQW7Y,김*은,************3084,5,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,1,2,1.5,3,2.8,2233,9.3,Growth

========== id : 5, seg : Loyal ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
231,01JPPQNMAWNV1X7QJS9DT42TE0,G***t,**********8455,5,2,0.034605,0.00000,0.0,0.0,0.0,...,1,3,4,3,3.5,3,1.4,3431,10.9,Loyal
237,01JH85DA18HJ4EYJVQ2KK662GM,김*정,**********9368,5,1,NaN,0.96124,1.0,0.0,1.0,...,3,3,1,3,1.5,4,3.2,3243,11.7,Loyal
246,01JSKDV23WE7B3B2YMN6DQT88G,G***t,**********0111,5,4,5.341879,0.00000,0.0,0.0,0.0,...,2,4,4,4,4.0,2,2.4,4422,12.4,Loyal
247,01JS16XSXKZJC5ZRZNTBMY75B3,강*용,************0531,5,3,1.438860,0.00000,0.0,0.0,0.0,...,2,4,4,4,3.5,3,2.2,4432,12.7,Loyal

========== id : 10028, seg : Dormant ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
259,01HAKWDHX2VCAXR366TM0W6R1M,문*영,*********2792,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,2,1,3,1,2.0,1,2.0,1212,6.0,Dormant
263,01J9D83GP9JKREB9J6H2BRRGV1,박*영,************8343,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
269,01J84Y68Z1Y6C3P9G4Q1C8NRJX,조*일,************0317,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.2,1211,4.7,Dormant
285,01J7N0QJ5TGEQRHTRMJ0JZ4YRN,이*은,************7039,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.0,1211,4.5,Dormant
294,01J6VEB3S4W7SEDXCNCPHSZCH3,G***t,**********6479,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
300,01J89YREX426JM4HC4GXF1J50M,G***t,**********5908,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,1,2.6,2213,7.1,Dormant
304,01J93P2KGBMTPDN1VT0Q5MKXNX,G***t,**********4092,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
309,01J7J7ZBVNS9V1GMSANRACB7R7,김*은,************3655,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,3,1.0,1231,6.5,Dormant
311,01J6XHT4TC5BGXDMHR2DSVS0DP,이*민,************6104,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
321,01J825R7VX59XNMCXF238J7M3R,정*주,************0627,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,1,2.6,2213,7.1,Dormant
328,01J7AZT8MCG8F20544JAW6HT6Y,G***t,**********1657,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,1,2.6,1213,6.1,Dormant
330,01J8XWBD7X7D927FATEF35PSET,심*민,************8352,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
332,01J784Y59DAVK50MVKJDFSM620,G***t,**********8970,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,3,1,2.0,2,2.4,1222,7.4,Dormant
337,01J7AK8095EN3ZYDRJKWRR9G4T,김*영,************7198,10028,1,NaN,0.741479,2.0,0.0,0.538462,...,2,1,2,1,1.5,2,2.0,1222,6.5,Dormant
339,01J7AAHFXFHQJ1F3PG0NHKE390,서*수,************3477,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
341,01J5WQ0C8KQMK62FA2ST4T5R4F,트**티,**********7776,10028,1,NaN,0.961240,11.0,0.0,1.000000,...,3,1,3,1,2.0,1,3.0,1213,7.0,Dormant
346,01J7CYHTN25HRTY8PBM43ETJN1,G***t,**********3056,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,1,2.8,1213,6.3,Dormant
349,01J78M4Q9CETX1XZSE8RFMRDC8,G***t,**********1784,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
350,01JAPG2A2X967KNQQ75NQRYJXX,김*채,************4693,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,3,1,3,1.5,1,1.4,3211,6.9,Dormant
351,01J9RAB5MF1EG5WE6Z6619KRTS,G***t,**********6969,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
353,01J7MQ20HY587DRKPHD92RX309,김*근,************6119,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,1,2.4,1212,5.9,Dormant
358,01J7TK1SM7J0QXWRPPDNEZPTN2,김*환,************6466,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.2,1211,4.7,Dormant
362,01J84MSVRT0HWN4T9NB0DP0Q0Y,김*주,************1793,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,1,2.6,2213,7.1,Dormant

========== id : 10028, seg : VIP ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
264,01J672R2JVDM6H86DPEQQJ366W,권*수,************8480,10028,3,38.413885,0.961240,1.0,0.0,1.000000,...,3,4,3,4,3.5,3,2.4,4432,12.9,VIP
266,01JD223QSYQTTXEY1AF0PDVPFM,G***t,**********9833,10028,2,0.188950,0.961240,1.0,0.0,1.000000,...,4,4,4,4,4.0,3,3.8,4434,14.8,VIP
276,01JNZSJ8S4EW5DVC9MJXYZ8AF0,안*민,************9128,10028,6,12.789424,2.595191,18.0,96264.0,0.079987,...,4,4,3,4,3.5,4,3.6,4444,15.1,VIP
278,01JDC5964EM5JFTRC0X6R2M0KX,G***t,**********5629,10028,2,0.332635,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,3,2.4,4432,13.4,VIP
282,01JAHGYND3Z51A9B1XW272J4CJ,이*영,************3080,10028,3,19.090853,0.000000,0.0,0.0,0.000000,...,1,4,3,4,3.5,4,1.4,4441,12.9,VIP
283,01J4P57HC7F5QFB15BESCPK2TA,홍*지,************5855,10028,3,60.853311,1.326765,4.0,10.0,0.750000,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP
286,01JA9MJ7QTQ661QEX8N1DDH5BV,G***t,**********8891,10028,3,14.314542,0.546252,1.0,0.0,0.600000,...,2,4,3,4,3.5,4,2.4,4442,13.9,VIP
287,01JDE94A2PH0HG7JWGQHQB5HQX,신*명,************7659,10028,2,0.418740,0.538994,2.0,0.0,0.083196,...,2,4,4,4,4.0,3,2.8,4433,13.8,VIP
289,01JDPA7N5349FHRTRJXH1HBM74,김*현,************1905,10028,11,10.689828,2.423364,20.0,15904.0,0.077044,...,4,4,3,4,3.5,4,3.6,4444,15.1,VIP
299,01JAYH736AYB7G9FVMZ0NFSYY3,최*정,************0528,10028,4,48.980444,1.050762,3.0,3540.0,0.100192,...,2,4,3,4,3.5,4,3.2,4443,14.7,VIP
307,01JAQ9HMDBTCKJ9Z95HZ5RHTH7,김*슬,************4524,10028,6,10.771924,1.641876,7.0,22.0,1.000000,...,4,4,3,4,3.5,4,4.0,4444,15.5,VIP
308,01JD65RAZBK03KEQ1G6MB19M4T,이*훈,************7141,10028,3,4.534097,1.572566,5.0,18.0,0.857143,...,4,4,4,4,4.0,3,3.8,4434,14.8,VIP
319,01J9AQX4M93849DZ052AMR1RK3,이*광,************0669,10028,2,6.999416,1.256885,3.0,10.0,0.666667,...,4,2,4,2,3.5,4,3.8,2444,13.3,VIP
322,01JAA5M5SAV6N2KK6KCJH493GX,김*영,************4138,10028,2,7.828484,0.961240,2.0,0.0,1.000000,...,3,3,4,3,3.5,4,3.4,3443,13.9,VIP
331,01JA9QXTN06K5H0GZ7NGPMYNXE,김*준,************3990,10028,5,1.004722,1.539243,5.0,12.0,1.000000,...,4,3,4,3,4.0,3,4.0,3434,14.0,VIP
342,01JA23C6CCD8B4MBAD31BZ8FWR,조*이,************5065,10028,4,69.695357,1.402891,2.0,2.0,1.000000,...,4,4,3,4,3.5,4,4.0,4444,15.5,VIP
344,01J7NDA8R08KMZRTAQ7GAEQ77D,김*우,************6784,10028,6,1.960434,1.488684,4.0,28.0,0.700000,...,4,2,4,2,4.0,4,3.8,2444,13.8,VIP
347,01JDE567X0RBEVN44XR1J3N3S3,김*태,************4434,10028,2,0.997250,0.961240,1.0,0.0,1.000000,...,4,4,4,4,4.0,3,3.8,4434,14.8,VIP
352,01J7JQ5ND43HZ2B6DJQAF4AJ58,G***t,**********5077,10028,6,18.628381,1.402891,2.0,2.0,1.000000,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP
360,01JC7HJAHSMRZ548MTGPKM6S3Q,G***t,**********3524,10028,3,33.605528,0.961240,3.0,0.0,1.000000,...,4,4,3,4,3.5,2,3.8,4424,13.3,VIP
361,01JA7PJK9R85VJFEX6ABM96W4W,박*건,************9377,10028,3,20.469381,1.024255,2.0,6.0,0.666667,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP

========== id : 10028, seg : At_Risk ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
251,01J70G6GRWT6Q91RW1XC6G71NQ,G***t,**********4949,10028,3,2.778279,0.961240,2.0,0.0,1.000000,...,3,1,4,1,4.0,1,2.6,1413,8.6,At_Risk
252,01J7QA8Q5FYK01EGHWVF75NXVQ,G***t,**********1438,10028,1,NaN,0.741479,2.0,0.0,0.538462,...,2,1,2,1,1.5,3,2.2,1232,7.7,At_Risk
253,01HATVZ2DFPPC3ERXCYXMVXXS6,김*하,*********1835,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,3,3,3,2.0,2,1.0,3221,8.0,At_Risk
254,01J86VFF2XEXFXSGQX0VAM2ZAV,G***t,**********1853,10028,2,2.913214,0.000000,0.0,0.0,0.000000,...,1,2,4,2,3.5,2,1.2,2421,8.7,At_Risk
255,01J7GADQAH0DYB35F7YE83A22W,L**********G,************7632,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.4,1232,7.9,At_Risk
257,01JC4RQJ55GA521K0TVFHY486B,G***t,**********3950,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
260,01JBGYKPBJ2PYXXWB9N55ABAZV,임*진,************1015,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
280,01J8CGC0DKSVXFHRQ117CE7P6J,박*영,************7217,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,2,2.6,2223,8.1,At_Risk
281,01J61WKHQENHNETE4NYERM2AE4,김*태,**********6674,10028,2,0.249847,0.961240,1.0,0.0,1.000000,...,3,1,4,1,3.5,2,2.4,1422,8.9,At_Risk
284,01J8F5EMWFW8N3YH05JQXF5X1G,G***t,**********9738,10028,1,NaN,0.444939,1.0,0.0,0.114420,...,2,2,2,2,1.5,2,2.2,2222,7.7,At_Risk
290,01J9XCJDFQCZV45MGBY33X830Q,G***t,**********0707,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,3,1.2,2231,8.2,At_Risk
296,01J8EYQ3RF6HE815W4T8KQ37BK,Z*********N,************9222,10028,1,NaN,0.961240,3.0,0.0,1.000000,...,3,2,2,2,1.5,1,3.2,2213,7.7,At_Risk
297,01JCD7MFFNA2WKA8H2SX5NMMT9,G***t,**********8389,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,2.0,1,2.4,3212,8.4,At_Risk
301,01J9K89692FKPXSF473X4MDVHE,G***t,**********8900,10028,2,0.209449,0.350679,1.0,0.0,0.500000,...,2,2,4,2,3.5,1,2.2,2412,8.7,At_Risk
302,01J7TFMXHSTRRPE4JN04B2GV28,G***t,**********8090,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,4,2.4,1242,8.9,At_Risk
317,01J8VV6DQ4YGMXS6RSC8BHAHEN,W*******G,************9333,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,1,3.0,2213,7.5,At_Risk
318,01JBR4HMBRQ3K8E2A93V6X6PYA,G***t,**********1116,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
326,01J7WE5PXENDXJBMNZD8BW8WSY,G***t,**********2595,10028,2,0.197164,0.402733,1.0,0.0,0.440000,...,2,1,4,1,3.5,2,2.0,1422,8.5,At_Risk
333,01J9X01039B34Y6RSAQAQ7D4PW,한*민,************4211,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,1,3.0,2213,8.0,At_Risk
336,01J844YY71YHDXW277AEHX203B,G***t,**********4458,10028,1,NaN,0.740415,1.0,0.0,0.666667,...,2,2,2,2,1.5,2,2.2,2222,7.7,At_Risk
338,01JACT8B3KHADWCH6HVG4HTEPM,김*호,************7740,10028,2,2.612117,0.000000,0.0,0.0,0.000000,...,1,3,4,3,3.5,1,1.4,3411,8.9,At_Risk
348,01JAQ2R10KPX4BGVZAP71N0XVW,G***t,**********2414,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
355,01HARR323KHW4NDARB2VGHBQYD,오*윤,*********4493,10028,1,NaN,0.445658,1.0,0.0,0.428571,...,2,1,3,1,2.0,3,1.8,1232,7.8,At_Risk

========== id : 10028, seg : Growth ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
256,01JAPKNW9TJ8EPDDB9DGXF4KDE,G***t,**********1266,10028,1,NaN,0.740415,1.0,0.0,0.666667,...,2,3,1,3,1.5,2,2.6,3223,9.1,Growth
258,01J6EWVAPX8E59ERSK1M6QNZB4,G***t,**********8204,10028,3,2.519891,0.000000,0.0,0.0,0.000000,...,1,1,4,1,4.0,4,1.0,1441,10.0,Growth
267,01J7QVPA905HHJCFXABKCPND2K,G***t,**********4628,10028,2,0.026823,0.961240,1.0,0.0,1.000000,...,3,1,4,1,3.5,3,2.4,1432,9.9,Growth
271,01JCA3PXPNVNEXVBQWVKZZRRZT,박*화,************2229,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,2.0,2,3.6,3224,10.6,Growth
277,01JB945EJ1FCGCNVVXFHCQ7HH2,G***t,**********0515,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,2,3.6,3224,10.1,Growth
291,01JBR1J5R5VKCJWV74A4GZ1VX0,장*원,*********2465,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,4,2.2,3242,10.7,Growth
295,01JD4E17BSYN6WQ34YKH8XSZC0,배*롬,************2162,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,2,2.4,4222,10.4,Growth
298,01JCWB1Z4705RHXQ3BEMQA8J1T,곽*환,************3995,10028,1,NaN,0.346411,1.0,0.0,0.202335,...,2,4,1,4,2.0,1,2.6,4213,9.6,Growth
303,01J84ZW37M7HYD5TGPNC61PA7B,전*헌,************6535,10028,1,NaN,0.961240,3.0,0.0,1.000000,...,3,1,2,1,1.5,4,3.0,1243,9.5,Growth
305,01JC0HHEM1N2WH9BY7SPB326XW,김*훈,************7988,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,2,3.6,3224,10.1,Growth
306,01JBZQNVH4B8SM4R72DMCS41Q5,김*현,************6951,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,4,3,1,3,1.5,2,3.8,3224,10.3,Growth
310,01JBXVJD52N7C3TCRV8X7559Z6,오*식,************2854,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,4,3,1,3,1.5,2,3.8,3224,10.3,Growth
312,01J93SHAQZJC75HT86F78XM4M6,G***t,**********5425,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,2,3.0,2223,9.0,Growth
313,01JC9ZJGVS43CR8FBAD8F8TFED,조*혜,************8772,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,2.0,2,3.6,3224,10.6,Growth
315,01JAWCT0QHAS04N2YWAC5307VE,육*연,************6923,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,1,3.6,3214,9.1,Growth
323,01JBXP4SSRPMV50XCF3NN5S05E,최*인,************1488,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,3,2.2,3232,9.7,Growth
324,01J9T5GDZEZN2NTW9G1GC96G5A,박*영,************3559,10028,2,0.844480,0.961240,1.0,0.0,1.000000,...,3,2,4,2,3.5,1,3.0,2413,9.5,Growth
325,01JA2T09H5ANX9K8KE9M27N7C3,최*지,************8586,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,4,1.2,2241,9.2,Growth
327,01HBQFZMCNA4CBAXPWPEXVNHFT,김*서,************2370,10028,2,0.878986,0.961240,2.0,0.0,1.000000,...,2,4,4,4,3.5,1,2.2,4412,10.7,Growth
329,01J6KE1NB9A6R8CQ590B9H8PNR,조*선,************3887,10028,2,0.239533,1.333106,3.0,12.0,0.714286,...,4,1,4,1,3.5,1,3.8,1414,9.3,Growth
335,01J9QHARR2RM53M30AWJC0N9ZZ,김*정,************7176,10028,1,NaN,0.607275,2.0,0.0,0.515152,...,2,2,2,2,2.0,3,2.4,2232,9.4,Growth
340,01J95JMWEV0XVJYBF8Q6N15WYB,G***t,**********2958,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,2,3.0,2223,9.0,Growth

========== id : 10028, seg : Loyal ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
250,01JACXQ5V4K02X9VM62XAG4A7X,이*나,************2192,10028,1,NaN,0.961240,5.0,0.0,1.000000,...,3,3,1,3,1.5,4,3.4,3243,11.9,Loyal
261,01JCCR356MHERES0VASPB0VPMX,김*경,************4679,10028,2,0.574963,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,2,2.4,3422,11.4,Loyal
262,01JCCKQRWHE9EMYS1K0R7F5SW8,윤*경,************8148,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,4,4,1,4,2.0,3,3.8,4234,12.8,Loyal
265,01J6C4GSH2TEFQ16SRMEW09TBP,G***t,**********1855,10028,3,1.922233,1.408808,3.0,4.0,1.000000,...,4,1,4,1,4.0,3,3.8,1434,11.8,Loyal
268,01JAM7XR2ZXG18QE51FS9NEF2A,G***t,**********2753,10028,2,0.078769,0.000000,0.0,0.0,0.000000,...,1,3,4,3,3.5,4,1.4,3441,11.9,Loyal
270,01JCHTJ1T674V695NH542JAHB6,G***t,**********8903,10028,2,0.051779,0.961240,1.0,0.0,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,Loyal
272,01JBRMEN3K7F4GWYKM82RZ6RBZ,문*우,************5815,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,3,3.6,3234,11.1,Loyal
273,01JCF58YZE17NJH4HBJD5MGZ74,임*진,************4784,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
274,01J7MRZG685D26H8ZJ8AFK054Y,황*란,************4855,10028,2,26.242714,0.961240,2.0,0.0,1.000000,...,3,2,3,2,3.0,3,2.8,2333,10.8,Loyal
275,01JCYZHFHV4D7AKH2AB37KNCH2,하*빈,************5214,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,3,3.8,4234,12.8,Loyal
279,01JB1G9PGDMK4BQ29TZAS9E0JF,도*훈,************5084,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,3,3.6,3234,11.1,Loyal
288,01JBXSS2PYT3NRQMD67JAPZ9GJ,박*애,************6940,10028,2,0.026796,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,2,2.2,3422,11.2,Loyal
292,01J6ZWVY598Q0231A15CDM5P01,G***t,**********8997,10028,3,4.306247,0.961240,1.0,0.0,1.000000,...,3,1,4,1,4.0,4,2.4,1442,11.4,Loyal
293,01JCQS0KBQWB39ZZ7ZSJWZYZVF,G***t,**********2365,10028,2,0.930704,0.961240,1.0,0.0,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,Loyal
314,01J8MAXMCZHS2F1CDVNVJM99F6,장*준,************8541,10028,2,28.979989,0.625220,2.0,0.0,0.531250,...,2,3,3,3,3.0,4,2.4,3342,12.4,Loyal
316,01JDHB85J5K7WNJ4F697AS56Y2,김*준,************6417,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
320,01J7GCSWE2W71AZGBMTZB9AJTE,G***t,**********9222,10028,2,25.656785,1.402891,2.0,2.0,1.000000,...,4,2,3,2,3.0,4,3.8,2344,12.8,Loyal
334,01JAMT3AVYB3A9CXMGR82WNJC2,김*현,************2548,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,3,3.6,3234,11.1,Loyal
343,01J9AQFPM25TFH2NM6CR0ZE73Y,주*빈,************7511,10028,2,167.255254,1.310494,4.0,3540.0,0.083577,...,4,4,3,4,3.0,1,3.6,4314,11.6,Loyal
345,01J9T2NB44EG7R1G30E4KD4D68,안*빈,************6003,10028,3,0.710830,1.587920,8.0,30.0,1.000000,...,4,2,4,2,4.0,1,4.0,2414,11.0,Loyal
354,01JCJN74J3BMN21M4PKNRMMP7D,강*팔,************7391,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,1,3.8,4214,10.8,Loyal
356,01J0JM2DFHVBKZSKHJY53BW8TQ,정*윤,************1807,10028,2,0.218913,1.401974,4.0,10.0,0.666667,...,4,1,4,1,3.5,3,3.8,1434,11.3,Loyal
357,01JCYV3G35RTZNHHZEX3TJSW3E,G***t,**********1131,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
359,01JD72KPBASQCTD7XHYSWNCM2S,G***t,**********5675,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal

## ② control 그룹

In [20]:
control_brief = control.drop(['dateOfBirth', 'isMarketingAgreed','first_visit','last_visit'], axis=1)

In [21]:
control_brief.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customerId              362 non-null    object
 1   fullName                362 non-null    object
 2   phoneNumber             362 non-null    object
 3   storeId                 362 non-null    int64
 4   visit_count             362 non-null    int64
 5   avg_revisit_days        146 non-null    float64
 6   pagerank                362 non-null    float64
 7   degree                  362 non-null    float64
 8   betweenness             362 non-null    float64
 9   closeness               362 non-null    float64
 10  eigen                   362 non-null    float64
 11  community               219 non-null    float64
 12  paidAmount              362 non-null    float64
 13  days_since_first        362 non-null    int64
 14  days_since_last         362 non-null    int64
 15  revisited               362 non-null    int64
 16  avg_revisit_days_imp    362 non-null    float64
 17  days_since_last_Q       362 non-null    int64
 18  visit_count_Q           362 non-null    int64
 19  avg_revisit_days_imp_Q  362 non-null    int64
 20  paidAmount_Q            362 non-null    int64
 21  pagerank_Q              362 non-null    int64
 22  degree_Q                362 non-null    int64
 23  closeness_Q             362 non-null    int64
 24  betweenness_Q           362 non-null    int64
 25  eigen_Q                 362 non-null    int64
 26  recency_Q               362 non-null    int64
 27  revisit_gap_Q           362 non-null    int64
 28  R_score                 362 non-null    int64
 29  F_score                 362 non-null    float64
 30  M_score                 362 non-null    int64
 31  N_score                 362 non-null    float64
 32  stratum                 362 non-null    int64
 33  total_score             362 non-null    float64
 34  segment                 362 non-null    object
dtypes: float64(12), int64(19), object(4)
memory usage: 99.1+ KB

In [22]:
for id in control_brief['storeId'].unique():
    for seg in control_brief['segment'].unique():
        print('='*10, f'id : {id}, seg : {seg}','='*10)
        display(test_brief[(test_brief['storeId']==id) & (test_brief['segment']==seg)])

========== id : 3, seg : VIP ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
1,01JMEGFN2FXFVJHJK8NFKQR267,박*성,************2198,3,2,0.232917,0.000000,0.0,0.000000,0.000000,...,2,3,4,3,4.0,4,2.2,3442,13.2,VIP
4,01JTZMR0E3T7GXWCVJZY4G2653,G***t,**********7216,3,2,0.002726,1.402891,2.0,2.000000,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,VIP
5,01JR9RK6M0Z7A0NTNWY4HWH649,G***t,**********9905,3,2,0.241227,0.961240,1.0,0.000000,1.000000,...,4,4,4,4,4.0,1,3.6,4414,12.6,VIP
8,01JSKVXANDXYD1F7B440WENRH6,오*상,************3775,3,2,2.216546,0.961240,1.0,0.000000,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,VIP
9,01JKQSKWBSVMKJ25WAKBVFPNQ9,G***t,**********6224,3,2,0.087646,0.961240,1.0,0.000000,1.000000,...,3,3,4,3,3.5,3,3.2,3433,12.7,VIP
12,01JHPQV3SAJ7EV0XK3B2ZWXBP3,서*우,************8388,3,6,59.592798,1.818332,17.0,382.000000,0.554348,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP
15,01JDEF0FVY0VFKXJXE5Y22AD3G,T*********a,************6505,3,5,15.294699,1.478989,9.0,60.000000,0.722222,...,4,3,3,3,3.5,4,3.8,3444,14.3,VIP
23,01HJDGRGXK5F2AY0DE0EC6Y8Q8,이*진,************5007,3,8,55.728301,2.868489,11.0,142.000000,0.823529,...,4,2,3,2,3.5,4,3.8,2444,13.3,VIP
32,01JGAWWXS52ZF6XW8D4CC4TJEZ,전*주,************2715,3,4,33.089790,1.622970,7.0,16.000000,1.000000,...,4,4,3,4,3.5,4,4.0,4444,15.5,VIP
33,01JT9YM7HE59EB3H28VK61GZSF,G***t,**********6850,3,2,0.091457,0.000000,0.0,0.000000,0.000000,...,2,4,4,4,4.0,2,2.4,4422,12.4,VIP
34,01JNTGWV6SMEA1EZKS6WJ30818,G***t,**********2858,3,3,0.081664,0.000000,0.0,0.000000,0.000000,...,2,3,4,3,4.0,4,2.2,3442,13.2,VIP
35,01JD6YBE6SPFNGF70FMBJT86EY,이*호,************8682,3,13,6.172741,1.408808,3.0,4.000000,1.000000,...,4,3,4,3,4.0,4,3.6,3444,14.6,VIP
56,01JT51PVM35WHH50Q4XQ8D0P9V,G***t,**********2127,3,2,12.222632,1.408808,3.0,4.000000,1.000000,...,4,4,4,4,4.0,2,4.0,4424,14.0,VIP
58,01JBVFYPTJYW7S6Z6ZJJZ27X6A,남*서,************0803,3,5,22.147408,0.961240,2.0,0.000000,1.000000,...,3,3,3,3,3.5,4,2.6,3443,13.1,VIP
62,01J14NZ3JCF5AFWGTM5WJZXPVX,천*현,************7760,3,4,77.275884,1.402891,2.0,2.000000,1.000000,...,4,3,3,3,3.5,4,3.6,3444,14.1,VIP
64,01JK33AE6871DPX3GKG0J06X55,황*범,************0574,3,1,NaN,1.068343,6.0,0.000000,0.750000,...,4,3,2,3,2.0,4,3.6,3244,12.6,VIP
70,01JFY7KMYN4D9R8QNX2PSCN2QF,G***t,**********1503,3,4,0.420024,1.622796,3.0,16.000000,0.714286,...,4,2,4,2,4.0,4,3.8,2444,13.8,VIP
73,01JFPEXWQV2BWNP31CT87ZQAQQ,이*식,************3425,3,3,0.029546,1.088985,8.0,0.000000,0.583333,...,4,2,4,2,4.0,4,3.4,2443,13.4,VIP
79,01J66W8A4C1XH3Y3CR99YJYRX9,김*은,************1263,3,4,72.665269,0.961240,2.0,0.000000,1.000000,...,3,4,3,4,3.5,4,2.6,4443,14.1,VIP
88,01J9WVNBC6K9WYJMSQF89E26G1,송*원,************2934,3,7,3.999688,1.531882,18.0,4.666667,1.000000,...,4,1,4,1,4.0,4,3.8,1444,12.8,VIP
89,01JRC60NEFPXS4CMCBRQ4VEE5B,서*한,************9506,3,1,NaN,0.961240,2.0,0.000000,1.000000,...,4,4,1,4,2.0,4,3.6,4244,13.6,VIP
92,01JKSM3A1TNNRB4DRH2F39JB48,이*현,************2400,3,2,0.047356,0.961240,2.0,0.000000,1.000000,...,3,3,4,3,3.5,3,3.2,3433,12.7,VIP
97,01JJ42JKMNXDJX2BZ72N1W245G,오*연,************7549,3,3,10.398627,1.127803,5.0,0.000000,0.750000,...,4,3,4,3,4.0,2,3.4,3423,12.4,VIP
102,01JS6TXE7VTDQTQP99CV7EDPJ1,김*진,************3474,3,2,0.110216,0.000000,0.0,0.000000,0.000000,...,2,4,4,4,4.0,2,2.4,4422,12.4,VIP
103,01JS8VF9SJTP97M1397P6M3XP4,이*은,************3819,3,2,0.001227,1.364909,4.0,6.000000,1.000000,...,4,4,4,4,4.0,3,4.0,4434,15.0,VIP
114,01JQKA1VKR76WXRZR3MQWZCZ4C,G***t,*********7404,3,2,0.110767,0.961240,7.0,0.000000,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,VIP
115,01HK24MHTERBCZZY8GEC0X37AQ,박*린,************5973,3,2,365.771524,1.393989,3.0,6.000000,0.800000,...,4,2,3,2,3.0,4,3.6,2344,12.6,VIP
139,01JQ19M6XHTVNTJ0DNVWMC4A0W,최*서,************9454,3,2,0.254274,0.961240,1.0,0.000000,1.000000,...,4,3,4,3,4.0,3,3.4,3433,13.4,VIP
140,01J4VAA701N7GZ8H8DNA7P0NRG,김*구,************0332,3,7,42.333037,1.324368,5.0,8.000000,1.000000,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP
141,01JH5CTBM5WTGXGV061QP1KYMX,김*호,************9610,3,4,0.544284,1.193532,3.0,50.000000,0.538462,...,3,2,4,2,4.0,3,3.6,2434,12.6,VIP
142,01JQDFA4E6Z82WMAGAF4KX86VW,G***t,**********0611,3,4,12.084099,2.095004,23.0,300.000000,1.000000,...,4,4,4,4,4.0,4,4.0,4444,16.0,VIP
149,01JQ1EGWT8S047FRTJQXC8H2C2,김*엽,************5584,3,2,0.095645,1.324368,5.0,8.000000,1.000000,...,4,3,4,3,4.0,3,4.0,3434,14.0,VIP
159,01JM6AYG339E224ZGQPXHKN7FE,조*은,************6753,3,2,6.965751,0.000000,0.0,0.000000,0.000000,...,2,3,4,3,4.0,4,2.2,3442,13.2,VIP
173,01JHY2GKAQC47TPZ1VS7VY9YNG,김*호,************3307,3,3,0.044429,1.458632,8.0,24.000000,1.000000,...,4,2,4,2,4.0,4,4.0,2444,14.0,VIP
174,01JPM5XPKZE4GGDH4H7P4VPK4P,신*빈,************5153,3,3,14.542933,0.000000,0.0,0.000000,0.000000,...,2,4,3,4,3.5,4,2.2,4442,13.7,VIP
190,01JNTB6KKG6T996W5KSJ6FJDJP,G***t,**********3908,3,2,0.972345,1.246566,2.0,4.000000,0.750000,...,4,3,4,3,4.0,2,3.6,3424,12.6,VIP
191,01JSK1S1J305SYF301DRWN7AV0,김*형,************7060,3,2,0.238155,0.961240,3.0,0.000000,1.000000,...,4,4,4,4,4.0,3,4.0,4434,15.0,VIP
210,01JME47H6E1KW13YC9ZTBTW3XA,황*진,************6605,3,2,81.279622,0.961240,5.0,0.000000,1.000000,...,3,4,3,4,3.5,3,3.4,4433,13.9,VIP
213,01JGTB7353H5EAR4JMK20F75MR,김*정,************1620,3,2,0.259294,0.961240,2.0,0.000000,1.000000,...,3,2,4,2,3.5,4,3.0,2443,12.5,VIP
221,01HMR4D5XRNW013CBR2AR76WNV,임*은,************7719,3,3,178.000688,1.452297,6.0,26.000000,0.583333,...,4,2,3,2,3.5,4,3.8,2444,13.3,VIP
222,01JQRC8CE1ZC4PKS9X9EP3AT6Z,김*민,************8472,3,2,0.098416,0.961240,1.0,0.000000,1.000000,...,4,4,4,4,4.0,1,3.6,4414,12.6,VIP
223,01JKTD6PJRWVET2PMX10ZX5TYC,이*휘,************8848,3,2,1.728781,0.000000,0.0,0.000000,0.000000,...,2,3,4,3,4.0,4,2.2,3442,13.2,VIP
225,01HJSY1QBJPK12Z705XVWTYD5T,임*란,************7085,3,6,84.700712,1.960005,5.0,16.000000,1.000000,...,4,3,3,3,3.5,4,3.8,3444,14.3,VIP
227,01HJMPASC1RHZFJGXJ39BEB2H5,장*근,************1241,3,2,409.033426,1.402891,2.0,2.000000,1.000000,...,4,3,3,3,3.0,4,3.6,3344,13.6,VIP
229,01JMPJCPA9CAV83HQGS2GW85T5,G***t,**********3301,3,3,24.019812,0.961240,5.0,0.000000,1.000000,...,3,4,3,4,3.5,4,3.4,4443,14.9,VIP
230,01J0CZN5947FRDP93MN1528JWC,고*언,************4336,3,22,14.290151,2.624389,13.0,184.000000,0.842105,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP

========== id : 3, seg : At_Risk ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
2,01JCYQ8BN664JAR1R0ATKSH89Q,김*희,************2967,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.4,1232,7.9,At_Risk
20,01JFPRC1D2XCQRS9633855X012,L*********T,************2129,3,2,364.853054,0.000000,0.0,0.0,0.000000,...,1,2,3,2,3.0,2,1.2,2321,8.2,At_Risk
22,01JK2VMK5SNQQEXC02MQQSC8J0,G***t,**********9271,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,2,3,2.0,2,2.2,3222,9.2,At_Risk
25,01JJXFM570YY6YV6JRSTN4B6TB,김*진,************8963,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,2,3,2.0,1,2.2,3212,8.2,At_Risk
26,01JHWJ7PSY8YB9Z5EXZP70ZW44,J****************M,************9550,3,2,0.555202,0.632704,3.0,0.0,0.464286,...,2,2,4,2,3.5,1,2.4,2412,8.9,At_Risk
28,01JNTK0EDW3BYNZX0QVF8CRVVQ,G***t,*********2381,3,1,NaN,1.036144,5.0,0.0,0.700000,...,4,3,1,3,1.5,1,3.6,3214,9.1,At_Risk
36,01JQ92CKF8SF3CY96GRJ20S203,신*민,************3113,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,1,2.2,4212,8.7,At_Risk
41,01JCW3X8GQW35AGEAH5XBXRMTV,G***t,**********7737,3,1,NaN,0.961240,3.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.6,1233,8.1,At_Risk
45,01J6XJEJPWCHCKKGA754NSW9VP,이*지,************9350,3,2,71.000183,0.548155,2.0,0.0,0.555556,...,2,1,3,1,3.0,3,2.2,1332,9.2,At_Risk
49,01HPGWPH2654CG8VY4CMXDD3PP,이*민,************5548,3,2,318.755079,0.000000,0.0,0.0,0.000000,...,1,2,3,2,3.0,3,1.0,2331,9.0,At_Risk
50,01JJTMDRZWX4BTY9JVM52DJXJM,G***t,**********6601,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,3,2,3,2.0,1,3.2,3213,9.2,At_Risk
53,01JM6D3PXTYN18AT82A8X9ZWWV,임*정,************9553,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
55,01JHCABMKWWN9854R7F6YP20CX,G***t,**********1147,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,4,1.2,2241,9.2,At_Risk
59,01JQTVZG429D1YQR1N4JB11Q7E,박*준,************4856,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,1,2.2,4212,8.7,At_Risk
66,01JC9WCVZJ0TDJTNPYGY4C0E7Q,박*경,************8413,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,4,2.6,1243,9.1,At_Risk
85,01JHD18THPPHF8C758VFDDTGHF,곽*연,************4285,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,3,1.2,2231,8.2,At_Risk
87,01J8Y7E1J2BCP3NH1QEGZKNW0H,G***t,**********6705,3,2,0.371004,0.961240,1.0,0.0,1.000000,...,3,1,4,1,3.5,1,2.4,1412,7.9,At_Risk
90,01JCW3R2XPM8F098554RX5S0KG,G***t,**********3210,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.6,1233,8.1,At_Risk
91,01JGN4CQNXXTG2ADBQ7RWS84BM,전*현,************1565,3,1,NaN,0.691063,2.0,0.0,0.338028,...,2,2,2,2,2.0,3,2.2,2232,9.2,At_Risk
101,01JF4KSG1JS94DMZ32P8M0DFG7,최*규,************1982,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,4,1.2,2241,8.7,At_Risk
106,01JJNNXAJ71X403FKFKVX9H6SW,G***t,**********9888,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,2,3,2.0,2,2.0,3222,9.0,At_Risk
107,01J915Z4J493J7KWR293TCW75Z,신*영,************2248,3,2,0.900392,0.961240,4.0,0.0,1.000000,...,3,1,4,1,3.5,1,2.8,1413,8.3,At_Risk
117,01JHZ1P1HEYNFRXGJB7H31YED5,김*휘,************0686,3,1,NaN,0.961240,4.0,0.0,1.000000,...,3,2,2,2,2.0,2,3.2,2223,9.2,At_Risk
128,01JNDK9H15F0KD12B735MZMFQG,G***t,**********4185,3,1,NaN,0.589992,2.0,0.0,0.316456,...,2,3,1,3,1.5,1,2.4,3212,7.9,At_Risk
130,01JQ14MJGSMMSBFR172K4HBPEP,G***t,**********4865,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
143,01JP7F3323F8P2FP2VDPT5J6W0,최*수,************8781,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
155,01JH004GBB6H7D3S54SY6RDQ6N,임*란,************2282,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,3,1.2,2231,8.2,At_Risk
161,01JBR911TN982SKAPSFBXPWP14,전*진,************7122,3,1,NaN,0.961240,4.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.8,1233,8.3,At_Risk
165,01JBVBAC49GBF8GANXXPJ8JTR6,장*숙,************4470,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.6,1233,8.1,At_Risk
166,01HGYPPCFRAB1M6ZXRENR62CJM,고*희,************8251,3,2,326.957508,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.0,4,1.0,1341,9.0,At_Risk
168,01JFVJKZ2P24HTNZRBTQC7HD9H,G***t,**********4058,3,2,0.096547,0.000000,0.0,0.0,0.000000,...,1,2,4,2,3.5,2,1.2,2421,8.7,At_Risk
170,01JCA2WYKDCDKN2DHNEPF5S1CF,정*규,************8816,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.4,1232,7.9,At_Risk
178,01JPGV91Z5XF43FYT9DE2TFC3D,G***t,**********9906,3,1,NaN,1.020023,6.0,0.0,0.875000,...,4,3,1,3,1.5,1,3.6,3214,9.1,At_Risk
179,01J9ZMMVP4ZVX1NJEKRPJ467JT,B*******************O,************6271,3,2,28.945233,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.0,3,1.0,1331,8.0,At_Risk
183,01JNAPARVVW2SCP54FWPY3F88B,G***t,**********0443,3,1,NaN,0.980824,8.0,0.0,0.722222,...,4,3,1,3,1.5,1,3.6,3214,9.1,At_Risk
192,01JK2H1E65NRTXECDW9TCJWF6N,권*지,************4607,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,3,2,3,2.0,1,3.2,3213,9.2,At_Risk
196,01JQB656M3CJ51RC7VJSZ3H5RJ,G***t,**********2527,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,1,2.2,4212,8.7,At_Risk
198,01JQZYYAC8RPVGQBHMTD9NXTDK,L*******G,************1214,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,1,2.2,4212,8.7,At_Risk
203,01JJ100G1YRG82T89CGZZPZ1Z5,배*우,************2199,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,2,2,2,2.0,2,2.0,2222,8.0,At_Risk
205,01J7DSX4Y1EA4YWZTSS6BGZGD0,성*영,************6962,3,1,NaN,0.961240,4.0,0.0,1.000000,...,3,1,3,1,2.0,2,2.8,1223,7.8,At_Risk
207,01JFSB1MPTS0N8HPSYPYCZVA7W,김*현,************7348,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,2,3.0,2223,8.5,At_Risk
209,01JPKMMTTTK43TG6G1WYJP7BFZ,G***t,**********6388,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
217,01HM8PG2PFQ6NV8ZKDBXPVJY0G,NaN,************5848,3,2,315.147014,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.0,4,1.0,1341,9.0,At_Risk

========== id : 3, seg : Loyal ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
13,01JFRV27HHHCBNK580G6XKCXG6,윤*령,************5330,3,2,0.000689,0.961240,1.0,0.0,1.000000,...,3,2,4,2,3.5,3,3.0,2433,11.5,Loyal
14,01JDHF7TZ46GWQAYGGZYJA79VJ,정*래,************2649,3,3,24.503569,0.961240,1.0,0.0,1.000000,...,3,2,3,2,3.5,4,2.6,2443,12.1,Loyal
17,01JBX72M6DTKJ82J0RCWB4DV92,G***t,**********1750,3,3,35.504002,0.961240,1.0,0.0,1.000000,...,3,2,3,2,3.5,3,2.4,2432,10.9,Loyal
37,01JE37CYMDR2KMY7028Y2S5VV3,김*섭,**********3905,3,2,0.108071,0.961240,1.0,0.0,1.000000,...,3,2,4,2,3.5,3,2.8,2433,11.3,Loyal
40,01JT87D4RXR8JT6SBBE9KATJYW,G***t,**********4865,3,1,NaN,0.961240,4.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
42,01JSC2K04R4223VJN1PK2TNPN2,G***t,**********5120,3,2,0.694753,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,1,2.4,4412,11.4,Loyal
44,01JQTXPF0CP3R1N04KZHS20WF7,김*정,************2133,3,3,7.984442,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,2,2.2,4422,12.2,Loyal
52,01JD43TJFT3T2RJR71QC4G8E1R,황*성,************8996,3,3,11.550376,0.000000,0.0,0.0,0.000000,...,1,2,4,2,4.0,4,1.0,2441,11.0,Loyal
57,01JRMG1698KH3AKPKDKZP1VD84,김*희,************0234,3,3,0.596540,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,1,2.4,4412,11.4,Loyal
63,01JKJEKAQ8D823HGYEHD0XVRC3,김*한,************0368,3,2,0.117965,0.000000,0.0,0.0,0.000000,...,2,3,4,3,3.5,3,2.2,3432,11.7,Loyal
65,01JHFECZ76BCRCF1D2KAFDHK42,G***t,**********1899,3,1,NaN,1.085179,8.0,0.0,0.263844,...,4,2,2,2,2.0,4,3.2,2243,11.2,Loyal
71,01JQ1ADTK87C41MRWTW15BJM3J,장*원,************5299,3,1,NaN,0.961240,2.0,0.0,1.000000,...,4,3,1,3,1.5,3,3.4,3233,10.9,Loyal
72,01JRYYFQBYFX5AJJ3ZJ65X7WR0,G***t,**********6112,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
75,01JQJF0R6RX2CXED08D1WPKSGF,엄*현,************6530,3,1,NaN,0.961240,6.0,0.0,1.000000,...,4,4,1,4,1.5,2,3.8,4224,11.3,Loyal
80,01JF4GQGWEVJ96N316EK9N2M1P,이*지,************5958,3,6,4.644169,0.000000,0.0,0.0,0.000000,...,1,2,4,2,4.0,4,1.2,2441,11.2,Loyal
82,01JRQ1EN6P2HRZQ2GDT8S3N04T,G***t,**********8055,3,2,0.274790,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,1,2.4,4412,11.4,Loyal
94,01JF1QP9R72JMRRSSJRJAXPTBQ,최*원,************4593,3,2,47.075174,0.961240,4.0,0.0,1.000000,...,3,3,3,3,3.0,3,3.2,3333,12.2,Loyal
95,01JNAES5YFD4DYS478QC38221K,전*지,************3389,3,2,2.866185,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,3,2.2,3432,12.2,Loyal
105,01J9ZX9QEAA12TB3HP5RRPM7WN,G***t,**********0773,3,3,0.499330,1.292189,6.0,10.0,1.000000,...,4,1,4,1,4.0,3,3.8,1434,11.8,Loyal
109,01HZ9N2YYEWDDGQJHWSJR9QDD0,G***t,**********9916,3,4,37.709513,0.961240,2.0,0.0,1.000000,...,3,1,3,1,3.5,4,2.6,1443,11.1,Loyal
111,01JHZ8Q9FKSA3B2W3AR8CCYTA3,G***t,**********6912,3,1,NaN,1.023220,6.0,0.0,0.800000,...,4,2,2,2,2.0,4,3.4,2243,11.4,Loyal
112,01JTD5Z6E3PTKVQ10NRQ4AP1FB,G***t,**********7682,3,1,NaN,0.972857,10.0,0.0,0.592593,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal
116,01JV15B83475G1QAYZT6BSR06S,박*욱,************8613,3,1,NaN,0.961240,2.0,0.0,1.000000,...,4,4,1,4,2.0,1,3.8,4214,10.8,Loyal
120,01JFSM0ZJXH03WGPVTTHH2FHPK,김*영,************0375,3,3,0.301260,1.028985,3.0,26.0,0.400000,...,2,2,4,2,4.0,2,3.2,2423,11.2,Loyal
121,01JRHJKGBHV3C95DHX62PQHSK9,박*현,************2722,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
122,01JJR1ZZ8KGVZNS5C50P9EYQY2,최*학,************8884,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,3,2,3,2.0,3,3.2,3233,11.2,Loyal
123,01JCSGPCKY48Q42K6MEEEH4XZ1,이*호,************1424,3,2,0.334942,1.242117,4.0,184.0,0.337500,...,4,1,4,1,3.5,3,3.6,1434,11.1,Loyal
132,01JT87DBYRJHT54YBR6696EWGM,G***t,**********6364,3,1,NaN,0.961240,4.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
134,01HPDNYF6TG1ADMGQPVB9G8Y5D,이*헌,************7524,3,4,78.077933,1.402891,2.0,2.0,1.000000,...,4,1,3,1,3.5,4,3.6,1444,12.1,Loyal
147,01JN8M9ZTF7ME8EJQAC231SAH1,G***t,**********0605,3,1,NaN,1.015113,6.0,0.0,0.538462,...,4,3,1,3,1.5,3,3.6,3234,11.1,Loyal
148,01JR4E34Z9WDMHNVCB5K8GVGSM,하*은,************7115,3,2,2.328998,0.910341,4.0,138.0,0.440678,...,2,4,4,4,4.0,1,3.0,4413,12.0,Loyal
151,01JT87FXCNKX3TJ1KRDGP9JX6M,G***t,**********3656,3,1,NaN,0.961240,4.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
153,01JV15AA4Z4VZ70P1RDMP6N80Z,G***t,**********6699,3,1,NaN,0.961240,2.0,0.0,1.000000,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal
158,01JCA4XZMMGSHDRYTY22ZKGFDQ,차*범,**********5068,3,2,56.104480,0.961240,1.0,0.0,1.000000,...,3,2,3,2,3.0,4,2.4,2342,11.4,Loyal
160,01JR4SFPQG3DCYNTXEANWM67ET,김*민,************6520,3,2,0.706837,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,1,2.2,4412,11.2,Loyal
163,01JTMEQQ4K1E6A9S5ACHCY553D,G***t,**********5495,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal
176,01J447RP2DXDEFKWH2NRQG7VTF,김*림,************3874,3,3,80.883237,0.961240,2.0,0.0,1.000000,...,3,2,3,2,3.5,4,2.6,2443,12.1,Loyal
185,01JEWMN3XYF8A27BXC7HG4EJAZ,마고,**********5435,3,8,6.438237,0.000000,0.0,0.0,0.000000,...,1,2,4,2,4.0,4,1.2,2441,11.2,Loyal
199,01JQ3WKB22B7D25CEBVXFHS8TH,이*신,************2368,3,2,0.519159,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,3,2.2,3432,12.2,Loyal
200,01JSK1YR98HD5BWJBMX73WQNVS,이*지,************2061,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal
211,01JMVY6CFSRWGE9FCDB7B0GQ7D,G***t,**********5153,3,1,NaN,0.961240,3.0,0.0,1.000000,...,3,3,1,3,1.5,3,3.4,3233,10.9,Loyal
219,01JTN5A251AQSV4PM76EJGEC4Y,G***t,**********7243,3,1,NaN,0.961240,7.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
220,01JN89SB90KSVBF9WDKAW8BQYE,최*희,************0803,3,1,NaN,0.961240,9.0,0.0,1.000000,...,3,3,1,3,1.5,4,3.4,3243,11.9,Loyal
224,01JT53ADPT7XGANHQRD9HCJBE4,백*수,************6472,3,1,NaN,0.961240,6.0,0.0,1.000000,...,4,4,1,4,2.0,2,4.0,4224,12.0,Loyal
226,01JR5BJVBB10KAKSBDW71QM890,김*영,************4583,3,1,NaN,0.669141,2.0,0.0,0.379310,...,2,4,1,4,1.5,3,2.4,4232,10.9,Loyal
228,01JV3V5021JTV9TFPSFSFM9YXX,박*영,************7083,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,2,3.8,4224,11.8,Loyal

========== id : 3, seg : Dormant ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
0,01JCPX1R8TH8B5NSBBSKGVYNWE,배*우,************6097,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.0,1211,4.5,Dormant
7,01JGGPDZQHJF64BM835XF0DG2Z,임*성,************8892,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
19,01J9K59YMKERT6DCH9J7SZ08EZ,G***t,**********4877,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,3,1,2.0,1,2.4,1212,6.4,Dormant
21,01JDXXY28JT6HSD1YB8EVMC1M8,G***t,**********3851,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,3,1.2,1231,6.7,Dormant
38,01JN2V38V1MSH4X64DZDFBGS29,조*준,************2642,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,1,2.2,3212,7.7,Dormant
39,01JF1GCDW5AXRS74MZQK1V9AS5,김*수,************8793,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
46,01JBR4R13TDXTGDBRAX6N52YMP,박*민,**********8489,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,2,2.4,1222,6.9,Dormant
51,01J69CB70YZTER92AYS0ZX824Z,오*숙,************0622,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,3,1,2.0,1,2.4,1212,6.4,Dormant
54,01J9ZFTXN82S16VNJWJGGDR7QT,G***t,**********7061,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
68,01J74ZQRNHNFNBZ8T8TFQGKPZX,노*구,************6140,3,2,0.002110,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,2,1.0,1421,7.5,Dormant
69,01JDEEYFAXAFJ1NXZGFJ17TTDH,김*령,************7490,3,1,NaN,0.795489,5.0,0.0,0.619048,...,3,1,2,1,1.5,1,2.8,1213,6.3,Dormant
74,01J8YMH459CWVCDGXACVQQX7GW,G***t,**********2090,3,1,NaN,1.129733,8.0,0.0,0.722222,...,4,1,3,1,2.0,1,3.2,1213,7.2,Dormant
76,01J78NH5WD3HJKJ57WNGP1D6F1,K**O,**********0397,3,2,0.630979,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,1,1.0,1411,6.5,Dormant
77,01JNZ5BJKJMXG333AT452JTS9V,G***t,**********5951,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,1,2.2,3212,7.7,Dormant
81,01JE0T509JG7ATSMYNR4NK2X29,G***t,**********5474,3,1,NaN,0.961240,4.0,0.0,1.000000,...,3,2,2,2,1.5,1,3.2,2213,7.7,Dormant
83,01JEZCFWMACS2SYP4PNXYBRQWZ,윤*경,************1294,3,2,1.879147,0.000000,0.0,0.0,0.000000,...,1,2,4,2,3.5,1,1.2,2411,7.7,Dormant
86,01JB99TAWVVMM2FW25YE1BFY3X,G***t,**********7465,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
93,01JFPMZ9BENGF5JCC8E21GN9TP,박*훈,************7191,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
96,01J9AMTDY80MYTXSRK7RJJSYY9,G***t,**********3170,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,3,1,2.0,2,2.4,1222,7.4,Dormant
100,01JFPMSFJDWWXV2RGYYJRMCT33,G***t,**********0006,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
110,01JFCFH1H1HMZPHDVX2S2BKX2S,G***t,**********8876,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,2,1.2,2221,6.7,Dormant
119,01JFYP9XGH00WP8A6KGYPET6QS,G***t,**********9693,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
124,01J78CFBH44PCX9TAERRY86TED,정*빈,**********6305,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
125,01JEX7BX9EHTA39ZS4Z2YX2RFG,G***t,**********3022,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,3,1.2,2231,7.7,Dormant
126,01J6S6PV95CRGA6HPSXYEY1DNC,G***t,**********6702,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
129,01JPHPYJCNC2P5YMS5FA2RWSY3,G***t,**********2118,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,1,2.2,3212,7.7,Dormant
131,01J786NVPPNWBEW03RFKYKWM3P,김*분,************4707,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
136,01JAYZ1CRSN0V25V446ZAMQ5HV,G***t,**********4104,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
137,01JBX3M8TNST904GNGTQBQ9WRQ,G***t,**********8072,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.0,1211,4.5,Dormant
138,01JHCH8ZHB92CS0Z5F54YQFKKK,전*희,************0578,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
145,01J6E4TK5YK0THD3W8HYDKZEQT,G***t,**********1935,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
146,01JCAZSTRQYFG6MHKBTTG15F9R,G***t,**********2613,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,3,1.0,1231,6.5,Dormant
152,01JHVW1R5E7FEP14M8QC6Y9VPA,정*도,************2089,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
154,01JDBN5MB6AKYS7B1R1Z4WT66T,G***t,**********3454,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,2,1.2,1221,5.7,Dormant
156,01JHWBNFRWBH1DHQMY16290FTC,정*석,************9795,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,1,1.2,2211,6.2,Dormant
162,01J6KJEMNWVFRTMWBMYJB5KEYZ,홍*진,**********0499,3,1,NaN,0.750151,2.0,0.0,1.000000,...,2,1,3,1,2.0,1,2.2,1212,6.2,Dormant
164,01J7SRDGJ7DJ0EZBK7GHG14XQM,이*영,************2706,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
169,01J8YBV7GCH6BMV3M65R3K54BD,노*별,************9570,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
172,01JACH6VH82047KSR9MH5TD6GG,이*혜,************6296,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
175,01JHW7Q08Y48H2JYS9QV0W2HE4,G***t,**********9321,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
177,01J7J3XNJ7CXTYS9ETVYGDBBNC,G***t,**********8351,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
182,01JDPQ8Z51HA02M2H7CB85BSKS,오*재,************4044,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,2,1.2,1221,5.7,Dormant
184,01J8VAVW9KZ67HCXSQXDPJJ5CP,구**********H,*********4909,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
193,01JCAX9NAC4PW2D0F8C13PF77M,김*성,************7615,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,4,1.0,1241,7.5,Dormant
194,01JGAW5E3YNVPXWR5F4RX44VTZ,G***t,**********6240,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
195,01JAQ6RV66PYW4D4ANFHJYMQWE,김*미,************3728,3,2,2.827488,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,1,1.0,1411,6.5,Dormant
197,01HDRDSP2CF4PRPB7EB209FXRV,김*정,************9906,3,2,398.029255,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.0,2,1.0,1321,7.0,Dormant
201,01J7ZRNR9M2P7E3JKA32VW6YNB,윤*철,************8821,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,1,1.0,1211,5.0,Dormant
208,01JFHZHK74XB6KXHS7Z0Q1WN31,박*현,************0130,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,1.5,1,1.2,2211,5.7,Dormant
212,01JH05APAZEX9ET1X9K1RTWX3T,전*아,************6996,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,1,1.2,2211,6.2,Dormant
215,01JDY53T2N9VGS286QZWCWH8V5,권*섭,************3304,3,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,2,1.2,1221,5.7,Dormant
218,01JBB1EZGK52E85443S0RR0PSW,박*현,************9014,3,2,1.468882,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,2,1.0,1421,7.5,Dormant

========== id : 3, seg : Growth ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
3,01JJBZVDS867W3ANC9T1ESFAVM,D*********************E,************3762,3,1,NaN,0.546252,1.0,0.0,0.600000,...,2,3,2,3,2.0,3,2.4,3232,10.4,Growth
6,01JEJHWNBK2X31KBHP87E0Z1DW,이*택,************2242,3,1,NaN,0.935614,2.0,0.0,0.666667,...,3,2,2,2,1.5,4,2.8,2243,10.3,Growth
10,01JQDPJHRXJV9554D3EXDJQ97T,이*현,************4285,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,1.5,2,2.2,4222,9.7,Growth
11,01JG6HQC090KB4G163X0JB2Y3R,G***t,**********7090,3,1,NaN,0.533020,1.0,0.0,0.538462,...,2,2,2,2,1.5,4,2.4,2242,9.9,Growth
16,01JHJ65RYZHAJP283HCSFTF814,박*진,************5565,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,3,3.0,2233,10.0,Growth
18,01JE2QVAM0VN7X4VM0H1JVZK8W,G***t,**********2275,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,3,2.8,2233,9.3,Growth
24,01JNTVK5WRCZAPCFP5YFMFBYAP,김*우,************6591,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,3,1,3,1.5,3,3.2,3233,10.7,Growth
27,01JJBZY7H8XFB3D2WPTCY4C1GG,H****************A,************6052,3,2,0.049080,0.000000,0.0,0.0,0.000000,...,2,3,4,3,3.5,2,2.0,3422,10.5,Growth
29,01JSTPW3YP2VN3PTB0AEB2XGEY,박*민,************1262,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
30,01HSJSRTC8B1NV6ZRGXHDB20JH,G***t,**********5731,3,3,134.458003,0.317955,1.0,0.0,0.533333,...,2,2,3,2,3.5,2,1.8,2422,9.3,Growth
31,01HSJ9Q7X72YRFQ0CB658FCX4A,정*림,************2705,3,4,55.448723,0.000000,0.0,0.0,0.000000,...,1,1,3,1,3.5,4,1.0,1441,9.5,Growth
43,01JGQTB3KFA440ZYPQE0F7WZSD,박*정,************4292,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,3,3.0,2233,10.0,Growth
47,01JT4XYMQSQM1XN068MRHTRVSX,최*진,************7791,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
48,01JQE0QE3VHNR31CBCBW4JWEWT,서정,*************0276,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,1.5,1,3.6,4214,10.1,Growth
60,01J8C56WB5GH98JDMCPN19X265,김*순,************3785,3,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,3,1,2.0,4,2.6,1243,9.6,Growth
61,01JS8KE8FMPCSVMJG3S0WTB7N3,손*혁,************9511,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,2,2.4,4222,10.4,Growth
67,01JT52QF23QPAZ2063S0SYZ6CB,박*지,************8620,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,2,2.4,4222,10.4,Growth
78,01JN8JVP14D90T63F2YNAEV210,정*원,************6127,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,3,1,3,1.5,3,3.2,3233,10.7,Growth
84,01JMR4C7HCGMGKVJMYHMF33WT4,G***t,**********0397,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,4,2.2,3242,10.7,Growth
98,01JS6SGCZM7R21TT2S0SFWAJZH,정*경,************8677,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
99,01JRPKJSCFTBA094JYC12C1712,G***t,**********2146,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
104,01JH2R0HH07DMS42KAVPPJP77H,G***t,**********5133,3,1,NaN,0.740415,1.0,0.0,0.666667,...,2,2,2,2,2.0,3,2.4,2232,9.4,Growth
108,01JE048TTH2ZHA4YR9MT9SXESG,김*민,************9561,3,1,NaN,1.000605,3.0,0.0,0.625000,...,4,2,2,2,1.5,3,3.2,2233,9.7,Growth
113,01JTFET5YY8ZJT9SW33PK4P3JJ,G***t,**********9989,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,1,2.4,4212,9.4,Growth
118,01J7T1TBKD5K907KYRCF03F8CX,김*홍,************5877,3,1,NaN,0.842701,4.0,0.0,0.400000,...,3,1,3,1,2.0,4,2.4,1242,9.4,Growth
127,01JMYA0VDT9FY0X7T50TPJVVG9,최*미,************9494,3,1,NaN,0.850039,3.0,0.0,0.185355,...,2,3,1,3,1.5,3,2.8,3233,10.3,Growth
133,01JKYS6E3AERAF2KKFHS0NETNC,김*경,************0306,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,3,2.2,3232,9.7,Growth
135,01JNG44GSGBYMKCC682Y4GZ5SR,G***t,**********9628,3,1,NaN,0.988412,6.0,0.0,0.446809,...,4,3,1,3,1.5,2,3.4,3223,9.9,Growth
144,01J75BX20BA0ZA896N9KA39AY6,G***t,**********2886,3,2,2.028714,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,4,1.0,1441,9.5,Growth
150,01J37X6TGEPJHG62KPM3KGQY1B,G***t,**********0336,3,2,188.767589,0.000000,0.0,0.0,0.000000,...,1,3,3,3,3.0,3,1.0,3331,10.0,Growth
157,01JKAFASGZRAC4X8EW97EZH623,G***t,**********9969,3,2,0.016581,0.000000,0.0,0.0,0.000000,...,2,3,4,3,3.5,2,2.2,3422,10.7,Growth
167,01JF1NSKKFJNKS4P5YEX90N2KY,강*경,************9194,3,2,0.274517,0.961240,1.0,0.0,1.000000,...,3,2,4,2,3.5,1,2.8,2413,9.3,Growth
171,01JHCB4D4W15BZ157MXVD2AVFW,G***t,**********7934,3,2,0.155883,1.189650,6.0,160.0,0.363636,...,4,2,4,2,3.5,1,3.6,2414,10.1,Growth
180,01JTTFSDZ81GN27S0FRA00ZZ14,G***t,**********2216,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,2,2.4,4222,10.4,Growth
181,01JNAJR4SBFSM6M660ZA5RQBBT,조*정,************3658,3,2,2.797087,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,1,2.2,3412,10.2,Growth
186,01JSKRQPXAYT6JDVECXT6PP9ZB,김*민,************5463,3,1,NaN,0.249098,1.0,0.0,0.411765,...,2,4,1,4,2.0,1,2.6,4213,9.6,Growth
187,01JT51Q3YCX226SWBE5RQM9BNZ,G***t,**********5230,3,1,NaN,0.944951,2.0,0.0,0.750000,...,3,4,1,4,2.0,1,3.2,4213,10.2,Growth
188,01JDBM4PM8J88V53RHP75PNKRT,G***t,**********5596,3,2,0.002006,0.000000,0.0,0.0,0.000000,...,1,1,4,1,3.5,4,1.2,1441,9.7,Growth
189,01JEG18ZYZ0ZS0ZETNRCNBVWFG,단*은,************1534,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,4,2.8,2243,10.3,Growth
202,01JNAHJ4Q26YDP7KK03TCTRT1G,G***t,**********8026,3,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,4,2.2,3242,10.7,Growth
204,01JQ6BWVZP9X0NC6ADPT4N37GM,황*호,************0721,3,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,1.5,1,3.6,4214,10.1,Growth
206,01J3CE2151B1YS1N0XAQEMYZKX,류*효,**********2486,3,6,31.010428,0.000000,0.0,0.0,0.000000,...,1,2,3,2,3.5,4,1.0,2441,10.5,Growth
214,01JPH4R31GV9ES9ZAPDQ1VXPGP,권*현,************8320,3,1,NaN,0.961240,1.0,0.0,1.000000,...,3,3,1,3,1.5,3,3.2,3233,10.7,Growth
216,01HWYXQ4GM1XK6TW0RXTZZABXT,이*빈,************0983,3,4,43.295433,0.961240,2.0,0.0,1.000000,...,3,1,3,1,3.5,3,2.6,1433,10.1,Growth

========== id : 5, seg : VIP ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
232,01JAY33R5XQ9A6ZXNY9WF2P81X,이*빈,************3373,5,4,4.419770,1.364909,4.0,6.0,1.000000,...,4,2,4,2,4.0,3,4.0,2434,13.0,VIP
238,01JAM9FA29W01Z50CSR3R17RX2,정*정,************2677,5,5,11.308003,1.402891,2.0,2.0,1.000000,...,4,2,3,2,3.5,4,3.6,2444,13.1,VIP
245,01J6VWNE93K2KSM2Y8FMDPPTCM,김*준,************0661,5,7,8.331215,1.173648,4.0,48.0,0.352113,...,4,2,3,2,3.5,4,3.6,2444,13.1,VIP
248,01JMC5G3MK9Y2CEG76CRC9PW8A,김*나,************4770,5,3,8.955304,0.961240,1.0,0.0,1.000000,...,3,3,3,3,3.0,4,3.2,3343,13.2,VIP

========== id : 5, seg : At_Risk ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
236,01JEB9NT047YBTQ093F3S2A33F,전*정,************7180,5,2,1.617315,0.933899,4.0,0.0,0.7,...,2,2,4,2,3.5,1,2.6,2413,9.1,At_Risk
239,01JAPG2A2X967KNQQ75NQRYJXX,김*채,************4693,5,1,NaN,0.000000,0.0,0.0,0.0,...,1,4,2,4,1.5,2,1.2,4221,8.7,At_Risk
240,01J7AK8095EN3ZYDRJKWRR9G4T,김*영,************7198,5,1,NaN,0.961240,3.0,0.0,1.0,...,3,4,2,4,1.5,1,2.6,4213,9.1,At_Risk
249,01JEZAG864D3EAA783RC4X5EV0,김*은,************9860,5,1,NaN,0.961240,1.0,0.0,1.0,...,3,2,1,2,1.5,2,3.0,2223,8.5,At_Risk

========== id : 5, seg : Loyal ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
231,01JPPQNMAWNV1X7QJS9DT42TE0,G***t,**********8455,5,2,0.034605,0.00000,0.0,0.0,0.0,...,1,3,4,3,3.5,3,1.4,3431,10.9,Loyal
237,01JH85DA18HJ4EYJVQ2KK662GM,김*정,**********9368,5,1,NaN,0.96124,1.0,0.0,1.0,...,3,3,1,3,1.5,4,3.2,3243,11.7,Loyal
246,01JSKDV23WE7B3B2YMN6DQT88G,G***t,**********0111,5,4,5.341879,0.00000,0.0,0.0,0.0,...,2,4,4,4,4.0,2,2.4,4422,12.4,Loyal
247,01JS16XSXKZJC5ZRZNTBMY75B3,강*용,************0531,5,3,1.438860,0.00000,0.0,0.0,0.0,...,2,4,4,4,3.5,3,2.2,4432,12.7,Loyal

========== id : 5, seg : Dormant ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
233,01JAYRDYZM78ZMN75XVCV9M45E,김*민,************1767,5,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,1,2,1.0,2,1.2,2121,6.2,Dormant
234,01J7QGD1CS3YS50DWCX1PGJBMJ,이*윤,************1176,5,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,2,1.0,1221,5.5,Dormant
235,01JGTC4CRSST66KG8YP4YXBSJA,심*우,************3657,5,1,NaN,0.000000,0.0,0.0,0.000000,...,1,3,1,3,1.5,1,1.4,3211,6.9,Dormant
242,01J64PVW1MSXS4BSG7WW35CJZZ,G***t,**********2506,5,1,NaN,0.445658,1.0,0.0,0.428571,...,2,1,2,1,1.5,4,1.8,1242,8.3,Dormant
243,01JBXSHCTXAMS9Z7T2A7DBCRJR,G***t,**********1914,5,1,NaN,0.000000,0.0,0.0,0.000000,...,1,3,1,3,1.0,1,1.2,3111,6.2,Dormant

========== id : 5, seg : Growth ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
241,01HARR323KHW4NDARB2VGHBQYD,오*윤,*********4493,5,4,8.329685,1.277794,4.0,8.0,0.833333,...,4,1,3,1,3.0,3,3.8,1334,10.8,Growth
244,01JEWGB5VDYX0J38NN68YXQW7Y,김*은,************3084,5,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,1,2,1.5,3,2.8,2233,9.3,Growth

========== id : 10028, seg : VIP ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
264,01J672R2JVDM6H86DPEQQJ366W,권*수,************8480,10028,3,38.413885,0.961240,1.0,0.0,1.000000,...,3,4,3,4,3.5,3,2.4,4432,12.9,VIP
266,01JD223QSYQTTXEY1AF0PDVPFM,G***t,**********9833,10028,2,0.188950,0.961240,1.0,0.0,1.000000,...,4,4,4,4,4.0,3,3.8,4434,14.8,VIP
276,01JNZSJ8S4EW5DVC9MJXYZ8AF0,안*민,************9128,10028,6,12.789424,2.595191,18.0,96264.0,0.079987,...,4,4,3,4,3.5,4,3.6,4444,15.1,VIP
278,01JDC5964EM5JFTRC0X6R2M0KX,G***t,**********5629,10028,2,0.332635,0.000000,0.0,0.0,0.000000,...,2,4,4,4,4.0,3,2.4,4432,13.4,VIP
282,01JAHGYND3Z51A9B1XW272J4CJ,이*영,************3080,10028,3,19.090853,0.000000,0.0,0.0,0.000000,...,1,4,3,4,3.5,4,1.4,4441,12.9,VIP
283,01J4P57HC7F5QFB15BESCPK2TA,홍*지,************5855,10028,3,60.853311,1.326765,4.0,10.0,0.750000,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP
286,01JA9MJ7QTQ661QEX8N1DDH5BV,G***t,**********8891,10028,3,14.314542,0.546252,1.0,0.0,0.600000,...,2,4,3,4,3.5,4,2.4,4442,13.9,VIP
287,01JDE94A2PH0HG7JWGQHQB5HQX,신*명,************7659,10028,2,0.418740,0.538994,2.0,0.0,0.083196,...,2,4,4,4,4.0,3,2.8,4433,13.8,VIP
289,01JDPA7N5349FHRTRJXH1HBM74,김*현,************1905,10028,11,10.689828,2.423364,20.0,15904.0,0.077044,...,4,4,3,4,3.5,4,3.6,4444,15.1,VIP
299,01JAYH736AYB7G9FVMZ0NFSYY3,최*정,************0528,10028,4,48.980444,1.050762,3.0,3540.0,0.100192,...,2,4,3,4,3.5,4,3.2,4443,14.7,VIP
307,01JAQ9HMDBTCKJ9Z95HZ5RHTH7,김*슬,************4524,10028,6,10.771924,1.641876,7.0,22.0,1.000000,...,4,4,3,4,3.5,4,4.0,4444,15.5,VIP
308,01JD65RAZBK03KEQ1G6MB19M4T,이*훈,************7141,10028,3,4.534097,1.572566,5.0,18.0,0.857143,...,4,4,4,4,4.0,3,3.8,4434,14.8,VIP
319,01J9AQX4M93849DZ052AMR1RK3,이*광,************0669,10028,2,6.999416,1.256885,3.0,10.0,0.666667,...,4,2,4,2,3.5,4,3.8,2444,13.3,VIP
322,01JAA5M5SAV6N2KK6KCJH493GX,김*영,************4138,10028,2,7.828484,0.961240,2.0,0.0,1.000000,...,3,3,4,3,3.5,4,3.4,3443,13.9,VIP
331,01JA9QXTN06K5H0GZ7NGPMYNXE,김*준,************3990,10028,5,1.004722,1.539243,5.0,12.0,1.000000,...,4,3,4,3,4.0,3,4.0,3434,14.0,VIP
342,01JA23C6CCD8B4MBAD31BZ8FWR,조*이,************5065,10028,4,69.695357,1.402891,2.0,2.0,1.000000,...,4,4,3,4,3.5,4,4.0,4444,15.5,VIP
344,01J7NDA8R08KMZRTAQ7GAEQ77D,김*우,************6784,10028,6,1.960434,1.488684,4.0,28.0,0.700000,...,4,2,4,2,4.0,4,3.8,2444,13.8,VIP
347,01JDE567X0RBEVN44XR1J3N3S3,김*태,************4434,10028,2,0.997250,0.961240,1.0,0.0,1.000000,...,4,4,4,4,4.0,3,3.8,4434,14.8,VIP
352,01J7JQ5ND43HZ2B6DJQAF4AJ58,G***t,**********5077,10028,6,18.628381,1.402891,2.0,2.0,1.000000,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP
360,01JC7HJAHSMRZ548MTGPKM6S3Q,G***t,**********3524,10028,3,33.605528,0.961240,3.0,0.0,1.000000,...,4,4,3,4,3.5,2,3.8,4424,13.3,VIP
361,01JA7PJK9R85VJFEX6ABM96W4W,박*건,************9377,10028,3,20.469381,1.024255,2.0,6.0,0.666667,...,4,4,3,4,3.5,4,3.8,4444,15.3,VIP

========== id : 10028, seg : At_Risk ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
251,01J70G6GRWT6Q91RW1XC6G71NQ,G***t,**********4949,10028,3,2.778279,0.961240,2.0,0.0,1.000000,...,3,1,4,1,4.0,1,2.6,1413,8.6,At_Risk
252,01J7QA8Q5FYK01EGHWVF75NXVQ,G***t,**********1438,10028,1,NaN,0.741479,2.0,0.0,0.538462,...,2,1,2,1,1.5,3,2.2,1232,7.7,At_Risk
253,01HATVZ2DFPPC3ERXCYXMVXXS6,김*하,*********1835,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,3,3,3,2.0,2,1.0,3221,8.0,At_Risk
254,01J86VFF2XEXFXSGQX0VAM2ZAV,G***t,**********1853,10028,2,2.913214,0.000000,0.0,0.0,0.000000,...,1,2,4,2,3.5,2,1.2,2421,8.7,At_Risk
255,01J7GADQAH0DYB35F7YE83A22W,L**********G,************7632,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,3,2.4,1232,7.9,At_Risk
257,01JC4RQJ55GA521K0TVFHY486B,G***t,**********3950,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
260,01JBGYKPBJ2PYXXWB9N55ABAZV,임*진,************1015,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
280,01J8CGC0DKSVXFHRQ117CE7P6J,박*영,************7217,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,2,2.6,2223,8.1,At_Risk
281,01J61WKHQENHNETE4NYERM2AE4,김*태,**********6674,10028,2,0.249847,0.961240,1.0,0.0,1.000000,...,3,1,4,1,3.5,2,2.4,1422,8.9,At_Risk
284,01J8F5EMWFW8N3YH05JQXF5X1G,G***t,**********9738,10028,1,NaN,0.444939,1.0,0.0,0.114420,...,2,2,2,2,1.5,2,2.2,2222,7.7,At_Risk
290,01J9XCJDFQCZV45MGBY33X830Q,G***t,**********0707,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,3,1.2,2231,8.2,At_Risk
296,01J8EYQ3RF6HE815W4T8KQ37BK,Z*********N,************9222,10028,1,NaN,0.961240,3.0,0.0,1.000000,...,3,2,2,2,1.5,1,3.2,2213,7.7,At_Risk
297,01JCD7MFFNA2WKA8H2SX5NMMT9,G***t,**********8389,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,2.0,1,2.4,3212,8.4,At_Risk
301,01J9K89692FKPXSF473X4MDVHE,G***t,**********8900,10028,2,0.209449,0.350679,1.0,0.0,0.500000,...,2,2,4,2,3.5,1,2.2,2412,8.7,At_Risk
302,01J7TFMXHSTRRPE4JN04B2GV28,G***t,**********8090,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,4,2.4,1242,8.9,At_Risk
317,01J8VV6DQ4YGMXS6RSC8BHAHEN,W*******G,************9333,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,1,3.0,2213,7.5,At_Risk
318,01JBR4HMBRQ3K8E2A93V6X6PYA,G***t,**********1116,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
326,01J7WE5PXENDXJBMNZD8BW8WSY,G***t,**********2595,10028,2,0.197164,0.402733,1.0,0.0,0.440000,...,2,1,4,1,3.5,2,2.0,1422,8.5,At_Risk
333,01J9X01039B34Y6RSAQAQ7D4PW,한*민,************4211,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,1,3.0,2213,8.0,At_Risk
336,01J844YY71YHDXW277AEHX203B,G***t,**********4458,10028,1,NaN,0.740415,1.0,0.0,0.666667,...,2,2,2,2,1.5,2,2.2,2222,7.7,At_Risk
338,01JACT8B3KHADWCH6HVG4HTEPM,김*호,************7740,10028,2,2.612117,0.000000,0.0,0.0,0.000000,...,1,3,4,3,3.5,1,1.4,3411,8.9,At_Risk
348,01JAQ2R10KPX4BGVZAP71N0XVW,G***t,**********2414,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,2,2.2,3222,8.7,At_Risk
355,01HARR323KHW4NDARB2VGHBQYD,오*윤,*********4493,10028,1,NaN,0.445658,1.0,0.0,0.428571,...,2,1,3,1,2.0,3,1.8,1232,7.8,At_Risk

========== id : 10028, seg : Loyal ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
250,01JACXQ5V4K02X9VM62XAG4A7X,이*나,************2192,10028,1,NaN,0.961240,5.0,0.0,1.000000,...,3,3,1,3,1.5,4,3.4,3243,11.9,Loyal
261,01JCCR356MHERES0VASPB0VPMX,김*경,************4679,10028,2,0.574963,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,2,2.4,3422,11.4,Loyal
262,01JCCKQRWHE9EMYS1K0R7F5SW8,윤*경,************8148,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,4,4,1,4,2.0,3,3.8,4234,12.8,Loyal
265,01J6C4GSH2TEFQ16SRMEW09TBP,G***t,**********1855,10028,3,1.922233,1.408808,3.0,4.0,1.000000,...,4,1,4,1,4.0,3,3.8,1434,11.8,Loyal
268,01JAM7XR2ZXG18QE51FS9NEF2A,G***t,**********2753,10028,2,0.078769,0.000000,0.0,0.0,0.000000,...,1,3,4,3,3.5,4,1.4,3441,11.9,Loyal
270,01JCHTJ1T674V695NH542JAHB6,G***t,**********8903,10028,2,0.051779,0.961240,1.0,0.0,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,Loyal
272,01JBRMEN3K7F4GWYKM82RZ6RBZ,문*우,************5815,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,3,3.6,3234,11.1,Loyal
273,01JCF58YZE17NJH4HBJD5MGZ74,임*진,************4784,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
274,01J7MRZG685D26H8ZJ8AFK054Y,황*란,************4855,10028,2,26.242714,0.961240,2.0,0.0,1.000000,...,3,2,3,2,3.0,3,2.8,2333,10.8,Loyal
275,01JCYZHFHV4D7AKH2AB37KNCH2,하*빈,************5214,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,3,3.8,4234,12.8,Loyal
279,01JB1G9PGDMK4BQ29TZAS9E0JF,도*훈,************5084,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,3,3.6,3234,11.1,Loyal
288,01JBXSS2PYT3NRQMD67JAPZ9GJ,박*애,************6940,10028,2,0.026796,0.000000,0.0,0.0,0.000000,...,2,3,4,3,4.0,2,2.2,3422,11.2,Loyal
292,01J6ZWVY598Q0231A15CDM5P01,G***t,**********8997,10028,3,4.306247,0.961240,1.0,0.0,1.000000,...,3,1,4,1,4.0,4,2.4,1442,11.4,Loyal
293,01JCQS0KBQWB39ZZ7ZSJWZYZVF,G***t,**********2365,10028,2,0.930704,0.961240,1.0,0.0,1.000000,...,4,4,4,4,4.0,1,3.8,4414,12.8,Loyal
314,01J8MAXMCZHS2F1CDVNVJM99F6,장*준,************8541,10028,2,28.979989,0.625220,2.0,0.0,0.531250,...,2,3,3,3,3.0,4,2.4,3342,12.4,Loyal
316,01JDHB85J5K7WNJ4F697AS56Y2,김*준,************6417,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
320,01J7GCSWE2W71AZGBMTZB9AJTE,G***t,**********9222,10028,2,25.656785,1.402891,2.0,2.0,1.000000,...,4,2,3,2,3.0,4,3.8,2344,12.8,Loyal
334,01JAMT3AVYB3A9CXMGR82WNJC2,김*현,************2548,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,3,3.6,3234,11.1,Loyal
343,01J9AQFPM25TFH2NM6CR0ZE73Y,주*빈,************7511,10028,2,167.255254,1.310494,4.0,3540.0,0.083577,...,4,4,3,4,3.0,1,3.6,4314,11.6,Loyal
345,01J9T2NB44EG7R1G30E4KD4D68,안*빈,************6003,10028,3,0.710830,1.587920,8.0,30.0,1.000000,...,4,2,4,2,4.0,1,4.0,2414,11.0,Loyal
354,01JCJN74J3BMN21M4PKNRMMP7D,강*팔,************7391,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,4,1,4,2.0,1,3.8,4214,10.8,Loyal
356,01J0JM2DFHVBKZSKHJY53BW8TQ,정*윤,************1807,10028,2,0.218913,1.401974,4.0,10.0,0.666667,...,4,1,4,1,3.5,3,3.8,1434,11.3,Loyal
357,01JCYV3G35RTZNHHZEX3TJSW3E,G***t,**********1131,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal
359,01JD72KPBASQCTD7XHYSWNCM2S,G***t,**********5675,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,3,2.4,4232,11.4,Loyal

========== id : 10028, seg : Dormant ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
259,01HAKWDHX2VCAXR366TM0W6R1M,문*영,*********2792,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,2,1,3,1,2.0,1,2.0,1212,6.0,Dormant
263,01J9D83GP9JKREB9J6H2BRRGV1,박*영,************8343,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
269,01J84Y68Z1Y6C3P9G4Q1C8NRJX,조*일,************0317,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.2,1211,4.7,Dormant
285,01J7N0QJ5TGEQRHTRMJ0JZ4YRN,이*은,************7039,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.0,1211,4.5,Dormant
294,01J6VEB3S4W7SEDXCNCPHSZCH3,G***t,**********6479,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
300,01J89YREX426JM4HC4GXF1J50M,G***t,**********5908,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,1,2.6,2213,7.1,Dormant
304,01J93P2KGBMTPDN1VT0Q5MKXNX,G***t,**********4092,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
309,01J7J7ZBVNS9V1GMSANRACB7R7,김*은,************3655,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,3,1.0,1231,6.5,Dormant
311,01J6XHT4TC5BGXDMHR2DSVS0DP,이*민,************6104,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
321,01J825R7VX59XNMCXF238J7M3R,정*주,************0627,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,1,2.6,2213,7.1,Dormant
328,01J7AZT8MCG8F20544JAW6HT6Y,G***t,**********1657,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,1,2.6,1213,6.1,Dormant
330,01J8XWBD7X7D927FATEF35PSET,심*민,************8352,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
332,01J784Y59DAVK50MVKJDFSM620,G***t,**********8970,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,3,1,2.0,2,2.4,1222,7.4,Dormant
337,01J7AK8095EN3ZYDRJKWRR9G4T,김*영,************7198,10028,1,NaN,0.741479,2.0,0.0,0.538462,...,2,1,2,1,1.5,2,2.0,1222,6.5,Dormant
339,01J7AAHFXFHQJ1F3PG0NHKE390,서*수,************3477,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,3,1.0,1231,7.0,Dormant
341,01J5WQ0C8KQMK62FA2ST4T5R4F,트**티,**********7776,10028,1,NaN,0.961240,11.0,0.0,1.000000,...,3,1,3,1,2.0,1,3.0,1213,7.0,Dormant
346,01J7CYHTN25HRTY8PBM43ETJN1,G***t,**********3056,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,3,1,2,1,1.5,1,2.8,1213,6.3,Dormant
349,01J78M4Q9CETX1XZSE8RFMRDC8,G***t,**********1784,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,3,1,2.0,2,1.0,1221,6.0,Dormant
350,01JAPG2A2X967KNQQ75NQRYJXX,김*채,************4693,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,3,1,3,1.5,1,1.4,3211,6.9,Dormant
351,01J9RAB5MF1EG5WE6Z6619KRTS,G***t,**********6969,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,2,1.2,2221,7.2,Dormant
353,01J7MQ20HY587DRKPHD92RX309,김*근,************6119,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,1,2,1,1.5,1,2.4,1212,5.9,Dormant
358,01J7TK1SM7J0QXWRPPDNEZPTN2,김*환,************6466,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,1,2,1,1.5,1,1.2,1211,4.7,Dormant
362,01J84MSVRT0HWN4T9NB0DP0Q0Y,김*주,************1793,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,1.5,1,2.6,2213,7.1,Dormant

========== id : 10028, seg : Growth ==========

,customerId,fullName,phoneNumber,storeId,visit_count,avg_revisit_days,pagerank,degree,betweenness,closeness,...,eigen_Q,recency_Q,revisit_gap_Q,R_score,F_score,M_score,N_score,stratum,total_score,segment
256,01JAPKNW9TJ8EPDDB9DGXF4KDE,G***t,**********1266,10028,1,NaN,0.740415,1.0,0.0,0.666667,...,2,3,1,3,1.5,2,2.6,3223,9.1,Growth
258,01J6EWVAPX8E59ERSK1M6QNZB4,G***t,**********8204,10028,3,2.519891,0.000000,0.0,0.0,0.000000,...,1,1,4,1,4.0,4,1.0,1441,10.0,Growth
267,01J7QVPA905HHJCFXABKCPND2K,G***t,**********4628,10028,2,0.026823,0.961240,1.0,0.0,1.000000,...,3,1,4,1,3.5,3,2.4,1432,9.9,Growth
271,01JCA3PXPNVNEXVBQWVKZZRRZT,박*화,************2229,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,2.0,2,3.6,3224,10.6,Growth
277,01JB945EJ1FCGCNVVXFHCQ7HH2,G***t,**********0515,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,2,3.6,3224,10.1,Growth
291,01JBR1J5R5VKCJWV74A4GZ1VX0,장*원,*********2465,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,4,2.2,3242,10.7,Growth
295,01JD4E17BSYN6WQ34YKH8XSZC0,배*롬,************2162,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,4,1,4,2.0,2,2.4,4222,10.4,Growth
298,01JCWB1Z4705RHXQ3BEMQA8J1T,곽*환,************3995,10028,1,NaN,0.346411,1.0,0.0,0.202335,...,2,4,1,4,2.0,1,2.6,4213,9.6,Growth
303,01J84ZW37M7HYD5TGPNC61PA7B,전*헌,************6535,10028,1,NaN,0.961240,3.0,0.0,1.000000,...,3,1,2,1,1.5,4,3.0,1243,9.5,Growth
305,01JC0HHEM1N2WH9BY7SPB326XW,김*훈,************7988,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,2,3.6,3224,10.1,Growth
306,01JBZQNVH4B8SM4R72DMCS41Q5,김*현,************6951,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,4,3,1,3,1.5,2,3.8,3224,10.3,Growth
310,01JBXVJD52N7C3TCRV8X7559Z6,오*식,************2854,10028,1,NaN,0.961240,2.0,0.0,1.000000,...,4,3,1,3,1.5,2,3.8,3224,10.3,Growth
312,01J93SHAQZJC75HT86F78XM4M6,G***t,**********5425,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,2,3.0,2223,9.0,Growth
313,01JC9ZJGVS43CR8FBAD8F8TFED,조*혜,************8772,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,2.0,2,3.6,3224,10.6,Growth
315,01JAWCT0QHAS04N2YWAC5307VE,육*연,************6923,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,4,3,1,3,1.5,1,3.6,3214,9.1,Growth
323,01JBXP4SSRPMV50XCF3NN5S05E,최*인,************1488,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,2,3,1,3,1.5,3,2.2,3232,9.7,Growth
324,01J9T5GDZEZN2NTW9G1GC96G5A,박*영,************3559,10028,2,0.844480,0.961240,1.0,0.0,1.000000,...,3,2,4,2,3.5,1,3.0,2413,9.5,Growth
325,01JA2T09H5ANX9K8KE9M27N7C3,최*지,************8586,10028,1,NaN,0.000000,0.0,0.0,0.000000,...,1,2,2,2,2.0,4,1.2,2241,9.2,Growth
327,01HBQFZMCNA4CBAXPWPEXVNHFT,김*서,************2370,10028,2,0.878986,0.961240,2.0,0.0,1.000000,...,2,4,4,4,3.5,1,2.2,4412,10.7,Growth
329,01J6KE1NB9A6R8CQ590B9H8PNR,조*선,************3887,10028,2,0.239533,1.333106,3.0,12.0,0.714286,...,4,1,4,1,3.5,1,3.8,1414,9.3,Growth
335,01J9QHARR2RM53M30AWJC0N9ZZ,김*정,************7176,10028,1,NaN,0.607275,2.0,0.0,0.515152,...,2,2,2,2,2.0,3,2.4,2232,9.4,Growth
340,01J95JMWEV0XVJYBF8Q6N15WYB,G***t,**********2958,10028,1,NaN,0.961240,1.0,0.0,1.000000,...,3,2,2,2,2.0,2,3.0,2223,9.0,Growth

### simple 버전

In [27]:
test[['customerId','storeId']].to_csv('../data/test_group_simple.csv', index=False, encoding='utf-8-sig')

In [26]:
control[['customerId','storeId']].to_csv('../data/control_group_simple.csv', index=False, encoding='utf-8-sig')