# store=3의 동반자 수(동일 인물 여러 번 초대해도 1번으로 계산)

In [3]:
from neo4j import GraphDatabase
import pandas as pd
from IPython.display import display

# Neo4j 연결
driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "gustjs21@"))

def run_query(tx, query):
    return tx.run(query).data()

# 방향 없는 동반자 수 쿼리 (store 3 기준)
query = """
MATCH (c:Customer)-[:`DINED_WITH_3`]-(d:Customer)
WHERE id(c) < id(d)
UNWIND [c, d] AS person
RETURN COALESCE(person.id, toString(ID(person))) AS customerId,
       COUNT(*) AS companion_count
"""

with driver.session(database="sicpama") as session:
    result = session.execute_read(run_query, query)

# DataFrame으로 변환
df_companion = pd.DataFrame(result)

# 출력
print("✅ store 3 기준, 고객별 동반자 수:")
display(df_companion)

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function. ('id' has been replaced by 'elementId or an application-generated id')} {position: line: 3, column: 7, offset: 57} for query: '\nMATCH (c:Customer)-[:`DINED_WITH_3`]-(d:Customer)\nWHERE id(c) < id(d)\nUNWIND [c, d] AS person\nRETURN COALESCE(person.id, toString(ID(person))) AS customerId,\n       COUNT(*) AS companion_count\n'
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function. ('id' has been replaced by 'elementId or an application-generated id')} {position: line: 3, column: 15, offset: 65} for query: '\nMATCH (c:Customer)-[:`DINED_WITH_3`]-(d:Customer)\nWHERE id(c) < id(d)\nUNWIND [c, d] AS person\nRETURN COALESCE(person.id, toString(ID(person))) AS customerId,\n       COUNT(*) AS companion_count\n'
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function. ('id' has been replaced by 'elementId or an application-generated id')} {position: line: 5, column: 37, offset: 131} for query: '\nMATCH (c:Customer)-[:`DINED_WITH_3`]-(d:Customer)\nWHERE id(c) < id(d)\nUNWIND [c, d] AS person\nRETURN COALESCE(person.id, toString(ID(person))) AS customerId,\n       COUNT(*) AS companion_count\n'

✅ store 3 기준, 고객별 동반자 수:

                       customerId  companion_count
0      01GYNFXQNDD0ATWHDFXCBHD5XG              333
1      01H7KZNWPQ3ZCXTEYM25XR54EW                1
2      01H7MBCAAT5N6ZWQY6V6SC32XB                1
3      01H7MCFH99MSQ0RXEREYY77XPT                2
4      01H7MDNCH41780VJNTHZHWYQT0                2
...                           ...              ...
11590  01JV4SH68N0PC7QGMYCVQYX0QY                1
11591  01JV4P923WY392D9K6V9P321S2                1
11592  01JV4RSHXDXH2CA97T0SHTTMSR                1
11593  01JV6C5JAJ7Q6EA7Q5RAPG9B4J                1
11594  01JV6C76P6ZEK56Z8AAB1WAFAF                1

[11595 rows x 2 columns]

# store=5 동반자 수

In [6]:
from neo4j import GraphDatabase
import pandas as pd
from IPython.display import display

# Neo4j 연결
driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "gustjs21@"))

def run_query(tx, query):
    return tx.run(query).data()

# 방향 없는 동반자 수 쿼리 (store 5 기준)
query = """
MATCH (c:Customer)-[:`DINED_WITH_5`]-(d:Customer)
WHERE id(c) < id(d)
UNWIND [c, d] AS person
RETURN COALESCE(person.id, toString(ID(person))) AS customerId,
       COUNT(*) AS companion_count
"""

with driver.session(database="sicpama") as session:
    result = session.execute_read(run_query, query)

# DataFrame으로 변환
df_companion = pd.DataFrame(result)

# 출력
print("✅ store 5 기준, 고객별 동반자 수:")
display(df_companion)

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function. ('id' has been replaced by 'elementId or an application-generated id')} {position: line: 3, column: 7, offset: 57} for query: '\nMATCH (c:Customer)-[:`DINED_WITH_5`]-(d:Customer)\nWHERE id(c) < id(d)\nUNWIND [c, d] AS person\nRETURN COALESCE(person.id, toString(ID(person))) AS customerId,\n       COUNT(*) AS companion_count\n'
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function. ('id' has been replaced by 'elementId or an application-generated id')} {position: line: 3, column: 15, offset: 65} for query: '\nMATCH (c:Customer)-[:`DINED_WITH_5`]-(d:Customer)\nWHERE id(c) < id(d)\nUNWIND [c, d] AS person\nRETURN COALESCE(person.id, toString(ID(person))) AS customerId,\n       COUNT(*) AS companion_count\n'
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function. ('id' has been replaced by 'elementId or an application-generated id')} {position: line: 5, column: 37, offset: 131} for query: '\nMATCH (c:Customer)-[:`DINED_WITH_5`]-(d:Customer)\nWHERE id(c) < id(d)\nUNWIND [c, d] AS person\nRETURN COALESCE(person.id, toString(ID(person))) AS customerId,\n       COUNT(*) AS companion_count\n'

✅ store 5 기준, 고객별 동반자 수:

                      customerId  companion_count
0     01GYNFXQNDD0ATWHDFXCBHD5XG               62
1     01HA9EJ87JZ3MGQG28X04Y2JMW                3
2     01HA9EKEWEQPZZM1CQG1Y1JNHK                3
3     01HA9EQX61NH4ACGHX7095YQB4                3
4     01HA9NKEGC1J6SM7KDP577B09X                6
...                          ...              ...
1212  01JTPS169FSK5H58NZYNBSGRSQ                5
1213  01JTPS16D0K8MT889TTZYGZNT9                5
1214  01JTPS16D7WPJNKS6P3BC9DH65                5
1215  01JTPS16QW5GWHRJ2T8WQG6N0V                5
1216  01JTPS16VH8T7E5MQDTZW00MEK                5

[1217 rows x 2 columns]

# store=10028 동반자 수

In [7]:
from neo4j import GraphDatabase
import pandas as pd
from IPython.display import display

# Neo4j 연결
driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "gustjs21@"))

def run_query(tx, query):
    return tx.run(query).data()

# 방향 없는 동반자 수 쿼리 (store 5 기준)
query = """
MATCH (c:Customer)-[:`DINED_WITH_10028`]-(d:Customer)
WHERE id(c) < id(d)
UNWIND [c, d] AS person
RETURN COALESCE(person.id, toString(ID(person))) AS customerId,
       COUNT(*) AS companion_count
"""

with driver.session(database="sicpama") as session:
    result = session.execute_read(run_query, query)

# DataFrame으로 변환
df_companion = pd.DataFrame(result)

# 출력
print("✅ store 10028 기준, 고객별 동반자 수:")
display(df_companion)

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function. ('id' has been replaced by 'elementId or an application-generated id')} {position: line: 3, column: 7, offset: 61} for query: '\nMATCH (c:Customer)-[:`DINED_WITH_10028`]-(d:Customer)\nWHERE id(c) < id(d)\nUNWIND [c, d] AS person\nRETURN COALESCE(person.id, toString(ID(person))) AS customerId,\n       COUNT(*) AS companion_count\n'
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function. ('id' has been replaced by 'elementId or an application-generated id')} {position: line: 3, column: 15, offset: 69} for query: '\nMATCH (c:Customer)-[:`DINED_WITH_10028`]-(d:Customer)\nWHERE id(c) < id(d)\nUNWIND [c, d] AS person\nRETURN COALESCE(person.id, toString(ID(person))) AS customerId,\n       COUNT(*) AS companion_count\n'
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function. ('id' has been replaced by 'elementId or an application-generated id')} {position: line: 5, column: 37, offset: 135} for query: '\nMATCH (c:Customer)-[:`DINED_WITH_10028`]-(d:Customer)\nWHERE id(c) < id(d)\nUNWIND [c, d] AS person\nRETURN COALESCE(person.id, toString(ID(person))) AS customerId,\n       COUNT(*) AS companion_count\n'

✅ store 10028 기준, 고객별 동반자 수:

                      customerId  companion_count
0     01H85T8BGM0WMY2H9G72XB1EX7                1
1     01JF9WPNSCV89XQ97NPBKCSWRW                1
2     01H9YV0N7ZR2M8HNJHJBXFBJK1                1
3     01JK0B3N4SMAD6SY8P6HWV4407                1
4     01HA6B7GK1J53TCM4TN0T9FP7F                1
...                          ...              ...
9232  01JV6CJ4F1C9DMFX6HB2SQGX0V                1
9233  01JV6CM23YS0EMN95H1XHK0VJ2                3
9234  01JV6CM24Q2TP3QK05RBJMN38T                3
9235  01JV6CM25Q7TVPG8NY3SH962Q6                3
9236  01JV6CM29T5HDSGVQPFP8ZA0K0                3

[9237 rows x 2 columns]