# 리스트 표현식
* 리스트 안에 for 반복문과 if else 조건문을 한 번에 적어서 리스트를 만드는 방법
* 여러 줄의 코드를 1줄로 줄일 수 있다.
* for문과 if else 문을 사용해서 처리할 때보다 속도가 빠르다.
* [실행할 명령 for 변수 in list, tuple]

In [1]:
for i in range(1,11):
    print("짝수입니다.") if i%2==0 else print("홀수입니다")

홀수입니다
짝수입니다.
홀수입니다
짝수입니다.
홀수입니다
짝수입니다.
홀수입니다
짝수입니다.
홀수입니다
짝수입니다.

* 1부터 10까지 들어있는 리스트 만들기

In [2]:
a1=[]
for i in range(1,11):
    a1.append(i)
a1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
[i for i in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### 리스트 표현식과 일반 반복문 속도 차이

In [2]:
import time

In [ ]:
start=time.time()
a=[]
for i in range(1,200000000):
    a.append(i+5)
print(a[:10])

print("코드 실행 시간: ", time.time()-start)

In [7]:
%%time
##start2=time.time()
b=[i+5 for i in range(1,200000000)]
print(b[:10])
print("코드 실행 시간: ", time.time()-start2)

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
코드 실행 시간:  630.2650246620178
CPU times: total: 14.5 s
Wall time: 14.6 s

In [4]:
import numpy as np

In [6]:
start3=time.time()
c=np.arange(1,200000000)
c=c+5
print("코드 실행 시간: ", time.time()-start3)

코드 실행 시간:  0.7995119094848633

* 1에서 10까지의 숫자 중 짝수만 넣어서 리스트 만들기

In [8]:
a1=[]
for i in range(1,11):
    if i %2 ==0:
        a1.append(i)
a1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
[i for i in range(1,11) if i%2==0]

[2, 4, 6, 8, 10]

## 다중 반복문을 사용한 리스트 표현식
[i*j for i in range(2, 10) for j in range(1, 9)

In [10]:
gugu=[]
for i in range(2, 10):
    for j in range(1,10):
        gugu.append(f"{i} x {j}={i*j}")
gugu

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 8,
 16,
 24,
 32,
 40,
 48,
 56,
 64,
 72,
 9,
 18,
 27,
 36,
 45,
 54,
 63,
 72,
 81]

In [11]:
[f"{i} x {j}={i*j}" for i in range(2, 10) for j in range(1,10)]

['2 x 1=2',
 '2 x 2=4',
 '2 x 3=6',
 '2 x 4=8',
 '2 x 5=10',
 '2 x 6=12',
 '2 x 7=14',
 '2 x 8=16',
 '2 x 9=18',
 '3 x 1=3',
 '3 x 2=6',
 '3 x 3=9',
 '3 x 4=12',
 '3 x 5=15',
 '3 x 6=18',
 '3 x 7=21',
 '3 x 8=24',
 '3 x 9=27',
 '4 x 1=4',
 '4 x 2=8',
 '4 x 3=12',
 '4 x 4=16',
 '4 x 5=20',
 '4 x 6=24',
 '4 x 7=28',
 '4 x 8=32',
 '4 x 9=36',
 '5 x 1=5',
 '5 x 2=10',
 '5 x 3=15',
 '5 x 4=20',
 '5 x 5=25',
 '5 x 6=30',
 '5 x 7=35',
 '5 x 8=40',
 '5 x 9=45',
 '6 x 1=6',
 '6 x 2=12',
 '6 x 3=18',
 '6 x 4=24',
 '6 x 5=30',
 '6 x 6=36',
 '6 x 7=42',
 '6 x 8=48',
 '6 x 9=54',
 '7 x 1=7',
 '7 x 2=14',
 '7 x 3=21',
 '7 x 4=28',
 '7 x 5=35',
 '7 x 6=42',
 '7 x 7=49',
 '7 x 8=56',
 '7 x 9=63',
 '8 x 1=8',
 '8 x 2=16',
 '8 x 3=24',
 '8 x 4=32',
 '8 x 5=40',
 '8 x 6=48',
 '8 x 7=56',
 '8 x 8=64',
 '8 x 9=72',
 '9 x 1=9',
 '9 x 2=18',
 '9 x 3=27',
 '9 x 4=36',
 '9 x 5=45',
 '9 x 6=54',
 '9 x 7=63',
 '9 x 8=72',
 '9 x 9=81']

In [13]:
[f"{i:02d}시 {j:02d}분 {k:02d}초" for i in range(0,23) for j in range(0,60) for k in range(0,60)]

['00시 00분 00초',
 '00시 00분 01초',
 '00시 00분 02초',
 '00시 00분 03초',
 '00시 00분 04초',
 '00시 00분 05초',
 '00시 00분 06초',
 '00시 00분 07초',
 '00시 00분 08초',
 '00시 00분 09초',
 '00시 00분 10초',
 '00시 00분 11초',
 '00시 00분 12초',
 '00시 00분 13초',
 '00시 00분 14초',
 '00시 00분 15초',
 '00시 00분 16초',
 '00시 00분 17초',
 '00시 00분 18초',
 '00시 00분 19초',
 '00시 00분 20초',
 '00시 00분 21초',
 '00시 00분 22초',
 '00시 00분 23초',
 '00시 00분 24초',
 '00시 00분 25초',
 '00시 00분 26초',
 '00시 00분 27초',
 '00시 00분 28초',
 '00시 00분 29초',
 '00시 00분 30초',
 '00시 00분 31초',
 '00시 00분 32초',
 '00시 00분 33초',
 '00시 00분 34초',
 '00시 00분 35초',
 '00시 00분 36초',
 '00시 00분 37초',
 '00시 00분 38초',
 '00시 00분 39초',
 '00시 00분 40초',
 '00시 00분 41초',
 '00시 00분 42초',
 '00시 00분 43초',
 '00시 00분 44초',
 '00시 00분 45초',
 '00시 00분 46초',
 '00시 00분 47초',
 '00시 00분 48초',
 '00시 00분 49초',
 '00시 00분 50초',
 '00시 00분 51초',
 '00시 00분 52초',
 '00시 00분 53초',
 '00시 00분 54초',
 '00시 00분 55초',
 '00시 00분 56초',
 '00시 00분 57초',
 '00시 00분 58초',
 '00시 00분 59초',
 '00시 01분 00초',
 '00시 01분 01초',
 '00시 01분 02초',
 '00시 01분 03초',
 '00시 01분 04초',
 '00시 01분 05초',
 '00시 01분 06초',
 '00시 01분 07초',
 '00시 01분 08초',
 '00시 01분 09초',
 '00시 01분 10초',
 '00시 01분 11초',
 '00시 01분 12초',
 '00시 01분 13초',
 '00시 01분 14초',
 '00시 01분 15초',
 '00시 01분 16초',
 '00시 01분 17초',
 '00시 01분 18초',
 '00시 01분 19초',
 '00시 01분 20초',
 '00시 01분 21초',
 '00시 01분 22초',
 '00시 01분 23초',
 '00시 01분 24초',
 '00시 01분 25초',
 '00시 01분 26초',
 '00시 01분 27초',
 '00시 01분 28초',
 '00시 01분 29초',
 '00시 01분 30초',
 '00시 01분 31초',
 '00시 01분 32초',
 '00시 01분 33초',
 '00시 01분 34초',
 '00시 01분 35초',
 '00시 01분 36초',
 '00시 01분 37초',
 '00시 01분 38초',
 '00시 01분 39초',
 '00시 01분 40초',
 '00시 01분 41초',
 '00시 01분 42초',
 '00시 01분 43초',
 '00시 01분 44초',
 '00시 01분 45초',
 '00시 01분 46초',
 '00시 01분 47초',
 '00시 01분 48초',
 '00시 01분 49초',
 '00시 01분 50초',
 '00시 01분 51초',
 '00시 01분 52초',
 '00시 01분 53초',
 '00시 01분 54초',
 '00시 01분 55초',
 '00시 01분 56초',
 '00시 01분 57초',
 '00시 01분 58초',
 '00시 01분 59초',
 '00시 02분 00초',
 '00시 02분 01초',
 '00시 02분 02초',
 '00시 02분 03초',
 '00시 02분 04초',
 '00시 02분 05초',
 '00시 02분 06초',
 '00시 02분 07초',
 '00시 02분 08초',
 '00시 02분 09초',
 '00시 02분 10초',
 '00시 02분 11초',
 '00시 02분 12초',
 '00시 02분 13초',
 '00시 02분 14초',
 '00시 02분 15초',
 '00시 02분 16초',
 '00시 02분 17초',
 '00시 02분 18초',
 '00시 02분 19초',
 '00시 02분 20초',
 '00시 02분 21초',
 '00시 02분 22초',
 '00시 02분 23초',
 '00시 02분 24초',
 '00시 02분 25초',
 '00시 02분 26초',
 '00시 02분 27초',
 '00시 02분 28초',
 '00시 02분 29초',
 '00시 02분 30초',
 '00시 02분 31초',
 '00시 02분 32초',
 '00시 02분 33초',
 '00시 02분 34초',
 '00시 02분 35초',
 '00시 02분 36초',
 '00시 02분 37초',
 '00시 02분 38초',
 '00시 02분 39초',
 '00시 02분 40초',
 '00시 02분 41초',
 '00시 02분 42초',
 '00시 02분 43초',
 '00시 02분 44초',
 '00시 02분 45초',
 '00시 02분 46초',
 '00시 02분 47초',
 '00시 02분 48초',
 '00시 02분 49초',
 '00시 02분 50초',
 '00시 02분 51초',
 '00시 02분 52초',
 '00시 02분 53초',
 '00시 02분 54초',
 '00시 02분 55초',
 '00시 02분 56초',
 '00시 02분 57초',
 '00시 02분 58초',
 '00시 02분 59초',
 '00시 03분 00초',
 '00시 03분 01초',
 '00시 03분 02초',
 '00시 03분 03초',
 '00시 03분 04초',
 '00시 03분 05초',
 '00시 03분 06초',
 '00시 03분 07초',
 '00시 03분 08초',
 '00시 03분 09초',
 '00시 03분 10초',
 '00시 03분 11초',
 '00시 03분 12초',
 '00시 03분 13초',
 '00시 03분 14초',
 '00시 03분 15초',
 '00시 03분 16초',
 '00시 03분 17초',
 '00시 03분 18초',
 '00시 03분 19초',
 '00시 03분 20초',
 '00시 03분 21초',
 '00시 03분 22초',
 '00시 03분 23초',
 '00시 03분 24초',
 '00시 03분 25초',
 '00시 03분 26초',
 '00시 03분 27초',
 '00시 03분 28초',
 '00시 03분 29초',
 '00시 03분 30초',
 '00시 03분 31초',
 '00시 03분 32초',
 '00시 03분 33초',
 '00시 03분 34초',
 '00시 03분 35초',
 '00시 03분 36초',
 '00시 03분 37초',
 '00시 03분 38초',
 '00시 03분 39초',
 '00시 03분 40초',
 '00시 03분 41초',
 '00시 03분 42초',
 '00시 03분 43초',
 '00시 03분 44초',
 '00시 03분 45초',
 '00시 03분 46초',
 '00시 03분 47초',
 '00시 03분 48초',
 '00시 03분 49초',
 '00시 03분 50초',
 '00시 03분 51초',
 '00시 03분 52초',
 '00시 03분 53초',
 '00시 03분 54초',
 '00시 03분 55초',
 '00시 03분 56초',
 '00시 03분 57초',
 '00시 03분 58초',
 '00시 03분 59초',
 '00시 04분 00초',
 '00시 04분 01초',
 '00시 04분 02초',
 '00시 04분 03초',
 '00시 04분 04초',
 '00시 04분 05초',
 '00시 04분 06초',
 '00시 04분 07초',
 '00시 04분 08초',
 '00시 04분 09초',
 '00시 04분 10초',
 '00시 04분 11초',
 '00시 04분 12초',
 '00시 04분 13초',
 '00시 04분 14초',
 '00시 04분 15초',
 '00시 04분 16초',
 '00시 04분 17초',
 '00시 04분 18초',
 '00시 04분 19초',
 '00시 04분 20초',
 '00시 04분 21초',
 '00시 04분 22초',
 '00시 04분 23초',
 '00시 04분 24초',
 '00시 04분 25초',
 '00시 04분 26초',
 '00시 04분 27초',
 '00시 04분 28초',
 '00시 04분 29초',
 '00시 04분 30초',
 '00시 04분 31초',
 '00시 04분 32초',
 '00시 04분 33초',
 '00시 04분 34초',
 '00시 04분 35초',
 '00시 04분 36초',
 '00시 04분 37초',
 '00시 04분 38초',
 '00시 04분 39초',
 '00시 04분 40초',
 '00시 04분 41초',
 '00시 04분 42초',
 '00시 04분 43초',
 '00시 04분 44초',
 '00시 04분 45초',
 '00시 04분 46초',
 '00시 04분 47초',
 '00시 04분 48초',
 '00시 04분 49초',
 '00시 04분 50초',
 '00시 04분 51초',
 '00시 04분 52초',
 '00시 04분 53초',
 '00시 04분 54초',
 '00시 04분 55초',
 '00시 04분 56초',
 '00시 04분 57초',
 '00시 04분 58초',
 '00시 04분 59초',
 '00시 05분 00초',
 '00시 05분 01초',
 '00시 05분 02초',
 '00시 05분 03초',
 '00시 05분 04초',
 '00시 05분 05초',
 '00시 05분 06초',
 '00시 05분 07초',
 '00시 05분 08초',
 '00시 05분 09초',
 '00시 05분 10초',
 '00시 05분 11초',
 '00시 05분 12초',
 '00시 05분 13초',
 '00시 05분 14초',
 '00시 05분 15초',
 '00시 05분 16초',
 '00시 05분 17초',
 '00시 05분 18초',
 '00시 05분 19초',
 '00시 05분 20초',
 '00시 05분 21초',
 '00시 05분 22초',
 '00시 05분 23초',
 '00시 05분 24초',
 '00시 05분 25초',
 '00시 05분 26초',
 '00시 05분 27초',
 '00시 05분 28초',
 '00시 05분 29초',
 '00시 05분 30초',
 '00시 05분 31초',
 '00시 05분 32초',
 '00시 05분 33초',
 '00시 05분 34초',
 '00시 05분 35초',
 '00시 05분 36초',
 '00시 05분 37초',
 '00시 05분 38초',
 '00시 05분 39초',
 '00시 05분 40초',
 '00시 05분 41초',
 '00시 05분 42초',
 '00시 05분 43초',
 '00시 05분 44초',
 '00시 05분 45초',
 '00시 05분 46초',
 '00시 05분 47초',
 '00시 05분 48초',
 '00시 05분 49초',
 '00시 05분 50초',
 '00시 05분 51초',
 '00시 05분 52초',
 '00시 05분 53초',
 '00시 05분 54초',
 '00시 05분 55초',
 '00시 05분 56초',
 '00시 05분 57초',
 '00시 05분 58초',
 '00시 05분 59초',
 '00시 06분 00초',
 '00시 06분 01초',
 '00시 06분 02초',
 '00시 06분 03초',
 '00시 06분 04초',
 '00시 06분 05초',
 '00시 06분 06초',
 '00시 06분 07초',
 '00시 06분 08초',
 '00시 06분 09초',
 '00시 06분 10초',
 '00시 06분 11초',
 '00시 06분 12초',
 '00시 06분 13초',
 '00시 06분 14초',
 '00시 06분 15초',
 '00시 06분 16초',
 '00시 06분 17초',
 '00시 06분 18초',
 '00시 06분 19초',
 '00시 06분 20초',
 '00시 06분 21초',
 '00시 06분 22초',
 '00시 06분 23초',
 '00시 06분 24초',
 '00시 06분 25초',
 '00시 06분 26초',
 '00시 06분 27초',
 '00시 06분 28초',
 '00시 06분 29초',
 '00시 06분 30초',
 '00시 06분 31초',
 '00시 06분 32초',
 '00시 06분 33초',
 '00시 06분 34초',
 '00시 06분 35초',
 '00시 06분 36초',
 '00시 06분 37초',
 '00시 06분 38초',
 '00시 06분 39초',
 '00시 06분 40초',
 '00시 06분 41초',
 '00시 06분 42초',
 '00시 06분 43초',
 '00시 06분 44초',
 '00시 06분 45초',
 '00시 06분 46초',
 '00시 06분 47초',
 '00시 06분 48초',
 '00시 06분 49초',
 '00시 06분 50초',
 '00시 06분 51초',
 '00시 06분 52초',
 '00시 06분 53초',
 '00시 06분 54초',
 '00시 06분 55초',
 '00시 06분 56초',
 '00시 06분 57초',
 '00시 06분 58초',
 '00시 06분 59초',
 '00시 07분 00초',
 '00시 07분 01초',
 '00시 07분 02초',
 '00시 07분 03초',
 '00시 07분 04초',
 '00시 07분 05초',
 '00시 07분 06초',
 '00시 07분 07초',
 '00시 07분 08초',
 '00시 07분 09초',
 '00시 07분 10초',
 '00시 07분 11초',
 '00시 07분 12초',
 '00시 07분 13초',
 '00시 07분 14초',
 '00시 07분 15초',
 '00시 07분 16초',
 '00시 07분 17초',
 '00시 07분 18초',
 '00시 07분 19초',
 '00시 07분 20초',
 '00시 07분 21초',
 '00시 07분 22초',
 '00시 07분 23초',
 '00시 07분 24초',
 '00시 07분 25초',
 '00시 07분 26초',
 '00시 07분 27초',
 '00시 07분 28초',
 '00시 07분 29초',
 '00시 07분 30초',
 '00시 07분 31초',
 '00시 07분 32초',
 '00시 07분 33초',
 '00시 07분 34초',
 '00시 07분 35초',
 '00시 07분 36초',
 '00시 07분 37초',
 '00시 07분 38초',
 '00시 07분 39초',
 '00시 07분 40초',
 '00시 07분 41초',
 '00시 07분 42초',
 '00시 07분 43초',
 '00시 07분 44초',
 '00시 07분 45초',
 '00시 07분 46초',
 '00시 07분 47초',
 '00시 07분 48초',
 '00시 07분 49초',
 '00시 07분 50초',
 '00시 07분 51초',
 '00시 07분 52초',
 '00시 07분 53초',
 '00시 07분 54초',
 '00시 07분 55초',
 '00시 07분 56초',
 '00시 07분 57초',
 '00시 07분 58초',
 '00시 07분 59초',
 '00시 08분 00초',
 '00시 08분 01초',
 '00시 08분 02초',
 '00시 08분 03초',
 '00시 08분 04초',
 '00시 08분 05초',
 '00시 08분 06초',
 '00시 08분 07초',
 '00시 08분 08초',
 '00시 08분 09초',
 '00시 08분 10초',
 '00시 08분 11초',
 '00시 08분 12초',
 '00시 08분 13초',
 '00시 08분 14초',
 '00시 08분 15초',
 '00시 08분 16초',
 '00시 08분 17초',
 '00시 08분 18초',
 '00시 08분 19초',
 '00시 08분 20초',
 '00시 08분 21초',
 '00시 08분 22초',
 '00시 08분 23초',
 '00시 08분 24초',
 '00시 08분 25초',
 '00시 08분 26초',
 '00시 08분 27초',
 '00시 08분 28초',
 '00시 08분 29초',
 '00시 08분 30초',
 '00시 08분 31초',
 '00시 08분 32초',
 '00시 08분 33초',
 '00시 08분 34초',
 '00시 08분 35초',
 '00시 08분 36초',
 '00시 08분 37초',
 '00시 08분 38초',
 '00시 08분 39초',
 '00시 08분 40초',
 '00시 08분 41초',
 '00시 08분 42초',
 '00시 08분 43초',
 '00시 08분 44초',
 '00시 08분 45초',
 '00시 08분 46초',
 '00시 08분 47초',
 '00시 08분 48초',
 '00시 08분 49초',
 '00시 08분 50초',
 '00시 08분 51초',
 '00시 08분 52초',
 '00시 08분 53초',
 '00시 08분 54초',
 '00시 08분 55초',
 '00시 08분 56초',
 '00시 08분 57초',
 '00시 08분 58초',
 '00시 08분 59초',
 '00시 09분 00초',
 '00시 09분 01초',
 '00시 09분 02초',
 '00시 09분 03초',
 '00시 09분 04초',
 '00시 09분 05초',
 '00시 09분 06초',
 '00시 09분 07초',
 '00시 09분 08초',
 '00시 09분 09초',
 '00시 09분 10초',
 '00시 09분 11초',
 '00시 09분 12초',
 '00시 09분 13초',
 '00시 09분 14초',
 '00시 09분 15초',
 '00시 09분 16초',
 '00시 09분 17초',
 '00시 09분 18초',
 '00시 09분 19초',
 '00시 09분 20초',
 '00시 09분 21초',
 '00시 09분 22초',
 '00시 09분 23초',
 '00시 09분 24초',
 '00시 09분 25초',
 '00시 09분 26초',
 '00시 09분 27초',
 '00시 09분 28초',
 '00시 09분 29초',
 '00시 09분 30초',
 '00시 09분 31초',
 '00시 09분 32초',
 '00시 09분 33초',
 '00시 09분 34초',
 '00시 09분 35초',
 '00시 09분 36초',
 '00시 09분 37초',
 '00시 09분 38초',
 '00시 09분 39초',
 '00시 09분 40초',
 '00시 09분 41초',
 '00시 09분 42초',
 '00시 09분 43초',
 '00시 09분 44초',
 '00시 09분 45초',
 '00시 09분 46초',
 '00시 09분 47초',
 '00시 09분 48초',
 '00시 09분 49초',
 '00시 09분 50초',
 '00시 09분 51초',
 '00시 09분 52초',
 '00시 09분 53초',
 '00시 09분 54초',
 '00시 09분 55초',
 '00시 09분 56초',
 '00시 09분 57초',
 '00시 09분 58초',
 '00시 09분 59초',
 '00시 10분 00초',
 '00시 10분 01초',
 '00시 10분 02초',
 '00시 10분 03초',
 '00시 10분 04초',
 '00시 10분 05초',
 '00시 10분 06초',
 '00시 10분 07초',
 '00시 10분 08초',
 '00시 10분 09초',
 '00시 10분 10초',
 '00시 10분 11초',
 '00시 10분 12초',
 '00시 10분 13초',
 '00시 10분 14초',
 '00시 10분 15초',
 '00시 10분 16초',
 '00시 10분 17초',
 '00시 10분 18초',
 '00시 10분 19초',
 '00시 10분 20초',
 '00시 10분 21초',
 '00시 10분 22초',
 '00시 10분 23초',
 '00시 10분 24초',
 '00시 10분 25초',
 '00시 10분 26초',
 '00시 10분 27초',
 '00시 10분 28초',
 '00시 10분 29초',
 '00시 10분 30초',
 '00시 10분 31초',
 '00시 10분 32초',
 '00시 10분 33초',
 '00시 10분 34초',
 '00시 10분 35초',
 '00시 10분 36초',
 '00시 10분 37초',
 '00시 10분 38초',
 '00시 10분 39초',
 '00시 10분 40초',
 '00시 10분 41초',
 '00시 10분 42초',
 '00시 10분 43초',
 '00시 10분 44초',
 '00시 10분 45초',
 '00시 10분 46초',
 '00시 10분 47초',
 '00시 10분 48초',
 '00시 10분 49초',
 '00시 10분 50초',
 '00시 10분 51초',
 '00시 10분 52초',
 '00시 10분 53초',
 '00시 10분 54초',
 '00시 10분 55초',
 '00시 10분 56초',
 '00시 10분 57초',
 '00시 10분 58초',
 '00시 10분 59초',
 '00시 11분 00초',
 '00시 11분 01초',
 '00시 11분 02초',
 '00시 11분 03초',
 '00시 11분 04초',
 '00시 11분 05초',
 '00시 11분 06초',
 '00시 11분 07초',
 '00시 11분 08초',
 '00시 11분 09초',
 '00시 11분 10초',
 '00시 11분 11초',
 '00시 11분 12초',
 '00시 11분 13초',
 '00시 11분 14초',
 '00시 11분 15초',
 '00시 11분 16초',
 '00시 11분 17초',
 '00시 11분 18초',
 '00시 11분 19초',
 '00시 11분 20초',
 '00시 11분 21초',
 '00시 11분 22초',
 '00시 11분 23초',
 '00시 11분 24초',
 '00시 11분 25초',
 '00시 11분 26초',
 '00시 11분 27초',
 '00시 11분 28초',
 '00시 11분 29초',
 '00시 11분 30초',
 '00시 11분 31초',
 '00시 11분 32초',
 '00시 11분 33초',
 '00시 11분 34초',
 '00시 11분 35초',
 '00시 11분 36초',
 '00시 11분 37초',
 '00시 11분 38초',
 '00시 11분 39초',
 '00시 11분 40초',
 '00시 11분 41초',
 '00시 11분 42초',
 '00시 11분 43초',
 '00시 11분 44초',
 '00시 11분 45초',
 '00시 11분 46초',
 '00시 11분 47초',
 '00시 11분 48초',
 '00시 11분 49초',
 '00시 11분 50초',
 '00시 11분 51초',
 '00시 11분 52초',
 '00시 11분 53초',
 '00시 11분 54초',
 '00시 11분 55초',
 '00시 11분 56초',
 '00시 11분 57초',
 '00시 11분 58초',
 '00시 11분 59초',
 '00시 12분 00초',
 '00시 12분 01초',
 '00시 12분 02초',
 '00시 12분 03초',
 '00시 12분 04초',
 '00시 12분 05초',
 '00시 12분 06초',
 '00시 12분 07초',
 '00시 12분 08초',
 '00시 12분 09초',
 '00시 12분 10초',
 '00시 12분 11초',
 '00시 12분 12초',
 '00시 12분 13초',
 '00시 12분 14초',
 '00시 12분 15초',
 '00시 12분 16초',
 '00시 12분 17초',
 '00시 12분 18초',
 '00시 12분 19초',
 '00시 12분 20초',
 '00시 12분 21초',
 '00시 12분 22초',
 '00시 12분 23초',
 '00시 12분 24초',
 '00시 12분 25초',
 '00시 12분 26초',
 '00시 12분 27초',
 '00시 12분 28초',
 '00시 12분 29초',
 '00시 12분 30초',
 '00시 12분 31초',
 '00시 12분 32초',
 '00시 12분 33초',
 '00시 12분 34초',
 '00시 12분 35초',
 '00시 12분 36초',
 '00시 12분 37초',
 '00시 12분 38초',
 '00시 12분 39초',
 '00시 12분 40초',
 '00시 12분 41초',
 '00시 12분 42초',
 '00시 12분 43초',
 '00시 12분 44초',
 '00시 12분 45초',
 '00시 12분 46초',
 '00시 12분 47초',
 '00시 12분 48초',
 '00시 12분 49초',
 '00시 12분 50초',
 '00시 12분 51초',
 '00시 12분 52초',
 '00시 12분 53초',
 '00시 12분 54초',
 '00시 12분 55초',
 '00시 12분 56초',
 '00시 12분 57초',
 '00시 12분 58초',
 '00시 12분 59초',
 '00시 13분 00초',
 '00시 13분 01초',
 '00시 13분 02초',
 '00시 13분 03초',
 '00시 13분 04초',
 '00시 13분 05초',
 '00시 13분 06초',
 '00시 13분 07초',
 '00시 13분 08초',
 '00시 13분 09초',
 '00시 13분 10초',
 '00시 13분 11초',
 '00시 13분 12초',
 '00시 13분 13초',
 '00시 13분 14초',
 '00시 13분 15초',
 '00시 13분 16초',
 '00시 13분 17초',
 '00시 13분 18초',
 '00시 13분 19초',
 '00시 13분 20초',
 '00시 13분 21초',
 '00시 13분 22초',
 '00시 13분 23초',
 '00시 13분 24초',
 '00시 13분 25초',
 '00시 13분 26초',
 '00시 13분 27초',
 '00시 13분 28초',
 '00시 13분 29초',
 '00시 13분 30초',
 '00시 13분 31초',
 '00시 13분 32초',
 '00시 13분 33초',
 '00시 13분 34초',
 '00시 13분 35초',
 '00시 13분 36초',
 '00시 13분 37초',
 '00시 13분 38초',
 '00시 13분 39초',
 '00시 13분 40초',
 '00시 13분 41초',
 '00시 13분 42초',
 '00시 13분 43초',
 '00시 13분 44초',
 '00시 13분 45초',
 '00시 13분 46초',
 '00시 13분 47초',
 '00시 13분 48초',
 '00시 13분 49초',
 '00시 13분 50초',
 '00시 13분 51초',
 '00시 13분 52초',
 '00시 13분 53초',
 '00시 13분 54초',
 '00시 13분 55초',
 '00시 13분 56초',
 '00시 13분 57초',
 '00시 13분 58초',
 '00시 13분 59초',
 '00시 14분 00초',
 '00시 14분 01초',
 '00시 14분 02초',
 '00시 14분 03초',
 '00시 14분 04초',
 '00시 14분 05초',
 '00시 14분 06초',
 '00시 14분 07초',
 '00시 14분 08초',
 '00시 14분 09초',
 '00시 14분 10초',
 '00시 14분 11초',
 '00시 14분 12초',
 '00시 14분 13초',
 '00시 14분 14초',
 '00시 14분 15초',
 '00시 14분 16초',
 '00시 14분 17초',
 '00시 14분 18초',
 '00시 14분 19초',
 '00시 14분 20초',
 '00시 14분 21초',
 '00시 14분 22초',
 '00시 14분 23초',
 '00시 14분 24초',
 '00시 14분 25초',
 '00시 14분 26초',
 '00시 14분 27초',
 '00시 14분 28초',
 '00시 14분 29초',
 '00시 14분 30초',
 '00시 14분 31초',
 '00시 14분 32초',
 '00시 14분 33초',
 '00시 14분 34초',
 '00시 14분 35초',
 '00시 14분 36초',
 '00시 14분 37초',
 '00시 14분 38초',
 '00시 14분 39초',
 '00시 14분 40초',
 '00시 14분 41초',
 '00시 14분 42초',
 '00시 14분 43초',
 '00시 14분 44초',
 '00시 14분 45초',
 '00시 14분 46초',
 '00시 14분 47초',
 '00시 14분 48초',
 '00시 14분 49초',
 '00시 14분 50초',
 '00시 14분 51초',
 '00시 14분 52초',
 '00시 14분 53초',
 '00시 14분 54초',
 '00시 14분 55초',
 '00시 14분 56초',
 '00시 14분 57초',
 '00시 14분 58초',
 '00시 14분 59초',
 '00시 15분 00초',
 '00시 15분 01초',
 '00시 15분 02초',
 '00시 15분 03초',
 '00시 15분 04초',
 '00시 15분 05초',
 '00시 15분 06초',
 '00시 15분 07초',
 '00시 15분 08초',
 '00시 15분 09초',
 '00시 15분 10초',
 '00시 15분 11초',
 '00시 15분 12초',
 '00시 15분 13초',
 '00시 15분 14초',
 '00시 15분 15초',
 '00시 15분 16초',
 '00시 15분 17초',
 '00시 15분 18초',
 '00시 15분 19초',
 '00시 15분 20초',
 '00시 15분 21초',
 '00시 15분 22초',
 '00시 15분 23초',
 '00시 15분 24초',
 '00시 15분 25초',
 '00시 15분 26초',
 '00시 15분 27초',
 '00시 15분 28초',
 '00시 15분 29초',
 '00시 15분 30초',
 '00시 15분 31초',
 '00시 15분 32초',
 '00시 15분 33초',
 '00시 15분 34초',
 '00시 15분 35초',
 '00시 15분 36초',
 '00시 15분 37초',
 '00시 15분 38초',
 '00시 15분 39초',
 '00시 15분 40초',
 '00시 15분 41초',
 '00시 15분 42초',
 '00시 15분 43초',
 '00시 15분 44초',
 '00시 15분 45초',
 '00시 15분 46초',
 '00시 15분 47초',
 '00시 15분 48초',
 '00시 15분 49초',
 '00시 15분 50초',
 '00시 15분 51초',
 '00시 15분 52초',
 '00시 15분 53초',
 '00시 15분 54초',
 '00시 15분 55초',
 '00시 15분 56초',
 '00시 15분 57초',
 '00시 15분 58초',
 '00시 15분 59초',
 '00시 16분 00초',
 '00시 16분 01초',
 '00시 16분 02초',
 '00시 16분 03초',
 '00시 16분 04초',
 '00시 16분 05초',
 '00시 16분 06초',
 '00시 16분 07초',
 '00시 16분 08초',
 '00시 16분 09초',
 '00시 16분 10초',
 '00시 16분 11초',
 '00시 16분 12초',
 '00시 16분 13초',
 '00시 16분 14초',
 '00시 16분 15초',
 '00시 16분 16초',
 '00시 16분 17초',
 '00시 16분 18초',
 '00시 16분 19초',
 '00시 16분 20초',
 '00시 16분 21초',
 '00시 16분 22초',
 '00시 16분 23초',
 '00시 16분 24초',
 '00시 16분 25초',
 '00시 16분 26초',
 '00시 16분 27초',
 '00시 16분 28초',
 '00시 16분 29초',
 '00시 16분 30초',
 '00시 16분 31초',
 '00시 16분 32초',
 '00시 16분 33초',
 '00시 16분 34초',
 '00시 16분 35초',
 '00시 16분 36초',
 '00시 16분 37초',
 '00시 16분 38초',
 '00시 16분 39초',
 ...]

# 파일 읽기 쓰기 open(), with open()
## 1)파일에 문자열을 쓰거나 읽을 때는 open 함수 사용
* 파일저장
변수명=open("파일이름", 모드(w:쓰기, r:읽기)<br>
변수명.write("저장할 내용")<br>
변수명.close()<br>
close()를 안하면 계속 열려있음

In [14]:
file=open("test.txt", "w")
file.write("파일 만들기 연습")
file.close()

* 파일열기
변수1 = open("파일이름",파일모드(r))<br>
변수2 = 변수1.read()<br>
변수1.close()

In [15]:
file1=open("test.txt","r")
my_file=file1.read()
file1.close()
print(my_file)

파일 만들기 연습

## with open
* with open은 close()를 하지 않아도 자동으로 close()처리를 해 줌

In [16]:
with open("test2.txt",'w') as file3:
    file3.write("with open을 사용하면 파일을 자동으로 닫아주어 편리하다.")

In [17]:
with open("test2.txt",'r') as file4:
    data=file4.read()
print(data)

with open을 사용하면 파일을 자동으로 닫아주어 편리하다.

# encoding에 따른 읽기 오류
* 운영체제나(windows, linux, macOS), 한글/영어 윈도우에 따라서 인코딩 되는 포멧이 달라짐
* 인코딩에 따른 오류가 발생 가능
* web표준은 utf-8이므로 인코딩은 utf-8로 하는 것이 좋다.
* windows의 경우 인코딩이 cp949이므로 주의

In [21]:
with open("test_utf-8.txt",'w',encoding='utf-8') as file5:
    file5.write("이것은 with open으로 만든 utf-8입니다.")

In [22]:
with open('test_utf-8.txt','r', encoding='utf-8') as file6:
    file6_data=file6.read()
print(file6_data)

이것은 with open으로 만든 utf-8입니다.

# json 파일 읽어와서 내용 정리하기

In [24]:
with open("./data/서울특별시_관광지입장정보_2011_2016.json", 'r',encoding="utf-8") as file7:
    trip_info=file7.read()
trip_info

'[\n    {\n        "ForNum": 44722,\n        "NatNum": 75991,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 11017,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "운현궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 132399,\n        "NatNum": 237330,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 3133,\n        "NatNum": 21267,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 18226,\n        "NatNum": 24223,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 233828,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 93554,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "서울역사박물관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 13935,\n        "NatNum": 52140,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 61115,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "서울시립미술관 본관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 10,\n        "NatNum": 1885,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 32412,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 19308,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 5214,\n        "NatNum": 6956,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 13,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 333,\n        "NatNum": 1823,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 14,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 4704,\n        "NatNum": 16634,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 15,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 52484,\n        "NatNum": 642290,\n        "addrCd": 1171,\n        "gungu": "송파구",\n        "resNm": "롯데월드",\n        "rnum": 16,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 27814,\n        "NatNum": 28061,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 546,\n        "NatNum": 5978,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "운현궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 105370,\n        "NatNum": 133012,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 1451,\n        "NatNum": 15722,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 8817,\n        "NatNum": 8068,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 13033,\n        "NatNum": 227077,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 1138,\n        "NatNum": 78179,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "서울역사박물관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 11151,\n        "NatNum": 44855,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 213467,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "서울시립미술관 본관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 15,\n        "NatNum": 1252,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 6625,\n        "NatNum": 14090,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 18881,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 24492,\n        "NatNum": 9167,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 13,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 62,\n        "NatNum": 860,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 14,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 66868,\n        "NatNum": 670056,\n        "addrCd": 1171,\n        "gungu": "송파구",\n        "resNm": "롯데월드",\n        "rnum": 15,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 25550,\n        "NatNum": 38553,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 101942,\n        "NatNum": 145544,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 1986,\n        "NatNum": 20035,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 6048,\n        "NatNum": 13896,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 9083,\n        "NatNum": 286992,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 13282,\n        "NatNum": 99301,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 6,\n        "NatNum": 706,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 6732,\n        "NatNum": 14607,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 23245,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 43129,\n        "NatNum": 11886,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 16,\n        "NatNum": 1248,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 1445,\n        "NatNum": 11890,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 29928,\n        "NatNum": 41561,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 129946,\n        "NatNum": 190501,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 1693,\n        "NatNum": 19473,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 3891,\n        "NatNum": 5951,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 7195,\n        "NatNum": 258781,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 14723,\n        "NatNum": 44272,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 12,\n        "NatNum": 486,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 6263,\n        "NatNum": 27205,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 24527,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 42443,\n        "NatNum": 7478,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 5,\n        "NatNum": 1036,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 823,\n        "NatNum": 8869,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 33342,\n        "NatNum": 59738,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 170379,\n        "NatNum": 148961,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 1783,\n        "NatNum": 27172,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 3406,\n        "NatNum": 14936,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 13127,\n        "NatNum": 281457,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 15197,\n        "NatNum": 68749,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 16,\n        "NatNum": 2221,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 5588,\n        "NatNum": 44232,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 22587,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 29520,\n        "NatNum": 8822,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 3,\n        "NatNum": 1647,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 492,\n        "NatNum": 14454,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    }\n]'

In [25]:
print(type(trip_info))

<class 'str'>

In [26]:
import json

In [27]:
data=json.loads(trip_info)

In [28]:
len(data)

67

In [30]:
for item in data[0]:
    print(item)

ForNum
NatNum
addrCd
gungu
resNm
rnum
sido
yyyymm

In [31]:
for item in data[0].items():
    print(item)

('ForNum', 44722)
('NatNum', 75991)
('addrCd', 1111)
('gungu', '종로구')
('resNm', '창덕궁')
('rnum', 1)
('sido', '서울특별시')
('yyyymm', '201112')

In [32]:
for item in data[:2]:
    for key in item:
        print(key)

ForNum
NatNum
addrCd
gungu
resNm
rnum
sido
yyyymm
ForNum
NatNum
addrCd
gungu
resNm
rnum
sido
yyyymm

In [34]:
for item in data[:2]:
    for key in item:
        print(item[key])

44722
75991
1111
종로구
창덕궁
1
서울특별시
201112
0
11017
1111
종로구
운현궁
2
서울특별시
201112

In [ ]:
* value를 리스트로 만든 후 dict함수로 딕셔너리 만들어 데이터프레임 만들기

In [41]:
year_mon=[]
sido=[]
place=[]
foriners=[]
total=[]

for item in data[:2]:
    foriners.append(item['ForNum'])
    total.append(item['NatNum'])
    place.append(item['resNm'])
    sido.append(item['sido'])
    year_mon.append(item['yyyymm'])
    
tour_info = dict(년월=year_mon, 시도=sido, 장소=place, 외국인=foriners, 전체방문객수= total)
tour_info

{'년월': ['201112', '201112'],
 '시도': ['서울특별시', '서울특별시'],
 '장소': ['창덕궁', '운현궁'],
 '외국인': [44722, 0],
 '전체방문객수': [75991, 11017]}

In [42]:
import pandas as pd

In [43]:
df=pd.DataFrame(tour_info)
df

       년월     시도   장소    외국인  전체방문객수
0  201112  서울특별시  창덕궁  44722   75991
1  201112  서울특별시  운현궁      0   11017

* 딕셔너리로 바로 만들어서 데이터프레임으로 변환

In [51]:
for key in data[0]:
    value_list=[]
    for item in data:
        value_list.append(item[key])
    print(key, value_list)

[44722, 0, 132399, 3133, 18226, 0, 0, 13935, 0, 10, 0, 0, 5214, 333, 4704, 52484, 27814, 546, 105370, 1451, 8817, 13033, 1138, 11151, 0, 15, 6625, 0, 24492, 62, 66868, 25550, 101942, 1986, 6048, 9083, 13282, 6, 6732, 0, 43129, 16, 1445, 29928, 129946, 1693, 3891, 7195, 14723, 12, 6263, 0, 42443, 5, 823, 33342, 170379, 1783, 3406, 13127, 15197, 16, 5588, 0, 29520, 3, 492]
[75991, 11017, 237330, 21267, 24223, 233828, 93554, 52140, 61115, 1885, 32412, 19308, 6956, 1823, 16634, 642290, 28061, 5978, 133012, 15722, 8068, 227077, 78179, 44855, 213467, 1252, 14090, 18881, 9167, 860, 670056, 38553, 145544, 20035, 13896, 286992, 99301, 706, 14607, 23245, 11886, 1248, 11890, 41561, 190501, 19473, 5951, 258781, 44272, 486, 27205, 24527, 7478, 1036, 8869, 59738, 148961, 27172, 14936, 281457, 68749, 2221, 44232, 22587, 8822, 1647, 14454]
[1111, 1111, 1111, 1111, 1111, 1117, 1111, 1114, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1171, 1111, 1111, 1111, 1111, 1111, 1117, 1111, 1114, 1114, 1135, 1141, 1141, 1144, 1165, 1171, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168]
['종로구', '종로구', '종로구', '종로구', '종로구', '용산구', '종로구', '중구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '송파구', '종로구', '종로구', '종로구', '종로구', '종로구', '용산구', '종로구', '중구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '송파구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구']
['창덕궁', '운현궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '서울역사박물관', '덕수궁', '서울시립미술관 본관', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '롯데월드', '창덕궁', '운현궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '서울역사박물관', '덕수궁', '서울시립미술관 본관', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '롯데월드', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉']
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
['서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시']
['201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512']

In [57]:
for item in data:
    print(item)

{'ForNum': 44722, 'NatNum': 75991, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창덕궁', 'rnum': 1, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 0, 'NatNum': 11017, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '운현궁', 'rnum': 2, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 132399, 'NatNum': 237330, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '경복궁', 'rnum': 3, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 3133, 'NatNum': 21267, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창경궁', 'rnum': 4, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 18226, 'NatNum': 24223, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '종묘', 'rnum': 5, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 0, 'NatNum': 233828, 'addrCd': 1117, 'gungu': '용산구', 'resNm': '국립중앙박물관', 'rnum': 6, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 0, 'NatNum': 93554, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '서울역사박물관', 'rnum': 7, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 13935, 'NatNum': 52140, 'addrCd': 1114, 'gungu': '중구', 'resNm': '덕수궁', 'rnum': 8, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 0, 'NatNum': 61115, 'addrCd': 1114, 'gungu': '중구', 'resNm': '서울시립미술관 본관', 'rnum': 9, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 10, 'NatNum': 1885, 'addrCd': 1135, 'gungu': '노원구', 'resNm': '태릉 ·  강릉 · 조선왕릉전시관', 'rnum': 10, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 0, 'NatNum': 32412, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문형무소역사관', 'rnum': 11, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 0, 'NatNum': 19308, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문자연사박물관', 'rnum': 12, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 5214, 'NatNum': 6956, 'addrCd': 1144, 'gungu': '마포구', 'resNm': '트릭아이미술관', 'rnum': 13, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 333, 'NatNum': 1823, 'addrCd': 1165, 'gungu': '서초구', 'resNm': '헌릉ㆍ인릉', 'rnum': 14, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 4704, 'NatNum': 16634, 'addrCd': 1168, 'gungu': '강남구', 'resNm': '선릉·정릉', 'rnum': 15, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 52484, 'NatNum': 642290, 'addrCd': 1171, 'gungu': '송파구', 'resNm': '롯데월드', 'rnum': 16, 'sido': '서울특별시', 'yyyymm': '201112'}
{'ForNum': 27814, 'NatNum': 28061, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창덕궁', 'rnum': 1, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 546, 'NatNum': 5978, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '운현궁', 'rnum': 2, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 105370, 'NatNum': 133012, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '경복궁', 'rnum': 3, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 1451, 'NatNum': 15722, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창경궁', 'rnum': 4, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 8817, 'NatNum': 8068, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '종묘', 'rnum': 5, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 13033, 'NatNum': 227077, 'addrCd': 1117, 'gungu': '용산구', 'resNm': '국립중앙박물관', 'rnum': 6, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 1138, 'NatNum': 78179, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '서울역사박물관', 'rnum': 7, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 11151, 'NatNum': 44855, 'addrCd': 1114, 'gungu': '중구', 'resNm': '덕수궁', 'rnum': 8, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 0, 'NatNum': 213467, 'addrCd': 1114, 'gungu': '중구', 'resNm': '서울시립미술관 본관', 'rnum': 9, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 15, 'NatNum': 1252, 'addrCd': 1135, 'gungu': '노원구', 'resNm': '태릉 ·  강릉 · 조선왕릉전시관', 'rnum': 10, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 6625, 'NatNum': 14090, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문형무소역사관', 'rnum': 11, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 0, 'NatNum': 18881, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문자연사박물관', 'rnum': 12, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 24492, 'NatNum': 9167, 'addrCd': 1144, 'gungu': '마포구', 'resNm': '트릭아이미술관', 'rnum': 13, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 62, 'NatNum': 860, 'addrCd': 1165, 'gungu': '서초구', 'resNm': '헌릉ㆍ인릉', 'rnum': 14, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 66868, 'NatNum': 670056, 'addrCd': 1171, 'gungu': '송파구', 'resNm': '롯데월드', 'rnum': 15, 'sido': '서울특별시', 'yyyymm': '201212'}
{'ForNum': 25550, 'NatNum': 38553, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창덕궁', 'rnum': 1, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 101942, 'NatNum': 145544, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '경복궁', 'rnum': 2, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 1986, 'NatNum': 20035, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창경궁', 'rnum': 3, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 6048, 'NatNum': 13896, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '종묘', 'rnum': 4, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 9083, 'NatNum': 286992, 'addrCd': 1117, 'gungu': '용산구', 'resNm': '국립중앙박물관', 'rnum': 5, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 13282, 'NatNum': 99301, 'addrCd': 1114, 'gungu': '중구', 'resNm': '덕수궁', 'rnum': 6, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 6, 'NatNum': 706, 'addrCd': 1135, 'gungu': '노원구', 'resNm': '태릉 ·  강릉 · 조선왕릉전시관', 'rnum': 7, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 6732, 'NatNum': 14607, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문형무소역사관', 'rnum': 8, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 0, 'NatNum': 23245, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문자연사박물관', 'rnum': 9, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 43129, 'NatNum': 11886, 'addrCd': 1144, 'gungu': '마포구', 'resNm': '트릭아이미술관', 'rnum': 10, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 16, 'NatNum': 1248, 'addrCd': 1165, 'gungu': '서초구', 'resNm': '헌릉ㆍ인릉', 'rnum': 11, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 1445, 'NatNum': 11890, 'addrCd': 1168, 'gungu': '강남구', 'resNm': '선릉·정릉', 'rnum': 12, 'sido': '서울특별시', 'yyyymm': '201312'}
{'ForNum': 29928, 'NatNum': 41561, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창덕궁', 'rnum': 1, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 129946, 'NatNum': 190501, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '경복궁', 'rnum': 2, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 1693, 'NatNum': 19473, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창경궁', 'rnum': 3, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 3891, 'NatNum': 5951, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '종묘', 'rnum': 4, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 7195, 'NatNum': 258781, 'addrCd': 1117, 'gungu': '용산구', 'resNm': '국립중앙박물관', 'rnum': 5, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 14723, 'NatNum': 44272, 'addrCd': 1114, 'gungu': '중구', 'resNm': '덕수궁', 'rnum': 6, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 12, 'NatNum': 486, 'addrCd': 1135, 'gungu': '노원구', 'resNm': '태릉 ·  강릉 · 조선왕릉전시관', 'rnum': 7, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 6263, 'NatNum': 27205, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문형무소역사관', 'rnum': 8, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 0, 'NatNum': 24527, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문자연사박물관', 'rnum': 9, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 42443, 'NatNum': 7478, 'addrCd': 1144, 'gungu': '마포구', 'resNm': '트릭아이미술관', 'rnum': 10, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 5, 'NatNum': 1036, 'addrCd': 1165, 'gungu': '서초구', 'resNm': '헌릉ㆍ인릉', 'rnum': 11, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 823, 'NatNum': 8869, 'addrCd': 1168, 'gungu': '강남구', 'resNm': '선릉·정릉', 'rnum': 12, 'sido': '서울특별시', 'yyyymm': '201412'}
{'ForNum': 33342, 'NatNum': 59738, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창덕궁', 'rnum': 1, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 170379, 'NatNum': 148961, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '경복궁', 'rnum': 2, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 1783, 'NatNum': 27172, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '창경궁', 'rnum': 3, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 3406, 'NatNum': 14936, 'addrCd': 1111, 'gungu': '종로구', 'resNm': '종묘', 'rnum': 4, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 13127, 'NatNum': 281457, 'addrCd': 1117, 'gungu': '용산구', 'resNm': '국립중앙박물관', 'rnum': 5, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 15197, 'NatNum': 68749, 'addrCd': 1114, 'gungu': '중구', 'resNm': '덕수궁', 'rnum': 6, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 16, 'NatNum': 2221, 'addrCd': 1135, 'gungu': '노원구', 'resNm': '태릉 ·  강릉 · 조선왕릉전시관', 'rnum': 7, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 5588, 'NatNum': 44232, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문형무소역사관', 'rnum': 8, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 0, 'NatNum': 22587, 'addrCd': 1141, 'gungu': '서대문구', 'resNm': '서대문자연사박물관', 'rnum': 9, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 29520, 'NatNum': 8822, 'addrCd': 1144, 'gungu': '마포구', 'resNm': '트릭아이미술관', 'rnum': 10, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 3, 'NatNum': 1647, 'addrCd': 1165, 'gungu': '서초구', 'resNm': '헌릉ㆍ인릉', 'rnum': 11, 'sido': '서울특별시', 'yyyymm': '201512'}
{'ForNum': 492, 'NatNum': 14454, 'addrCd': 1168, 'gungu': '강남구', 'resNm': '선릉·정릉', 'rnum': 12, 'sido': '서울특별시', 'yyyymm': '201512'}

In [55]:
d={}
d['장소']='경복궁'
d

{'장소': '경복궁'}

In [61]:
value_list_df = pd.DataFrame(value_list)
value_list_df

         0
0   201112
1   201112
2   201112
3   201112
4   201112
..     ...
62  201512
63  201512
64  201512
65  201512
66  201512

[67 rows x 1 columns]

* setdefault 함수를 이용해 만들기

In [63]:
dic_result={}
for dicts in data:
    for key, value in dicts.items():
    dic_result.setdefault(key, [].append(value))
dic_result

IndentationError: expected an indented block (532288883.py, line 4)

In [ ]:
d2={}
d2.setdefault("key", 3)
d2