국민은행 앱 사용자 리뷰 데이터 JSON 파일을 읽어와서 csv파일로 변환하기

In [1]:
import json
import pandas as pd

In [3]:
with open("./data/com_kbstar_kbbank.json", 'r', encoding='utf-8')as file:
    data=file.read()

'[\n    {\n        "사용자": "박성진 (홀리진)",\n        "별점": "4",\n        "리뷰": "리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.",\n        "날짜": "2025년 3월 2일",\n        "개발자 응답": "고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다."\n    },\n    {\n        "사용자": "윤태경",\n        "별점": "5",\n        "리뷰": "KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.",\n        "날짜": "2025년 1월 20일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"\n    },\n    {\n        "사용자": "tae tae",\n        "별점": "1",\n        "리뷰": "타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.",\n        "날짜": "2025년 1월 14일",\n        "개발자 응답": "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다."\n    },\n    {\n        "사용자": "정다우니",\n        "별점": "5",\n        "리뷰": "설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.",\n        "날짜": "2025년 1월 25일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"\n    },\n    {\n        "사용자": "우간능",\n        "별점": "1",\n        "리뷰": "왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오",\n        "날짜": "2025년 2월 1일",\n        "개발자 응답": "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 \'KB스타뱅킹 앱리뷰\' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다."\n    },\n    {\n        "사용자": "꾸꾸잉꾸",\n        "별점": "1",\n        "리뷰": "2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...",\n        "날짜": "2025년 2월 17일",\n        "개발자 응답": "고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다."\n    },\n    {\n        "사용자": "이이민우",\n        "별점": "3",\n        "리뷰": "전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!",\n        "날짜": "2025년 3월 3일",\n        "개발자 응답": null\n    },\n    {\n        "사용자": "김수진",\n        "별점": "3",\n        "리뷰": "갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ",\n        "날짜": "2025년 1월 24일",\n        "개발자 응답": "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다."\n    },\n    {\n        "사용자": "김영옥",\n        "별점": "5",\n        "리뷰": "거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~",\n        "날짜": "2025년 2월 11일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 \'KB스타뱅킹 앱리뷰\' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"\n    },\n    {\n        "사용자": "이욱",\n        "별점": "5",\n        "리뷰": "앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..",\n        "날짜": "2025년 3월 3일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 \'KB스타뱅킹 앱리뷰\' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"\n    },\n    {\n        "사용자": "김두영",\n        "별점": "1",\n        "리뷰": "리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요",\n        "날짜": "2025년 2월 24일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다."\n    },\n    {\n        "사용자": "훈",\n        "별점": "1",\n        "리뷰": "진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄",\n        "날짜": "2025년 2월 24일",\n        "개발자 응답": "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 \'오류해제\'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 \'계좌비밀번호 변경\' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 \'기존 비밀번호 입력\' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 \'신분증 촬영\' 진행이 필요합니다. 감사합니다."\n    },\n    {\n        "사용자": "위윌왁휴",\n        "별점": "1",\n        "리뷰": "빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.",\n        "날짜": "2025년 3월 8일",\n        "개발자 응답": null\n    },\n    {\n        "사용자": "김숏",\n        "별점": "1",\n        "리뷰": "진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?",\n        "날짜": "2025년 3월 12일",\n        "개발자 응답": "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 \'없음\'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다."\n    },\n    {\n        "사용자": "Sean Moon",\n        "별점": "5",\n        "리뷰": "UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)",\n        "날짜": "2025년 3월 1일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 \'KB스타뱅킹 앱리뷰\' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"\n    },\n    {\n        "사용자": "sprirea KTH",\n        "별점": "1",\n        "리뷰": "나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.",\n        "날짜": "2025년 2월 25일",\n        "개발자 응답": null\n    },\n    {\n        "사용자": "깔린느",\n        "별점": "5",\n        "리뷰": "이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^",\n        "날짜": "2024년 12월 23일",\n        "개발자 응답": "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 \'자동 로그인 해제하는 방법\'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 \'앱 열때마다 로그인\'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!"\n    },\n    {\n        "사용자": "김유리",\n        "별점": "5",\n        "리뷰": "안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.",\n        "날짜": "2024년 12월 18일",\n        "개발자 응답": "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다."\n    },\n    {\n        "사용자": "박성진 (홀리진)",\n        "별점": "4",\n        "리뷰": "리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.",\n        "날짜": "2025년 3월 2일",\n        "개발자 응답": "고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다."\n    },\n    {\n        "사용자": "윤태경",\n        "별점": "5",\n        "리뷰": "KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.",\n        "날짜": "2025년 1월 20일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"\n    },\n    {\n        "사용자": "tae tae",\n        "별점": "1",\n        "리뷰": "타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.",\n        "날짜": "2025년 1월 14일",\n        "개발자 응답": "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다."\n    },\n    {\n        "사용자": "정다우니",\n        "별점": "5",\n        "리뷰": "설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.",\n        "날짜": "2025년 1월 25일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"\n    },\n    {\n        "사용자": "우간능",\n        "별점": "1",\n        "리뷰": "왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오",\n        "날짜": "2025년 2월 1일",\n        "개발자 응답": "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 \'KB스타뱅킹 앱리뷰\' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다."\n    },\n    {\n        "사용자": "꾸꾸잉꾸",\n        "별점": "1",\n        "리뷰": "2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...",\n        "날짜": "2025년 2월 17일",\n        "개발자 응답": "고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다."\n    },\n    {\n        "사용자": "이이민우",\n        "별점": "3",\n        "리뷰": "전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!",\n        "날짜": "2025년 3월 3일",\n        "개발자 응답": null\n    },\n    {\n        "사용자": "김수진",\n        "별점": "3",\n        "리뷰": "갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ",\n        "날짜": "2025년 1월 24일",\n        "개발자 응답": "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다."\n    },\n    {\n        "사용자": "김영옥",\n        "별점": "5",\n        "리뷰": "거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~",\n        "날짜": "2025년 2월 11일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 \'KB스타뱅킹 앱리뷰\' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"\n    },\n    {\n        "사용자": "이욱",\n        "별점": "5",\n        "리뷰": "앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..",\n        "날짜": "2025년 3월 3일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 \'KB스타뱅킹 앱리뷰\' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"\n    },\n    {\n        "사용자": "김두영",\n        "별점": "1",\n        "리뷰": "리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요",\n        "날짜": "2025년 2월 24일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다."\n    },\n    {\n        "사용자": "훈",\n        "별점": "1",\n        "리뷰": "진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄",\n        "날짜": "2025년 2월 24일",\n        "개발자 응답": "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 \'오류해제\'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 \'계좌비밀번호 변경\' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 \'기존 비밀번호 입력\' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 \'신분증 촬영\' 진행이 필요합니다. 감사합니다."\n    },\n    {\n        "사용자": "위윌왁휴",\n        "별점": "1",\n        "리뷰": "빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.",\n        "날짜": "2025년 3월 8일",\n        "개발자 응답": null\n    },\n    {\n        "사용자": "김숏",\n        "별점": "1",\n        "리뷰": "진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?",\n        "날짜": "2025년 3월 12일",\n        "개발자 응답": "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 \'없음\'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다."\n    },\n    {\n        "사용자": "Sean Moon",\n        "별점": "5",\n        "리뷰": "UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)",\n        "날짜": "2025년 3월 1일",\n        "개발자 응답": "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 \'KB스타뱅킹 앱리뷰\' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"\n    },\n    {\n        "사용자": "sprirea KTH",\n        "별점": "1",\n        "리뷰": "나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.",\n        "날짜": "2025년 2월 25일",\n        "개발자 응답": null\n    },\n    {\n        "사용자": "깔린느",\n        "별점": "5",\n        "리뷰": "이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^",\n        "날짜": "2024년 12월 23일",\n        "개발자 응답": "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 \'자동 로그인 해제하는 방법\'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 \'앱 열때마다 로그인\'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!"\n    },\n    {\n        "사용자": "김유리",\n        "별점": "5",\n        "리뷰": "안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.",\n        "날짜": "2024년 12월 18일",\n        "개발자 응답": "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 \'KB스타뱅킹 앱리뷰\' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다."\n    },\n    {\n        "사용자": "박성진 (홀리진)",\n        "별점": "4",\n        "리뷰": "리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.",\n        "날짜": "2025년 3월 2일",\n        "개발자 응답": "고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다."\n    },\n    {\n        "사용자": "윤태경",\n        "별점": "5",\n        "리뷰": "KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 

In [4]:
data[:100]

'[\n    {\n        "사용자": "박성진 (홀리진)",\n        "별점": "4",\n        "리뷰": "리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면'

In [5]:
reviews=json.loads(data)
len(reviews)

2223

In [6]:
reviews[0]

{'사용자': '박성진 (홀리진)',
 '별점': '4',
 '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
 '날짜': '2025년 3월 2일',
 '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}

{'사용자': ['박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', 'KTS Pastor', '조하진', 'J H', '김영진', 'Anne Sim', '유순', 'EunCheol Kweon', '송기복', '이영아', 'Yongbeom Moon', '이영주', '빛과소금', '김하늘', '밝고긍정적인거', '정현우', '임겸', 'Changwan “-” Yu'], '별점': ['4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1

In [10]:
result={}
for dicts in reviews:
    for key, value in dicts.items():
        result.setdefault(key,[]).append(value)
print(result)

{'사용자': ['박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', 'KTS Pastor', '조하진', 'J H', '김영진', 'Anne Sim', '유순', 'EunCheol Kweon', '송기복', '이영아', 'Yongbeom Moon', '이영주', '빛과소금', '김하늘', '밝고긍정적인거', '정현우', '임겸', 'Changwan “-” Yu'], '별점': ['4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1

In [11]:
import pandas as pd

In [12]:
df=pd.DataFrame(result)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

In [13]:
reviews

[{'사용자': '박성진 (홀리진)',
  '별점': '4',
  '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  '날짜': '2025년 3월 2일',
  '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'},
 {'사용자': '윤태경',
  '별점': '5',
  '리뷰': 'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '날짜': '2025년 1월 20일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"},
 {'사용자': 'tae tae',
  '별점': '1',
  '리뷰': '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '날짜': '2025년 1월 14일',
  '개발자 응답': '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.'},
 {'사용자': '정다우니',
  '별점': '5',
  '리뷰': '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '날짜': '2025년 1월 25일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"},
 {'사용자': '우간능',
  '별점': '1',
  '리뷰': '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '날짜': '2025년 2월 1일',
  '개발자 응답': "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다."},
 {'사용자': '꾸꾸잉꾸',
  '별점': '1',
  '리뷰': '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...',
  '날짜': '2025년 2월 17일',
  '개발자 응답': '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.'},
 {'사용자': '이이민우',
  '별점': '3',
  '리뷰': '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
  '날짜': '2025년 3월 3일',
  '개발자 응답': None},
 {'사용자': '김수진',
  '별점': '3',
  '리뷰': '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ',
  '날짜': '2025년 1월 24일',
  '개발자 응답': '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.'},
 {'사용자': '김영옥',
  '별점': '5',
  '리뷰': '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~',
  '날짜': '2025년 2월 11일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"},
 {'사용자': '이욱',
  '별점': '5',
  '리뷰': '앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..',
  '날짜': '2025년 3월 3일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"},
 {'사용자': '김두영',
  '별점': '1',
  '리뷰': '리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요',
  '날짜': '2025년 2월 24일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다."},
 {'사용자': '훈',
  '별점': '1',
  '리뷰': '진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄',
  '날짜': '2025년 2월 24일',
  '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다."},
 {'사용자': '위윌왁휴',
  '별점': '1',
  '리뷰': '빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.',
  '날짜': '2025년 3월 8일',
  '개발자 응답': None},
 {'사용자': '김숏',
  '별점': '1',
  '리뷰': '진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?',
  '날짜': '2025년 3월 12일',
  '개발자 응답': "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다."},
 {'사용자': 'Sean Moon',
  '별점': '5',
  '리뷰': 'UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)',
  '날짜': '2025년 3월 1일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"},
 {'사용자': 'sprirea KTH',
  '별점': '1',
  '리뷰': '나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.',
  '날짜': '2025년 2월 25일',
  '개발자 응답': None},
 {'사용자': '깔린느',
  '별점': '5',
  '리뷰': '이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^',
  '날짜': '2024년 12월 23일',
  '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!"},
 {'사용자': '김유리',
  '별점': '5',
  '리뷰': '안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.',
  '날짜': '2024년 12월 18일',
  '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다."},
 {'사용자': '박성진 (홀리진)',
  '별점': '4',
  '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  '날짜': '2025년 3월 2일',
  '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'},
 {'사용자': '윤태경',
  '별점': '5',
  '리뷰': 'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '날짜': '2025년 1월 20일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"},
 {'사용자': 'tae tae',
  '별점': '1',
  '리뷰': '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '날짜': '2025년 1월 14일',
  '개발자 응답': '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.'},
 {'사용자': '정다우니',
  '별점': '5',
  '리뷰': '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '날짜': '2025년 1월 25일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"},
 {'사용자': '우간능',
  '별점': '1',
  '리뷰': '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '날짜': '2025년 2월 1일',
  '개발자 응답': "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다."},
 {'사용자': '꾸꾸잉꾸',
  '별점': '1',
  '리뷰': '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...',
  '날짜': '2025년 2월 17일',
  '개발자 응답': '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.'},
 {'사용자': '이이민우',
  '별점': '3',
  '리뷰': '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
  '날짜': '2025년 3월 3일',
  '개발자 응답': None},
 {'사용자': '김수진',
  '별점': '3',
  '리뷰': '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ',
  '날짜': '2025년 1월 24일',
  '개발자 응답': '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.'},
 {'사용자': '김영옥',
  '별점': '5',
  '리뷰': '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~',
  '날짜': '2025년 2월 11일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"},
 {'사용자': '이욱',
  '별점': '5',
  '리뷰': '앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..',
  '날짜': '2025년 3월 3일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"},
 {'사용자': '김두영',
  '별점': '1',
  '리뷰': '리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요',
  '날짜': '2025년 2월 24일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다."},
 {'사용자': '훈',
  '별점': '1',
  '리뷰': '진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄',
  '날짜': '2025년 2월 24일',
  '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다."},
 {'사용자': '위윌왁휴',
  '별점': '1',
  '리뷰': '빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.',
  '날짜': '2025년 3월 8일',
  '개발자 응답': None},
 {'사용자': '김숏',
  '별점': '1',
  '리뷰': '진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?',
  '날짜': '2025년 3월 12일',
  '개발자 응답': "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다."},
 {'사용자': 'Sean Moon',
  '별점': '5',
  '리뷰': 'UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)',
  '날짜': '2025년 3월 1일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"},
 {'사용자': 'sprirea KTH',
  '별점': '1',
  '리뷰': '나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.',
  '날짜': '2025년 2월 25일',
  '개발자 응답': None},
 {'사용자': '깔린느',
  '별점': '5',
  '리뷰': '이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^',
  '날짜': '2024년 12월 23일',
  '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!"},
 {'사용자': '김유리',
  '별점': '5',
  '리뷰': '안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.',
  '날짜': '2024년 12월 18일',
  '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다."},
 {'사용자': '박성진 (홀리진)',
  '별점': '4',
  '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  '날짜': '2025년 3월 2일',
  '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'},
 {'사용자': '윤태경',
  '별점': '5',
  '리뷰': 'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '날짜': '2025년 1월 20일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"},
 {'사용자': 'tae tae',
  '별점': '1',
  '리뷰': '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '날짜': '2025년 1월 14일',
  '개발자 응답': '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.'},
 {'사용자': '정다우니',
  '별점': '5',
  '리뷰': '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '날짜': '2025년 1월 25일',
  '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"},
 {'사용자': '우간능',
  '별점': '1',
  '리뷰': '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '날짜': '2025년 2월 1일',
  '개발자 응답': "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다."},
 {'사용자': '꾸꾸잉꾸',
  '별점': '1',

In [ ]:
for key in data[0]:
    value_list=[]
    for item in data:
        value_list.append(item[key])
    print(key, value_list)

In [20]:
for key in reviews[0]:
    value_list=[]
    for item in reviews:
        value_list.append(item[key])
    print(key, value_list)

사용자 ['박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', 'KTS Pastor', '조하진', 'J H', '김영진', 'Anne Sim', '유순', 'EunCheol Kweon', '송기복', '이영아', 'Yongbeom Moon', '이영주', '빛과소금', '김하늘', '밝고긍정적인거', '정현우', '임겸', 'Changwan “-” Yu']

별점은 숫자로 변환해서 넣기, 나머지는

In [31]:
result={}
for key in reviews[0]:
    temp=[]
    for review in reviews:
        if key=="별점":
            temp.append(int(review[key]))
        else:
            temp.append(review[key].replace("!","").replace(",","").replace(" ",""))
    result[key]=temp
print(result)

AttributeError: 'NoneType' object has no attribute 'replace'

In [ ]:
for review in reviews[:2]:
    for key, value in review.items():
        result2.setdefault(key,[]).append(value)

In [28]:
df=pd.DataFrame(result)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

# 2번째 과제

* data에는 리스트 요소가 37개 있음
* 리스트 요소 1개에는 1000개의 딕셔너리가 있고 그 안에 가게 정보가 있음
* 가게 정보는 data[0]['body']['items']에 있다.
* 가게 정보를 구성하는 key는 39개이다.

In [1]:
import json

In [2]:
with open("./data/전국치킨집리스트.json", 'r', encoding="utf-8") as file2:
    chick=file2.read()
data=json.loads(chick)

In [59]:
result={}
for page in data:
    for item in page['body']['items']:
        for key, value in zip(page['header']['columns'],item.values()):
            result.setdefault(key,[]).append(value)
result

df2=pd.DataFrame(result)
df2

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36059,9829515,아리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010200106740003008662,,경기도 동두천시 거북마루로 6,483020,11348,,1,,127.046713,37.895702
36060,9851302,애니치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4785031036104090002008916,,경상북도 칠곡군 지천면 신동로 147,718821,39864,,,,128.488717,35.956631
36061,9867543,에디슨치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1135010600103590001010681,중계5단지주공아파트,서울특별시 노원구 중계로 230,139781,01713,,1,,127.075031,37.651004
36062,9918905,오븐에꾸운닭장유점,장유점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4825031027103150002091993,재영프라자,경상남도 김해시 삼문로 26,621280,51004,,1,,128.803565,35.192491
36063,9967953,웰빙치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011100101360002016167,,강원도 원주시 상지대길 43,220954,26342,,1,,127.937290,37.369591

In [56]:
data[0]['header']['columns']

['상가업소번호',
 '상호명',
 '지점명',
 '상권업종대분류코드',
 '상권업종대분류명',
 '상권업종중분류코드',
 '상권업종중분류명',
 '상권업종소분류코드',
 '상권업종소분류명',
 '표준산업분류코드',
 '표준산업분류명',
 '시도코드',
 '시도명',
 '시군구코드',
 '시군구명',
 '행정동코드',
 '행정동명',
 '법정동코드',
 '법정동명',
 'PNU코드',
 '대지구분코드',
 '대지구분명',
 '지번본번지',
 '지번부번지',
 '지번주소',
 '도로명코드',
 '도로명',
 '건물본번지',
 '건물부번지',
 '건물관리번호',
 '건물명',
 '도로명주소',
 '구우편번호',
 '신우편번호',
 '동정보',
 '층정보',
 '호정보',
 '경도',
 '위도']

In [67]:
for i in data[:1]:
    print(i)

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보', 'columns': ['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드', '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드', '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', 'PNU코드', '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지', '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보', '호정보', '경도', '위도'], 'stdrYm': '202206', 'resultCode': '00', 'resultMsg': 'NORMAL SERVICE'}, 'body': {'items': [{'bizesId': '10027626', 'bizesNm': '장모님치킨가창점', 'brchNm': '가창점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '27', 'ctprvnNm': '대구광역시', 'signguCd': '27710', 'signguNm': '달성군', 'adongCd': '2771031000', 'adongNm': '가창면', 'ldongCd': '2771031024', 'ldongNm': '가창면', 'lnoCd': '2771031024101200001', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 120, 'lnoSlno': 1, 'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1', 'rdnmCd': '277103148001', 'rdnm': '대구광역시 달성군 가창면 가창동로', 'bldMnno': 6, 'bldSlno': '', 'bldMngNo': '2771031024101200004036858', 'bldNm': '', 'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6', 'oldZipcd': '711861', 'newZipcd': '42938', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 128.644458591419, 'lat': 35.7826625402814}, {'bizesId': '10098244', 'bizesNm': '짱구피자치킨', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '41', 'ctprvnNm': '경기도', 'signguCd': '41250', 'signguNm': '동두천시', 'adongCd': '4125056500', 'adongNm': '불현동', 'ldongCd': '4125010300', 'ldongNm': '생연동', 'lnoCd': '4125010300102680011', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 268, 'lnoSlno': 11, 'lnoAdr': '경기도 동두천시 생연동 268-11', 'rdnmCd': '412503189006', 'rdnm': '경기도 동두천시 못골로', 'bldMnno': 30, 'bldSlno': '', 'bldMngNo': '4125010300102680011008557', 'bldNm': '', 'rdnmAdr': '경기도 동두천시 못골로 30', 'oldZipcd': '483030', 'newZipcd': '11320', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 127.06590346074, 'lat': 37.9012616518346}, {'bizesId': '10099459', 'bizesNm': '쭈노치킨', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '41', 'ctprvnNm': '경기도', 'signguCd': '41570', 'signguNm': '김포시', 'adongCd': '4157025300', 'adongNm': '고촌읍', 'ldongCd': '4157025324', 'ldongNm': '고촌읍', 'lnoCd': '4157025324105380008', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 538, 'lnoSlno': 8, 'lnoAdr': '경기도 김포시 고촌읍 신곡리 538-8', 'rdnmCd': '415704427512', 'rdnm': '경기도 김포시 고촌읍 장차로13번길', 'bldMnno': 18, 'bldSlno': '', 'bldMngNo': '4157025324105380008019970', 'bldNm': '', 'rdnmAdr': '경기도 김포시 고촌읍 장차로13번길 18', 'oldZipcd': '415811', 'newZipcd': '10126', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 126.769859060814, 'lat': 37.6037515030602}, {'bizesId': '10136167', 'bizesNm': '치킨뱅이', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '42', 'ctprvnNm': '강원도', 'signguCd': '42130', 'signguNm': '원주시', 'adongCd': '4213059000', 'adongNm': '단계동', 'ldongCd': '4213011000', 'ldongNm': '단계동', 'lnoCd': '4213011000108300006', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 830, 'lnoSlno': 6, 'lnoAdr': '강원도 원주시 단계동 830-6', 'rdnmCd': '421304457083', 'rdnm': '강원도 원주시 금불3길', 'bldMnno': 5, 'bldSlno': '', 'bldMngNo': '4213011000108300006022278', 'bldNm': '', 'rdnmAdr': '강원도 원주시 금불3길 5', 'oldZipcd': '220938', 'newZipcd': '26423', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 127.932025388709, 'lat': 37.3483579547022}, {'bizesId': '10136346', 'bizesNm': '치킨월드율량점', 'brchNm': '율량점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '43', 'ctprvnNm': '충청북도', 'signguCd': '43114', 'signguNm': '청주시 청원구', 'adongCd': '4311454000', 'adongNm': '율량.사천동', 'ldongCd': '4311410300', 'ldongNm': '율량동', 'lnoCd': '4311410300108060000', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 806, 'lnoSlno': '', 'lnoAdr': '충청북도 청주시 청원구 율량동 806', 'rdnmCd': '431144508043', 'rdnm': '충청북도 청주시 청원구 공항로138번길', 'bldMnno': 53, 'bldSlno': '', 'bldMngNo': '4311111500108060000045239', 'bldNm': '', 'rdnmAdr': '충청북도 청주시 청원구 공항로138번길 53', 'oldZipcd': '363818', 'newZipcd': '28328', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 127.487585541514, 'lat': 36.6698161542425}, {'bizesId': '10150151', 'bizesNm': 'KFC', 'brchNm': '수원이마트점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '41', 'ctprvnNm': '경기도', 'signguCd': '41113', 'signguNm': '수원시 권선구', 'adongCd': '4111368000', 'adongNm': '권선2동', 'ldongCd': '4111313700', 'ldongNm': '권선동', 'lnoCd': '4111313700111890000', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 1189, 'lnoSlno': '', 'lnoAdr': '경기도 수원시 권선구 권선동 1189', 'rdnmCd': '411132012008', 'rdnm': '경기도 수원시 권선구 경수대로', 'bldMnno': 270, 'bldSlno': '', 'bldMngNo': '4111313700111890000027851', 'bldNm': '할인점동', 'rdnmAdr': '경기도 수원시 권선구 경수대로 270', 'oldZipcd': '441713', 'newZipcd': '16585', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 127.020087664145, 'lat': 37.2501017782401}, {'bizesId': '10186527', 'bizesNm': '토마토두마리치킨', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '11', 'ctprvnNm': '서울특별시', 'signguCd': '11440', 'signguNm': '마포구', 'adongCd': '1144063000', 'adongNm': '신수동', 'ldongCd': '1144011300', 'ldongNm': '구수동', 'lnoCd': '1144011300100700001', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 70, 'lnoSlno': 1, 'lnoAdr': '서울특별시 마포구 구수동 70-1', 'rdnmCd': '114403113023', 'rdnm': '서울특별시 마포구 토정로', 'bldMnno': 195, 'bldSlno': 1, 'bldMngNo': '1144011300100700001008546', 'bldNm': '정우빌딩', 'rdnmAdr': '서울특별시 마포구 토정로 195-1', 'oldZipcd': '121130', 'newZipcd': '04087', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 126.932820696234, 'lat': 37.545508849345}, {'bizesId': '10208331', 'bizesNm': '페리카나치킨연수우성체인점', 'brchNm': '연수우성체인점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '28', 'ctprvnNm': '인천광역시', 'signguCd': '28185', 'signguNm': '연수구', 'adongCd': '2818576200', 'adongNm': '연수2동', 'ldongCd': '2818510300', 'ldongNm': '연수동', 'lnoCd': '2818510300106340000', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 634, 'lnoSlno': '', 'lnoAdr': '인천광역시 연수구 연수동 634', 'rdnmCd': '281853152021', 'rdnm': '인천광역시 연수구 원인재로', 'bldMnno': 180, 'bldSlno': '', 'bldMngNo': '2818510300106340000007257', 'bldNm': '연수우성2차아파트', 'rdnmAdr': '인천광역시 연수구 원인재로 180', 'oldZipcd': '406765', 'newZipcd': '21931', 'dongNo': '', 'flrNo': '2', 'hoNo': '', 'lon': 126.683928104747, 'lat': 37.4122665635834}, {'bizesId': '10208355', 'bizesNm': '페리카나치킨벽산분점', 'brchNm': '벽산분점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '42', 'ctprvnNm': '강원도', 'signguCd': '42130', 'signguNm': '원주시', 'adongCd': '4213059000', 'adongNm': '단계동', 'ldongCd': '4213011000', 'ldongNm': '단계동', 'lnoCd': '4213011000108130012', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 813, 'lnoSlno': 12, 'lnoAdr': '강원도 원주시 단계동 813-12', 'rdnmCd': '421304457083', 'rdnm': '강원도 원주시 금불3길', 'bldMnno': 34, 'bldSlno': '', 'bldMngNo': '4213011000108130012022273', 'bldNm': '', 'rdnmAdr': '강원도 원주시 금불3길 34', 'oldZipcd': '220938', 'newZipcd': '26423', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 127.93187697793, 'lat': 37.3502141596654}, {'bizesId': '10208360', 'bizesNm': '페리카나치킨', 'brchNm': '송천점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '45', 'ctprvnNm': '전라북도', 'signguCd': '45113', 'signguNm': '전주시 덕진구', 'adongCd': '4511364100', 'adongNm': '송천1동', 'ldongCd': '4511312100', 'ldongNm': '송천동1가', 'lnoCd': '4511312100101070143', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 107, 'lnoSlno': 143, 'lnoAdr': '전라북도 전주시 덕진구 송천동1가 107-143', 'rdnmCd': '451134601338', 'rdnm': '전라북도 전주시 덕진구 오송1길', 'bldMnno': 15, 'bldSlno': '', 'bldMngNo': '4511312100101070143016691', 'bldNm': '', 'rdnmAdr': '전라북도 전주시 덕진구 오송1길 15', 'oldZipcd': '561816', 'newZipcd': '54823', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 127.128483752173, 'lat': 35.8631606134181}, {'bizesId': '10231561', 'bizesNm': '피자앤닭컴', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '41', 'ctprvnNm': '경기도', 'signguCd': '41281', 'signguNm': '고양시 덕양구', 'adongCd': '4128160000', 'adongNm': '관산동', 'ldongCd': '4128111900', 'ldongNm': '내유동', 'lnoCd': '4128111900109030014', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 903, 'lnoSlno': 14, 'lnoAdr': '경기도 고양시 덕양구 내유동 903-14', 'rdnmCd': '412814379207', 'rdnm': '경기도 고양시 덕양구 통일로1267번길', 'bldMnno': 12, 'bldSlno': '', 'bldMngNo': '4128111900109030014007802', 'bldNm': '', 'rdnmAdr': '경기도 고양시 덕양구 통일로1267번길 12', 'oldZipcd': '412520', 'newZipcd': '10262', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 126.842370394144, 'lat': 37.7250861314577}, {'bizesId': '10242205', 'bizesNm': '하림치킨', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '48', 'ctprvnNm': '경상남도', 'signguCd': '48270', 'signguNm': '밀양시', 'adongCd': '4827034000', 'adongNm': '산내면', 'ldongCd': '4827034028', 'ldongNm': '산내면', 'lnoCd': '4827034028111160004', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 1116, 'lnoSlno': 4, 'lnoAdr': '경상남도 밀양시 산내면 남명리 1116-4', 'rdnmCd': '482703336029', 'rdnm': '경상남도 밀양시 산내면 산내로', 'bldMnno': 1134, 'bldSlno': '', 'bldMngNo': '4827034028111160004000237', 'bldNm': '', 'rdnmAdr': '경상남도 밀양시 산내면 산내로 1134', 'oldZipcd': '627832', 'newZipcd': '50415', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 128.952863807002, 'lat': 35.5878569482513}, {'bizesId': '10274423', 'bizesNm': '핫썬치킨옥동점', 'brchNm': '옥동점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '47', 'ctprvnNm': '경상북도', 'signguCd': '47170', 'signguNm': '안동시', 'adongCd': '4717065000', 'adongNm': '옥동', 'ldongCd': '4717013300', 'ldongNm': '옥동', 'lnoCd': '4717013300107870006', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 787, 'lnoSlno': 6, 'lnoAdr': '경상북도 안동시 옥동 787-6', 'rdnmCd': '471704721489', 'rdnm': '경상북도 안동시 복주1길', 'bldMnno': 92, 'bldSlno': '', 'bldMngNo': '4717013300107870006027092', 'bldNm': '', 'rdnmAdr': '경상북도 안동시 복주1길 92', 'oldZipcd': '760310', 'newZipcd': '36661', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 128.701658516225, 'lat': 36.5633746443297}, {'bizesId': '10398264', 'bizesNm': 'BHC치킨', 'brchNm': '강북점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '42', 'ctprvnNm': '강원도', 'signguCd': '42110', 'signguNm': '춘천시', 'adongCd': '4211070500', 'adongNm': '신사우동', 'ldongCd': '4211011900', 'ldongNm': '사농동', 'lnoCd': '4211011900100320003', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 32, 'lnoSlno': 3, 'lnoAdr': '강원도 춘천시 사농동 32-3', 'rdnmCd': '421104454187', 'rdnm': '강원도 춘천시 마장길', 'bldMnno': 62, 'bldSlno': '', 'bldMngNo': '4211011900100320003012141', 'bldNm': '', 'rdnmAdr': '강원도 춘천시 마장길 62', 'oldZipcd': '200140', 'newZipcd': '24221', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 127.730540190041, 'lat': 37.9093809548376}, {'bizesId': '10407416', 'bizesNm': '치킨아이', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '29', 'ctprvnNm': '광주광역시', 'signguCd': '29170', 'signguNm': '북구', 'adongCd': '2917066900', 'adongNm': '일곡동', 'ldongCd': '2917012700', 'ldongNm': '일곡동', 'lnoCd': '2917012700108160003', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 816, 'lnoSlno': 3, 'lnoAdr': '광주광역시 북구 일곡동 816-3', 'rdnmCd': '291704286581', 'rdnm': '광주광역시 북구 우치로537번길', 'bldMnno': 10, 'bldSlno': 1, 'bldMngNo': '2917012700108160003015135', 'bldNm': '동아아파트', 'rdnmAdr': '광주광역시 북구 우치로537번길 10-1', 'oldZipcd': '500795', 'newZipcd': '61031', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 126.899570717972, 'lat': 35.2126556214737}, {'bizesId': '10423599', 'bizesNm': '더화덕', 'brchNm': '중동점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '48', 'ctprvnNm': '경상남도', 'signguCd': '48121', 'signguNm': '창원시 의창구', 'adongCd': '4812151000', 'adongNm': '의창동', 'ldongCd': '4812110300', 'ldongNm': '서상동', 'lnoCd': '4812110300106680010', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 668, 'lnoSlno': 10, 'lnoAdr': '경상남도 창원시 의창구 서상동 668-10', 'rdnmCd': '481214781529', 'rdnm': '경상남도 창원시 의창구 의창대로254번길', 'bldMnno': 19, 'bldSlno': '', 'bldMngNo': '4812110200103710009067614', 'bldNm': '', 'rdnmAdr': '경상남도 창원시 의창구 의창대로254번길 19', 'oldZipcd': '641500', 'newZipcd': '51370', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 128.625322165672, 'lat': 35.2595259139192}, {'bizesId': '10446382', 'bizesNm': '월드양념통닭', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '26', 'ctprvnNm': '부산광역시', 'signguCd': '26380', 'signguNm': '사하구', 'adongCd': '2638058000', 'adongNm': '장림1동', 'ldongCd': '2638010500', 'ldongNm': '장림동', 'lnoCd': '2638010500106410130', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 641, 'lnoSlno': 130, 'lnoAdr': '부산광역시 사하구 장림동 641-130', 'rdnmCd': '263804202433', 'rdnm': '부산광역시 사하구 장림시장3길', 'bldMnno': 80, 'bldSlno': '', 'bldMngNo': '2638010500106410130018701', 'bldNm': '', 'rdnmAdr': '부산광역시 사하구 장림시장3길 80', 'oldZipcd': '604040', 'newZipcd': '49476', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 128.967851385835, 'lat': 35.0806599306185}, {'bizesId': '10482089', 'bizesNm': 'BBQ치킨', 'brchNm': '진접센트레빌점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '41', 'ctprvnNm': '경기도', 'signguCd': '41360', 'signguNm': '남양주시', 'adongCd': '4136025300', 'adongNm': '진접읍', 'ldongCd': '4136025325', 'ldongNm': '진접읍', 'lnoCd': '4136025325107640000', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 764, 'lnoSlno': '', 'lnoAdr': '경기도 남양주시 진접읍 부평리 764', 'rdnmCd': '413603197029', 'rdnm': '경기도 남양주시 진접읍 부평로', 'bldMnno': 32, 'bldSlno': '', 'bldMngNo': '4136025325107640000000016', 'bldNm': '진접센트레빌시티1단지상가', 'rdnmAdr': '경기도 남양주시 진접읍 부평로 32', 'oldZipcd': '472856', 'newZipcd': '12022', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 127.200193095712, 'lat': 37.7401667347414}, {'bizesId': '10623611', 'bizesNm': '치킨마루', 'brchNm': '현대시장점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '11', 'ctprvnNm': '서울특별시', 'signguCd': '11620', 'signguNm': '관악구', 'adongCd': '1162060500', 'adongNm': '은천동', 'ldongCd': '1162010100', 'ldongNm': '봉천동', 'lnoCd': '1162010100117080000', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 1708, 'lnoSlno': '', 'lnoAdr': '서울특별시 관악구 봉천동 1708', 'rdnmCd': '116203005083', 'rdnm': '서울특별시 관악구 봉천로', 'bldMnno': 387, 'bldSlno': '', 'bldMngNo': '1162010100117080000040043', 'bldNm': '두산아파트', 'rdnmAdr': '서울특별시 관악구 봉천로 387', 'oldZipcd': '151782', 'newZipcd': '08750', 'dongNo': '2', 'flrNo': '', 'hoNo': '', 'lon': 126.9427601496, 'lat': 37.484309081691}, {'bizesId': '10663586', 'bizesNm': '교촌치킨', 'brchNm': '신개금점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '26', 'ctprvnNm': '부산광역시', 'signguCd': '26230', 'signguNm': '부산진구', 'adongCd': '2623074000', 'adongNm': '개금1동', 'ldongCd': '2623011100', 'ldongNm': '개금동', 'lnoCd': '2623011100102010006', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 201, 'lnoSlno': 6, 'lnoAdr': '부산광역시 부산진구 개금동 201-6', 'rdnmCd': '262302006015', 'rdnm': '부산광역시 부산진구 가야대로', 'bldMnno': 475, 'bldSlno': '', 'bldMngNo': '2623011100102010037024141', 'bldNm': '', 'rdnmAdr': '부산광역시 부산진구 가야대로 475', 'oldZipcd': '614110', 'newZipcd': '47268', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 129.024050678641, 'lat': 35.1534913537491}, {'bizesId': '10797221', 'bizesNm': '새때치킨대산점', 'brchNm': '대산점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '48', 'ctprvnNm': '경상남도', 'signguCd': '48121', 'signguNm': '창원시 의창구', 'adongCd': '4812132000', 'adongNm': '대산면', 'ldongCd': '4812132024', 'ldongNm': '대산면', 'lnoCd': '4812132024103800001', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 380, 'lnoSlno': 1, 'lnoAdr': '경상남도 창원시 의창구 대산면 가술리 380-1', 'rdnmCd': '481214781001', 'rdnm': '경상남도 창원시 의창구 대산면 가술길', 'bldMnno': 5, 'bldSlno': 8, 'bldMngNo': '4812132024103800001037798', 'bldNm': '', 'rdnmAdr': '경상남도 창원시 의창구 대산면 가술길 5-8', 'oldZipcd': '641921', 'newZipcd': '51124', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 128.707389819456, 'lat': 35.3347646151675}, {'bizesId': '10843494', 'bizesNm': '본스치킨', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '11', 'ctprvnNm': '서울특별시', 'signguCd': '11440', 'signguNm': '마포구', 'adongCd': '1144060000', 'adongNm': '대흥동', 'ldongCd': '1144010800', 'ldongNm': '대흥동', 'lnoCd': '1144010800108030000', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 803, 'lnoSlno': '', 'lnoAdr': '서울특별시 마포구 대흥동 803', 'rdnmCd': '114403005016', 'rdnm': '서울특별시 마포구 백범로', 'bldMnno': 82, 'bldSlno': '', 'bldMngNo': '1144010800108030000013024', 'bldNm': '동양엔파트', 'rdnmAdr': '서울특별시 마포구 백범로 82', 'oldZipcd': '121811', 'newZipcd': '04110', 'dongNo': '', 'flrNo': '-1', 'hoNo': '', 'lon': 126.940577184787, 'lat': 37.5475699996142}, {'bizesId': '10849818', 'bizesNm': '치킨매니아', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '42', 'ctprvnNm': '강원도', 'signguCd': '42790', 'signguNm': '화천군', 'adongCd': '4279034000', 'adongNm': '사내면', 'ldongCd': '4279034021', 'ldongNm': '사내면', 'lnoCd': '4279034021104540018', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 454, 'lnoSlno': 18, 'lnoAdr': '강원도 화천군 사내면 사창리 454-18', 'rdnmCd': '427903231009', 'rdnm': '강원도 화천군 사내면 사내로', 'bldMnno': 46, 'bldSlno': 1, 'bldMngNo': '4279034021004540018012320', 'bldNm': '치킨매니아', 'rdnmAdr': '강원도 화천군 사내면 사내로 46-1', 'oldZipcd': '209834', 'newZipcd': '24154', 'dongNo': '', 'flrNo': '', 'hoNo': '', 'lon': 127.521222953837, 'lat': 38.0720589580985}, {'bizesId': '10862582', 'bizesNm': '둘둘치킨', 'brchNm': '', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMc

In [70]:
new_data=del data[0]['header']
new_data

SyntaxError: invalid syntax (1211427456.py, line 1)

In [69]:
data[0]['header']

{'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
 'columns': ['상가업소번호',
  '상호명',
  '지점명',
  '상권업종대분류코드',
  '상권업종대분류명',
  '상권업종중분류코드',
  '상권업종중분류명',
  '상권업종소분류코드',
  '상권업종소분류명',
  '표준산업분류코드',
  '표준산업분류명',
  '시도코드',
  '시도명',
  '시군구코드',
  '시군구명',
  '행정동코드',
  '행정동명',
  '법정동코드',
  '법정동명',
  'PNU코드',
  '대지구분코드',
  '대지구분명',
  '지번본번지',
  '지번부번지',
  '지번주소',
  '도로명코드',
  '도로명',
  '건물본번지',
  '건물부번지',
  '건물관리번호',
  '건물명',
  '도로명주소',
  '구우편번호',
  '신우편번호',
  '동정보',
  '층정보',
  '호정보',
  '경도',
  '위도'],
 'stdrYm': '202206',
 'resultCode': '00',
 'resultMsg': 'NORMAL SERVICE'}

In [3]:
data[1]

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
  'columns': ['상가업소번호',
   '상호명',
   '지점명',
   '상권업종대분류코드',
   '상권업종대분류명',
   '상권업종중분류코드',
   '상권업종중분류명',
   '상권업종소분류코드',
   '상권업종소분류명',
   '표준산업분류코드',
   '표준산업분류명',
   '시도코드',
   '시도명',
   '시군구코드',
   '시군구명',
   '행정동코드',
   '행정동명',
   '법정동코드',
   '법정동명',
   'PNU코드',
   '대지구분코드',
   '대지구분명',
   '지번본번지',
   '지번부번지',
   '지번주소',
   '도로명코드',
   '도로명',
   '건물본번지',
   '건물부번지',
   '건물관리번호',
   '건물명',
   '도로명주소',
   '구우편번호',
   '신우편번호',
   '동정보',
   '층정보',
   '호정보',
   '경도',
   '위도'],
  'stdrYm': '202206',
  'resultCode': '00',
  'resultMsg': 'NORMAL SERVICE'},
 'body': {'items': [{'bizesId': '11927910',
    'bizesNm': '흥부네대박닭강정난곡점',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11620',
    'signguNm': '관악구',
    'adongCd': '1162071500',
    'adongNm': '난향동',
    'ldongCd': '1162010200',
    'ldongNm': '신림동',
    'lnoCd': '1162010200106670017',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 667,
    'lnoSlno': 17,
    'lnoAdr': '서울특별시 관악구 신림동 667-17',
    'rdnmCd': '116203120003',
    'rdnm': '서울특별시 관악구 난곡로',
    'bldMnno': 87,
    'bldSlno': '',
    'bldMngNo': '1162010200106680000009515',
    'bldNm': '',
    'rdnmAdr': '서울특별시 관악구 난곡로 87',
    'oldZipcd': '151015',
    'newZipcd': '08859',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.918787821105,
    'lat': 37.4632057701891},
   {'bizesId': '11928045',
    'bizesNm': '또봉이통닭동산남부점',
    'brchNm': '동산남부점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '45',
    'ctprvnNm': '전라북도',
    'signguCd': '45140',
    'signguNm': '익산시',
    'adongCd': '4514057000',
    'adongNm': '동산동',
    'ldongCd': '4514011100',
    'ldongNm': '동산동',
    'lnoCd': '4514011100106090031',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 609,
    'lnoSlno': 31,
    'lnoAdr': '전라북도 익산시 동산동 609-31',
    'rdnmCd': '451404608304',
    'rdnm': '전라북도 익산시 평동로12길',
    'bldMnno': 21,
    'bldSlno': '',
    'bldMngNo': '4514011100106090031083264',
    'bldNm': '',
    'rdnmAdr': '전라북도 익산시 평동로12길 21',
    'oldZipcd': '570959',
    'newZipcd': '54676',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.958748004124,
    'lat': 35.9271437349077},
   {'bizesId': '11928103',
    'bizesNm': '원조옛날통닭',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '44',
    'ctprvnNm': '충청남도',
    'signguCd': '44150',
    'signguNm': '공주시',
    'adongCd': '4415051000',
    'adongNm': '중학동',
    'ldongCd': '4415010400',
    'ldongNm': '중동',
    'lnoCd': '4415010400100010003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1,
    'lnoSlno': 3,
    'lnoAdr': '충청남도 공주시 중동 1-3',
    'rdnmCd': '441503251013',
    'rdnm': '충청남도 공주시 무령로',
    'bldMnno': 274,
    'bldSlno': '',
    'bldMngNo': '4415010400100010003753599',
    'bldNm': '',
    'rdnmAdr': '충청남도 공주시 무령로 274',
    'oldZipcd': '314050',
    'newZipcd': '32562',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.13010082465,
    'lat': 36.4556887869483},
   {'bizesId': '11928271',
    'bizesNm': '해피오네치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41465',
    'signguNm': '용인시 수지구',
    'adongCd': '4146556000',
    'adongNm': '동천동',
    'ldongCd': '4146510300',
    'ldongNm': '동천동',
    'lnoCd': '4146510300108830007',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 883,
    'lnoSlno': 7,
    'lnoAdr': '경기도 용인시 수지구 동천동 883-7',
    'rdnmCd': '414654415048',
    'rdnm': '경기도 용인시 수지구 문인로54번길',
    'bldMnno': 7,
    'bldSlno': '',
    'bldMngNo': '4146510300108830007027115',
    'bldNm': '',
    'rdnmAdr': '경기도 용인시 수지구 문인로54번길 7',
    'oldZipcd': '448504',
    'newZipcd': '16828',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.096606428907,
    'lat': 37.3337548197113},
   {'bizesId': '11928279',
    'bizesNm': '옛날통닭',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41287',
    'signguNm': '고양시 일산서구',
    'adongCd': '4128751000',
    'adongNm': '일산1동',
    'ldongCd': '4128710100',
    'ldongNm': '일산동',
    'lnoCd': '4128710100109660074',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 966,
    'lnoSlno': 74,
    'lnoAdr': '경기도 고양시 일산서구 일산동 966-74',
    'rdnmCd': '412873194019',
    'rdnm': '경기도 고양시 일산서구 원일로',
    'bldMnno': 23,
    'bldSlno': '',
    'bldMngNo': '4128710100109660074003593',
    'bldNm': '',
    'rdnmAdr': '경기도 고양시 일산서구 원일로 23',
    'oldZipcd': '411310',
    'newZipcd': '10348',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.765010126455,
    'lat': 37.6873508803679},
   {'bizesId': '11928346',
    'bizesNm': '깐부치킨',
    'brchNm': '죽전새터내대지점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41465',
    'signguNm': '용인시 수지구',
    'adongCd': '4146554000',
    'adongNm': '죽전1동',
    'ldongCd': '4146510200',
    'ldongNm': '죽전동',
    'lnoCd': '4146510200111880001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1188,
    'lnoSlno': 1,
    'lnoAdr': '경기도 용인시 수지구 죽전동 1188-1',
    'rdnmCd': '414653205022',
    'rdnm': '경기도 용인시 수지구 현암로',
    'bldMnno': 153,
    'bldSlno': '',
    'bldMngNo': '4146510200111880001027753',
    'bldNm': '건영타운',
    'rdnmAdr': '경기도 용인시 수지구 현암로 153',
    'oldZipcd': '448160',
    'newZipcd': '16876',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.126407658862,
    'lat': 37.3319421591449},
   {'bizesId': '11928400',
    'bizesNm': '치킨조이',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '29',
    'ctprvnNm': '광주광역시',
    'signguCd': '29200',
    'signguNm': '광산구',
    'adongCd': '2920070000',
    'adongNm': '신창동',
    'ldongCd': '2920011800',
    'ldongNm': '신창동',
    'lnoCd': '2920011800112220006',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1222,
    'lnoSlno': 6,
    'lnoAdr': '광주광역시 광산구 신창동 1222-6',
    'rdnmCd': '292004289396',
    'rdnm': '광주광역시 광산구 신창로72번길',
    'bldMnno': 10,
    'bldSlno': 15,
    'bldMngNo': '2920011800112220006045682',
    'bldNm': '',
    'rdnmAdr': '광주광역시 광산구 신창로72번길 10-15',
    'oldZipcd': '506841',
    'newZipcd': '62252',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.838083458264,
    'lat': 35.1913314770652},
   {'bizesId': '11928583',
    'bizesNm': '호식이두마리치킨개포1호점',
    'brchNm': '개포1호점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11680',
    'signguNm': '강남구',
    'adongCd': '1168069000',
    'adongNm': '개포4동',
    'ldongCd': '1168010300',
    'ldongNm': '개포동',
    'lnoCd': '1168010300111770000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1177,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 강남구 개포동 1177',
    'rdnmCd': '116804166204',
    'rdnm': '서울특별시 강남구 논현로8길',
    'bldMnno': 50,
    'bldSlno': '',
    'bldMngNo': '1168010300101770000020970',
    'bldNm': '',
    'rdnmAdr': '서울특별시 강남구 논현로8길 50',
    'oldZipcd': '135240',
    'newZipcd': '06314',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.052776969964,
    'lat': 37.4746188698975},
   {'bizesId': '11928677',
    'bizesNm': '쌀민족쌀통닭',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41465',
    'signguNm': '용인시 수지구',
    'adongCd': '4146558000',
    'adongNm': '상현2동',
    'ldongCd': '4146510700',
    'ldongNm': '상현동',
    'lnoCd': '4146510700100660009',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 66,
    'lnoSlno': 9,
    'lnoAdr': '경기도 용인시 수지구 상현동 66-9',
    'rdnmCd': '414653205005',
    'rdnm': '경기도 용인시 수지구 만현로',
    'bldMnno': 88,
    'bldSlno': '',
    'bldMngNo': '4146510700100660009027439',
    'bldNm': '상현종합상가',
    'rdnmAdr': '경기도 용인시 수지구 만현로 88',
    'oldZipcd': '448130',
    'newZipcd': '16930',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.085113399254,
    'lat': 37.3090578604047},
   {'bizesId': '11928764',
    'bizesNm': '치킨하우스',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41133',
    'signguNm': '성남시 중원구',
    'adongCd': '4113357000',
    'adongNm': '상대원1동',
    'ldongCd': '4113310500',
    'ldongNm': '상대원동',
    'lnoCd': '4113310500100710001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 71,
    'lnoSlno': 1,
    'lnoAdr': '경기도 성남시 중원구 상대원동 71-1',
    'rdnmCd': '411333179014',
    'rdnm': '경기도 성남시 중원구 순환로',
    'bldMnno': 234,
    'bldSlno': '',
    'bldMngNo': '4113310500100710001059804',
    'bldNm': '',
    'rdnmAdr': '경기도 성남시 중원구 순환로 234',
    'oldZipcd': '462120',
    'newZipcd': '13205',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.179412355416,
    'lat': 37.4447225427694},
   {'bizesId': '11928772',
    'bizesNm': '그집마늘치킨',
    'brchNm': '장천점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '47',
    'ctprvnNm': '경상북도',
    'signguCd': '47190',
    'signguNm': '구미시',
    'adongCd': '4719036000',
    'adongNm': '장천면',
    'ldongCd': '4719036021',
    'ldongNm': '장천면',
    'lnoCd': '4719036021107070008',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 707,
    'lnoSlno': 8,
    'lnoAdr': '경상북도 구미시 장천면 상장리 707-8',
    'rdnmCd': '471903305003',
    'rdnm': '경상북도 구미시 장천면 강동로',
    'bldMnno': 163,
    'bldSlno': '',
    'bldMngNo': '4719036021107070008073516',
    'bldNm': '',
    'rdnmAdr': '경상북도 구미시 장천면 강동로 163',
    'oldZipcd': '730843',
    'newZipcd': '39454',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.49549782398,
    'lat': 36.1242725804201},
   {'bizesId': '11929020',
    'bizesNm': '호식이두마리치킨',
    'brchNm': '송림점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '28',
    'ctprvnNm': '인천광역시',
    'signguCd': '28140',
    'signguNm': '동구',
    'adongCd': '2814058000',
    'adongNm': '송림1동',
    'ldongCd': '2814010700',
    'ldongNm': '송림동',
    'lnoCd': '2814010700102270007',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 227,
    'lnoSlno': 7,
    'lnoAdr': '인천광역시 동구 송림동 227-7',
    'rdnmCd': '281403150037',
    'rdnm': '인천광역시 동구 송림로',
    'bldMnno': 59,
    'bldSlno': '',
    'bldMngNo': '2814010700102270007032241',
    'bldNm': '',
    'rdnmAdr': '인천광역시 동구 송림로 59',
    'oldZipcd': '401070',
    'newZipcd': '22542',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.641338632853,
    'lat': 37.4749560193084},
   {'bizesId': '11929050',
    'bizesNm': '수동착한통닭',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41360',
    'signguNm': '남양주시',
    'adongCd': '4136034000',
    'adongNm': '수동면',
    'ldongCd': '4136034021',
    'ldongNm': '수동면',
    'lnoCd': '4136034021100900004',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 90,
    'lnoSlno': 4,
    'lnoAdr': '경기도 남양주시 수동면 운수리 90-4',
    'rdnmCd': '413603197032',
    'rdnm': '경기도 남양주시 수동면 비룡로',
    'bldMnno': 750,
    'bldSlno': '',
    'bldMngNo': '4136034021100890002000001',
    'bldNm': '',
    'rdnmAdr': '경기도 남양주시 수동면 비룡로 750',
    'oldZipcd': '472852',
    'newZipcd': '12031',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.32639474784,
    'lat': 37.705328407085},
   {'bizesId': '11929066',
    'bizesNm': 'BHC치킨',
    'brchNm': '산호야구장점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48125',
    'signguNm': '창원시 마산합포구',
    'adongCd': '4812565000',
    'adongNm': '산호동',
    'ldongCd': '4812511800',
    'ldongNm': '산호동',
    'lnoCd': '4812511800100260057',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 26,
    'lnoSlno': 57,
    'lnoAdr': '경상남도 창원시 마산합포구 산호동 26-57',
    'rdnmCd': '481254787330',
    'rdnm': '경상남도 창원시 마산합포구 산호북15길',
    'bldMnno': 35,
    'bldSlno': '',
    'bldMngNo': '4812511800100260057020643',
    'bldNm': '',
    'rdnmAdr': '경상남도 창원시 마산합포구 산호북15길 35',
    'oldZipcd': '631852',
    'newZipcd': '51328',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.583095740912,
    'lat': 35.2191910321841},
   {'bizesId': '11929081',
    'bizesNm': '훌리네다리치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41250',
    'signguNm': '동두천시',
    'adongCd': '4125056500',
    'adongNm': '불현동',
    'ldongCd': '4125010200',
    'ldongNm': '지행동',
    'lnoCd': '4125010200102860000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 286,
    'lnoSlno': '',
    'lnoAdr': '경기도 동두천시 지행동 286',
    'rdnmCd': '412503189026',
    'rdnm': '경기도 동두천시 지행로',
    'bldMnno': 104,
    'bldSlno': '',
    'bldMngNo': '4125010200102860000008995',
    'bldNm': '',
    'rdnmAdr': '경기도 동두천시 지행로 104',
    'oldZipcd': '483020',
    'newZipcd': '11363',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.05892159358,
    'lat': 37.8923492308577},
   {'bizesId': '11929447',
    'bizesNm': '치킨스토리',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26470',
    'signguNm': '연제구',
    'adongCd': '2647067000',
    'adongNm': '연산3동',
    'ldongCd': '2647010200',
    'ldongNm': '연산동',
    'lnoCd': '2647010200118110244',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1811,
    'lnoSlno': 244,
    'lnoAdr': '부산광역시 연제구 연산동 1811-244',
    'rdnmCd': '264704211128',
    'rdnm': '부산광역시 연제구 금련로12번길',
    'bldMnno': 17,
    'bldSlno': '',
    'bldMngNo': '2647010200118110244003480',
    'bldNm': '',
    'rdnmAdr': '부산광역시 연제구 금련로12번길 17',
    'oldZipcd': '611080',
    'newZipcd': '47614',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 129.095243237613,
    'lat': 35.1728524844134},
   {'bizesId': '11929512',
    'bizesNm': '닭킬러숯불바베큐',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '28',
    'ctprvnNm': '인천광역시',
    'signguCd': '28177',
    'signguNm': '미추홀구',
    'adongCd': '2817757000',
    'adongNm': '용현5동',
    'ldongCd': '2817710200',
    'ldongNm': '용현동',
    'lnoCd': '2817710200106270364',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 627,
    'lnoSlno': 364,
    'lnoAdr': '인천광역시 미추홀구 용현동 627-364',
    'rdnmCd': '281774253116',
    'rdnm': '인천광역시 미추홀구 낙섬서로18번길',
    'bldMnno': 5,
    'bldSlno': '',
    'bldMngNo': '2817010200106270364000001',
    'bldNm': '',
    'rdnmAdr': '인천광역시 미추홀구 낙섬서로18번길 5',
    'oldZipcd': '402834',
    'newZipcd': '22190',
    'dongNo': '5',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.634783602233,
    'lat': 37.4512194784295},
   {'bizesId': '11929749',
    'bizesNm': 'BBQ치킨',
    'brchNm': '대전전민점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '30',
    'ctprvnNm': '대전광역시',
    'signguCd': '30200',
    'signguNm': '유성구',
    'adongCd': '3020057000',
    'adongNm': '전민동',
    'ldongCd': '3020014100',
    'ldongNm': '전민동',
    'lnoCd': '3020014100103270023',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 327,
    'lnoSlno': 23,
    'lnoAdr': '대전광역시 유성구 전민동 327-23',
    'rdnmCd': '302004301384',
    'rdnm': '대전광역시 유성구 전민로10번길',
    'bldMnno': 58,
    'bldSlno': '',
    'bldMngNo': '3020014100103270023002680',
    'bldNm': '',
    'rdnmAdr': '대전광역시 유성구 전민로10번길 58',
    'oldZipcd': '305810',
    'newZipcd': '34052',
    'dongNo': '',
    'flrNo': '2',
    'hoNo': '',
    'lon': 127.40413006205,
    'lat': 36.3989350130297},
   {'bizesId': '11929942',
    'bizesNm': '둘둘치킨상계점',
    'brchNm': '상계점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11350',
    'signguNm': '노원구',
    'adongCd': '1135062400',
    'adongNm': '중계4동',
    'ldongCd': '1135010600',
    'ldongNm': '중계동',
    'lnoCd': '1135010600101420045',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 142,
    'lnoSlno': 45,
    'lnoAdr': '서울특별시 노원구 중계동 142-45',
    'rdnmCd': '113504130392',
    'rdnm': '서울특별시 노원구 한글비석로20길',
    'bldMnno': 25,
    'bldSlno': '',
    'bldMngNo': '1135010600101420045009854',
    'bldNm': '',
    'rdnmAdr': '서울특별시 노원구 한글비석로20길 25',
    'oldZipcd': '139220',
    'newZipcd': '01662',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.073826035809,
    'lat': 37.6603925969997},
   {'bizesId': '11930077',
    'bizesNm': '노량통닭신천점',
    'brchNm': '신천점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11710',
    'signguNm': '송파구',
    'adongCd': '1171065000',

In [6]:
data[1]['header']

{'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
 'columns': ['상가업소번호',
  '상호명',
  '지점명',
  '상권업종대분류코드',
  '상권업종대분류명',
  '상권업종중분류코드',
  '상권업종중분류명',
  '상권업종소분류코드',
  '상권업종소분류명',
  '표준산업분류코드',
  '표준산업분류명',
  '시도코드',
  '시도명',
  '시군구코드',
  '시군구명',
  '행정동코드',
  '행정동명',
  '법정동코드',
  '법정동명',
  'PNU코드',
  '대지구분코드',
  '대지구분명',
  '지번본번지',
  '지번부번지',
  '지번주소',
  '도로명코드',
  '도로명',
  '건물본번지',
  '건물부번지',
  '건물관리번호',
  '건물명',
  '도로명주소',
  '구우편번호',
  '신우편번호',
  '동정보',
  '층정보',
  '호정보',
  '경도',
  '위도'],
 'stdrYm': '202206',
 'resultCode': '00',
 'resultMsg': 'NORMAL SERVICE'}

In [8]:
data[1]['header']['columns']

['상가업소번호',
 '상호명',
 '지점명',
 '상권업종대분류코드',
 '상권업종대분류명',
 '상권업종중분류코드',
 '상권업종중분류명',
 '상권업종소분류코드',
 '상권업종소분류명',
 '표준산업분류코드',
 '표준산업분류명',
 '시도코드',
 '시도명',
 '시군구코드',
 '시군구명',
 '행정동코드',
 '행정동명',
 '법정동코드',
 '법정동명',
 'PNU코드',
 '대지구분코드',
 '대지구분명',
 '지번본번지',
 '지번부번지',
 '지번주소',
 '도로명코드',
 '도로명',
 '건물본번지',
 '건물부번지',
 '건물관리번호',
 '건물명',
 '도로명주소',
 '구우편번호',
 '신우편번호',
 '동정보',
 '층정보',
 '호정보',
 '경도',
 '위도']

In [10]:
for i in data[2]

SyntaxError: invalid syntax (798098806.py, line 1)

In [28]:
result={}


key=data[1]['body']['items'][0].keys()
key

for key, value in new_data.items():
    result.setdefault(key,[]).append(value)
    
    #for key, value in review.items():
        #result2.setdefault(key,[]).append(value)

AttributeError: 'list' object has no attribute 'items'

2

In [35]:
result={}
key=data[1]['body']['items'].keys()
for key in data[0]:
    temp=[]
    for dicts in data[1]['body']['items'][i]:
        temp.append(dicts[key])
    result[key]=temp
print(result)

AttributeError: 'list' object has no attribute 'keys'

In [55]:
import pandas as pd
df=pd.DataFrame(result)
df

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36059,9829515,아리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010200106740003008662,,경기도 동두천시 거북마루로 6,483020,11348,,1,,127.046713,37.895702
36060,9851302,애니치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4785031036104090002008916,,경상북도 칠곡군 지천면 신동로 147,718821,39864,,,,128.488717,35.956631
36061,9867543,에디슨치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1135010600103590001010681,중계5단지주공아파트,서울특별시 노원구 중계로 230,139781,01713,,1,,127.075031,37.651004
36062,9918905,오븐에꾸운닭장유점,장유점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4825031027103150002091993,재영프라자,경상남도 김해시 삼문로 26,621280,51004,,1,,128.803565,35.192491
36063,9967953,웰빙치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011100101360002016167,,강원도 원주시 상지대길 43,220954,26342,,1,,127.937290,37.369591

In [34]:
data[1]['body']['items']

[{'bizesId': '11927910',
  'bizesNm': '흥부네대박닭강정난곡점',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11620',
  'signguNm': '관악구',
  'adongCd': '1162071500',
  'adongNm': '난향동',
  'ldongCd': '1162010200',
  'ldongNm': '신림동',
  'lnoCd': '1162010200106670017',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 667,
  'lnoSlno': 17,
  'lnoAdr': '서울특별시 관악구 신림동 667-17',
  'rdnmCd': '116203120003',
  'rdnm': '서울특별시 관악구 난곡로',
  'bldMnno': 87,
  'bldSlno': '',
  'bldMngNo': '1162010200106680000009515',
  'bldNm': '',
  'rdnmAdr': '서울특별시 관악구 난곡로 87',
  'oldZipcd': '151015',
  'newZipcd': '08859',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 126.918787821105,
  'lat': 37.4632057701891},
 {'bizesId': '11928045',
  'bizesNm': '또봉이통닭동산남부점',
  'brchNm': '동산남부점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '45',
  'ctprvnNm': '전라북도',
  'signguCd': '45140',
  'signguNm': '익산시',
  'adongCd': '4514057000',
  'adongNm': '동산동',
  'ldongCd': '4514011100',
  'ldongNm': '동산동',
  'lnoCd': '4514011100106090031',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 609,
  'lnoSlno': 31,
  'lnoAdr': '전라북도 익산시 동산동 609-31',
  'rdnmCd': '451404608304',
  'rdnm': '전라북도 익산시 평동로12길',
  'bldMnno': 21,
  'bldSlno': '',
  'bldMngNo': '4514011100106090031083264',
  'bldNm': '',
  'rdnmAdr': '전라북도 익산시 평동로12길 21',
  'oldZipcd': '570959',
  'newZipcd': '54676',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 126.958748004124,
  'lat': 35.9271437349077},
 {'bizesId': '11928103',
  'bizesNm': '원조옛날통닭',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '44',
  'ctprvnNm': '충청남도',
  'signguCd': '44150',
  'signguNm': '공주시',
  'adongCd': '4415051000',
  'adongNm': '중학동',
  'ldongCd': '4415010400',
  'ldongNm': '중동',
  'lnoCd': '4415010400100010003',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 1,
  'lnoSlno': 3,
  'lnoAdr': '충청남도 공주시 중동 1-3',
  'rdnmCd': '441503251013',
  'rdnm': '충청남도 공주시 무령로',
  'bldMnno': 274,
  'bldSlno': '',
  'bldMngNo': '4415010400100010003753599',
  'bldNm': '',
  'rdnmAdr': '충청남도 공주시 무령로 274',
  'oldZipcd': '314050',
  'newZipcd': '32562',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 127.13010082465,
  'lat': 36.4556887869483},
 {'bizesId': '11928271',
  'bizesNm': '해피오네치킨',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '41',
  'ctprvnNm': '경기도',
  'signguCd': '41465',
  'signguNm': '용인시 수지구',
  'adongCd': '4146556000',
  'adongNm': '동천동',
  'ldongCd': '4146510300',
  'ldongNm': '동천동',
  'lnoCd': '4146510300108830007',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 883,
  'lnoSlno': 7,
  'lnoAdr': '경기도 용인시 수지구 동천동 883-7',
  'rdnmCd': '414654415048',
  'rdnm': '경기도 용인시 수지구 문인로54번길',
  'bldMnno': 7,
  'bldSlno': '',
  'bldMngNo': '4146510300108830007027115',
  'bldNm': '',
  'rdnmAdr': '경기도 용인시 수지구 문인로54번길 7',
  'oldZipcd': '448504',
  'newZipcd': '16828',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 127.096606428907,
  'lat': 37.3337548197113},
 {'bizesId': '11928279',
  'bizesNm': '옛날통닭',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '41',
  'ctprvnNm': '경기도',
  'signguCd': '41287',
  'signguNm': '고양시 일산서구',
  'adongCd': '4128751000',
  'adongNm': '일산1동',
  'ldongCd': '4128710100',
  'ldongNm': '일산동',
  'lnoCd': '4128710100109660074',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 966,
  'lnoSlno': 74,
  'lnoAdr': '경기도 고양시 일산서구 일산동 966-74',
  'rdnmCd': '412873194019',
  'rdnm': '경기도 고양시 일산서구 원일로',
  'bldMnno': 23,
  'bldSlno': '',
  'bldMngNo': '4128710100109660074003593',
  'bldNm': '',
  'rdnmAdr': '경기도 고양시 일산서구 원일로 23',
  'oldZipcd': '411310',
  'newZipcd': '10348',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 126.765010126455,
  'lat': 37.6873508803679},
 {'bizesId': '11928346',
  'bizesNm': '깐부치킨',
  'brchNm': '죽전새터내대지점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '41',
  'ctprvnNm': '경기도',
  'signguCd': '41465',
  'signguNm': '용인시 수지구',
  'adongCd': '4146554000',
  'adongNm': '죽전1동',
  'ldongCd': '4146510200',
  'ldongNm': '죽전동',
  'lnoCd': '4146510200111880001',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 1188,
  'lnoSlno': 1,
  'lnoAdr': '경기도 용인시 수지구 죽전동 1188-1',
  'rdnmCd': '414653205022',
  'rdnm': '경기도 용인시 수지구 현암로',
  'bldMnno': 153,
  'bldSlno': '',
  'bldMngNo': '4146510200111880001027753',
  'bldNm': '건영타운',
  'rdnmAdr': '경기도 용인시 수지구 현암로 153',
  'oldZipcd': '448160',
  'newZipcd': '16876',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 127.126407658862,
  'lat': 37.3319421591449},
 {'bizesId': '11928400',
  'bizesNm': '치킨조이',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '29',
  'ctprvnNm': '광주광역시',
  'signguCd': '29200',
  'signguNm': '광산구',
  'adongCd': '2920070000',
  'adongNm': '신창동',
  'ldongCd': '2920011800',
  'ldongNm': '신창동',
  'lnoCd': '2920011800112220006',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 1222,
  'lnoSlno': 6,
  'lnoAdr': '광주광역시 광산구 신창동 1222-6',
  'rdnmCd': '292004289396',
  'rdnm': '광주광역시 광산구 신창로72번길',
  'bldMnno': 10,
  'bldSlno': 15,
  'bldMngNo': '2920011800112220006045682',
  'bldNm': '',
  'rdnmAdr': '광주광역시 광산구 신창로72번길 10-15',
  'oldZipcd': '506841',
  'newZipcd': '62252',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 126.838083458264,
  'lat': 35.1913314770652},
 {'bizesId': '11928583',
  'bizesNm': '호식이두마리치킨개포1호점',
  'brchNm': '개포1호점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11680',
  'signguNm': '강남구',
  'adongCd': '1168069000',
  'adongNm': '개포4동',
  'ldongCd': '1168010300',
  'ldongNm': '개포동',
  'lnoCd': '1168010300111770000',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 1177,
  'lnoSlno': '',
  'lnoAdr': '서울특별시 강남구 개포동 1177',
  'rdnmCd': '116804166204',
  'rdnm': '서울특별시 강남구 논현로8길',
  'bldMnno': 50,
  'bldSlno': '',
  'bldMngNo': '1168010300101770000020970',
  'bldNm': '',
  'rdnmAdr': '서울특별시 강남구 논현로8길 50',
  'oldZipcd': '135240',
  'newZipcd': '06314',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 127.052776969964,
  'lat': 37.4746188698975},
 {'bizesId': '11928677',
  'bizesNm': '쌀민족쌀통닭',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '41',
  'ctprvnNm': '경기도',
  'signguCd': '41465',
  'signguNm': '용인시 수지구',
  'adongCd': '4146558000',
  'adongNm': '상현2동',
  'ldongCd': '4146510700',
  'ldongNm': '상현동',
  'lnoCd': '4146510700100660009',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 66,
  'lnoSlno': 9,
  'lnoAdr': '경기도 용인시 수지구 상현동 66-9',
  'rdnmCd': '414653205005',
  'rdnm': '경기도 용인시 수지구 만현로',
  'bldMnno': 88,
  'bldSlno': '',
  'bldMngNo': '4146510700100660009027439',
  'bldNm': '상현종합상가',
  'rdnmAdr': '경기도 용인시 수지구 만현로 88',
  'oldZipcd': '448130',
  'newZipcd': '16930',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 127.085113399254,
  'lat': 37.3090578604047},
 {'bizesId': '11928764',
  'bizesNm': '치킨하우스',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '41',
  'ctprvnNm': '경기도',
  'signguCd': '41133',
  'signguNm': '성남시 중원구',
  'adongCd': '4113357000',
  'adongNm': '상대원1동',
  'ldongCd': '4113310500',
  'ldongNm': '상대원동',
  'lnoCd': '4113310500100710001',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 71,
  'lnoSlno': 1,
  'lnoAdr': '경기도 성남시 중원구 상대원동 71-1',
  'rdnmCd': '411333179014',
  'rdnm': '경기도 성남시 중원구 순환로',
  'bldMnno': 234,
  'bldSlno': '',
  'bldMngNo': '4113310500100710001059804',
  'bldNm': '',
  'rdnmAdr': '경기도 성남시 중원구 순환로 234',
  'oldZipcd': '462120',
  'newZipcd': '13205',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 127.179412355416,
  'lat': 37.4447225427694},
 {'bizesId': '11928772',
  'bizesNm': '그집마늘치킨',
  'brchNm': '장천점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '47',
  'ctprvnNm': '경상북도',
  'signguCd': '47190',
  'signguNm': '구미시',
  'adongCd': '4719036000',
  'adongNm': '장천면',
  'ldongCd': '4719036021',
  'ldongNm': '장천면',
  'lnoCd': '4719036021107070008',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 707,
  'lnoSlno': 8,
  'lnoAdr': '경상북도 구미시 장천면 상장리 707-8',
  'rdnmCd': '471903305003',
  'rdnm': '경상북도 구미시 장천면 강동로',
  'bldMnno': 163,
  'bldSlno': '',
  'bldMngNo': '4719036021107070008073516',
  'bldNm': '',
  'rdnmAdr': '경상북도 구미시 장천면 강동로 163',
  'oldZipcd': '730843',
  'newZipcd': '39454',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 128.49549782398,
  'lat': 36.1242725804201},
 {'bizesId': '11929020',
  'bizesNm': '호식이두마리치킨',
  'brchNm': '송림점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '28',
  'ctprvnNm': '인천광역시',
  'signguCd': '28140',
  'signguNm': '동구',
  'adongCd': '2814058000',
  'adongNm': '송림1동',
  'ldongCd': '2814010700',
  'ldongNm': '송림동',
  'lnoCd': '2814010700102270007',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 227,
  'lnoSlno': 7,
  'lnoAdr': '인천광역시 동구 송림동 227-7',
  'rdnmCd': '281403150037',
  'rdnm': '인천광역시 동구 송림로',
  'bldMnno': 59,
  'bldSlno': '',
  'bldMngNo': '2814010700102270007032241',
  'bldNm': '',
  'rdnmAdr': '인천광역시 동구 송림로 59',
  'oldZipcd': '401070',
  'newZipcd': '22542',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 126.641338632853,
  'lat': 37.4749560193084},
 {'bizesId': '11929050',
  'bizesNm': '수동착한통닭',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '41',
  'ctprvnNm': '경기도',
  'signguCd': '41360',
  'signguNm': '남양주시',
  'adongCd': '4136034000',
  'adongNm': '수동면',
  'ldongCd': '4136034021',
  'ldongNm': '수동면',
  'lnoCd': '4136034021100900004',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 90,
  'lnoSlno': 4,
  'lnoAdr': '경기도 남양주시 수동면 운수리 90-4',
  'rdnmCd': '413603197032',
  'rdnm': '경기도 남양주시 수동면 비룡로',
  'bldMnno': 750,
  'bldSlno': '',
  'bldMngNo': '4136034021100890002000001',
  'bldNm': '',
  'rdnmAdr': '경기도 남양주시 수동면 비룡로 750',
  'oldZipcd': '472852',
  'newZipcd': '12031',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 127.32639474784,
  'lat': 37.705328407085},
 {'bizesId': '11929066',
  'bizesNm': 'BHC치킨',
  'brchNm': '산호야구장점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '48',
  'ctprvnNm': '경상남도',
  'signguCd': '48125',
  'signguNm': '창원시 마산합포구',
  'adongCd': '4812565000',
  'adongNm': '산호동',
  'ldongCd': '4812511800',
  'ldongNm': '산호동',
  'lnoCd': '4812511800100260057',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 26,
  'lnoSlno': 57,
  'lnoAdr': '경상남도 창원시 마산합포구 산호동 26-57',
  'rdnmCd': '481254787330',
  'rdnm': '경상남도 창원시 마산합포구 산호북15길',
  'bldMnno': 35,
  'bldSlno': '',
  'bldMngNo': '4812511800100260057020643',
  'bldNm': '',
  'rdnmAdr': '경상남도 창원시 마산합포구 산호북15길 35',
  'oldZipcd': '631852',
  'newZipcd': '51328',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 128.583095740912,
  'lat': 35.2191910321841},
 {'bizesId': '11929081',
  'bizesNm': '훌리네다리치킨',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '41',
  'ctprvnNm': '경기도',
  'signguCd': '41250',
  'signguNm': '동두천시',
  'adongCd': '4125056500',
  'adongNm': '불현동',
  'ldongCd': '4125010200',
  'ldongNm': '지행동',
  'lnoCd': '4125010200102860000',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 286,
  'lnoSlno': '',
  'lnoAdr': '경기도 동두천시 지행동 286',
  'rdnmCd': '412503189026',
  'rdnm': '경기도 동두천시 지행로',
  'bldMnno': 104,
  'bldSlno': '',
  'bldMngNo': '4125010200102860000008995',
  'bldNm': '',
  'rdnmAdr': '경기도 동두천시 지행로 104',
  'oldZipcd': '483020',
  'newZipcd': '11363',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 127.05892159358,
  'lat': 37.8923492308577},
 {'bizesId': '11929447',
  'bizesNm': '치킨스토리',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '26',
  'ctprvnNm': '부산광역시',
  'signguCd': '26470',
  'signguNm': '연제구',
  'adongCd': '2647067000',
  'adongNm': '연산3동',
  'ldongCd': '2647010200',
  'ldongNm': '연산동',
  'lnoCd': '2647010200118110244',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 1811,
  'lnoSlno': 244,
  'lnoAdr': '부산광역시 연제구 연산동 1811-244',
  'rdnmCd': '264704211128',
  'rdnm': '부산광역시 연제구 금련로12번길',
  'bldMnno': 17,
  'bldSlno': '',
  'bldMngNo': '2647010200118110244003480',
  'bldNm': '',
  'rdnmAdr': '부산광역시 연제구 금련로12번길 17',
  'oldZipcd': '611080',
  'newZipcd': '47614',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 129.095243237613,
  'lat': 35.1728524844134},
 {'bizesId': '11929512',
  'bizesNm': '닭킬러숯불바베큐',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '28',
  'ctprvnNm': '인천광역시',
  'signguCd': '28177',
  'signguNm': '미추홀구',
  'adongCd': '2817757000',
  'adongNm': '용현5동',
  'ldongCd': '2817710200',
  'ldongNm': '용현동',
  'lnoCd': '2817710200106270364',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 627,
  'lnoSlno': 364,
  'lnoAdr': '인천광역시 미추홀구 용현동 627-364',
  'rdnmCd': '281774253116',
  'rdnm': '인천광역시 미추홀구 낙섬서로18번길',
  'bldMnno': 5,
  'bldSlno': '',
  'bldMngNo': '2817010200106270364000001',
  'bldNm': '',
  'rdnmAdr': '인천광역시 미추홀구 낙섬서로18번길 5',
  'oldZipcd': '402834',
  'newZipcd': '22190',
  'dongNo': '5',
  'flrNo': '1',
  'hoNo': '',
  'lon': 126.634783602233,
  'lat': 37.4512194784295},
 {'bizesId': '11929749',
  'bizesNm': 'BBQ치킨',
  'brchNm': '대전전민점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '30',
  'ctprvnNm': '대전광역시',
  'signguCd': '30200',
  'signguNm': '유성구',
  'adongCd': '3020057000',
  'adongNm': '전민동',
  'ldongCd': '3020014100',
  'ldongNm': '전민동',
  'lnoCd': '3020014100103270023',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 327,
  'lnoSlno': 23,
  'lnoAdr': '대전광역시 유성구 전민동 327-23',
  'rdnmCd': '302004301384',
  'rdnm': '대전광역시 유성구 전민로10번길',
  'bldMnno': 58,
  'bldSlno': '',
  'bldMngNo': '3020014100103270023002680',
  'bldNm': '',
  'rdnmAdr': '대전광역시 유성구 전민로10번길 58',
  'oldZipcd': '305810',
  'newZipcd': '34052',
  'dongNo': '',
  'flrNo': '2',
  'hoNo': '',
  'lon': 127.40413006205,
  'lat': 36.3989350130297},
 {'bizesId': '11929942',
  'bizesNm': '둘둘치킨상계점',
  'brchNm': '상계점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11350',
  'signguNm': '노원구',
  'adongCd': '1135062400',
  'adongNm': '중계4동',
  'ldongCd': '1135010600',
  'ldongNm': '중계동',
  'lnoCd': '1135010600101420045',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 142,
  'lnoSlno': 45,
  'lnoAdr': '서울특별시 노원구 중계동 142-45',
  'rdnmCd': '113504130392',
  'rdnm': '서울특별시 노원구 한글비석로20길',
  'bldMnno': 25,
  'bldSlno': '',
  'bldMngNo': '1135010600101420045009854',
  'bldNm': '',
  'rdnmAdr': '서울특별시 노원구 한글비석로20길 25',
  'oldZipcd': '139220',
  'newZipcd': '01662',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 127.073826035809,
  'lat': 37.6603925969997},
 {'bizesId': '11930077',
  'bizesNm': '노량통닭신천점',
  'brchNm': '신천점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11710',
  'signguNm': '송파구',
  'adongCd': '1171065000',
  'adongNm': '잠실본동',
  'ldongCd': '1171010100',
  'ldongNm': '잠실동',
  'lnoCd': '1171010100101920012',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 192,
  'lnoSlno': 12,
  'lnoAdr': '서울특별시 송파구 잠실동 192-12',
  'rdnmCd': '117104169204',
  'rdnm': '서울특별시 송파구 백제고분로7길',
  'bldMnno': 20,
  'bldSlno': '',
  'bldMngNo': '1171010100101920012000564',
  'bldNm': '',
  'rdnmAdr': '서울특별시 송파구 백제고분로7길 20',
  'oldZipcd': '138220',
  'newZipcd': '05561',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 127.080997635039,
  'lat': 37.5104966627785},
 {'bizesId': '11930113',
  'bizesNm': 'BBQ치킨봉천1점',
  'brchNm': '봉천1점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11620',
  'signguNm': '관악구',
  'adongCd': '1162057500',
  'adongNm': '행운동',
  'ldongCd': '1162010100',
  'ldongNm': '봉천동',
  'lnoCd': '1162010100100360010',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 36,
  'lnoSlno': 10,
  'lnoAdr': '서울특별시 관악구 봉천동 36-10',
  'rdnmCd': '116204160016',
  'rdnm': '서울특별시 관악구 관악로28길',
  'bldMnno': 11,
  'bldSlno': '',
  'bldMngNo': '1162010100100360010031478',
  'bldNm': '',
  'rdnmAdr': '서울특별시 관악구 관악로28길 11',
  'oldZipcd': '151050',
  'newZipcd': '08735',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 126.956777794322,
  'lat': 37.4853527633028},
 {'bizesId': '11930382',
  'bizesNm': '맥칸백암치킨',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '45',
  'ctprvnNm': '전라북도',
  'signguCd': '45140',
  'signguNm': '익산시',
  'adongCd': '4514040000',
  'adongNm': '금마면',
  'ldongCd': '4514040021',
  'ldongNm': '금마면',
  'lnoCd': '4514040021108610001',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 861,
  'lnoSlno': 1,
  'lnoAdr': '전라북도 익산시 금마면 동고도리 861-1',
  'rdnmCd': '451404607150',
  'rdnm': '전라북도 익산시 금마면 금마길',
  'bldMnno': 48,
  'bldSlno': '',

# pandas의 json_normalize를 이용해서 쉽게 json에서 DataFrame으로 만들기

In [63]:
pd.json_normalize(data[i]['body']['items'])

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,11927910,흥부네대박닭강정난곡점,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1162010200106680000009515,,서울특별시 관악구 난곡로 87,151015,08859,,1,,126.918788,37.463206
1,11928045,또봉이통닭동산남부점,동산남부점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4514011100106090031083264,,전라북도 익산시 평동로12길 21,570959,54676,,1,,126.958748,35.927144
2,11928103,원조옛날통닭,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4415010400100010003753599,,충청남도 공주시 무령로 274,314050,32562,,1,,127.130101,36.455689
3,11928271,해피오네치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4146510300108830007027115,,경기도 용인시 수지구 문인로54번길 7,448504,16828,,1,,127.096606,37.333755
4,11928279,옛날통닭,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4128710100109660074003593,,경기도 고양시 일산서구 원일로 23,411310,10348,,1,,126.765010,37.687351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,12077761,굽네치킨,용곡점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4413111500104820016021351,더쉴아파트,충청남도 천안시 동남구 새말1길 47,330250,31184,,1,,127.131872,36.788981
996,12077835,다감옛날통닭화천점,화천점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4279025022100990007000001,CAFFELATERRE,강원도 화천군 화천읍 상승로 51-3,209804,24121,,1,,127.704553,38.105558
997,12078004,대박치킨,영주남산점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4721011100111870064000001,영주한우직판장,경상북도 영주시 구성로142번길 7,750120,36155,,,,128.629486,36.806092
998,12078087,바른치킨청라연희점,청라연희점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2826010600108060009000001,,인천광역시 서구 청라에메랄드로 49,404180,22740,,1,,126.656246,37.529494
999,12078171,맘스터치,혁신도시점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011700118860002000001,,강원도 원주시 혁신로 55,220170,26465,,,,127.980420,37.323433