In [1]:
import pandas as pd

In [2]:
pd.read_csv()

TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'

In [3]:
# dataframe
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}
countries = pd.DataFrame(data)
countries = countries.set_index('country') # 인덱스 지정
countries

                population    area    capital
country
Belgium               11.3   30510   Brussels
France                64.3  671308      Paris
Germany               81.3  357050     Berlin
Netherlands           16.9   41526  Amsterdam
United Kingdom        64.9  244820     London

In [4]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Belgium to United Kingdom
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  5 non-null      float64
 1   area        5 non-null      int64
 2   capital     5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

---

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도를 의미하는 `density` 칼럼을 추가하세요. (주의: 현재 'population' 칼럼은 100만 단위로 표기되어 있습니다)  
  
</div>

In [7]:
countries['density']=countries['population']*1000000 / countries['area']
countries

                population    area    capital     density
country
Belgium               11.3   30510   Brussels  370.370370
France                64.3  671308      Paris   95.783158
Germany               81.3  357050     Berlin  227.699202
Netherlands           16.9   41526  Amsterdam  406.973944
United Kingdom        64.9  244820     London  265.092721

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도가 300을 초과하는 국가(country)의 수도(capital)과 인구(population)을 선택해주세요.  
  
</div>

In [10]:
countries.loc[countries['density']>300, ['capital','population']]

               capital  population
country
Belgium       Brussels        11.3
Netherlands  Amsterdam        16.9

In [11]:
countries[countries['density']>300]['capital']['population']

KeyError: 'population'

<div class="alert alert-success">
    <b>EXERCISE</b>: 'density_ratio' 칼럼을 추가해주세요. (density_ratio = 인구밀도/평균 인구밀도)
</div>

In [12]:
countries['density'].mean()

np.float64(273.1838790074409)

In [14]:
countries['density_ratio']=countries['density'] / countries['density'].mean()
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 영국(United Kingdom)의 수도(capital)를 'Cambridge'로 변경해주세요.
</div>

In [16]:
countries.loc['United Kingdom', 'capital']='Cambridge'
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

In [19]:
countries.iloc[4,2]='London'
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구 밀도가 100 초과, 300 미만인 국가들을 표시해주세요.  
</div>

In [20]:
countries[(countries['density'] > 100) & (countries['density']<300)]

                population    area capital     density  density_ratio
country
Germany               81.3  357050  Berlin  227.699202       0.833502
United Kingdom        64.9  244820  London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도가 7글자 이상인 국가들을 표시해주세요. (힌트: string의 len( )를 사용하세요.)
</div>

In [24]:
countries[countries['capital'].str.len() >= 7]

             population   area    capital     density  density_ratio
country
Belgium            11.3  30510   Brussels  370.370370       1.355755
Netherlands        16.9  41526  Amsterdam  406.973944       1.489744

In [26]:
countries['cap_len']=countries['capital'].apply(len)
countries=countries[countries['cap_len']>=7]
countries

             population   area    capital     density  density_ratio  cap_len
country
Belgium            11.3  30510   Brussels  370.370370       1.355755        8
Netherlands        16.9  41526  Amsterdam  406.973944       1.489744        9

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도에 'am' 이 포함되는 국가들을 표시해주세요. (힌트: string의 contains( )를 사용하세요.)
</div>

In [28]:
countries[countries['capital'].str.contains("am")]

             population   area    capital     density  density_ratio  cap_len
country
Netherlands        16.9  41526  Amsterdam  406.973944       1.489744        9

# 영화리뷰 데이터에서 자료 찾기

movie_title_data.tsv 읽어오기

https://drive.google.com/file/d/1cvBtLVyfhfodJK-BXWqBLcopyus9HOIc/view?usp=sharing

<div class="alert alert-success">
    <b>EXERCISE</b>: titles 데이터프레임에는 몇 개의 영화가 기록되어 있나요?
</div>

In [30]:
titles=pd.read_csv("./data/movie_title_data.tsv", delimiter="\t")

FileNotFoundError: [Errno 2] No such file or directory: './data/movie_title_data.tsv'

In [ ]:
titles.head()

In [31]:
titles.info(show_counts=True)

NameError: name 'titles' is not defined

In [ ]:
# 데이터 행의 개수
len(titles)

<div class="alert alert-success">
    <b>EXERCISE</b>: titles에서 가장 빠른 시기에 제작된 영화 두 개를 표시하세요.  힌트: .sort_values()
</div>

In [32]:
newline_index=titles[titles['startYear'] =="\\N"].index

NameError: name 'titles' is not defined

In [ ]:
titles.loc[titles['startYear'] =="\\N", 'startYear']=0

In [ ]:
titles.loc[newline_index]

In [ ]:
titles['startYear']=titles['startYear'].astype(int)

In [ ]:
titles['startYear'].dtype

In [ ]:
titles[titles['startYear'] !=0].sort_values(by='startYear').head(2)

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(originalTitle)이 "Hamlet"인 영화는 몇 개가 있나요?
</div>

In [ ]:
titles[titles['originalTitle'].isna()==False].str.contains("Hamlet")

In [ ]:
no_na_titles=titles[titles['originalTitle'].isna()==False]
len(no_na_titles[no_na_titles['originalTitle'].str.contains("Hamlet")])

In [ ]:
no_na_titles['originalTitle']="Hamlet"

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(originalTitle)이 "Treasure Island"인 영화를 제작년도(startYear)의 오름차순에 따라 표시하세요
</div>

In [33]:
titles[(titles['originalTitle'] == 'Treasure Island')& titles['startYear']!=0)].sort_values(by="startYear")

NameError: name 'titles' is not defined

<div class="alert alert-success">
    <b>EXERCISE</b>: 1950년에서 1959년 사이 몇 개의 영화가 만들어졌나요?(1950 <= 제작년도 <= 1959)
</div>

In [ ]:
len(titles[(titles['startYear']>=1950) & (titles['startYear']<=1959)])

# 타이타닉 자료에서 그룹별 연산하기

원격 DB에 접속해서 titanic 데이터베이스 안에 있는 p_info, t_info, survived 테이블을 불러와 합치고 아래의 문제를 풀어보세요.<br>
<id:kict00, pw:kict00, ip:221.155.18.165:3306, db:titanic>

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 상위 5개 행을 출력하세요.
</div>

In [34]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb
engine=create_engine("mysql+pymysql://user:password@localhost:3306/titanic")
conn=engine.connect()
p_info=pd.read_sql("p_info", con=conn)
t_info=pd.read_sql("t_info", con=conn)
survived=pd.read_sql("survived", con=conn)
conn.close()

RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

In [ ]:
data=pd.merge(p_info, t_info, how='inner', on="PassengerId")
data=pd.merge9data, survived, how='inner', on='PassengerId'

In [ ]:
data.head()

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 정보(info)를 출력하세요.
</div>

In [ ]:
data.info()

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 기술통계(describe)를 확인하세요.
</div>

In [ ]:
data.describe(include=all)

<div class="alert alert-success">
    <b>EXERCISE</b>: 처음 100명의 데이터를 출력하세요.
</div>

In [ ]:
data.loc[:99,:]

In [ ]:
data.iloc[:100, :]

In [ ]:
pd.set_option('display.max_rows', 100)
data.head(100)

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스가 10~20인 데이터를 출력하세요.
</div>

In [ ]:
data.loc[10:20, : ]

<div class="alert alert-success">
    <b>EXERCISE</b>: 컬럼 이름을 모두 출력하세요.
</div>

In [ ]:
data.columns

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 shape를 확인하세요.
</div>

In [ ]:
data.shape

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age' 컬럼의 평균을 구하세요.
</div>

In [ ]:
data['Age'].mean()

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Survived' 컬럼의 고유값을 확인하세요.
</div>

In [ ]:
data['Survived'].unique

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 30 이상인 승객만 출력하세요.
</div>

In [ ]:
data['Age']>=30

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별이 'female'이고 생존한 승객만 출력하세요.
</div>

In [ ]:
data[(data['Sex']=='female')&(data['Survived']==1)]

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 10살 이하이고 요금이 20 이상인 승객을 출력하세요.
</div>

In [ ]:
data[(data['Age']<=10) & (data['Fare']>=20)]

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 결측치인 데이터를 출력하세요.
</div>

In [ ]:
data[data['Age'].isna()==True]

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이를 기준으로 오름차순 정렬하세요.
</div>

In [ ]:
data[data['Age'].isna() == False].sort_values(by='Age')

In [ ]:
data.sort_values(by="Age")

<div class="alert alert-success">
    <b>EXERCISE</b>: 요금을 기준으로 내림차순 정렬하고 상위 5명만 출력하세요.
</div>

In [ ]:
data['Fare'].sort_values(by='Fare', ascending=False)[:5]

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별로 그룹화하여 생존률 평균을 구하세요.
</div>

In [35]:
data[['Sex','Survived']].groupby('Sex').mean()

TypeError: unhashable type: 'list'

<div class="alert alert-success">
    <b>EXERCISE</b>: Pclass별 평균 나이를 구하세요.
</div>

In [ ]:
data[['Pclass','Age']].groupby('Pclass').mean()

In [ ]:
data.groupby('Pclass')[[Age']].mean()

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'에 10을 더한 값을 새로운 컬럼 'Age_plus_10'으로 추가하세요.
</div>

In [ ]:
data['Age_plus_10']=data['Age']+10
data

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'가 18 이상이면 '성인', 아니면 '미성년'으로 분류하는 컬럼을 추가하세요.
</div>

In [ ]:
data['isAdult']=data['Age'].apply(lambda x:"성인" if x > =18 else "미성년")

In [ ]:
data['Age'].apply(lambda x:np.where(x>=18,"성인","미성년"))

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'의 결측치를 평균으로 채우세요.
</div>

In [ ]:
age_na_index=data[data['Age'].isna()].index

In [ ]:
data['Age'].mean()

In [ ]:
data['Age']=data['Age'].fillna(data['Age'].mean())

In [ ]:
data.loc[]

In [ ]:
data['Age'].isna().sum()

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Cabin' 컬럼의 결측치를 'Unknown'으로 채우세요.
</div>

In [ ]:
cabin_na_idx=data[data['Cabin'].isna()].index

In [ ]:
data['Cabin']=data['Cabin'].fillna('Unknown')

In [ ]:
data.loc[cabin_]

In [ ]:
data['Cabin'].isna().sum()

<div class="alert alert-success">
    <b>EXERCISE</b>: 중복된 'Ticket' 값을 제거하고 몇 개가 남는지 출력하세요.
</div>

In [ ]:
data['Ticket'].duplicated()

In [ ]:
daata=data.drop_duplicates(subset='Ticket')
data['Ticket'].duplicated().sum()

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Embarked' 컬럼의 고유값과 각각의 개수를 출력하세요.
</div>

In [ ]:
data['Embarked'].value_counts()

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 'PassengerId'로 설정하세요.
</div>

In [ ]:
data=data.set_index('PassengerId')
data

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 초기화하세요.
</div>

In [ ]:
data=data.reset_index()
data

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별과 Pclass의 생존률을 피벗 테이블로 만드세요.
</div>

In [ ]:
data.pivot_table(values='Survived', index='Pclass', columns='Sex')

In [ ]:
data.pivot_table(values='Survived', index='Sex', columns='Pclass')

<div class="alert alert-success">
    <b>EXERCISE</b>: groupby()를 사용하여 각 성별(sex)의 평균 나이(age)를 구하세요.
</div>

In [ ]:
data[['Sex','Age']].groupby('Sex').mean()

<div class="alert alert-success">
    <b>EXERCISE</b>: 전체 승객(passenger)의 평균 생존율을 구하세요.
</div>

In [36]:
data['Survived'].mean()

KeyError: 'Survived'

In [ ]:
data['Survived'].sum()/len(data['Survived'])

<div class="alert alert-success">
    <b>EXERCISE</b>: 25세 이하 승객의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [ ]:
data.loc[data['Age']<=25, 'Survived'].mean()

<div class="alert alert-success">
    <b>EXERCISE</b>: 남성의 생존율을 구하세요. 여성의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [ ]:
print("남성의 생존율:", data.loc[data['Sex']=='male', 'Survived'].mean())
print("여성의 생존율:", data.loc[data['Sex']=='female', 'Survived'].mean())

In [ ]:
data['Sex','Survived'].grouby('Sex').mean()

<div class="alert alert-success">
    <b>EXERCISE</b>: 생존율을 구하는 함수가 작성되어 있습니다. 성별 생존율을 groupby를 활용해 구하기 위해 ?부분을 알맞게 채워주세요.
</div>

In [49]:
def survival_ratio(survived):
    return survived.sum() / len(survived)

In [ ]:
data[['Sex','Survived']].groupby('Sex').agg(['survival_ratio'])

In [ ]:
for i in sy_unique:
    print(i, type(i))

In [ ]:
countries['density']=countries['population']*1000000/countries['area']

In [ ]:
countries.loc[countries['density']>300]

In [ ]:
countries['density'].mean()

In [ ]:
countries.loc['United Kingdom', 'capital']='Cambridge'
countries

In [ ]:
countries.iloc[4,2]='London'

In [ ]:
countries[(countries['density']>100)& (coountries)]

In [ ]:
countries[countries['capital'].str.len()>=7]

In [ ]:
countries[countries['captial'].apply(len)>=7]

In [ ]:
countries['cap_len']=countries['captial'].apply(len)

In [ ]:
countries[countries['captial'].str.contains("am")]

In [ ]:
titles=pd.read_csv("./data/movie_title_data.tsv", delimiter="\t")

In [ ]:
# 숫자 + 문자이면 다 문자로 바꿔버림. unique 했는데 앞쪽에 공백이 있으면 공백 다 제거할 것
titles['startYear'].unique

In [ ]:
titles['startYear']=titles['startYear'].str.strip()

In [ ]:
len(titles)

In [ ]:
newline_index=titles[titles['startYear']=="\\N"].index

In [ ]:
titles['startYear']=titles['startYear'].astype(int)

In [ ]:
titles[titles['startYear']!=0].sort_values(by='startYear').head(2)

In [ ]:
#isna()->  결측값 찾는 함수
no_na_titles=titles[titles['or']]

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
p_info=pd.read_sql
conn.close()

In [ ]:
data=pd.merge(p_info, t_info, how='inner', on="PassengerId")

In [ ]:
data.head()

In [ ]:
data.info()

In [ ]:
data.describe()

In [ ]:
pd.set_option('display.max_rows',100)

In [ ]:
data.loc[10:20, :]

In [ ]:
data['Age'].mean()

In [ ]:
data[data['Age'].isna()]

In [ ]:
data.sort_values(by='Age')

In [ ]:
data.sort_values(by='Fare', ascending=False).head()

In [ ]:
data[['Sex','Survived']].groupby('Sex')

In [ ]:
data['Pclass','Age'].groupby('Pclass').mean()

In [ ]:
data['Age_plus_10']=data['Age']+10

In [ ]:
data['isAdult']=data['Age'].apply(lambda x)

In [ ]:
data['Age'].apply(lambda x:np.where(x>18))

In [ ]:
data['Age'].mean()

In [ ]:
data.loc[age_na_index]

In [ ]:
cabin_na_idx=data[data['Cabin'].isna()].index

In [ ]:
data[data['Ticket']].duplicated()

In [ ]:
data=data.drop_duplicates(subset='Ticket')
data['Ticket'].duplicated().sum()

In [ ]:
data['Embarked'].value

In [ ]:
data=data.set_index

In [ ]:
data.loc[data['Age']<=25, "Survived"].mean()

In [ ]:
data.loc[data['Sex']=='male','Survived'].mean()

In [ ]:
data['Sex','Survived']