In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import koreanize_matplotlib
import seaborn as sns

In [2]:
data=pd.read_csv("./data/salary2.csv")

In [3]:
data.head()

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K

In [4]:
data.describe()

                age  education-num  capital-gain  capital-loss  hours-per-week
count  48842.000000   48842.000000  48842.000000  48842.000000    48842.000000
mean      38.643585      10.078089   1079.067626     87.502314       40.422382
std       13.710510       2.570973   7452.019058    403.004552       12.391444
min       17.000000       1.000000      0.000000      0.000000        1.000000
25%       28.000000       9.000000      0.000000      0.000000       40.000000
50%       37.000000      10.000000      0.000000      0.000000       40.000000
75%       48.000000      12.000000      0.000000      0.000000       45.000000
max       90.000000      16.000000  99999.000000   4356.000000       99.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       46043 non-null  object
 2   education       48842 non-null  object
 3   education-num   48842 non-null  int64
 4   marital-status  48842 non-null  object
 5   occupation      46033 non-null  object
 6   relationship    48842 non-null  object
 7   race            48842 non-null  object
 8   sex             48842 non-null  object
 9   capital-gain    48842 non-null  int64
 10  capital-loss    48842 non-null  int64
 11  hours-per-week  48842 non-null  int64
 12  native-country  47985 non-null  object
 13  class           48842 non-null  object
dtypes: int64(5), object(9)
memory usage: 5.2+ MB

# 결측값 처리

In [6]:
data.isna().sum() / len(data) *100

age               0.000000
workclass         5.730724
education         0.000000
education-num     0.000000
marital-status    0.000000
occupation        5.751198
relationship      0.000000
race              0.000000
sex               0.000000
capital-gain      0.000000
capital-loss      0.000000
hours-per-week    0.000000
native-country    1.754637
class             0.000000
dtype: float64

In [7]:
data.columns

Index(['age', 'workclass', 'education', 'education-num', 'marital-status',
       'occupation', 'relationship', 'race', 'sex', 'capital-gain',
       'capital-loss', 'hours-per-week', 'native-country', 'class'],
      dtype='object')

In [8]:
data['native-country'].value_counts()

native-country
United-States                 43832
Mexico                          951
Philippines                     295
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Guatemala                        88
Poland                           87
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Nicaragua                        49
Greece                           49
Peru                             46
Ecuador                          45
France                           38
Ireland                          37
Thailand                         30
Hong                             30
Cambodia                         28
Trinadad&Tobago                  27
Laos                             23
Outlying-US(Guam-USVI-etc)       23
Yugoslavia                       23
Scotland                         21
Honduras                         20
Hungary                          19
Holand-Netherlands                1
Name: count, dtype: int64

In [9]:
data=data.drop(data[data['workclass'].isna()].index)

In [10]:
data=data.drop(data[data['occupation'].isna()].index)

In [11]:
data=data.drop(data[data['native-country'].isna()].index)

In [12]:
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
5,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [13]:
data['age'].describe()

count    45222.000000
mean        38.547941
std         13.217870
min         17.000000
25%         28.000000
50%         37.000000
75%         47.000000
max         90.000000
Name: age, dtype: float64

In [14]:
data['age'].value_counts()

age
36    1283
33    1279
31    1274
35    1272
23    1241
      ...
85       5
88       5
89       1
87       1
86       1
Name: count, Length: 74, dtype: int64

In [15]:
data['workclass'].value_counts()

workclass
Private             33307
Self-emp-not-inc     3796
Local-gov            3100
State-gov            1946
Self-emp-inc         1646
Federal-gov          1406
Without-pay            21
Name: count, dtype: int64

In [16]:
data['workclass'].info()

<class 'pandas.core.series.Series'>
Index: 45222 entries, 0 to 48841
Series name: workclass
Non-Null Count  Dtype
--------------  -----
45222 non-null  object
dtypes: object(1)
memory usage: 706.6+ KB

In [17]:
data['education'].value_counts()

education
HS-grad         14783
Some-college     9899
Bachelors        7570
Masters          2514
Assoc-voc        1959
11th             1619
Assoc-acdm       1507
10th             1223
7th-8th           823
Prof-school       785
9th               676
12th              577
Doctorate         544
5th-6th           449
1st-4th           222
Preschool          72
Name: count, dtype: int64

In [18]:
data['marital-status'].value_counts()

marital-status
Married-civ-spouse       21055
Never-married            14598
Divorced                  6297
Separated                 1411
Widowed                   1277
Married-spouse-absent      552
Married-AF-spouse           32
Name: count, dtype: int64

In [19]:
data['occupation'].value_counts()

occupation
Craft-repair         6020
Prof-specialty       6008
Exec-managerial      5984
Adm-clerical         5540
Sales                5408
Other-service        4808
Machine-op-inspct    2970
Transport-moving     2316
Handlers-cleaners    2046
Farming-fishing      1480
Tech-support         1420
Protective-serv       976
Priv-house-serv       232
Armed-Forces           14
Name: count, dtype: int64

In [20]:
data['relationship'].value_counts()

relationship
Husband           18666
Not-in-family     11702
Own-child          6626
Unmarried          4788
Wife               2091
Other-relative     1349
Name: count, dtype: int64

In [21]:
data['race'].value_counts()

race
White                 38903
Black                  4228
Asian-Pac-Islander     1303
Amer-Indian-Eskimo      435
Other                   353
Name: count, dtype: int64

In [22]:
data['sex'].value_counts()

sex
Male      30527
Female    14695
Name: count, dtype: int64

In [23]:
data['capital-gain'].value_counts()

capital-gain
0        41432
15024      498
7688       391
7298       351
99999      229
         ...
7262         1
1731         1
22040        1
1639         1
2387         1
Name: count, Length: 121, dtype: int64

In [24]:
data['capital-gain'].describe()

count    45222.000000
mean      1101.430344
std       7506.430084
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      99999.000000
Name: capital-gain, dtype: float64

In [25]:
data['capital-loss'].value_counts()

capital-loss
0       43082
1902      294
1977      246
1887      228
2415       68
        ...
4356        1
419         1
2080        1
155         1
2201        1
Name: count, Length: 97, dtype: int64

In [26]:
data['capital-loss'].describe()

count    45222.000000
mean        88.595418
std        404.956092
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       4356.000000
Name: capital-loss, dtype: float64

In [27]:
data['hours-per-week'].value_counts()

hours-per-week
40    21358
50     4094
45     2602
60     2085
35     1776
      ...
79        1
94        1
87        1
69        1
82        1
Name: count, Length: 96, dtype: int64

In [28]:
data['hours-per-week'].describe()

count    45222.000000
mean        40.938017
std         12.007508
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
Name: hours-per-week, dtype: float64

In [29]:
data['native-country'].value_counts()

native-country
United-States                 41292
Mexico                          903
Philippines                     283
Germany                         193
Puerto-Rico                     175
Canada                          163
India                           147
El-Salvador                     147
Cuba                            133
England                         119
China                           113
Jamaica                         103
South                           101
Italy                           100
Dominican-Republic               97
Japan                            89
Guatemala                        86
Vietnam                          83
Columbia                         82
Poland                           81
Haiti                            69
Portugal                         62
Iran                             56
Taiwan                           55
Greece                           49
Nicaragua                        48
Peru                             45
Ecuador                          43
Ireland                          36
France                           36
Thailand                         29
Hong                             28
Cambodia                         26
Trinadad&Tobago                  26
Yugoslavia                       23
Outlying-US(Guam-USVI-etc)       22
Laos                             21
Scotland                         20
Honduras                         19
Hungary                          18
Holand-Netherlands                1
Name: count, dtype: int64

In [30]:
data['native-country'].info()

<class 'pandas.core.series.Series'>
Index: 45222 entries, 0 to 48841
Series name: native-country
Non-Null Count  Dtype
--------------  -----
45222 non-null  object
dtypes: object(1)
memory usage: 706.6+ KB

In [31]:
data['class'].value_counts()

class
<=50K    34014
>50K     11208
Name: count, dtype: int64

In [32]:
data['age'].value_counts()

age
36    1283
33    1279
31    1274
35    1272
23    1241
      ...
85       5
88       5
89       1
87       1
86       1
Name: count, Length: 74, dtype: int64

In [33]:
data['age'].describe()

count    45222.000000
mean        38.547941
std         13.217870
min         17.000000
25%         28.000000
50%         37.000000
75%         47.000000
max         90.000000
Name: age, dtype: float64

In [34]:
data['age']=pd.cut(data['age'], bins=[10, 20, 30, 40, 50, 60, 70, 80, 90,100], 
       labels=['10s','20s','30s','40s','50s','60s','70s','80s','90s'],
    right=False)

In [35]:
data.head()

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,20s,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,30s,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,20s,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,40s,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
5,30s,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K

In [36]:
data.groupby(['age', 'class']).size()

C:\Users\Admin\AppData\Local\Temp\ipykernel_11704\483805188.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby(['age', 'class']).size()

age  class
10s  <=50K     2050
     >50K         2
20s  <=50K    10274
     >50K       719
30s  <=50K     8996
     >50K      3366
40s  <=50K     6425
     >50K      3880
50s  <=50K     3855
     >50K      2409
60s  <=50K     1828
     >50K       686
70s  <=50K      469
     >50K       120
80s  <=50K       83
     >50K        14
90s  <=50K       34
     >50K        12
dtype: int64

In [37]:
data['workclass'].value_counts()

workclass
Private             33307
Self-emp-not-inc     3796
Local-gov            3100
State-gov            1946
Self-emp-inc         1646
Federal-gov          1406
Without-pay            21
Name: count, dtype: int64

In [38]:
data.groupby(['workclass', 'class']).size()

workclass         class
Federal-gov       <=50K      857
                  >50K       549
Local-gov         <=50K     2185
                  >50K       915
Private           <=50K    26056
                  >50K      7251
Self-emp-inc      <=50K      734
                  >50K       912
Self-emp-not-inc  <=50K     2737
                  >50K      1059
State-gov         <=50K     1426
                  >50K       520
Without-pay       <=50K       19
                  >50K         2
dtype: int64

In [39]:
data['capital-gain'].describe()

count    45222.000000
mean      1101.430344
std       7506.430084
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      99999.000000
Name: capital-gain, dtype: float64

In [40]:
data['capital-gain'].value_counts()

capital-gain
0        41432
15024      498
7688       391
7298       351
99999      229
         ...
7262         1
1731         1
22040        1
1639         1
2387         1
Name: count, Length: 121, dtype: int64

In [41]:
len(data['capital-gain'])

45222

In [42]:
len(data['capital-loss'])

45222

In [43]:
len(data['age'])

45222

In [44]:
data['captial_change']=data['capital-gain']-data['capital-loss']

In [45]:
data=data.drop(['capital-gain','capital-loss'], axis=1)
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,class,captial_change
0,20s,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,40,United-States,<=50K,0
1,30s,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,50,United-States,<=50K,0
2,20s,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,40,United-States,>50K,0
3,40s,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,40,United-States,>50K,7688
5,30s,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,30,United-States,<=50K,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,20s,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,38,United-States,<=50K,0
48838,40s,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K,0
48839,50s,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,40,United-States,<=50K,0
48840,20s,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,20,United-States,<=50K,0
48841,50s,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,>50K,15024

In [46]:
data['sex'].value_counts()

sex
Male      30527
Female    14695
Name: count, dtype: int64

In [47]:
data['hours-per-week'].value_counts()

hours-per-week
40    21358
50     4094
45     2602
60     2085
35     1776
      ...
79        1
94        1
87        1
69        1
82        1
Name: count, Length: 96, dtype: int64

In [48]:
data['hours-per-week'].describe()

count    45222.000000
mean        40.938017
std         12.007508
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
Name: hours-per-week, dtype: float64

In [49]:
data['hours-per-week']=pd.cut(data['hours-per-week'], bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90,100], 
       labels=['under10h','10h','20h','30h','40h','50h','60h','70h','80h','90h'],
    right=False)
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,class,captial_change
0,20s,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,40h,United-States,<=50K,0
1,30s,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,50h,United-States,<=50K,0
2,20s,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,40h,United-States,>50K,0
3,40s,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,40h,United-States,>50K,7688
5,30s,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,30h,United-States,<=50K,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,20s,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,30h,United-States,<=50K,0
48838,40s,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40h,United-States,>50K,0
48839,50s,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,40h,United-States,<=50K,0
48840,20s,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,20h,United-States,<=50K,0
48841,50s,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,40h,United-States,>50K,15024

In [50]:
data['workclass'].value_counts()

workclass
Private             33307
Self-emp-not-inc     3796
Local-gov            3100
State-gov            1946
Self-emp-inc         1646
Federal-gov          1406
Without-pay            21
Name: count, dtype: int64

In [51]:
data['education'].value_counts()

education
HS-grad         14783
Some-college     9899
Bachelors        7570
Masters          2514
Assoc-voc        1959
11th             1619
Assoc-acdm       1507
10th             1223
7th-8th           823
Prof-school       785
9th               676
12th              577
Doctorate         544
5th-6th           449
1st-4th           222
Preschool          72
Name: count, dtype: int64

In [52]:
data.columns

Index(['age', 'workclass', 'education', 'education-num', 'marital-status',
       'occupation', 'relationship', 'race', 'sex', 'hours-per-week',
       'native-country', 'class', 'captial_change'],
      dtype='object')

# 문자데이터 숫자로 인코딩

In [53]:
data=pd.get_dummies(data, columns=['age', 'workclass', 'education', 'education-num', 'marital-status',
       'occupation', 'relationship', 'race', 'sex', 'hours-per-week',
       'native-country','captial_change'], drop_first=True)

In [54]:
data

,class,age_20s,age_30s,age_40s,age_50s,age_60s,age_70s,age_80s,age_90s,workclass_ Local-gov,...,captial_change_15831,captial_change_18481,captial_change_20051,captial_change_22040,captial_change_25124,captial_change_25236,captial_change_27828,captial_change_34095,captial_change_41310,captial_change_99999
0,<=50K,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,<=50K,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,>50K,True,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,>50K,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,<=50K,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,<=50K,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48838,>50K,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48839,<=50K,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48840,<=50K,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48841,>50K,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [55]:
X=data.drop('class', axis=1)
y=data['class']

In [56]:
X

,age_20s,age_30s,age_40s,age_50s,age_60s,age_70s,age_80s,age_90s,workclass_ Local-gov,workclass_ Private,...,captial_change_15831,captial_change_18481,captial_change_20051,captial_change_22040,captial_change_25124,captial_change_25236,captial_change_27828,captial_change_34095,captial_change_41310,captial_change_99999
0,True,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
5,False,True,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,True,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
48838,False,False,True,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
48839,False,False,False,True,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
48840,True,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
48841,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# 홀드아웃

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=10)

# 분석 모델 선택 및 분석

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

In [60]:
dtc=DecisionTreeClassifier(random_state=10)
dtc.fit(X_train, y_train)
pred=dtc.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8371047394412914
              precision    recall  f1-score   support

       <=50K       0.88      0.91      0.89     10167
        >50K       0.70      0.61      0.65      3400

    accuracy                           0.84     13567
   macro avg       0.79      0.76      0.77     13567
weighted avg       0.83      0.84      0.83     13567

In [61]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

       <=50K       0.88      0.91      0.89     10167
        >50K       0.70      0.61      0.65      3400

    accuracy                           0.84     13567
   macro avg       0.79      0.76      0.77     13567
weighted avg       0.83      0.84      0.83     13567

# Dataset2: 모든 컬럼을 다 넣고 분석해보기

In [62]:
data

,class,age_20s,age_30s,age_40s,age_50s,age_60s,age_70s,age_80s,age_90s,workclass_ Local-gov,...,captial_change_15831,captial_change_18481,captial_change_20051,captial_change_22040,captial_change_25124,captial_change_25236,captial_change_27828,captial_change_34095,captial_change_41310,captial_change_99999
0,<=50K,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,<=50K,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,>50K,True,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,>50K,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,<=50K,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,<=50K,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48838,>50K,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48839,<=50K,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48840,<=50K,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48841,>50K,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [64]:
data.columns

Index(['class', 'age_20s', 'age_30s', 'age_40s', 'age_50s', 'age_60s',
       'age_70s', 'age_80s', 'age_90s', 'workclass_ Local-gov',
       ...
       'captial_change_15831', 'captial_change_18481', 'captial_change_20051',
       'captial_change_22040', 'captial_change_25124', 'captial_change_25236',
       'captial_change_27828', 'captial_change_34095', 'captial_change_41310',
       'captial_change_99999'],
      dtype='object', length=339)

In [ ]:
X2= data.drop('class', axis=1)
X2=pd.get_dummies(X2, drop_first=True)

In [ ]:
X2_train, X2_test, y2_train, y2_test =train_test_split(X2, y, test_size=0.4, random_state=10)

In [ ]:
dtc2 = DecisionTreeClassifier(random_state=10)
dtc2.fit(X2_train, y2_train)
pred2=dtc2.predict(X2_test)
print(accuracy_score(y2_test, pred2))
print(classification_report(y2_test, pred2))

In [ ]:
for i in range(1,11):
    dtc2 = DecisionTreeClassifier(random_state=10)
    dtc2.fit(X2_train, y2_train)
    pred2=dtc2.predict(X2_test)
    print("="*30, "max_depth", i, "="*30)
    print(accuracy_score(y2_test, pred2))
    print(classification_report(y2_test, pred2))

In [ ]:
dtc2=

# 데이터 분석 모델의 성능평가

1. accuracy(정확도/정분류율): 1을 1이라고 맞추고, 0을 0이라고 맞춘 비율.
2. False Positive Rate(오분류율): 1을 0이라고 예측하고 0을 1이라고 예측해서 잘못 예측한 것
3. precision(정밀도): 예측한 것 중에서 실제로 맞은 것, 예측 postive 중에서 실제 positive 비율. 예측을 잘 함.
4. recall(재현율/민감도): 실제값을 실제값으로 잘 예측한 것, 실제 positive 중에서 예측 positive가 맞은 것. 실제 값을 잘 찾음.
5. f1-score: precision과 recall의 조화 평균. f1-score가 높다는 건 precision과 recall   모두 잘 작동한다는 뜻. 
6. Specificity(특이도): 실제 negative 중 예측에 성공할 비율

# Confusion Matrix(혼동행렬)
|              |  예측 Positive    |  예측 Negative     |
|--------------|-------------------|--------------------|
|실제 Positive | TP(True Positive) | FN(False Negative) |
|실제 Negative | FP(False Positive)| TN(True Negative)  |

* TP: 실제도 Positive, 예측도 Positive (실제 연봉 >5만, 예측 연봉 >5만)
* TN: 실제 Negative, 예측 Negative (실제 연봉 <=5만, 예측 연봉 <=5만)
* FP(1형 오류): 실제 Negative, 예측 Positive (실제 연봉 <=5만, 예측 연봉 >5만)
* FN(2형 오류): 실제 Positive, 예측 Negative (실제 연봉 > 5만, 예측 연봉 <= 5만)

* 정확도(accuracy_score): $ TP + TN \over TP+TN+FP+FN $
* 오분류율(FPR): $ FP+FN \over TP+TN+FP+FN $
* 정밀도(precision): $ TP \over TP+FP $
* 재현율/민감도(recall): $ TP \over TP+FN $
* 특이도(Specificity): $ TN \over FP+TN $
* F1-score: $  2 \cdot {Precision \cdot Recall \over Precision + Recall} $

In [63]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

       <=50K       0.88      0.91      0.89     10167
        >50K       0.70      0.61      0.65      3400

    accuracy                           0.84     13567
   macro avg       0.79      0.76      0.77     13567
weighted avg       0.83      0.84      0.83     13567

# EDA를 간편하게 하자
* ydata
* https://github.com/ydataai/ydata-profiling

In [65]:
from ydata_profiling import ProfileReport

C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [67]:
profile=ProfileReport(data, title="Profiling Report")

In [69]:
profile.to_file("salary2_eda.html")

Summarize dataset:   5%|▉                   | 16/344 [00:00<00:02, 110.78it/s, Describe variable: education_ Bachelors]
Summarize dataset:  12%|▎  | 40/344 [00:00<00:01, 168.05it/s, Describe variable: marital-status_ Married-spouse-absent]
Summarize dataset:  20%|████▎                 | 68/344 [00:00<00:01, 189.42it/s, Describe variable: hours-per-week_20h]
Summarize dataset:  26%|█████▎              | 91/344 [00:00<00:01, 199.38it/s, Describe variable: native-country_ Hong]
Summarize dataset:  34%|██████▌            | 118/344 [00:00<00:01, 194.60it/s, Describe variable: captial_change_-3683]
Summarize dataset:  43%|████████           | 147/344 [00:00<00:00, 213.97it/s, Describe variable: captial_change_-2149]
Summarize dataset:  51%|█████████▊         | 177/344 [00:00<00:00, 226.54it/s, Describe variable: captial_change_-1669]
Summarize dataset:  59%|███████████▎       | 204/344 [00:01<00:00, 214.76it/s, Describe variable: captial_change_-1258]
Summarize dataset:  66%|█████████████▎      | 228/344 [00:01<00:00, 214.96it/s, Describe variable: captial_change_1731]
Summarize dataset:  73%|██████████████▋     | 252/344 [00:01<00:00, 238.23it/s, Describe variable: captial_change_2635]
Summarize dataset:  80%|████████████████    | 276/344 [00:01<00:00, 197.35it/s, Describe variable: captial_change_3908]
Summarize dataset:  87%|█████████████████▎  | 298/344 [00:01<00:00, 189.10it/s, Describe variable: captial_change_6497]
Summarize dataset:  94%|█████████████████▉ | 325/344 [00:01<00:00, 211.99it/s, Describe variable: captial_change_22040]
100%|███████████████████████████████████████████████████████████████████████████████| 339/339 [00:01<00:00, 216.16it/s]
Summarize dataset:  99%|████████████████████████████████▌| 341/346 [00:39<00:00,  8.58it/s, Calculate auto correlation]

KeyboardInterrupt:

In [70]:
data2=pd.read_csv("./data/salary2.csv")

In [71]:
data2

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [72]:
profile=ProfileReport(data2, title="Profiling Report")

In [73]:
profile.to_file("salary2_eda.html")

Summarize dataset:   5%|██                                     | 1/19 [00:00<00:06,  2.78it/s, Describe variable: race]
Summarize dataset:  47%|██████████████████                    | 9/19 [00:00<00:01,  9.65it/s, Describe variable: class]
Summarize dataset:  74%|███████████████████████████▎         | 14/19 [00:01<00:00, 15.85it/s, Describe variable: class]
100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 28.77it/s]
Summarize dataset: 100%|████████████████████████████████████████████████████| 49/49 [00:06<00:00,  7.86it/s, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.74s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.87s/it]
Export report to file: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 93.79it/s]

y-data의 결과를 통해 데이터 전처리

In [75]:
data2=data2.dropna()
data2

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
5,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [77]:
data2[data2.duplicated()]

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
595,59,Private,HS-grad,9,Divorced,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
653,32,Private,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
741,40,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
864,24,Private,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,35,United-States,<=50K
1131,44,Private,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,60,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48784,47,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
48793,20,Private,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K
48808,22,Private,Some-college,10,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
48838,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48840,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [79]:
data2=data2.drop_duplicates()

In [80]:
data2.columns

Index(['age', 'workclass', 'education', 'education-num', 'marital-status',
       'occupation', 'relationship', 'race', 'sex', 'capital-gain',
       'capital-loss', 'hours-per-week', 'native-country', 'class'],
      dtype='object')

In [83]:
data2=data2.drop(["education","relationship"], axis=1)
data2

KeyError: "['education', 'relationship'] not found in axis"

In [84]:
data2=pd.get_dummies(data2, drop_first=True)
X3=data2.drop("class_ >50K", axis=1)
y3=data2['class_ >50K']

In [87]:
X3_train, X3_test, y3_train, y3_test= train_test_split(X3, y3, test_size=0.4, stratify=y3, random_state=10)

In [90]:
for i in range(1,31):
    dtc3 = DecisionTreeClassifier(random_state=10, max_depth=i)
    dtc3.fit(X3_train, y3_train)
    pred3=dtc3.predict(X3_test)
    print("="*30, "max_depth", i, "="*30)
    print(accuracy_score(y3_test, pred3))
    print(classification_report(y3_test, pred3))

============================== max_depth 1 ==============================
0.7457951070336392
              precision    recall  f1-score   support

       False       0.75      1.00      0.85     11706
        True       0.00      0.00      0.00      3990

    accuracy                           0.75     15696
   macro avg       0.37      0.50      0.43     15696
weighted avg       0.56      0.75      0.64     15696

============================== max_depth 2 ==============================
0.8162589194699287

C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

       False       0.83      0.94      0.88     11706
        True       0.73      0.44      0.55      3990

    accuracy                           0.82     15696
   macro avg       0.78      0.69      0.72     15696
weighted avg       0.81      0.82      0.80     15696

============================== max_depth 3 ==============================
0.8333333333333334
              precision    recall  f1-score   support

       False       0.85      0.94      0.89     11706
        True       0.75      0.51      0.61      3990

    accuracy                           0.83     15696
   macro avg       0.80      0.73      0.75     15696
weighted avg       0.83      0.83      0.82     15696

============================== max_depth 4 ==============================
0.8336518858307849
              precision    recall  f1-score   support

       False       0.85      0.94      0.89     11706
        True       0.75      0.51      0.61      3990

    accuracy                           0.83     15696
   macro avg       0.80      0.73      0.75     15696
weighted avg       0.83      0.83      0.82     15696

============================== max_depth 5 ==============================
0.8418068297655453
              precision    recall  f1-score   support

       False       0.85      0.95      0.90     11706
        True       0.78      0.52      0.63      3990

    accuracy                           0.84     15696
   macro avg       0.82      0.74      0.76     15696
weighted avg       0.84      0.84      0.83     15696

============================== max_depth 6 ==============================
0.8435907237512742
              precision    recall  f1-score   support

       False       0.85      0.95      0.90     11706
        True       0.79      0.52      0.63      3990

    accuracy                           0.84     15696
   macro avg       0.82      0.74      0.77     15696
weighted avg       0.84      0.84      0.83     15696

============================== max_depth 7 ==============================
0.845756880733945
              precision    recall  f1-score   support

       False       0.86      0.95      0.90     11706
        True       0.79      0.54      0.64      3990

    accuracy                           0.85     15696
   macro avg       0.82      0.75      0.77     15696
weighted avg       0.84      0.85      0.84     15696

============================== max_depth 8 ==============================
0.8476681957186545
              precision    recall  f1-score   support

       False       0.87      0.93      0.90     11706
        True       0.75      0.60      0.67      3990

    accuracy                           0.85     15696
   macro avg       0.81      0.77      0.78     15696
weighted avg       0.84      0.85      0.84     15696

============================== max_depth 9 ==============================
0.8486875637104995
              precision    recall  f1-score   support

       False       0.87      0.94      0.90     11706
        True       0.77      0.58      0.66      3990

    accuracy                           0.85     15696
   macro avg       0.82      0.76      0.78     15696
weighted avg       0.84      0.85      0.84     15696

============================== max_depth 10 ==============================
0.8467125382262997
              precision    recall  f1-score   support

       False       0.87      0.94      0.90     11706
        True       0.76      0.59      0.66      3990

    accuracy                           0.85     15696
   macro avg       0.81      0.76      0.78     15696
weighted avg       0.84      0.85      0.84     15696

============================== max_depth 11 ==============================
0.8466488277268094
              precision    recall  f1-score   support

       False       0.87      0.94      0.90     11706
        True       0.76      0.58      0.66      3990

    accuracy                           0.85     15696
   macro avg       0.81      0.76      0.78     15696
weighted avg       0.84      0.85      0.84     15696

============================== max_depth 12 ==============================
0.8442278287461774
              precision    recall  f1-score   support

       False       0.87      0.94      0.90     11706
        True       0.75      0.58      0.65      3990

    accuracy                           0.84     15696
   macro avg       0.81      0.76      0.78     15696
weighted avg       0.84      0.84      0.84     15696

============================== max_depth 13 ==============================
0.8461391437308868
              precision    recall  f1-score   support

       False       0.87      0.93      0.90     11706
        True       0.75      0.59      0.66      3990

    accuracy                           0.85     15696
   macro avg       0.81      0.76      0.78     15696
weighted avg       0.84      0.85      0.84     15696

============================== max_depth 14 ==============================
0.8446100917431193
              precision    recall  f1-score   support

       False       0.87      0.93      0.90     11706
        True       0.75      0.59      0.66      3990

    accuracy                           0.84     15696
   macro avg       0.81      0.76      0.78     15696
weighted avg       0.84      0.84      0.84     15696

============================== max_depth 15 ==============================
0.8419979612640163
              precision    recall  f1-score   support

       False       0.87      0.93      0.90     11706
        True       0.74      0.58      0.65      3990

    accuracy                           0.84     15696
   macro avg       0.80      0.76      0.77     15696
weighted avg       0.84      0.84      0.84     15696

============================== max_depth 16 ==============================
0.8393858307849134
              precision    recall  f1-score   support

       False       0.87      0.93      0.90     11706
        True       0.73      0.58      0.65      3990

    accuracy                           0.84     15696
   macro avg       0.80      0.75      0.77     15696
weighted avg       0.83      0.84      0.83     15696

============================== max_depth 17 ==============================
0.8337155963302753
              precision    recall  f1-score   support

       False       0.88      0.90      0.89     11706
        True       0.69      0.64      0.66      3990

    accuracy                           0.83     15696
   macro avg       0.78      0.77      0.78     15696
weighted avg       0.83      0.83      0.83     15696

============================== max_depth 18 ==============================
0.8339704383282365
              precision    recall  f1-score   support

       False       0.88      0.90      0.89     11706
        True       0.69      0.64      0.66      3990

    accuracy                           0.83     15696
   macro avg       0.78      0.77      0.78     15696
weighted avg       0.83      0.83      0.83     15696

============================== max_depth 19 ==============================
0.8326325178389399
              precision    recall  f1-score   support

       False       0.88      0.90      0.89     11706
        True       0.68      0.64      0.66      3990

    accuracy                           0.83     15696
   macro avg       0.78      0.77      0.77     15696
weighted avg       0.83      0.83      0.83     15696

============================== max_depth 20 ==============================
0.8297018348623854
              precision    recall  f1-score   support

       False       0.87      0.91      0.89     11706
        True       0.69      0.59      0.64      3990

    accuracy                           0.83     15696
   macro avg       0.78      0.75      0.76     15696
weighted avg       0.82      0.83      0.82     15696

============================== max_depth 21 ==============================
0.8295744138634047
              precision    recall  f1-score   support

       False       0.87      0.90      0.89     11706
        True       0.68      0.61      0.65      3990

    accuracy                           0.83     15696
   macro avg       0.78      0.76      0.77     15696
weighted avg       0.82      0.83      0.83     15696

============================== max_depth 22 ==============================
0.8300203873598369
              precision    recall  f1-score   support

       False       0.88      0.89      0.89     11706
        True       0.67      0.65      0.66      3990

    accuracy                           0.83     15696
   macro avg       0.78      0.77      0.77     15696
weighted avg       0.83      0.83      0.83     15696

============================== max_depth 23 ==============================
0.8234582059123343
              precision    recall  f1-score   support

       False       0.88      0.88      0.88     11706
        True       0.65      0.65      0.65      3990

    accuracy                           0.82     15696
   macro avg       0.77      0.77      0.77     15696
weighted avg       0.82      0.82      0.82     15696

============================== max_depth 24 ==============================
0.8194444444444444
              precision    recall  f1-score   support

       False       0.87      0.88      0.88     11706
        True       0.65      0.63      0.64      3990

    accuracy                           0.82     15696
   macro avg       0.76      0.76      0.76     15696
weighted avg       0.82      0.82      0.82     15696

============================== max_depth 25 ==============================
0.8174694189602446
              precision    recall  f1-score   support

       False       0.87      0.88      0.88     11706
        True       0.65      0.62      0.63      3990

    accuracy                           0.82     15696
   macro avg       0.76      0.75      0.76     15696
weighted avg       0.82      0.82      0.82     15696

============================== max_depth 26 ==============================
0.816322629969419
              precision    recall  f1-score   support

       False       0.87      0.88      0.88     11706
        True       0.64      0.62      0.63      3990

    accuracy                           0.82     15696
   macro avg       0.76      0.75      0.76     15696
weighted avg       0.81      0.82      0.82     15696

============================== max_depth 27 ==============================
0.8152395514780836
              precision    recall  f1-score   support

       False       0.87      0.88      0.88     11706
        True       0.64      0.62      0.63      3990

    accuracy                           0.82     15696
   macro avg       0.76      0.75      0.75     15696
weighted avg       0.81      0.82      0.81     15696

============================== max_depth 28 ==============================
0.8139653414882773
              precision    recall  f1-score   support

       False       0.87      0.88      0.88     11706
        True       0.64      0.61      0.63      3990

    accuracy                           0.81     15696
   macro avg       0.75      0.75      0.75     15696
weighted avg       0.81      0.81      0.81     15696

============================== max_depth 29 ==============================
0.8105249745158002
              precision    recall  f1-score   support

       False       0.87      0.88      0.87     11706
        True       0.63      0.61      0.62      3990

    accuracy                           0.81     15696
   macro avg       0.75      0.74      0.75     15696
weighted avg       0.81      0.81      0.81     15696

============================== max_depth 30 ==============================
0.8108435270132518
              precision    recall  f1-score   support

       False       0.87      0.88      0.87     11706
        True       0.63      0.61      0.62      3990

    accuracy                           0.81     15696
   macro avg       0.75      0.74      0.75     15696
weighted avg       0.81      0.81      0.81     15696

In [ ]:
len(data)

# 배깅, 부스팅, 랜덤배깅

# 배깅
* 데이터셋에서 복원추출방법으로 부트스트랩을 여러 개 만들고 각각의 부트스트랩을 분류기(의사결정나무)에 넣고 나온 결과를 다수결로 결정하는 방법.
* 독립된 부트스트랩, 독립된 모델로 결과 도출
* 투표를 통해서 결정

In [91]:
from sklearn.ensemble import BaggingClassifier

In [97]:
#estimator가 기본 10개 
est= DecisionTreeClassifier(max_depth=9, random_state=10)
bc=BaggingClassifier(estimator=est, n_estimators=100, n_jobs=4, random_state=10)
bc.fit(X_train, y_train)
pred=bc.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8488243532099948
              precision    recall  f1-score   support

       <=50K       0.87      0.93      0.90     10167
        >50K       0.75      0.59      0.66      3400

    accuracy                           0.85     13567
   macro avg       0.81      0.76      0.78     13567
weighted avg       0.84      0.85      0.84     13567

# 부스팅
* 처음 만든 부트스트랩을 분석한 후, 정답은 제외하고 틀린 것만 모아서 다시 부트스트랩 만들고 공부 후 틀린 것을 다시 공부하는 것.
* 점진적으로 성능이 향상되는 알고리즘
* XGBoost,LightGBM, Catboost

In [98]:
from sklearn.ensemble import AdaBoostClassifier

In [101]:
# n_estimators=100, 틀린 걸 100번 학습했다고 보면 됨
# learning_rate는 공부를 얼마나 촘촘히 할거냐
abc=AdaBoostClassifier(n_estimators=100, learning_rate= 0.5, random_state=10)
abc.fit(X_train, y_train)
pred=abc.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8228053364782192
              precision    recall  f1-score   support

       <=50K       0.84      0.95      0.89     10167
        >50K       0.74      0.45      0.56      3400

    accuracy                           0.82     13567
   macro avg       0.79      0.70      0.72     13567
weighted avg       0.81      0.82      0.81     13567

In [103]:
from sklearn.ensemble import GradientBoostingClassifier

In [104]:
gbc=GradientBoostingClassifier(n_estimators=100, random_state=10)
gbc.fit(X_train, y_train)
pred=gbc.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8528783076582885
              precision    recall  f1-score   support

       <=50K       0.87      0.95      0.91     10167
        >50K       0.79      0.56      0.66      3400

    accuracy                           0.85     13567
   macro avg       0.83      0.76      0.78     13567
weighted avg       0.85      0.85      0.84     13567

# XGBOOST
* 병렬연산이 가능해서 처리 속도가 매우 빨라짐
* 외부에서 만들어졌기 때문에 따로 설치 필요

In [106]:
from xgboost import XGBClassifier

In [108]:
for i in range(1,20):
    xgb=XGBClassifier(max_depth=i, n_estimators=100, random_state=10)
    xgb.fit(X_train, y_train)
    pred=xgb.predict(X_test)
    print(i)
    print(accuracy_score(y_test, pred))
    print(classification_report(y_test, pred))

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got [' <=50K' ' >50K']

In [ ]:
%%time
xgb=XGBClassifier(max_depth=8, n_estimators=100, random_state=10)
xgb.fit(X_train, y_train)
pred=xgb.predict(X_test)
print(i)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

# LightGBM
* xgboost보다 속도를 더 빠르게
* 비대칭 트리를 만듦.

In [111]:
from lightgbm import LGBMClassifier

In [113]:
%%time
lgbm=LGBMClassifier(max_depth=8, n_estimators=100, n_jobs=10, random_state=10)
lgbm.fit(X_train, y_train)
pred=lgbm.predict(X_test)
print(i)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 7808, number of negative: 23847
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007445 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 330
[LightGBM] [Info] Number of data points in the train set: 31655, number of used features: 165
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.246659 -> initscore=-1.116510
[LightGBM] [Info] Start training from score -1.116510
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
30
0.8611336330802682
              precision    recall  f1-score   support

       <=50K       0.88      0.95      0.91     10167
        >50K       0.79      0.60      0.69      3400

    accuracy                           0.86     13567
   macro avg       0.83      0.78      0.80     13567
weighted avg       0.86      0.86      0.85     13567

In [114]:
#Catboost는 카테고리 데이터에 특화되어 있음
from catboost import CatBoostClassifier

In [116]:
%%time
cbc=CatBoostClassifier(n_estimators=100, random_state=10)
cbc.fit(X_train, y_train)
pred=cbc.predict(X_test)
print(i)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

Learning rate set to 0.372068
0:	learn: 0.4607808	total: 150ms	remaining: 14.8s
1:	learn: 0.3980429	total: 165ms	remaining: 8.08s
2:	learn: 0.3807774	total: 175ms	remaining: 5.65s
3:	learn: 0.3636020	total: 185ms	remaining: 4.44s
4:	learn: 0.3543362	total: 197ms	remaining: 3.74s
5:	learn: 0.3445783	total: 210ms	remaining: 3.29s
6:	learn: 0.3395262	total: 223ms	remaining: 2.96s
7:	learn: 0.3336946	total: 237ms	remaining: 2.72s
8:	learn: 0.3300017	total: 248ms	remaining: 2.5s
9:	learn: 0.3262285	total: 260ms	remaining: 2.34s
10:	learn: 0.3234946	total: 271ms	remaining: 2.2s
11:	learn: 0.3199265	total: 285ms	remaining: 2.09s
12:	learn: 0.3174810	total: 295ms	remaining: 1.97s
13:	learn: 0.3162264	total: 305ms	remaining: 1.87s
14:	learn: 0.3145776	total: 315ms	remaining: 1.79s
15:	learn: 0.3129746	total: 327ms	remaining: 1.72s
16:	learn: 0.3118189	total: 340ms	remaining: 1.66s
17:	learn: 0.3099273	total: 352ms	remaining: 1.6s
18:	learn: 0.3083092	total: 362ms	remaining: 1.54s
19:	learn: 0.3066722	total: 385ms	remaining: 1.54s
20:	learn: 0.3052969	total: 400ms	remaining: 1.5s
21:	learn: 0.3038769	total: 414ms	remaining: 1.47s
22:	learn: 0.3030272	total: 424ms	remaining: 1.42s
23:	learn: 0.3019930	total: 434ms	remaining: 1.37s
24:	learn: 0.3006525	total: 444ms	remaining: 1.33s
25:	learn: 0.2999161	total: 454ms	remaining: 1.29s
26:	learn: 0.2991475	total: 464ms	remaining: 1.25s
27:	learn: 0.2983054	total: 473ms	remaining: 1.22s
28:	learn: 0.2971921	total: 483ms	remaining: 1.18s
29:	learn: 0.2963595	total: 493ms	remaining: 1.15s
30:	learn: 0.2955816	total: 502ms	remaining: 1.12s
31:	learn: 0.2946130	total: 511ms	remaining: 1.09s
32:	learn: 0.2938095	total: 521ms	remaining: 1.06s
33:	learn: 0.2929656	total: 529ms	remaining: 1.03s
34:	learn: 0.2919785	total: 537ms	remaining: 996ms
35:	learn: 0.2913936	total: 545ms	remaining: 969ms
36:	learn: 0.2898026	total: 554ms	remaining: 944ms
37:	learn: 0.2895364	total: 562ms	remaining: 917ms
38:	learn: 0.2890020	total: 574ms	remaining: 898ms
39:	learn: 0.2881505	total: 584ms	remaining: 876ms
40:	learn: 0.2874748	total: 592ms	remaining: 852ms
41:	learn: 0.2871645	total: 601ms	remaining: 830ms
42:	learn: 0.2865128	total: 612ms	remaining: 812ms
43:	learn: 0.2854060	total: 622ms	remaining: 792ms
44:	learn: 0.2848953	total: 631ms	remaining: 771ms
45:	learn: 0.2846762	total: 640ms	remaining: 752ms
46:	learn: 0.2845566	total: 650ms	remaining: 732ms
47:	learn: 0.2843320	total: 658ms	remaining: 713ms
48:	learn: 0.2838972	total: 667ms	remaining: 694ms
49:	learn: 0.2838291	total: 676ms	remaining: 676ms
50:	learn: 0.2832233	total: 685ms	remaining: 658ms
51:	learn: 0.2825530	total: 695ms	remaining: 641ms
52:	learn: 0.2824127	total: 705ms	remaining: 625ms
53:	learn: 0.2819707	total: 713ms	remaining: 607ms
54:	learn: 0.2816560	total: 723ms	remaining: 592ms
55:	learn: 0.2808048	total: 733ms	remaining: 576ms
56:	learn: 0.2804004	total: 743ms	remaining: 560ms
57:	learn: 0.2796213	total: 752ms	remaining: 544ms
58:	learn: 0.2791603	total: 760ms	remaining: 528ms
59:	learn: 0.2787323	total: 771ms	remaining: 514ms
60:	learn: 0.2786210	total: 779ms	remaining: 498ms
61:	learn: 0.2785189	total: 789ms	remaining: 483ms
62:	learn: 0.2784695	total: 798ms	remaining: 469ms
63:	learn: 0.2781436	total: 809ms	remaining: 455ms
64:	learn: 0.2778796	total: 819ms	remaining: 441ms
65:	learn: 0.2774969	total: 828ms	remaining: 427ms
66:	learn: 0.2774511	total: 838ms	remaining: 413ms
67:	learn: 0.2772728	total: 848ms	remaining: 399ms
68:	learn: 0.2765418	total: 859ms	remaining: 386ms
69:	learn: 0.2764605	total: 867ms	remaining: 372ms
70:	learn: 0.2763307	total: 877ms	remaining: 358ms
71:	learn: 0.2758705	total: 886ms	remaining: 345ms
72:	learn: 0.2753925	total: 895ms	remaining: 331ms
73:	learn: 0.2748674	total: 905ms	remaining: 318ms
74:	learn: 0.2747828	total: 914ms	remaining: 305ms
75:	learn: 0.2740825	total: 922ms	remaining: 291ms
76:	learn: 0.2740410	total: 930ms	remaining: 278ms
77:	learn: 0.2738022	total: 940ms	remaining: 265ms
78:	learn: 0.2735364	total: 949ms	remaining: 252ms
79:	learn: 0.2730901	total: 958ms	remaining: 240ms
80:	learn: 0.2725714	total: 969ms	remaining: 227ms
81:	learn: 0.2725080	total: 977ms	remaining: 214ms
82:	learn: 0.2720076	total: 985ms	remaining: 202ms
83:	learn: 0.2717214	total: 994ms	remaining: 189ms
84:	learn: 0.2716649	total: 1s	remaining: 177ms
85:	learn: 0.2712754	total: 1.01s	remaining: 165ms
86:	learn: 0.2706180	total: 1.03s	remaining: 154ms
87:	learn: 0.2704056	total: 1.04s	remaining: 142ms
88:	learn: 0.2699873	total: 1.06s	remaining: 131ms
89:	learn: 0.2695918	total: 1.07s	remaining: 119ms
90:	learn: 0.2694494	total: 1.08s	remaining: 107ms
91:	learn: 0.2690611	total: 1.09s	remaining: 94.6ms
92:	learn: 0.2687185	total: 1.1s	remaining: 82.7ms
93:	learn: 0.2684187	total: 1.11s	remaining: 70.9ms
94:	learn: 0.2683857	total: 1.12s	remaining: 58.9ms
95:	learn: 0.2682081	total: 1.13s	remaining: 47.1ms
96:	learn: 0.2679309	total: 1.14s	remaining: 35.2ms
97:	learn: 0.2678865	total: 1.15s	remaining: 23.4ms
98:	learn: 0.2677355	total: 1.16s	remaining: 11.7ms
99:	learn: 0.2673609	total: 1.17s	remaining: 0us
30
0.8666617527824869
              precision    recall  f1-score   support

       <=50K       0.88      0.95      0.91     10167
        >50K       0.80      0.63      0.70      3400

    accuracy                           0.87     13567
   macro avg       0.84      0.79      0.81     13567
weighted avg       0.86      0.87      0.86     13567

CPU times: total: 4.77 s
Wall time: 1.58 s

# 랜덤배깅(RandomForest)

In [117]:
from sklearn.ensemble import RandomForestClassifier

In [119]:
%%time
rfc=RandomForestClassifier(n_estimators=100, n_jobs=10, random_state=10)
rfc.fit(X_train, y_train)
pred=rfc.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

30
0.8437384830839537
              precision    recall  f1-score   support

       <=50K       0.88      0.92      0.90     10167
        >50K       0.72      0.61      0.66      3400

    accuracy                           0.84     13567
   macro avg       0.80      0.77      0.78     13567
weighted avg       0.84      0.84      0.84     13567

CPU times: total: 12.5 s
Wall time: 2.38 s

In [120]:
for i in range(1, 21):
    rfc=RandomForestClassifier(max_depth=i, n_estimators=100, n_jobs=10, random_state=10)
    rfc.fit(X_train, y_train)
    pred=rfc.predict(X_test)
    print(i)
    print(accuracy_score(y_test, pred))
    print(classification_report(y_test, pred))

1
0.7493919068327559
              precision    recall  f1-score   support

       <=50K       0.75      1.00      0.86     10167
        >50K       0.00      0.00      0.00      3400

    accuracy                           0.75     13567
   macro avg       0.37      0.50      0.43     13567
weighted avg       0.56      0.75      0.64     13567

C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2
0.7493919068327559
              precision    recall  f1-score   support

       <=50K       0.75      1.00      0.86     10167
        >50K       0.00      0.00      0.00      3400

    accuracy                           0.75     13567
   macro avg       0.37      0.50      0.43     13567
weighted avg       0.56      0.75      0.64     13567

C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

3
0.749981572934326
              precision    recall  f1-score   support

       <=50K       0.75      1.00      0.86     10167
        >50K       1.00      0.00      0.00      3400

    accuracy                           0.75     13567
   macro avg       0.87      0.50      0.43     13567
weighted avg       0.81      0.75      0.64     13567

4
0.7669344733544631
              precision    recall  f1-score   support

       <=50K       0.76      1.00      0.87     10167
        >50K       1.00      0.07      0.13      3400

    accuracy                           0.77     13567
   macro avg       0.88      0.54      0.50     13567
weighted avg       0.82      0.77      0.68     13567

5
0.7815287093683202
              precision    recall  f1-score   support

       <=50K       0.78      1.00      0.87     10167
        >50K       0.96      0.13      0.23      3400

    accuracy                           0.78     13567
   macro avg       0.87      0.57      0.55     13567
weighted avg       0.82      0.78      0.71     13567

6
0.800766565932041
              precision    recall  f1-score   support

       <=50K       0.79      0.99      0.88     10167
        >50K       0.89      0.23      0.37      3400

    accuracy                           0.80     13567
   macro avg       0.84      0.61      0.63     13567
weighted avg       0.82      0.80      0.75     13567

7
0.8054101864819047
              precision    recall  f1-score   support

       <=50K       0.80      0.99      0.88     10167
        >50K       0.91      0.25      0.39      3400

    accuracy                           0.81     13567
   macro avg       0.85      0.62      0.64     13567
weighted avg       0.83      0.81      0.76     13567

8
0.8228053364782192
              precision    recall  f1-score   support

       <=50K       0.82      0.98      0.89     10167
        >50K       0.85      0.35      0.50      3400

    accuracy                           0.82     13567
   macro avg       0.84      0.67      0.70     13567
weighted avg       0.83      0.82      0.79     13567

9
0.8275226652907791
              precision    recall  f1-score   support

       <=50K       0.83      0.98      0.89     10167
        >50K       0.84      0.38      0.53      3400

    accuracy                           0.83     13567
   macro avg       0.83      0.68      0.71     13567
weighted avg       0.83      0.83      0.80     13567

10
0.8376944055428613
              precision    recall  f1-score   support

       <=50K       0.84      0.97      0.90     10167
        >50K       0.82      0.45      0.58      3400

    accuracy                           0.84     13567
   macro avg       0.83      0.71      0.74     13567
weighted avg       0.84      0.84      0.82     13567

11
0.8433699417704724
              precision    recall  f1-score   support

       <=50K       0.85      0.96      0.90     10167
        >50K       0.82      0.48      0.61      3400

    accuracy                           0.84     13567
   macro avg       0.83      0.72      0.75     13567
weighted avg       0.84      0.84      0.83     13567

12
0.8435173582958649
              precision    recall  f1-score   support

       <=50K       0.85      0.96      0.90     10167
        >50K       0.81      0.49      0.61      3400

    accuracy                           0.84     13567
   macro avg       0.83      0.73      0.76     13567
weighted avg       0.84      0.84      0.83     13567

13
0.8444755657109162
              precision    recall  f1-score   support

       <=50K       0.85      0.96      0.90     10167
        >50K       0.80      0.50      0.62      3400

    accuracy                           0.84     13567
   macro avg       0.83      0.73      0.76     13567
weighted avg       0.84      0.84      0.83     13567

14
0.8467605218544999
              precision    recall  f1-score   support

       <=50K       0.85      0.96      0.90     10167
        >50K       0.81      0.51      0.62      3400

    accuracy                           0.85     13567
   macro avg       0.83      0.73      0.76     13567
weighted avg       0.84      0.85      0.83     13567

15
0.8491191862607799
              precision    recall  f1-score   support

       <=50K       0.86      0.96      0.91     10167
        >50K       0.81      0.52      0.63      3400

    accuracy                           0.85     13567
   macro avg       0.83      0.74      0.77     13567
weighted avg       0.84      0.85      0.84     13567

16
0.8492666027861723
              precision    recall  f1-score   support

       <=50K       0.86      0.96      0.90     10167
        >50K       0.81      0.52      0.64      3400

    accuracy                           0.85     13567
   macro avg       0.83      0.74      0.77     13567
weighted avg       0.84      0.85      0.84     13567

17
0.8496351440996536
              precision    recall  f1-score   support

       <=50K       0.86      0.96      0.90     10167
        >50K       0.80      0.53      0.64      3400

    accuracy                           0.85     13567
   macro avg       0.83      0.74      0.77     13567
weighted avg       0.84      0.85      0.84     13567

18
0.850961892828186
              precision    recall  f1-score   support

       <=50K       0.86      0.95      0.91     10167
        >50K       0.80      0.54      0.65      3400

    accuracy                           0.85     13567
   macro avg       0.83      0.75      0.78     13567
weighted avg       0.85      0.85      0.84     13567

19
0.8528045993955923
              precision    recall  f1-score   support

       <=50K       0.86      0.95      0.91     10167
        >50K       0.80      0.55      0.65      3400

    accuracy                           0.85     13567
   macro avg       0.83      0.75      0.78     13567
weighted avg       0.85      0.85      0.84     13567

20
0.8526571828701998
              precision    recall  f1-score   support

       <=50K       0.86      0.95      0.91     10167
        >50K       0.80      0.55      0.65      3400

    accuracy                           0.85     13567
   macro avg       0.83      0.75      0.78     13567
weighted avg       0.85      0.85      0.84     13567