In [92]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import seaborn as sns
from sklearnex import patch_sklearn
patch_sklearn()

ModuleNotFoundError: No module named 'sklearnex'

In [2]:
data=pd.read_csv("./data/fraud.csv")
data.head()

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [3]:
data.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud'],
      dtype='object')

In [4]:
data.describe()

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06
mean,4.173860e+17,7.006357e+01,4.881326e+04,3.853931e+01,-9.022783e+01,8.864367e+04,1.358674e+09,3.853898e+01,-9.022794e+01,5.210015e-03
std,1.309115e+18,1.592540e+02,2.688185e+04,5.071470e+00,1.374789e+01,3.014876e+05,1.819508e+07,5.105604e+00,1.375969e+01,7.199217e-02
min,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902742e+01,-1.666716e+02,0.000000e+00
25%,1.800429e+14,9.640000e+00,2.623700e+04,3.466890e+01,-9.679800e+01,7.410000e+02,1.343017e+09,3.474012e+01,-9.689944e+01,0.000000e+00
50%,3.521417e+15,4.745000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.443000e+03,1.357089e+09,3.936890e+01,-8.744069e+01,0.000000e+00
75%,4.642255e+15,8.310000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.374581e+09,4.195626e+01,-8.024511e+01,0.000000e+00
max,4.992346e+18,2.894890e+04,9.992100e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.388534e+09,6.751027e+01,-6.695090e+01,1.000000e+00

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1852394 entries, 0 to 1852393
Data columns (total 22 columns):
 #   Column                 Dtype
---  ------                 -----
 0   trans_date_trans_time  object
 1   cc_num                 int64
 2   merchant               object
 3   category               object
 4   amt                    float64
 5   first                  object
 6   last                   object
 7   gender                 object
 8   street                 object
 9   city                   object
 10  state                  object
 11  zip                    int64
 12  lat                    float64
 13  long                   float64
 14  city_pop               int64
 15  job                    object
 16  dob                    object
 17  trans_num              object
 18  unix_time              int64
 19  merch_lat              float64
 20  merch_long             float64
 21  is_fraud               int64
dtypes: float64(5), int64(5), object(12)
memory usage: 310.9+ MB

# 결측치, 중복값 확인

In [6]:
data.isna().sum() / len(data) * 100

trans_date_trans_time    0.0
cc_num                   0.0
merchant                 0.0
category                 0.0
amt                      0.0
first                    0.0
last                     0.0
gender                   0.0
street                   0.0
city                     0.0
state                    0.0
zip                      0.0
lat                      0.0
long                     0.0
city_pop                 0.0
job                      0.0
dob                      0.0
trans_num                0.0
unix_time                0.0
merch_lat                0.0
merch_long               0.0
is_fraud                 0.0
dtype: float64

In [7]:
data[data.duplicated()]

Empty DataFrame
Columns: [trans_date_trans_time, cc_num, merchant, category, amt, first, last, gender, street, city, state, zip, lat, long, city_pop, job, dob, trans_num, unix_time, merch_lat, merch_long, is_fraud]
Index: []

[0 rows x 22 columns]

In [8]:
data['unix_time']

0          1325376018
1          1325376044
2          1325376051
3          1325376076
4          1325376186
              ...
1852389    1388534347
1852390    1388534349
1852391    1388534355
1852392    1388534364
1852393    1388534374
Name: unix_time, Length: 1852394, dtype: int64

In [9]:
data=data.drop(['trans_date_trans_time'], axis=1)

In [10]:
data['cc_num']

0          2703186189652095
1              630423337322
2            38859492057661
3          3534093764340240
4           375534208663984
                 ...
1852389      30560609640617
1852390    3556613125071656
1852391    6011724471098086
1852392       4079773899158
1852393    4170689372027579
Name: cc_num, Length: 1852394, dtype: int64

In [11]:
data['cc_num'].value_counts()

cc_num
6538441737335434       4392
30270432095985         4392
4642255475285942       4386
6538891242532018       4386
4364010865167176       4386
                       ...
4352307151555405069       7
501894933032              7
4975457191020             7
6577777028615915          7
4295296907373             6
Name: count, Length: 999, dtype: int64

In [12]:
data['name']=data['first']+data['last']

In [13]:
data.head()

,cc_num,merchant,category,amt,first,last,gender,street,city,state,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,name
0,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,...,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,JenniferBanks
1,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,...,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,StephanieGill
2,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,...,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,EdwardSanchez
3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,...,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,JeremyWhite
4,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,...,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,TylerGarcia

In [14]:
data=data.drop(['first','last'], axis=1)

In [15]:
data['name'].value_counts

<bound method IndexOpsMixin.value_counts of 0          JenniferBanks
1          StephanieGill
2          EdwardSanchez
3            JeremyWhite
4            TylerGarcia
               ...
1852389     MichaelOlson
1852390      JoseVasquez
1852391        AnnLawson
1852392      EricPreston
1852393       SamuelFrey
Name: name, Length: 1852394, dtype: object>

In [16]:
data['name'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1852394 entries, 0 to 1852393
Series name: name
Non-Null Count    Dtype
--------------    -----
1852394 non-null  object
dtypes: object(1)
memory usage: 14.1+ MB

In [17]:
data['name'].describe()

count         1852394
unique            989
top       ScottMartin
freq             6583
Name: name, dtype: object

In [18]:
data[['street', 'city', 'state', 'zip']]

                               street            city state    zip
0                      561 Perry Cove  Moravian Falls    NC  28654
1        43039 Riley Greens Suite 393          Orient    WA  99160
2            594 White Dale Suite 530      Malad City    ID  83252
3         9443 Cynthia Court Apt. 038         Boulder    MT  59632
4                    408 Bradley Rest        Doe Hill    VA  24433
...                               ...             ...   ...    ...
1852389           558 Michael Estates           Luray    MO  63453
1852390           572 Davis Mountains    Lake Jackson    TX  77566
1852391    144 Evans Islands Apt. 683         Burbank    WA  99323
1852392    7020 Doyle Stream Apt. 951            Mesa    ID  83643
1852393      830 Myers Plaza Apt. 384          Edmond    OK  73034

[1852394 rows x 4 columns]

In [19]:
data[['lat','long']]

             lat      long
0        36.0788  -81.1781
1        48.8878 -118.2105
2        42.1808 -112.2620
3        46.2306 -112.1138
4        38.4207  -79.4629
...          ...       ...
1852389  40.4931  -91.8912
1852390  29.0393  -95.4401
1852391  46.1966 -118.9017
1852392  44.6255 -116.4493
1852393  35.6665  -97.4798

[1852394 rows x 2 columns]

In [20]:
from haversine import haversine, Unit

In [21]:
def calc_distance(row):
    home=(row['lat'], row['long'])
    store = (row['merch_lat'], row['merch_long'])
    return haversine(home, store, unit=Unit.KILOMETERS)

data['distance'] = data.apply(calc_distance, axis=1)

In [22]:
data.head()

,cc_num,merchant,category,amt,gender,street,city,state,zip,lat,...,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,name,distance
0,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,...,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,JenniferBanks,78.597677
1,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,...,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,StephanieGill,30.212217
2,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,...,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,EdwardSanchez,108.206232
3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,...,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,JeremyWhite,95.673363
4,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,...,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,TylerGarcia,77.556851

In [23]:
data['is_fraud']

0          0
1          0
2          0
3          0
4          0
          ..
1852389    0
1852390    0
1852391    0
1852392    0
1852393    0
Name: is_fraud, Length: 1852394, dtype: int64

In [24]:
data['is_fraud'].value_counts

<bound method IndexOpsMixin.value_counts of 0          0
1          0
2          0
3          0
4          0
          ..
1852389    0
1852390    0
1852391    0
1852392    0
1852393    0
Name: is_fraud, Length: 1852394, dtype: int64>

In [25]:
data['is_fraud'].describe()

count    1.852394e+06
mean     5.210015e-03
std      7.199217e-02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.000000e+00
Name: is_fraud, dtype: float64

In [26]:
data['is_fraud'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1852394 entries, 0 to 1852393
Series name: is_fraud
Non-Null Count    Dtype
--------------    -----
1852394 non-null  int64
dtypes: int64(1)
memory usage: 14.1 MB

In [27]:
data.loc[data['is_fraud']==1]

,cc_num,merchant,category,amt,gender,street,city,state,zip,lat,...,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,name,distance
2449,4613314721966,fraud_Rutherford-Mertz,grocery_pos,281.06,M,542 Steve Curve Suite 011,Collettsville,NC,28611,35.9946,...,885,Soil scientist,1988-09-15,e8a81877ae9a0a7f883e15cb39dc4022,1325466397,36.430124,-81.179483,1,JasonMurphy,68.953537
2472,340187018810220,"fraud_Jenkins, Hauck and Friesen",gas_transport,11.52,F,27954 Hall Mill Suite 575,San Antonio,TX,78208,29.4400,...,1595797,Horticultural consultant,1960-10-28,bc7d41c41103877b03232f03f1f8d3f5,1325468849,29.819364,-99.142791,1,MistyHart,78.406204
2523,340187018810220,fraud_Goodwin-Nitzsche,grocery_pos,276.31,F,27954 Hall Mill Suite 575,San Antonio,TX,78208,29.4400,...,1595797,Horticultural consultant,1960-10-28,b98f12f4168391b2203238813df5aa8c,1325473523,29.273085,-98.836360,1,MistyHart,41.012248
2546,4613314721966,fraud_Erdman-Kertzmann,gas_transport,7.03,M,542 Steve Curve Suite 011,Collettsville,NC,28611,35.9946,...,885,Soil scientist,1988-09-15,397894a5c4c02e3c61c784001f0f14e4,1325475483,35.909292,-82.091010,1,JasonMurphy,34.145841
2553,340187018810220,fraud_Koepp-Parker,grocery_pos,275.73,F,27954 Hall Mill Suite 575,San Antonio,TX,78208,29.4400,...,1595797,Horticultural consultant,1960-10-28,7863235a750d73a244c07f1fb7f0185a,1325476547,29.786426,-98.683410,1,MistyHart,44.209503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1813872,2242176657877538,"fraud_Willms, Kris and Bergnaum",shopping_pos,1041.51,M,1327 Rose Causeway Apt. 610,Senatobia,MS,38668,34.6323,...,14462,Database administrator,1959-03-03,35b0297dd026d2e9a75d024a5dec7955,1387749948,34.573471,-89.911011,1,TravisDaniel,6.945715
1813949,2242176657877538,fraud_Kuhn LLC,shopping_pos,868.09,M,1327 Rose Causeway Apt. 610,Senatobia,MS,38668,34.6323,...,14462,Database administrator,1959-03-03,da7f67d7375f10a054a3d919448c45dd,1387750687,34.091227,-90.390612,1,TravisDaniel,75.956610
1814016,2242176657877538,"fraud_Mosciski, Ziemann and Farrell",shopping_net,1039.42,M,1327 Rose Causeway Apt. 610,Senatobia,MS,38668,34.6323,...,14462,Database administrator,1959-03-03,25b076c7bcd70f272c1c5326bb234f4b,1387751508,34.628434,-90.284780,1,TravisDaniel,36.534723
1814204,2242176657877538,fraud_Bauch-Raynor,grocery_pos,289.27,M,1327 Rose Causeway Apt. 610,Senatobia,MS,38668,34.6323,...,14462,Database administrator,1959-03-03,2df7d894868fbc99ec1d8b055585fc9d,1387753563,34.746063,-90.401093,1,TravisDaniel,48.808516
1814246,2242176657877538,fraud_Jaskolski-Vandervort,misc_net,766.38,M,1327 Rose Causeway Apt. 610,Senatobia,MS,38668,34.6323,...,14462,Database administrator,1959-03-03,44292cbc51e37dc018ee6a988a4bc426,1387754019,33.771462,-90.651342,1,TravisDaniel,118.839211

In [28]:
data=data.drop(['lat','long','merch_lat','merch_long'], axis=1)

In [29]:
data.head()

,cc_num,merchant,category,amt,gender,street,city,state,zip,city_pop,job,dob,trans_num,unix_time,is_fraud,name,distance
0,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,561 Perry Cove,Moravian Falls,NC,28654,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,0,JenniferBanks,78.597677
1,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,43039 Riley Greens Suite 393,Orient,WA,99160,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,0,StephanieGill,30.212217
2,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,594 White Dale Suite 530,Malad City,ID,83252,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,0,EdwardSanchez,108.206232
3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,0,JeremyWhite,95.673363
4,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,408 Bradley Rest,Doe Hill,VA,24433,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,0,TylerGarcia,77.556851

In [30]:
data['address']=data['zip'].astype(str)+data['street']+data['city']+data['state']

In [31]:
data['address']

0                28654561 Perry CoveMoravian FallsNC
1          9916043039 Riley Greens Suite 393OrientWA
2          83252594 White Dale Suite 530Malad CityID
3          596329443 Cynthia Court Apt. 038BoulderMT
4                    24433408 Bradley RestDoe HillVA
                             ...
1852389              63453558 Michael EstatesLurayMO
1852390       77566572 Davis MountainsLake JacksonTX
1852391     99323144 Evans Islands Apt. 683BurbankWA
1852392        836437020 Doyle Stream Apt. 951MesaID
1852393        73034830 Myers Plaza Apt. 384EdmondOK
Name: address, Length: 1852394, dtype: object

In [32]:
data=data.drop(['zip','street','city','state'], axis=1)

In [33]:
data.columns

Index(['cc_num', 'merchant', 'category', 'amt', 'gender', 'city_pop', 'job',
       'dob', 'trans_num', 'unix_time', 'is_fraud', 'name', 'distance',
       'address'],
      dtype='object')

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1852394 entries, 0 to 1852393
Data columns (total 14 columns):
 #   Column     Dtype
---  ------     -----
 0   cc_num     int64
 1   merchant   object
 2   category   object
 3   amt        float64
 4   gender     object
 5   city_pop   int64
 6   job        object
 7   dob        object
 8   trans_num  object
 9   unix_time  int64
 10  is_fraud   int64
 11  name       object
 12  distance   float64
 13  address    object
dtypes: float64(2), int64(4), object(8)
memory usage: 197.9+ MB

In [35]:
data[['address','is_fraud']].groupby('address').count()

                                                    is_fraud
address
100189599 Washington Field Suite 238New York Ci...         7
100396278 Stephanie UnionsNew York CityNY               2195
10162022 Moore IslandNew York CityNY                     739
1028020938 Barbara ViaductNew York CityNY                739
1046304975 Allison ShoalBronxNY                         2913
...                                                      ...
99323144 Evans Islands Apt. 683BurbankWA                3651
997469455 Kathleen Brook Apt. 651HusliaAK                734
99747362 Brown WallKaktovikAK                             12
997838580 Moore CoveWalesAK                             2203
999215942 Thomas ParkCraigAK                              14

[999 rows x 1 columns]

In [36]:
data.columns

Index(['cc_num', 'merchant', 'category', 'amt', 'gender', 'city_pop', 'job',
       'dob', 'trans_num', 'unix_time', 'is_fraud', 'name', 'distance',
       'address'],
      dtype='object')

In [40]:
data[['cc_num','is_fraud']].groupby('cc_num').count()

                     is_fraud
cc_num
60416207185              2196
60422928733              2200
60423098130               738
60427851591               743
60487002085               735
...                       ...
4958589671582726883      2191
4973530368125489546      1467
4980323467523543940       736
4989847570577635369      1471
4992346398065154184      2922

[999 rows x 1 columns]

In [43]:
data[['merchant','is_fraud']].groupby('merchant').count()

                                  is_fraud
merchant
fraud_Abbott-Rogahn                   2647
fraud_Abbott-Steuber                  2529
fraud_Abernathy and Sons              2513
fraud_Abshire PLC                     2733
fraud_Adams, Kovacek and Kuhlman      1354
...                                    ...
fraud_Zemlak Group                    1888
fraud_Zemlak, Tillman and Cremin      2538
fraud_Ziemann-Waters                  2438
fraud_Zieme, Bode and Dooley          3720
fraud_Zulauf LLC                      2605

[693 rows x 1 columns]

In [44]:
data[['name','is_fraud']].groupby('name').count()

                 is_fraud
name
AaronMurray          2920
AaronPena            2191
AaronRogers           741
AaronStewart          737
AdamKeller            743
...                   ...
WilliamThompson      2927
WillieJordan         1463
XavierBeltran        2197
ZacharyAllen         2196
ZacharyBoone          735

[989 rows x 1 columns]

In [45]:
# 1. name별로 is_fraud 개수 세기
table = pd.crosstab(data['name'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100

print(table)

is_fraud            0   1  fraud_rate(%)
name
AaronMurray      2912   8       0.273973
AaronPena        2184   7       0.319489
AaronRogers       729  12       1.619433
AaronStewart      729   8       1.085482
AdamKeller        729  14       1.884253
...               ...  ..            ...
WilliamThompson  2915  12       0.409976
WillieJordan     1459   4       0.273411
XavierBeltran    2184  13       0.591716
ZacharyAllen     2188   8       0.364299
ZacharyBoone      728   7       0.952381

[989 rows x 3 columns]

In [46]:
# 1. name별로 is_fraud 개수 세기
table = pd.crosstab(data['merchant'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100

print(table)

is_fraud                             0   1  fraud_rate(%)
merchant
fraud_Abbott-Rogahn               2643   4       0.151114
fraud_Abbott-Steuber              2521   8       0.316331
fraud_Abernathy and Sons          2509   4       0.159172
fraud_Abshire PLC                 2724   9       0.329308
fraud_Adams, Kovacek and Kuhlman  1349   5       0.369276
...                                ...  ..            ...
fraud_Zemlak Group                1864  24       1.271186
fraud_Zemlak, Tillman and Cremin  2535   3       0.118203
fraud_Ziemann-Waters              2428  10       0.410172
fraud_Zieme, Bode and Dooley      3710  10       0.268817
fraud_Zulauf LLC                  2601   4       0.153551

[693 rows x 3 columns]

In [47]:
table = pd.crosstab(data['category'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100

print(table)

is_fraud             0     1  fraud_rate(%)
category
entertainment   133826   292       0.217719
food_dining     130524   205       0.156813
gas_transport   187257   772       0.410575
grocery_net      64703   175       0.269737
grocery_pos     173963  2228       1.264537
health_fitness  122368   185       0.150955
home            175195   265       0.151032
kids_pets       161423   304       0.187971
misc_net         89472  1182       1.303859
misc_pos        113907   322       0.281890
personal_care   129795   290       0.222931
shopping_net    137103  2219       1.592713
shopping_pos    165407  1056       0.634375
travel           57800   156       0.269170

In [50]:
table = pd.crosstab(data['amt'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100

print(table[table['fraud_rate(%)']>0])

is_fraud    0  1  fraud_rate(%)
amt
1.06      670  1       0.149031
1.18      692  2       0.288184
1.51      632  1       0.157978
1.78      641  1       0.155763
1.91      641  1       0.155763
...       ... ..            ...
1320.92     0  1     100.000000
1324.80     0  1     100.000000
1334.07     0  1     100.000000
1371.81     0  1     100.000000
1376.04     1  1      50.000000

[8296 rows x 3 columns]

In [51]:
table = pd.crosstab(data['gender'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100

print(table)

is_fraud        0     1  fraud_rate(%)
gender
F         1009850  4899       0.482779
M          832893  4752       0.567305

In [52]:
table = pd.crosstab(data['city_pop'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100

print(table)

is_fraud     0   1  fraud_rate(%)
city_pop
23        2907   8       0.274443
37        1460   9       0.612662
43        2920   0       0.000000
46        4374  12       0.273598
47         728   6       0.817439
...        ...  ..            ...
1577385   3645  35       0.951087
1595797   7287  25       0.341904
2383912    728   9       1.221167
2504700   2919  10       0.341413
2906700   5826  39       0.664962

[891 rows x 3 columns]

In [54]:
table = pd.crosstab(data['job'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100

print(table)

is_fraud                                 0   1  fraud_rate(%)
job
Academic librarian                    1456  11       0.749830
Accountant, chartered                    0  11     100.000000
Accountant, chartered certified        730  21       2.796272
Accountant, chartered public finance  3648   9       0.246103
Accounting technician                 6562  33       0.500379
...                                    ...  ..            ...
Water engineer                        8727  13       0.148741
Water quality scientist                727   7       0.953678
Web designer                          3644  18       0.491535
Wellsite geologist                    3637  32       0.872172
Writer                                 726  15       2.024291

[497 rows x 3 columns]

In [ ]:
table = pd.crosstab(data['job'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100

print(table)

In [59]:
table = pd.crosstab(data['name'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100
table = table.sort_values(by='i', ascending=False)

print(table)

KeyError: 'table[1]'

In [58]:
table = pd.crosstab(data['dob'], data['is_fraud'])

# 2. 1 비율 계산 (1 / (0+1))
table['fraud_rate(%)'] = table[1] / (table[0] + table[1]) * 100
table = table.sort_values(by='fraud_rate(%)', ascending=False)

print(table)

is_fraud       0   1  fraud_rate(%)
dob
2001-07-17     0  10          100.0
2002-03-17     0  12          100.0
1925-08-29     0  11          100.0
1927-02-03     0  11          100.0
1944-05-30     0   8          100.0
...          ...  ..            ...
1949-10-04  2920   0            0.0
1975-04-16  2190   0            0.0
1973-10-19  2920   0            0.0
1975-06-29  2920   0            0.0
1930-02-28  1460   0            0.0

[984 rows x 3 columns]

In [60]:
data[['name','dob']]

                  name         dob
0        JenniferBanks  1988-03-09
1        StephanieGill  1978-06-21
2        EdwardSanchez  1962-01-19
3          JeremyWhite  1967-01-12
4          TylerGarcia  1986-03-28
...                ...         ...
1852389   MichaelOlson  1966-02-13
1852390    JoseVasquez  1999-12-27
1852391      AnnLawson  1981-11-29
1852392    EricPreston  1965-12-15
1852393     SamuelFrey  1993-05-10

[1852394 rows x 2 columns]

In [61]:
data['trans_num'].duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1852389    False
1852390    False
1852391    False
1852392    False
1852393    False
Name: trans_num, Length: 1852394, dtype: bool

In [62]:
data['trans_num'].nunique()

1852394

In [63]:
data['name'].nunique()

989

In [64]:
data['dob'].nunique()

984

In [65]:
data['merchant']

0                  fraud_Rippin, Kub and Mann
1             fraud_Heller, Gutmann and Zieme
2                        fraud_Lind-Buckridge
3          fraud_Kutch, Hermiston and Farrell
4                         fraud_Keeling-Crist
                          ...
1852389                 fraud_Reilly and Sons
1852390                  fraud_Hoppe-Parisian
1852391                       fraud_Rau-Robel
1852392                 fraud_Breitenberg LLC
1852393                     fraud_Dare-Marvin
Name: merchant, Length: 1852394, dtype: object

In [66]:
data['category']

0                misc_net
1             grocery_pos
2           entertainment
3           gas_transport
4                misc_pos
                ...
1852389    health_fitness
1852390         kids_pets
1852391         kids_pets
1852392            travel
1852393     entertainment
Name: category, Length: 1852394, dtype: object

In [38]:
data['merchant']

0                  fraud_Rippin, Kub and Mann
1             fraud_Heller, Gutmann and Zieme
2                        fraud_Lind-Buckridge
3          fraud_Kutch, Hermiston and Farrell
4                         fraud_Keeling-Crist
                          ...
1852389                 fraud_Reilly and Sons
1852390                  fraud_Hoppe-Parisian
1852391                       fraud_Rau-Robel
1852392                 fraud_Breitenberg LLC
1852393                     fraud_Dare-Marvin
Name: merchant, Length: 1852394, dtype: object

In [67]:
data.columns

Index(['cc_num', 'merchant', 'category', 'amt', 'gender', 'city_pop', 'job',
       'dob', 'trans_num', 'unix_time', 'is_fraud', 'name', 'distance',
       'address'],
      dtype='object')

In [70]:
data=data.drop(['city_pop','dob','trans_num'], axis=1)

In [74]:
data.columns

Index(['cc_num', 'merchant', 'category', 'amt', 'gender', 'job', 'unix_time',
       'is_fraud', 'name', 'distance', 'address'],
      dtype='object')

In [75]:
selected_cols = ['cc_num', 'merchant', 'category', 'amt', 'gender', 'job', 'unix_time',
       'is_fraud', 'name', 'distance', 'address']  # 네가 고른 열 이름

data_selected = data[selected_cols]

In [76]:
from ydata_profiling import ProfileReport

In [77]:

profile = ProfileReport(data_selected, title="Selected Features Profiling Report", explorative=True)

profile.to_file("selected_features_report.html")

Summarize dataset:   0%|                                           | 0/16 [00:00<?, ?it/s, Describe variable: is_fraud]
Summarize dataset:  44%|███████████████▊                    | 7/16 [00:12<00:09,  1.04s/it, Describe variable: address]
Summarize dataset:  56%|████████████████████▎               | 9/16 [00:13<00:05,  1.18it/s, Describe variable: address]
Summarize dataset:  69%|████████████████████████           | 11/16 [00:13<00:03,  1.62it/s, Describe variable: address]
100%|██████████████████████████████████████████████████████████████████████████████████| 11/11 [00:11<00:00,  1.06s/it]
Summarize dataset: 100%|████████████████████████████████████████████████████| 36/36 [00:30<00:00,  1.19it/s, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.91s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.30it/s]
Export report to file: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 93.07it/s]

In [81]:
data.loc['cc_num']

,cc_num,merchant,category,amt,gender,job,unix_time,is_fraud,name,distance,address
43,30074693890476,fraud_Lockman Ltd,grocery_pos,212.75,F,Arboriculturist,1325377935,0,KelseyRichards,98.962176,67851889 Sarah Station Suite 624HolcombKS
59,4642255475285942,fraud_Huel-Langworth,misc_net,177.57,F,"Surveyor, minerals",1325378505,0,SabrinaJohnson,67.682849,84540320 Nicholson OrchardThompsonUT
87,5456776410929288,fraud_Bernhard Inc,gas_transport,64.47,F,Patent attorney,1325379966,0,TaylorKhan,108.807874,16048658 Diane Glen Apt. 677North WashingtonPA
93,180048185037117,"fraud_Rippin, Kub and Mann",misc_net,3.79,F,Leisure centre manager,1325380197,0,MaryWall,76.450559,70602481 Mills LockPlainfieldNJ
100,6593250708747804,fraud_Brekke and Sons,gas_transport,55.18,F,Paramedic,1325380612,0,MelissaMeza,70.407845,33470244 Abbott ParkwayLoxahatcheeFL
...,...,...,...,...,...,...,...,...,...,...,...
1852389,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,M,Town planner,1388534347,0,MichaelOlson,77.026254,63453558 Michael EstatesLurayMO
1852390,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,M,Futures trader,1388534349,0,JoseVasquez,100.074558,77566572 Davis MountainsLake JacksonTX
1852391,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,F,Musician,1388534355,0,AnnLawson,80.759414,99323144 Evans Islands Apt. 683BurbankWA
1852392,4079773899158,fraud_Breitenberg LLC,travel,7.99,M,Cartographer,1388534364,0,EricPreston,52.933314,836437020 Doyle Stream Apt. 951MesaID
1852393,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,M,Media buyer,1388534374,0,SamuelFrey,72.438389,73034830 Myers Plaza Apt. 384EdmondOK

In [83]:
data=data.drop(['address'], axis=1)

# one-hot 인코딩

In [84]:
data=pd.get_dummies(data, drop_first=True)

In [85]:
X=data.drop('is_fraud', axis=1)
y=data['is_fraud']

In [86]:
X

,cc_num,amt,unix_time,distance,merchant_fraud_Abbott-Steuber,merchant_fraud_Abernathy and Sons,merchant_fraud_Abshire PLC,"merchant_fraud_Adams, Kovacek and Kuhlman",merchant_fraud_Adams-Barrows,"merchant_fraud_Altenwerth, Cartwright and Koss",...,name_WilliamMarshall,name_WilliamMartinez,name_WilliamPerry,name_WilliamSkinner,name_WilliamThomas,name_WilliamThompson,name_WillieJordan,name_XavierBeltran,name_ZacharyAllen,name_ZacharyBoone
0,2703186189652095,4.97,1325376018,78.597677,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,630423337322,107.23,1325376044,30.212217,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,38859492057661,220.11,1325376051,108.206232,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3534093764340240,45.00,1325376076,95.673363,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,375534208663984,41.96,1325376186,77.556851,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,30560609640617,43.77,1388534347,77.026254,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1852390,3556613125071656,111.84,1388534349,100.074558,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1852391,6011724471098086,86.88,1388534355,80.759414,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1852392,4079773899158,7.99,1388534364,52.933314,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1852393,4170689372027579,38.13,1388534374,72.438389,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [87]:
y

0          0
1          0
2          0
3          0
4          0
          ..
1852389    0
1852390    0
1852391    0
1852392    0
1852393    0
Name: is_fraud, Length: 1852394, dtype: int64

# 홀드아웃

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, stratify=y, random_state=10)

# 모델 생성

In [90]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [93]:
for i in range(1, 11): 
    dtc = DecisionTreeClassifier(max_depth=i, random_state=10)
    print(i)
    dtc.fit(X_train, y_train)
    pred = dtc.predict(X_test)
    print(classification_report(y_test, pred))

1

C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00    737098
           1       0.00      0.00      0.00      3860

    accuracy                           0.99    740958
   macro avg       0.50      0.50      0.50    740958
weighted avg       0.99      0.99      0.99    740958

2

C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00    737098
           1       0.00      0.00      0.00      3860

    accuracy                           0.99    740958
   macro avg       0.50      0.50      0.50    740958
weighted avg       0.99      0.99      0.99    740958

3
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    737098
           1       0.61      0.64      0.62      3860

    accuracy                           1.00    740958
   macro avg       0.80      0.82      0.81    740958
weighted avg       1.00      1.00      1.00    740958

4
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    737098
           1       0.76      0.45      0.57      3860

    accuracy                           1.00    740958
   macro avg       0.88      0.73      0.78    740958
weighted avg       1.00      1.00      1.00    740958

5
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    737098
           1       0.76      0.45      0.57      3860

    accuracy                           1.00    740958
   macro avg       0.88      0.73      0.78    740958
weighted avg       1.00      1.00      1.00    740958

6
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    737098
           1       0.73      0.57      0.64      3860

    accuracy                           1.00    740958
   macro avg       0.86      0.78      0.82    740958
weighted avg       1.00      1.00      1.00    740958

7
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    737098
           1       0.73      0.59      0.65      3860

    accuracy                           1.00    740958
   macro avg       0.87      0.79      0.83    740958
weighted avg       1.00      1.00      1.00    740958

8
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    737098
           1       0.74      0.59      0.65      3860

    accuracy                           1.00    740958
   macro avg       0.87      0.79      0.83    740958
weighted avg       1.00      1.00      1.00    740958

9
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    737098
           1       0.76      0.55      0.64      3860

    accuracy                           1.00    740958
   macro avg       0.88      0.78      0.82    740958
weighted avg       1.00      1.00      1.00    740958

10
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    737098
           1       0.77      0.57      0.65      3860

    accuracy                           1.00    740958
   macro avg       0.89      0.78      0.83    740958
weighted avg       1.00      1.00      1.00    740958

# 모델 성능 검증

# 하이퍼파라미터 튜닝(클래스 불균형 해소-모델에서 소수 클래스 가중치 조절, 데이터 증폭, 축소)

# 최종 모델 선택