# 3월 31일

# 1. requests 모듈: HTTP 프로토콜을 사용할 수 있게 해주는 모듈
* [request 모듈 사용설명서](https://requests.readthedocs.io/en/latest/user/quickstart/)

# 2. requests 모듈 설치
* conda install requests
* pip install requests

# 3. requests 모듈 사용법

* 1) 모듈 불러오기: import requests
* 2) url 변수에 저장
* 3) url 파라미터
    * payload={파라미터1: value, 파라미터2: value}
* 4) header
    * headers={key:value}
* 5) HTTP 요청 보내기 get, post
    * get: r=requests.get(url, params=payload, headers=headers)
    * post: r=requests.post(url, data={key:value}): 로그인 해서 크롤링 하는 경우
* 6) 만들어진 url 확인: print(r.url)
* 7) 응답 코드 확인: print(r.status_code)
* 8) 응답 요소 출력: r.text, r.json(), r.content

In [1]:
import requests
url="https://openapi.naver.com/v1/search/blog"
payload = {'query': '핀테크','display': 100, 'start': '1', 'sort':'sim'}
headers={"X-Naver-Client-Id" : "HaXEGE3cbTofjrDFePfE", "X-Naver-Client-Secret": "U1uuXe2QfQ"} #header를 통해 할당함
r=requests.get(url, params=payload, headers=headers) #인코딩, 디코딩 해줌
print(r.url)
data=r.json()
data

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim

{'lastBuildDate': 'Fri, 06 Jun 2025 21:49:47 +0900',
 'total': 462702,
 'start': 1,
 'display': 100,
 'items': [{'title': '한국<b>핀테크</b>지원센터 제13기 대학생 기자단 서류&amp;면접 후기',
   'link': 'https://blog.naver.com/koreafintech/223875135954',
   'description': '한국<b>핀테크</b>지원센터 제13기 대학생 기자단 이영민입니다. 다음 기수분들이 지원할 때 도움 되도록... 봤는데 <b>핀테크</b> 관련 활동인 거예요. 금융에 관심이 많은 인공지능 학도여서 딱이다 생각하고... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20250523'},
  {'title': '삼성금융 <b>핀테크</b> 앱 모니모 3주년 이벤트(ft. 3년 이용 후기)',
   'link': 'https://blog.naver.com/sin1735/223843421065',
   'description': '삼성금융 <b>핀테크</b> 앱 모니모가 출시한지 벌써 3년이 지났습니다. 출시 때부터 아직까지 써오고 있는 <b>핀테크</b> 앱이기에 그 누구보다 잘 쓰고 있다 자부할 수 있는데요. 개인적으로는 출석체크 측면에서도 가장... ',
   'bloggername': '반시르의 치열한 재테크',
   'bloggerlink': 'blog.naver.com/sin1735',
   'postdate': '20250423'},
  {'title': 'TransferWise WireBarley Remitly 머니박스, <b>핀테크</b>와... ',
   'link': 'https://blog.naver.com/elly0515/223878710308',
   'description': 'TransferWise WireBarley Remitly같은 <b>핀테크</b>보다 환율이 좋은거냐는 질문이 들어왔다. 나도 그렇게... 3개의 <b>핀테크</b> 중에는 환율이 가장 좋기 때문이다. 대신 Remitly가 가장 시간이 많이 걸린다.... ',
   'bloggername': 'Ellina 2.0, 2기 출현',
   'bloggerlink': 'blog.naver.com/elly0515',
   'postdate': '20250526'},
  {'title': '코나아이, <b>핀테크</b> 산업의 선두주자! 지역화폐부터 블록체인까지',
   'link': 'https://blog.naver.com/an5217/223887999913',
   'description': '오늘은 <b>핀테크</b> 분야에서 꾸준히 성장하고 있는 코나아이에 대해 자세히 살펴보려고 합니다.... 코나아이는 27년간 <b>핀테크</b> 산업을 이끌어 온 베테랑 기업입니다. 스마트카드와 IC칩 제조를 넘어, 우리가 흔히... ',
   'bloggername': '오늘도 절도있고 검소하게',
   'bloggerlink': 'blog.naver.com/an5217',
   'postdate': '20250604'},
  {'title': '맨틀 온체인 금융 <b>핀테크</b> 미래 제시하는 인덱스펀드 출시 발표',
   'link': 'https://blog.naver.com/duswnswlstlf/223864983664',
   'description': '<b>핀테크</b> 시대에 온체인 금융의 발전이 정말 빠르게 이루어지고 있습니다. 특히 맨틀은 기존 전통... 하는 <b>핀테크</b> 혁명입니다. 이렇게 된다면 사용자는 본인도 모르는 사이 디파이 환경에 접근해 쉽게... ',
   'bloggername': '이기사 블로그',
   'bloggerlink': 'blog.naver.com/duswnswlstlf',
   'postdate': '20250514'},
  {'title': '은행을 삼킨 <b>핀테크</b>: 미국 금융 혁명을 주도하다! (5/27 상장)',
   'link': 'https://blog.naver.com/samsungfund/223871897369',
   'description': '이러한 규제 완화 흐름 속에서 인터넷 전문은행, <b>핀테크</b> 기업, 그리고 빅테크 기반 금융 서비스들이... 그럼 <b>핀테크</b> 산업의 투자 포인트를 좀 더 살펴볼까요?  오늘의 ETF [Kodex 미국금융테크 액티브 ETF]... ',
   'bloggername': '삼성자산운용 Kodex ETF',
   'bloggerlink': 'blog.naver.com/samsungfund',
   'postdate': '20250522'},
  {'title': '쿠팡 정산 관리 및 주기, 올라 <b>핀테크</b> 정산달력으로 보다 쉽게!',
   'link': 'https://blog.naver.com/ekdud0706/223845991975',
   'description': '올라 <b>핀테크</b>는 29,000여 업체가 가입되어 있는 선정산 플랫폼으로 이미 많이 알려져 있다. 앞서 봤던... 대금을 미리 양도받아 지급하는 전자금융, <b>핀테크</b> 서비스로 매출액을 채권화해서 거래한다고 생각하면... ',
   'bloggername': '찐주부J의 생활금융',
   'bloggerlink': 'blog.naver.com/ekdud0706',
   'postdate': '20250425'},
  {'title': '<b>핀테크</b> 기업 뜻, 맨틀코인 MNT의 인덱스 펀드와 뱅킹',
   'link': 'https://blog.naver.com/totoro3123/223834423560',
   'description': "특히 최근 공개된 '맨틀 인덱스 펀드'와 '맨틀 뱅킹'은 암호화폐를 더 쉽고 안전하게 사용할 수 있는 <b>핀테크</b> 방법을 제시하고 있는데요. 관련해서 자세히 알아보죠~ <b>핀테크</b>(Fintech)란? ‘금융(Finance)’과... ",
   'bloggername': '너부리의 주식경제노트',
   'bloggerlink': 'blog.naver.com/totoro3123',
   'postdate': '20250415'},
  {'title': '<b>핀테크</b> 관련주 블록(스퀘어 주식) 주목',
   'link': 'https://blog.naver.com/lmj400/223681430570',
   'description': '<b>핀테크</b>의 중심, 블록이란? 최근 <b>핀테크</b> 관련주들이 연말 소비 성수기와 금융 시장의 긍정적 전망에 힘입어 주목받고 있습니다. 그중에서도 특히 블록(Block), 이전 이름으로 스퀘어(Square)로 알려진 기업은... ',
   'bloggername': '웰커넥티드',
   'bloggerlink': 'blog.naver.com/lmj400',
   'postdate': '20241203'},
  {'title': '인덱스펀드 <b>핀테크</b> 맨틀 코인에서 출시 전망 분석',
   'link': 'https://blog.naver.com/ghfjvb465/223865796299',
   'description': '맨틀 네트워크 인덱스펀드, <b>핀테크</b> 소개, 전망 코하! 경제적 자유 얻기 노마드신지테입니다.... 특히 맨틀이 출시를 발표한 인덱스펀드 MI4는 온체인 <b>핀테크</b>의 새로운 가능성을 보여주고 있어요. 통합... ',
   'bloggername': '노마드신지테의 경제적자유얻기 챌린지',
   'bloggerlink': 'blog.naver.com/ghfjvb465',
   'postdate': '20250514'},
  {'title': '<b>핀테크</b> 투자 후기',
   'link': 'https://blog.naver.com/kan1687/223812724931',
   'description': '<b>핀테크</b> 투자, 아직도 망설이고 계신가요?  여러분 혹시 이런 고민 해보신 적 있나요? &quot;<b>핀테크</b> 분야가 떴다는데, 지금 시작해도 괜찮을까? 좀 더 상황을 지켜봐야 하나?&quot; 사실 이런 생각은 투자를 고민하는 우리... ',
   'bloggername': '우정잉♥',
   'bloggerlink': 'blog.naver.com/kan1687',
   'postdate': '20250329'},
  {'title': '<b>핀테크</b> 뜻 예시 - 관련주 IPO 현황까지 총정리',
   'link': 'https://blog.naver.com/press02/223744135375',
   'description': '요즘 뉴스를 보다 보면 ‘<b>핀테크</b>(Fintech)’라는 단어를 자주 접하게 됩니다. 처음 들으면 다소 낯설고 어려운 개념처럼 느껴질 수 있지만, 사실 우리는 이미 <b>핀테크</b> 서비스를 일상에서 많이 사용하고... ',
   'bloggername': '재미진 저널리스트의 금융탐구생활',
   'bloggerlink': 'blog.naver.com/press02',
   'postdate': '20250201'},
  {'title': '제13기 <b>핀테크</b> 대학생 기자단 합격 후기',
   'link': 'https://blog.naver.com/koreafintech/223873805585',
   'description': '<b>핀테크</b> 관심 계기 대학 생활을 하며 무역, 경영, 경제, 회계까지 다양한 분야의 학문을 접했고, 가장... 독일 온라인뱅크 &quot;Vivid&quot; 당시 <b>핀테크</b> 서비스 중 하나인 “모인”을 통해 무사히 교환학생 파견을... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20250522'},
  {'title': '맨틀(MNT)코인, <b>핀테크</b> 혁신 담은 뱅킹·인덱스펀드 정리',
   'link': 'https://blog.naver.com/jkyun0621/223835784002',
   'description': '특히 맨틀(Mantle) 생태계는 혁신적인 <b>핀테크</b> 모델을 제안하며 이더리움 기반 레이어2 솔루션 이상의... <b>핀테크</b>와 블록체인의 이상적인 결합으로 온체인 상에서 실제 사용성을 확보했으며 Defi의 대중화를... ',
   'bloggername': '경제현미경의 디테일한 시야',
   'bloggerlink': 'blog.naver.com/jkyun0621',
   'postdate': '20250416'},
  {'title': '<b>핀테크</b> 앱 모니모. 출시부터 지금까지 사용하는 이유',
   'link': 'https://blog.naver.com/sin1735/223736128298',
   'description': '삼성그룹의 <b>핀테크</b> 앱이지요. 모니모를 출시부터 지금까지 대략 2년 반정도 되는데요. 최근... <b>핀테크</b> 앱들의 목적은 사용자가 얼마나 자주 접속하느냐이다보니, 초창기부터 제공하는 기능들이 왜 남아 있는지는... ',
   'bloggername': '반시르의 치열한 재테크',
   'bloggerlink': 'blog.naver.com/sin1735',
   'postdate': '20250123'},
  {'title': '비전공자도 가능한 <b>핀테크</b> 앱 개발: 토스처럼 만드는 방법',
   'link': 'https://blog.naver.com/itbank21c/223835729943',
   'description': "바로 '<b>핀테크</b>(FinTech)' 입니다. ✔️ 간편결제, ✔️ 모바일 송금, ✔️ 신용정보 관리, ✔️ 개인 자산 분석 등 우리가 매일 사용하는 앱 속 기술이 바로 <b>핀테크</b>예요. 대표적으로 토스나 카카오뱅크... ",
   'bloggername': 'KG에듀원 아이티뱅크',
   'bloggerlink': 'blog.naver.com/itbank21c',
   'postdate': '20250416'},
  {'title': '이재명 수혜주 집중 분석 - 지역화폐·<b>핀테크</b> 관련주',
   'link': 'https://blog.naver.com/dhong1000/223890661799',
   'description': "이재명 정부는 지역화폐를 &quot;<b>핀테크</b> 산업과 연동되는 공공 소비 플랫폼&quot;으로 진화시키고 있습니다. 지금 왜 '지역화폐·<b>핀테크</b>'가 수혜 산업인가? 즉, 단기 테마주가 아닌 제도화 + 기술화 + 인프라화된 구조적... ",
   'bloggername': 'SMART PROPERTY LAB',
   'bloggerlink': 'blog.naver.com/dhong1000',
   'postdate': '20250606'},
  {'title': '<b>핀테크</b>와 코인 인덱스 펀드까지, 맨틀(MNT)은 온체인 금융... ',
   'link': 'https://blog.naver.com/urchoco/223835104307',
   'description': '맨틀이 온체인 금융그룹으로 확장하기 위해 자그마치 맨틀 뱅킹(<b>핀테크</b>)과 맨틀 Entanced 인덱스 펀드를... 맨틀 뱅크도 토스의 행보를 따라 작은 것부터 시작해 <b>핀테크</b>와 관련된 모든 것을 지원하는 금융... ',
   'bloggername': '유라빠의 금융 옹알이',
   'bloggerlink': 'blog.naver.com/urchoco',
   'postdate': '20250416'},
  {'title': '[<b>핀테크</b>] 앱으로 1초 투자! MZ세대 재테크 혁명',
   'link': 'https://blog.naver.com/kimciko/223884324997',
   'description': '<b>핀테크</b>란? 금융 앱 하나로 돈이 모이는 시대 은행 대신 앱으로 돈을 관리하는 시대, <b>핀테크</b>는 더 이상 미래가 아닙니다.  알고 계셨나요? 매일 사용하는 토스, 카카오뱅크, 네이버페이도 모두 ‘<b>핀테크</b>... ',
   'bloggername': '김치코의 머니로그',
   'bloggerlink': 'blog.naver.com/kimciko',
   'postdate': '20250531'},
  {'title': '롯데카드의 역사 그리고 미래: 인수전에 뛰어드는 <b>핀테크</b>와... ',
   'link': 'https://blog.naver.com/eotjd350/223877392850',
   'description': '뛰어드는 <b>핀테크</b>와 금융지주 대한민국의 신용카드 업계는 지금 변화의 소용돌이 한가운데에 있습니다. 특히 롯데카드는 현재 매각 절차가 본격화되면서 금융지주와 <b>핀테크</b> 기업들이 눈독을 들이고 있는... ',
   'bloggername': '레티.',
   'bloggerlink': 'blog.naver.com/eotjd350',
   'postdate': '20250525'},
  {'title': '<b>핀테크</b>·게임… 인도 시장 선점한 한국 IT 기업들',
   'link': 'https://blog.naver.com/newroad2015/223889394905',
   'description': '<b>핀테크</b>·게임… 인도 시장 선점한 한국 IT 기업들 인도 경제 디지털 전환 속도 빨라… 새로운 기회의... 빌려주는 <b>핀테크</b> 앱 덕분에 가게를 차렸다”고 했다. 고얄씨가 쓴 <b>핀테크</b>(금융 기술) 앱은 ‘트루... ',
   'bloggername': '열린 자료실 다우리',
   'bloggerlink': 'blog.naver.com/newroad2015',
   'postdate': '20250605'},
  {'title': '25년 금융 클라우드 지원사업 <b>핀테크</b> 기업 클라우드는... ',
   'link': 'https://blog.naver.com/xeno_solution/223791865385',
   'description': '이번에 <b>핀테크</b> 기업 담당하고 계신 분들이 주목할 만한 소식이 업데이트되어 가지고 왔습니다~ 다름... <b>핀테크</b> 기업의 경우 보안 기능과 빠르게 처리가 가능한 인프라를 요구할 수밖에 없습니다. 그렇기... ',
   'bloggername': '클라우드를 가장 잘 하는 회사, 제노솔루션',
   'bloggerlink': 'blog.naver.com/xeno_solution',
   'postdate': '20250311'},
  {'title': '손잡고 ‘미국 우선’ ETF 출시…<b>핀테크</b> 사업 본격 진출',
   'link': 'https://blog.naver.com/tearhunter/223844115672',
   'description': "자사 <b>핀테크</b> 브랜드 '트루스파이(Truth.Fi)'를 통해 상장지수펀드(ETF) 및 상장지수상품(ETP) 라인업을... (레퍼럴 코드: laniakea) ■ <b>핀테크</b>·금융 서비스로 사업 확장…‘빅테크 대항마’ 노린다 이번 ETF... ",
   'bloggername': '웹진 [Coin Choice]',
   'bloggerlink': 'blog.naver.com/tearhunter',
   'postdate': '20250423'},
  {'title': '맨틀 인덱스펀드 MI4 <b>핀테크</b> 온체인 소개',
   'link': 'https://blog.naver.com/moneyalarm/223864325768',
   'description': '이번 포스팅에서는 맨틀 인덱스펀드 MI4 <b>핀테크</b> 온체인에 대해서 알아보려고 합니다. 맨틀은... 설계되었으며, <b>핀테크</b>형 앱이라고 볼 수 있습니다. Revolut, 토스처럼 직관적인 UX를 제공하고 DeFi의 복잡함은... ',
   'bloggername': '경제를 깨워주는 머니알람',
   'bloggerlink': 'blog.naver.com/moneyalarm',
   'postdate': '20250513'},
  {'title': '핀스틸러: 미디어 속 <b>핀테크</b> 찾기 #1 이제 송아지도 조각투자 해!',
   'link': 'https://blog.naver.com/koreafintech/223879540081',
   'description': "미디어 속 <b>핀테크</b> 찾기 핀스틸러 #1 이제 송아지도 조각투자 해! '한우 조각투자' 뱅카우 가축투자계약증권 8연속 완판! 소를 어떻게 조각투자 한다는 거지?! 소액 대체 투자로 떠오른 조각투자 조각투자를 통한... ",
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20250527'},
  {'title': '페이버스와 알아보는 2025 글로벌 <b>핀테크</b> 규제 변화',
   'link': 'https://blog.naver.com/payverse/223809522693',
   'description': '2025년 주목해야 할 글로벌 <b>핀테크</b> 규제 변화 안녕하세요, 페이버스 입니다 :) <b>핀테크</b> 산업은 전 세계적으로 빠르게 성장하고 있으며, 이에 따라 각국의 규제 환경도 계속해서 변화하고 있습니다.... ',
   'bloggername': '페이버스(PayVerse)',
   'bloggerlink': 'blog.naver.com/payverse',
   'postdate': '20250326'},
  {'title': '우원식 국회의장, 리투아니아 최고위급 인사와 회담… <b>핀테크</b>... ',
   'link': 'https://blog.naver.com/news33net/223882789175',
   'description': '우원식 국회의장, 리투아니아 최고위급 인사 면담… <b>핀테크</b>·방산·문화교류 확대 논의 우원식 국회의장, 리투아니아 최고위급 인사와 회담… <b>핀테크</b>·방산·문화교류 협력 논의 대한민국 국회의장 우원식이... ',
   'bloggername': '창업일보',
   'bloggerlink': 'blog.naver.com/news33net',
   'postdate': '20250530'},
  {'title': '통장 관리에 필수! <b>핀테크</b> 자동이체(ft.모니모)',
   'link': 'https://blog.naver.com/sin1735/223675460362',
   'description': '<b>핀테크</b>들이 등장하면서, 상황은 완전 달라졌지요? 금일 언급할 모니모 자동이체도 그렇습니다만, 꼭 이 시스템을 이용하라는 것은 아니고, 제가 사용하는 기능이니 설명을 드리는 부분이며, 다른 <b>핀테크</b>에서도... ',
   'bloggername': '반시르의 치열한 재테크',
   'bloggerlink': 'blog.naver.com/sin1735',
   'postdate': '20241128'},
  {'title': '<b>핀테크</b> 기업을 위한 금융 클라우드 지원 사업 (~4/4)',
   'link': 'https://blog.naver.com/n_cloudplatform/223790696137',
   'description': '돈과 개인정보를 다루는 만큼 금융∙<b>핀테크</b> 업계는 보안이 정말 중요한데요. 그렇기 때문에 금융∙<b>핀테크</b> 기업이 혁신적인 서비스를 개발하기 위해선 믿을 수 있는 안전한 클라우드 환경이 꼭... ',
   'bloggername': '네이버클라우드 (NAVER Cloud)',
   'bloggerlink': 'blog.naver.com/n_cloudplatform',
   'postdate': '20250310'},
  {'title': '<b>핀테크</b> 기업으로 전환을 꿈꾸는 맨틀 그룹의 다양한 시도',
   'link': 'https://blog.naver.com/kilsunboa/223835970631',
   'description': '아니라 <b>핀테크</b>를 비롯한 다양한 시도를 하는 중인데요 그래서 오늘 최근 맨틀 그룹의 <b>핀테크</b> 관련 소식을 알려드리도록 하겠습니다 바이비트가 주도한 글로벌 DAO 프로젝트인 BitDAO에서 시작된 맨틀은... ',
   'bloggername': '슬기로운 길짱',
   'bloggerlink': 'blog.naver.com/kilsunboa',
   'postdate': '20250416'},
  {'title': '금융지주회사법 개정, <b>핀테크</b> 혁신의 새 장을 열다',
   'link': 'https://blog.naver.com/newsystock/223833826820',
   'description': '금융지주회사법 개정, <b>핀테크</b> 혁신의 새 장을 열다 안녕하세요, 뉴지스탁입니다. 오늘은 국내 <b>핀테크</b> 산업과 금융지주회사 간 협업에 새로운 전기가 마련된 중요한 소식을 전해드립니다. 금융위원회가 지난... ',
   'bloggername': '뉴지스탁 공식 블로그',
   'bloggerlink': 'blog.naver.com/newsystock',
   'postdate': '20250415'},
  {'title': '<b>핀테크</b>로 외국에 보내는 송금 비용 낮추기',
   'link': 'https://blog.naver.com/e9pay7200/223790123142',
   'description': '그중에서도 스마트폰을 이용해 금융업무를 볼 수 있게 해주는 <b>핀테크</b> 기술의 등장으로 금융시장에서 상당한 변화를 맞이하게 됐답니다. <b>핀테크</b>의 등장으로 현재 대부분의 금융업무는 스마트폰을 통해... ',
   'bloggername': '해외송금이 쉬워지는 순간 이나인페이',
   'bloggerlink': 'blog.naver.com/e9pay7200',
   'postdate': '20250310'},
  {'title': '데이터 금융부터 일상 계약 플랫폼까지 &lt;㈜<b>핀테크</b>... ',
   'link': 'https://blog.naver.com/kmacforever/223862714903',
   'description': '합성어인 ‘<b>핀테크</b>(Fintech)’는 이제 단순한 트렌드를 넘어 금융 혁신의 필수 요소로 자리 잡았다. 그런데 흥미롭게도 이 산업 용어를 회사명으로 선점한 기업이 있다. 2011년 설립된 ㈜<b>핀테크</b>로 금융과... ',
   'bloggername': 'Innovative Knowledge Platformer',
   'bloggerlink': 'blog.naver.com/kmacforever',
   'postdate': '20250522'},
  {'title': '금융위원회 인턴의 ‘<b>핀테크</b> 오픈 네트워킹 데이’ 참석 후기... ',
   'link': 'https://blog.naver.com/blogfsc/223844997210',
   'description': '<b>핀테크</b> 기업과 금융회사, 투자기관이 한 자리에 모이는 ‘<b>핀테크</b> 오픈 네트워킹 데이’가 3회째를 맞이했습니다. 감사하게도 이 뜻깊은 자리에 함께할 수 있었는데요. 과연 그 현장은 어땠는지 생생한 후기를... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20250425'},
  {'title': '[4/14까지][서울] 2025년 <b>핀테크</b> 기술사업화 지원사업 공고... ',
   'link': 'https://blog.naver.com/ilsinbc/223800254706',
   'description': '기술 [서울] 2025년 <b>핀테크</b> 기술사업화 지원사업 공고(서울형 R&amp;D 지원사업) 소관부처·지자체 : 서울특별시 사업수행기관 : 서울경제진흥원 신청기간 : 2025.03.25 ~ 2025.04.14 사업개요 2025년 <b>핀테크</b>... ',
   'bloggername': '경영지도사 김진영의 105세 경영',
   'bloggerlink': 'blog.naver.com/ilsinbc',
   'postdate': '20250318'},
  {'title': '애자일 조직문화로 성장한 <b>핀테크</b> 최초 유니콘 기업... ',
   'link': 'https://blog.naver.com/asan_nanum/223822052140',
   'description': '애자일 조직문화로 성장한 <b>핀테크</b> 최초 유니콘 기업, 비바리퍼블리카(토스) 이승건 대표가 창업한... 최초의 <b>핀테크</b> 유니콘 기업으로 자리 잡았습니다. 하지만 조직 규모 2천 명이 넘어가자 실행력은 점차... ',
   'bloggername': '아산나눔재단 공식 블로그',
   'bloggerlink': 'blog.naver.com/asan_nanum',
   'postdate': '20250404'},
  {'title': '[기자단 뉴스] 보험 <b>핀테크</b> 트렌드 (인슈어테크/온디맨드 보험)',
   'link': 'https://blog.naver.com/koreafintech/223661661653',
   'description': '보험 <b>핀테크</b> 트렌드 제12기 대학생 기자단 이서현 인슈어테크 인슈어테크는 보험과 기술의 합성어로... 보험 <b>핀테크</b> 트렌드 인슈어테크와 온디맨드 보험은 보험 산업의 혁신을 이끄는 핵심 요소로, 소비자에게... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20241118'},
  {'title': '테솔 컬리지, 2025년 <b>핀테크</b>허브 기업 선정!',
   'link': 'https://blog.naver.com/tesol_college/223813299337',
   'description': '2025년 <b>핀테크</b>허브입주기업으로 선정되었습니다! 이번 선정을 통해 테솔컬리지는 영어교육과 기술이 융합된 에듀테크 기반 사업모델을 더욱 본격적으로 전개할 수 있게 되었습니다.  <b>핀테크</b>허브란?... ',
   'bloggername': '테솔 자격증 : TESOL College',
   'bloggerlink': 'blog.naver.com/tesol_college',
   'postdate': '20250328'},
  {'title': '소셜 <b>핀테크</b>, 왜 사람들이 계속 이용할까?',
   'link': 'https://blog.naver.com/imin_app/223789749173',
   'description': '<b>핀테크</b>를 활용해서 2~3천만원의 결혼 자금을 만드는 사람부터 1천만원 이내의 시드머니를 빠른 시간내에 확보하여 투자에 활용하는 사람까지 참여자들이 급속도로 늘어나고 있습니다. 재밌는 점은 소셜 <b>핀테크</b>... ',
   'bloggername': '아임인, 함께라서 더 쉬운 돈 모으는 습관',
   'bloggerlink': 'blog.naver.com/imin_app',
   'postdate': '20250309'},
  {'title': '서울 청년취업사관학교, AI·<b>핀테크</b> 등 실무 역량 교육 제공!... ',
   'link': 'https://blog.naver.com/haechiseoul/223837254002',
   'description': "AI, <b>핀테크</b>, 빅테이터 등 4차 산업 분야의 실무 역량 교육을 제공하는 '청년취업사관학교' 교육생을 모집합니다. ✅ 청년취업사관학교란? 2030 청년 구직자들에게 AI 분야 실무 교육부터 멘토링, 취업까지 연계해... ",
   'bloggername': '서울특별시 공식블로그',
   'bloggerlink': 'blog.naver.com/haechiseoul',
   'postdate': '20250417'},
  {'title': '서울<b>핀테크</b>랩, 2025년 상반기 신규 입주기업으로... ',
   'link': 'https://blog.naver.com/venturesquare_/223864002628',
   'description': '서울<b>핀테크</b>랩은 2025년 상반기 신규 입주기업으로 <b>핀테크</b> 스타트업 소셜트러스트㈜를 선정했다고 13일 밝혔다. 소셜트러스트는 아프리카 나이지리아를 중심으로 대안 신용평가 기반의 모바일 대출 서비스... ',
   'bloggername': 'VentureSquare',
   'bloggerlink': 'blog.naver.com/venturesquare_',
   'postdate': '20250513'},
  {'title': '[프로모션] 최대 9600만원 지원, NHN Cloud <b>핀테크</b> 기업 수요... ',
   'link': 'https://blog.naver.com/nhncloud_official/223805041831',
   'description': 'NHN Cloud는 <b>핀테크</b> 기업에게 중요한 안전한 인프라와 폭넓은 기술 지원을 5년 연속 제공하고 있습니다. NHN Cloud의 <b>핀테크</b> 기업을 위한 특별한 혜택을 안내해 드립니다. ‘금융 클라우드 지원사업’이란?... ',
   'bloggername': '유연하게 안전하게 비즈니스에 힘이 되다 ☁️',
   'bloggerlink': 'blog.naver.com/nhncloud_official',
   'postdate': '20250325'},
  {'title': "KB금융·신한금융, 금융·<b>핀테크</b> 스타트업 해외 진출 '전방위... ",
   'link': 'https://blog.naver.com/investnews/223828468563',
   'description': "신한금융, 'K-<b>핀테크</b> 해외 진출' 프로그램 신설… 일본·베트남 공략 본격화 출처 = 신한금융그룹... 하는 <b>핀테크</b> 중심의 '글로벌 분야' 등 세 가지로 구성된다. 특히 올해 새롭게 추가된 글로벌 분야는... ",
   'bloggername': '인베스트 뉴스',
   'bloggerlink': 'blog.naver.com/investnews',
   'postdate': '20250410'},
  {'title': 'IoT가 바꾸는 <b>핀테크</b>의 미래, 더 스마트한 금융 환경',
   'link': 'https://blog.naver.com/ntjackpot/223820522706',
   'description': 'IoT가 바꾸는 <b>핀테크</b>의 미래, 더 스마트한 금융 환경 1. 사물인터넷과 <b>핀테크</b>의 개념 사물인터넷(IoT, Internet of Things)은 다양한 기기가 인터넷에 연결되어 데이터를 주고받는 기술을 의미한다. 초기에는 스마트... ',
   'bloggername': "IT QUEEN's Queendom",
   'bloggerlink': 'blog.naver.com/ntjackpot',
   'postdate': '20250403'},
  {'title': '<b>핀테크</b> 해외송금 어플리케이션 이나인페이',
   'link': 'https://blog.naver.com/e9pay7200/223854290403',
   'description': '스마트폰 어플리케이션을 기반으로 다양한 산업들이 새롭게 등장했고 그 중세서도 주목할 만한 분야는 바로 <b>핀테크</b>입니다. <b>핀테크</b>는 금용(Finance)과 기술(Technology)의 합성어로 말 그대로 정보기술이 금융... ',
   'bloggername': '해외송금이 쉬워지는 순간 이나인페이',
   'bloggerlink': 'blog.naver.com/e9pay7200',
   'postdate': '20250503'},
  {'title': '금융지주회사의 <b>핀테크</b>기업 출자제한을 완화합니다.',
   'link': 'https://blog.naver.com/blogfsc/223833861352',
   'description': '금융지주회사의 <b>핀테크</b>기업 출자제한을 완화합니다. ✔ 금융지주회사법 및 금융지주회사법 시행령... 금융지주회사는 자회사가 아닌 <b>핀테크</b>기업에 대해서도 15%까지 출자를 할 수 있습니다.... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20250415'},
  {'title': '‘<b>핀테크</b> 개척자’ 류영준, SK일렉링크 이끈다',
   'link': 'https://blog.naver.com/wemakenews/223881949202',
   'description': '제공 <b>핀테크</b> 산업의 흐름을 바꿔놓았다는 평가를 받는 류영준 전 카카오페이 대표가 전기차 충전... 사용자 중심 서비스 설계와 정교한 데이터 운영, 금융과 기술의 융합에 있어 그가 남긴 발자취는 <b>핀테크</b>... ',
   'bloggername': 'wemakenew::위메이크뉴스',
   'bloggerlink': 'blog.naver.com/wemakenews',
   'postdate': '20250529'},
  {'title': '자회사로, 세금 신고 및 환급을 돕는 서비스를 제공하는 <b>핀테크</b>',
   'link': 'https://blog.naver.com/only8278/223876516360',
   'description': '* 토스의 자회사: 토스는 한국의 대표적인 <b>핀테크</b> 기업으로, 이미 많은 사용자들에게 신뢰를 얻고 있습니다. 토스인컴 역시 토스의 엄격한 보안 및 운영 기준을 따릅니다. * 공식 세금 신고 대행 서비스... ',
   'bloggername': '.',
   'bloggerlink': 'blog.naver.com/only8278',
   'postdate': '20250524'},
  {'title': '가족보험도 <b>핀테크</b>로! 내보험찾아줌 서비스',
   'link': 'https://blog.naver.com/koreafintech/223885752938',
   'description': '가족보험도 <b>핀테크</b>로! 내보험찾아줌 서비스  한국<b>핀테크</b>지원센터 13기 대학생 기자단 카드뉴스 기자 박민희 내 보험 잘 알고 있나요? &quot;보험은 많은데.. 정확하게 뭘 들었는지 모르겠는 부모님&quot; &quot;부모님 명의로... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20250602'},
  {'title': '中 그리텍, 반도체·디스플레이용 초순수 업체 가오<b>핀테크</b> 인수',
   'link': 'https://blog.naver.com/kipost0815/223835365588',
   'description': '[KIPOST] 중국 실리콘 잉곳 및 웨이퍼 제조사 그리텍(有研硅发, GRITEK)은 베이징 가오<b>핀테크</b>... 가오<b>핀테크</b>는 초순수(UPW, Ultra-Pure Water) 전문 업체로, 중국 내에서 처음으로 UPW 시스템을 공급한 바 있다.... ',
   'bloggername': '[KIPOST] 첨단 산업의 모든 정보- 키포스트',
   'bloggerlink': 'blog.naver.com/kipost0815',
   'postdate': '20250416'},
  {'title': '[5/3까지][금융위원회]2025년 <b>핀테크</b> 특화 해외진출... ',
   'link': 'https://blog.naver.com/ilsinbc/223855948295',
   'description': '수출 2025년 <b>핀테크</b> 특화 해외진출 프로그램(Nexus Luxembourg 2025) 참가기업 모집 공고 소관부처·지자체 : 금융위원회 사업수행기관 : 한국<b>핀테크</b>지원센터 신청기간 : 2025.04.30 ~ 2025.05.13 사업개요... ',
   'bloggername': '경영지도사 김진영의 105세 경영',
   'bloggerlink': 'blog.naver.com/ilsinbc',
   'postdate': '20250505'},
  {'title': 'MZ세대가 소셜 <b>핀테크</b> 아임인에 빠지는 이유 3가지',
   'link': 'https://blog.naver.com/imin_app/223841076850',
   'description': '소셜 <b>핀테크</b>이기에 MZ 세대에 특히 잘 맞는 플랫폼입니다. 결론. 아임인은 단순히 “금융”이 아니라, 내 스케쥴과 리듬에 맞춰 쓰고, 유연하게 조절하는 소셜 <b>핀테크</b>입니다. 정해진 방식의 적금이나, 여러가지... ',
   'bloggername': '아임인, 함께라서 더 쉬운 돈 모으는 습관',
   'bloggerlink': 'blog.naver.com/imin_app',
   'postdate': '20250421'},
  {'title': 'NFT, DX, SDGs, <b>핀테크</b> - IT 용어 뜻풀이',
   'link': 'https://blog.naver.com/coreit_gene/223859905149',

# 네이버 검색 api를 이용해서 책을 검색하고 결과를 데이터프레임으로 만드세요.
* 검색어는 input을 이용해서 입력받은 값을 이용하세요.

In [2]:
import requests
import pandas as pd
keyword=input("검색하고 싶은 책이름을 입력하세요")
url = "https://openapi.naver.com/v1/search/book.json"
payload={'query':keyword,'display': 100, 'start': '1', 'sort':'sim'}
headers={"X-Naver-Client-Id" : "HaXEGE3cbTofjrDFePfE", "X-Naver-Client-Secret": "U1uuXe2QfQ"} 

#X-Naver-Client-Id: {HaXEGE3cbTofjrDFePfE}
#X-Naver-Client-Secret:{U1uuXe2QfQ}

검색하고 싶은 책이름을 입력하세요파이썬

In [3]:
r=requests.get(url, params=payload, headers=headers) #인코딩, 디코딩 해줌
print(r.url)
data=r.json()
data

https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1&sort=sim

{'lastBuildDate': 'Fri, 06 Jun 2025 21:49:53 +0900',
 'total': 1128,
 'start': 1,
 'display': 100,
 'items': [{'title': '혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임, 맵, AI 챗봇 만들기|저자 직강 유튜브 강의, 오픈 채팅 제공)',
   'link': 'https://search.shopping.naver.com/book/catalog/52859338841',
   'image': 'https://shopping-phinf.pstatic.net/main_5285933/52859338841.20250209071357.jpg',
   'author': '문현일',
   'discount': '23400',
   'publisher': '한빛미디어',
   'pubdate': '20250214',
   'isbn': '9791169213271',
   'description': '“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석, 우리 아파트 실거래가 시각화해보기, 맛집 지도 웹 앱 만들기 등 \n생활 속  15가지 파이썬 프로젝트를 직접 완성해 보며 재미있게 실전 경험 쌓기!\n\nQR 코드, 이미지 콜라주 등 일상과 가까운 생활형 프로젝트부터 부동산, 경제지표, 시가총액 같은 실용적인 데이터를 다루는 프로젝트, LLM, 멀티모달 AI와 TTS 등 최신 기술까지! 폭넓은 주제를 통해 흥미롭게 따라 해 보세요.\n\n●\t 주식 & 경제 데이터 분석 - 시가총액, 기준금리, 주요 경제지표 데이터 분석 및 시각화하기\n●\t 부동산 실거래가 분석 - 지역별 단위면적당 아파트 매매 실거래가 평균 지도로 만들기\n●\t 멀티모달 AI & 챗봇 개발 - 생성형 AI와 챗봇을 활용한 실시간 영자 신문 스크레이핑\n●\t 웹 자동화 & 크롤링 - 연관 키워드 분석을 통한 연령별, 성별 쇼핑 트렌드 분석\n●\t 게임 & GUI 개발 - 슬라이딩 퍼즐, 영어 받아쓰기 앱으로 직접 만들어 보는 인터랙티브 프로젝트'},
  {'title': '혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서)',
   'link': 'https://search.shopping.naver.com/book/catalog/32507605957',
   'image': 'https://shopping-phinf.pstatic.net/main_3250760/32507605957.20230509170119.jpg',
   'author': '윤인성',
   'discount': '19800',
   'publisher': '한빛미디어',
   'pubdate': '20220601',
   'isbn': '9791162245651',
   'description': '혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 공부하는 파이썬』이 더욱 흥미있고 알찬 내용으로 개정되었습니다. 프로그래밍이 정말 처음인 입문자도 따라갈 수 있는 친절한 설명과 단계별 학습은 그대로! 혼자 공부하더라도 체계적으로 계획을 세워 학습할 수 있도록 ‘혼공 계획표’를 새롭게 추가했습니다. 또한 입문자가 자주 물어보는 질문과 오류 해결 방법을 적재적소에 배치하여 예상치 못한 문제에 부딪혀도 좌절하지 않고 끝까지 완독할 수 있도록 도와줍니다. 단순한 문법 암기와 코딩 따라하기에 지쳤다면, 새로운 혼공파와 함께 ‘누적 예제’와 ‘도전 문제’로 프로그래밍의 신세계를 경험해 보세요! 배운 내용을 씹고 뜯고 맛보고 즐기다 보면 응용력은 물론 알고리즘 사고력까지 키워 코딩 실력이 쑥쑥 성장할 것입니다.\n\n이 책은 독학으로 파이썬을 배우는 입문자가 ‘꼭 필요한 내용을 제대로 학습’할 수 있도록 구성했습니다. 뭘 모르는지조차 모르는 입문자의 막연한 마음에 십분 공감하여 과외 선생님이 알려주듯 친절하게, 핵심적인 내용만 콕콕 집어줍니다. 책의 첫 페이지를 펼쳐서 마지막 페이지를 덮을 때까지, 혼자서도 충분히 파이썬을 배울 수 있다는 자신감과 확신이 계속될 것입니다!\n\n베타리더와 함께 입문자에게 맞는 난이도, 분량, 학습 요소 등을 적극 반영했습니다. 어려운 용어와 개념은 한 번 더 풀어쓰고, 복잡한 설명은 눈에 잘 들어오는 그림으로 풀어냈습니다. ‘혼자 공부해 본’ 여러 입문자의 초심과 눈높이가 책 곳곳에 반영된 것이 이 책의 가장 큰 장점입니다.'},
  {'title': 'Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서)',
   'link': 'https://search.shopping.naver.com/book/catalog/40354085633',
   'image': 'https://shopping-phinf.pstatic.net/main_4035408/40354085633.20230927071024.jpg',
   'author': '박응용',
   'discount': '19800',
   'publisher': '이지스퍼블리싱',
   'pubdate': '20230615',
   'isbn': '9791163034735',
   'description': '프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정 2판 출시!\n\n중고등학생도, 비전공자도, 직장인도 프로그래밍에 눈뜨게 만든 바로 그 책이 전면 개정 2판으로 새롭게 태어났다! 챗GPT를 시작으로 펼쳐진 생성 AI 시대에 맞춰 설명과 예제를 다듬고, 최신 경향과 심화 내용을 보충했다. 또한 이번 개정 2판도 50만 코딩 유튜버인 조코딩과 협업을 통해 유튜브 동영상을 제공해 파이썬을 더 쉽게 공부할 수 있다.\n\n8년 연속 베스트셀러! 위키독스 누적 방문 300만! 독자의 입에서 입으로 전해진 추천과 수많은 대학 및 학원의 교재 채택을 통해 검증은 이미 끝났다. 코딩을 처음 배우는 중고등학생부터 코딩 소양을 기르려는 비전공자, 자기계발에 진심인 직장인까지! 이 책과 함께 파이썬 프로그래밍의 세계로 ‘점프’해 보자!'},
  {'title': '밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현)',
   'link': 'https://search.shopping.naver.com/book/catalog/52615553184',
   'image': 'https://shopping-phinf.pstatic.net/main_5261555/52615553184.20250123071242.jpg',
   'author': '사이토 고키',
   'discount': '23400',
   'publisher': '한빛미디어',
   'pubdate': '20250124',
   'isbn': '9791169213387',
   'description': '딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 입문서\n\n이 책은 딥러닝의 핵심 개념을 ‘밑바닥부터’ 구현해보며 기초를 한 걸음씩 탄탄하게 다질 수 있도록 도와주는 친절한 안내서입니다. 라이브러리나 프레임워크에 의존하지 않고 딥러닝의 기본 개념부터 이미지 인식에 활용되는 합성곱 신경망(CNN)까지 딥러닝의 원리를 체계적으로 설명합니다. 또한 복잡한 개념은 계산 그래프를 활용해 시각적으로 전달하여 누구나 쉽게 이해할 수 있습니다. 이 책은 딥러닝에 첫발을 내딛는 입문자는 물론이고 기초를 다시금 다지고 싶은 개발자와 연구자에게도 훌륭한 길잡이가 되어줄 것입니다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32460987987',
   'image': 'https://shopping-phinf.pstatic.net/main_3246098/32460987987.20230207163755.jpg',
   'author': '홍의경',
   'discount': '30400',
   'publisher': '생능출판',
   'pubdate': '20220309',
   'isbn': '9788970506784',
   'description': '코딩 실력을 키우는 지름길은 실습이다.\n\n2008년 즈음에 검인정 중학교 교과서 정보1, 정보2, 정보3을 공저로 저술하였습니다. 그 당시에 8종류의 교과서가 검인정에 합격하였는데, 파이썬을 기반으로 하는 교과서가 2종류, C언어를 기반으로 하는 교과서가 2종류, 베이직을 기반으로 하는 교과서가 2종류, 스크래치를 기반으로 하는 교과서가 2종류였습니다.\n\n교육용 언어로 시작한 파이썬이 중학교 학생들이 비교적 쉽게 학습할 수 있는 프로그래밍 언어라고 생각했는데 10여년의 세월이 흐른 지금 파이썬이 활용되는 분야가 가히 폭발적으로 증가하였습니다. \n\n파이썬에 관한 쉽고 좋은 교재를 저술하기 위해서 인터넷에서 30,000페이지 이상의 자료를 찾아서 검토하였습니다. 어쩌면 파이썬이 첫 프로그래밍 언어일 본 교재의 독자들이 두려움 없이 파이썬을 기초부터 쉽게 공부하다가, 교재를 다 읽고 나면 “어느새 중급 수준에 도달했구나”라는 생각이 들도록  완성도 높은 교재를 목표로 하였습니다. \n\n입문자를 대상으로 하는 교재일수록 집필하는데 훨씬 더 많은 정성과 노력이 필요하다는 것을 잘 알고 있습니다. 개인적으로는 데이터베이스 전공교재를 저술할 때보다 몇 배 더 힘들었고, 공을 많이 들였습니다. \n\n원고를 버전 9까지 작성하는 동안 셀 수 없이 원고를 읽어보면서 꼭 필요하지 않은 문장은 삭제하고, 필요한 문장은 반드시 넣었습니다. 고등학교 검인정 교과서 1권, 중학교 검인정 교과서 3권, 데이터베이스 전공 교재 2권, 엑셀 교재 1권, 번역서 2권을 집필하면서 나름대로 한글을 정확하고 간결하게 표현하는데 자신이 있습니다.'},
  {'title': 'CODING BASICS PYTHON (파이썬)',
   'link': 'https://search.shopping.naver.com/book/catalog/32440944646',
   'image': 'https://shopping-phinf.pstatic.net/main_3244094/32440944646.20230509164030.jpg',
   'author': '김상민^장성식^김일태',
   'discount': '18000',
   'publisher': '렉스미디어닷넷',
   'pubdate': '20220210',
   'isbn': '9788959604210',
   'description': '파이썬으로 다지는 프로그래밍의 기초\n\nㆍ 다양한 예제를 활용하여 초보자도 쉽게 프로그래밍의 기본을 익힐 수 있는 파이썬 입문서입니다.\nㆍ 문법을 사전식으로 나열하지 않고 기능적인 프로그램을 하나씩 완성하면서 익힐 수 있게 구성했습니다.\nㆍ 단계별로 완성하는 장별 예제 및 연습문제를 바탕으로 자신만의 프로그램을 완성할 수 있습니다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32489150082',
   'image': 'https://shopping-phinf.pstatic.net/main_3248915/32489150082.20230207165503.jpg',
   'author': '천인국',
   'discount': '10800',
   'publisher': '인피니티북스',
   'pubdate': '20170830',
   'isbn': '9791185578330',
   'description': '컴퓨팅 사고(Computational Thinking)는 자넷 윙 교수가 2006년에 컴퓨터 학술지에서 언급한 이후로 컴퓨터 교육 분야에서 상당한 이슈가 되고 있는 용어이다. 컴퓨팅 사고는 복잡한 문제를 분해하여 문제 안에 내재된 패턴을 찾고 추상화 단계를 거쳐서 문제를 해결하는 알고리즘을 작성하는 과정이다. 작성된 알고리즘은 사람이 수행하거나 컴퓨터를 이용하여 자동화될 수 있다. \n이 책은 컴퓨팅 사고와 파이썬을 동시에 학습할 수 있도록 기획되었다. 파이썬은 컴퓨터를 전공하지 않은 학생들도 쉽게 사용할 수 있다는 큰 장점이 있다. 컴퓨팅 사고는 흥미로운 실습 예제가 많이 필요하다. 이 책에서는 최대한 많은 실습 예제를 간추려서 파이썬으로 실습할 수 있도록 하였다. 파이썬은 다양한 애니메이션이나 가상 실습을 만들 수 있는 최적의 도구이다. 학생들은 파이썬을 통하여 컴퓨터 프로그래밍의 기본적인 개념들과 컴퓨팅 사고에서 나타나는 다양한 실습을 수행할 수 있을 것이다.'},
  {'title': '파이썬 (제2판)',
   'link': 'https://search.shopping.naver.com/book/catalog/32436240934',
   'image': 'https://shopping-phinf.pstatic.net/main_3243624/32436240934.20230928092006.jpg',
   'author': '염기원^오지영',
   'discount': '16200',
   'publisher': '북두',
   'pubdate': '20220120',
   'isbn': '9791166750991',
   'description': '책의 전반부는 비전공자의 입장에서 비전공자를 위한 파이썬 프로그래밍의 기초적인 내용으로 구성되어 있다. 프로그래밍에 익숙하거나 파이썬 경험이 있는 독자들은 곧바로 책의 후반부를 공부하는 것을 권한다. 책의 전반부에서는 저자가 처음 컴퓨터 프로그래밍이라는 것을 배울 때 가장 어려워했던 변수와 메모리 관계, 특성에 대해서 상세하게 설명하면서 비전공자들이 쉽게 프로그래밍에 입문할 수 있도록 하였다. 대부분의 프로그래밍 교재와 다를바 없이, 파이썬으로 프로그램을 작성할 수 있도록 개발환경을 설치하는 과정과 사용 가능한 프로그래밍 툴에 대해서도 빠지지 않고 최대한 상세한 설명과 충분한 그림을 삽입하였다. 또한, 전반부의 뒷부분은 데이터 분석에 필요한 파이썬 프로그램 위주로 구성해서 앞부분의 기초 프로그래밍 지식을 바탕으로 본격적인 데이터 분석을 위한 토대를 마련할 수 있도록 구성하였다.'},
  {'title': '파이썬 (비전공자를위한 파이썬 기초 입문서)',
   'link': 'https://search.shopping.naver.com/book/catalog/32436003648',
   'image': 'https://shopping-phinf.pstatic.net/main_3243600/32436003648.20230920072841.jpg',
   'author': '김명호',
   'discount': '11400',
   'publisher': '에듀웨이',
   'pubdate': '20190525',
   'isbn': '9791186179369',
   'description': '막막했던 파이썬, 이제 한 권으로 기초를 배우는\n파이썬 사용 설명서!\n\n전 세계적으로 유명한 구글(Google)이 자신의 많은 서비스를 파이썬으로 제공하고 있습니다. 이것은 구글의 뛰어난 서비스를 개인의 비즈니스에 쉽게 이용할 수 있다는 의미입니다.  이러한 발전에 맞춰 파이썬 문법의 기초를 쉽게 이해할 수 있도록 이 책에서는 친절한 도해와 함께 코딩 개념을 설명합니다. 파이썬을 처음 배우는 학생부터 비전공자, 코딩 실력을 높이려는 직장인까지 기본 문법부터 예제를 통한 활용 실력을 높여 파이썬 프로그래밍을 마스터할 수 있습니다. 가장 쉽고, 빠르게, 효율적인 파이썬 사용 설명서! ‘한 권으로 끝내는 파이썬’에서 찾아보세요.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32490271648',
   'image': 'https://shopping-phinf.pstatic.net/main_3249027/32490271648.20220527033830.jpg',
   'author': '염기원',
   'discount': '0',
   'publisher': '복두출판사',
   'pubdate': '20200820',
   'isbn': '9791159069048',
   'description': '비전공자의 데이터 분석을 위한 『파이썬』은 〈파이썬 기초〉, 〈파이썬을 이용한 데이터 분석 기초〉, 〈시각화 라이브러리 사용하기〉 등 파이썬의 기초적이고 전반적인 내용이 수록되어 있다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32438172833',
   'image': 'https://shopping-phinf.pstatic.net/main_3243817/32438172833.20230920072917.jpg',
   'author': '김영천',
   'discount': '23750',
   'publisher': '기한재',
   'pubdate': '20200225',
   'isbn': '9788970187990',
   'description': '▶ 이 책은 Python(파이썬)을 다룬 이론서입니다. Python(파이썬)의 기초적이고 전반적인 내용을 학습할 수 있습니다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32505098970',
   'image': 'https://shopping-phinf.pstatic.net/main_3250509/32505098970.20220527074158.jpg',
   'author': '서정원^김태령',
   'discount': '0',
   'publisher': '생능출판',
   'pubdate': '20190228',
   'isbn': '9788970509723',
   'description': '이 책은 지금까지 경험하지 못한 코딩 교육의 진수를 보여준다. “코딩 교육이 가야 할 방향은 컴퓨팅 사고력을 높이는 것이다.”라고 이 책의 저자들이 말하듯, “디지털 시대에 적합한 창의력과 문제해결력을 기르기 위한 코딩의 기초부터 응용까지 컴퓨터 코드를 작성하는 것은 물론이고, 알고리즘 학습을 통한 컴퓨팅 사고력을 완전 정복한다.'},
  {'title': '파이썬 (다양한 예제로 알로리즘 쉽게 분석하기)',
   'link': 'https://search.shopping.naver.com/book/catalog/32441765959',
   'image': 'https://shopping-phinf.pstatic.net/main_3244176/32441765959.20220527045202.jpg',
   'author': '김유진',
   'discount': '22500',
   'publisher': '다본',
   'pubdate': '20190410',
   'isbn': '9791188577255',
   'description': '파이썬은 인터프리터 방식으로 접근이 쉬운 반면 다양한 기능의 라이브러리들이 제공되어 빅 데이터나 머신 러닝, 순수 과학, 웹, GUI 등 다양한 분야에서 사용되고 있다. 또한, 파이썬은 이식성이 높고 모듈 제작이 가능하기 때문에 자주 사용하는 기능을 모듈로 제작하여 해당 기능이 필요할 때마다 작성한 모듈을 임포트(import)하여 사용할 수 있다. 이처럼 많은 장점을 가진 파이썬은 특히 빅 데이터나 머신 러닝, 사물 인터넷, 웹에서 많이 사용되므로 해당 분야와 관련해 취업을 준비하거나 공부하는 학생 그리고 이런 분야와 관련된 일을 하는 개발자들에게 꼭 필요한 프로그램 언어이므로 이 책은 이들에게 좋은 참고서가 될 것이다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32441653441',
   'image': 'https://shopping-phinf.pstatic.net/main_3244165/32441653441.20230418164550.jpg',
   'author': 'Y. Daniel Liang',
   'discount': '31500',
   'publisher': '에피스테메',
   'pubdate': '20180302',
   'isbn': '9788920028892',
   'description': '이 책은 누구나 쉽게 따라할 수 있는 파이썬 프로그래밍 언어에 기반하고 있기 때문에 프로그래밍을 통해 얻을 수 있는 논리 능력 향상과 문제 해결력 배양에 가장 적합하다. \n비전공자도 쉽게 이해하고 활용할 수 있는 풍부한 예제를 제공하여 프로그래밍의 기본 개념 정립에 도움을 주며 실생활과 밀접하게 관련된 다양한 사례 연구를 통해 실생활의 문제 해결 능력을 자연스럽게 배양시킨다.\n 이 책을 활용한 프로그래밍 학습을 통해 파이썬 프로그램을 스스로 작성하고 실행해 봄으로써 자신만의 프로그램을 작성할 수 있다는 뿌듯함을 느껴볼 수 있다. \n객체지향 개념과 그래픽 처리, 이벤트 처리 등이 쉽게 설명되어 있어 복잡하지 않고 간단하게 프로그램에 추가하여 다양한 기능을 가진 자신만의 프로그램도 작성해 볼 수 있다.\n이 책은 파이썬 언어에 대한 기본 문법부터 활용까지 프로그래밍에 관한 전반적인 내용을 다루고 있고 원저자의 경험과 능력, 치밀한 구성에 의해 완성한 책인 만큼 완성도 및 충실도는 매우 뛰어나다. \n그동안 무심코 넘어갔던 개념들에 대해서 다시 한 번 생각해 보는 계기를 마련해 준다. 그만큼 이 책은 파이썬 프로그래밍 언어에 대한 개념과 활용을 집대성했기 때문이다. 그래서 IT 전공자뿐만 아니라 광범위한 분야에서 프로그래밍에 관심 있는 입문자들에게 많은 도움과 개념을 정리해 줄 수 있는 책이다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32504743740',
   'image': 'https://shopping-phinf.pstatic.net/main_3250474/32504743740.20220527031429.jpg',
   'author': 'Y. Daniel Liang',
   'discount': '0',
   'publisher': '생능출판',
   'pubdate': '20160205',
   'isbn': '9788970508504',
   'description': '[파이썬]은 파이썬 언어에 대한 기본 문법부터 활용까지 프로그래밍에 관한 전반적인 내용을 다루고 있다. 이 책을 활용한 프로그래밍 학습을 통해 파이썬 프로그램을 스스로 작성하고 실행해 봄으로써 자신만의 프로그램을 작성할 수 있을 것이다.'},
  {'title': '독학 파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/51981118640',
   'image': 'https://shopping-phinf.pstatic.net/main_5198111/51981118640.20241224071117.jpg',
   'author': '야마다 요시히로',
   'discount': '28800',
   'publisher': '정보문화사',
   'pubdate': '20241220',
   'isbn': '9788956749891',
   'description': '이론과 실전이 모두 담긴 단 한 권의 파이썬 교과서\n\n처음 파이썬 프로그래밍을 시작하는 사람 또는 더욱 깊은 내용을 목표로 하는 사람에게 정확한 지식을 제공하기 위해 쓰였다. 파이썬 프로그래밍을 위한 환경 설정과 파이썬만의 기본 규칙에서 시작해 연산자, 라이브러리, 객체지향 구문까지 다뤘다. 파이썬을 보다 정확하게 이해해 책 속 예제 코드뿐만 아니라 실전에서 관련 지식을 활용할 수 있도록 꼼꼼하게 설명한다. 이렇게 기초를 탄탄하게 세운 후, 의식하면 좋은 파이썬 개발 관습과 보다 간단한 표현법을 언급해 프로그래밍 능력을 차근차근 키울 수 있게 했으며, 이 책 한 권으로 독학부터 협업까지 가능하게 했다.\n또한 이 책은 중간에 포함된 연습 문제의 해답을 제공한다. 챕터와 절이 끝날 때마다 단답형, 코드 작성, OX 등의 연습 문제가 다양하게 제공되는데, 독학이 가능한 파이썬 교과서답게 모든 연습 문제의 해답을 부록으로 실어 독자의 답답함을 해소했다. 꼼꼼하면서 실무적인 설명과 해답이 있는 연습 문제에 더불어 각종 팁이 담긴 ‘note’와 추가 정보를 담은 ‘전문가에게 묻기’, ‘칼럼’이 곳곳에 준비되어 있어, 파이썬을 독학으로 마스터하려는 사람, 파이썬의 어느 부분을 공부해야 할지 망설여졌던 사람에게 특히 도움이 될 것이다.'},
  {'title': '내공의 파이썬 (한 권으로 끝내는 초보자용 코딩 입문서)',
   'link': 'https://search.shopping.naver.com/book/catalog/53550577590',
   'image': 'https://shopping-phinf.pstatic.net/main_5355057/53550577590.20250315093055.jpg',
   'author': '한선관',
   'discount': '24300',
   'publisher': '자유아카데미',
   'pubdate': '20250315',
   'isbn': '9791158087005',
   'description': '『내공의 파이썬』은 파이썬을 처음 접하는 독자들이 기본 개념을 쉽게 익히고, 점진적으로 내공의 실력을 쌓을 수 있도록 구성하였다. 단순한 문법 암기에 그치지 않고, 실제 코딩에 적용할 수 있는 능력을 기를 수 있도록 다양한 예제와 실습 문제를 포함하였다. 또한, 프로그래밍의 기초 개념을 배우는 과정에서 컴퓨터과학적 사고를 함께 익힐 수 있도록 ‘기초 내공 쌓기’, ‘도전 내공 쌓기’, ‘기초튼튼 컴퓨터과학’ 등의 코너를 마련하여 독자들이 문제 해결 능력을 기르면서 컴퓨터과학의 개념과 자연스럽게 연결 지을 수 있도록 하였다.'},
  {'title': '파이썬 3 (프로그래밍을 배우기에 가장 재미있는 언어)',
   'link': 'https://search.shopping.naver.com/book/catalog/32485534946',
   'image': 'https://shopping-phinf.pstatic.net/main_3248553/32485534946.20221019105212.jpg',
   'author': '박상현',
   'discount': '0',
   'publisher': '한빛미디어',
   'pubdate': '20160210',
   'isbn': '9788968482359',
   'description': '본서는 프로그래밍 경험이 없는 독자가 파이썬을 통해 프로그래밍을 배워볼 수 있는 입문서로서, 프로그래밍을 배우고 싶지만 두려움이 있는 입문자에게 가장 적합한 난이도로 설명한다.'},
  {'title': '파이썬 + AI (코드조각과 실행화면으로 배우는 코딩)',
   'link': 'https://search.shopping.naver.com/book/catalog/48703888619',
   'image': 'https://shopping-phinf.pstatic.net/main_4870388/48703888619.20240627091044.jpg',
   'author': '안용제^김남규',
   'discount': '25200',
   'publisher': '디지털북스',
   'pubdate': '20240715',
   'isbn': '9788960884571',
   'description': '“코드조각과 실행화면을 통해, 단계적 반복을 통해 배우는 파이썬과 AI”\n\n이 책은 프로그래밍 언어에 익숙한 프로그래머가 아닌 프로그램 입문자들을 대상으로 프로그래밍에 대해 아무런 지식이 없다고 가정하고 프로그램 코딩을 가르치기 위해 작성되었습니다. 이 책을 통해 코딩 개요, Python 기초, numpy, matplotlib, pandas 그리고 머신러닝/딥러닝 퀵스타트 등 Python의 전반을 한 권으로 학습할 수 있습니다.\n또한 코드조각이라고 부르는 프로그램 코딩에 대한 예제를 설명을 위한 주축으로 사용합니다. 그래서 코드조각을 먼저 이해하려고 노력한 후 코드조각을 실행하여 얻게 되는 실행화면을 통해, 코딩의 결과를 바로바로 확인할 수 있도록 하였습니다. 코드조각을 컴퓨터에 입력하여 실행시켜 보면서 프로그램의 수행 결과를 자세히 관찰하고, 프로그램 코드를 한 줄씩 따라가면서 변수와 객체 등 컴퓨터 저장 공간의 변화를 함께 따라가 보면 어느새 파이썬과 AI 코딩을 능숙하게 활용할 수 있을 것입니다.'},
  {'title': '파이썬 마스터 (실생활 융합 예제로 배우는)',
   'link': 'https://search.shopping.naver.com/book/catalog/52509305501',
   'image': 'https://shopping-phinf.pstatic.net/main_5250930/52509305501.20250123071218.jpg',
   'author': '김종훈^김동건',
   'discount': '31040',
   'publisher': '한빛아카데미',
   'pubdate': '20250117',
   'isbn': '9791173400018',
   'description': '파이썬 프로그래밍 기초와 데이터 분석을\n한 권으로 마스터하는 파이썬 기본서!\n\n『파이썬 마스터』는 파이썬을 처음 배우는 독자를 대상으로 하는 책이며, 파이썬의 기초 문법부터 넘파이, 판다스, 데이터 시각화, 머신러닝과 딥러닝까지 학습할 수 있다. 각 장에는 꼭 알아야 하는 파이썬의 핵심 개념과 문법을 다루고 있으며, 더 나아가 실제 개발에 필요한 실력을 쌓을 수 있도록 5단계 반복 학습 과정을 제공한다. 이 책의 단계별 훈련으로 문제 해결 능력을 키우고 파이썬을 마스터하길 바란다.\n\n※ 본 도서는 대학 강의용 교재로 개발되었으므로 연습문제 해답은 제공하지 않습니다.'},
  {'title': '파이썬 워크북',
   'link': 'https://search.shopping.naver.com/book/catalog/52417646624',
   'image': 'https://shopping-phinf.pstatic.net/main_5241764/52417646624.20250111113916.jpg',
   'author': '안기수',
   'discount': '13500',
   'publisher': '생능출판',
   'pubdate': '20250115',
   'isbn': '9791192932682',
   'description': '파이썬 언어의 가장 큰 특징은 문법이 간결하여 배우기 쉽다는 것이다. 그러나 이미 만들어진 프로그램이나 어플을 단지 활용만 해보다가 그 프로그램이 어떤 언어로 만들어진 것인지, 그 어플이 어떤 과정을 거쳐서 만들어진 것인지를 알아보려는 시점에서 그것을 만드는데 사용한 언어가 아무리 쉽다하더라도 컴퓨터 언어 자체가 우리가 사용하는 언어처럼 익숙한 것이 아니므로 어려움을 느낄 수밖에 없다.\n\n컴퓨터 언어의 실습시간에 학생들에게 “궁금한 것 또는 이해되지 않는 부분에 대해 질문하세요?”라고 물어봤을 때 언젠가 한 학생이 “뭘 알아야 질문을 하죠?”라고 말한 적이 있다. 그 말의 의미가 무엇인지 대략은 이해하지만, 나의 대답은 이러했다. “뭘 알면 질문할 필요가 있나요? 모르니까 질문을 하는 것이 아닐까요?”\n여기서 중요한 것은 그 학생의 경우 수업내용을 이해하지 못하면 무슨 질문을 해야 할지를 모른다는 것이고, 조금이라도 뭘 좀 알고 있어야, 지식이 좀 있어야 질문할 수 있다고 생각한다는 점이다. 이러한 생각이 틀렸다고 생각하지는 않지만 학생들마다 수업에 대한 이해 정도가 다르므로 무엇을 이해했고 무엇을 이해하지 못하고 있는 것인지를 스스로 판단할 수 있도록 유도한다면 이러한 문제가 해소되지 않을까 생각한다.\n\n프로그램 언어를 설명한 대부분의 책들은 각 단원의 마지막 부분에 있는 연습문제를 통해 이해의 정도를 스스로 판단하도록 하지만, 풀어나갈 문제의 난이도 또는 주관식 문제가 주는 부담감으로 문제를 풀 엄두가 나지 않는 경우가 발생하기도 한다. 이러한 부담감을 줄여주기 위한 방법을 고민하다가 가급적 학생들이 문제를 스스로 해결해 나갈 수 있도록 문제 풀이에 관심을 갖게 하고, 틀린 이유와 원인을 실습을 통해 확인하고 메모해가면서 자기주도의 반복 학습으로 유도하기 위하여 워크북을 이용하고자 한다.\n따라서 이 워크북은 수업이 끝나고 과제로 남겨두는 것이 아니라 수업 시간에 학생들 스스로가 직접 코딩하고 실행하여 결과를 확인하고, 나름대로 틀린 부분들을 요약하는 오답노트로 활용하여 프로그램 작성에 대한 이해도와 자신감을 점차 높이도록 구성하였다.'},
  {'title': '으뜸 파이썬 (개정판)',
   'link': 'https://search.shopping.naver.com/book/catalog/48359296619',
   'image': 'https://shopping-phinf.pstatic.net/main_4835929/48359296619.20240612092113.jpg',
   'author': '박동규^강영민',
   'discount': '32300',
   'publisher': '생능출판',
   'pubdate': '20240614',
   'isbn': '9791192932675',
   'description': '이 책의 구성\n초판과 마찬가지로 이 책은 대학에서 교양 과정 수강생과 전공자들이 쉽게 프로그래밍을 접하고 흥미를 가질 수 있도록 구성하였다. 이를 위하여 파이썬 설치부터 기초적인 출력문, 연산자, 조건문, 반복문, 함수, 클래스 등에 관련된 설명과 많은 문제 풀이를 제공하고 있다. 뿐만 아니라, 다양한 모듈의 활용 방법과 넘파이 패키지 등 파이썬에 관한 깊이 있는 내용도 함께 다루고 있다. 각 장의 심화 내용은 [심화학습]이라는 별도의 표시를 하였다. 이 [심화학습]은 학생들의 흥미를 유발하는 깊이 있는 내용이며, 강사의 필요에 따라서 선택적으로 강의할 수 있다.\n\n개정판에서 초판과 달라진 점\n초판은 11개 장(chapter)로 구성되었으나 개정판은 13개 장(chapter)로 구성되어 있다.\n이 책은 개인 학습서로써도 활용 가능하지만, 대학의 15주 수업 교재로서도 적절하도록 고심하였다. 중간고사와 기말고사를 제외하고 13주 수업에서 다룰 수 있도록 파이썬 학습에 필요한 내용을 정리하였다. 초판에서는 일부 장들이 담고 있는 내용의 양이 균형 잡히지 않았던 부분이 있었지만, 이를 적절히 배분하여 새롭게 장을 구성하였다.\n초판과 개정판을 비교하면, 우선 초판 3장 제어문은 그 양이 한 주의 수업으로 다루기에는 방대하여 개정판에서는 조건문과 반복문으로 나누어 각각을 3장과 4장의 별도 장에담았다.\n이에 따라 초판의 4장에서 11장의 내용들은 개정판의 5장에서 12장까지를 차지하게 된다. 이와 함께 개정판 8장에서는 터틀 그래픽과 tkinter와 같이 파이썬 문법과 직접적 관련이 없는 활용 부분을 덜어내고 13장으로 옮겨 따로 정리하였다.\n5장에서 12장까지의 내용은 초판의 내용을 그대로 옮긴 것은 아니다. 10장의 클래스와 객체지향에서는 상속과 관련한 내용을 새롭게 다루었고, 11장의 파이썬답게 코딩하기는 초판에서 다루었던 람다함수와 리스트 축약뿐만 아니라 파이썬의 장점을 더욱 잘 활용할 수 있는 코딩 방법에 대한 이해를 돕기 위해 노력했다. 그리고 12장의 넘파이는 외부 모듈인 넘파이를 활용하는 방법을 소개하는 데에 그치지 않고 파이썬이 성공을 거두는 데에 큰 기여를 한 넘파이가 가진 장점을 이해하고 활용할 수 있도록 개정하였다.\n13장에서는 외부 모듈을 활용하여 조금 더 재미있는 파이썬 코딩을 할 수 있도록 하면서 초판에서 정확히 다루어지지 않았던 싱글턴 객체의 개념에 대한 설명 등을 더했다. 이러한 설명을 통해 외부 모듈의 클래스를 활용할 때 더욱 정확하고 바르게 사용할 수 있을 것이다.'},
  {'title': '이지파이썬 1 (그림과 스토리텔링으로 이해하는 쉽고 재미있는 파이썬)',
   'link': 'https://search.shopping.naver.com/book/catalog/49922621623',
   'image': 'https://shopping-phinf.pstatic.net/main_4992262/49922621623.20240824073231.jpg',
   'author': '한국인공지능아카데미',
   'discount': '14400',
   'publisher': '클라우드북스',
   'pubdate': '20240901',
   'isbn': '9788997793273',
   'description': '"이지 파이썬"은 프로그래밍 초보자를 위해 만든 쉽고 친근한 파이썬 입문서입니다. 재미있는 상황과 그림으로 프로그래밍 개념을 설명하고, 그 개념들이 상황과 함께 기억에 남도록 합니다. 또한, 파이썬 학습 시 번거로웠던 파이썬 설치과정 없이도 파이썬을 실습할 수 있도록 이지파이썬 전용 사이트를 제공합니다. \nwww.ezst.kr에 로그인하면 사이트에서 바로 예제 코드를 직접 연습하고 즉각적인 피드백도 받을 수 있으며, 각 장마다 퀴즈를 통해 더 많은 코드를 접하면서 실력을 점검할 수 있도록 합니다. 또한, 각 장의 마지막에는 재미있는 스토리를 기반으로 만든 미션도 제공하여, 파이썬 학습을 더욱 재미있게 만듭니다.'},
  {'title': '이지파이썬 2 (그림과 스토리텔링으로 이해하는 쉽고 재미있는 파이썬)',
   'link': 'https://search.shopping.naver.com/book/catalog/49926240618',
   'image': 'https://shopping-phinf.pstatic.net/main_4992624/49926240618.20240825071509.jpg',
   'author': '한국인공지능아카데미',
   'discount': '14400',
   'publisher': '클라우드북스',
   'pubdate': '20240901',
   'isbn': '9788997793280',
   'description': '"이지 파이썬"은 프로그래밍 초보자를 위해 만든 쉽고 친근한 파이썬 입문서입니다. 재미있는 상황과 그림으로 프로그래밍 개념을 설명하고, 그 개념들이 상황과 함께 기억에 남도록 합니다. 또한, 파이썬 학습 시 번거로웠던 파이썬 설치과정 없이도 파이썬을 실습할 수 있도록 이지파이썬 전용 사이트를 제공합니다. \nwww.ezst.kr에 로그인하면 사이트에서 바로 예제 코드를 직접 연습하고 즉각적인 피드백도 받을 수 있으며, 각 장마다 퀴즈를 통해 더 많은 코드를 접하면서 실력을 점검할 수 있도록 합니다. 또한, 각 장의 마지막에는 재미있는 스토리를 기반으로 만든 미션도 제공하여, 파이썬 학습을 더욱 재미있게 만듭니다.'},
  {'title': '이지파이썬 1 (그림과 스토리텔링으로 이해하는 쉽고 재미있는 파이썬)',
   'link': 'https://search.shopping.naver.com/book/catalog/49922615621',
   'image': 'https://shopping-phinf.pstatic.net/main_4992261/49922615621.20240828071013.jpg',
   'author': '한국인공지능아카데미',
   'discount': '0',
   'publisher': '클라우드북스',
   'pubdate': '20240901',
   'isbn': '9788997793266',
   'description': '"이지 파이썬"은 프로그래밍 초보자를 위해 만든 쉽고 친근한 파이썬 입문서입니다. 재미있는 상황과 그림으로 프로그래밍 개념을 설명하고, 그 개념들이 상황과 함께 기억에 남도록 합니다. 또한, 파이썬 학습 시 번거로웠던 파이썬 설치과정 없이도 파이썬을 실습할 수 있도록 이지파이썬 전용 사이트를 제공합니다.'},
  {'title': '파이썬 강좌',
   'link': 'https://search.shopping.naver.com/book/catalog/39215805619',

# 함수화

In [4]:
result={}
for item in data['items']:
    for key, value in item.items():
        result.setdefault(key, []).append(value)
df=pd.DataFrame(result)
df

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,파이썬,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324609...,홍의경,30400,생능출판,20220309,9788970506784,코딩 실력을 키우는 지름길은 실습이다.\n\n2008년 즈음에 검인정 중학교 교과서...
...,...,...,...,...,...,...,...,...,...
95,파이썬아 반가워! (20일 안에 끝내는 코딩),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324560...,곽문기,12420,다락원,20180827,9788927747147,"소프트웨어 교육 왜 해야 할까요? \n『파이썬아 반가워!』, 블록 코딩부터 텍스트 ..."
96,이젠 나도! 파이썬 (지금 시작해도 괜찮아),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324877...,이지선,22500,성안당,20191004,9788931556278,17일 만에 비전공자도 제대로 끝내는 파이썬! \n저자 직강 무료 동영상 강의와 함...
97,파이썬 코딩 도장,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324692...,남재윤,11400,길벗,20181130,9791160506181,외우기만 해서는 파이썬도 어렵다!\n프로그래밍은 연습으로 배우는 것!\n문법을 외우...
98,파이썬3 바이블 (스크립트 언어의 지존을 만나다!),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324934...,이강성,10600,프리렉,20131001,9788965400493,『파이썬3 바이블』은 파이썬에 대한 이해와 활용을 한 권으로 해결할 수 있는 책이다...
99,파이썬 클린 코드 (유지보수가 쉬운 파이썬 코드를 만드는 비결),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324727...,마리아노 아나야,12600,터닝포인트,20190225,9791161340463,견고하면서도 확장성이 뛰어난 파이썬 코드를 만드는 비법\n\n파이썬은 누구나 쉽게 ...

In [22]:
data['items']

[{'title': '머신 러닝 교과서 with 파이썬, 사이킷런, 텐서플로 (머신 러닝, 딥러닝 핵심 알고리즘부터 GAN, 강화 학습까지!)',
  'link': 'https://search.shopping.naver.com/book/catalog/32438179659',
  'image': 'https://shopping-phinf.pstatic.net/main_3243817/32438179659.20230606103925.jpg',
  'author': '세바스찬 라시카^바히드 미자리리',
  'discount': '30800',
  'publisher': '길벗',
  'pubdate': '20210331',
  'isbn': '9791165215187',
  'description': '아마존 머신 러닝 분야 베스트셀러! 그 명성 그대로!\n머신 러닝, 딥러닝 핵심 알고리즘에서 GAN, 강화 학습까지!\n\n코드 실행만으로는 머신 러닝과 딥러닝을 충분히 이해할 수 없다. 머신 러닝과 딥러닝을 제대로 이해하고 싶다면 코드 외에도 관련 이론과 알고리즘의 뒤편에 있는 수학 개념을 알아야 한다. 이 책은 이해를 돕는 개념 설명, 머신 러닝과 딥러닝 핵심 알고리즘의 작동 방식과 사용 방법, 그 밑바탕이 되는 수학, 실용적인 예제, 빠지기 쉬운 함정을 피하는 방법까지 이론과 코드를 균형 있게 설명한다. 파이썬 언어와 파이썬 기반의 머신 러닝 핵심 라이브러리(SciPy, NumPy, scikit-learn, Matplotlib, Pandas)를 사용해 머신 러닝을, 텐서플로(TensorFlow 2)를 사용해 딥러닝을 실습해본다. 특히 딥러닝은 최신 텐서플로 2에 맞춰 대폭 수정 및 보강되었다. 그러고 나서 GAN과 강화 학습도 자세하게 다룬다. 머신 러닝과 딥러닝 기본기를 탄탄하게 다지고 싶은 분께 적절하다.'},
 {'title': '생활코딩 머신러닝 실습편 with 파이썬 텐서플로 (누구나 쉽게 시작하는 인공지능 첫걸음)',
  'link': 'https://search.shopping.naver.com/book/catalog/32467096228',
  'image': 'https://shopping-phinf.pstatic.net/main_3246709/32467096228.20230704085329.jpg',
  'author': '이숙번^이고잉',
  'discount': '21600',
  'publisher': '위키북스',
  'pubdate': '20211215',
  'isbn': '9791158392994',
  'description': '너무 어려워서 높은 벽처럼 느껴졌던 ‘딥러닝(deep learning)’, 이 책과 함께라면 쉽게 시작할 수 있습니다!\n\n《생활코딩 머신러닝 실습편 with 파이썬 텐서플로》는 초등학생부터 어르신까지, 딥러닝이 궁금하고 직접 코딩해보고 싶은 모든 분을 위한 책입니다. 복잡한 원리와 수학을 몰라도, 휴대폰 사용법을 익히듯 쉽고 재미있게 딥러닝을 배울 수 있습니다.\n\n구글의 딥러닝 라이브러리인 텐서플로(TensorFlow)를 활용해 간단한 형태의 딥러닝 모델을 작성합니다. 실습은 무료로 사용할 수 있는 구글 코랩(Colaboratory)과 스프레드시트(Google Sheets)를 이용해 이뤄지므로 고성능 컴퓨터가 없어도 충분히 실습할 수 있습니다.'},
 {'title': '프로그래머를 위한 수학 (파이썬으로 하는 3D 그래픽스, 시뮬레이션, 머신러닝)',
  'link': 'https://search.shopping.naver.com/book/catalog/32473358591',
  'image': 'https://shopping-phinf.pstatic.net/main_3247335/32473358591.20230919130646.jpg',
  'author': '폴 올랜드',
  'discount': '37630',
  'publisher': '한빛아카데미',
  'pubdate': '20211229',
  'isbn': '9791156645719',
  'description': '개발자에게 필요 없는 수학은 없다\n롱런하고 싶은 프로그래머를 위한 핵심 비법!\n\n"3D 그래픽스, 시뮬레이션, 머신러닝"\n세 분야의 공통점은 수학적 논리와 사고방식이 필요하다는 것!\n프로그래밍에 수학을 더하면 작업 효율과 완성도가 현저히 달라진다.\n여기, 프로그래머로 오래 살아남을 수 있는 비법이 담긴 가장 친절한 수학책을 소개한다.\n파이썬을 이용하여 3D 그래픽스, 게임 설계, 시뮬레이션, 머신러닝 알고리즘에 필요한 수학을 쉽게 설명하고,\n상황별 다양한 코딩을 직접 해보며 수학 개념이 작동하는 방식을 깨달을 수 있도록 구성하였다.\n이제, 선형대수학과 미분적분학이 파이썬 코드 안에서 어떻게 활력 있게 움직이는지 직접 확인해보자!\n\n이 책의 주요 내용\nㆍ 컴퓨터 그래픽스 관련 벡터 기하학\nㆍ 행렬과 일차변환\nㆍ 미분적분학의 핵심 개념\nㆍ 시뮬레이션과 최적화\nㆍ 이미지 처리와 신호 처리\nㆍ 회귀와 분류에 대한 머신러닝 알고리즘'},
 {'title': '머신 러닝·딥 러닝에 필요한 기초 수학 with 파이썬',
  'link': 'https://search.shopping.naver.com/book/catalog/32439211618',
  'image': 'https://shopping-phinf.pstatic.net/main_3243921/32439211618.20250429073615.jpg',
  'author': '조준우',
  'discount': '18500',
  'publisher': '인사이트',
  'pubdate': '20201104',
  'isbn': '9788966262854',
  'description': '수학으로 다지는 머신 러닝·딥 러닝 기본기!\n\n이 책은 소위 머신 러닝·딥 러닝 ‘왕초보’라 할 수 있는 분들을 대상으로 약 2년간 여러 차례 강의를 진행한 콘텐츠를 토대로 만들어졌습니다. 저자는 강의를 하는 동안 독자의 눈높이에 맞게 내용들을 다듬었으며, 독자와 머신 러닝 사이의 간극을 메우기 위해 머신 러닝·딥 러닝에 필요한 기초 수학만을 간추려 놓았습니다.\n우선 1장에서는 간단한 선형회귀를 직접 손으로 시도해 보면서 선형회귀에 대한 감을 익힙니다. 그리고 2장부터 9장까지 함수, 미분, 행렬과 벡터, 최적화, 인공신경망에 대한 내용을 학습합니다. 이렇게 학습한 내용으로 바탕으로 10장에서 선형회귀를 다시 구현합니다.\n이 책은 다음과 같은 특징으로 차별화를 시도하였습니다.\n\n배운 내용이 머신 러닝에 어떻게 활용되는지 가능한 한 실용적인 비유와 예를 들어 설명하였습니다.\n파이썬 등 프로그래밍 도구를 이용하여 배운 수학 개념을 눈으로 확인해 볼 수 있게 하였습니다.\n수학과 실제 작업을 단단하게 연결하는 경험을 통해서 앞으로 새로운 알고리즘을 공부할 때도 스스로 학습할 수 있는 능력을 기를 수 있도록 하였습니다.'},
 {'title': '심층 강화학습 인 액션 (기본 개념부터 파이썬 기반의 최신 알고리즘 구현까지)',
  'link': 'https://search.shopping.naver.com/book/catalog/32455948250',
  'image': 'https://shopping-phinf.pstatic.net/main_3245594/32455948250.20221227203944.jpg',
  'author': '알렉스 짜이^브랜던 브라운',
  'discount': '27000',
  'publisher': '제이펍',
  'pubdate': '20201117',
  'isbn': '9791190665612',
  'description': '프로젝트로 배우는 심층 강화학습의 이론과 실제!\n\n이 책 『심층 강화학습 인 액션』은 환경이 제공하는 직접적인 피드백에 기반해서 환경에 적응하고 자신을 개선해 나가는 에이전트의 구현 방법을 설명한다. 흐름이 있는 하나의 강좌 형태로 구성된 이 책에서 여러분은 심층 강화학습의 기본 기법과 고급 기법을 미로 탈출이나 비디오 게임 플레이 같은 흥미로운 예제를 통해서 배우게 된다. 그 과정에서 심층 Q 신경망과 정책 기울기 방법을 포함한 여러 핵심 알고리즘을 익힐 수 있고, PyTorch와 OpenAI Gym 같은 업계 표준에 해당하는 라이브러리에도 익숙해질 것이다.'},
 {'title': '파이썬과 리액트를 활용한 주식 자동거래 시스템 구축 (데이터 수집부터 거래 자동화, API 서버, 웹 개발, 데이터 분석까지 아우르는)',
  'link': 'https://search.shopping.naver.com/book/catalog/32440898722',
  'image': 'https://shopping-phinf.pstatic.net/main_3244089/32440898722.20250326071214.jpg',
  'author': '박재현',
  'discount': '17820',
  'publisher': '위키북스',
  'pubdate': '20200212',
  'isbn': '9791158391881',
  'description': '파이썬을 이용해 데이터를 수집, 저장, 가공, 분석하는 방법부터 리액트를 이용해 사용자의 화면까지 개발하는 방법까지 한 권에 담았다. 증권사(이베스트)에서 제공하는 API를 이용해 파이썬으로 거래 자동화 시스템을 개발해보며, 외부로 기능을 제공하기 위한 Restful API 서버를 구현한다. 또한 리액트를 이용해 웹과 앱에 필요한 화면을 만들어 보고, 데이터 분석에 필요한 기본적인 방법을 익히고, 퀀트 전략을 구현해 본다.'},
 {'title': '알짜배기 예제로 배우는 OpenCV (파이썬과 C++로 마스터하는 OpenCV 프로그래밍)',
  'link': 'https://search.shopping.naver.com/book/catalog/32445061894',
  'image': 'https://shopping-phinf.pstatic.net/main_3244506/32445061894.20230207163041.jpg',
  'author': '이정주',
  'discount': '28800',
  'publisher': '비제이퍼블릭',
  'pubdate': '20200429',
  'isbn': '9791190014915',
  'description': '영상 처리의 기본 개념부터\n개발 환경 구축까지 예제로 한번에\n\nOpenCV는 오픈소스 컴퓨터 비전 라이브러리로, 공통의 API를 사용하여 컴퓨터 비전 또는 영상 처리 프로그래밍을 할 수 있는 환경을 제공합니다. 또한 윈도우, 맥, 리눅스, iOS, 안드로이드 등 다양한 운영체제에서 사용이 가능하다는 장점도 가지고 있습니다. 이 책에서는 파이썬을 사용하여 빠르게 OpenCV 프로그램을 개발하고 C++을 사용하여 속도를 최적화할 수 있도록 두 가지 언어에 대한 예제를 제공합니다. 안드로이드에서 OpenCV 프로그램을 동작시키기 위해 필요한 예제도 다루고 있기 때문에 초심자에게 큰 도움이 될 것입니다.'},
 {'title': '파이썬을 이용한 인터랙티브 대시보드 만들기 (컬러판)',
  'link': 'https://search.shopping.naver.com/book/catalog/32466654097',
  'image': 'https://shopping-phinf.pstatic.net/main_3246665/32466654097.20220519221050.jpg',
  'author': '홍성준^홍성수',
  'discount': '32800',
  'publisher': '부크크(bookk)',
  'pubdate': '20210601',
  'isbn': '9791137246799',
  'description': "파이썬(Python)을 배웠지만 '데이터 시각화'가 어려운, 혹은 '대시보드 개발'을 해보고 싶은 분들에게 적합한 책입니다. \nPlotly와 Dash를 이용한 그래프 구성의 기본부터 웹 대시보드 개발과 배포까지 단계별 예제를 통해 정리하였습니다.\n\n대시보드1. 국가별 매출 데이터 현황 비교\n대시보드2. COVID-19 팬데믹 영향으로 인한 호흡기 질환 발생 현황 비교\n\n이 책을 통해 다양한 데이터 시각화와 대시보드를 구현하여 데이터 특성을 잘 이해할 수 있고, 더 나아가 데이터 전문가 또는 분석가로서의 역량을 키울 수 있습니다."},
 {'title': '코딩 초보자를 위한 데이터 중심의 파이썬 프로그래밍 (코딩 초보자를 위한 데이터 중심의)',
  'link': 'https://search.shopping.naver.com/book/catalog/32494110706',
  'image': 'https://shopping-phinf.pstatic.net/main_3249411/32494110706.20221230074852.jpg',
  'author': '길준민^박지수',
  'discount': '20900',
  'publisher': '인피니티북스',
  'pubdate': '20191230',
  'isbn': '9791185578583',
  'description': '데이터 활용과 논리적 사고를 위한 파이썬 프로그래밍 \n\n이 책은 데이터 활용 능력과 함께 논리적 사고와 문제해결력을 배양하기 위해 파이썬 프로그래밍 언어에 기반한 데이터와 코딩의 기본 원리와 지식을 학습하며, 특히 데이터와 코딩에 대한 기능과 활용을 파이썬 프로그래밍 언어의 터틀 그래픽을 통해 재미있고, 쉽게 학습할 수 있도록 하였으며, 이를 통해 다양한 전공 분야와 연계 가능한 융합적 사고능력을 배양하는 것을 목표로 한다. \n\n한편, 컴퓨터 비전공자도 쉽게 이해하고 활용할 수 있는 다양하고 풍부한 예제를 제공하여 데이터와 코딩에 관한 기본 개념의 정립뿐 아니라 응용문제를 제공함으로써 문제해결력 증진에 도움이 되는 논리적 사고 배양에 초점이 맞춰져 있다. 또한 데이터와 코딩에 관심을 둔 입문자들이나 프로그래밍 초보자들에게 프로그래밍의 기본 개념을 정립해 줄 충분한 입문서가 될 것이다.'},
 {'title': '파이썬 Jupyter Notebook 실전 입문 (데이터 분석에 필수적인 Jupyter Notebook 완벽 가이드)',
  'link': 'https://search.shopping.naver.com/book/catalog/32465888833',
  'image': 'https://shopping-phinf.pstatic.net/main_3246588/32465888833.20250601073957.jpg',
  'author': '이케우치 다카히로',
  'discount': '12000',
  'publisher': '터닝포인트',
  'pubdate': '20180601',
  'isbn': '9791161340210',
  'description': 'Python을 이용한 데이터 분석에 관심이 있거나 Jupyter Notebook의 사용법을 배우고 싶어 하는 초보자부터 이미 Jupyter Notebook을 사용하고 있는 사용자까지 폭넓은 층을 위해 구성되어 있다. Jupyter Notebook을 처음 접하는 사용자는 Jupyter Notebook에서 데이터 가공 및 집계를 할 수 있거나 다양한 그래프를 작성할 수 있는 방법을 배울 수 있고 기존 사용자는 그래프 패키지에 대해 더욱 깊이 있게 배울 수 있다.'},
 {'title': '머신 러닝 교과서 with 파이썬, 사이킷런, 텐서플로 (Numpy, scikit-learn 0.2x, TensorFlow 2.x로 배우는 머신 러닝)',
  'link': 'https://search.shopping.naver.com/book/catalog/32486418789',
  'image': 'https://shopping-phinf.pstatic.net/main_3248641/32486418789.20220527030816.jpg',
  'author': '세바스찬 라시카^바히드 미자리리',
  'discount': '10000',
  'publisher': '길벗',
  'pubdate': '20190524',
  'isbn': '9791160507966',
  'description': '아마존 머신 러닝 분야 베스트셀러!\n기본기에 충실한 머신 러닝 입문서\n\n코드 실행만으로는 머신 러닝을 충분히 이해할 수 없다. 머신 러닝을 제대로 이해하고 싶다면 코드 외에도 머신 러닝 이론과 머신 러닝 알고리즘의 뒤편에 있는 수학 개념을 알아야 한다. 이 책은 이해를 돕는 개념 설명, 머신 러닝 핵심 알고리즘의 작동 방식과 사용 방법, 그 밑바탕이 되는 수학, 실용적인 예제까지 이론과 코드를 균형 있게 설명한다. 파이썬 언어와 파이썬 기반의 머신 러닝 핵심 라이브러리(SciPy, NumPy, scikit-learn, Matplotlib, Pandas)를 사용해 머신 러닝을, 텐서플로를 사용해 딥러닝을 실습하면서 머신 러닝과 딥러닝 핵심 알고리즘을 설명하고, 간단한 알고리즘은 처음부터 직접 구현해본다. 또한, 사이킷런의 기여자이자 mlxtend 라이브러리 제작자인 저자가 오랜 기간 머신 러닝 개발자로 일하면서 익힌 노하우도 책 곳곳에서 만날 수 있다. 머신 러닝에 관심 있는 분들에게 추천한다.'},
 {'title': 'matplotlib을 이용한 데이터 시각화 프로그래밍 (파이썬으로 구현하는 데이터 분석용 2D & 3D 그래프)',
  'link': 'https://search.shopping.naver.com/book/catalog/32480678265',
  'image': 'https://shopping-phinf.pstatic.net/main_3248067/32480678265.20221230073558.jpg',
  'author': '알렉상드르 드베르',
  'discount': '22500',
  'publisher': '에이콘출판',
  'pubdate': '20150116',
  'isbn': '9788960776685',
  'description': '맷플롯립(matplotlib)을 설치하는 방법을 먼저 알려주고, 다양한 2차원 그래프를 출력하는 방법을 소개하고, 이어서 자신만의 컬러와 스타일을 사용자 정의하는 방법, 주석 추가, 3D 그래프 처리, 타 애플리케이션과 통합하는 방법 등 기초부터 활용까지 고르게 설명하면서 예제 코드 중심으로 다룬다. 이 책에 제공되는 맷플롯립 코드는 다양한 분야에서 데이터 분석을 위한 시각화에 적용할 수 있다.\n\n\n\n필요한 모든 일반적인 플롯을 생성하는 방법, 주석과 정교한 범례로 플롯을 풍요롭게 하는 방법, 플롯 제어와 컬러, 선 스타일, 크기를 조정하는 방법, 플롯에 차원을 추가해 3D화, 애플리케이션에 플롯 통합, 작업 자동화와 그래프 일괄처리 생성, 맷플롯립으로 대화형 플롯 생성 등을 다루고 있다.'},
 {'title': 'IoT 사물인터넷을 위한 라즈베리파이 4 정석 (파이썬을 활용한 센서제어 및 나만의 가상비서 만들기)',
  'link': 'https://search.shopping.naver.com/book/catalog/32464611669',
  'image': 'https://shopping-phinf.pstatic.net/main_3246461/32464611669.20250415091711.jpg',
  'author': '최주호^김재범^정동진',
  'discount': '13200',
  'publisher': '앤써북',
  'pubdate': '20191130',
  'isbn': '9791185553573',
  'description': '『IoT 사물인터넷을 위한 라즈베리파이 4 정석』은 왕초보도 라즈베리파이를 이용해 다양한 IoT를 직접 개발할 수 있도록 전기전자 기초 원리부터 센서제어 및 나만의 가상비서 만들기 등 초수/중수/고수 예제 실습과 실전 프로젝트까지 단계별로 구성하였다.\n \n라즈베리파이가 무엇인지부터 시작하여 전기, 전자와 배경지식이 부족한 분들도 볼 수 있도록 관련 부품의 동작 원리와 파이썬 기초 내용부터 아주 쉽게 설명하였습니다. \n\n이 책은 라즈베리파이 4와 라즈베리파이 3 버전 모두 사용할 수 있다. 독자는 라즈베리파이 3, 4 중 어떤 버전을 선택해도 이 책의 내용을 학습하는데 충분하도록 환경 설정 방법을 자세히 설명하였다. \n\n이 책은 라즈베리파이로 IoT를 만들 때 필요한 거의 모든 기술을 담았다!\n- 왕초보를 위한 알기 쉬운 리눅스/파이썬/전자 기초\n- 각종 센서 활용하기\n- Flask를 활용한 센서 제어하기\n- 라즈베리파이 카메라 활용하기\n- NodeMCU 활용하기\n- 포트포워딩과 슈퍼디엠지로 우리집 LED 제어하기\n- 머신러닝 Open API와 가상 비서 만들기\n- Git 버전관리(형상관리)\n\n이 책은 부품 및 전자회로가 어떻게 동작하는지와 IoT 동작을 위해 어떻게 코딩해야 하는지를 도식화와 한 줄 한 줄 등으로 진짜 친절하게 설명하였다. \n\n이 책에서 사용하는 전체 부품은 5쪽과 19~21쪽을 참조한다. \n\n※ 이 책의 실습에 필요한 부품은 편리하게 본인에 맞게 선택해서 키트로 구매할 수 있다. 구매 관련 자세한 내용은 19쪽을 참조한다.'},
 {'title': '파이썬과 케라스를 이용한 딥러닝/강화학습 주식투자 (퀀트 투자 알고리즘 트레이딩을 위한 최첨단 해법 입문)',
  'link': 'https://search.shopping.naver.com/book/catalog/32474235838',
  'image': 'https://shopping-phinf.pstatic.net/main_3247423/32474235838.20220627092408.jpg',
  'author': '퀀티랩',
  'discount': '0',
  'publisher': '위키북스',
  'pubdate': '20200427',
  'isbn': '9791158392031',
  'description': '실제 주식 데이터를 이용해 파이썬으로 강화학습 주식투자 프로그램을 직접 구현해 봅니다!\n\n강화학습은 스스로 학습하는 머신러닝 기법으로 주식 데이터 학습에 잘 적용되는 기법입니다. 이 책은 파이썬을 이용한 강화학습 기반의 주식투자 시뮬레이션 프로그램 개발에 대해 설명합니다. 이를 위한 이론과 코드 수준의 상세한 설명을 수록했습니다. 이 책을 통해 딥러닝과 강화학습을 이해하고 주식투자를 비롯한 다양한 도메인에서 활용할 수 있을 것입니다.\n\n★ 이 책에서 다루는 내용 ★\n◎ 딥러닝과 강화학습의 이론\n◎ 주식투자에 강화학습을 적용하는 방법\n◎ 강화학습 기반의 주식투자 시스템 개발 방법\n◎ 강화학습을 위한 실제 주식 데이터 획득 및 처리 방법\n◎ 강화학습으로 주식 데이터를 학습하는 방법\n◎ 학습한 강화학습 모델을 활용하는 방법\n◎ 강화학습 주식투자 시스템 커스터마이징 방법'},
 {'title': '파이썬으로 배우는 Anti-Virus 구조와 원리 (예제와 오픈소스를 통해 이해하는 악성코드의 진단과 치료)',
  'link': 'https://search.shopping.naver.com/book/catalog/32456292851',
  'image': 'https://shopping-phinf.pstatic.net/main_3245629/32456292851.20240129074239.jpg',
  'author': '최원혁',
  'discount': '30600',
  'publisher': '비제이퍼블릭',
  'pubdate': '20170927',
  'isbn': '9791186697412',
  'description': '파이썬을 통해 전체적인 백신의 구조와 동작 원리를 정확한 이해할 수 있도록 안내한다. 악성코드를 치료하는 백신이 어떻게 동작하는지 그리고 어떻게 개발하면 되는지 기록으로 남기기 위해, 저자가 과거 개발했던 키콤백신을 오픈소스로 재탄생시켰다. 이 키콤백신은 사용자에게 백신의 원리를 쉽게 이해시키기 위해 파이썬 언어를 선택하고 있다.\n\n\n\n소스코드에 존재하지만 주석만으로 설명되지 않는 부분들을 가급적 자세하고 상세히 설명해 악성코드와 백신이 작동하는 구조와 원리에 대해 더 깊이 이해할 수 있도록 했다. 파이썬 프로그래밍에 대해 새로운 예제코드가 필요한 이들이나 백신 개발 및 오픈소스 프로젝트에 참여하고 싶은 이들에게 적합하다.'},
 {'title': '이토록 쉬운 딥러닝을 위한 기초 수학 with 파이썬',
  'link': 'https://search.shopping.naver.com/book/catalog/32436152495',
  'image': 'https://shopping-phinf.pstatic.net/main_3243615/32436152495.20221019104945.jpg',
  'author': '마스이 도시카츠',
  'discount': '18000',
  'publisher': '루비페이퍼',
  'pubdate': '20190813',
  'isbn': '9791186710524',
  'description': '딥러닝도 모르겠는데 수학은 손놓은 지 오래다?\n이 책을 한마디로 설명하자면 ‘수학 기초와 파이썬으로 배우는 머신러닝과 딥러닝 기초’라고 할 수 있습니다. 기초 수학을 설명한 후 여기서 파생하는 머신러닝과 딥러닝의 주요 개념인 회귀, 신경망, 경사하강법, 합성곱 신경망, 순환 신경망, 강화 학습 등을 설명합니다. 그리고 각 개념을 구현하는 파이썬 코드도 함께 소개합니다.'},
 {'title': '파이썬을 활용한 공격적 & 방어적 해킹 프로그래밍 세트 (창의적이고 새로운 관점을 제시하는 해킹과 방어 기법)',
  'link': 'https://search.shopping.naver.com/book/catalog/32490345813',
  'image': 'https://shopping-phinf.pstatic.net/main_3249034/32490345813.20220527063553.jpg',
  'author': '저스틴 지이츠',
  'discount': '0',
  'publisher': '에이콘출판',
  'pubdate': '20150511',
  'isbn': '9788960777064',
  'description': '[파이썬을 활용한 공격적 & 방어적 해킹 프로그래밍 세트]는 해커와 모의 침투 테스터를 위한 공격용 파이썬 프로그래밍을 소개하는 『Black Hat Python』과 디버거, 트로이목마, 퍼저, 에뮬레이터 같은 해킹 툴과 해킹 기술의 기반 개념을 설명하며, 기존 파이썬 기반 보안 툴의 사용법과 기존 툴이 만족스럽지 않을 때 직접 제작하는 방법도 알려주는 『파이썬 해킹 프로그래밍』을 엮은 세트 상품이다.'},
 {'title': '슬기로운 코딩 생활 with 파이썬 으랏차차 기초편 (즐겁게 시작하고 똑똑하게 끝내는 코딩 교과서)',
  'link': 'https://search.shopping.naver.com/book/catalog/32490279658',
  'image': 'https://shopping-phinf.pstatic.net/main_3249027/32490279658.20220527030402.jpg',
  'author': '김정욱',
  'discount': '10800',
  'publisher': '루비페이퍼',
  'pubdate': '20180515',
  'isbn': '9791186710333',
  'description': '수학, 과학, 국어, 사회 등 실제 초중등 교과 과목과 연계된 예제로 코딩력과 학습력까지 단번에 쑥쑥 슬기로운 코딩 생활, 이렇게 공부하세요!\n\nStage 1 재미있는 코딩 세계로 초대합니다!\n첫인사를 나눌 때는 먼저 자기소개를 해야 겠죠? 직접 이야기를 만들고 몰래 러브레터를 주고받으면서 놀다 보면 자연스럽게 코딩을 시작하기 전 알아 두어야 할 것들을 배울 수 있어요.\n\nStage 2 코딩의 기본은 연산!\n소풍 도시락에 맛있는 음식들을 꽉꽉 채워 넣으려면 음식 크기와 부피를 알맞게 재고 넣어야 해요. 척하면 척! 숫자만 입력하면 결과를 알려주는 척척 계산기를 코딩해 볼까요?\n\nStage 3 조건에 따라 다르게 행동해요\n키가 130cm가 넘어야 탈 수 있는 자이로드롭, 직접 설계해보는 부루마블 게임! 이번엔 조건에 따라 결과가 달라지는 코딩을 해 봐요. 원하는 하나씩 추가하다 보면 어느새 조건문도 마스터!\n\nStage 4 코딩을 쉽게 만들어주는 반복 친구들\n하고 싶은 건 많은데 코드는 점점 길어지고… 훨씬 간단한 코드를 만드는 반복문을 배워 내릴 층을 알려주는 엘리베이터와 지각쟁이도 깨우는 알람 앱을 만들어 봐요!\n\n슬기로운 코딩 생활 Stage 구성\n오늘의 문제 → 학습하기 → 연습 문제 → 좀 더 어려운 문제 → Stage 끝내기'},
 {'title': '파이썬과 케라스를 이용한 딥러닝/강화학습 주식투자 (퀀트 투자 알고리즘 트레이딩을 위한 최첨단 해법 입문)',
  'link': 'https://search.shopping.naver.com/book/catalog/32492068420',
  'image': 'https://shopping-phinf.pstatic.net/main_3249206/32492068420.20220527033654.jpg',
  'author': '김문권',
  'discount': '13200',
  'publisher': '위키북스',
  'pubdate': '20180529',
  'isbn': '9791158391065',
  'description': '강화학습은 스스로 학습하는 머신러닝 기법으로서 주식 데이터 학습에 잘 적용되는 기법입니다. 이 책은 파이썬을 이용한 강화학습 기반의 주식투자 시뮬레이션 프로그램을 개발하는 방법을 설명합니다. 이를 위해 이론과 코드 수준에서 상세한 설명을 덧붙였습니다. 이 책을 통해 딥러닝과 강화학습을 이해하고 이를 주식투자를 비롯한 다양한 도메인에서 활용할 수 있을 것입니다.'},
 {'title': 'Step by Step CRM을 위한 파이썬 머신러닝 (빅 데이터 분석 자격증 머신러닝 분야 학습서)',
  'link': 'https://search.shopping.naver.com/book/catalog/39490938619',
  'image': 'https://shopping-phinf.pstatic.net/main_3949093/39490938619.20231115072122.jpg',
  'author': '김형수',
  'discount': '30000',
  'publisher': '프레딕스',
  'pubdate': '20230501',
  'isbn': '9791195511792',
  'description': '\n본서는 파이썬을 전혀 모르는 사람도, 프로그래밍을 전혀 해보지 않은 사람도 단계적으로 (step by step) 따라하다 보면 파이썬 기반의 머신러닝을 용이하게 다룰 수 있도록 도와주는 이론서이자 실무 지침서입니다. 또한, 국내 빅 데이터 분석 및 데이터 사이언스 관련 자격증의 머신러닝에 대한 대부분의 출제범위가 포함되어 있어 빅 데이터 분석 자격증을 준비하는 분들에게도 좋은 가이드라인이 됩니다.\n\n이 책의 주요 특징은 다음과 같습니다.\n\n - 머신러닝의 큰 두가지 축인 지도학습모형과 비지도학습모형의 대부분을 다루었습니다.\n - 실습에 필요한 소프트웨어의 다운로드, 설치, 환경설정 등 필요한 모든 과정에 대해서 화면 이미지와 더불어 자세한 설명을 제공하고자 하였습니다.\n - 실습에 사용하는 데이터는 기업의 실제 CRM 데이터이므로, 책에서 배우는 내용과 실무의 괴리가 크지 않도록 노력하였습니다. 실습 데이터의 다운로드 방법은 2장에서 자세히 설명합니다. \n - 복잡한 수학적 원리는 가급적 요약하고, 대신 핵심적인 원리는 자세히 언급하되 예시를 들어 이해를 도모하고자 하였습니다. \n - 파이썬 분석코드는 전문가를 위한 축약된 코딩 방식보다는 조금 비효율적일 수 있어도 초보자가 해당 모형의 분석 과정을 쉽게 이해할 수 있도록 작성되었습니다. \n - 책의 분량이 많아질 수 있지만 모든 실습 코드에 대한 설명을 제시하였습니다. 다만, 이미 앞에서 설명된 코드 부분은 반복 설명을 생략합니다.'},
 {'title': '비즈니스 애널리틱스를 위한 데이터 마이닝 in 파이썬 (비즈니스 애널리틱스를 위한)',
  'link': 'https://search.shopping.naver.com/book/catalog/37799040624',
  'image': 'https://shopping-phinf.pstatic.net/main_3779904/37799040624.20230906071049.jpg',
  'author': '갈리트 슈무엘리^Peter C. Bruce^Gedeck, Peter^Nitin R. Patel',
  'discount': '36270',
  'publisher': '한빛아카데미',
  'pubdate': '20230210',
  'isbn': '9791156646440',
  'description': '데이터 마이닝의 개념, 기법, 응용\n\n다양한 분석 기법이 존재하는 이유는 각 분석 기법마다 장단점이 있기 때문이다. 데이터를 분석하는 목적, 데이터의 양·유형·노이즈 등에 따라 적합한 분석 기법이 달라진다. 이 책은 전통적인 통계 기법부터 머신러닝 기법까지 데이터 마이닝 기술 전반을 다루어, 주어진 상황에 적합한 분석 기법을 선택할 수 있는 힘을 키워준다. 또한 풍부한 연습문제와 9개의 실전 사례를 통해 실전 감각도 기를 수 있다.\n※ 본 도서는 대학 강의용 교재로 개발되었으므로 연습문제 해답은 제공하지 않습니다.'},
 {'title': '라즈베리파이 피코, 마이크로파이썬을 만나다 (마이크로파이썬으로 시작하는 마이크로컨트롤러 프로그래밍)',
  'link': 'https://search.shopping.naver.com/book/catalog/36197079619',
  'image': 'https://shopping-phinf.pstatic.net/main_3619707/36197079619.20230822103319.jpg',
  'author': '허경용',
  'discount': '19800',
  'publisher': '제이펍',
  'pubdate': '20221214',
  'isbn': '9791192469546',
  'description': 'IoT 시대, 쉽고 재밌게 따라 하며 배우는 라즈베리파이 피코. 라즈베리파이 피코의 장점은 저렴한 가격과 높은 하드웨어 성능이다. 접근성이 뛰어나며, 직접 다뤄보기 좋은 마이크로컨트롤러다. 또 하나의 장점은 프로그래밍 언어로 파이썬(마이크로파이썬)을 지원하는 것이다. 상대적으로 배우기 쉬운 프로그래밍 언어인 마이크로파이썬을 이용하면 하드웨어를 손쉽게 제어할 수 있다.\n이 책에서는 데이터의 입출력 방법부터 센서, 모터, 통신 모듈 등 다양한 장치를 활용하고 제어하는 방법까지 설명한다. 프로젝트마다 작동 원리를 설명하고 마이크로파이썬으로 구현한 코드를 제공하므로 처음 접하는 사람도 어려움 없이 따라 할 수 있다. 사물인터넷이 일상이 된 지금, 접근하기 쉬운 라즈베리파이 피코를 통해 IoT 시스템에 입문해보자.'},
 {'title': '2024 내일은 빅데이터분석기사 실기 with 파이썬 (작업형 제3유형 반영)',
  'link': 'https://search.shopping.naver.com/book/catalog/43414018630',
  'image': 'https://shopping-phinf.pstatic.net/main_4341401/43414018630.20250518071912.jpg',
  'author': 'Jade Jeong',
  'discount': '20700',
  'publisher': '아이비김영(김앤북)',
  'pubdate': '20231030',
  'isbn': '9788965127925',
  'description': '자격증을 준비하는 수험생 & 재직자(비전공자, 입문자 포함)를 위해 쓰였다. 이 책은 저자가 직접 시험에 응시하여 쌓은 합격 노하우를 바탕으로, 최신 3개년 기출을 분석하여 비전공자도 3주 만에 초단기 합격할 수 있도록 구성하였다.'},
 {'title': '파이썬 자료구조와 알고리즘 for Beginner',
  'link': 'https://search.shopping.naver.com/book/catalog/32439270500',
  'image': 'https://shopping-phinf.pstatic.net/main_3243927/32439270500.20230913071640.jpg',
  'author': '우재남',
  'discount': '25110',
  'publisher': '한빛아카데미',
  'pubdate': '20210123',
  'isbn': '9791156645252',
  'description': '파이썬으로 구현하며 다지는\n논리적 사고를 위한 기초 체력\n\n기본 자료구조와 알고리즘을 쉽게 풀어낸 입문서입니다. 기본 → 간단 구현 → 일반 구현 → 응용 순으로 체계적으로 학습할 수 있습니다. 주요 개념을 그림과 예를 통해 설명한 후(기본) 가장 기본이 되는 동작 원리를 먼저 구현해봄으로써(간단 구현) 개념과 구현을 한 흐름으로 이해할 수 있습니다. 그런 다음 일반적인 형태로 구현하고(일반 구현) 다양하게 연습(응용)해봅니다. 학습을 진행함에 따라 자료구조와 알고리즘 기본기뿐만 아니라 논리적으로 사고하는 힘도 기를 수 있습니다.\n\n※ 본 도서는 대학 강의용 교재로 개발되었으므로 연습문제 해답은 제공하지 않습니다.'},
 {'title': '이제 시작이야! 컴퓨팅 사고력으로 인공지능까지 파이썬',
  'link': 'https://search.shopping.naver.com/book/catalog/32485026895',
  'image': 'https://shopping-phinf.pstatic.net/main_3248502/32485026895.20230928092019.jpg',
  'author': '전수진^박주연^김수환',
  'discount': '20700',
  'publisher': '연두에디션',
  'pubdate': '20220110',
  'isbn': '9791192187037',
  'description': '부모는 아이에게 색깔을 가르칠 때 각각의 이미지를 가리키며 갈색, 초록색, 노란색 등과 같이 가르치게 된다. 이와 같이 다양한 사례를 통해 시각적인 정보와 언어정보를 일치 시키는 것을 반복함으로써 아이가 색깔을 분류하는 학습을 하도록 도와준다.\n이와 같이 지도학습은 어린 아이에게 색깔, 동물 이름을 하나하나 짚어주며 알려주듯이 사람이 알고 있는 지식에 기반을 두어 각 데이터에 레이블(Label), 즉, 정답을 알려주며 컴퓨터를 학습시키는 방식이다.\n지도학습은 데이터와 과제의 유형에 따라 예측을 위한 회귀(Regression)와 두 레이블의 구분을 위한 분류(Classification)의 두 가지 방식으로 나누어 볼 수 있다. 예를 들어, 세상에는 여러 종류의 오리가 있는데 각각의 오리 이미지에 레이블(정답)을 붙\n여 학습시킨다. 이때 사용하는 데이터 셋을 훈련용 셋(Training Set)이라고 한다. 또, 펭귄이라는 이미지에 레이블을 붙여 학습시킬 수도 있다. 그렇게 수많은 데이터를 사용하여 정답을 가진 이미지를 입력시키면 오리와 펭귄의 색, 부리모양, 크기, 날개나 발의 모양 등의 특성을 컴퓨터가 파악하여 스스로 학습하게 된다. 결국 컴퓨터는 오리와 펭귄을 구별할 수 있게 되는 것이다.'},
 {'title': '코딩천재의 비법노트 3단계: 파이썬, HTML과 CSS (코딩과 친해지는 가장 완벽한 방법)',
  'link': 'https://search.shopping.naver.com/book/catalog/32467109627',
  'image': 'https://shopping-phinf.pstatic.net/main_3246710/32467109627.20230313182536.jpg',
  'author': '브레인 퀘스트',
  'discount': '11700',
  'publisher': '우리학교',
  'pubdate': '20211220',
  'isbn': '9791167550309',

In [5]:
def json_unpack(data):
    result={}
    for item in data['items']:
        for key, value in item.items():
            result.setdefault(key, []).append(value)
    df=pd.DataFrame(result)
    return df

In [6]:
keyword=input("검색하고 싶은 책이름을 입력하세요")
url = "https://openapi.naver.com/v1/search/book.json"
headers={"X-Naver-Client-Id" : "HaXEGE3cbTofjrDFePfE", "X-Naver-Client-Secret": "U1uuXe2QfQ"}
payload={'query':keyword,'display': 100, 'start': '1', 'sort':'sim'}
r=requests.get(url, params=payload, headers=headers)
data=r.json()
print("전체 검색 데이터 수: ", data['total'], '검색할 페이지수: ', (int(data['total'])/100)+1)
result_df=json_unpack(data)
result_df

검색하고 싶은 책이름을 입력하세요파이썬
전체 검색 데이터 수:  1128 검색할 페이지수:  12.28

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,파이썬,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324609...,홍의경,30400,생능출판,20220309,9788970506784,코딩 실력을 키우는 지름길은 실습이다.\n\n2008년 즈음에 검인정 중학교 교과서...
...,...,...,...,...,...,...,...,...,...
95,파이썬아 반가워! (20일 안에 끝내는 코딩),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324560...,곽문기,12420,다락원,20180827,9788927747147,"소프트웨어 교육 왜 해야 할까요? \n『파이썬아 반가워!』, 블록 코딩부터 텍스트 ..."
96,이젠 나도! 파이썬 (지금 시작해도 괜찮아),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324877...,이지선,22500,성안당,20191004,9788931556278,17일 만에 비전공자도 제대로 끝내는 파이썬! \n저자 직강 무료 동영상 강의와 함...
97,파이썬 코딩 도장,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324692...,남재윤,11400,길벗,20181130,9791160506181,외우기만 해서는 파이썬도 어렵다!\n프로그래밍은 연습으로 배우는 것!\n문법을 외우...
98,파이썬3 바이블 (스크립트 언어의 지존을 만나다!),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324934...,이강성,10600,프리렉,20131001,9788965400493,『파이썬3 바이블』은 파이썬에 대한 이해와 활용을 한 권으로 해결할 수 있는 책이다...
99,파이썬 클린 코드 (유지보수가 쉬운 파이썬 코드를 만드는 비결),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324727...,마리아노 아나야,12600,터닝포인트,20190225,9791161340463,견고하면서도 확장성이 뛰어난 파이썬 코드를 만드는 비법\n\n파이썬은 누구나 쉽게 ...

# 네이버 api로 검색한 결과 최대한 가져오기
* 1회 네이버 서버에 요청
* 응답에서 total을 찾아서 display로 나누어 총 반복할 페이지 산출
* 반복문 작성 및 종료 조건 설정
* start가 1, 101, 201, 301처럼 변경되어야 함. start의 max 값은 1000
* 1페이지 결과를 데이터 프레임으로 만들고 리스트에 append
* 반복이 끝난 후 리스트에 append된 데이터 프레임을 1개로 합침

# for문을 이용해서 전체 페이지 가져오기

In [7]:
keyword=input("검색하고 싶은 책이름을 입력하세요")

검색하고 싶은 책이름을 입력하세요파이썬

In [8]:
all_data=[]

# requests 모듈로 1페이지만 가져오기

In [9]:
url = "https://openapi.naver.com/v1/search/book.json"
headers={"X-Naver-Client-Id" : "HaXEGE3cbTofjrDFePfE", "X-Naver-Client-Secret": "U1uuXe2QfQ"}
payload={'query':keyword,'display': 100, 'start': 1, 'sort':'sim'}
r=requests.get(url, params=payload, headers=headers)
data=r.json()
n_data=data['total']
total_pages=(int(data['total'])//100)+1
print("전체 검색 데이터 수: ", n_data, '검색할 페이지수: ', (int(data['total'])//100)+1)
result_df=json_unpack(data)
result_df
all_data.append(result_df)

전체 검색 데이터 수:  1128 검색할 페이지수:  12

In [10]:
start=101
for page in range(total_pages):
    print(f"{page+1}/{total_pages} 수집중", end='\r')   
    url = "https://openapi.naver.com/v1/search/book.json"
    headers={"X-Naver-Client-Id" : "HaXEGE3cbTofjrDFePfE", "X-Naver-Client-Secret": "U1uuXe2QfQ"}
    payload={'query':keyword,'display': 100, 'start': start, 'sort':'sim'}
    r=requests.get(url, params=payload, headers=headers)
    data=r.json()
    n_data=data['total']
    total_pages=(int(data['total'])//100)+1
    print("전체 검색 데이터 수: ", n_data, '검색할 페이지수: ', (int(data['total'])//100)+1)
    result_df=json_unpack(data)
    all_data.append(result_df)
    if start==1000:
        break
    elif start < 901:
        start+=100
    elif start == 901:
        start +=99

전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12

In [11]:
len(all_data)

11

In [12]:
final_result=pd.concat(all_data)
final_result=final_result.reset_index(drop=True)
final_result

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,파이썬,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324609...,홍의경,30400,생능출판,20220309,9788970506784,코딩 실력을 키우는 지름길은 실습이다.\n\n2008년 즈음에 검인정 중학교 교과서...
...,...,...,...,...,...,...,...,...,...
1095,딥러닝을 위한 최적화와 수치해석 (기본 수식과 파이썬으로 가장 핵심적인 최적화 문제...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324397...,황윤구^양한별,0,남가람북스,20200203,9791189184032,이 책은 텐서플로(Tensorflow)를 사용하여 다양한 딥러닝 모델들을 학습하는 ...
1096,파이썬으로 구현하는 AI 자율주행 자동차 with 아두이노 자동차 만들기,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_435864...,장문철,18000,앤써북,20231110,9791193059111,〈〈파이썬으로 구현하는 AI 자율주행 자동차 with 아두이노 자동차 만들기〉〉책의...
1097,"AI 인공지능 드론 만들고 날리고 딥러닝 구현하기 (데이터수집, 파이썬과 파이토치,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_399471...,서민우,23400,앤써북,20230530,9791193059029,드론을 이용하여 인공지능 딥러닝을 공부하고 적용하는 방법을 소개하는데 초점을 맞춘 ...
1098,파이썬과 인공지능 프로젝트 with ASUS Tinker Board (제품 개발 실...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_388946...,서민우^전한결,25200,앤써북,20230415,9791198189233,이 책은 라즈베리파이 사용자도 손쉽게 Tinker Board를 이용하여 제품 개발 ...
1099,"파이썬을 활용한 금융 분석: 파이썬의 기초부터 금융공학, 머신러닝, 퀀트 분석, 매...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324427...,이브 힐피시,40500,한빛미디어,20220331,9791162245170,파이썬으로 데이터 주도 금융 분석 마스터하기\n\n현재 파이썬은 데이터와 인공지능이...

# While 문으로 데이터 모두 가져오기

In [13]:
import requests
import pandas as pd

In [14]:
keyword=input("검색하고 싶은 책이름을 입력하세요")

검색하고 싶은 책이름을 입력하세요파이썬

In [15]:
all_data2=[]
start=1
while True:
    print(f"{page+1}/{total_pages} 수집중", end='\r')   
    url = "https://openapi.naver.com/v1/search/book.json"
    headers={"X-Naver-Client-Id" : "HaXEGE3cbTofjrDFePfE", "X-Naver-Client-Secret": "U1uuXe2QfQ"}
    payload={'query':keyword,'display': 100, 'start': start, 'sort':'sim'}
    r=requests.get(url, params=payload, headers=headers)
    data=r.json()
    n_data=data['total']
    total_pages=(int(data['total'])//100)+1
    print("전체 검색 데이터 수: ", n_data, '검색할 페이지수: ', (int(data['total'])//100)+1)
    result_df=json_unpack(data)
    all_data2.append(result_df)
    if start==1000:
        break
    elif start <901:
        start+=100
    elif start == 901:
        start+=99

전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12

In [16]:
len(all_data2)

11

In [17]:
final_result2=pd.concat(all_data2)
final_result2=final_result2.reset_index(drop=True) #drop: 새로운 인덱스 컬럼 안 만들고 버림
final_result2

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,파이썬,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324609...,홍의경,30400,생능출판,20220309,9788970506784,코딩 실력을 키우는 지름길은 실습이다.\n\n2008년 즈음에 검인정 중학교 교과서...
...,...,...,...,...,...,...,...,...,...
1095,딥러닝을 위한 최적화와 수치해석 (기본 수식과 파이썬으로 가장 핵심적인 최적화 문제...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324397...,황윤구^양한별,0,남가람북스,20200203,9791189184032,이 책은 텐서플로(Tensorflow)를 사용하여 다양한 딥러닝 모델들을 학습하는 ...
1096,파이썬으로 구현하는 AI 자율주행 자동차 with 아두이노 자동차 만들기,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_435864...,장문철,18000,앤써북,20231110,9791193059111,〈〈파이썬으로 구현하는 AI 자율주행 자동차 with 아두이노 자동차 만들기〉〉책의...
1097,"AI 인공지능 드론 만들고 날리고 딥러닝 구현하기 (데이터수집, 파이썬과 파이토치,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_399471...,서민우,23400,앤써북,20230530,9791193059029,드론을 이용하여 인공지능 딥러닝을 공부하고 적용하는 방법을 소개하는데 초점을 맞춘 ...
1098,파이썬과 인공지능 프로젝트 with ASUS Tinker Board (제품 개발 실...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_388946...,서민우^전한결,25200,앤써북,20230415,9791198189233,이 책은 라즈베리파이 사용자도 손쉽게 Tinker Board를 이용하여 제품 개발 ...
1099,"파이썬을 활용한 금융 분석: 파이썬의 기초부터 금융공학, 머신러닝, 퀀트 분석, 매...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324427...,이브 힐피시,40500,한빛미디어,20220331,9791162245170,파이썬으로 데이터 주도 금융 분석 마스터하기\n\n현재 파이썬은 데이터와 인공지능이...

In [18]:
final_result2.to_csv("네이버검색_책_파이썬.csv", encoding='utf-8-sig', index=False)

# 블로그, 뉴스, 책 한번에 검색해서 저장하기

In [19]:
all_data3=[]
for category in ['blog','news','book']:
    start=1
    while True:
        print(f"{page+1}/{total_pages} 수집중", end='\r')   
        url = f"https://openapi.naver.com/v1/search/{category}.json"
        headers={"X-Naver-Client-Id" : "HaXEGE3cbTofjrDFePfE", "X-Naver-Client-Secret": "U1uuXe2QfQ"}
        payload={'query':keyword,'display': 100, 'start': start, 'sort':'sim'}
        r=requests.get(url, params=payload, headers=headers)
        data=r.json()
        n_data=data['total']
        total_pages=(int(data['total'])//100)+1
        print("전체 검색 데이터 수: ", n_data, '검색할 페이지수: ', (int(data['total'])//100)+1)
        result_df=json_unpack(data)
        all_data3.append(result_df)
        if start==1000:
            break
        elif start <901:
            start+=100
        elif start == 901:
            start+=99
final_result3=pd.concat(all_data3)
final_result3=final_result3.reset_index(drop=True) #drop: 새로운 인덱스 컬럼 안 만들고 버림
final_result3

전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  533533 검색할 페이지수:  5336
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  24324 검색할 페이지수:  244
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12
전체 검색 데이터 수:  1128 검색할 페이지수:  12

,title,link,description,bloggername,bloggerlink,postdate,originallink,pubDate,image,author,discount,publisher,pubdate,isbn
0,대전<b>파이썬</b>학원 단계별 코딩 실무 학습 과정,https://blog.naver.com/she_op/223881011131,그래서 대전<b>파이썬</b>학원을 알아보기로 했죠. 아무 데서나 할 순 없고 커리...,"오롯이 여행, 마음먹기 나름 :)",blog.naver.com/she_op,20250528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,<b>파이썬</b>전문가 자격증 종류 및 효율적인 취득방법,https://blog.naver.com/mellybird/223842981098,<b>파이썬</b>전문가 자격증 종류 및 효율적인 취득방법 <b>파이썬</b>은 요...,멜잉로그 : 현직 국내파 영어강사 블로그,blog.naver.com/mellybird,20250422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,대구<b>파이썬</b>학원 실전 기술 익힌 곳,https://blog.naver.com/xshinerx/223787876858,그때 힘이 되어 준 대구<b>파이썬</b>학원에 대한 글을 써보려 해요! IT 위주...,▶ 제이의 맛있는 세상 ◀,blog.naver.com/xshinerx,20250308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,<b>파이썬</b>자격증 종류 취업 분야 및 공부 후기,https://blog.naver.com/kang6902/223863482199,<b>파이썬</b>자격증 종류 취업 분야 및 공부 후기 공부하신 분의 후기를 바탕으...,세 아이와 함께 성장하는 곳,blog.naver.com/kang6902,20250512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,<b>파이썬</b>전문가 자격증 학습방법 취득후기,https://blog.naver.com/bbobbny/223842932148,<b>파이썬</b>전문가 자격증 학습방법 취득후기 요즘 IT 분야에 대한 관심이 점...,ALICEMADE-앨리스가 만들어가는 세상,blog.naver.com/bbobbny,20250422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,딥러닝을 위한 최적화와 수치해석 (기본 수식과 파이썬으로 가장 핵심적인 최적화 문제...,https://search.shopping.naver.com/book/catalog...,이 책은 텐서플로(Tensorflow)를 사용하여 다양한 딥러닝 모델들을 학습하는 ...,NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_324397...,황윤구^양한별,0,남가람북스,20200203,9791189184032
3296,파이썬으로 구현하는 AI 자율주행 자동차 with 아두이노 자동차 만들기,https://search.shopping.naver.com/book/catalog...,〈〈파이썬으로 구현하는 AI 자율주행 자동차 with 아두이노 자동차 만들기〉〉책의...,NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_435864...,장문철,18000,앤써북,20231110,9791193059111
3297,"AI 인공지능 드론 만들고 날리고 딥러닝 구현하기 (데이터수집, 파이썬과 파이토치,...",https://search.shopping.naver.com/book/catalog...,드론을 이용하여 인공지능 딥러닝을 공부하고 적용하는 방법을 소개하는데 초점을 맞춘 ...,NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_399471...,서민우,23400,앤써북,20230530,9791193059029
3298,파이썬과 인공지능 프로젝트 with ASUS Tinker Board (제품 개발 실...,https://search.shopping.naver.com/book/catalog...,이 책은 라즈베리파이 사용자도 손쉽게 Tinker Board를 이용하여 제품 개발 ...,NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_388946...,서민우^전한결,25200,앤써북,20230415,9791198189233
3299,"파이썬을 활용한 금융 분석: 파이썬의 기초부터 금융공학, 머신러닝, 퀀트 분석, 매...",https://search.shopping.naver.com/book/catalog...,파이썬으로 데이터 주도 금융 분석 마스터하기\n\n현재 파이썬은 데이터와 인공지능이...,NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_324427...,이브 힐피시,40500,한빛미디어,20220331,9791162245170

# While True로 전체 데이터 가져오기

In [20]:
import requests
import json

In [21]:
page=1
start_num=1
result_json=[]
while True:
    url="https://openapi.naver.com/v1/search/book.json"
    Client_Id="HaXEGE3cbTofjrDFePfE"
    Client_Secret="U1uuXe2QfQ"
    payload=dict(query="핀테크", display=100, start=start_num, sort='sim')
    headers={"X-Naver-Client-Id": Client_Id , "X-Naver-Client-Secret": Client_Secret}
    r=requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    response=r.json()
    total_pages=(response['total']//100)+1
    result_json.append(response)
    if start_num==1000: 
        break
    if start_num<901:
        start_num+=100
    elif start_num==901:
        start_num+=99
    
    if page<total_pages:
        page+=1
    else:
        break
print(len(response_json3))

https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200

NameError: name 'response_json3' is not defined

# 블로그, 책, 뉴스 동시에 수집하기

In [ ]:
import time
result_json=[]
for category in ['blog','news','book']:
    page=1
    start_num=1
    while True:
        url=f"https://openapi.naver.com/v1/search/{category}.json"
        Client_Id="HaXEGE3cbTofjrDFePfE"
        Client_Secret="U1uuXe2QfQ"
        payload=dict(query="핀테크", display=100, start=start_num, sort='sim')
        headers={"X-Naver-Client-Id": Client_Id , "X-Naver-Client-Secret": Client_Secret}
        r=requests.get(url, params=payload, headers=headers)
        print(r.url)
        print(r.status_code)
        response=r.json()
        total_pages=(response['total']//100)+1
        result_json.append(response)
        if start_num==1000: 
            break
        if start_num<901:
            start_num+=100
        elif start_num==901:
            start_num+=99

        if page<total_pages:
            page+=1
        else:
            break
        time.sleep(0.5)
    print(len(response_json3))

# 블로그, 뉴스, 책 데이터 각각 저장하기

In [ ]:
import time
keyword=input("검색할 키워드를 입력해주세요")
response_blog=[]
response_news=[]
response_book=[]
for category in ['blog','news','book']:
    page=1
    start_num=1
    while True:
        url=f"https://openapi.naver.com/v1/search/{category}.json"
        Client_Id="HaXEGE3cbTofjrDFePfE"
        Client_Secret="U1uuXe2QfQ"
        payload=dict(query=keyword, display=100, start=start_num, sort='sim')
        headers={"X-Naver-Client-Id": Client_Id , "X-Naver-Client-Secret": Client_Secret}
        r=requests.get(url, params=payload, headers=headers)
        print(r.url, end='\r')
        print(r.status_code, end='\r')
        response=r.json()
        total_pages=(response['total']//100)+1
        
        if category=='blog':
            response_blog.append(response)
        elif category=='news':
            response_news.append(response)
        elif category=='book':
            response_book.append(response)
            
        result_json.append(response)
        if start_num==1000: 
            break
        if start_num<901:
            start_num+=100
        elif start_num==901:
            start_num+=99

        if page<total_pages:
            page+=1
        else:
            break
        time.sleep(0.5)
print(len(response_blog))
print(len(response_news))
print(len(response_book))

In [ ]:
import pandas as pd
pd.DataFrame(response_blog)

In [ ]:
def json_unpack(all_data):
    final_result={}
    for page in all_data:
        for item in page['items']:
            for key, value in item.items():
                final_result.setdefault(key, []).append(value)
    df=pd.DataFrame(final_result)
    return df

In [ ]:
for jsons, cat in zip([response_blog, response_news, response_book],["blog", "news", "book"]):
    unpack_result=json_unpack(jsons)
    unpack_result.to_csv(f"naver_{cat}_result.csv", encoding="utf-8", index=False)

# 3개 카테고리 수집 코드를 함수화하기

In [ ]:
import time
keyword=input("검색할 키워드를 입력해주세요")
for category in ['blog','news','book']:
def naver_search(category):
    response_result=[]
    
    page=1
    start_num=1
    while True:
        url=f"https://openapi.naver.com/v1/search/{category}.json"
        Client_Id="HaXEGE3cbTofjrDFePfE"
        Client_Secret="U1uuXe2QfQ"
        payload=dict(query=keyword, display=100, start=start_num, sort='sim')
        headers={"X-Naver-Client-Id": Client_Id , "X-Naver-Client-Secret": Client_Secret}
        r=requests.get(url, params=payload, headers=headers)
        print(r.url, end='\r')
        print(r.status_code, end='\r')
        response=r.json()
        total_pages=(response['total']//100)+1
        response_result.append(response)
        
        if category=='blog':
            response_blog.append(response)
        elif category=='news':
            response_news.append(response)
        elif category=='book':
            response_book.append(response)
            
        result_json.append(response)
        if start_num==1000: 
            break
        if start_num<901:
            start_num+=100
        elif start_num==901:
            start_num+=99

        if page<total_pages:
            page+=1
        else:
            break
        time.sleep(0.5)
    return response_result

In [ ]:
import time
keyword=input("검색할 키워드를 입력해주세요")
for category in ['blog','news','book']:
    naver_search_result=naver_search(category)
    result_df=json_unpack(naver_search_result)
    display(result_df)