# 4.1~4.2

# 상권정보 데이터 수집하기

In [4]:
import requests
import json
import pandas as pd
import os
import time

In [5]:
def unpack_data(response):
    result={}
    for item in response['body']['items']:
        for key, value in zip(response['header']['columns'], item.values()):
            result.setdefault(key, []).append(value)
    df=pd.DataFrame(result)
    return df

In [17]:
page = 1
result_dfs = []
while True:
    url = "http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
    service_key = "TUszyF9E+ahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9+oN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw=="
    payload = dict(servicekey=service_key, divId="indsSclsCd", 
                  key="I21006", numOfRows=1000, pageNo=page, type="json")
    r = requests.get(url, params=payload)
    print(r.url, end="\r")
    print(r.status_code, end="\r")
    
    response = r.json()
    total_page = (response['body']['totalCount'] // 1000) + 1
    result_dfs.append(unpack_data(response))
    print(f"{page}/{total_page} 수집중", end="\r")
    if page < total_page:
        page += 1
    else:
        break
    time.sleep(0.2)
        
result = pd.concat(result_dfs)    
result = result.reset_index(drop=True)
result.to_csv("공공데이터_상권정보_202504.csv", encoding="utf-8", index=False)

In [7]:
response['body']

{'items': [{'bizesId': 'MA0106202306A0595317',
   'bizesNm': '마마치킨마포지점',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56192',
   'ksicNm': '피자, 햄버거, 샌드위치 및 유사 음식점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11440',
   'signguNm': '마포구',
   'adongCd': '11440590',
   'adongNm': '용강동',
   'ldongCd': '1144010500',
   'ldongNm': '용강동',
   'lnoCd': '1144010500100190003',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 19,
   'lnoSlno': 3,
   'lnoAdr': '서울특별시 마포구 용강동 19-3',
   'rdnmCd': '114403113022',
   'rdnm': '서울특별시 마포구 큰우물로',
   'bldMnno': 62,
   'bldSlno': '',
   'bldMngNo': '1144010500100190003003692',
   'bldNm': '',
   'rdnmAdr': '서울특별시 마포구 큰우물로 62',
   'oldZipcd': '121875',
   'newZipcd': '04166',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 126.94495129865,
   'lat': 37.5416664523466},
  {'bizesId': 'MA0106202303A0590715',
   'bizesNm': '돈치킨용인서천점',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '41',
   'ctprvnNm': '경기도',
   'signguCd': '41463',
   'signguNm': '용인시 기흥구',
   'adongCd': '41463550',
   'adongNm': '서농동',
   'ldongCd': '4146310900',
   'ldongNm': '농서동',
   'lnoCd': '4146310900104130002',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 413,
   'lnoSlno': 2,
   'lnoAdr': '경기도 용인시 기흥구 농서동 413-2',
   'rdnmCd': '414634412328',
   'rdnm': '경기도 용인시 기흥구 서천로202번길',
   'bldMnno': 2,
   'bldSlno': '',
   'bldMngNo': '4146310900104130002000001',
   'bldNm': '',
   'rdnmAdr': '경기도 용인시 기흥구 서천로202번길 2',
   'oldZipcd': '446920',
   'newZipcd': '17110',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.070068308166,
   'lat': 37.2307513845698},
  {'bizesId': 'MA0106202308A1870651',
   'bizesNm': '치킨몬스터김해삼미대박집',
   'brchNm': '삼계점',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '48',
   'ctprvnNm': '경상남도',
   'signguCd': '48250',
   'signguNm': '김해시',
   'adongCd': '48250550',
   'adongNm': '북부동',
   'ldongCd': '4825010700',
   'ldongNm': '삼계동',
   'lnoCd': '4825010700114750004',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1475,
   'lnoSlno': 4,
   'lnoAdr': '경상남도 김해시 삼계동 1475-4',
   'rdnmCd': '482504805864',
   'rdnm': '경상남도 김해시 해반천로144번길',
   'bldMnno': 23,
   'bldSlno': 5,
   'bldMngNo': '4825010700114750004081552',
   'bldNm': '',
   'rdnmAdr': '경상남도 김해시 해반천로144번길 23-5',
   'oldZipcd': '621070',
   'newZipcd': '50901',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 128.869580990799,
   'lat': 35.2615153365155},
  {'bizesId': 'MA0106202312A2442023',
   'bizesNm': '유일닭강정가평맛집',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '41',
   'ctprvnNm': '경기도',
   'signguCd': '41820',
   'signguNm': '가평군',
   'adongCd': '41820250',
   'adongNm': '가평읍',
   'ldongCd': '4182025021',
   'ldongNm': '가평읍',
   'lnoCd': '4182025021104710002',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 471,
   'lnoSlno': 2,
   'lnoAdr': '경기도 가평군 가평읍 읍내리 471-2',
   'rdnmCd': '418203000142',
   'rdnm': '경기도 가평군 가평읍 가화로',
   'bldMnno': 122,
   'bldSlno': '',
   'bldMngNo': '4182025021104710002005180',
   'bldNm': '',
   'rdnmAdr': '경기도 가평군 가평읍 가화로 122',
   'oldZipcd': '477805',
   'newZipcd': '12419',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.513662466816,
   'lat': 37.8305568229902},
  {'bizesId': 'MA0106202401A1467223',
   'bizesNm': '프랜푸드땅땅치킨잠원',
   'brchNm': '한강점',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11650',
   'signguNm': '서초구',
   'adongCd': '11650540',
   'adongNm': '잠원동',
   'ldongCd': '1165010600',
   'ldongNm': '잠원동',
   'lnoCd': '1165010600100350001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 35,
   'lnoSlno': 1,
   'lnoAdr': '서울특별시 서초구 잠원동 35-1',
   'rdnmCd': '116504163039',
   'rdnm': '서울특별시 서초구 강남대로95길',
   'bldMnno': 47,
   'bldSlno': 4,
   'bldMngNo': '1165010600100350001019342',
   'bldNm': '',
   'rdnmAdr': '서울특별시 서초구 강남대로95길 47-4',
   'oldZipcd': '137905',
   'newZipcd': '06530',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.017678932534,
   'lat': 37.5128278776435},
  {'bizesId': 'MA0106202405A2153895',
   'bizesNm': '림스치킨',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '52',
   'ctprvnNm': '전북특별자치도',
   'signguCd': '52111',
   'signguNm': '전주시 완산구',
   'adongCd': '52111730',
   'adongNm': '효자5동',
   'ldongCd': '5211114200',
   'ldongNm': '효자동3가',
   'lnoCd': '5211114200115440003',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1544,
   'lnoSlno': 3,
   'lnoAdr': '전북특별자치도 전주시 완산구 효자동3가 1544-3',
   'rdnmCd': '521113266035',
   'rdnm': '전북특별자치도 전주시 완산구 서원로',
   'bldMnno': 145,
   'bldSlno': '',
   'bldMngNo': '4511114200115440003000001',
   'bldNm': '유탑유블레스리버뷰',
   'rdnmAdr': '전북특별자치도 전주시 완산구 서원로 145',
   'oldZipcd': '560900',
   'newZipcd': '54969',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.110595422631,
   'lat': 35.814448447123},
  {'bizesId': 'MA0106202410A2451537',
   'bizesNm': '교촌치킨목동',
   'brchNm': '파크자이점',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11470',
   'signguNm': '양천구',
   'adongCd': '11470680',
   'adongNm': '신정7동',
   'ldongCd': '1147010100',
   'ldongNm': '신정동',
   'lnoCd': '1147010100113250000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1325,
   'lnoSlno': '',
   'lnoAdr': '서울특별시 양천구 신정동 1325',
   'rdnmCd': '114704142095',
   'rdnm': '서울특별시 양천구 목동남로4길',
   'bldMnno': 80,
   'bldSlno': '',
   'bldMngNo': '1147010100101710061000192',
   'bldNm': '목동파크자이',
   'rdnmAdr': '서울특별시 양천구 목동남로4길 80',
   'oldZipcd': '158077',
   'newZipcd': '08102',
   'dongNo': '',
   'flrNo': '3',
   'hoNo': '',
   'lon': 126.868473145754,
   'lat': 37.5085302639809},
  {'bizesId': 'MA0106202311A0627476',
   'bizesNm': '지코바',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '28',
   'ctprvnNm': '인천광역시',
   'signguCd': '28260',
   'signguNm': '서구',
   'adongCd': '28260700',
   'adongNm': '원당동',
   'ldongCd': '2826011500',
   'ldongNm': '원당동',
   'lnoCd': '2826011500108100011',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 810,
   'lnoSlno': 11,
   'lnoAdr': '인천광역시 서구 원당동 810-11',
   'rdnmCd': '282604268593',
   'rdnm': '인천광역시 서구 원당대로839번길',
   'bldMnno': 35,
   'bldSlno': 1,
   'bldMngNo': '2826011500108100011000008',
   'bldNm': '',
   'rdnmAdr': '인천광역시 서구 원당대로839번길 35-1',
   'oldZipcd': '404320',
   'newZipcd': '22644',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.696200896762,
   'lat': 37.59648328471},
  {'bizesId': 'MA0106202501A2302176',
   'bizesNm': '넥스트치킨',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '41',
   'ctprvnNm': '경기도',
   'signguCd': '41173',
   'signguNm': '안양시 동안구',
   'adongCd': '41173559',
   'adongNm': '인덕원동',
   'ldongCd': '4117310200',
   'ldongNm': '관양동',
   'lnoCd': '4117310200108100000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 810,
   'lnoSlno': '',
   'lnoAdr': '경기도 안양시 동안구 관양동 810',
   'rdnmCd': '411733012016',
   'rdnm': '경기도 안양시 동안구 학의로',
   'bldMnno': 282,
   'bldSlno': '',
   'bldMngNo': '4117310200108100000012996',
   'bldNm': '제',
   'rdnmAdr': '경기도 안양시 동안구 학의로 282',
   'oldZipcd': '431810',
   'newZipcd': '14056',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 126.969133286162,
   'lat': 37.4010635556705},
  {'bizesId': 'MA0106202405A2021697',
   'bizesNm': '코리엔탈깻잎두마리치킨&모락로제떡볶이원주점',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '51',
   'ctprvnNm': '강원특별자치도',
   'signguCd': '51130',
   'signguNm': '원주시',
   'adongCd': '51130330',
   'adongNm': '지정면',
   'ldongCd': '5113033023',
   'ldongNm': '지정면',
   'lnoCd': '5113033023113480009',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1348,
   'lnoSlno': 9,
   'lnoAdr': '강원특별자치도 원주시 지정면 가곡리 1348-9',
   'rdnmCd': '511303350530',
   'rdnm': '강원특별자치도 원주시 지정면 신지정로',
   'bldMnno': 184,
   'bldSlno': '',
   'bldMngNo': '4213033023113480009000001',
   'bldNm': '',
   'rdnmAdr': '강원특별자치도 원주시 지정면 신지정로 184',
   'oldZipcd': '220821',
   'newZipcd': '26353',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.876472576101,
   'lat': 37.3743120804409},
  {'bizesId': 'MA0106202412A2102800',
   'bizesNm': '중앙닭강정강남',
   'brchNm': '직영점',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11650',
   'signguNm': '서초구',
   'adongCd': '11650580',
   'adongNm': '반포3동',
   'ldongCd': '1165010600',
   'ldongNm': '잠원동',
   'lnoCd': '1165010600100700002',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 70,
   'lnoSlno': 2,
   'lnoAdr': '서울특별시 서초구 잠원동 70-2',
   'rdnmCd': '116503121019',
   'rdnm': '서울특별시 서초구 잠원로',
   'bldMnno': 51,
   'bldSlno': '',
   'bldMngNo': '1165010600100700002017536',
   'bldNm': '식품관',
   'rdnmAdr': '서울특별시 서초구 잠원로 51',
   'oldZipcd': '137711',
   'newZipcd': '06511',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.007442214525,
   'lat': 37.5092429685439},
  {'bizesId': 'MA0106202412A1503360',
   'bizesNm': '대림닭강정왕십리역사점',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11200',
   'signguNm': '성동구',
   'adongCd': '11200560',
   'adongNm': '행당1동',
   'ldongCd': '1120010700',
   'ldongNm': '행당동',
   'lnoCd': '1120010700101680151',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 168,
   'lnoSlno': 151,
   'lnoAdr': '서울특별시 성동구 행당동 168-151',
   'rdnmCd': '112003103005',
   'rdnm': '서울특별시 성동구 왕십리광장로',
   'bldMnno': 17,
   'bldSlno': '',
   'bldMngNo': '1120010700101680001017508',
   'bldNm': '비트플렉스',
   'rdnmAdr': '서울특별시 성동구 왕십리광장로 17',
   'oldZipcd': '133866',
   'newZipcd': '04750',
   'dongNo': '',
   'flrNo': '2',
   'hoNo': '',
   'lon': 127.038391477602,
   'lat': 37.5614409428511},
  {'bizesId': 'MA0106202405A1938675',
   'bizesNm': '노랑통닭가촌점',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '48',
   'ctprvnNm': '경상남도',
   'signguCd': '48330',
   'signguNm': '양산시',
   'adongCd': '48330253',
   'adongNm': '물금읍',
   'ldongCd': '4833025323',
   'ldongNm': '물금읍',
   'lnoCd': '4833025323112690016',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1269,
   'lnoSlno': 16,
   'lnoAdr': '경상남도 양산시 물금읍 가촌리 1269-16',
   'rdnmCd': '483303338111',
   'rdnm': '경상남도 양산시 물금읍 백호로',
   'bldMnno': 76,
   'bldSlno': '',
   'bldMngNo': '4833025323112690016000001',
   'bldNm': '',
   'rdnmAdr': '경상남도 양산시 물금읍 백호로 76',
   'oldZipcd': '626811',
   'newZipcd': '50613',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 129.002520121772,
   'lat': 35.3174399856685},
  {'bizesId': 'MA0106202502A1360638',
   'bizesNm': '알비/산방산치킨그랜드메르호텔점',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '50',
   'ctprvnNm': '제주특별자치도',
   'signguCd': '50130',
   'signguNm': '서귀포시',
   'adongCd': '50130620',
   'adongNm': '예래동',
   'ldongCd': '5013012100',
   'ldongNm': '하예동',
   'lnoCd': '5013012100104600001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 460,
   'lnoSlno': 1,
   'lnoAdr': '제주특별자치도 서귀포시 하예동 460-1',
   'rdnmCd': '501303350039',
   'rdnm': '제주특별자치도 서귀포시 논짓물로',
   'bldMnno': 45,
   'bldSlno': '',
   'bldMngNo': '5013012100104500001000001',
   'bldNm': '',
   'rdnmAdr': '제주특별자치도 서귀포시 논짓물로 45',
   'oldZipcd': '697310',
   'newZipcd': '63538',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.38611901535,
   'lat': 33.239642791679},
  {'bizesId': 'MA0106202305A0525778',
   'bizesNm': '예술치킨',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '28',
   'ctprvnNm': '인천광역시',
   'signguCd': '28237',
   'signguNm': '부평구',
   'adongCd': '28237592',
   'adongNm': '청천2동',
   'ldongCd': '2823710400',
   'ldongNm': '청천동',
   'lnoCd': '2823710400102360017',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 236,
   'lnoSlno': 17,
   'lnoAdr': '인천광역시 부평구 청천동 236-17',
   'rdnmCd': '282373154073',
   'rdnm': '인천광역시 부평구 원적로',
   'bldMnno': 435,
   'bldSlno': '',
   'bldMngNo': '2823710400102360017000001',
   'bldNm': '',
   'rdnmAdr': '인천광역시 부평구 원적로 435',
   'oldZipcd': '403858',
   'newZipcd': '21364',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 126.714988709615,
   'lat': 37.5037996860147},
  {'bizesId': 'MA0106202405A0770625',
   'bizesNm': '2피자1치킨상회',
   'brchNm': '2호점',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '27',
   'ctprvnNm': '대구광역시',
   'signguCd': '27290',
   'signguNm': '달서구',
   'adongCd': '27290585',
   'adongNm': '신당동',
   'ldongCd': '2729010700',
   'ldongNm': '신당동',
   'lnoCd': '2729010700118180005',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1818,
   'lnoSlno': 5,
   'lnoAdr': '대구광역시 달서구 신당동 1818-5',
   'rdnmCd': '272903147025',
   'rdnm': '대구광역시 달서구 신당로',
   'bldMnno': 12,
   'bldSlno': 1,
   'bldMngNo': '2729010700118180005000762',
   'bldNm': '',
   'rdnmAdr': '대구광역시 달서구 신당로 12-1',
   'oldZipcd': '704922',
   'newZipcd': '42614',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 128.493611786897,
   'lat': 35.8535131539341},
  {'bizesId': 'MA0106202405A2425484',
   'bizesNm': '구도로통닭',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '27',
   'ctprvnNm': '대구광역시',
   'signguCd': '27290',
   'signguNm': '달서구',
   'adongCd': '27290555',
   'adongNm': '감삼동',
   'ldongCd': '2729011300',
   'ldongNm': '감삼동',
   'lnoCd': '2729011300107090000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 709,
   'lnoSlno': '',
   'lnoAdr': '대구광역시 달서구 감삼동 709',
   'rdnmCd': '272904241423',
   'rdnm': '대구광역시 달서구 와룡로31길',
   'bldMnno': 26,
   'bldSlno': '',
   'bldMngNo': '2729011300105560000000002',
   'bldNm': '힐스테이트감삼',
   'rdnmAdr': '대구광역시 달서구 와룡로31길 26',
   'oldZipcd': '704150',
   'newZipcd': '42688',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 128.533918639207,
   'lat': 35.8468053089674},
  {'bizesId': 'MA0106202407A2169373',
   'bizesNm': '김해동상점뉴욕버거.또래오래동상부원점',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '48',
   'ctprvnNm': '경상남도',
   'signguCd': '48250',
   'signguNm': '김해시',
   'adongCd': '48250510',
   'adongNm': '동상동',
   'ldongCd': '4825010100',
   'ldongNm': '동상동',
   'lnoCd': '4825010100111170000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1117,
   'lnoSlno': '',
   'lnoAdr': '경상남도 김해시 동상동 1117',
   'rdnmCd': '482503335004',
   'rdnm': '경상남도 김해시 가야로',
   'bldMnno': 470,
   'bldSlno': '',
   'bldMngNo': '4825010100111170000000001',
   'bldNm': '김해캐슬아리스타궁',
   'rdnmAdr': '경상남도 김해시 가야로 470',
   'oldZipcd': '621020',
   'newZipcd': '50913',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 128.885801623266,
   'lat': 35.2393648203425},
  {'bizesId': 'MA0106202305A1208862',
   'bizesNm': '치킨아이',
   'brchNm': '매곡점',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '29',
   'ctprvnNm': '광주광역시',
   'signguCd': '29170',
   'signguNm': '북구',
   'adongCd': '29170673',
   'adongNm': '매곡동',
   'ldongCd': '2917011700',
   'ldongNm': '매곡동',
   'lnoCd': '2917011700102140001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 214,
   'lnoSlno': 1,
   'lnoAdr': '광주광역시 북구 매곡동 214-1',
   'rdnmCd': '291703162014',
   'rdnm': '광주광역시 북구 매곡로',
   'bldMnno': 84,
   'bldSlno': '',
   'bldMngNo': '2917011700102140001036939',
   'bldNm': '대화',
   'rdnmAdr': '광주광역시 북구 매곡로 84',
   'oldZipcd': '500815',
   'newZipcd': '61059',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.892856851572,
   'lat': 35.1920174068033},
  {'bizesId': 'MA0106202302A1246093',
   'bizesNm': '청정횟집&bhc무창포해수욕장점',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '44',
   'ctprvnNm': '충청남도',
   'signguCd': '44180',
   'signguNm': '보령시',
   'adongCd': '44180250',
   'adongNm': '웅천읍',
   'ldongCd': '4418025029',
   'ldongNm': '웅천읍',
   'lnoCd': '4418025029107880007',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 788,
   'lnoSlno': 7,
   'lnoAdr': '충청남도 보령시 웅천읍 독산리 788-7',
   'rdnmCd': '441803252027',
   'rdnm': '충청남도 보령시 웅천읍 열린바다로',
   'bldMnno': 388,
   'bldSlno': 34,
   'bldMngNo': '4418025029200020015000001',
   'bldNm': '',
   'rdnmAdr': '충청남도 보령시 웅천읍 열린바다로 388-34',
   'oldZipcd': '355852',
   'newZipcd': '33509',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 126.530392811703,
   'lat': 36.238128996185},
  {'bizesId': 'MA0106202305A1329764',
   'bizesNm': '천년닭강정부천',
   'brchNm': '부평점',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I210',
   'indsMclsNm': '기타 간이',
   'indsSclsCd': 'I21006',
   'indsSclsNm': '치킨',
   'ksicCd': 'I56111',
   'ksicNm': '한식 일반 음식점업',
   'ctprvnCd': '41',
   'ctprvnNm': '경기도',
   'signguCd': '41192',
   'signguNm': '부천시 원미구',
   'adongCd': '41192700',
   'adongNm': '상3동',
   'ldongCd': '4119210900',
   'ldongNm': '상동',
   'lnoCd': '4119210900105310003',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 531,

In [8]:
response

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
  'columns': ['상가업소번호',
   '상호명',
   '지점명',
   '상권업종대분류코드',
   '상권업종대분류명',
   '상권업종중분류코드',
   '상권업종중분류명',
   '상권업종소분류코드',
   '상권업종소분류명',
   '표준산업분류코드',
   '표준산업분류명',
   '시도코드',
   '시도명',
   '시군구코드',
   '시군구명',
   '행정동코드',
   '행정동명',
   '법정동코드',
   '법정동명',
   'PNU코드',
   '대지구분코드',
   '대지구분명',
   '지번본번지',
   '지번부번지',
   '지번주소',
   '도로명코드',
   '도로명',
   '건물본번지',
   '건물부번지',
   '건물관리번호',
   '건물명',
   '도로명주소',
   '구우편번호',
   '신우편번호',
   '동정보',
   '층정보',
   '호정보',
   '경도',
   '위도'],
  'stdrYm': '202503',
  'resultCode': '00',
  'resultMsg': 'NORMAL SERVICE'},
 'body': {'items': [{'bizesId': 'MA0106202306A0595317',
    'bizesNm': '마마치킨마포지점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56192',
    'ksicNm': '피자, 햄버거, 샌드위치 및 유사 음식점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11440',
    'signguNm': '마포구',
    'adongCd': '11440590',
    'adongNm': '용강동',
    'ldongCd': '1144010500',
    'ldongNm': '용강동',
    'lnoCd': '1144010500100190003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 19,
    'lnoSlno': 3,
    'lnoAdr': '서울특별시 마포구 용강동 19-3',
    'rdnmCd': '114403113022',
    'rdnm': '서울특별시 마포구 큰우물로',
    'bldMnno': 62,
    'bldSlno': '',
    'bldMngNo': '1144010500100190003003692',
    'bldNm': '',
    'rdnmAdr': '서울특별시 마포구 큰우물로 62',
    'oldZipcd': '121875',
    'newZipcd': '04166',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.94495129865,
    'lat': 37.5416664523466},
   {'bizesId': 'MA0106202303A0590715',
    'bizesNm': '돈치킨용인서천점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41463',
    'signguNm': '용인시 기흥구',
    'adongCd': '41463550',
    'adongNm': '서농동',
    'ldongCd': '4146310900',
    'ldongNm': '농서동',
    'lnoCd': '4146310900104130002',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 413,
    'lnoSlno': 2,
    'lnoAdr': '경기도 용인시 기흥구 농서동 413-2',
    'rdnmCd': '414634412328',
    'rdnm': '경기도 용인시 기흥구 서천로202번길',
    'bldMnno': 2,
    'bldSlno': '',
    'bldMngNo': '4146310900104130002000001',
    'bldNm': '',
    'rdnmAdr': '경기도 용인시 기흥구 서천로202번길 2',
    'oldZipcd': '446920',
    'newZipcd': '17110',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.070068308166,
    'lat': 37.2307513845698},
   {'bizesId': 'MA0106202308A1870651',
    'bizesNm': '치킨몬스터김해삼미대박집',
    'brchNm': '삼계점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48250',
    'signguNm': '김해시',
    'adongCd': '48250550',
    'adongNm': '북부동',
    'ldongCd': '4825010700',
    'ldongNm': '삼계동',
    'lnoCd': '4825010700114750004',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1475,
    'lnoSlno': 4,
    'lnoAdr': '경상남도 김해시 삼계동 1475-4',
    'rdnmCd': '482504805864',
    'rdnm': '경상남도 김해시 해반천로144번길',
    'bldMnno': 23,
    'bldSlno': 5,
    'bldMngNo': '4825010700114750004081552',
    'bldNm': '',
    'rdnmAdr': '경상남도 김해시 해반천로144번길 23-5',
    'oldZipcd': '621070',
    'newZipcd': '50901',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.869580990799,
    'lat': 35.2615153365155},
   {'bizesId': 'MA0106202312A2442023',
    'bizesNm': '유일닭강정가평맛집',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41820',
    'signguNm': '가평군',
    'adongCd': '41820250',
    'adongNm': '가평읍',
    'ldongCd': '4182025021',
    'ldongNm': '가평읍',
    'lnoCd': '4182025021104710002',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 471,
    'lnoSlno': 2,
    'lnoAdr': '경기도 가평군 가평읍 읍내리 471-2',
    'rdnmCd': '418203000142',
    'rdnm': '경기도 가평군 가평읍 가화로',
    'bldMnno': 122,
    'bldSlno': '',
    'bldMngNo': '4182025021104710002005180',
    'bldNm': '',
    'rdnmAdr': '경기도 가평군 가평읍 가화로 122',
    'oldZipcd': '477805',
    'newZipcd': '12419',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.513662466816,
    'lat': 37.8305568229902},
   {'bizesId': 'MA0106202401A1467223',
    'bizesNm': '프랜푸드땅땅치킨잠원',
    'brchNm': '한강점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11650',
    'signguNm': '서초구',
    'adongCd': '11650540',
    'adongNm': '잠원동',
    'ldongCd': '1165010600',
    'ldongNm': '잠원동',
    'lnoCd': '1165010600100350001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 35,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 서초구 잠원동 35-1',
    'rdnmCd': '116504163039',
    'rdnm': '서울특별시 서초구 강남대로95길',
    'bldMnno': 47,
    'bldSlno': 4,
    'bldMngNo': '1165010600100350001019342',
    'bldNm': '',
    'rdnmAdr': '서울특별시 서초구 강남대로95길 47-4',
    'oldZipcd': '137905',
    'newZipcd': '06530',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.017678932534,
    'lat': 37.5128278776435},
   {'bizesId': 'MA0106202405A2153895',
    'bizesNm': '림스치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '52',
    'ctprvnNm': '전북특별자치도',
    'signguCd': '52111',
    'signguNm': '전주시 완산구',
    'adongCd': '52111730',
    'adongNm': '효자5동',
    'ldongCd': '5211114200',
    'ldongNm': '효자동3가',
    'lnoCd': '5211114200115440003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1544,
    'lnoSlno': 3,
    'lnoAdr': '전북특별자치도 전주시 완산구 효자동3가 1544-3',
    'rdnmCd': '521113266035',
    'rdnm': '전북특별자치도 전주시 완산구 서원로',
    'bldMnno': 145,
    'bldSlno': '',
    'bldMngNo': '4511114200115440003000001',
    'bldNm': '유탑유블레스리버뷰',
    'rdnmAdr': '전북특별자치도 전주시 완산구 서원로 145',
    'oldZipcd': '560900',
    'newZipcd': '54969',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.110595422631,
    'lat': 35.814448447123},
   {'bizesId': 'MA0106202410A2451537',
    'bizesNm': '교촌치킨목동',
    'brchNm': '파크자이점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11470',
    'signguNm': '양천구',
    'adongCd': '11470680',
    'adongNm': '신정7동',
    'ldongCd': '1147010100',
    'ldongNm': '신정동',
    'lnoCd': '1147010100113250000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1325,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 양천구 신정동 1325',
    'rdnmCd': '114704142095',
    'rdnm': '서울특별시 양천구 목동남로4길',
    'bldMnno': 80,
    'bldSlno': '',
    'bldMngNo': '1147010100101710061000192',
    'bldNm': '목동파크자이',
    'rdnmAdr': '서울특별시 양천구 목동남로4길 80',
    'oldZipcd': '158077',
    'newZipcd': '08102',
    'dongNo': '',
    'flrNo': '3',
    'hoNo': '',
    'lon': 126.868473145754,
    'lat': 37.5085302639809},
   {'bizesId': 'MA0106202311A0627476',
    'bizesNm': '지코바',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '28',
    'ctprvnNm': '인천광역시',
    'signguCd': '28260',
    'signguNm': '서구',
    'adongCd': '28260700',
    'adongNm': '원당동',
    'ldongCd': '2826011500',
    'ldongNm': '원당동',
    'lnoCd': '2826011500108100011',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 810,
    'lnoSlno': 11,
    'lnoAdr': '인천광역시 서구 원당동 810-11',
    'rdnmCd': '282604268593',
    'rdnm': '인천광역시 서구 원당대로839번길',
    'bldMnno': 35,
    'bldSlno': 1,
    'bldMngNo': '2826011500108100011000008',
    'bldNm': '',
    'rdnmAdr': '인천광역시 서구 원당대로839번길 35-1',
    'oldZipcd': '404320',
    'newZipcd': '22644',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.696200896762,
    'lat': 37.59648328471},
   {'bizesId': 'MA0106202501A2302176',
    'bizesNm': '넥스트치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41173',
    'signguNm': '안양시 동안구',
    'adongCd': '41173559',
    'adongNm': '인덕원동',
    'ldongCd': '4117310200',
    'ldongNm': '관양동',
    'lnoCd': '4117310200108100000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 810,
    'lnoSlno': '',
    'lnoAdr': '경기도 안양시 동안구 관양동 810',
    'rdnmCd': '411733012016',
    'rdnm': '경기도 안양시 동안구 학의로',
    'bldMnno': 282,
    'bldSlno': '',
    'bldMngNo': '4117310200108100000012996',
    'bldNm': '제',
    'rdnmAdr': '경기도 안양시 동안구 학의로 282',
    'oldZipcd': '431810',
    'newZipcd': '14056',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.969133286162,
    'lat': 37.4010635556705},
   {'bizesId': 'MA0106202405A2021697',
    'bizesNm': '코리엔탈깻잎두마리치킨&모락로제떡볶이원주점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '51',
    'ctprvnNm': '강원특별자치도',
    'signguCd': '51130',
    'signguNm': '원주시',
    'adongCd': '51130330',
    'adongNm': '지정면',
    'ldongCd': '5113033023',
    'ldongNm': '지정면',
    'lnoCd': '5113033023113480009',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1348,
    'lnoSlno': 9,
    'lnoAdr': '강원특별자치도 원주시 지정면 가곡리 1348-9',
    'rdnmCd': '511303350530',
    'rdnm': '강원특별자치도 원주시 지정면 신지정로',
    'bldMnno': 184,
    'bldSlno': '',
    'bldMngNo': '4213033023113480009000001',
    'bldNm': '',
    'rdnmAdr': '강원특별자치도 원주시 지정면 신지정로 184',
    'oldZipcd': '220821',
    'newZipcd': '26353',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.876472576101,
    'lat': 37.3743120804409},
   {'bizesId': 'MA0106202412A2102800',
    'bizesNm': '중앙닭강정강남',
    'brchNm': '직영점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11650',
    'signguNm': '서초구',
    'adongCd': '11650580',
    'adongNm': '반포3동',
    'ldongCd': '1165010600',
    'ldongNm': '잠원동',
    'lnoCd': '1165010600100700002',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 70,
    'lnoSlno': 2,
    'lnoAdr': '서울특별시 서초구 잠원동 70-2',
    'rdnmCd': '116503121019',
    'rdnm': '서울특별시 서초구 잠원로',
    'bldMnno': 51,
    'bldSlno': '',
    'bldMngNo': '1165010600100700002017536',
    'bldNm': '식품관',
    'rdnmAdr': '서울특별시 서초구 잠원로 51',
    'oldZipcd': '137711',
    'newZipcd': '06511',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.007442214525,
    'lat': 37.5092429685439},
   {'bizesId': 'MA0106202412A1503360',
    'bizesNm': '대림닭강정왕십리역사점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11200',
    'signguNm': '성동구',
    'adongCd': '11200560',
    'adongNm': '행당1동',
    'ldongCd': '1120010700',
    'ldongNm': '행당동',
    'lnoCd': '1120010700101680151',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 168,
    'lnoSlno': 151,
    'lnoAdr': '서울특별시 성동구 행당동 168-151',
    'rdnmCd': '112003103005',
    'rdnm': '서울특별시 성동구 왕십리광장로',
    'bldMnno': 17,
    'bldSlno': '',
    'bldMngNo': '1120010700101680001017508',
    'bldNm': '비트플렉스',
    'rdnmAdr': '서울특별시 성동구 왕십리광장로 17',
    'oldZipcd': '133866',
    'newZipcd': '04750',
    'dongNo': '',
    'flrNo': '2',
    'hoNo': '',
    'lon': 127.038391477602,
    'lat': 37.5614409428511},
   {'bizesId': 'MA0106202405A1938675',
    'bizesNm': '노랑통닭가촌점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48330',
    'signguNm': '양산시',
    'adongCd': '48330253',
    'adongNm': '물금읍',
    'ldongCd': '4833025323',
    'ldongNm': '물금읍',
    'lnoCd': '4833025323112690016',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1269,
    'lnoSlno': 16,
    'lnoAdr': '경상남도 양산시 물금읍 가촌리 1269-16',
    'rdnmCd': '483303338111',
    'rdnm': '경상남도 양산시 물금읍 백호로',
    'bldMnno': 76,
    'bldSlno': '',
    'bldMngNo': '4833025323112690016000001',
    'bldNm': '',
    'rdnmAdr': '경상남도 양산시 물금읍 백호로 76',
    'oldZipcd': '626811',
    'newZipcd': '50613',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 129.002520121772,
    'lat': 35.3174399856685},
   {'bizesId': 'MA0106202502A1360638',
    'bizesNm': '알비/산방산치킨그랜드메르호텔점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '50',
    'ctprvnNm': '제주특별자치도',
    'signguCd': '50130',
    'signguNm': '서귀포시',
    'adongCd': '50130620',
    'adongNm': '예래동',
    'ldongCd': '5013012100',
    'ldongNm': '하예동',
    'lnoCd': '5013012100104600001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 460,
    'lnoSlno': 1,
    'lnoAdr': '제주특별자치도 서귀포시 하예동 460-1',
    'rdnmCd': '501303350039',
    'rdnm': '제주특별자치도 서귀포시 논짓물로',
    'bldMnno': 45,
    'bldSlno': '',
    'bldMngNo': '5013012100104500001000001',
    'bldNm': '',
    'rdnmAdr': '제주특별자치도 서귀포시 논짓물로 45',
    'oldZipcd': '697310',
    'newZipcd': '63538',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.38611901535,
    'lat': 33.239642791679},
   {'bizesId': 'MA0106202305A0525778',
    'bizesNm': '예술치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '28',
    'ctprvnNm': '인천광역시',
    'signguCd': '28237',
    'signguNm': '부평구',
    'adongCd': '28237592',
    'adongNm': '청천2동',
    'ldongCd': '2823710400',
    'ldongNm': '청천동',
    'lnoCd': '2823710400102360017',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 236,
    'lnoSlno': 17,
    'lnoAdr': '인천광역시 부평구 청천동 236-17',
    'rdnmCd': '282373154073',
    'rdnm': '인천광역시 부평구 원적로',
    'bldMnno': 435,
    'bldSlno': '',
    'bldMngNo': '2823710400102360017000001',
    'bldNm': '',
    'rdnmAdr': '인천광역시 부평구 원적로 435',
    'oldZipcd': '403858',
    'newZipcd': '21364',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.714988709615,
    'lat': 37.5037996860147},
   {'bizesId': 'MA0106202405A0770625',
    'bizesNm': '2피자1치킨상회',
    'brchNm': '2호점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '27',
    'ctprvnNm': '대구광역시',
    'signguCd': '27290',
    'signguNm': '달서구',
    'adongCd': '27290585',
    'adongNm': '신당동',
    'ldongCd': '2729010700',
    'ldongNm': '신당동',
    'lnoCd': '2729010700118180005',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1818,
    'lnoSlno': 5,
    'lnoAdr': '대구광역시 달서구 신당동 1818-5',
    'rdnmCd': '272903147025',
    'rdnm': '대구광역시 달서구 신당로',
    'bldMnno': 12,
    'bldSlno': 1,
    'bldMngNo': '2729010700118180005000762',
    'bldNm': '',
    'rdnmAdr': '대구광역시 달서구 신당로 12-1',
    'oldZipcd': '704922',
    'newZipcd': '42614',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.493611786897,
    'lat': 35.8535131539341},
   {'bizesId': 'MA0106202405A2425484',
    'bizesNm': '구도로통닭',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '27',
    'ctprvnNm': '대구광역시',
    'signguCd': '27290',
    'signguNm': '달서구',
    'adongCd': '27290555',
    'adongNm': '감삼동',
    'ldongCd': '2729011300',
    'ldongNm': '감삼동',
    'lnoCd': '2729011300107090000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 709,
    'lnoSlno': '',
    'lnoAdr': '대구광역시 달서구 감삼동 709',
    'rdnmCd': '272904241423',
    'rdnm': '대구광역시 달서구 와룡로31길',
    'bldMnno': 26,
    'bldSlno': '',
    'bldMngNo': '2729011300105560000000002',
    'bldNm': '힐스테이트감삼',
    'rdnmAdr': '대구광역시 달서구 와룡로31길 26',
    'oldZipcd': '704150',
    'newZipcd': '42688',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.533918639207,
    'lat': 35.8468053089674},
   {'bizesId': 'MA0106202407A2169373',
    'bizesNm': '김해동상점뉴욕버거.또래오래동상부원점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48250',
    'signguNm': '김해시',
    'adongCd': '48250510',
    'adongNm': '동상동',
    'ldongCd': '4825010100',
    'ldongNm': '동상동',
    'lnoCd': '4825010100111170000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1117,
    'lnoSlno': '',
    'lnoAdr': '경상남도 김해시 동상동 1117',
    'rdnmCd': '482503335004',
    'rdnm': '경상남도 김해시 가야로',
    'bldMnno': 470,
    'bldSlno': '',
    'bldMngNo': '4825010100111170000000001',
    'bldNm': '김해캐슬아리스타궁',
    'rdnmAdr': '경상남도 김해시 가야로 470',
    'oldZipcd': '621020',
    'newZipcd': '50913',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.885801623266,
    'lat': 35.2393648203425},
   {'bizesId': 'MA0106202305A1208862',
    'bizesNm': '치킨아이',
    'brchNm': '매곡점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56111',
    'ksicNm': '한식 일반 음식점업',
    'ctprvnCd': '29',
    'ctprvnNm': '광주광역시',
    'signguCd': '29170',
    'signguNm': '북구',
    'adongCd': '29170673',
    'adongNm': '매곡동',
    'ldongCd': '2917011700',
    'ldongNm': '매곡동',
    'lnoCd': '2917011700102140001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 214,
    'lnoSlno': 1,
    'lnoAdr': '광주광역시 북구 매곡동 214-1',
    'rdnmCd': '291703162014',
    'rdnm': '광주광역시 북구 매곡로',
    'bldMnno': 84,
    'bldSlno': '',
    'bldMngNo': '2917011700102140001036939',
    'bldNm': '대화',
    'rdnmAdr': '광주광역시 북구 매곡로 84',
    'oldZipcd': '500815',
    'newZipcd': '61059',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.892856851572,
    'lat': 35.1920174068033},
   {'bizesId': 'MA0106202302A1246093',
    'bizesNm': '청정횟집&bhc무창포해수욕장점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',

In [9]:
# 열 설정
response['header']['columns']

['상가업소번호',
 '상호명',
 '지점명',
 '상권업종대분류코드',
 '상권업종대분류명',
 '상권업종중분류코드',
 '상권업종중분류명',
 '상권업종소분류코드',
 '상권업종소분류명',
 '표준산업분류코드',
 '표준산업분류명',
 '시도코드',
 '시도명',
 '시군구코드',
 '시군구명',
 '행정동코드',
 '행정동명',
 '법정동코드',
 '법정동명',
 'PNU코드',
 '대지구분코드',
 '대지구분명',
 '지번본번지',
 '지번부번지',
 '지번주소',
 '도로명코드',
 '도로명',
 '건물본번지',
 '건물부번지',
 '건물관리번호',
 '건물명',
 '도로명주소',
 '구우편번호',
 '신우편번호',
 '동정보',
 '층정보',
 '호정보',
 '경도',
 '위도']

In [10]:
total_page=(response['body']['totalCount']//1000)+1

In [11]:
#반복해야 할 페이지 수
response['body']['totalCount']//response['body']['numOfRows']+1

41

In [12]:
page=response['body']['pageNo']
while True:
    result={}
    for item in response['body']['items']:
        for key, value in item.items():
            result.setdefault(key, []).append(value)
    if page > int(response['body']['totalCount'])//int(response['body']['numOfRows'])+1:
        break
    else:
        page+=1
df=pd.DataFrame(result)
df

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,MA0106202306A0595317,마마치킨마포지점,,I2,음식,I210,기타 간이,I21006,치킨,I56192,...,1144010500100190003003692,,서울특별시 마포구 큰우물로 62,121875,04166,,1,,126.944951,37.541666
1,MA0106202303A0590715,돈치킨용인서천점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4146310900104130002000001,,경기도 용인시 기흥구 서천로202번길 2,446920,17110,,1,,127.070068,37.230751
2,MA0106202308A1870651,치킨몬스터김해삼미대박집,삼계점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4825010700114750004081552,,경상남도 김해시 해반천로144번길 23-5,621070,50901,,,,128.869581,35.261515
3,MA0106202312A2442023,유일닭강정가평맛집,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4182025021104710002005180,,경기도 가평군 가평읍 가화로 122,477805,12419,,1,,127.513662,37.830557
4,MA0106202401A1467223,프랜푸드땅땅치킨잠원,한강점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,1165010600100350001019342,,서울특별시 서초구 강남대로95길 47-4,137905,06530,,1,,127.017679,37.512828
5,MA0106202405A2153895,림스치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4511114200115440003000001,유탑유블레스리버뷰,전북특별자치도 전주시 완산구 서원로 145,560900,54969,,1,,127.110595,35.814448
6,MA0106202410A2451537,교촌치킨목동,파크자이점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,1147010100101710061000192,목동파크자이,서울특별시 양천구 목동남로4길 80,158077,08102,,3,,126.868473,37.508530
7,MA0106202311A0627476,지코바,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,2826011500108100011000008,,인천광역시 서구 원당대로839번길 35-1,404320,22644,,,,126.696201,37.596483
8,MA0106202501A2302176,넥스트치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4117310200108100000012996,제,경기도 안양시 동안구 학의로 282,431810,14056,,1,,126.969133,37.401064
9,MA0106202405A2021697,코리엔탈깻잎두마리치킨&모락로제떡볶이원주점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4213033023113480009000001,,강원특별자치도 원주시 지정면 신지정로 184,220821,26353,,1,,127.876473,37.374312
10,MA0106202412A2102800,중앙닭강정강남,직영점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,1165010600100700002017536,식품관,서울특별시 서초구 잠원로 51,137711,06511,,1,,127.007442,37.509243
11,MA0106202412A1503360,대림닭강정왕십리역사점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,1120010700101680001017508,비트플렉스,서울특별시 성동구 왕십리광장로 17,133866,04750,,2,,127.038391,37.561441
12,MA0106202405A1938675,노랑통닭가촌점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4833025323112690016000001,,경상남도 양산시 물금읍 백호로 76,626811,50613,,,,129.002520,35.317440
13,MA0106202502A1360638,알비/산방산치킨그랜드메르호텔점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5013012100104500001000001,,제주특별자치도 서귀포시 논짓물로 45,697310,63538,,,,126.386119,33.239643
14,MA0106202305A0525778,예술치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,2823710400102360017000001,,인천광역시 부평구 원적로 435,403858,21364,,1,,126.714989,37.503800
15,MA0106202405A0770625,2피자1치킨상회,2호점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,2729010700118180005000762,,대구광역시 달서구 신당로 12-1,704922,42614,,1,,128.493612,35.853513
16,MA0106202405A2425484,구도로통닭,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,2729011300105560000000002,힐스테이트감삼,대구광역시 달서구 와룡로31길 26,704150,42688,,1,,128.533919,35.846805
17,MA0106202407A2169373,김해동상점뉴욕버거.또래오래동상부원점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4825010100111170000000001,김해캐슬아리스타궁,경상남도 김해시 가야로 470,621020,50913,,,,128.885802,35.239365
18,MA0106202305A1208862,치킨아이,매곡점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,2917011700102140001036939,대화,광주광역시 북구 매곡로 84,500815,61059,,,,126.892857,35.192017
19,MA0106202302A1246093,청정횟집&bhc무창포해수욕장점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4418025029200020015000001,,충청남도 보령시 웅천읍 열린바다로 388-34,355852,33509,,1,,126.530393,36.238129
20,MA0106202305A1329764,천년닭강정부천,부평점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4119510900105310003033766,광장프라자,경기도 부천시 원미구 길주로77번길 19-27,420861,14543,,,,126.749382,37.506914
21,MA0106202412A1186515,페리카나치킨가능,2호점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4115011000106470027004671,,경기도 의정부시 가능로 101-1,480814,11683,,1,,127.042424,37.746997
22,MA0106202405A2168897,김해동상점뉴욕버거또래오래동산부원점,,I2,음식,I210,기타 간이,I21006,치킨,I56192,...,4825010100111170000000001,김해캐슬아리스타궁,경상남도 김해시 가야로 470,621020,50913,,,,128.885802,35.239365
23,MA0106202410A1330431,비에이치씨금산,금성점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4471031026102890008029210,,충청남도 금산군 금성면 파초길 47-2,312913,32708,,1,,127.465696,36.129965
24,MA0106202305A2358896,아라치치킨,교동점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4215013200100690004004403,,강원특별자치도 강릉시 경포로15번길 5-2,210320,25465,,,,128.876047,37.772503
25,MA0106202403A0677603,BHC치킨오르새피자,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5176033021110010131000001,,강원특별자치도 평창군 대화면 청룡길 32,232912,25358,,,,128.453768,37.500999
26,MA0106202407A1257991,또래오래치킨조례점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4615013300108510000002618,대림1차,전라남도 순천시 봉화2길 119,540775,57934,,1,,127.517731,34.963401
27,MA0106202311A1976184,노랑통닭대구,반야월점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,2714012400106240020000001,,대구광역시 동구 안심로73길 12-10,701870,41083,,1,,128.726153,35.869375
28,MA0106202309A2238332,굽네치킨지축점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4128110900110700001000001,,경기도 고양시 덕양구 지정로 20,412140,10585,,1,,126.916681,37.647264
29,MA0106202306A1189937,페리카나치킨가능,2호점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4115011000107460029011991,,경기도 의정부시 흥선로92번길 15-15,480819,11672,,1,,127.037690,37.741917
30,MA0106202311A0409598,피오에이취BHC풍납올림픽공원점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,1171010300104000001025147,율곡빌라,서울특별시 송파구 올림픽로47길 11,138879,05538,,1,,127.117499,37.528016
31,MA0106202411A0249701,보드람치킨,대치점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,1168010600109910000013756,남성빌딩,서울특별시 강남구 도곡로 524,135501,06282,,1,,127.063737,37.499522
32,MA0106202411A2096411,중앙닭강정하남미사,직영점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4145011000101390002000001,,경기도 하남시 미사강변대로 90,465170,12919,,1,,127.188123,37.557892
33,MA0106202403A2243083,맥시칸치킨동,수원점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4111514100109430000015042,,경기도 수원시 팔달구 장다리로 304,442832,16484,,1,,127.030894,37.275172
34,MA0106202312A2176704,프랑킨숯불양념구이치킨,부평점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,2823710100108890011101455,,인천광역시 부평구 길주남로 25-4,403860,21354,,1,,126.724609,37.504868
35,MA0106202401A0257107,경성치킨광화문,스퀘어점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,1111012000101350002027935,지상,서울특별시 종로구 새문안로 96,110054,03186,,1,,126.975437,37.569941

In [13]:
import json
import os
import pandas as pd
import requests

In [14]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\admin\miniforge3\envs\fintech\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\admin\miniforge3\envs\fintech\lib\site-packages (from openpyxl) (2.0.0)

In [15]:
ori_data=pd.read_excel("./data/복사본 소상공인시장진흥공단_상가(상권)정보_업종분류(2302)_및_연계표_v1.0.xlsx", engine='openpyxl', header=[1])
ori_data

    대분류코드          대분류명 중분류코드              중분류명   소분류코드            소분류명
0      G2           소매업  G202  자동차 부품 및 내장품 소매업  G20201         타이어 소매업
1      G2           소매업  G202  자동차 부품 및 내장품 소매업  G20202      자동차 부품 소매업
2      G2           소매업  G203    모터사이클 및 부품 소매업  G20301  모터사이클 및 부품 소매업
3      G2           소매업  G204            종합 소매업  G20404            슈퍼마켓
4      G2           소매업  G204            종합 소매업  G20405             편의점
..    ...           ...   ...               ...     ...             ...
242    S2  수리 및 개인 서비스업  S209               세탁업  S20902          셀프 빨래방
243    S2  수리 및 개인 서비스업  S210    장례식장 및 관련 서비스업  S21001            장례식장
244    S2  수리 및 개인 서비스업  S210    장례식장 및 관련 서비스업  S21002      화장터/묘지/납골당
245    S2  수리 및 개인 서비스업  S211          기타 개인서비스  S21101            예식장업
246    S2  수리 및 개인 서비스업  S211          기타 개인서비스  S21105      결혼 상담 서비스업

[247 rows x 6 columns]

In [18]:
errors = []
for idx, (code, name) in enumerate(zip(ori_data['소분류코드'][80:], ori_data['소분류명'][80:])):
    name = name.replace("/", "_").replace("·", "_")
    print(f"{name}_수집중 {idx}/{len(ori_data['소분류코드'])}", end="\r")
    page = 1
    result_dfs = []
    while True:
        url = "http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
        service_key = "TUszyF9E+ahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9+oN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw=="
        payload = dict(servicekey=service_key, divId="indsSclsCd", 
                      key=code, numOfRows=1000, pageNo=page, type="json")
        r = requests.get(url, params=payload)
        print(r.url, end="\r")
        print(r.status_code, end="\r")

        response = r.json()
        try:
            total_page = (response['body']['totalCount'] // 1000) + 1
        except Exception as e:
            print("데이터 없음", end="\r")
            errors.append(f"{idx}, {code}, {name} 데이터 없음")
            break
        result_dfs.append(unpack_data(response))
        print(f"{page}/{total_page} 수집중", end="\r")
        if page < total_page:
            page += 1
        else:
            break
        time.sleep(0.2)

    result = pd.concat(result_dfs)    
    result = result.reset_index(drop=True)
    
    # 폴더가 있는지 확인하고 없으면 폴더 생성하기
    if not os.path.exists("./scraping_results"):
        os.mkdir("./scraping_results")
#     else:
#         print("scraping_results이 이미 있습니다.")
    
    result.to_csv(f"./scraping_results/공공데이터_{name}_상권정보_202504.csv", encoding="utf-8", index=False)

KeyboardInterrupt: