# 4.2

# xml: html처럼 태그 기반으로 자료를 저장한 포멧
* xml parser를 통해서 str을 xml로 변환하는 작업필요
* xml로 변환이 되면 태그 기반으로 자료를 찾아서 정리
* 태그에서 자료를 추출할 때는 beautifulsoup이라는 라이브러리를 이용

# 전세대출 데이터 수집하기

In [4]:
import requests
import json
import os
import time
import pandas as pd

In [4]:
url="http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list"
servicekey="TUszyF9E+ahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9+oN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw=="
payload=dict(serviceKey=servicekey, numOfRows=10, pageNo=1, dataType='JSON')
r=requests.get(url, params=payload)
response=r.json()
response

{'header': {'resultCode': '00', 'resultMsg': '정상'},
 'body': {'pageNo': 1,
  'totalCount': 18,
  'numOfRows': 10,
  'items': [{'bssYmdStart': '20250526',
    'interest4_1': '0',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': '산업은행',
    'callCenter': '1588-1500'},
   {'bssYmdStart': '20250526',
    'interest4_1': '0',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': '수협은행',
    'callCenter': '1588-1515'},
   {'bssYmdStart': '20250526',
    'interest4_1': '0',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': 'SC은행',
    'callCenter': '1588-1599'},
   {'bssYmdStart': '20250526',
    'interest4_1': '5.06',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': '경남은행',
    'callCenter': '1588-8585'},
   {'bssYmdStart': '20250526',
    'interest4_1': '0',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': '제주은행',
    'callCenter': '1588-0079'},
   {'bssYmdStart': '20250526',
    'interest4_1': '4.04',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': '광주은행',
    'callCenter': '1600-4000'},
   {'bssYmdStart': '20250526',
    'interest4_1': '4.8',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': '전북은행',
    'callCenter': '1588-4477'},
   {'bssYmdStart': '20250526',
    'interest4_1': '3.37',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': '토스뱅크',
    'callCenter': '1661-7654'},
   {'bssYmdStart': '20250526',
    'interest4_1': '2.92',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': '아이엠뱅크',
    'callCenter': '1588-5050'},
   {'bssYmdStart': '20250526',
    'interest4_1': '3.93',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250601',
    'organId': '우리은행',
    'callCenter': '1599-5000'}]}}

In [9]:
def unpack_data(response):
    result={}
    for item in response['body']['items']:
        for key, value in item.items():
            result.setdefault(key,[]).append(value)
    df=pd.DataFrame(result)
    return df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250526,0,0,0,0,0,0,0,0,20250601,산업은행,1588-1500
1,20250526,0,0,0,0,0,0,0,0,20250601,수협은행,1588-1515
2,20250526,0,0,0,0,0,0,0,0,20250601,SC은행,1588-1599
3,20250526,5.06,0,0,0,0,0,0,0,20250601,경남은행,1588-8585
4,20250526,0,0,0,0,0,0,0,0,20250601,제주은행,1588-0079
5,20250526,4.04,0,0,0,0,0,0,0,20250601,광주은행,1600-4000
6,20250526,4.8,0,0,0,0,0,0,0,20250601,전북은행,1588-4477
7,20250526,3.37,0,0,0,0,0,0,0,20250601,토스뱅크,1661-7654
8,20250526,2.92,0,0,0,0,0,0,0,20250601,아이엠뱅크,1588-5050
9,20250526,3.93,0,0,0,0,0,0,0,20250601,우리은행,1599-5000

In [14]:
page=1
result={}
while True:
    url="http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list"
    servicekey="TUszyF9E+ahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9+oN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw=="
    payload=dict(serviceKey=servicekey, numOfRows=10, pageNo=page, dataType='JSON')
    r=requests.get(url, params=payload)
    response=r.json()
    for item in response['body']['items']:
        for key, value in item.items():
            result.setdefault(key,[]).append(value)
    total_page=(response['body']['totalCount']//10)+1
    if page<total_page:
        page+=1
    else:
        break
df=pd.DataFrame(result)
df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250526,0,0,0,0,0,0,0,0,20250601,산업은행,1588-1500
1,20250526,0,0,0,0,0,0,0,0,20250601,수협은행,1588-1515
2,20250526,0,0,0,0,0,0,0,0,20250601,SC은행,1588-1599
3,20250526,5.06,0,0,0,0,0,0,0,20250601,경남은행,1588-8585
4,20250526,0,0,0,0,0,0,0,0,20250601,제주은행,1588-0079
5,20250526,4.04,0,0,0,0,0,0,0,20250601,광주은행,1600-4000
6,20250526,4.8,0,0,0,0,0,0,0,20250601,전북은행,1588-4477
7,20250526,3.37,0,0,0,0,0,0,0,20250601,토스뱅크,1661-7654
8,20250526,2.92,0,0,0,0,0,0,0,20250601,아이엠뱅크,1588-5050
9,20250526,3.93,0,0,0,0,0,0,0,20250601,우리은행,1599-5000
10,20250526,3.5,0,0,0,0,0,0,0,20250601,국민은행,1644-9999
11,20250526,3.42,0,0,0,0,0,0,0,20250601,케이뱅크,1522-1000
12,20250526,3.65,0,0,0,0,0,0,0,20250601,카카오뱅크,1599-3333
13,20250526,3.62,0,0,0,0,0,0,0,20250601,농협은행,1588-2100
14,20250526,3.75,0,0,0,0,0,0,0,20250601,하나은행,1599-1111
15,20250526,3.73,0,0,0,0,0,0,0,20250601,신한은행,1599-8000
16,20250526,3.85,0,0,0,0,0,0,0,20250601,부산은행,1588-6200
17,20250526,3.78,0,0,0,0,0,0,0,20250601,기업은행,1566-2566

# xml로 가져오기

In [5]:
from bs4 import BeautifulSoup as bs

In [11]:
url="http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list"
servicekey="TUszyF9E+ahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9+oN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw=="
payload=dict(serviceKey=servicekey, numOfRows=1000, pageNo=1, dataType='XML')
r=requests.get(url, params=payload)
response=r.content
soup=bs(response, 'xml')
xml_result={}
for item in soup.select('item'):
    for tags in item:
        if tags.name==None:
            continue
        else:
            xml_result.setdefault(tags.name, []).append(tags.text)
xml_result_df=pd.DataFrame(xml_result)
xml_result_df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250526,0,0,0,0,0,0,0,0,20250601,산업은행,1588-1500
1,20250526,0,0,0,0,0,0,0,0,20250601,수협은행,1588-1515
2,20250526,0,0,0,0,0,0,0,0,20250601,SC은행,1588-1599
3,20250526,5.06,0,0,0,0,0,0,0,20250601,경남은행,1588-8585
4,20250526,0,0,0,0,0,0,0,0,20250601,제주은행,1588-0079
5,20250526,4.04,0,0,0,0,0,0,0,20250601,광주은행,1600-4000
6,20250526,4.8,0,0,0,0,0,0,0,20250601,전북은행,1588-4477
7,20250526,3.37,0,0,0,0,0,0,0,20250601,토스뱅크,1661-7654
8,20250526,2.92,0,0,0,0,0,0,0,20250601,아이엠뱅크,1588-5050
9,20250526,3.93,0,0,0,0,0,0,0,20250601,우리은행,1599-5000
10,20250526,3.5,0,0,0,0,0,0,0,20250601,국민은행,1644-9999
11,20250526,3.42,0,0,0,0,0,0,0,20250601,케이뱅크,1522-1000
12,20250526,3.65,0,0,0,0,0,0,0,20250601,카카오뱅크,1599-3333
13,20250526,3.62,0,0,0,0,0,0,0,20250601,농협은행,1588-2100
14,20250526,3.75,0,0,0,0,0,0,0,20250601,하나은행,1599-1111
15,20250526,3.73,0,0,0,0,0,0,0,20250601,신한은행,1599-8000
16,20250526,3.85,0,0,0,0,0,0,0,20250601,부산은행,1588-6200
17,20250526,3.78,0,0,0,0,0,0,0,20250601,기업은행,1566-2566

setdefault를 이용해 xml의 tag명의 유일값 추출하기

In [7]:
tag_names={}
for tags in soup.select("*"):
    tag_names.setdefault(tags.name,"")
for tag_name in tag_names.keys():
    print(tag_name)

response
header
resultCode
resultMsg
body
pageNo
totalCount
numOfRows
items
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter

* xml로 데이터를 받으면 처음에는 단순 문자열로 받게 된다.
* 문자열을 xml 문서로 변환해야 함
* beautifulsoup을 이용해 변환
* beautifulsoup의 메서드인 select, select_one을 이용해 css 셀렉터 기반으로
데이터가 위치한 태그를 찾아서

# BeautifulSoup
* pip install beautifulsoup4
* from bs4 import BeautifulSoup as bs
* find, find_all 함수: xml, htmlm에서 태그 기반으로 내용을 찾음
* select, select_one 함수: xml, html에서 css selector 기반으로 내용을 찾음
* find_all, select는 해당 태그나 css selector를 가진 부분을 모두 찾아서 list로 반환
* find, select_one은 여러 태그나 css selector 중에서 가장 먼저 나오는 태그/selector를 한개만 찾아줌
* 찾아온 태그 .name: 태그 이름 반환
* 찾아온 태그 .text, .string: 태그 안쪽의 텍스트 반환

In [18]:
from bs4 import BeautifulSoup as bs

In [19]:
soup=bs(response, 'xml')
soup

<?xml version="1.0" encoding="utf-8"?>
<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>10</numOfRows><items><item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250526</bssYmdStart><interest4_1>5.06</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250526</bssYmdStart><interest4_1>4.04</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item><item><bssYmdStart>20250526</bssYmdStart><interest4_1>4.8</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250526</bssYmdStart><interest4_1>3.37</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item><item><bssYmdStart>20250526</bssYmdStart><interest4_1>2.92</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250526</bssYmdStart><interest4_1>3.93</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item></items></body></response>

In [9]:
xml_result_df

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item>

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item>

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item>

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>5.06</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item>

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item>

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>4.04</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item>

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>4.8</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item>

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>3.37</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item>

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>2.92</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item>

<item><bssYmdStart>20250526</bssYmdStart><interest4_1>3.93</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item>

In [20]:
soup.select_one('resultCode')

In [25]:
for tag in items.select_one("item"):
    print(tag.name)

bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter

In [26]:
items=soup.select_one('items')
bssYmdStart_list=items.select('bssYmdStart')
interest4_1_list=items.select('interest4_1')
interest3_2_list=items.select('interest3_2')
interest4_2_list=items.select('interest4_2')
interest2_1_list=items.select('interest2_1')
interest1_2_list=items.select('interest1_2')
interest3_1_list=items.select('interest3_1')
interest2_2_list=items.select('interest2_2')
interest1_1_list=items.select('interest1_1')
bssYmdEnd_list=items.select('bssYmdEnd')
organId_list=items.select('organId')
callCenter_list=items.select('callCenter')

In [28]:
tag_list=[bssYmdStart_list,interest4_1_list, interest3_2_list,interest4_2_list, interest2_1_list, interest1_2_list, interest3_1_list, interest2_2_list, interest1_1_list, bssYmdEnd_list, organId_list, callCenter_list ]

In [31]:
result={}
for lists in tag_list:
    for item in lists:
        result.setdefault(item.name, []).append(item.text)
result

{'bssYmdStart': ['20250526',
  '20250526',
  '20250526',
  '20250526',
  '20250526',
  '20250526',
  '20250526',
  '20250526',
  '20250526',
  '20250526'],
 'interest4_1': ['0',
  '0',
  '0',
  '5.06',
  '0',
  '4.04',
  '4.8',
  '3.37',
  '2.92',
  '3.93'],
 'interest3_2': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'interest4_2': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'interest2_1': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'interest1_2': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'interest3_1': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'interest2_2': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'interest1_1': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'bssYmdEnd': ['20250601',
  '20250601',
  '20250601',
  '20250601',
  '20250601',
  '20250601',
  '20250601',
  '20250601',
  '20250601',
  '20250601'],
 'organId': ['산업은행',
  '수협은행',
  'SC은행',
  '경남은행',
  '제주은행',
  '광주은행',
  '전북은행',
  '토스뱅크',
  '아이엠뱅크',
  '우리은행'],
 'callCenter': ['1588-1500',
  '1588-1515',
  '1588-1599',
  '1588-8585',
  '1588-0079',
  '1600-4000',
  '1588-4477',
  '1661-7654',
  '1588-5050',
  '1599-5000']}

# 반복문으로 태그를 자동 추출해서 만들기

In [40]:
for tag in soup.select("item")[0]:
    print(tag.name, tag.text)
#     print(key.name, key.text)

bssYmdStart 20250526
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250601
organId 산업은행
callCenter 1588-1500

In [41]:
result = {}
for tags in soup.select("item"):
    for tag in tags:
        result.setdefault(tag.name, []).append(tag.text)
df = pd.DataFrame(result)
df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250526,0,0,0,0,0,0,0,0,20250601,산업은행,1588-1500
1,20250526,0,0,0,0,0,0,0,0,20250601,수협은행,1588-1515
2,20250526,0,0,0,0,0,0,0,0,20250601,SC은행,1588-1599
3,20250526,5.06,0,0,0,0,0,0,0,20250601,경남은행,1588-8585
4,20250526,0,0,0,0,0,0,0,0,20250601,제주은행,1588-0079
5,20250526,4.04,0,0,0,0,0,0,0,20250601,광주은행,1600-4000
6,20250526,4.8,0,0,0,0,0,0,0,20250601,전북은행,1588-4477
7,20250526,3.37,0,0,0,0,0,0,0,20250601,토스뱅크,1661-7654
8,20250526,2.92,0,0,0,0,0,0,0,20250601,아이엠뱅크,1588-5050
9,20250526,3.93,0,0,0,0,0,0,0,20250601,우리은행,1599-5000

In [42]:
soup.select("item")

[<item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item>,
 <item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item>,
 <item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item>,
 <item><bssYmdStart>20250526</bssYmdStart><interest4_1>5.06</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item>,
 <item><bssYmdStart>20250526</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item>,
 <item><bssYmdStart>20250526</bssYmdStart><interest4_1>4.04</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item>,
 <item><bssYmdStart>20250526</bssYmdStart><interest4_1>4.8</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item>,
 <item><bssYmdStart>20250526</bssYmdStart><interest4_1>3.37</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item>,
 <item><bssYmdStart>20250526</bssYmdStart><interest4_1>2.92</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item>,
 <item><bssYmdStart>20250526</bssYmdStart><interest4_1>3.93</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250601</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item>]

# xml에 있는 모든 key를 추출하기

In [51]:
tag_names = []
for items in soup.select("item"):
    for item in items:
        tag_names.append(item.name)
len(tag_names)

120

# 집합자료형 set: 중복 없는 데이터 집합 만들기

In [50]:
tags=set(tag_names)
tags

{'body',
 'bssYmdEnd',
 'bssYmdStart',
 'callCenter',
 'header',
 'interest1_1',
 'interest1_2',
 'interest2_1',
 'interest2_2',
 'interest3_1',
 'interest3_2',
 'interest4_1',
 'interest4_2',
 'item',
 'items',
 'numOfRows',
 'organId',
 'pageNo',
 'response',
 'resultCode',
 'resultMsg',
 'totalCount'}

In [52]:
import requests
import json
import os
import pandas as pd
import time

In [55]:
url="https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
servicekey="TUszyF9E+ahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9+oN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw=="
payload=dict(serviceKey=servicekey, numOfRows=100, pageNo=1, resultType='json')
r=requests.get(url, params=payload)
response=r.json()
response

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'numOfRows': 100,
   'pageNo': 1,
   'totalCount': 5439,
   'items': {'item': [{'basYm': '202505',
      'snq': '1',
      'finPrdNm': '새희망홀씨Ⅱ',
      'lnLmt': '3500만원',
      'irtCtg': '변동금리',
      'irt': '은행별 상이',
      'maxTotLnTrm': '은행별 상이',
      'maxDfrmTrm': '-',
      'maxRdptTrm': '-',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자',
      'instCtg': '시중은행',
      'ofrInstNm': '14개 취급은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하',
      'age': '없음',
      'incm': '연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)',
      'rsdArea': '-',
      'crdtSc': '신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '취급은행 콜센터, 서민금융콜센터 (국번없이)1397',
      'grnInst': '-',
      'jnMthd': '14개 취급은행 신청방법 문의',
      'rpymdCfe': '-',
      'lnIcdcst': '-',
      'ovItrYr': '-',
      'prftAddIrtCond': '성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)',
      'etcRefSbjc': '-',
      'hdlInst': '취급 은행(14개)',
      'cnpl': '취급은행 콜센터, 서민금융콜센터 (국번없이)1397',
      'rltSite': '취급은행 홈페이지',
      'tgtFltr': '근로자',
      'hdlInstDtlVw': '취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '2',
      'finPrdNm': '징검다리론',
      'lnLmt': '3000만원',
      'irtCtg': '변동금리',
      'irt': '은행별 상이',
      'maxTotLnTrm': '5년',
      'maxDfrmTrm': '1년',
      'maxRdptTrm': '4년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자, 대학생·청년, 채무조정자, 금융취약계층',
      'instCtg': '시중은행',
      'ofrInstNm': '15개 취급은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '4대 서민금융상품(새희망홀씨, 햇살론, 미소금융, 바꿔드림론)을 성실상환한 자1) 4대 서민금융상품 중 어느 하나를 2년 이상 거래한 후 해당 대출 원금의 75% 이상을 상환한 자 또는 거래기간에 상관없이 전액상환한 자2) CB신용평점: 상위 80%',
      'age': '없음',
      'incm': '없음',
      'rsdArea': '-',
      'crdtSc': 'CB신용평점: 상위 80%',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '취급은행 콜센터',
      'grnInst': '-',
      'jnMthd': '10개 취급은행 방문 또는 신청방법 문의',
      'rpymdCfe': None,
      'lnIcdcst': None,
      'ovItrYr': None,
      'prftAddIrtCond': '사회적 취약계층에 대한 금리 우대',
      'etcRefSbjc': None,
      'hdlInst': '취급 은행(10개)',
      'cnpl': '취급은행 콜센터',
      'rltSite': '취급은행 홈페이지',
      'tgtFltr': '근로자, 대학생·청년, 채무조정자, 금융취약계층',
      'hdlInstDtlVw': '취급은행(국민, 우리, 신한, 하나, SC, 기업, 수협, 부산, 경남, 광주)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '기관 문의',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '3',
      'finPrdNm': '우리지역 氣-Up 서포트론(영세 소기업,소상공인)',
      'lnLmt': '5,00010,000 (코로나 19 피해 소기업, 소상공인)',
      'irtCtg': '변동금리',
      'irt': '6.27~8.97%',
      'maxTotLnTrm': '5년',
      'maxDfrmTrm': '1년',
      'maxRdptTrm': '4년',
      'rdptMthd': '원금균등분할상환',
      'usge': '운영·시설',
      'trgt': '소기업, 소상공인',
      'instCtg': '시중은행',
      'ofrInstNm': 'BNK경남은행',
      'rsdAreaPamtEqltIstm': '경남, 울산',
      'suprTgtDtlCond': '신용보증신청 접수일 현재 사업자등록 후 가동(영업)중으로서 지역보증재단의 신용보증서를 발급받은 소기업ㆍ소상공인① 영세 소기업ㆍ소상공인 : CB평점구간 7구간 이상의 소기업ㆍ소상공인 등 금융소외계층② 코로나19 피해 소기업ㆍ소상공인 : CB평점구간 8구간 이상의 소기업ㆍ소상공인 중 코로나 19로 인해 피해를 입은 경우※ 보증 가능여부는 재단에서 확인 가능함.※ CB평점구간 : 재단에서 보유하고 있는 NICE CB사의 평점구간※ 금융기관 신용관리관리 대상자 등 여신 부적격자에 대하여 대출이 제한될 수 있음',
      'age': '없음',
      'incm': '없음',
      'rsdArea': '-',
      'crdtSc': '① 영세 소기업ㆍ소상공인 : CB평점구간 7구간 이상② 코로나19 피해 소기업ㆍ소상공인 : CB평점구간 8구간 이상',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '1588-85851600-8585',
      'grnInst': '지역신용보증재단',
      'jnMthd': 'BNK경남은행 지점 문의 및 방문',
      'rpymdCfe': '대출취급 후 3년 경과시 면제대출잔여기간 1년 이상 1.6%대출잔여기간 1년 미만 및 할부상환방식일 경우 1.3%',
      'lnIcdcst': '(1) 인지세 : 인지세법에 의해 대출약정 체결시 납부하는 세금으로 대출금액에 따라 세액이 차등 적용되며, 각 50%씩 고객과 은행이 부담합니다.(2) 신용보증서 발급 수수료(고객께서 보증재단에 납부, 고객부담)',
      'ovItrYr': '대출금리+3.0%p (최고 연 15%)',
      'prftAddIrtCond': '(경남은행 계좌 BC가맹점 결제계좌 가입 및 입금) 0.2%p, (본인 신용카드(체크, 가족카드 포함) 이용액(매출표 접수기준)의 최근 3개월(대출취급일의 익월부터 산정) 평균 이용액이 월 평균 50만원 이상인 경우(신규 및 기존 포함)) 0.1%p',
      'etcRefSbjc': '-',
      'hdlInst': 'BNK경남은행',
      'cnpl': '1588-85851600-8585',
      'rltSite': 'https://www.knbank.co.kr/ib20/mnu/FPMLON050101000?ib20_wc=FPMLON210LSTV00M:FPMLON231DETV00M&FNC_PRD_NO=0000202720&FNC_PRD_DIS_CD=04&DUP_CHK=N&ib20_redirect_org_mnu=FPMCOM990000000',
      'tgtFltr': '소기업, 소상공인',
      'hdlInstDtlVw': 'BNK경남은행 전국 지점',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '4',
      'finPrdNm': '경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업)',
      'lnLmt': '9000만원',
      'irtCtg': '변동금리',
      'irt': '은행별 상이',
      'maxTotLnTrm': '임대차계약기간 이내 최대 2년',
      'maxDfrmTrm': '0년',
      'maxRdptTrm': '0년',
      'rdptMthd': '일시상환',
      'usge': '주거',
      'trgt': '근로자, 사업자, 청년',
      'instCtg': '시중은행',
      'ofrInstNm': 'BNK경남은행',
      'rsdAreaPamtEqltIstm': '경남',
      'suprTgtDtlCond': '- 아래 요건을 모두 충족1) 경상남도에 주소를 두고 있거나, 대출신청 후 1개월 이내 전입신고 예정인 자2) 신청일 기준 만19세 이상 34세 이하인 청년3) 본인, 배우자, 자녀가 주거급여 대상자가 아니고 무주택인 자4) 다음의 어느 하나에 해당하는 경우  ① 대학(원)생, 취업준비생 등 무소득자 : 부모 합산 연소득 7천만원 이하 또는 부부합산 연소득 6천만원 이하  ② 사회초년생(한 직장에서 5년미만 근무하는 자/자영업자임을 증빙한 지역세대원) : 본인 연소득 4천5백만원 이하 또는 부부합산 연소득 6천만원 이하인 경우 5) 신청인 본인이 주거할 목적으로 경상남도에 소재한 임차보증금 1억원 이하, 전용면적 60 ㎡ 이하인 주택, 아파트, 오피스텔 등 주거용 건물에 임대차계약 체결 예정자 또는 계약체결 3개월 이내인 자',
      'age': '19세~34세',
      'incm': '본인 연소득 4500만원 이하 / 부부합산 연소득 6000만원 이하',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '무주택',
      'housAr': '60㎡',
      'lnTgtHous': '임차보증금 1억원 이하, 전용면적 60㎡ 이하의 주택 (경상남도 소재)',
      'rfrcCnpl': '경상남도 건축주택과 (Tel. 055-211-4374)',
      'grnInst': '주택금융공사',
      'jnMthd': '[경상남도 바로서비스누리집] 에서 본 사업 신청서 작성 → 제출서류 첨부 자격심사 통과 후 은행지점 방문',
      'rpymdCfe': '없음',
      'lnIcdcst': '중도상환해약금(면제), 수입인지(건별 대출금액 5천만원 초과시 금액구간별 차등 부과_고객부담 50%), 주택금융공사 신용보증료(보증금액의 0.05%)',
      'ovItrYr': '-',
      'prftAddIrtCond': '은행자체 우대금리 : 급여이체, 카드사용 실적 등을 통한 우대금리 적용',
      'etcRefSbjc': '본인부담금리 = 은행 자체규정에 따른 금리 - 0.5%(우대금리) - 3%(경남도지원금리) - α(은행자체 우대금리)',
      'hdlInst': '농협은행, BNK경남은행',
      'cnpl': '경상남도 건축주택과 (Tel. 055-211-4374)',
      'rltSite': '경남 바로 서비스(https://baro.gyeongnam.go.kr/baro/serviceView.es?mid=a10202000000&service_no=183)',
      'tgtFltr': '근로자, 사업자, 청년',
      'hdlInstDtlVw': '농협은행 경남지역지점, BNK 경남은행 경남지역지점(지역 농？축협은 대출 미취급)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '5',
      'finPrdNm': 'i-ONE근로자생활안정자금대출',
      'lnLmt': '1000만원',
      'irtCtg': '고정금리',
      'irt': '1.5 / 2.6 / 1.0 / 3.0',
      'maxTotLnTrm': '근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년, 8년요양급여비 : 5년직업훈련생계비 : 4년, 6년, 8년재직근로자의 대학학자금 : 7년, 8년, 9년, 10년, 11년',
      'maxDfrmTrm': '6년',
      'maxRdptTrm': '5년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자',
      'instCtg': '시중은행',
      'ofrInstNm': 'IBK기업은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '근로복지공단으로부터 신용보증결정 통보를 받은 고객※대출제외대상-은행연합회 신용정보 등재된 고객-대출신청일 현재 당행 대출금 또는 신용카드 연체중인 고객-재외국민, 외국인, 해외체류자',
      'age': '없음',
      'incm': '_',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '1566-2566',
      'grnInst': '근로복지공단',
      'jnMthd': '영업점, 인터넷뱅킹, i-ONE뱅크',
      'rpymdCfe': '없음',
      'lnIcdcst': '▶ 신용보증료: 대출실행시 보증료를 차감한 후 고객이 요청한 당행 본인명의 예금계좌에 입금   ▶ 보증료: 근로자생활안정자금 연 0.9%, 그 외 연 1.00%',
      'ovItrYr': '여신이자율에 연체가산금리 연 3%를 더하여 적용. 단, 최고지연배상금률은 연 11%',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '대출종류별 확정금리 적용 (단, 공단이 별도로 정하여 통보하는 경우 그에 따른다)- 근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 연 1.5%- 요양급여비 : 거치기간 연 0.6%, 상환기간 연 2.6%- 직업훈련생계비 : 연 1.0%- 재직근로자의 대학학자금 : 거치기간 연 1.0%, 상환기간 연 3.0%',
      'hdlInst': '기업은행',
      'cnpl': '1566-2566',
      'rltSite': 'https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp?lncd=02&grcd=21&tmcd=209&pdcd=0001&wvcd=&i_trns_biz_kncd=',
      'tgtFltr': '근로자',
      'hdlInstDtlVw': '기업은행',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '6',
      'finPrdNm': 'IBK청년전·월세대출 (전세)',
      'lnLmt': '20000만원',
      'irtCtg': '고정금리, 변동금리',
      'irt': '3.8~4.3%',
      'maxTotLnTrm': '3년',
      'maxDfrmTrm': '3년',
      'maxRdptTrm': '0년',
      'rdptMthd': '만기일시상환',
      'usge': '주거',
      'trgt': '근로자, 사업자, 청년',
      'instCtg': '시중은행',
      'ofrInstNm': 'IBK기업은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.',
      'age': '34세 이하',
      'incm': '본인과 배우자의 합산 소득이 7천만원 이하인 자',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '1566-2566',
      'grnInst': '한국주택금융공사',
      'jnMthd': '영업점 방문',
      'rpymdCfe': '없음',
      'lnIcdcst': '5,000만원 초과 ~ 1억원 이하 인지세 70,000원 (고객부담 35,000원)1억원 초과 ~ 10억원 이하 인지세 150,000원 (고객부담 75,000원)',
      'ovItrYr': '대출이자율+연체가산금리 연 3% (최고 연체이자율 : 가계 및 중소기업의 경우 연 11%, 그 외 13%)',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '- 근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 연 1.5%',
      'hdlInst': '기업은행',
      'cnpl': '1566-2566',
      'rltSite': 'https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp',
      'tgtFltr': '근로자, 사업자, 청년',
      'hdlInstDtlVw': '기업은행',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '7',
      'finPrdNm': 'IBK청년전·월세대출 (월세)',
      'lnLmt': '1200만원',
      'irtCtg': '변동금리',
      'irt': '4.34%',
      'maxTotLnTrm': '11, 13년',
      'maxDfrmTrm': '8년',
      'maxRdptTrm': '3, 5년',
      'rdptMthd': '원금균등분할상환',
      'usge': '주거',
      'trgt': '근로자, 사업자, 청년',
      'instCtg': '시중은행',
      'ofrInstNm': 'IBK기업은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.',
      'age': '34세 이하',
      'incm': '본인과 배우자의 합산 소득이 7천만원 이하인 자',
      'rsdArea': '-',
      'crdtSc': '-',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '1566-2566',
      'grnInst': '한국주택금융공사',
      'jnMthd': '영업점 방문',
      'rpymdCfe': '없음',
      'lnIcdcst': '5,000만원 초과 ~ 1억원 이하 인지세 70,000원 (고객부담 35,000원)1억원 초과 ~ 10억원 이하 인지세 150,000원 (고객부담 75,000원)',
      'ovItrYr': '대출이자율+연체가산금리 연 3% (최고 연체이자율 : 가계 및 중소기업의 경우 연 11%, 그 외 13%)',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '- 요양급여비 : 거치기간 연 0.6%, 상환기간 연 2.6%',
      'hdlInst': '기업은행',
      'cnpl': '1566-2566',
      'rltSite': 'https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp',
      'tgtFltr': '근로자, 사업자, 청년',
      'hdlInstDtlVw': '기업은행',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '8',
      'finPrdNm': '사잇돌Ⅱ대출_표준',
      'lnLmt': '3000만원',
      'irtCtg': '변동금리',
      'irt': '~19.99%',
      'maxTotLnTrm': '5(최대 60개월, 보증기간 이내)',
      'maxDfrmTrm': '0년',
      'maxRdptTrm': '5년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자, 사업자, 연금소득자',
      'instCtg': '민간기업',
      'ofrInstNm': 'SGI서울보증',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)',
      'age': '없음',
      'incm': '(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
      'grnInst': 'SGI서울보증보험',
      'jnMthd': '취급 금융기관 방문, 서금원 맞춤대출 조회',
      'rpymdCfe': '없음',
      'lnIcdcst': '-',
      'ovItrYr': '-',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '- 직업훈련생계비 : 연 1.0%',
      'hdlInst': '저축은행',
      'cnpl': '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
      'rltSite': 'https://www.fsb.or.kr/finloanconn_0100.act',
      'tgtFltr': '근로자, 사업자, 연금소득자',
      'hdlInstDtlVw': '취급 저축은행(신한, 하나, KB, SBI, NH, 키움예스, 웰컴, 다올, 키움, BNK, 우리금융, 예가람, 융창)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '9',
      'finPrdNm': '사잇돌Ⅱ대출_대환형',
      'lnLmt': '2000만원',
      'irtCtg': '변동금리',
      'irt': '~19.99%',
      'maxTotLnTrm': '5(최대 60개월, 보증기간 이내)',
      'maxDfrmTrm': '0년',
      'maxRdptTrm': '5년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자, 사업자, 연금소득자',
      'instCtg': '민간기업',
      'ofrInstNm': 'SGI서울보증',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)',
      'age': '없음',
      'incm': '(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
      'grnInst': 'SGI서울보증보험',
      'jnMthd': '취급 금융기관 방문, 서금원 맞춤대출 조회',
      'rpymdCfe': '없음',
      'lnIcdcst': '-',
      'ovItrYr': '-',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '- 재직근로자의 대학학자금 : 거치기간 연 1.0%, 상환기간 연 3.0%',
      'hdlInst': '저축은행',
      'cnpl': '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
      'rltSite': 'https://www.fsb.or.kr/finloanconn_0300.act',
      'tgtFltr': '근로자, 사업자, 연금소득자',
      'hdlInstDtlVw': '취급 저축은행(신한, 하나, KB, SBI, NH, 키움예스, 웰컴, 다올, 키움, BNK, 우리금융, 예가람, 융창)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '10',
      'finPrdNm': '사잇돌Ⅱ대출_채무조정졸업자',
      'lnLmt': '1000만원',
      'irtCtg': '변동금리',
      'irt': '~19.99%',
      'maxTotLnTrm': '5(최대 60개월, 보증기간 이내)',
      'maxDfrmTrm': '0년',
      'maxRdptTrm': '5년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '채무조정자',
      'instCtg': '민간기업',
      'ofrInstNm': 'SGI서울보증',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '- 소득수준 : 다음의 어느 하나에 해당하는 소득이 있는 자 - (근로소득)보증 신청일 현재 5개월 이상(유지) 재직자로서 연 소득이 12백만원 이상인 자 - (사업소득)보증 신청일 현재 4개월 이상(유지) 사업소득 발생자로서 연 소득이 6백만원 이상인 자 - (연금소득) 보증 신청일 현재 연금(국민연금, 공무원연금, 군인연금, 사학연금) 소득 1회 이상 수령자로서 연금 소득이 연 6백만원 이상인 자 -  기타조건 - 채무조정제도(개인워크아웃, 프리워크아웃, 개인회생)를 졸업한지 3년 이내인 자- 보험 청약일 현재 사잇돌 1, 2 대출’을 보유하고 있지 않은 자- 한국신용정보원을 통하여 확인되는 대부업체 대출보유건수가 1건 이내인 자',
      'age': '없음',
      'incm': '(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '033-370-2627',
      'grnInst': 'SGI서울보증보험',
      'jnMthd': '취급 금융기관 방문, 서금원 맞춤대출 조회',
      'rpymdCfe': '없음',
      'lnIcdcst': '-',
      'ovItrYr': '-',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '-',
      'hdlInst': '저축은행',
      'cnpl': '033-370-2627',
      'rltSite': 'https://www.fsb.or.kr/finloanconn_0400.act',
      'tgtFltr': '채무조정자',
      'hdlInstDtlVw': '취급저축은행',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '기관 문의',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '11',
      'finPrdNm': '생업자금융자',
      'lnLmt': '5000만원',
      'irtCtg': '고정금리',
      'irt': '3%',
      'maxTotLnTrm': '10년',
      'maxDfrmTrm': '5년',
      'maxRdptTrm': '5년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '창업, 운영',
      'trgt': '금융취약계층',
      'instCtg': '지자체',
      'ofrInstNm': '강원도 삼척시',
      'rsdAreaPamtEqltIstm': '강원',
      'suprTgtDtlCond': '국민기초생활보장법상의 수급자 저소득층(실제소득이 최저생계비의 150% 이하인 자)',
      'age': '없음',
      'incm': '최저생계비의 150%이하인 자',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '033-570-3312',
      'grnInst': '-',
      'jnMthd': '삼척시 읍·면·동 주민센터 또는 시청 사업과 방문',
      'rpymdCfe': '-',
      'lnIcdcst': '-',
      'ovItrYr': '-',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '대출한도- 무보증대출 (가구당 1,200만원 이하)- 보증대출 (가구당 2,000만원 이하)- 담보대출 (담보범위내 5,000만원 한도)* 무보증대출요건기존에 금융채무불이행자가 아니고 기존 대출금이 2천만원 이하인 자 중, 연간 재산세 납세실적이 2만원 이상인 자 또는 연간소득이 600만원 이상인 자(다만, 금융기관 대출 및 현금서비스 잔액이 2천만원 이하인 자)* 보증인 요건연간 재산세 납세실적이 2만원 이상인 자 또는 연간소득이 800만원 이상인 자 중 1명 (1,000만원 초과인 경우 보증인 1명 추가)',
      'hdlInst': '강원도 삼척시청',
      'cnpl': '033-570-3312',
      'rltSite': 'http://www.samcheok.go.kr/specialty/00464/01020.web',
      'tgtFltr': '금융취약계층',
      'hdlInstDtlVw': None,
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '기관 문의',
      'prdCtg2': '-',
      'fileWrtDt': '202506010700'},
     {'basYm': '202505',
      'snq': '12',
      'finPrdNm': '저소득주민 융자사업(주택매입 및 전세임대자금 지원사업)',
      'lnLmt': '3000만원',
      'irtCtg': '무이자',
      'irt': '0%',
      'maxTotLnTrm': '3년',
      'maxDfrmTrm': '3년',
      'maxRdptTrm': '0년',
      'rdptMthd': '만기일시상환',
      'usge': '주거',
      'trgt': '저소득가구 및 무주택세대주',
      'instCtg': '지자체',
      'ofrInstNm': '강원도 영월군',
      'rsdAreaPamtEqltIstm': '강원',
      'suprTgtDtlCond': '가. 소득기준 : 기초생활수급자·차상위계층 복지증명서 발급자- 국민기초생활수급자 증명서(생계/의료/주거/교육급여)- 차상위계층 증명서(차상위 자활근로 참가자, 차상위 본인부담 경감자, 차상위 장애수당 수급자, 차상위 장애인연금 부가급여 수급자, 차상위 한부모가족 보호대상자)   ※ 발급자 명의는 신청자 기준으로 발급나. 거주기준 : 주민등록상 영월군에 6개월 이상 계속 거주 중인 무주택세대주- 공고일 기준 세대주 및 세대원 모두 6개월 이상 무주택자에 한함- 만 35세 미만 단독세대주 제외',
      'age': '없음',
      'incm': '기초생활수급자 및 차상위계층 복지증명서 발급자',
      'rsdArea': '-',
      'crdtSc': '없음',

In [58]:
result={}
for tag in response['response']['body']['items']['item']:
    for key, value in tag.items():
        result.setdefault(key, []).append(value)
result

{'basYm': ['202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505',
  '202505'],
 'snq': ['1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '39',
  '40',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
  '49',
  '50',
  '51',
  '52',
  '53',
  '54',
  '55',
  '56',
  '57',
  '58',
  '59',
  '60',
  '61',
  '62',
  '63',
  '64',
  '65',
  '66',
  '67',
  '68',
  '69',
  '70',
  '71',
  '72',
  '73',
  '74',
  '75',
  '76',
  '77',
  '78',
  '79',
  '80',
  '81',
  '82',
  '83',
  '84',
  '85',
  '86',
  '87',
  '88',
  '89',
  '90',
  '91',
  '92',
  '93',
  '94',
  '95',
  '96',
  '97',
  '98',
  '99',
  '100',
  '101'],
 'finPrdNm': ['새희망홀씨Ⅱ',
  '징검다리론',
  '우리지역 氣-Up 서포트론(영세 소기업,소상공인)',
  '경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업)',
  'i-ONE근로자생활안정자금대출',
  'IBK청년전·월세대출 (전세)',
  'IBK청년전·월세대출 (월세)',
  '사잇돌Ⅱ대출_표준',
  '사잇돌Ⅱ대출_대환형',
  '사잇돌Ⅱ대출_채무조정졸업자',
  '생업자금융자',
  '저소득주민 융자사업(주택매입 및 전세임대자금 지원사업)',
  '자활기금 대여사업',
  '강원도형 사회적경제기업 특례보증',
  '일반상환 학자금대출 특별상환유예',
  '저소득주민 생활안정융자금 대출 (학자금)',
  '경기도 중소기업 육성자금(운전_일반기업)',
  '경기도 중소기업 육성자금(운전_신기술기업)',
  '경기도 중소기업 육성자금(운전_벤처창업기업)',
  '경기도 중소기업 육성자금(운전_여성창업기업)',
  '경기도 중소기업 육성자금(소상공인 지원_점포임차자금, 경영개선, (재)창업 등)',
  '개인택시 운송사업면허 양수비용지원 특례보증',
  '북한이탈주민 특별보증',
  '전통시장 특례보증',
  '한국은행 경기본부 중소기업 지원자금 연계보증',
  '지역상권 활성화를 위한 특별출연 협약보증',
  '콘텐츠기업 지원 특례보증',
  '경기도 중소기업 육성자금(특별경영자금_재도전 희망특례)',
  '생활안정자금',
  '2024 금융기관 특별출연 협약보증',
  '전세입주보증금',
  '경상남도 중소기업 육성자금 지원(경영안정자금)',
  '경상남도 중소기업 육성자금 지원(시설설비자금)',
  '금융기관 협약보증',
  '2024 남구 소상공인 특례보증',
  '2024 서구 영세 소상공인 특례보증',
  '노후긴급자금대부',
  '햇살론15',
  '국민행복기금 소액대출',
  '생활안정자금 융자(혼례비)',
  '생활안정자금 융자(자녀학자금)',
  '생활안정자금 융자(의료비)',
  '생활안정자금 융자(부모요양비)',
  '생활안정자금 융자(장례비)',
  '생활안정자금 융자(소액생계비)',
  '직업훈련생계비 융자(직업훈련생계비)',
  '산재근로자 생활안정자금 융자(의료비)',
  '산재근로자 생활안정자금 융자(혼례비)',
  '산재근로자 생활안정자금 융자(장례비)',
  '산재근로자 생활안정자금 융자(차량구입비)',
  '산재근로자 생활안정자금 융자(취업안정자금)',
  '대전광역시 중소기업 경영안정자금 우대보증',
  '근로자햇살론 생계자금',
  '햇살론유스',
  '햇살론뱅크',
  '햇살론카드',
  '미소금융 사업수행기관 창업·운영자금_창업자금',
  '미소금융 창업자금_생계형차량 구입자금',
  '미소금융 사업수행기관 창업·운영자금_운영자금',
  '미소금융 창업자금_창업초기 시설자금',
  '미소금융 운영자금',
  '미소금융 사업수행기관 창업·운영자금_시설개선자금',
  '미소금융 사업수행기관 창업·운영자금_긴급생계자금',
  '미소금융 취업성공대출',
  '미소금융 교육비지원대출',
  '미소금융 취약계층자립자금',
  '미소금융 취약계층교육비지원대출',
  '미소금융 재기자금123_운영자금',
  '미소금융 창업자금_무등록사업자',
  '미소금융 운영자금_무등록사업자',
  '전통시장 소액대출',
  '민간사업수행기관 창업·운영자금_창업자금',
  '민간사업수행기관 창업·운영자금_사회적기업지원',
  '민간사업수행기관 창업·운영자금_생활안정자금',
  '서울시 중소기업 육성자금 지원(운전_긴급자영업자금)',
  '서울시 중소기업 육성자금 지원(운전_재해중소기업자금)',
  '서울시 중소기업 육성자금 지원(운전_경제활성화자금)',
  '서울시 중소기업 육성자금 지원(운전_창업기업자금)',
  '서울시 중소기업 육성자금 지원(운전_일자리창출우수기업자금)',
  '창업자금 특별보증',
  '사업장 임차자금 특별보증',
  '스마트 혁신성장 소상공인 지원 특례보증',
  '희망사다리론',
  '희망사다리론_학자금',
  '사회복지론',
  '새출발 마중물론',
  '신용카드 사랑가득론',
  '새희망 힐링론',
  '개인회생론',
  '제주특별자치도 혼디론',
  '강원도 재기성공자금',
  '대구광역시 울타리론',
  '경기도 재도전론',
  '대전광역시 드림론',
  '부산광역시 부비론',
  '경상북도 낙동강론',
  'LH공사 행복론',
  '광주광역시 빛고을론',
  '인천광역시 어진론',
  '서울특별시 한강론'],
 'lnLmt': ['3500만원',
  '3000만원',
  '5,00010,000 (코로나 19 피해 소기업, 소상공인)',
  '9000만원',
  '1000만원',
  '20000만원',
  '1200만원',
  '3000만원',
  '2000만원',
  '1000만원',
  '5000만원',
  '3000만원',
  '3000만원',
  '40000만원',
  '-',
  '500만원',
  '50000만원',
  '50000만원',
  '50000만원',
  '50000만원',
  '15000만원',
  '8000만원',
  '5000만원',
  '2000만원',
  '10,000 (소상공인)80,000 (중소기업)',
  '5000만원',
  '50000만원',
  '10000만원',
  '1200만원',
  '10000만원',
  '2000만원',
  '100000만원',
  '200000만원',
  '20000만원',
  '2000만원',
  '2000만원',
  '최대 1,000만원(연간 연금수령액 2배 이내 실소요비용)',
  '2000만원',
  '2000만원',
  '1250만원',
  '1000만원',
  '1000만원',
  '1000만원',
  '1000만원',
  '200만원',
  '1000만원',
  '1000만원',
  '1000만원',
  '1000만원',
  '1500만원',
  '1000만원',
  '20000만원',
  '2000만원',
  '1200만원',
  '2500만원',
  '보증한도(월 최대 300, 최초 200內, 한도증액 시 300內)',
  '7000만원',
  '2000만원',
  '2000만원',
  '2000만원',
  '2000만원',
  '2000만원',
  '1000만원',
  '300만원',
  '500만원',
  '1200만원',
  '500만원',
  '500만원',
  '500만원',
  '500만원',
  '1000만원',
  '7000만원',
  '10000만원',
  '1000만원',
  '5000만원',
  '20000만원',
  '50000만원',
  '10000만원',
  '50000만원',
  '7000만원',
  '5000만원',
  '보증한도 산정방법에 따라 상이',
  '1500만원',
  '1000만원',
  '1500만원',
  '1500만원',
  '1500만원',
  '500만원',
  '700만원',
  '1500만원',
  '1500만원',
  '1500만원',
  '1500만원',
  '1000만원',
  '1500만원',
  '1500만원',
  '1500만원',
  '1500만원',
  '1500만원',
  '1500만원'],
 'irtCtg': ['변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '고정금리',
  '고정금리, 변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '고정금리',
  '무이자',
  '고정금리',
  '-',
  '무이자',
  '무이자',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '무이자',
  '변동금리',
  '-',
  '-',
  '-',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리(분기별)',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '-',
  '변동금리',
  '고정금리',
  '은행별 자욜(24년 상반기 기준 약 8.7% 내외)',
  '-',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '고정금리',
  '고정금리',
  '변동금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '협약금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리',
  '고정금리'],
 'irt': ['은행별 상이',
  '은행별 상이',
  '6.27~8.97%',
  '은행별 상이',
  '1.5 / 2.6 / 1.0 / 3.0',
  '3.8~4.3%',
  '4.34%',
  '~19.99%',
  '~19.99%',
  '~19.99%',
  '3%',
  '0%',
  '1%',
  '-',
  '무이자',
  '무이자',
  '은행별 상이',
  '은행별 상이',
  '은행별 상이',
  '은행별 상이',
  '은행별 상이',
  '은행금리-1.5',
  '은행별 상이',
  '은행별 상이',
  '은행별 상이',
  '은행별 상이',
  '은행별 상이',
  '은행별 상이',
  '0%',
  '은행별 상이',
  '-',
  '-',
  '-',
  '은행별 상이',
  '은행별 상이',
  '-',
  '5년 만기 국고채권 수익률과 예금은행 가중평균 수신금리(신규취급액 기준) 중 낮은 금리를 적용',
  '15.9%',
  '3.0~4.0%',
  '1.5%',
  '1.5%',
  '1.5%',
  '1.5%',
  '1.5%',
  '1.5%',
  '1%',
  '1.25%',
  '1.25%',
  '1.25%',
  '1.25%',
  '1.25%',
  '은행협약금리',
  '~11.5%',
  '3.5%',
  '은행별 상이',
  '-',
  '4.5%',
  '4.5%',
  '4.5%',
  '4.5%',
  '4.5%',
  '4.5%',
  '4.5%',
  '4.5%',
  '4.5%',
  '3%',
  '3%',
  '4.5%',
  '2%',
  '2%',
  '0~4.5%',
  '6%',
  '6%',
  '6%',
  '3%',
  '2%',
  '-',
  '-',
  '-',
  '-',
  '-',
  '은행별 상이',
  '3.0~4.0%',
  '2%',
  '2.0~4.0%',
  '2.0~4.0%',
  '2.0~4.0%',
  '3%',
  '2.0~4.0%',
  '1%',
  '2~3.5%',
  '2.0~4.0%',
  '1~2.5%',
  '2.0~4.0%',
  '2.0~4.0%',
  '2.0~4.0%',
  '2.0~4.0%',
  '2.0~ 3.5%',
  '2.0~3.5%',
  '2~3%'],
 'maxTotLnTrm': ['은행별 상이',
  '5년',
  '5년',
  '임대차계약기간 이내 최대 2년',
  '근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년, 8년요양급여비 : 5년직업훈련생계비 : 4년, 6년, 8년재직근로자의 대학학자금 : 7년, 8년, 9년, 10년, 11년',
  '3년',
  '11, 13년',
  '5(최대 60개월, 보증기간 이내)',
  '5(최대 60개월, 보증기간 이내)',
  '5(최대 60개월, 보증기간 이내)',
  '10년',
  '3년',
  '5년',
  '1~5',
  '7년',
  '8년',
  '3년',
  '3년',
  '3년',
  '3년',
  '5년',
  '8년',
  '5년',
  '5년',
  '1년',
  '5년',
  '-',
  '5년',
  '5년',
  '5년',
  '2년',
  '2,3년',
  '5, 8, 10년',
  '5년',
  '5년',
  '5년',
  '7년',
  '3,5년',
  '5년',
  '4, 5년',
  '4, 5년',
  '4, 5년',
  '4, 5년',
  '4, 5년',
  '2년',
  '4, 6, 8년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '2년',
  '3, 5년',
  '15년',
  '3, 5년',
  '5년',
  '6년',
  '6년',
  '5.5',
  '6년',
  '5.5',
  '5.5',
  '5년',
  '3년',
  '6년',
  '6년',
  '6년',
  '6년',
  '6년',
  '5.5',
  '2.5',
  '5년',
  '5년',
  '5년',
  '5년',
  '2, 5년',
  '2, 3, 4, 5년',
  '2, 3, 4, 5년',
  '5년',
  '5년',
  '5년',
  '~5년',
  '1~5',
  '5년',
  '1~5',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년'],
 'maxDfrmTrm': ['-',
  '1년',
  '1년',
  '0년',
  '6년',
  '3년',
  '8년',
  '0년',
  '0년',
  '0년',
  '5년',
  '3년',
  '2년',
  '0년',
  '3년',
  '4년',
  '1년',
  '1년',
  '1년',
  '1년',
  '1년',
  '-',
  '1년',
  '-',
  '1년',
  '-',
  '-',
  '2년',
  '2년',
  '1년',
  '0년',
  '2년',
  '2, 3, 4년',
  '1년',
  '1년',
  '1년',
  '2년',
  '0년',
  '0년',
  '1년',
  '1년',
  '1년',
  '1년',
  '1년',
  '1년',
  '1, 2, 3년',
  '1, 2, 3년',
  '1, 2, 3년',
  '1, 2, 3년',
  '1, 2, 3년',
  '1, 2, 3년',
  '-',
  '-',
  '8년',
  '1(대출기간 내 선택 가능)',
  '-',
  '1년',
  '1년',
  '0.5',
  '1년',
  '0.5',
  '0.5',
  '1년',
  '0년',
  '1년',
  '1년',
  '1년',
  '1년',
  '1년',
  '0.5',
  '0.5',
  '0.5',
  '0.25',
  '0.5',
  '1년',
  '1년',
  '1, 2년',
  '1, 2년',
  '1, 2년',
  '-',
  '-',
  '5년',
  '0년',
  '0년',
  '0년',
  '0년',
  '0년',
  '2년',
  '0년',
  '0년',
  '0년',
  '0년',
  '0년',
  '0년',
  '0년',
  '0년',
  '0년',
  '0년',
  '0년',
  '0년'],
 'maxRdptTrm': ['-',
  '4년',
  '4년',
  '0년',
  '5년',
  '0년',
  '3, 5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '0년',
  '3년',
  '1~5',
  '4년',
  '4년',
  '2년',
  '2년',
  '2년',
  '2년',
  '4년',
  '-',
  '4년',
  '-',
  '0년',
  '-',
  '-',
  '3년',
  '3년',
  '4년',
  '0년',
  '2,1년',
  '3,5,6년',
  '4년',
  '4년',
  '4년',
  '5년',
  '3,5년',
  '5년',
  '3, 4년',
  '3, 4년',
  '3, 4년',
  '3, 4년',
  '3, 4년',
  '1년',
  '3, 4, 5년',
  '4, 3, 2년',
  '4, 3, 2년',
  '4, 3, 2년',
  '4, 3, 2년',
  '4, 3, 2년',
  '-',
  '-',
  '7년',
  '3,5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '4년',
  '3년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '2년',
  '4.5',
  '4.75',
  '4.5',
  '4년',
  '4년',
  '2, 3, 4년',
  '2, 3, 4년',
  '3,4년',
  '-',
  '-',
  '0년',
  '1~5',
  '5년',
  '1~5',
  '5년',
  '5년',
  '3년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년',
  '5년'],
 'rdptMthd': ['원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원금균등분할상환',
  '일시상환',
  '원(리)금균등분할상환',
  '만기일시상환',
  '원금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '만기일시상환',
  '분할상환, 만기일시상환',
  '일시상환(최대5년까지 1년단위 기한연장가능) 또는 분할상환',
  '한국장학재단 일반 상환 학자금대출의 원리금 상환을 최대 3년 간 상환유예하고, 해당 금액을 최대 4년간 무이자 분할상환 또는 4년 후 만기 일시 상환',
  '균등분할상환',
  '균등분할상환',
  '균등분할상환',
  '균등분할상환',
  '균등분할상환',
  '분할상환',
  '-',
  '-',
  '-',
  '만기일시상환',
  '-',
  '-',
  '분할상환',
  '원(리)금균등분할상환',
  '균등분할상환, 만기일시상환',
  '일시상환(1회에 한해 2년 연장 가능)',
  '일시상환, 균등분할상환',
  '균등분할상환',
  '일시상환, 분할상환',
  '균등분할상환, 만기일시상환',
  '분할상환',
  '원금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원금균등분할상환',
  '원금균등분할상환',
  '원금균등분할상환',
  '원금균등분할상환',
  '원금균등분할상환',
  '원금균등분할상환',
  '원금균등분할상환',
  '균등분할상환',
  '균등분할상환',
  '균등분할상환',
  '균등분할상환',
  '균등분할상환',
  '-',
  '원금균등분할상환',
  '원금균등분할상환',
  '원리금균등분할상환',
  '매월 이용대금 납부',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '일/월 원(리)금분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '균등분할상환',
  '균등분할상환, 일시상환',
  '균등분할상환, 만기일시상환(2년)',
  '균등분할상환, 만기일시상환(2년)',
  '균등분할상환',
  '-',
  '-',
  '- 일시상환(1년, 최대 5년까지 1년 단위 기한연장 가능)- 분할상환(5년, 1년 거치 4년 분할상환, 월단위 원금균등분할상환)',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환',
  '원리금균등분할상환'],
 'usge': ['생계',
  '생계',
  '운영·시설',
  '주거',
  '생계',
  '주거',
  '주거',
  '생계',
  '생계',
  '생계',
  '창업, 운영',
  '주거',
  '주거, 창업',
  '운전',
  '학자금',
  '학자금',
  '운전',
  '운전',
  '운전',
  '운전',
  '운영·시설',
  '운영·시설',
  '운영·시설',
  '운영·시설',
  '운영·시설',
  '운영·시설',
  '운영·시설',
  '운전',
  '생계, 운영',
  '운영·시설',
  '주거',
  '운영·시설',
  '시설',
  '운영·시설',
  '운영·시설',
  '운영·시설',
  '의료비, 배우자장제비, 전월세보증금, 재해복구비',
  '생계',
  '생계',
  '생계',
  '학자금',
  '생계',
  '생계',
  '생계',
  '생계',
  '생계',
  '생계',
  '생계',
  '생계',
  '생계',
  '생계',
  '운영·시설',
  '생계',
  '생계',
  '생계',
  '생계',
  '창업',
  '생계',
  '창업',
  '창업',
  '운영·시설',
  '운영·시설',
  '생계',
  '생계',
  '생계',
  '생계',
  '생계',
  '생계',
  '창업',
  '운영·시설',
  '운영·시설',
  '창업, 운영·시설',
  '운영·시설',
  '생계',
  '운영',
  '운영',
  '운영·시설',
  '창업, 운영, 시설',
  '운영·시설',
  '운영·시설',
  '운영·시설',
  '운전자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환',
  '운영·시설, 생계, 저금리전환, 학자금',
  '생계. 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '생계, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금',
  '운영·시설, 생계, 저금리전환, 학자금'],
 'trgt': ['근로자',
  '근로자, 대학생·청년, 채무조정자, 금융취약계층',
  '소기업, 소상공인',
  '근로자, 사업자, 청년',
  '근로자',
  '근로자, 사업자, 청년',
  '근로자, 사업자, 청년',
  '근로자, 사업자, 연금소득자',
  '근로자, 사업자, 연금소득자',
  '채무조정자',
  '금융취약계층',
  '저소득가구 및 무주택세대주',
  '금융취약계층',
  '소상공인',
  '대학생·청년',
  '금융취약계층',
  '중소기업',
  '중소기업',
  '중소기업',
  '여성기업',
  '사업자, 소상공인',
  '사업자, 소상공인',
  '기타',
  '사업자, 소상공인',
  '사업자, 소상공인',
  '민간기업',
  '사업자, 소상공인',
  '사업자, 소상공인',
  '금융취약계층',
  '사업자, 소상공인',
  '금융취약계층',
  '중소기업',
  '중소기업',
  '소기업, 소상공인',
  '사업자, 소상공인',
  '사업자, 소상공인',
  '만60세 이상 국민연금수급자 (노령,분할,유족,장애1~3급 수급자',
  '근로자, 사업자, 연금소득자 등',
  '채무조정 성실상환자',
  '근로자',
  '근로자',
  '근로자',
  '근로자',
  '근로자',
  '근로자',
  '근로자',
  '산재근로자',
  '산재근로자 및 유족급여수급권자',
  '산재근로자 및 유족급여수급권자',
  '산재근로자 및 유족급여수급권자',
  '산재근로자',
  '중소기업',
  '근로자',
  '대학(원)생, 미취업청년, 사회초년생, 국민취업지원제도 성공 사회초년생',
  '저신용·저소득자',
  '근로자, 사업자, 연금소득자 등',
  '사업자, 금융취약계층',
  '사업자, 금융취약계층',
  '사업자, 금융취약계층',
  '사업자, 금융취약계층',
  '사업자, 금융취약계층',
  '사업자, 금융취약계층',
  '금융취약계층',
  '금융취약계층',
  '금융취약계층',
  '금융취약계층',
  '금융취약계층',
  '사업자, 금융취약계층',
  '사업자, 금융취약계층',
  '사업자, 금융취약계층',
  '소상공인',
  '사업자, 금융취약계층',
  '사회적기업',
  '자영업자, 근로자',
  '중소기업 및 소상공인',
  '중소기업 및 소상공인',
  '사업자, 소상공인',
  '사업자, 소상공인',
  '사업자, 소상공인',
  '사업자, 소상공인',
  '사업자, 소상공인',
  '소기업, 소상공인',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '기타',
  '개인회생인가자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자',
  '채무조정자'],
 'instCtg': ['시중은행',
  '시중은행',
  '시중은행',
  '시중은행',
  '시중은행',
  '시중은행',
  '시중은행',
  '민간기업',
  '민간기업',
  '민간기업',
  '지자체',
  '지자체',
  '지자체',
  '재단법인',
  '준정부기관',
  '지자체',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '지자체',
  '재단법인',
  '지자체',
  '공공기관',
  '공공기관',
  '재단법인',
  '재단법인',
  '재단법인',
  '공공기관',
  '공공기관',
  '기금',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '재단법인',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '공공기관',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '재단법인',
  '공공기관',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인',
  '사단법인'],
 'ofrInstNm': ['14개 취급은행',
  '15개 취급은행',
  'BNK경남은행',
  'BNK경남은행',
  'IBK기업은행',
  'IBK기업은행',
  'IBK기업은행',
  'SGI서울보증',
  'SGI서울보증',
  'SGI서울보증',
  '강원도 삼척시',
  '강원도 영월군',
  '강원도 춘천시',
  '강원신용보증재단',
  '한국장학재단',
  '경기도 고양시',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경기신용보증재단',
  '경상북도 김천시',
  '경북신용보증재단',
  '경상북도 김천시',
  '경남투자경제진흥원',
  '경남투자경제진흥원',
  '광주신용보증재단',
  '광주신용보증재단',
  '광주신용보증재단',
  '국민연금공단',
  '서민금융진흥원',
  '국민행복기금',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '근로복지공단',
  '대전신용보증재단',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서민금융진흥원',
  '서울신용보증재단',
  '서울신용보증재단',
  '서울신용보증재단',
  '서울신용보증재단',
  '서울신용보증재단',
  '서울신용보증재단',
  '서울신용보증재단',
  '신용보증재단중앙회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회',
  '신용회복위원회'],
 'rsdAreaPamtEqltIstm': ['전국',
  '전국',
  '경남, 울산',
  '경남',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '강원',
  '강원',
  '강원',
  '강원',
  '전국',
  '경기',
  '경기',
  '경기',
  '경기',
  '경기',
  '경기',
  '경기',
  '경기',
  '경기',
  '경기',
  '경기',
  '경기',
  '경기',
  '경북',
  '경북',
  '경북',
  '경남',
  '경남',
  '광주',
  '광주',
  '광주',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '대전',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '서울',
  '서울',
  '서울',
  '서울',
  '서울',
  '서울',
  '서울',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '제주',
  '강원',
  '대구',
  '경기',
  '대전',
  '부산',
  '경북',
  '전국',
  '광주',
  '인천',
  '서울'],
 'suprTgtDtlCond': ['연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하',
  '4대 서민금융상품(새희망홀씨, 햇살론, 미소금융, 바꿔드림론)을 성실상환한 자1) 4대 서민금융상품 중 어느 하나를 2년 이상 거래한 후 해당 대출 원금의 75% 이상을 상환한 자 또는 거래기간에 상관없이 전액상환한 자2) CB신용평점: 상위 80%',
  '신용보증신청 접수일 현재 사업자등록 후 가동(영업)중으로서 지역보증재단의 신용보증서를 발급받은 소기업ㆍ소상공인① 영세 소기업ㆍ소상공인 : CB평점구간 7구간 이상의 소기업ㆍ소상공인 등 금융소외계층② 코로나19 피해 소기업ㆍ소상공인 : CB평점구간 8구간 이상의 소기업ㆍ소상공인 중 코로나 19로 인해 피해를 입은 경우※ 보증 가능여부는 재단에서 확인 가능함.※ CB평점구간 : 재단에서 보유하고 있는 NICE CB사의 평점구간※ 금융기관 신용관리관리 대상자 등 여신 부적격자에 대하여 대출이 제한될 수 있음',
  '- 아래 요건을 모두 충족1) 경상남도에 주소를 두고 있거나, 대출신청 후 1개월 이내 전입신고 예정인 자2) 신청일 기준 만19세 이상 34세 이하인 청년3) 본인, 배우자, 자녀가 주거급여 대상자가 아니고 무주택인 자4) 다음의 어느 하나에 해당하는 경우  ① 대학(원)생, 취업준비생 등 무소득자 : 부모 합산 연소득 7천만원 이하 또는 부부합산 연소득 6천만원 이하  ② 사회초년생(한 직장에서 5년미만 근무하는 자/자영업자임을 증빙한 지역세대원) : 본인 연소득 4천5백만원 이하 또는 부부합산 연소득 6천만원 이하인 경우 5) 신청인 본인이 주거할 목적으로 경상남도에 소재한 임차보증금 1억원 이하, 전용면적 60 ㎡ 이하인 주택, 아파트, 오피스텔 등 주거용 건물에 임대차계약 체결 예정자 또는 계약체결 3개월 이내인 자',
  '근로복지공단으로부터 신용보증결정 통보를 받은 고객※대출제외대상-은행연합회 신용정보 등재된 고객-대출신청일 현재 당행 대출금 또는 신용카드 연체중인 고객-재외국민, 외국인, 해외체류자',
  '대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.',
  '대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.',
  '중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)',
  '중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)',
  '- 소득수준 : 다음의 어느 하나에 해당하는 소득이 있는 자 - (근로소득)보증 신청일 현재 5개월 이상(유지) 재직자로서 연 소득이 12백만원 이상인 자 - (사업소득)보증 신청일 현재 4개월 이상(유지) 사업소득 발생자로서 연 소득이 6백만원 이상인 자 - (연금소득) 보증 신청일 현재 연금(국민연금, 공무원연금, 군인연금, 사학연금) 소득 1회 이상 수령자로서 연금 소득이 연 6백만원 이상인 자 -  기타조건 - 채무조정제도(개인워크아웃, 프리워크아웃, 개인회생)를 졸업한지 3년 이내인 자- 보험 청약일 현재 사잇돌 1, 2 대출’을 보유하고 있지 않은 자- 한국신용정보원을 통하여 확인되는 대부업체 대출보유건수가 1건 이내인 자',
  '국민기초생활보장법상의 수급자 저소득층(실제소득이 최저생계비의 150% 이하인 자)',

In [61]:
page=1
result={}
while True:
    url="https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    servicekey="TUszyF9E+ahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9+oN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw=="
    payload=dict(serviceKey=servicekey, numOfRows=100, pageNo=page, resultType='json')
    r=requests.get(url, params=payload)
    response=r.json()
    
    for tag in response['response']['body']['items']['item']:
        for key, value in tag.items():
            result.setdefault(key, []).append(value)
            
    total_pages=int(response['response']['body']['totalCount'])//100+1
    
    if page<total_pages:
        page+=1
    else:
        break
        
    
 
            
df=pd.DataFrame(result)
df

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202505,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
1,202505,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202506010700
2,202505,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
3,202505,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
4,202505,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5434,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
5435,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
5436,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
5437,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
5438,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,None,1,대출상품,None,None,None,None,None,202502010700

# xml로 가져오기

In [19]:
xml_result_df_list=[]
page=1

while True:
    url="https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    servicekey="TUszyF9E+ahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9+oN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw=="
    payload=dict(serviceKey=servicekey, numOfRows=1000, pageNo=1, resultType='xml')
    r=requests.get(url, params=payload)
    response=r.content
    soup=bs(response, 'xml')
    xml_result={}
    for item in soup.select('item'):
        for tags in item:
            if tags.name==None:
                continue
            else:
                xml_result.setdefault(tags.name,[]).append(tags.text)
    xml_result_df_list.append(pd.DataFrame(xml_result))
    numOfRows=int(soup.select_one('numOfRows').text)
    totalCount=int(soup.select_one('totalCount').text)
    total_pages=totalCount//numOfRows+1
    if page<total_pages:
        page+=1
    else:
        break
        
xml_result_df_list=pd.concat(xml_result_df_list)
xml_result_df_list=xml_result_df_list.reset_index(drop=True)
xml_result_df_list

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202505,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
1,202505,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202506010700
2,202505,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
3,202505,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
4,202505,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,202503,299,희망전북 함께도~ 특례보증,80000만원,변동금리,~3.5%,1~5,-,-,일시상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
5996,202503,300,익산시 희망더드림 특례보증(Track1 튼튼소상공인),5000만원,변동금리,~2.68%,1~5,1년,"4, 5년",원금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
5997,202503,301,익산시 희망더드림 특례보증(Track2 탄탄소상공인),5000만원,변동금리,~1.68%,1~5,1년,"4, 5년",원금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
5998,202503,302,전주시 희망더드림 안심연장 특례보증,-,변동금리,~ 2.48%,9년,1년,8년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
5999,202503,303,전북 위기극복 특례보증,20000만원,변동금리,~ 3.07%,1~5,-,-,일시상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700

In [18]:
xml_result_df_list = []
page = 1
while True:
    url = "https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    service_key = "TUszyF9E+ahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9+oN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw=="
    payload = dict(serviceKey=service_key, numOfRows=1000, pageNo=page, resultType='xml')
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    response = r.content
    soup = bs(response, "xml")
    xml_result = {}
    for item in soup.select("item"):
        for tags in item:
            if tags.name == None:
                continue
            else:
                xml_result.setdefault(tags.name, []).append(tags.text)
    xml_result_df_list.append(pd.DataFrame(xml_result))
    numOfRows = int(soup.select_one("numOfRows").text)
    totalCount = int(soup.select_one("totalCount").text)
    total_pages = totalCount // numOfRows + 1
    if page < total_pages:
        page += 1
    else:
        break
        
xml_result_df_list = pd.concat(xml_result_df_list)
xml_result_df_list = xml_result_df_list.reset_index(drop=True)
xml_result_df_list

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=TUszyF9E%2BahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9%2BoN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw%3D%3D&numOfRows=1000&pageNo=1&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=TUszyF9E%2BahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9%2BoN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw%3D%3D&numOfRows=1000&pageNo=2&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=TUszyF9E%2BahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9%2BoN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw%3D%3D&numOfRows=1000&pageNo=3&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=TUszyF9E%2BahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9%2BoN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw%3D%3D&numOfRows=1000&pageNo=4&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=TUszyF9E%2BahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9%2BoN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw%3D%3D&numOfRows=1000&pageNo=5&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=TUszyF9E%2BahKSr7EHb1uL3WyU458jqCE99oqTvyRDyQ9%2BoN7KcVAIijXzvc8iFsJhgTjoKHuRWT2wV35QeNBZw%3D%3D&numOfRows=1000&pageNo=6&resultType=xml
200

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202505,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
1,202505,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202506010700
2,202505,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
3,202505,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
4,202505,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5434,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
5435,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
5436,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
5437,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,,,202502010700
5438,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700

In [21]:
key_list={}
for item in soup.select("*"):
    key_list.setdefault(item.name,"")
key_list=list(key_list.keys())
key_list

['response',
 'header',
 'resultCode',
 'resultMsg',
 'body',
 'numOfRows',
 'pageNo',
 'totalCount',
 'items',
 'item',
 'basYm',
 'snq',
 'finPrdNm',
 'lnLmt',
 'irtCtg',
 'irt',
 'maxTotLnTrm',
 'maxDfrmTrm',
 'maxRdptTrm',
 'rdptMthd',
 'usge',
 'trgt',
 'instCtg',
 'ofrInstNm',
 'rsdAreaPamtEqltIstm',
 'suprTgtDtlCond',
 'age',
 'incm',
 'rsdArea',
 'crdtSc',
 'anin',
 'housHoldCnt',
 'housAr',
 'lnTgtHous',
 'rfrcCnpl',
 'grnInst',
 'jnMthd',
 'rpymdCfe',
 'lnIcdcst',
 'ovItrYr',
 'prftAddIrtCond',
 'etcRefSbjc',
 'hdlInst',
 'cnpl',
 'rltSite',
 'tgtFltr',
 'hdlInstDtlVw',
 'prdExisYn',
 'cv19Rfrc',
 'prdCtg',
 'prdNm',
 'cv19SuprCtg',
 'cv19SuprCtn',
 'cv19SuprTgtDtlCtn',
 'mgmDln',
 'prdCtg2',
 'fileWrtDt']

In [22]:
keys=key_list[10:]

In [23]:
soup.select('basYm')
soup.select("snq")

[<snq>1</snq>,
 <snq>2</snq>,
 <snq>3</snq>,
 <snq>4</snq>,
 <snq>5</snq>,
 <snq>6</snq>,
 <snq>7</snq>,
 <snq>8</snq>,
 <snq>9</snq>,
 <snq>10</snq>,
 <snq>11</snq>,
 <snq>12</snq>,
 <snq>13</snq>,
 <snq>14</snq>,
 <snq>15</snq>,
 <snq>16</snq>,
 <snq>17</snq>,
 <snq>18</snq>,
 <snq>19</snq>,
 <snq>20</snq>,
 <snq>21</snq>,
 <snq>22</snq>,
 <snq>23</snq>,
 <snq>24</snq>,
 <snq>25</snq>,
 <snq>26</snq>,
 <snq>27</snq>,
 <snq>28</snq>,
 <snq>29</snq>,
 <snq>30</snq>,
 <snq>31</snq>,
 <snq>33</snq>,
 <snq>34</snq>,
 <snq>35</snq>,
 <snq>36</snq>,
 <snq>37</snq>,
 <snq>38</snq>,
 <snq>39</snq>,
 <snq>40</snq>,
 <snq>41</snq>,
 <snq>42</snq>,
 <snq>43</snq>,
 <snq>44</snq>,
 <snq>45</snq>,
 <snq>46</snq>,
 <snq>47</snq>,
 <snq>48</snq>,
 <snq>49</snq>,
 <snq>50</snq>,
 <snq>51</snq>,
 <snq>52</snq>,
 <snq>53</snq>,
 <snq>54</snq>,
 <snq>55</snq>,
 <snq>56</snq>,
 <snq>57</snq>,
 <snq>58</snq>,
 <snq>59</snq>,
 <snq>60</snq>,
 <snq>61</snq>,
 <snq>62</snq>,
 <snq>63</snq>,
 <snq>64</snq>,
 <snq>65</snq>,
 <snq>66</snq>,
 <snq>67</snq>,
 <snq>68</snq>,
 <snq>69</snq>,
 <snq>70</snq>,
 <snq>71</snq>,
 <snq>72</snq>,
 <snq>73</snq>,
 <snq>74</snq>,
 <snq>75</snq>,
 <snq>76</snq>,
 <snq>77</snq>,
 <snq>78</snq>,
 <snq>79</snq>,
 <snq>80</snq>,
 <snq>81</snq>,
 <snq>82</snq>,
 <snq>83</snq>,
 <snq>84</snq>,
 <snq>85</snq>,
 <snq>86</snq>,
 <snq>87</snq>,
 <snq>88</snq>,
 <snq>89</snq>,
 <snq>90</snq>,
 <snq>91</snq>,
 <snq>92</snq>,
 <snq>93</snq>,
 <snq>94</snq>,
 <snq>95</snq>,
 <snq>96</snq>,
 <snq>97</snq>,
 <snq>98</snq>,
 <snq>99</snq>,
 <snq>100</snq>,
 <snq>101</snq>,
 <snq>102</snq>,
 <snq>103</snq>,
 <snq>104</snq>,
 <snq>105</snq>,
 <snq>106</snq>,
 <snq>107</snq>,
 <snq>108</snq>,
 <snq>109</snq>,
 <snq>110</snq>,
 <snq>111</snq>,
 <snq>112</snq>,
 <snq>113</snq>,
 <snq>114</snq>,
 <snq>115</snq>,
 <snq>116</snq>,
 <snq>117</snq>,
 <snq>118</snq>,
 <snq>119</snq>,
 <snq>120</snq>,
 <snq>121</snq>,
 <snq>122</snq>,
 <snq>123</snq>,
 <snq>124</snq>,
 <snq>125</snq>,
 <snq>126</snq>,
 <snq>127</snq>,
 <snq>128</snq>,
 <snq>129</snq>,
 <snq>130</snq>,
 <snq>131</snq>,
 <snq>132</snq>,
 <snq>133</snq>,
 <snq>134</snq>,
 <snq>135</snq>,
 <snq>136</snq>,
 <snq>137</snq>,
 <snq>138</snq>,
 <snq>139</snq>,
 <snq>140</snq>,
 <snq>141</snq>,
 <snq>142</snq>,
 <snq>143</snq>,
 <snq>144</snq>,
 <snq>145</snq>,
 <snq>146</snq>,
 <snq>147</snq>,
 <snq>148</snq>,
 <snq>149</snq>,
 <snq>150</snq>,
 <snq>151</snq>,
 <snq>152</snq>,
 <snq>153</snq>,
 <snq>154</snq>,
 <snq>155</snq>,
 <snq>156</snq>,
 <snq>157</snq>,
 <snq>158</snq>,
 <snq>159</snq>,
 <snq>160</snq>,
 <snq>161</snq>,
 <snq>162</snq>,
 <snq>163</snq>,
 <snq>164</snq>,
 <snq>165</snq>,
 <snq>166</snq>,
 <snq>167</snq>,
 <snq>168</snq>,
 <snq>169</snq>,
 <snq>170</snq>,
 <snq>171</snq>,
 <snq>172</snq>,
 <snq>173</snq>,
 <snq>174</snq>,
 <snq>175</snq>,
 <snq>176</snq>,
 <snq>177</snq>,
 <snq>178</snq>,
 <snq>179</snq>,
 <snq>180</snq>,
 <snq>181</snq>,
 <snq>182</snq>,
 <snq>183</snq>,
 <snq>184</snq>,
 <snq>185</snq>,
 <snq>186</snq>,
 <snq>187</snq>,
 <snq>188</snq>,
 <snq>189</snq>,
 <snq>190</snq>,
 <snq>191</snq>,
 <snq>192</snq>,
 <snq>193</snq>,
 <snq>194</snq>,
 <snq>195</snq>,
 <snq>196</snq>,
 <snq>197</snq>,
 <snq>198</snq>,
 <snq>199</snq>,
 <snq>200</snq>,
 <snq>201</snq>,
 <snq>202</snq>,
 <snq>203</snq>,
 <snq>204</snq>,
 <snq>205</snq>,
 <snq>206</snq>,
 <snq>207</snq>,
 <snq>208</snq>,
 <snq>209</snq>,
 <snq>210</snq>,
 <snq>211</snq>,
 <snq>212</snq>,
 <snq>213</snq>,
 <snq>214</snq>,
 <snq>215</snq>,
 <snq>216</snq>,
 <snq>217</snq>,
 <snq>218</snq>,
 <snq>219</snq>,
 <snq>220</snq>,
 <snq>221</snq>,
 <snq>222</snq>,
 <snq>223</snq>,
 <snq>224</snq>,
 <snq>225</snq>,
 <snq>226</snq>,
 <snq>227</snq>,
 <snq>228</snq>,
 <snq>229</snq>,
 <snq>230</snq>,
 <snq>231</snq>,
 <snq>232</snq>,
 <snq>233</snq>,
 <snq>234</snq>,
 <snq>235</snq>,
 <snq>236</snq>,
 <snq>237</snq>,
 <snq>238</snq>,
 <snq>239</snq>,
 <snq>240</snq>,
 <snq>241</snq>,
 <snq>242</snq>,
 <snq>243</snq>,
 <snq>244</snq>,
 <snq>245</snq>,
 <snq>246</snq>,
 <snq>247</snq>,
 <snq>248</snq>,
 <snq>249</snq>,
 <snq>250</snq>,
 <snq>251</snq>,
 <snq>252</snq>,
 <snq>253</snq>,
 <snq>254</snq>,
 <snq>255</snq>,
 <snq>256</snq>,
 <snq>257</snq>,
 <snq>258</snq>,
 <snq>259</snq>,
 <snq>260</snq>,
 <snq>261</snq>,
 <snq>262</snq>,
 <snq>263</snq>,
 <snq>264</snq>,
 <snq>265</snq>,
 <snq>266</snq>,
 <snq>267</snq>,
 <snq>268</snq>,
 <snq>269</snq>,
 <snq>270</snq>,
 <snq>271</snq>,
 <snq>272</snq>,
 <snq>273</snq>,
 <snq>274</snq>,
 <snq>275</snq>,
 <snq>276</snq>,
 <snq>277</snq>,
 <snq>278</snq>,
 <snq>279</snq>,
 <snq>280</snq>,
 <snq>281</snq>,
 <snq>282</snq>,
 <snq>283</snq>,
 <snq>284</snq>,
 <snq>285</snq>,
 <snq>286</snq>,
 <snq>287</snq>,
 <snq>288</snq>,
 <snq>289</snq>,
 <snq>290</snq>,
 <snq>291</snq>,
 <snq>292</snq>,
 <snq>293</snq>,
 <snq>294</snq>,
 <snq>295</snq>,
 <snq>296</snq>,
 <snq>297</snq>,
 <snq>298</snq>,
 <snq>299</snq>,
 <snq>300</snq>,
 <snq>301</snq>,
 <snq>302</snq>,
 <snq>303</snq>,
 <snq>304</snq>,
 <snq>305</snq>,
 <snq>306</snq>,
 <snq>307</snq>,
 <snq>308</snq>,
 <snq>309</snq>,
 <snq>310</snq>,
 <snq>311</snq>,
 <snq>312</snq>,
 <snq>313</snq>,
 <snq>314</snq>,
 <snq>315</snq>,
 <snq>316</snq>,
 <snq>317</snq>,
 <snq>318</snq>,
 <snq>319</snq>,
 <snq>320</snq>,
 <snq>321</snq>,
 <snq>322</snq>,
 <snq>323</snq>,
 <snq>324</snq>,
 <snq>325</snq>,
 <snq>326</snq>,
 <snq>327</snq>,
 <snq>328</snq>,
 <snq>329</snq>,
 <snq>330</snq>,
 <snq>331</snq>,
 <snq>332</snq>,
 <snq>333</snq>,
 <snq>334</snq>,
 <snq>335</snq>,
 <snq>336</snq>,
 <snq>337</snq>,
 <snq>338</snq>,
 <snq>339</snq>,
 <snq>340</snq>,
 <snq>341</snq>,
 <snq>342</snq>,
 <snq>343</snq>,
 <snq>344</snq>,
 <snq>345</snq>,
 <snq>346</snq>,
 <snq>347</snq>,
 <snq>348</snq>,
 <snq>349</snq>,
 <snq>350</snq>,
 <snq>1</snq>,
 <snq>2</snq>,
 <snq>3</snq>,
 <snq>4</snq>,
 <snq>5</snq>,
 <snq>6</snq>,
 <snq>7</snq>,
 <snq>8</snq>,
 <snq>9</snq>,
 <snq>10</snq>,
 <snq>11</snq>,
 <snq>12</snq>,
 <snq>13</snq>,
 <snq>14</snq>,
 <snq>15</snq>,
 <snq>16</snq>,
 <snq>17</snq>,
 <snq>18</snq>,
 <snq>19</snq>,
 <snq>20</snq>,
 <snq>21</snq>,
 <snq>22</snq>,
 <snq>23</snq>,
 <snq>24</snq>,
 <snq>25</snq>,
 <snq>26</snq>,
 <snq>27</snq>,
 <snq>28</snq>,
 <snq>29</snq>,
 <snq>30</snq>,
 <snq>31</snq>,
 <snq>33</snq>,
 <snq>34</snq>,
 <snq>35</snq>,
 <snq>36</snq>,
 <snq>37</snq>,
 <snq>38</snq>,
 <snq>39</snq>,
 <snq>40</snq>,
 <snq>41</snq>,
 <snq>42</snq>,
 <snq>43</snq>,
 <snq>44</snq>,
 <snq>45</snq>,
 <snq>46</snq>,
 <snq>47</snq>,
 <snq>48</snq>,
 <snq>49</snq>,
 <snq>50</snq>,
 <snq>51</snq>,
 <snq>52</snq>,
 <snq>53</snq>,
 <snq>54</snq>,
 <snq>55</snq>,
 <snq>56</snq>,
 <snq>57</snq>,
 <snq>58</snq>,
 <snq>59</snq>,
 <snq>60</snq>,
 <snq>61</snq>,
 <snq>62</snq>,
 <snq>63</snq>,
 <snq>64</snq>,
 <snq>65</snq>,
 <snq>66</snq>,
 <snq>67</snq>,
 <snq>68</snq>,
 <snq>69</snq>,
 <snq>70</snq>,
 <snq>71</snq>,
 <snq>72</snq>,
 <snq>73</snq>,
 <snq>74</snq>,
 <snq>75</snq>,
 <snq>76</snq>,
 <snq>77</snq>,
 <snq>78</snq>,
 <snq>79</snq>,
 <snq>80</snq>,
 <snq>81</snq>,
 <snq>82</snq>,
 <snq>83</snq>,
 <snq>84</snq>,
 <snq>85</snq>,
 <snq>86</snq>,
 <snq>87</snq>,
 <snq>88</snq>,
 <snq>89</snq>,
 <snq>90</snq>,
 <snq>91</snq>,
 <snq>92</snq>,
 <snq>93</snq>,
 <snq>94</snq>,
 <snq>95</snq>,
 <snq>96</snq>,
 <snq>97</snq>,
 <snq>98</snq>,
 <snq>99</snq>,
 <snq>100</snq>,
 <snq>101</snq>,
 <snq>102</snq>,
 <snq>103</snq>,
 <snq>104</snq>,
 <snq>105</snq>,
 <snq>106</snq>,
 <snq>107</snq>,
 <snq>108</snq>,
 <snq>109</snq>,
 <snq>110</snq>,
 <snq>111</snq>,
 <snq>112</snq>,
 <snq>113</snq>,
 <snq>114</snq>,
 <snq>115</snq>,
 <snq>116</snq>,
 <snq>117</snq>,
 <snq>118</snq>,
 <snq>119</snq>,
 <snq>120</snq>,
 <snq>121</snq>,
 <snq>122</snq>,
 <snq>123</snq>,
 <snq>124</snq>,
 <snq>125</snq>,
 <snq>126</snq>,
 <snq>127</snq>,
 <snq>128</snq>,
 <snq>129</snq>,
 <snq>130</snq>,
 <snq>131</snq>,
 <snq>132</snq>,
 <snq>133</snq>,
 <snq>134</snq>,
 <snq>135</snq>,
 <snq>136</snq>,
 <snq>137</snq>,
 <snq>138</snq>,
 <snq>139</snq>,
 <snq>140</snq>,
 <snq>141</snq>,
 <snq>142</snq>,
 <snq>143</snq>,
 <snq>144</snq>,
 <snq>145</snq>,
 <snq>146</snq>,
 <snq>147</snq>,
 <snq>148</snq>,
 <snq>149</snq>,
 <snq>150</snq>,
 <snq>151</snq>,
 <snq>152</snq>,
 <snq>153</snq>,
 <snq>154</snq>,
 <snq>155</snq>,
 <snq>156</snq>,
 <snq>157</snq>,
 <snq>158</snq>,
 <snq>159</snq>,
 <snq>160</snq>,
 <snq>161</snq>,
 <snq>162</snq>,
 <snq>163</snq>,
 <snq>164</snq>,
 <snq>165</snq>,
 <snq>166</snq>,
 <snq>167</snq>,
 <snq>168</snq>,
 <snq>169</snq>,
 <snq>170</snq>,
 <snq>171</snq>,
 <snq>172</snq>,
 <snq>173</snq>,
 <snq>174</snq>,
 <snq>175</snq>,
 <snq>176</snq>,
 <snq>177</snq>,
 <snq>178</snq>,
 <snq>179</snq>,
 <snq>180</snq>,
 <snq>181</snq>,
 <snq>182</snq>,
 <snq>183</snq>,
 <snq>184</snq>,
 <snq>185</snq>,
 <snq>186</snq>,
 <snq>187</snq>,
 <snq>188</snq>,
 <snq>189</snq>,
 <snq>190</snq>,
 <snq>191</snq>,
 <snq>192</snq>,
 <snq>193</snq>,
 <snq>194</snq>,
 <snq>195</snq>,
 <snq>196</snq>,
 <snq>197</snq>,
 <snq>198</snq>,
 <snq>199</snq>,
 <snq>200</snq>,
 <snq>201</snq>,
 <snq>202</snq>,
 <snq>203</snq>,
 <snq>204</snq>,
 <snq>205</snq>,
 <snq>206</snq>,
 <snq>207</snq>,
 <snq>208</snq>,
 <snq>209</snq>,
 <snq>210</snq>,
 <snq>211</snq>,
 <snq>212</snq>,
 <snq>213</snq>,
 <snq>214</snq>,
 <snq>215</snq>,
 <snq>216</snq>,
 <snq>217</snq>,
 <snq>218</snq>,
 <snq>219</snq>,
 <snq>220</snq>,
 <snq>221</snq>,
 <snq>222</snq>,
 <snq>223</snq>,
 <snq>224</snq>,
 <snq>225</snq>,
 <snq>226</snq>,
 <snq>227</snq>,
 <snq>228</snq>,
 <snq>229</snq>,
 <snq>230</snq>,
 <snq>231</snq>,
 <snq>232</snq>,
 <snq>233</snq>,
 <snq>234</snq>,
 <snq>235</snq>,
 <snq>236</snq>,
 <snq>237</snq>,
 <snq>238</snq>,
 <snq>239</snq>,
 <snq>240</snq>,
 <snq>241</snq>,
 <snq>242</snq>,
 <snq>243</snq>,
 <snq>244</snq>,
 <snq>245</snq>,
 <snq>246</snq>,
 <snq>247</snq>,
 <snq>248</snq>,
 <snq>249</snq>,
 <snq>250</snq>,
 <snq>251</snq>,
 <snq>252</snq>,
 <snq>253</snq>,
 <snq>254</snq>,
 <snq>255</snq>,
 <snq>256</snq>,
 <snq>257</snq>,
 <snq>258</snq>,
 <snq>259</snq>,
 <snq>260</snq>,
 <snq>261</snq>,
 <snq>262</snq>,
 <snq>263</snq>,
 <snq>264</snq>,
 <snq>265</snq>,
 <snq>266</snq>,
 <snq>267</snq>,
 <snq>268</snq>,
 <snq>269</snq>,
 <snq>270</snq>,
 <snq>271</snq>,
 <snq>272</snq>,
 <snq>273</snq>,
 <snq>274</snq>,
 <snq>275</snq>,
 <snq>276</snq>,
 <snq>277</snq>,
 <snq>278</snq>,
 <snq>279</snq>,
 <snq>280</snq>,
 <snq>281</snq>,
 <snq>282</snq>,
 <snq>283</snq>,
 <snq>284</snq>,
 <snq>285</snq>,
 <snq>286</snq>,
 <snq>287</snq>,
 <snq>288</snq>,
 <snq>289</snq>,
 <snq>290</snq>,
 <snq>291</snq>,
 <snq>292</snq>,
 <snq>293</snq>,
 <snq>294</snq>,
 <snq>295</snq>,
 <snq>296</snq>,
 <snq>297</snq>,
 <snq>298</snq>,
 <snq>299</snq>,
 <snq>300</snq>,
 <snq>301</snq>,
 <snq>302</snq>,
 <snq>303</snq>,
 <snq>304</snq>,
 <snq>305</snq>,
 <snq>306</snq>,
 <snq>307</snq>,
 <snq>308</snq>,
 <snq>309</snq>,
 <snq>310</snq>,
 <snq>311</snq>,
 <snq>312</snq>,
 <snq>313</snq>,
 <snq>314</snq>,
 <snq>315</snq>,
 <snq>316</snq>,
 <snq>317</snq>,
 <snq>318</snq>,
 <snq>319</snq>,
 <snq>320</snq>,
 <snq>321</snq>,
 <snq>322</snq>,
 <snq>323</snq>,
 <snq>324</snq>,
 <snq>325</snq>,
 <snq>326</snq>,
 <snq>327</snq>,
 <snq>328</snq>,
 <snq>329</snq>,
 <snq>330</snq>,
 <snq>331</snq>,
 <snq>332</snq>,
 <snq>333</snq>,
 <snq>334</snq>,
 <snq>335</snq>,
 <snq>336</snq>,
 <snq>337</snq>,
 <snq>338</snq>,
 <snq>339</snq>,
 <snq>340</snq>,
 <snq>341</snq>,
 <snq>342</snq>,
 <snq>343</snq>,
 <snq>344</snq>,
 <snq>345</snq>,
 <snq>346</snq>,
 <snq>347</snq>,
 <snq>348</snq>,
 <snq>349</snq>,
 <snq>350</snq>,
 <snq>1</snq>,
 <snq>2</snq>,
 <snq>3</snq>,
 <snq>4</snq>,
 <snq>5</snq>,
 <snq>6</snq>,
 <snq>7</snq>,
 <snq>8</snq>,
 <snq>9</snq>,
 <snq>10</snq>,
 <snq>11</snq>,
 <snq>12</snq>,
 <snq>13</snq>,
 <snq>14</snq>,
 <snq>15</snq>,
 <snq>16</snq>,
 <snq>17</snq>,
 <snq>18</snq>,
 <snq>19</snq>,
 <snq>20</snq>,
 <snq>21</snq>,
 <snq>22</snq>,
 <snq>23</snq>,
 <snq>24</snq>,
 <snq>25</snq>,
 <snq>26</snq>,
 <snq>27</snq>,
 <snq>28</snq>,
 <snq>29</snq>,
 <snq>30</snq>,
 <snq>31</snq>,
 <snq>33</snq>,
 <snq>34</snq>,
 <snq>35</snq>,
 <snq>36</snq>,
 <snq>37</snq>,
 <snq>38</snq>,
 <snq>39</snq>,
 <snq>40</snq>,
 <snq>41</snq>,
 <snq>42</snq>,
 <snq>43</snq>,
 <snq>44</snq>,
 <snq>45</snq>,
 <snq>46</snq>,
 <snq>47</snq>,
 <snq>48</snq>,
 <snq>49</snq>,
 <snq>50</snq>,
 <snq>51</snq>,
 <snq>52</snq>,
 <snq>53</snq>,
 <snq>54</snq>,
 <snq>55</snq>,
 <snq>56</snq>,
 <snq>57</snq>,
 <snq>58</snq>,
 <snq>59</snq>,
 <snq>60</snq>,
 <snq>61</snq>,
 <snq>62</snq>,
 <snq>63</snq>,
 <snq>64</snq>,
 <snq>65</snq>,
 <snq>66</snq>,
 <snq>67</snq>,
 <snq>68</snq>,
 <snq>69</snq>,
 <snq>70</snq>,
 <snq>71</snq>,
 <snq>72</snq>,
 <snq>73</snq>,
 <snq>74</snq>,
 <snq>75</snq>,
 <snq>76</snq>,
 <snq>77</snq>,
 <snq>78</snq>,
 <snq>79</snq>,
 <snq>80</snq>,
 <snq>81</snq>,
 <snq>82</snq>,
 <snq>83</snq>,
 <snq>84</snq>,
 <snq>85</snq>,
 <snq>86</snq>,
 <snq>87</snq>,
 <snq>88</snq>,
 <snq>89</snq>,
 <snq>90</snq>,
 <snq>91</snq>,
 <snq>92</snq>,
 <snq>93</snq>,
 <snq>94</snq>,
 <snq>95</snq>,
 <snq>96</snq>,
 <snq>97</snq>,
 <snq>98</snq>,
 <snq>99</snq>,
 <snq>100</snq>,
 <snq>101</snq>,
 <snq>102</snq>,
 <snq>103</snq>,
 <snq>104</snq>,
 <snq>105</snq>,
 <snq>106</snq>,
 <snq>107</snq>,
 <snq>108</snq>,
 <snq>109</snq>,
 <snq>110</snq>,
 <snq>111</snq>,
 <snq>112</snq>,
 <snq>113</snq>,
 <snq>114</snq>,
 <snq>115</snq>,
 <snq>116</snq>,
 <snq>117</snq>,
 <snq>118</snq>,
 <snq>119</snq>,
 <snq>120</snq>,
 <snq>121</snq>,
 <snq>122</snq>,
 <snq>123</snq>,
 <snq>124</snq>,
 <snq>125</snq>,
 <snq>126</snq>,
 <snq>127</snq>,
 <snq>128</snq>,
 <snq>129</snq>,
 <snq>130</snq>,
 <snq>131</snq>,
 <snq>132</snq>,
 <snq>133</snq>,
 <snq>134</snq>,
 <snq>135</snq>,
 <snq>136</snq>,
 <snq>137</snq>,
 <snq>138</snq>,
 <snq>139</snq>,
 <snq>140</snq>,
 <snq>141</snq>,
 <snq>142</snq>,
 <snq>143</snq>,
 <snq>144</snq>,
 <snq>145</snq>,
 <snq>146</snq>,
 <snq>147</snq>,
 <snq>148</snq>,
 <snq>149</snq>,
 <snq>150</snq>,
 <snq>151</snq>,
 <snq>152</snq>,
 <snq>153</snq>,
 <snq>154</snq>,
 <snq>155</snq>,
 <snq>156</snq>,
 <snq>157</snq>,
 <snq>158</snq>,
 <snq>159</snq>,
 <snq>160</snq>,
 <snq>161</snq>,
 <snq>162</snq>,
 <snq>163</snq>,
 <snq>164</snq>,
 <snq>165</snq>,
 <snq>166</snq>,
 <snq>167</snq>,
 <snq>168</snq>,
 <snq>169</snq>,
 <snq>170</snq>,
 <snq>171</snq>,
 <snq>172</snq>,
 <snq>173</snq>,
 <snq>174</snq>,
 <snq>175</snq>,
 <snq>176</snq>,
 <snq>177</snq>,
 <snq>178</snq>,
 <snq>179</snq>,
 <snq>180</snq>,
 <snq>181</snq>,
 <snq>182</snq>,
 <snq>183</snq>,
 <snq>184</snq>,
 <snq>185</snq>,
 <snq>186</snq>,
 <snq>187</snq>,
 <snq>188</snq>,
 <snq>189</snq>,
 <snq>190</snq>,
 <snq>191</snq>,
 <snq>192</snq>,
 <snq>193</snq>,
 <snq>194</snq>,
 <snq>195</snq>,
 <snq>196</snq>,
 <snq>197</snq>,
 <snq>198</snq>,
 <snq>199</snq>,
 <snq>200</snq>,
 <snq>201</snq>,
 <snq>202</snq>,
 <snq>203</snq>,
 <snq>204</snq>,
 <snq>205</snq>,
 <snq>206</snq>,
 <snq>207</snq>,
 <snq>208</snq>,
 <snq>209</snq>,
 <snq>210</snq>,
 <snq>211</snq>,
 <snq>212</snq>,
 <snq>213</snq>,
 <snq>214</snq>,
 <snq>215</snq>,
 <snq>216</snq>,
 <snq>217</snq>,
 <snq>218</snq>,
 <snq>219</snq>,
 <snq>220</snq>,
 <snq>221</snq>,
 <snq>222</snq>,
 <snq>223</snq>,
 <snq>224</snq>,
 <snq>225</snq>,
 <snq>226</snq>,
 <snq>227</snq>,
 <snq>228</snq>,
 <snq>229</snq>,
 <snq>230</snq>,
 <snq>231</snq>,
 <snq>232</snq>,
 <snq>233</snq>,
 <snq>234</snq>,
 <snq>235</snq>,
 <snq>236</snq>,
 <snq>237</snq>,
 <snq>238</snq>,
 <snq>239</snq>,
 <snq>240</snq>,
 <snq>241</snq>,
 <snq>242</snq>,
 <snq>243</snq>,
 <snq>244</snq>,
 <snq>245</snq>,
 <snq>246</snq>,
 <snq>247</snq>,
 <snq>248</snq>,
 <snq>249</snq>,
 <snq>250</snq>,
 <snq>251</snq>,
 <snq>252</snq>,
 <snq>253</snq>,
 <snq>254</snq>,
 <snq>255</snq>,
 <snq>256</snq>,
 <snq>257</snq>,
 <snq>258</snq>,
 <snq>259</snq>,
 <snq>260</snq>,
 <snq>261</snq>,
 <snq>262</snq>,
 <snq>263</snq>,
 <snq>264</snq>,
 <snq>265</snq>,
 <snq>266</snq>,
 <snq>267</snq>,
 <snq>268</snq>,
 <snq>269</snq>,
 <snq>270</snq>,
 <snq>271</snq>,
 <snq>272</snq>,
 <snq>273</snq>,
 <snq>274</snq>,
 <snq>275</snq>,
 <snq>276</snq>,
 <snq>277</snq>,
 <snq>278</snq>,
 <snq>279</snq>,
 <snq>280</snq>,
 <snq>281</snq>,
 <snq>282</snq>,
 <snq>283</snq>,
 <snq>284</snq>,
 <snq>285</snq>,
 <snq>286</snq>,
 <snq>287</snq>,
 <snq>288</snq>,
 <snq>289</snq>,
 <snq>290</snq>,
 <snq>291</snq>,
 <snq>292</snq>,
 <snq>293</snq>,
 <snq>294</snq>,
 <snq>295</snq>,
 <snq>296</snq>,
 <snq>297</snq>,
 <snq>298</snq>,
 <snq>299</snq>,
 <snq>300</snq>,
 <snq>301</snq>,
 <snq>302</snq>,
 <snq>303</snq>]

In [24]:
result={}
for key in keys:
    for item in soup.select(key):
        result.setdefault(item.name, []).append(item.text)
df=pd.DataFrame(result)
df

basYm
snq
finPrdNm
lnLmt
irtCtg
irt
maxTotLnTrm
maxDfrmTrm
maxRdptTrm
rdptMthd
usge
trgt
instCtg
ofrInstNm
rsdAreaPamtEqltIstm
suprTgtDtlCond
age
incm
rsdArea
crdtSc
anin
housHoldCnt
housAr
lnTgtHous
rfrcCnpl
grnInst
jnMthd
rpymdCfe
lnIcdcst
ovItrYr
prftAddIrtCond
etcRefSbjc
hdlInst
cnpl
rltSite
tgtFltr
hdlInstDtlVw
prdExisYn
cv19Rfrc
prdCtg
prdNm
cv19SuprCtg
cv19SuprCtn
cv19SuprTgtDtlCtn
mgmDln
prdCtg2
fileWrtDt

# key_list를 만들고 select로 직접 추출하기

In [25]:
df_list = []
page = 1
while True:
    url = "https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    service_key = "8Ym5dhmVJdr12XzGnyYrQjSBS1QuRBYK8yHfx65JCl4vACM9uLKo8fxCVOFJkPB71llD7F2rOEROZnHgNGoj3A=="
    payload = dict(serviceKey=service_key, numOfRows=1000, pageNo=page, resultType='xml')
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    response = r.content
    soup = bs(response, "xml")
    numOfRows = int(soup.select_one("numOfRows").text)
    totalCount = int(soup.select_one("totalCount").text)
    total_pages = totalCount // numOfRows + 1
    key_list = {}
    for item in soup.select("*"):
        key_list.setdefault(item.name, "")
    keys = list(key_list.keys())
    result = {}
    for key in keys[10:]:
        for item in soup.select(key):
            result.setdefault(item.name, []).append(item.text)
    df_list.append(pd.DataFrame(result))
    if page < total_pages:
        page += 1
    else:
        print("데이터 수집완료")
        break
result_df = pd.concat(df_list)
result_df = result_df.reset_index(drop=True)
result_df

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=8Ym5dhmVJdr12XzGnyYrQjSBS1QuRBYK8yHfx65JCl4vACM9uLKo8fxCVOFJkPB71llD7F2rOEROZnHgNGoj3A%3D%3D&numOfRows=1000&pageNo=1&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=8Ym5dhmVJdr12XzGnyYrQjSBS1QuRBYK8yHfx65JCl4vACM9uLKo8fxCVOFJkPB71llD7F2rOEROZnHgNGoj3A%3D%3D&numOfRows=1000&pageNo=2&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=8Ym5dhmVJdr12XzGnyYrQjSBS1QuRBYK8yHfx65JCl4vACM9uLKo8fxCVOFJkPB71llD7F2rOEROZnHgNGoj3A%3D%3D&numOfRows=1000&pageNo=3&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=8Ym5dhmVJdr12XzGnyYrQjSBS1QuRBYK8yHfx65JCl4vACM9uLKo8fxCVOFJkPB71llD7F2rOEROZnHgNGoj3A%3D%3D&numOfRows=1000&pageNo=4&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=8Ym5dhmVJdr12XzGnyYrQjSBS1QuRBYK8yHfx65JCl4vACM9uLKo8fxCVOFJkPB71llD7F2rOEROZnHgNGoj3A%3D%3D&numOfRows=1000&pageNo=5&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=8Ym5dhmVJdr12XzGnyYrQjSBS1QuRBYK8yHfx65JCl4vACM9uLKo8fxCVOFJkPB71llD7F2rOEROZnHgNGoj3A%3D%3D&numOfRows=1000&pageNo=6&resultType=xml
200
데이터 수집완료

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202505,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
1,202505,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202506010700
2,202505,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
3,202505,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
4,202505,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202506010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5434,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
5435,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
5436,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
5437,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,,,202502010700
5438,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700