* post로 자료가져올 때, payload로 자료 가져오는 방법
* 개발자 모드 -> Fetch -> preview로 표 확인하기 -> payload

In [5]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [2]:
url='https://kind.krx.co.kr/corpgeneral/corpList.do?method=loadInitPage'

* http 프로토콜로 넘어오는 거는 모두 문자열이기 때문에 반드시 beautifulsoup을 통해서 파싱해야 됨

In [4]:
r=requests.get(url)
print(r.status_code)
soup=bs(r.content,'lxml')
soup

200

<!DOCTYPE html>
<html lang="ko">
<head>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="kr" http-equiv="content-language"/>
<meta content="text/css" http-equiv="content-style-type"/>
<meta content="no-cache" http-equiv="pragma"/>
<meta content="no-cache" http-equiv="cache-control"/>
<meta content="no" http-equiv="imagetoolbar"/>
<meta content="대한민국 대표 기업공시채널 KIND(c)2014" name="copyright"/>
<meta content="대한민국 대표 기업공시채널 KIND" name="description"/>
<meta content="대한민국 대표 기업공시채널 KIND" name="keywords"/>
<title>대한민국 대표 기업공시채널 KIND</title>
<link href="../images/kind.ico" rel="shortcut icon"/>
<link href="../js/jquery/themes-base/jquery-ui.min.css" media="all" rel="stylesheet" type="text/css"/>
<link href="../css/default_new.css" media="all" rel="stylesheet" type="text/css"/>
<link href="../css/common.css?version=20240927" media="all" rel="stylesheet" type="text/css"/>
<link href="../css/style.css?version=20250509" media="all" rel="stylesheet" type="text/css"/>
<link href="../esg/notoSans.css?20240524" media="all" rel="stylesheet" type="text/css"/>
<!--[if lt IE 9]>
<script type="text/javascript" src="../js/html5shiv.js"></script>
<![endif]-->
<script src="../js/dtree.js" type="text/javascript"></script>
<script src="../js/trans.js" type="text/javascript"></script>
<script src="../js/jquery/jquery.js" type="text/javascript"></script>
<script src="../js/jquery/jquery-ui.min.js" type="text/javascript"></script>
<script src="../js/jquery/jquery.placeholder.js" type="text/javascript"></script>
<script src="../js/common.js?version=20240927" type="text/javascript"></script>
<script src="../js/common-ajax.js" type="text/javascript"></script>
<script src="../js/JCommon.js?version=20250509" type="text/javascript"></script>
<script src="../js/common-sort.js" type="text/javascript"></script>
</head>
<body>
<!-- 화면 확대/축소 안내 START-->
<section class="notice popup modal type-00 hide">
<div class="container">
<div class="wrapper">
<hgroup class="handle"><h2>화면 확대/축소 안내</h2></hgroup>
<a class="btn-pop-close btn_close" href="#">닫기</a>
<section class="body">
<ul class="msg type-99 fc01">
<li>※ IE8 이하의 웹브라우저에서는 다음과 같은 방법으로 화면의 확대/축소 기능을 이용하실 수 있습니다.</li>
</ul>
<img alt="화면확대 화면축소" src="../images/common/notice.png"/>
</section>
</div>
<img alt="배경이미지" class="tl" src="../images/common/pop-type-00-tl.png"/>
<img alt="배경이미지" class="bl" src="../images/common/pop-type-00-bl.png"/>
<img alt="배경이미지" class="tr" src="../images/common/pop-type-00-tr.png"/>
<img alt="배경이미지" class="br" src="../images/common/pop-type-00-br.png"/>
<div class="tm"></div>
<div class="lm"></div>
<div class="bm"></div>
<div class="rm"></div>
</div>
</section>
<!-- HEADER 영역 START -->
<header class="container">
<div class="container_line">
<div class="wrapper-super">
<hgroup>
<h1 class="logo"><a href="/main.do?method=loadInitPage&amp;scrnmode=1" title="대한민국 대표 기업공시채널 KIND"><img alt="대한민국 대표 기업공시채널 KIND" src="../images/main/logo.gif"/></a></h1>
</hgroup>
<ul class="util">
<li class="first"><a href="/common/JLDDST35000.html" onclick="winCommPopOpen('1'); return false;" title="KIND 소개 새창"><img alt="KIND 소개" src="../images/common/util_intro.gif"/></a></li>
<li>
<a href="https://engkind.krx.co.kr/" target="_blank" title="KIND 영문사이트 바로가기"><img alt="ENGLISH KIND" src="../images/common/util_eng.gif"/></a>
</li>
<li class="btn-group">
<img alt="화면크기" class="ttl" src="../images/common/ttl_screen.gif"/>
<a class="plus zoom_btn-in" href="#"><span>확대</span></a>
<a class="reset zoom_btn-reset" href="#"><span>원래대로</span></a>
<a class="minus zoom_btn-out" href="#"><span>축소</span></a>
</li>
</ul>
<div class="clear"></div>
<form id="AKCFrm" name="AKCFrm">
<input id="method" name="method" type="hidden" value="disclosureSimpleSearchMain"/>
<input id="searchCodeType" name="searchCodeType" type="hidden" value=""/>
<input id="repIsuSrtCd" name="repIsuSrtCd" type="hidden" value=""/>
<input id="isurCd" name="isurCd" type="hidden" value=""/>
<input id="AKCKwdCode" name="AKCKwdCode" type="hidden" value=""/>
<section class="search auto_complete top-akc-sub">
<div class="autoKey">
<input autocomplete="off" class="search-txt dval" id="AKCKwdTop" name="searchCorpName" onblur="chkValidChar_top(this); fnMainCorpType();" placeholder="회사명 또는 종목코드를 입력해 주세요." type="text"/>
<div class="tselect">
<img alt="자동완성 열기" class="autoc_open" id="AKCArrowTop" src="../images/common/icn_autoc_open.gif"/>
<div class="AKCDivTop" id="AKCDivTop" style="display:none;">
<iframe frameborder="0" id="AKCIfrmTop" name="AKCIfrmTop" scrolling="no" src="../common/akc_top.html?version=20220624" title="자동완성"></iframe>
</div>
</div>
</div>
<input alt="검색" class="submit" onclick="fnTopAKCKwdSearch(); return false;" src="../images/common/btn_search.gif" type="image"/>
<div class="clear"></div>
</section>
</form>
<a class="btn sitemap open" href="#"><img alt="전체메뉴보기" src="../images/common/btn_sitemap.gif"/></a>
</div>
</div>
<div class="sitemap-wrapper">
<!-- TOP MENU START -->
<section class="sitemap">
<article class="mymenu">
<h3><img alt="나만의 메뉴" src="../images/common/ttl_sitemap_my.png"/></h3>
<div class="list">
<ul id="myMenuTop">
<li class="active"><a href="/disclosure/todaydisclosure.do?method=searchTodayDisclosureMain">오늘의공시</a></li>
<li><a href="/disclosure/searchdisclosurebycorp.do?method=searchDisclosureByCorpMain">회사별검색</a></li>
<li><a href="/disclosure/searchtotalinfo.do?method=searchTotalInfoMain">통합검색</a></li>
<li><a href="/disclosure/details.do?method=searchDetailsMain">상세검색</a></li>
<li><a href="/corpdetail/totalinfo.do?method=loadInitPage">종합정보</a></li>
</ul>
</div>
<a class="btn_sitemap-set" href="#"><img alt="설정" src="../images/common/btn_sitemap_set.png"/></a>
</article>
<section class="list-wrapper links">
<article class="list">
<h3>공시</h3>
<ul>
<li><a class="first" href="/disclosure/todaydisclosure.do?method=searchTodayDisclosureMain">오늘의공시</a></li>
<li><a class="first" href="/disclosure/searchdisclosurebycorp.do?method=searchDisclosureByCorpMain">회사별검색</a></li>
<li><a class="first" href="/disclosure/details.do?method=searchDetailsMain">상세검색</a></li>
<li><a class="first" href="#" onclick="krxPaPago_open(); return false;">KRX-Papago번역기</a></li>
<li><a class="first" href="/disclosure/searchtotalinfo.do?method=searchTotalInfoMain">통합검색</a></li>
<li><a class="first" href="/disclosure/searchbondcorpdisclosure.do?method=searchBondCorpDisclosureMain">채권공시</a></li>
<!-- <li style="height:32px;"><a href="#" class="more">ETF/ELW/ETN/<br>상장형수익증권<span><img src="../images/common/bg_gnb_gmn2.gif" alt="메뉴 더보기"/></span></a></li> 2025.07 오픈. 주석 풀면 됨--> <!-- 상장형수익증권이 추가 되면서 간격조정을 위해 해당 메뉴만 높이를 34px로 잡음 2025.02.14 -->
<li><a class="more" href="#">ETF/ELW/ETN<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li> <!-- 2025.07 오픈 시 삭제 -->
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeEtf">ETF</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeElw">ELW</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeEtn">ETN</a>
<!-- <A class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypePf">상장형수익증권</A> 2025.07 오픈. 주석 풀면 됨-->
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="more" href="#">펀드공시<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeRestinvstcom">부동산투자회사</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeShipinvstcom">선박투자회사</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeInvstcom">투자회사</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeBenfcert">수익증권</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/disclosure/misccorpdiscls.do?method=searchMiscCorpDisclsMain">기타법인공시</a></li>
<li><a class="more" href="#">의결권행사공시<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/disclosure/disclosurebyvote.do?method=searchDisclosurebyVoteMain">의결권행사공시</a>
<a class="lmn" href="https://dis.kofia.or.kr/websquare/index.jsp?w2xPath=/wq/compann/DISFndVoteRightView.xml&amp;divisionId=MDIS02003010000000&amp;serviceId=SDIS02003010000#!" target="_blank">운용사 펀드의결권행사공시</a>
<a class="lmn" href="https://dis.kofia.or.kr/websquare/index.jsp?w2xPath=/wq/compann/DISFndVoteRightViewDet.xml&amp;divisionId=MDIS02003011000000&amp;serviceId=SDIS02003011000" target="_blank">펀드별 의결권행사공시</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/corpdetail/chart.do?method=loadInitPage">공시차트</a></li>
<li><a class="first" href="/disclosure/searchErrorTradeRelief.do?method=searchErrorTradeReliefMain">착오매매구제신청</a></li>
<!-- 신종증권 메뉴 제외 -->
<!--<li><a href="#" class="more">신종증권<span><img src="../images/common/bg_gnb_gmn2.gif" alt="메뉴 더보기"/></span></a></li>
						<DIV id="sub" class="gnb1-wrapper">
							<nav id="gnb1">
							<DL>
							<DD>
							<DIV class="lnb">
								<DIV class="wrapper">
									<A class="lmn" href="/digital/digitalList.do?method=digitalList">비금전신탁수익증권</A>
									<A class="lmn" href="/digital/digitalInvstList.do?method=digitalInvstList">투자계약증권</A>
									<IMG class="arrow" src="../images/common/lnb_arrow_sub.png" />
									<IMG class="tl" src="../images/common/lnb_tl.png" />
									<IMG class="tr" src="../images/common/lnb_tr.png" />
									<IMG class="bl" src="../images/common/lnb_bl.png" />
									<IMG class="br" src="../images/common/lnb_br.png" />
								</DIV>
							</DIV>
							</DD>
							</DL>
							</nav>
						</DIV>
						-->
</ul>
</article>
<article class="list">
<h3>상장법인상세정보</h3>
<ul>
<li><a class="first" href="/corpdetail/totalinfo.do?method=loadInitPage">종합정보</a></li>
<li><a class="first" href="/corpgeneral/listedIssueStatus.do?method=loadInitPage">상장종목현황</a></li>
<li><a class="first" href="/corpgeneral/corpList.do?method=loadInitPage">상장법인목록</a></li>
<li><a class="first" href="/corpgeneral/stockissuelist.do?method=loadInitPage">주식발행내역</a></li>
<li><a class="more" href="#">기업지배구조<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/corpgeneral/companyGovernance.do?method=loadInitPage">기업지배구조 보고서</a>
<a class="lmn" href="http://www.cgs.or.kr/business/esg_tab04.jsp" target="_blank">ESG등급</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/corpgeneral/treasurystk.do?method=loadInitPage">자사주취득/처분</a></li>
<li><a class="more" href="#">IR일정/IR자료실<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/corpgeneral/irschedule.do?method=searchIRScheduleMain&amp;gubun=iRSchedule">IR일정</a>
<a class="lmn" href="/corpgeneral/irschedule.do?method=searchIRScheduleMain&amp;gubun=iRMaterials">IR자료실</a>
<a class="lmn" href="https://www.youtube.com/playlist?list=PLAgvDyD2zN6ry9AVlh2emmvoJy4K39KT7" target="_blank">영상자료</a>
<a class="lmn" href="/corpgeneral/irschedule.do?method=searchIRScheduleMain&amp;gubun=iRScheduleCalendar">IR일정 달력</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="more" href="#">기업분석보고서<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/corpgeneral/companyAnalysisReport.do?method=listingForeignCompanyMain&amp;searchGubun=companyAnalysisReport">기업분석리포트</a>
<a class="lmn" href="/corpgeneral/newListingForeignCompany.do?method=listingForeignCompanyMain&amp;searchGubun=newListingForeignCompany">신규상장기업분석보고서</a>
<a class="lmn" href="/corpgeneral/growthReport.do?method=listingForeignCompanyMain&amp;searchGubun=growthReport">사업모델 평가보고서 및 기업 계속성 보고서</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/corpgeneral/corpGroup.do?method=loadInitPage">기업집단</a></li>
<li><a class="more" href="#">배당정보<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/disclosureinfo/dividendinfo.do?method=searchDividendInfoMain">배당정보</a>
<a class="lmn" href="http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201010107" target="_blank">업종배당수익율</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/compfinance/financialinfo.do?method=loadInitPage&amp;searchgubun=corporation">회사재무비교</a></li>
<li><a class="first" href="/corpgeneral/excntDisclsCompany.do?method=loadInitPage">공시우수법인</a></li>
<li><a class="first" href="/corpdetail/ventureFundInvest.do?method=corpListMain">벤처펀드투자기업(코)</a></li>
<!-- 신종증권 메뉴 제외 -->
<!--<li><a href="/digital/digitalCorpList.do?method=digitalCorpList" class="first">상장종목(신종증권)</a></li>-->
</ul>
</article>
<article class="list">
<h3>기업 밸류업 정보</h3>
<ul>
<li><a class="first" href="/valueup/intro.do?method=valueupIntroMain">기업 밸류업 소개</a></li>
<li><a class="first" href="/valueup/notice.do?method=valueupNoticeMain">공지사항</a></li>
<li><a class="first" href="/valueup/disclsstat.do?method=valueupDisclsStatMain">공시현황</a></li>
<li><a class="more" href="#">투자지표<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/valueup/invstindicsectors.do?method=valueupInvstIndicRankIndMain">업종별 투자지표 순위</a>
<a class="lmn" href="/valueup/invstindicstocks.do?method=valueupInvstIndicRankIsuMain">종목별 투자지표 추이</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/valueup/idx.do?method=valueupIdxMain">인덱스</a></li>
<li><a class="first" href="/valueup/excntcorp.do?method=valueupExcntCorpMain">밸류업 우수기업</a></li>
<li><a class="first" href="/valueup/resoroom.do?method=valueupResoroomMain">자료실</a></li>
</ul>
</article>
<article class="list weight">
<h3>투자유의사항</h3>
<ul>
<li><a class="first" href="/investwarn/adminissue.do?method=searchAdminIssueList">관리종목</a></li>
<li><a class="first" href="/investwarn/hwangiissue.do?method=searchHwangiIssueMain">투자주의환기종목(코)</a></li>
<li><a class="first" href="/investwarn/tradinghaltissue.do?method=searchTradingHaltIssueMain">매매거래정지종목</a></li>
<li><a class="first" href="/investwarn/undisclosure.do?method=searchUnfaithfulDisclosureCorpList">불성실공시법인</a></li>
<li><a class="first" href="/investwarn/investattentwarnrisky.do?method=investattentwarnriskyMain">투자주의/경고/위험종목</a></li>
<li><a class="first" href="/corpgeneral/delistRealInvstg.do?method=searchDelistRealInvstgMain">실질심사법인</a></li>
<li><a class="first" href="/investwarn/investattentEmbezzlement.do?method=searchInvestAttentEmbezzlementMain">횡령 등</a></li>
<li><a class="first" href="/investwarn/investattentLargeShareChange.do?method=searchInvestAttentLargeShareChangeMain">최대주주변경2회이상</a></li>
<li><a class="more" href="#">기타사항<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/investwarn/investattentEtcMarket.do?method=searchInvestAttentEtcMarketMain">기타 시장안내</a>
<a class="lmn" href="/investwarn/prtdepoStat.do?method=searchPrtdepoStatMain">의무보유현황(유가)</a>
<a class="lmn" href="/investwarn/penalty.do?method=searchPenaltyImprovementList">벌점및개선계획서 현황</a>
<a class="lmn" href="/investwarn/delcompany.do?method=searchDelCompanyMain">상장폐지현황</a>
<a class="lmn" href="/investwarn/delListDelibRec.do?method=searchDelListDelibRecMain">상장폐지최종심의의사록</a>
<a class="lmn" href="/investwarn/investwarnGuide.do?method=searchInvestGuideMain">투자유의안내</a>
<a class="lmn" href="/disclosureinfo/nfaithdisclsdecl.do?method=insertNfaithdisclsDeclMain">불성실공시 신고포상</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
</ul>
</article>
<article class="list">
<h3>IPO현황</h3>
<ul>
<li><a class="first" href="/listinvstg/listinvstgcom.do?method=searchListInvstgCorpMain">예비심사기업</a></li>
<li><a class="first" href="/listinvstg/listapplcom.do?method=searchListApplCorpMain">코넥스 상장신청기업</a></li>
<li><a class="more" href="#">공모기업<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/listinvstg/pubofrprogcom.do?method=searchPubofrProgComMain">공모기업현황</a>
<a class="lmn" href="/listinvstg/pubofrschdl.do?method=searchPubofrScholMain">공모일정</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>

# 찾을 자료 1개씩 가져오기

In [8]:
url="https://kind.krx.co.kr/corpgeneral/corpList.do"

In [9]:
payload=dict(method='searchCorpList', pageIndex=1, currentPageSize=100, orderMode=3, orderStat='D', searchType=13, fiscalYearEnd='all', location='all')

In [10]:
r=requests.post(url, data=payload)
print(r.status_code)
soup=bs(r.content, 'lxml')
soup

200

<html><body><section class="scrarea type-00">
<table class="list type-00 tmt30" summary="회사명, 업종, 주요제품, 상장일, 결산월, 대표자명, 홈페이지, 지역">
<caption>목록</caption>
<colgroup>
<col width="*"/>
<col width="15%"/>
<col width="20%"/>
<col width="11%"/>
<col width="8%"/>
<col width="10%"/>
<col width="8%"/>
<col width="12%"/>
</colgroup>
<thead>
<tr class="first" id="title-contents">
</tr>
</thead>
<tbody>
<tr class="first">
<td class="first" title="키스트론(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('47543'); return false;" title="키스트론"> 키스트론</a> </td>
<td class="textOverflow" title="절연선 및 케이블 제조업">절연선 및 케이블 제조업</td>
<td class="textOverflow" title="전자부품용 와이어, 케이블용 와이어 등">전자부품용 와이어, 케이블용 와이어 등</td>
<td class="txc">2025-06-02</td>
<td class="txc">12월</td>
<td class="txc" title="정민호">정민호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.kistron.com/" target="_blank" title="http://www.kistron.com/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="신한제16호기업인수목적 주식회사"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('49607'); return false;" title="신한제16호스팩"> 신한제16호스팩</a> </td>
<td class="textOverflow" title="금융 지원 서비스업">금융 지원 서비스업</td>
<td class="textOverflow" title="기타금융서비스(기업합병)">기타금융서비스(기업합병)</td>
<td class="txc">2025-05-29</td>
<td class="txc">12월</td>
<td class="txc" title="김종환">김종환</td>
<td class="txc">
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)인투셀"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('28784'); return false;" title="인투셀"> 인투셀</a> </td>
<td class="textOverflow" title="자연과학 및 공학 연구개발업">자연과학 및 공학 연구개발업</td>
<td class="textOverflow" title="ADC 링커/톡신 플랫폼 기술">ADC 링커/톡신 플랫폼 기술</td>
<td class="txc">2025-05-23</td>
<td class="txc">12월</td>
<td class="txc" title="박태교">박태교</td>
<td class="txc">
<a class="btn ico homepage" href="http://intocell.com" target="_blank" title="http://intocell.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대전광역시</td>
</tr>
<tr>
<td class="first" title="(주)달바글로벌"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48365'); return false;" title="달바글로벌"> 달바글로벌</a> </td>
<td class="textOverflow" title="기타 화학제품 제조업">기타 화학제품 제조업</td>
<td class="textOverflow" title="기초 화장품, 건강기능식품 등">기초 화장품, 건강기능식품 등</td>
<td class="txc">2025-05-22</td>
<td class="txc">12월</td>
<td class="txc" title="반성연">반성연</td>
<td class="txc">
<a class="btn ico homepage" href="http://dalbaglobal.com" target="_blank" title="http://dalbaglobal.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="주식회사 바이오비쥬"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48946'); return false;" title="바이오비쥬"> 바이오비쥬</a> </td>
<td class="textOverflow" title="기타 화학제품 제조업">기타 화학제품 제조업</td>
<td class="textOverflow" title="스킨부스터 제품 및 필러">스킨부스터 제품 및 필러</td>
<td class="txc">2025-05-20</td>
<td class="txc">12월</td>
<td class="txc" title="양준호">양준호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.biobijou.co.kr/" target="_blank" title="http://www.biobijou.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)이뮨온시아"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('42487'); return false;" title="이뮨온시아"> 이뮨온시아</a> </td>
<td class="textOverflow" title="자연과학 및 공학 연구개발업">자연과학 및 공학 연구개발업</td>
<td class="textOverflow" title="면역항암제 신약개발">면역항암제 신약개발</td>
<td class="txc">2025-05-19</td>
<td class="txc">12월</td>
<td class="txc" title="김흥태">김흥태</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.immuneoncia.com/immun/" target="_blank" title="http://www.immuneoncia.com/immun/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)바이오포트코리아"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('18804'); return false;" title="바이오포트"> 바이오포트</a> </td>
<td class="textOverflow" title="기타 식품 제조업">기타 식품 제조업</td>
<td class="textOverflow" title="후라이드오징어튀김, 유자생강차 등 스낵 및 음료">후라이드오징어튀김, 유자생강차 등 스낵 및 음료</td>
<td class="txc">2025-05-16</td>
<td class="txc">12월</td>
<td class="txc" title="김성구">김성구</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.biopk.co.kr" target="_blank" title="http://www.biopk.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">부산광역시</td>
</tr>
<tr>
<td class="first" title="티씨머티리얼즈(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('12502'); return false;" title="티씨머티리얼즈"> 티씨머티리얼즈</a> </td>
<td class="textOverflow" title="절연선 및 케이블 제조업">절연선 및 케이블 제조업</td>
<td class="textOverflow" title="에나멜동선, 초고압케이블, 각동선, CTC 등">에나멜동선, 초고압케이블, 각동선, CTC 등</td>
<td class="txc">2025-05-15</td>
<td class="txc">12월</td>
<td class="txc" title="심영섭">심영섭</td>
<td class="txc">
</td>
<td class="txc">울산광역시</td>
</tr>
<tr>
<td class="first" title="주식회사 로킷헬스케어"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('37690'); return false;" title="로킷헬스케어"> 로킷헬스케어</a> </td>
<td class="textOverflow" title="의료용품 및 기타 의약 관련제품 제조업">의료용품 및 기타 의약 관련제품 제조업</td>
<td class="textOverflow" title="장기 재생 플랫폼">장기 재생 플랫폼</td>
<td class="txc">2025-05-12</td>
<td class="txc">12월</td>
<td class="txc" title="유석환">유석환</td>
<td class="txc">
<a class="btn ico homepage" href="http://rokithealthcare.com" target="_blank" title="http://rokithealthcare.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="오가노이드사이언스(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('47604'); return false;" title="오가노이드사이언스"> 오가노이드사이언스</a> </td>
<td class="textOverflow" title="자연과학 및 공학 연구개발업">자연과학 및 공학 연구개발업</td>
<td class="textOverflow" title="오가노이드 기반 재생치료제, 오가노이드 기반 신소재평가 솔루션">오가노이드 기반 재생치료제, 오가노이드 기반 신소재평가 솔루션</td>
<td class="txc">2025-05-09</td>
<td class="txc">12월</td>
<td class="txc" title="유종만">유종만</td>
<td class="txc">
<a class="btn ico homepage" href="http://organoidrx.com" target="_blank" title="http://organoidrx.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)원일티엔아이"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('13615'); return false;" title="원일티엔아이"> 원일티엔아이</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="수소저장합금, 고압연소식기화기">수소저장합금, 고압연소식기화기</td>
<td class="txc">2025-05-09</td>
<td class="txc">12월</td>
<td class="txc" title="이정빈">이정빈</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.woniltni.co.kr/" target="_blank" title="http://www.woniltni.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)나우로보틱스"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('45951'); return false;" title="나우로보틱스"> 나우로보틱스</a> </td>
<td class="textOverflow" title="특수 목적용 기계 제조업">특수 목적용 기계 제조업</td>
<td class="textOverflow" title="산업용로봇 및 로봇자동화시스템">산업용로봇 및 로봇자동화시스템</td>
<td class="txc">2025-05-08</td>
<td class="txc">12월</td>
<td class="txc" title="이종주">이종주</td>
<td class="txc">
<a class="btn ico homepage" href="http://naurobot.com" target="_blank" title="http://naurobot.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">인천광역시</td>
</tr>
<tr>
<td class="first" title="(주)에이아이코리아"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('36495'); return false;" title="에이아이코리아"> 에이아이코리아</a> </td>
<td class="textOverflow" title="특수 목적용 기계 제조업">특수 목적용 기계 제조업</td>
<td class="textOverflow" title="2차전지 중앙 전해액 공급시스템(CESS), 프로세스파이핑, 건식세정장비">2차전지 중앙 전해액 공급시스템(CESS), 프로세스파이핑, 건식세정장비</td>
<td class="txc">2025-04-29</td>
<td class="txc">12월</td>
<td class="txc" title="안진호">안진호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.aik.co.kr/" target="_blank" title="http://www.aik.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)쎄크"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('08118'); return false;" title="쎄크"> 쎄크</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="X-ray 검사장비, LINAC, Tabletop SEM">X-ray 검사장비, LINAC, Tabletop SEM</td>
<td class="txc">2025-04-28</td>
<td class="txc">12월</td>
<td class="txc" title="김종현">김종현</td>
<td class="txc">
<a class="btn ico homepage" href="http:///www.seceng.co.kr/" target="_blank" title="http:///www.seceng.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="한국피아이엠(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44890'); return false;" title="한국피아이엠"> 한국피아이엠</a> </td>
<td class="textOverflow" title="자동차 신품 부품 제조업">자동차 신품 부품 제조업</td>
<td class="textOverflow" title="내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)">내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)</td>
<td class="txc">2025-04-04</td>
<td class="txc">12월</td>
<td class="txc" title="송준호">송준호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.pimkorea.com" target="_blank" title="http://www.pimkorea.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대구광역시</td>
</tr>
<tr>
<td class="first" title="(주)에이유브랜즈"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48107'); return false;" title="에이유브랜즈"> 에이유브랜즈</a> </td>
<td class="textOverflow" title="섬유, 의복, 신발 및 가죽제품 소매업">섬유, 의복, 신발 및 가죽제품 소매업</td>
<td class="textOverflow" title="레인부츠, 스니커즈, 겨울화, 패션잡화 등">레인부츠, 스니커즈, 겨울화, 패션잡화 등</td>
<td class="txc">2025-04-03</td>
<td class="txc">12월</td>
<td class="txc" title="김지훈">김지훈</td>
<td class="txc">
<a class="btn ico homepage" href="http://aubrandz.irpage.co.kr" target="_blank" title="http://aubrandz.irpage.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="우양에이치씨(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('10197'); return false;" title="우양에이치씨"> 우양에이치씨</a> </td>
<td class="textOverflow" title="구조용 금속제품, 탱크 및 증기발생기 제조업">구조용 금속제품, 탱크 및 증기발생기 제조업</td>
<td class="textOverflow" title="화공 플랜트, 에너지 플랜트">화공 플랜트, 에너지 플랜트</td>
<td class="txc">2025-03-28</td>
<td class="txc">12월</td>
<td class="txc" title="김진태">김진태</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.wooyang.co.kr" target="_blank" title="http://www.wooyang.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)더즌"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46286'); return false;" title="더즌"> 더즌</a> </td>
<td class="textOverflow" title="전기 통신업">전기 통신업</td>
<td class="textOverflow" title="디지털뱅킹 솔루션(B2B 금융 서비스)">디지털뱅킹 솔루션(B2B 금융 서비스)</td>
<td class="txc">2025-03-24</td>
<td class="txc">12월</td>
<td class="txc" title="조철한">조철한</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.dozn.co.kr/" target="_blank" title="http://www.dozn.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)심플랫폼"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44453'); return false;" title="심플랫폼"> 심플랫폼</a> </td>
<td class="textOverflow" title="소프트웨어 개발 및 공급업">소프트웨어 개발 및 공급업</td>
<td class="textOverflow" title="NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)">NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)</td>
<td class="txc">2025-03-21</td>
<td class="txc">12월</td>
<td class="txc" title="임대근, 강태신">임대근..</td>
<td class="txc">
<a class="btn ico homepage" href="http://simplatform.com/" target="_blank" title="http://simplatform.com/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="주식회사 티엑스알로보틱스"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48481'); return false;" title="티엑스알로보틱스"> 티엑스알로보틱스</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="물류자동화, 로봇자동화, AMR/AGV">물류자동화, 로봇자동화, AMR/AGV</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="엄인섭">엄인섭</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.txr.kr" target="_blank" title="http://www.txr.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)한텍"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('09807'); return false;" title="한텍"> 한텍</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="열교환기 등 화공기기, 저장용 탱크">열교환기 등 화공기기, 저장용 탱크</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="김강식">김강식</td>
<td class="txc">
<a class="btn ico homepage" href="http://hantechltd.com" target="_blank" title="http://hantechltd.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">울산광역시</td>
</tr>
<tr>
<td class="first" title="한화플러스제5호기업인수목적(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('49839'); return false;" title="한화플러스제5호스팩"> 한화플러스제5호스팩</a> </td>
<td class="textOverflow" title="금융 지원 서비스업">금융 지원 서비스업</td>
<td class="textOverflow" title="-">-</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="김광후">김광후</td>
<td class="txc">
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)씨케이솔루션"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48037'); return false;" title="씨케이솔루션"> 씨케이솔루션</a> </td>
<td class="textOverflow" title="건축기술, 엔지니어링 및 관련 기술 서비스업">건축기술, 엔지니어링 및 관련 기술 서비스업</td>
<td class="textOverflow" title="드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업">드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업</td>
<td class="txc">2025-03-17</td>
<td class="txc">12월</td>
<td class="txc" title="김유곤, 안근표 (공동 대표이사)">김유곤..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.cksolution.co.kr/" target="_blank" title="http://www.cksolution.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="서울보증보험(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('03121'); return false;" title="서울보증보험"> 서울보증보험</a> </td>
<td class="textOverflow" title="보험업">보험업</td>
<td class="textOverflow" title="보증보험, 신용보험 등">보증보험, 신용보험 등</td>
<td class="txc">2025-03-14</td>
<td class="txc">12월</td>
<td class="txc" title="이명순">이명순</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.sgic.co.kr" target="_blank" title="http://www.sgic.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)에스엠씨지"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46087'); return false;" title="에스엠씨지"> 에스엠씨지</a> </td>
<td class="textOverflow" title="유리 및 유리제품 제조업">유리 및 유리제품 제조업</td>
<td class="textOverflow" title="화장품 유리용기">화장품 유리용기</td>
<td class="txc">2025-03-07</td>
<td class="txc">12월</td>
<td class="txc" title="최승호">최승호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.somangglass.co.kr" target="_blank" title="http://www.somangglass.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="엠디바이스 주식회사"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('22659'); return false;" title="엠디바이스"> 엠디바이스</a> </td>
<td class="textOverflow" title="전자부품 제조업">전자부품 제조업</td>
<td class="textOverflow" title="반도체기억장치">반도체기억장치</td>
<td class="txc">2025-03-07</td>
<td class="txc">12월</td>
<td class="txc" title="조호경">조호경</td>
<td class="txc">
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="대진첨단소재(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('39397'); return false;" title="대진첨단소재"> 대진첨단소재</a> </td>
<td class="textOverflow" title="플라스틱제품 제조업">플라스틱제품 제조업</td>
<td class="textOverflow" title="이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름">이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름</td>
<td class="txc">2025-03-06</td>
<td class="txc">12월</td>
<td class="txc" title="유성준, 장현주">유성준..</td>
<td class="txc">
<a class="btn ico homepage" href="http://daejin2019.com" target="_blank" title="http://daejin2019.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)에르코스 농업회사법인"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('43557'); return false;" title="에르코스"> 에르코스</a> </td>
<td class="textOverflow" title="도시락 및 식사용 조리식품 제조업">도시락 및 식사용 조리식품 제조업</td>
<td class="textOverflow" title="영유아식, 고령친화식품, 식물기반 대체식품">영유아식, 고령친화식품, 식물기반 대체식품</td>
<td class="txc">2025-02-28</td>
<td class="txc">12월</td>
<td class="txc" title="김슬기">김슬기</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ercohs.com" target="_blank" title="http://www.ercohs.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대전광역시</td>
</tr>
<tr>
<td class="first" title="(주)엘케이켐"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48950'); return false;" title="엘케이켐"> 엘케이켐</a> </td>
<td class="textOverflow" title="기타 화학제품 제조업">기타 화학제품 제조업</td>
<td class="textOverflow" title="반도체 소재(CP, PCP, DIS) 등">반도체 소재(CP, PCP, DIS) 등</td>
<td class="txc">2025-02-25</td>
<td class="txc">12월</td>
<td class="txc" title="이창엽">이창엽</td>
<td class="txc">
<a class="btn ico homepage" href="http://lkchem.co.kr" target="_blank" title="http://lkchem.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">충청남도</td>
</tr>
<tr>
<td class="first" title="(주)위너스"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('47996'); return false;" title="위너스"> 위너스</a> </td>
<td class="textOverflow" title="기타 전기장비 제조업">기타 전기장비 제조업</td>
<td class="textOverflow" title="배선기구(스위치, 콘센트, 멀티탭), 전기차 충전기(급속, 완속)">배선기구(스위치, 콘센트, 멀티탭), 전기차 충전기(급속, 완속)</td>
<td class="txc">2025-02-24</td>
<td class="txc">12월</td>
<td class="txc" title="김창성">김창성</td>
<td class="txc">

In [24]:
soup.select('tbody > tr')[0].select_one('td:nth-child(1)')

<td class="first" title="키스트론(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('47543'); return false;" title="키스트론"> 키스트론</a> </td>

In [29]:
# 주식종목
soup.select('tbody > tr')[0].select_one('td:nth-child(1) img')['alt']

'코스닥'

In [30]:
#회사명
soup.select('tbody > tr')[0].select_one('td:nth-child(1) > a')['title']

'키스트론'

In [34]:
# 종목코드
soup.select('tbody > tr')[0].select_one('td:nth-child(1) > a')['onclick'].split("'")[1]

'47543'

In [64]:
# 업종
soup.select('tbody > tr')[0].select_one('td:nth-child(2)').text

'절연선 및 케이블 제조업'

In [63]:
# 주요제품
soup.select('tbody > tr')[0].select_one('td:nth-child(3)').text

'전자부품용 와이어, 케이블용 와이어 등'

In [52]:
# 상장일
soup.select('tbody > tr')[0].select_one('td:nth-child(4)').text

'2025-06-02'

In [53]:
# 결산월
soup.select('tbody > tr')[0].select_one('td:nth-child(5)').text

'12월'

In [54]:
# 대표자명
soup.select('tbody > tr')[0].select_one('td:nth-child(6)')['title']

'정민호'

In [67]:
# 홈페이지
soup.select('tbody > tr')[0].select_one('td:nth-child(7) > a')['href']

'http://www.kistron.com/'

In [69]:
# 지역
soup.select('tbody > tr')[0].select_one('td:nth-child(8)').text

'경기도'

In [75]:
# 전체 페이지
total_page=int(soup.select_one('.info.type-00 em').text.replace(",","")) // 100 + 1

2763

In [83]:
columns

['주식종목', '회사명', '종목코드', '업종', '주요제품', '상장일', '결산월', '대표자명', '홈페이지', '지역']

# 전체 페이지 수쥡

In [13]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs
import os

In [15]:
company_infos=[]
page=1
while True:
    url="https://kind.krx.co.kr/corpgeneral/corpList.do"
    payload=dict(method='searchCorpList', pageIndex=page, currentPageSize=100, orderMode=3, orderStat='D', searchType=13, fiscalYearEnd='all', location='all')
    r=requests.post(url, data=payload)
    print(r.status_code)
    soup=bs(r.content, 'lxml')
    total_page=int(soup.select_one('.info.type-00 em').text.replace(",","")) // 100 + 1
    for idx, tr in enumerate(soup.select('tbody > tr')):
        print(f"{page}/{total_page}", end='\r')
        print(f'{idx+1}/{len(soup.select("tbody > tr"))} 작업중', end='\r')
        # 주식종목
        stock_type=tr.select_one('td:nth-child(1) img')['alt']
        #회사명
        company_name=tr.select_one('td:nth-child(1) > a')['title']
        # 종목코드
        stock_code=tr.select_one('td:nth-child(1) > a')['onclick'].split("'")[1]
        # 업종
        business_type=tr.select_one('td:nth-child(2)').text
        # 주요제품
        product=tr.select_one('td:nth-child(3)').text
        # 상장일
        resi_date=tr.select_one('td:nth-child(4)').text
        # 결산월
        settlement=tr.select_one('td:nth-child(5)').text
        # 대표자명
        ceo=tr.select_one('td:nth-child(6)')['title']
        # 홈페이지
        homepage=tr.select_one('td:nth-child(7) > a')['href'] if tr.select_one('td:nth-child(7) > a')!=None else ""
        # 지역
        region=tr.select_one('td:nth-child(8)').text
        company_infos.append((stock_type, company_name, stock_code, business_type, product,
                            resi_date, settlement, ceo, homepage, region))

    if page < total_page:
        page+=1
    else:
        break
# 컬럼명
columns=soup.select_one(".list.type-00.tmt30")['summary'].split(", ")
columns.insert(0, '주식종목')
columns.insert(2, '종목코드')
print(columns)
df=pd.DataFrame(company_infos, columns=columns)
df

200
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
200/100 작업중
['주식종목', '회사명', '종목코드', '업종', '주요제품', '상장일', '결산월', '대표자명', '홈페이지', '지역']

,주식종목,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,코스닥,키스트론,47543,절연선 및 케이블 제조업,"전자부품용 와이어, 케이블용 와이어 등",2025-06-02,12월,정민호,http://www.kistron.com/,경기도
1,코스닥,신한제16호스팩,49607,금융 지원 서비스업,기타금융서비스(기업합병),2025-05-29,12월,김종환,,서울특별시
2,코스닥,인투셀,28784,자연과학 및 공학 연구개발업,ADC 링커/톡신 플랫폼 기술,2025-05-23,12월,박태교,http://intocell.com,대전광역시
3,유가증권,달바글로벌,48365,기타 화학제품 제조업,"기초 화장품, 건강기능식품 등",2025-05-22,12월,반성연,http://dalbaglobal.com,서울특별시
4,코스닥,바이오비쥬,48946,기타 화학제품 제조업,스킨부스터 제품 및 필러,2025-05-20,12월,양준호,http://www.biobijou.co.kr/,경기도
...,...,...,...,...,...,...,...,...,...,...
2758,유가증권,유한양행,00010,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이사 조욱제,http://www.yuhan.co.kr,서울특별시
2759,유가증권,CJ대한통운,00012,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,"신영수, 민영학 (각자 대표)",http://www.cjlogistics.com,서울특별시
2760,유가증권,경방,00005,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
2761,유가증권,유수홀딩스,00070,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2762,유가증권,한진중공업홀딩스,00348,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,http://www.hhic-holdings.com,경기도

In [16]:
columns=soup.select_one(".list.type-00.tmt30")['summary'].split(", ")
columns.insert(0, '주식종목')
columns.insert(2, '종목코드')
print(columns)
df=pd.DataFrame(company_infos, columns=columns)
df

['주식종목', '회사명', '종목코드', '업종', '주요제품', '상장일', '결산월', '대표자명', '홈페이지', '지역']

,주식종목,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,코스닥,키스트론,47543,절연선 및 케이블 제조업,"전자부품용 와이어, 케이블용 와이어 등",2025-06-02,12월,정민호,http://www.kistron.com/,경기도
1,코스닥,신한제16호스팩,49607,금융 지원 서비스업,기타금융서비스(기업합병),2025-05-29,12월,김종환,,서울특별시
2,코스닥,인투셀,28784,자연과학 및 공학 연구개발업,ADC 링커/톡신 플랫폼 기술,2025-05-23,12월,박태교,http://intocell.com,대전광역시
3,유가증권,달바글로벌,48365,기타 화학제품 제조업,"기초 화장품, 건강기능식품 등",2025-05-22,12월,반성연,http://dalbaglobal.com,서울특별시
4,코스닥,바이오비쥬,48946,기타 화학제품 제조업,스킨부스터 제품 및 필러,2025-05-20,12월,양준호,http://www.biobijou.co.kr/,경기도
...,...,...,...,...,...,...,...,...,...,...
2758,유가증권,유한양행,00010,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이사 조욱제,http://www.yuhan.co.kr,서울특별시
2759,유가증권,CJ대한통운,00012,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,"신영수, 민영학 (각자 대표)",http://www.cjlogistics.com,서울특별시
2760,유가증권,경방,00005,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
2761,유가증권,유수홀딩스,00070,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2762,유가증권,한진중공업홀딩스,00348,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,http://www.hhic-holdings.com,경기도

# 데이터를 수집한 날짜를 포함해서 파일명을 만들고 저장하기

In [17]:
from datetime import datetime

In [18]:
today=datetime.now()
date=(f"{today.year}.{today.month:02d}.{today.day:02d}")

In [19]:
df.to_csv(f"./scraping_results/상장기업정보_{date}기준.csv", encoding='utf-8', index=False)

# 수집한  자료를 데이터베이스에 저장하기

In [20]:
# sql과 파이썬 연결
from sqlalchemy import create_engine, text #engine을 통해 db접속
import pymysql
pymysql.install_as_MySQLdb()

* sqlalchemy의 create_engine을 이용해서 mysql 서버에 접속
engine=create_engine('mysql+pymysql://userid:password@ip주소:port/데이터베이스이름)

In [21]:
# 데이터베이스에 미리 stock_info 파일 만들어놔야 함
engine=create_engine("mysql+pymysql://root:1234@localhost:3306/stock_info")
# create_engine에 있는 정보로 db 접속
conn=engine.connect()

In [22]:
#데이터프레임을 DB에 저장하기
#데이터프레임명.to_sql('테이블명')
df.to_sql(f"stock_company_info_{today}", con=conn, if_exists='replace', index=False)
conn.close()

# 판다스의 read_html를 이용해서 table 자료 한번에 가져오기
* 표 형식으로 되어있는 경우 read_html로 가져오면 바로 dataframe으로 가져올 수 있음
* but 정교한 처리는 어려워서, 링크 같은 거는 직접 추출해서 가져와야 됨

In [24]:
soup.select_one('table')

<table class="list type-00 tmt30" summary="회사명, 업종, 주요제품, 상장일, 결산월, 대표자명, 홈페이지, 지역">
<caption>목록</caption>
<colgroup>
<col width="*"/>
<col width="15%"/>
<col width="20%"/>
<col width="11%"/>
<col width="8%"/>
<col width="10%"/>
<col width="8%"/>
<col width="12%"/>
</colgroup>
<thead>
<tr class="first" id="title-contents">
</tr>
</thead>
<tbody>
<tr class="first">
<td class="first" title="(주)코오롱"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00202'); return false;" title="코오롱"> 코오롱</a> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1975-06-23</td>
<td class="txc">12월</td>
<td class="txc" title="안병덕, 이규호">안병덕..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.kolon.com" target="_blank" title="http://www.kolon.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="삼성전자(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00593'); return false;" title="삼성전자"> 삼성전자</a> <img alt="V100" class="vmiddle legend" src="/images/common/icn_t_v100.gif"/> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> <img alt="KTOP30" class="vmiddle legend" src="/images/common/icn_t_ktop.gif"/> </td>
<td class="textOverflow" title="통신 및 방송 장비 제조업">통신 및 방송 장비 제조업</td>
<td class="textOverflow" title="통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품,  전자부품 제조(디스플레이) 제품, 영상 및 음향기기 제조(영상기기) 제품 등">통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품,  전자부품 제조(디스플레이) 제품, 영상 및 음향기기 제조(영상기기) 제품 등</td>
<td class="txc">1975-06-11</td>
<td class="txc">12월</td>
<td class="txc" title="전영현">전영현</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.samsung.com/sec" target="_blank" title="http://www.samsung.com/sec"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)디에이치오토넥스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00030'); return false;" title="DH오토넥스"> DH오토넥스</a> </td>
<td class="textOverflow" title="자동차 신품 부품 제조업">자동차 신품 부품 제조업</td>
<td class="textOverflow" title="유,무선 통신장비">유,무선 통신장비</td>
<td class="txc">1975-06-09</td>
<td class="txc">12월</td>
<td class="txc" title="최준용">최준용</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.dayouplus.co.kr" target="_blank" title="http://www.dayouplus.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">전북특별자치도</td>
</tr>
<tr>
<td class="first" title="(주)BYC"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00146'); return false;" title="BYC"> BYC</a> </td>
<td class="textOverflow" title="봉제의복 제조업">봉제의복 제조업</td>
<td class="textOverflow" title="메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급">메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급</td>
<td class="txc">1975-06-02</td>
<td class="txc">12월</td>
<td class="txc" title="김 대 환">김 대..</td>
<td class="txc">
<a class="btn ico homepage" href="http://home.byc.co.kr" target="_blank" title="http://home.byc.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="케이지모빌리티(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00362'); return false;" title="KG모빌리티"> KG모빌리티</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="자동차용 엔진 및 자동차 제조업">자동차용 엔진 및 자동차 제조업</td>
<td class="textOverflow" title="자동차,자동차부품,차륜,정비 제조/도소매">자동차,자동차부품,차륜,정비 제조/도소매</td>
<td class="txc">1975-05-29</td>
<td class="txc">12월</td>
<td class="txc" title="곽재선, 황기영 (각자대표이사)">곽재선..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.kg-mobility.com" target="_blank" title="http://www.kg-mobility.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)SPC삼립"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00561'); return false;" title="SPC삼립"> SPC삼립</a> </td>
<td class="textOverflow" title="기타 식품 제조업">기타 식품 제조업</td>
<td class="textOverflow" title="빵,아이스크림,과자,케익,유산균음료,인스턴트식품,병조림,면류,식용유 제조,판매">빵,아이스크림,과자,케익,유산균음료,인스턴트식품,병조림,면류,식용유 제조,판매</td>
<td class="txc">1975-05-02</td>
<td class="txc">12월</td>
<td class="txc" title="황종현, 김범수(각자 대표이사)">황종현..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.spcsamlip.co.kr" target="_blank" title="http://www.spcsamlip.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="흥국화재해상보험(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00054'); return false;" title="흥국화재"> 흥국화재</a> </td>
<td class="textOverflow" title="보험업">보험업</td>
<td class="textOverflow" title="손해보험">손해보험</td>
<td class="txc">1974-12-05</td>
<td class="txc">12월</td>
<td class="txc" title="송윤상">송윤상</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.insurance.co.kr" target="_blank" title="http://www.insurance.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="일양약품(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00757'); return false;" title="일양약품"> 일양약품</a> </td>
<td class="textOverflow" title="의약품 제조업">의약품 제조업</td>
<td class="textOverflow" title="일반의약품(원비디,영비천,아진탈,디세텔,노루모산),항암제(베타-이뮤난),전문의약품 제조,판매,수출입">일반의약품(원비디,영비천,아진탈,디세텔,노루모산),항암제(베타-이뮤난),전문의약품 제조,판매,수출입</td>
<td class="txc">1974-08-28</td>
<td class="txc">12월</td>
<td class="txc" title="김동연, 정유석">김동연..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ilyang.co.kr" target="_blank" title="http://www.ilyang.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)한진"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00232'); return false;" title="한진"> 한진</a> </td>
<td class="textOverflow" title="도로 화물 운송업">도로 화물 운송업</td>
<td class="textOverflow" title="포장화물,택배산업,항만하역,고속버스사업,운수보관">포장화물,택배산업,항만하역,고속버스사업,운수보관</td>
<td class="txc">1974-08-12</td>
<td class="txc">12월</td>
<td class="txc" title="노삼석">노삼석</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hanjin.com" target="_blank" title="http://www.hanjin.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="한국수출포장공업(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00220'); return false;" title="한국수출포장공업"> 한국수출포장공업</a> </td>
<td class="textOverflow" title="골판지, 종이 상자 및 종이용기 제조업">골판지, 종이 상자 및 종이용기 제조업</td>
<td class="textOverflow" title="골판지상자,골판지원지 제조,판매">골판지상자,골판지원지 제조,판매</td>
<td class="txc">1974-06-28</td>
<td class="txc">12월</td>
<td class="txc" title="대표이사 회장 허용삼
대표이사 사장 허정훈(각자대표이사)">대표이..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.keppack.co.kr" target="_blank" title="http://www.keppack.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="현대자동차(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00538'); return false;" title="현대자동차"> 현대자동차</a> <img alt="V100" class="vmiddle legend" src="/images/common/icn_t_v100.gif"/> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> <img alt="KTOP30" class="vmiddle legend" src="/images/common/icn_t_ktop.gif"/> </td>
<td class="textOverflow" title="자동차용 엔진 및 자동차 제조업">자동차용 엔진 및 자동차 제조업</td>
<td class="textOverflow" title="자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업">자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업</td>
<td class="txc">1974-06-28</td>
<td class="txc">12월</td>
<td class="txc" title="정의선, 이동석, 무뇨스 바르셀로 호세 안토니오(각자 대표이사)">정의선..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hyundai.com" target="_blank" title="http://www.hyundai.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)모나미"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00536'); return false;" title="모나미"> 모나미</a> </td>
<td class="textOverflow" title="생활용품 도매업">생활용품 도매업</td>
<td class="textOverflow" title="BP153(BALL POINT PEN), P-3000(PLUS PEN), 유성매직, 보드마카, 네임펜, PARKER, WARTERMAN, 색연필">BP153(BALL POINT PEN), P-3000(PLUS PEN), 유성매직, 보드마카, 네임펜, PARKER, WARTERMAN, 색연필</td>
<td class="txc">1974-06-26</td>
<td class="txc">12월</td>
<td class="txc" title="송하경">송하경</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.monami.com" target="_blank" title="http://www.monami.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="한화솔루션(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00983'); return false;" title="한화솔루션"> 한화솔루션</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기초 화학물질 제조업">기초 화학물질 제조업</td>
<td class="textOverflow" title="합성수지,유화부문(LDPE,LLDPE)제품 제조,플라스틱가공품(PVC),CA,무기화학제품,부동산업">합성수지,유화부문(LDPE,LLDPE)제품 제조,플라스틱가공품(PVC),CA,무기화학제품,부동산업</td>
<td class="txc">1974-06-19</td>
<td class="txc">12월</td>
<td class="txc" title="남정운, 홍정권, 김동관">남정운..</td>
<td class="txc">
<a class="btn ico homepage" href="http://hcc.hanwha.co.kr" target="_blank" title="http://hcc.hanwha.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="아세아(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00203'); return false;" title="아세아"> 아세아</a> </td>
<td class="textOverflow" title="회사 본부 및 경영 컨설팅 서비스업">회사 본부 및 경영 컨설팅 서비스업</td>
<td class="textOverflow" title="회사본부,지주회사 및 경영컨설팅 서비스업">회사본부,지주회사 및 경영컨설팅 서비스업</td>
<td class="txc">1974-06-03</td>
<td class="txc">12월</td>
<td class="txc" title="이훈범, 오기호">이훈범..</td>
<td class="txc">
<a class="btn ico homepage" href="http://asiaholdings.co.kr" target="_blank" title="http://asiaholdings.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)카프로"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00638'); return false;" title="카프로"> 카프로</a> </td>
<td class="textOverflow" title="기초 화학물질 제조업">기초 화학물질 제조업</td>
<td class="textOverflow" title="카프로락탐,유안비료 제조">카프로락탐,유안비료 제조</td>
<td class="txc">1974-05-28</td>
<td class="txc">12월</td>
<td class="txc" title="박성명">박성명</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hcccapro.co.kr" target="_blank" title="http://www.hcccapro.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">울산광역시</td>
</tr>
<tr>
<td class="first" title="롯데지주(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00499'); return false;" title="롯데지주"> 롯데지주</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1974-02-16</td>
<td class="txc">12월</td>
<td class="txc" title="신동빈,이동우">신동빈..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.lotte.co.kr" target="_blank" title="http://www.lotte.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="대한방직(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00107'); return false;" title="대한방직"> 대한방직</a> </td>
<td class="textOverflow" title="직물직조 및 직물제품 제조업">직물직조 및 직물제품 제조업</td>
<td class="textOverflow" title="면사,화섬사,면직물 제조,판매,건설">면사,화섬사,면직물 제조,판매,건설</td>
<td class="txc">1973-12-28</td>
<td class="txc">12월</td>
<td class="txc" title="설 범, 김 인호">설 범..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.thtc.co.kr" target="_blank" title="http://www.thtc.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="서울식품공업(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00441'); return false;" title="서울식품공업"> 서울식품공업</a> </td>
<td class="textOverflow" title="기타 식품 제조업">기타 식품 제조업</td>
<td class="textOverflow" title="빵,스넥,마아가린,유지류,사료 제조,도매">빵,스넥,마아가린,유지류,사료 제조,도매</td>
<td class="txc">1973-12-28</td>
<td class="txc">12월</td>
<td class="txc" title="서성훈">서성훈</td>
<td class="txc">
<a class="btn ico homepage" href="http://seoul-food.co.kr" target="_blank" title="http://seoul-food.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">충청북도</td>
</tr>
<tr>
<td class="first" title="(주)아이에이치큐"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00356'); return false;" title="아이에이치큐"> 아이에이치큐</a> <img alt="관리종목" class="vmiddle legend" src="/images/common/icn_t_kwan.gif"/> </td>
<td class="textOverflow" title="영화, 비디오물, 방송프로그램 제작 및 배급업">영화, 비디오물, 방송프로그램 제작 및 배급업</td>
<td class="textOverflow" title="매니지먼트, 음반, 드라마 제작, 유료방송, 프로그램 공급, 광고대행">매니지먼트, 음반, 드라마 제작, 유료방송, 프로그램 공급, 광고대행</td>
<td class="txc">1973-12-18</td>
<td class="txc">12월</td>
<td class="txc" title="오준">오준</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ihq.co.kr" target="_blank" title="http://www.ihq.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)LS네트웍스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00068'); return false;" title="LS네트웍스"> LS네트웍스</a> </td>
<td class="textOverflow" title="상품 종합 도매업">상품 종합 도매업</td>
<td class="textOverflow" title="혁화,의류,등산용품 도매,제조/부동산 임대">혁화,의류,등산용품 도매,제조/부동산 임대</td>
<td class="txc">1973-11-15</td>
<td class="txc">12월</td>
<td class="txc" title="문성준">문성준</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.lsnetworks.co.kr" target="_blank" title="http://www.lsnetworks.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경상남도</td>
</tr>
<tr>
<td class="first" title="금호전기(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00121'); return false;" title="금호전기"> 금호전기</a> </td>
<td class="textOverflow" title="전구 및 조명장치 제조업">전구 및 조명장치 제조업</td>
<td class="textOverflow" title="형광등,백열전구,전구식현광등,실드빔(차량용전조) 제조,판매">형광등,백열전구,전구식현광등,실드빔(차량용전조) 제조,판매</td>
<td class="txc">1973-11-15</td>
<td class="txc">12월</td>
<td class="txc" title="이홍민">이홍민</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.khe.co.kr" target="_blank" title="http://www.khe.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="하이트진로홀딩스(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00014'); return false;" title="하이트진로홀딩스"> 하이트진로홀딩스</a> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1973-09-19</td>
<td class="txc">12월</td>
<td class="txc" title="김인규">김인규</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hitejinroholdings.com" target="_blank" title="http://www.hitejinroholdings.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)노루홀딩스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00032'); return false;" title="노루홀딩스"> 노루홀딩스</a> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주사업">지주사업</td>
<td class="txc">1973-08-10</td>
<td class="txc">12월</td>
<td class="txc" title="한영재,김용기">한영재..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.norooholdings.co.kr" target="_blank" title="http://www.norooholdings.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="기아(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00027'); return false;" title="기아"> 기아</a> <img alt="V100" class="vmiddle legend" src="/images/common/icn_t_v100.gif"/> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> <img alt="KTOP30" class="vmiddle legend" src="/images/common/icn_t_ktop.gif"/> </td>
<td class="textOverflow" title="자동차용 엔진 및 자동차 제조업">자동차용 엔진 및 자동차 제조업</td>
<td class="textOverflow" title="승용차,중대형버스,트럭,민수특수차량,군수차량 제조,판매,정비">승용차,중대형버스,트럭,민수특수차량,군수차량 제조,판매,정비</td>
<td class="txc">1973-07-21</td>
<td class="txc">12월</td>
<td class="txc" title="송호성,최준영(각자 대표이사)">송호성..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.kia.co.kr" target="_blank" title="http://www.kia.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)효성"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00480'); return false;" title="효성"> 효성</a> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="스판덱스,합성원사,나일론,폴리에스터,타이어코드지,PET병,수지제품,중전기제품(변압기,차단기),사무용기계,컴퓨터 제조/건축공사">스판덱스,합성원사,나일론,폴리에스터,타이어코드지,PET병,수지제품,중전기제품(변압기,차단기),사무용기계,컴퓨터 제조/건축공사</td>
<td class="txc">1973-06-30</td>
<td class="txc">12월</td>
<td class="txc" title="조현준, 황윤언">조현준..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hyosung.com" target="_blank" title="http://www.hyosung.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="CJ(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00104'); return false;" title="CJ"> CJ</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1973-06-29</td>
<td class="txc">12월</td>
<td class="txc" title="손경식, 김홍기">손경식..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.cj.net" target="_blank" title="http://www.cj.net"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>

In [26]:
from io import StringIO

In [27]:
pd.read_html(StringIO(r.text))[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,코오롱,기타 금융업,지주회사,1975-06-23,12월,안병덕..,홈페이지 보기,경기도
1,삼성전자,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,전영현,홈페이지 보기,경기도
2,DH오토넥스,자동차 신품 부품 제조업,"유,무선 통신장비",1975-06-09,12월,최준용,홈페이지 보기,전북특별자치도
3,BYC,봉제의복 제조업,"메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급",1975-06-02,12월,김 대..,홈페이지 보기,서울특별시
4,KG모빌리티,자동차용 엔진 및 자동차 제조업,"자동차,자동차부품,차륜,정비 제조/도소매",1975-05-29,12월,곽재선..,홈페이지 보기,경기도
...,...,...,...,...,...,...,...,...
58,유한양행,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이..,홈페이지 보기,서울특별시
59,CJ대한통운,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,신영수..,홈페이지 보기,서울특별시
60,경방,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준,..",홈페이지 보기,서울특별시
61,유수홀딩스,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,홈페이지 보기,서울특별시
62,한진중공업홀딩스,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,홈페이지 보기,경기도

In [28]:
pd.read_html(r.text)[0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_19108\1880019241.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(r.text)[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,코오롱,기타 금융업,지주회사,1975-06-23,12월,안병덕..,홈페이지 보기,경기도
1,삼성전자,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,전영현,홈페이지 보기,경기도
2,DH오토넥스,자동차 신품 부품 제조업,"유,무선 통신장비",1975-06-09,12월,최준용,홈페이지 보기,전북특별자치도
3,BYC,봉제의복 제조업,"메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급",1975-06-02,12월,김 대..,홈페이지 보기,서울특별시
4,KG모빌리티,자동차용 엔진 및 자동차 제조업,"자동차,자동차부품,차륜,정비 제조/도소매",1975-05-29,12월,곽재선..,홈페이지 보기,경기도
...,...,...,...,...,...,...,...,...
58,유한양행,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이..,홈페이지 보기,서울특별시
59,CJ대한통운,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,신영수..,홈페이지 보기,서울특별시
60,경방,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준,..",홈페이지 보기,서울특별시
61,유수홀딩스,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,홈페이지 보기,서울특별시
62,한진중공업홀딩스,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,홈페이지 보기,경기도